### ISSUE TITLE
evolverMammals example fails with apptainer during progressive_workflow

### ISSUE THREAD

**Issue by k-hench** [ComparativeGenomicsToolkit/cactus#1004]
Hi :wave:

I feel like I must be doing some silly mistake here - but somehow I fail to run the `cactus` example snippet within `apptainer`: :raised_eyebrow:

```sh
# downloading the example seqdata config
wget https://raw.githubusercontent.com/ComparativeGenomicsToolkit/cactus/master/examples/evolverMammals.txt

# trying to run the example within apptainer
apptainer \
  run docker://quay.io/comparative-genomics-toolkit/cactus:v2.5.1 \
  cactus js evolverMammals.txt evolverMammals.hal &> cactus.log
```

I tried running this both on my laptop and our HPC and in both attempts the `progressive_workflow` jobs fail with 

```
OSError: [Errno 38] Function not implemented: '/run/lock/<...>'
```

Can someone point me to what I am doing wrong here? :flushed: 

---

(below, the log-file `cactus.log` from that run)

```
INFO:    Using cached SIF image
INFO:    underlay of /etc/localtime required more than 50 (81) bind mounts
[2023-04-28T18:13:25+0200] [MainThread] [I] [toil.statsAndLogging] Enabling realtime logging in Toil
[2023-04-28T18:13:25+0200] [MainThread] [I] [toil.statsAndLogging] Cactus Command: /home/cactus/cactus_env/bin/cactus js evolverMammals.txt evolverMammals.hal
[2023-04-28T18:13:25+0200] [MainThread] [I] [toil.statsAndLogging] Cactus Commit: 4823037fe5038c8d2a9dd29a159e153e74a1aab5
[2023-04-28T18:13:25+0200] [MainThread] [I] [toil.statsAndLogging] Tree: ((simHuman_chr6:0.144018,(simMouse_chr6:0.084509,simRat_chr6:0.091589)mr:0.271974)Anc1:0.020593,(simCow_chr6:0.18908,simDog_chr6:0.16303)Anc2:0.032898)Anc0;
[2023-04-28T18:13:25+0200] [MainThread] [I] [toil.statsAndLogging] Importing https://raw.githubusercontent.com/ComparativeGenomicsToolkit/cactusTestData/master/evolver/mammals/loci1/simCow.chr6
[2023-04-28T18:13:32+0200] [MainThread] [I] [toil.statsAndLogging] Importing https://raw.githubusercontent.com/ComparativeGenomicsToolkit/cactusTestData/master/evolver/mammals/loci1/simDog.chr6
[2023-04-28T18:13:32+0200] [MainThread] [I] [toil.statsAndLogging] Importing https://raw.githubusercontent.com/ComparativeGenomicsToolkit/cactusTestData/master/evolver/mammals/loci1/simHuman.chr6
[2023-04-28T18:13:33+0200] [MainThread] [I] [toil.statsAndLogging] Importing https://raw.githubusercontent.com/ComparativeGenomicsToolkit/cactusTestData/master/evolver/mammals/loci1/simMouse.chr6
[2023-04-28T18:13:33+0200] [MainThread] [I] [toil.statsAndLogging] Importing https://raw.githubusercontent.com/ComparativeGenomicsToolkit/cactusTestData/master/evolver/mammals/loci1/simRat.chr6
[2023-04-28T18:13:33+0200] [MainThread] [I] [toil.job] Saving graph of 1 jobs, 1 new
[2023-04-28T18:13:33+0200] [MainThread] [I] [toil.job] Processing job 'progressive_workflow' kind-progressive_workflow/instance-2e64c5y_ v0
[2023-04-28T18:13:33+0200] [MainThread] [I] [toil] Running Toil version 5.9.2-54bfe0b146b76ecc6221de384c255e1be89547c6 on host <hostname>.
[2023-04-28T18:13:33+0200] [MainThread] [I] [toil.realtimeLogger] Starting real-time logging.
[2023-04-28T18:13:34+0200] [MainThread] [I] [toil.leader] Issued job 'progressive_workflow' kind-progressive_workflow/instance-2e64c5y_ v1 with job batch system ID: 0 and disk: 2.0 Gi, memory: 2.0 Gi, cores: 1, accelerators: [], preemptible: False
Traceback (most recent call last):
  File "/home/cactus/cactus_env/bin/_toil_worker", line 8, in <module>
    sys.exit(main())
  File "/home/cactus/cactus_env/lib/python3.10/site-packages/toil/worker.py", line 725, in main
    exit_code = workerScript(jobStore, config, options.jobName, options.jobStoreID)
  File "/home/cactus/cactus_env/lib/python3.10/site-packages/toil/worker.py", line 228, in workerScript
    toil_coordination_dir = Toil.get_local_workflow_coordination_dir(config.workflowID, config.workDir, config.coordination_dir)
  File "/home/cactus/cactus_env/lib/python3.10/site-packages/toil/common.py", line 1453, in get_local_workflow_coordination_dir
    os.makedirs(subdir, exist_ok=True)
  File "/usr/lib/python3.10/os.py", line 225, in makedirs
    mkdir(name, mode)
OSError: [Errno 38] Function not implemented: '/run/lock/4eaa935a08e75227a870a51c18bd23fe'
[2023-04-28T18:13:35+0200] [Thread-1 (daddy)] [E] [toil.batchSystems.singleMachine] Got exit code 1 (indicating failure) from job _toil_worker progressive_workflow file:/<current wd>/js kind-progressive_workflow/instance-2e64c5y_.
[2023-04-28T18:13:35+0200] [MainThread] [W] [toil.leader] Job failed with exit value 1: 'progressive_workflow' kind-progressive_workflow/instance-2e64c5y_ v1
Exit reason: None
[2023-04-28T18:13:35+0200] [MainThread] [W] [toil.leader] No log file is present, despite job failing: 'progressive_workflow' kind-progressive_workflow/instance-2e64c5y_ v1
[2023-04-28T18:13:35+0200] [MainThread] [W] [toil.job] Due to failure we are reducing the remaining try count of job 'progressive_workflow' kind-progressive_workflow/instance-2e64c5y_ v1 with ID kind-progressive_workflow/instance-2e64c5y_ to 1
[2023-04-28T18:13:35+0200] [MainThread] [I] [toil.leader] 0 jobs are running, 0 jobs are issued and waiting to run
[2023-04-28T18:13:35+0200] [MainThread] [I] [toil.leader] Issued job 'progressive_workflow' kind-progressive_workflow/instance-2e64c5y_ v2 with job batch system ID: 1 and disk: 2.0 Gi, memory: 2.0 Gi, cores: 1, accelerators: [], preemptible: False
Traceback (most recent call last):
  File "/home/cactus/cactus_env/bin/_toil_worker", line 8, in <module>
    sys.exit(main())
  File "/home/cactus/cactus_env/lib/python3.10/site-packages/toil/worker.py", line 725, in main
    exit_code = workerScript(jobStore, config, options.jobName, options.jobStoreID)
  File "/home/cactus/cactus_env/lib/python3.10/site-packages/toil/worker.py", line 228, in workerScript
    toil_coordination_dir = Toil.get_local_workflow_coordination_dir(config.workflowID, config.workDir, config.coordination_dir)
  File "/home/cactus/cactus_env/lib/python3.10/site-packages/toil/common.py", line 1453, in get_local_workflow_coordination_dir
    os.makedirs(subdir, exist_ok=True)
  File "/usr/lib/python3.10/os.py", line 225, in makedirs
    mkdir(name, mode)
OSError: [Errno 38] Function not implemented: '/run/lock/4eaa935a08e75227a870a51c18bd23fe'
[2023-04-28T18:13:35+0200] [Thread-1 (daddy)] [E] [toil.batchSystems.singleMachine] Got exit code 1 (indicating failure) from job _toil_worker progressive_workflow file:/<current wd>/js kind-progressive_workflow/instance-2e64c5y_.
[2023-04-28T18:13:35+0200] [MainThread] [W] [toil.leader] Job failed with exit value 1: 'progressive_workflow' kind-progressive_workflow/instance-2e64c5y_ v2
Exit reason: None
[2023-04-28T18:13:35+0200] [MainThread] [W] [toil.leader] No log file is present, despite job failing: 'progressive_workflow' kind-progressive_workflow/instance-2e64c5y_ v2
[2023-04-28T18:13:35+0200] [MainThread] [W] [toil.job] Due to failure we are reducing the remaining try count of job 'progressive_workflow' kind-progressive_workflow/instance-2e64c5y_ v2 with ID kind-progressive_workflow/instance-2e64c5y_ to 0
[2023-04-28T18:13:35+0200] [MainThread] [W] [toil.leader] Job 'progressive_workflow' kind-progressive_workflow/instance-2e64c5y_ v3 is completely failed
[2023-04-28T18:13:39+0200] [MainThread] [I] [toil.leader] Finished toil run with 1 failed jobs.
[2023-04-28T18:13:39+0200] [MainThread] [I] [toil.leader] Failed jobs at end of the run: 'progressive_workflow' kind-progressive_workflow/instance-2e64c5y_ v3
[2023-04-28T18:13:39+0200] [MainThread] [I] [toil.realtimeLogger] Stopping real-time logging server.
[2023-04-28T18:13:39+0200] [MainThread] [I] [toil.realtimeLogger] Joining real-time logging server thread.
Traceback (most recent call last):
  File "/home/cactus/cactus_env/lib/python3.10/site-packages/toil/common.py", line 1030, in start
    return self._runMainLoop(rootJobDescription)
  File "/home/cactus/cactus_env/lib/python3.10/site-packages/toil/common.py", line 1475, in _runMainLoop
    jobCache=self._jobCache).run()
  File "/home/cactus/cactus_env/lib/python3.10/site-packages/toil/leader.py", line 330, in run
    raise FailedJobsException(self.jobStore, failed_jobs, exit_code=self.recommended_fail_exit_code)
toil.leader.FailedJobsException: The job store '/<current wd>/js' contains 1 failed jobs: 'progressive_workflow' kind-progressive_workflow/instance-2e64c5y_ v3

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/cactus/cactus_env/bin/cactus", line 8, in <module>
    sys.exit(main())
  File "/home/cactus/cactus_env/lib/python3.10/site-packages/cactus/progressive/cactus_progressive.py", line 400, in main
    hal_id = toil.start(Job.wrapJobFn(progressive_workflow, options, config_node, mc_tree, og_map, input_seq_id_map))
  File "/home/cactus/cactus_env/lib/python3.10/site-packages/toil/common.py", line 1032, in start
    self._shutdownBatchSystem()
  File "/home/cactus/cactus_env/lib/python3.10/site-packages/toil/common.py", line 1481, in _shutdownBatchSystem
    self._batchSystem.shutdown()
  File "/home/cactus/cactus_env/lib/python3.10/site-packages/toil/batchSystems/singleMachine.py", line 805, in shutdown
    BatchSystemSupport.workerCleanup(self.workerCleanupInfo)
  File "/home/cactus/cactus_env/lib/python3.10/site-packages/toil/batchSystems/abstractBatchSystem.py", line 428, in workerCleanup
    coordination_dir = Toil.get_local_workflow_coordination_dir(info.workflow_id, info.work_dir, info.coordination_dir)
  File "/home/cactus/cactus_env/lib/python3.10/site-packages/toil/common.py", line 1453, in get_local_workflow_coordination_dir
    os.makedirs(subdir, exist_ok=True)
  File "/usr/lib/python3.10/os.py", line 225, in makedirs
    mkdir(name, mode)
OSError: [Errno 38] Function not implemented: '/run/lock/4eaa935a08e75227a870a51c18bd23fe'
```

**Comment by glennhickey** [comment]
I don't know what an "apptainer" is, but there's an example in the manual of [using Docker](https://github.com/ComparativeGenomicsToolkit/cactus/blob/master/doc/progressive.md#using-docker).  In that case it's very important to use `-v` to get the directories straight.
