### ISSUE TITLE
Cactus-graphmap-join error when using the --gfa full option

### ISSUE THREAD

**Issue by NMarthe** [ComparativeGenomicsToolkit/cactus#1005]
Hello, 
I'm trying to make a complete pangenome graph using the --gfa full option.
I previously ran the command without this option, only with "--gfa", and it worked perfectly. 
But with the option, I get a similar error message during the last step of the pipeline, whether I use the cactus-pangneome or the cactus-graphmap-join command : 

With cactus-graphmap-join :
```
cactus-graphmap-join /scratch/AsianRiceGenomeGraph/pangenome/chr10_steps_full/js5 --vg /scratch/AsianRiceGenomeGraph/pangenome/chr10_steps_full/step_minigraph_chr10.vg --hal /scratch/AsianRiceGenomeGraph/pangenome/chr10_steps_full step_minigraph_chr10.hal --outDir /scratch/AsianRiceGenomeGraph/pangenome/chr10_steps_full/ --outName graphe_steps_chr10 --reference IRGSP-1_0 --workDir /scratch/AsianRiceGenomeGraph/pangenome/chr10_steps_full/workDir --clean never --cleanWorkDir never --gfa full
```
```
[2023-04-21T17:43:14+0200] [MainThread] [I] [toil-rt] 2023-04-21 17:43:14.295286: Running the command: "vg snarls /scratch/AsianRiceGenomeGraph/pangenome/chr10_steps_full/workDir/7191491d638a50b2a7b3182c9c9c61c1/94fe/8459/tmplxa71ebw/full.merged.gbz -T -t 88"
[2023-04-21T17:44:00+0200] [MainThread] [I] [toil-rt] 2023-04-21 17:44:00.437111: Successfully ran: "vg snarls /scratch/AsianRiceGenomeGraph/pangenome/chr10_steps_full/workDir/7191491d638a50b2a7b3182c9c9c61c1/94fe/8459/tmplxa71ebw/full.merged.gbz -T -t 88" in 46.1401 seconds and 2.0 Gi memory
[2023-04-21T17:44:10+0200] [MainThread] [I] [toil.leader] Finished toil run successfully.
[2023-04-21T17:44:10+0200] [MainThread] [I] [toil.realtimeLogger] Stopping real-time logging server.
[2023-04-21T17:44:10+0200] [MainThread] [I] [toil.realtimeLogger] Joining real-time logging server thread.
Traceback (most recent call last):
  File "/home/cactus/cactus_env/bin/cactus-graphmap-join", line 8, in <module>
    sys.exit(main())
  File "/home/cactus/cactus_env/lib/python3.10/site-packages/cactus/refmap/cactus_graphmap_join.py", line 98, in main
    graphmap_join(options)
  File "/home/cactus/cactus_env/lib/python3.10/site-packages/cactus/refmap/cactus_graphmap_join.py", line 240, in graphmap_join
    export_join_data(toil, options, wf_output[0], wf_output[1], wf_output[2], wf_output[3], wf_output[4])
  File "/home/cactus/cactus_env/lib/python3.10/site-packages/cactus/refmap/cactus_graphmap_join.py", line 758, in export_join_data
    for stats_file in clip_stats.keys():
AttributeError: 'NoneType' object has no attribute 'keys'
```

With cactus-pangenome :
```
cactus-pangenome /scratch/AsianRiceGenomeGraph/pangenome/chr102/jobstore /scratch/AsianRiceGenomeGraph/data_chr10/seqfile --outDir /scratch/AsianRiceGenomeGraph/pangenome/chr102 --outName platGB2_r426_chr10_cactus --reference IRGSP-1_0 --workDir /scratch/AsianRiceGenomeGraph/pangenome/chr102/workDir --mapCores 12 --gfa full
```
```
[2023-04-21T06:54:55+0200] [MainThread] [I] [toil.leader] Issued job 'export_join_wrapper' kind-export_join_wrapper/instance-mua5f30f v1 with job batch system ID: 108 and disk: 2.0 Gi, memory: 2.0 Gi, co
res: 1, accelerators: [], preemptible: False
[2023-04-21T06:54:55+0200] [MainThread] [I] [toil.worker] Redirecting logging to /scratch/AsianRiceGenomeGraph/pangenome/chr102/workDir/2f6bce300a8c5d179bdbb854860cf818/f46c/worker_log.txt
[2023-04-21T06:54:56+0200] [Thread-1 (daddy)] [E] [toil.batchSystems.singleMachine] Got exit code 1 (indicating failure) from job _toil_worker export_join_wrapper file:/scratch/AsianRiceGenomeGraph/pange
nome/chr102/jobstore kind-export_join_wrapper/instance-mua5f30f.
[2023-04-21T06:54:56+0200] [MainThread] [W] [toil.leader] Job failed with exit value 1: 'export_join_wrapper' kind-export_join_wrapper/instance-mua5f30f v1
Exit reason: None
[2023-04-21T06:54:56+0200] [MainThread] [W] [toil.leader] The job seems to have left a log file, indicating failure: 'export_join_wrapper' kind-export_join_wrapper/instance-mua5f30f v2
[2023-04-21T06:54:56+0200] [MainThread] [W] [toil.leader] Log from job "kind-export_join_wrapper/instance-mua5f30f" follows:
=========>
        [2023-04-21T06:54:55+0200] [MainThread] [I] [toil.worker] ---TOIL WORKER OUTPUT LOG---
        [2023-04-21T06:54:55+0200] [MainThread] [I] [toil] Running Toil version 5.9.2-54bfe0b146b76ecc6221de384c255e1be89547c6 on host node5.alineos.net.
        [2023-04-21T06:54:55+0200] [MainThread] [I] [toil.worker] Working on job 'export_join_wrapper' kind-export_join_wrapper/instance-mua5f30f v1
        [2023-04-21T06:54:56+0200] [MainThread] [I] [toil.worker] Loaded body Job('export_join_wrapper' kind-export_join_wrapper/instance-mua5f30f v1) from description 'export_join_wrapper' kind-export_j
oin_wrapper/instance-mua5f30f v1
        Traceback (most recent call last):
          File "/home/cactus/cactus_env/lib/python3.10/site-packages/toil/worker.py", line 403, in workerScript
            job._runner(jobGraph=None, jobStore=jobStore, fileStore=fileStore, defer=defer)
          File "/home/cactus/cactus_env/lib/python3.10/site-packages/toil/job.py", line 2743, in _runner
            returnValues = self._run(jobGraph=None, fileStore=fileStore)
          File "/home/cactus/cactus_env/lib/python3.10/site-packages/toil/job.py", line 2660, in _run
            return self.run(fileStore)
          File "/home/cactus/cactus_env/lib/python3.10/site-packages/toil/job.py", line 2888, in run
            rValue = userFunction(*((self,) + tuple(self._args)), **self._kwargs)
          File "/home/cactus/cactus_env/lib/python3.10/site-packages/cactus/refmap/cactus_pangenome.py", line 282, in export_join_wrapper
            export_join_data(job.fileStore, options, wf_output[0], wf_output[1], wf_output[2], wf_output[3], wf_output[4])
          File "/home/cactus/cactus_env/lib/python3.10/site-packages/cactus/refmap/cactus_graphmap_join.py", line 758, in export_join_data
            for stats_file in clip_stats.keys():
        AttributeError: 'NoneType' object has no attribute 'keys'
        [2023-04-21T06:54:56+0200] [MainThread] [E] [toil.worker] Exiting the worker because of a failed job on host node5.alineos.net
<=========
```

Thank you for your help !

**Comment by glennhickey** [comment]
Thanks for pointing out this dumb bug.  I'll fix it very soon.  In the meantime, it looks like you can work around it by using `--gfa clip full`.
