### ISSUE TITLE
Why does using " --chrom-vg" cause errors?

### ISSUE THREAD

**Issue by xuxingyubio** [ComparativeGenomicsToolkit/cactus#1018]
My code is as follows：
cactus-pangenome ./js grch38_pan.seqfile --reference GRCh38 --outDir ./grch38_pan --outName grch38_pan --gbz --giraffe --vcf --chrom-vg  --refContigs $(for i in `seq 22`; do printf "chr$i "; done ; echo "chrX chrY chrM") --otherContig chrOther --maxCores 40 --indexCores 20 --mapCores 6 --permissiveContigFilter 0.05 --workDir work_final  --logFile grch38_pan.log
error is as follows:
join_wrapper' kind-export_join_wrapper/instance-t9ez1nr2 v4
        Traceback (most recent call last):
          File "/home/users/xyxu/pangenome/demo/cactus-bin-v2.5.1/cactus_env/lib/python3.9/site-packages/toil/worker.py", line 403, in workerScript
            job._runner(jobGraph=None, jobStore=jobStore, fileStore=fileStore, defer=defer)
          File "/home/users/xyxu/pangenome/demo/cactus-bin-v2.5.1/cactus_env/lib/python3.9/site-packages/toil/job.py", line 2743, in _runner
            returnValues = self._run(jobGraph=None, fileStore=fileStore)
          File "/home/users/xyxu/pangenome/demo/cactus-bin-v2.5.1/cactus_env/lib/python3.9/site-packages/toil/job.py", line 2660, in _run
            return self.run(fileStore)
          File "/home/users/xyxu/pangenome/demo/cactus-bin-v2.5.1/cactus_env/lib/python3.9/site-packages/toil/job.py", line 2888, in run
            rValue = userFunction(*((self,) + tuple(self._args)), **self._kwargs)
          File "/home/users/xyxu/pangenome/demo/cactus-bin-v2.5.1/cactus_env/lib/python3.9/site-packages/cactus/refmap/cactus_pangenome.py", line 288, in export_join_wrapper
            export_join_data(job.fileStore, options, wf_output[0], wf_output[1], wf_output[2], wf_output[3], wf_output[4])
          File "/home/users/xyxu/pangenome/demo/cactus-bin-v2.5.1/cactus_env/lib/python3.9/site-packages/cactus/refmap/cactus_graphmap_join.py", line 753, in export_join_data
            name = os.path.splitext(vg_path)[0] + '.vg'
          File "/home/users/xyxu/miniconda3/lib/python3.9/posixpath.py", line 118, in splitext
            p = os.fspath(p)
        TypeError: expected str, bytes or os.PathLike object, not NoneType
        [2023-05-17T22:34:42+0800] [MainThread] [E] [toil.worker] Exiting the worker because of a failed job on host node13
If I don't use " --chrom-vg", it can run successfully.

**Comment by glennhickey** [comment]
Please try the latest release. It should be fixed there

**Comment by xuxingyubio** [comment]
I'm sorry to bother you again.
 When I use 'cactus-graphmap', it displays "cactus graphmap: error: unrecognized arguments: -- base -- maxLen 100000"
how can I use this parameter?
The version is Cactus 2.5.2

**Comment by glennhickey** [comment]
Those parameters are not longer in `cactus-graphmap`: you must run without them.
