### ISSUE TITLE
cactus fails writing installed cactus_config.xml even if --configFile specified

### ISSUE THREAD

**Issue by michaelkarlcoleman** [ComparativeGenomicsToolkit/cactus#102]
It appears that cactus is trying to write an installed config file, even when another is specified with `--configFile`.  This doesn't work with a shared installation, of course.

Is this a bug, or am I doing something wrong?  I'd prefer not to force each user to install their own copy of cactus...

Mike

Command:
```
cactus file:./jobStore examples/evolverMammals.txt examples/evolverMammals.hal \
       --configFile=my_cactus_progressive_config.xml \
       --root mr \
       --batchSystem Mesos \
       --mesosMaster $master:$port \
       --binariesMode singularity \
       --stats \
       --disableCaching \
       --workDir $(pwd -P)/workDir \
#
```

Tail of output:
```
...
Done. Container is at: ./cactus.img
INFO:cactus.progressive.projectWrapper:Using config from path my_cactus_progressive_config.xml.
simHuman_chr6 True False
simMouse_chr6 True True
simRat_chr6 True True
mr False True
Anc1 False False
simCow_chr6 True False
simDog_chr6 True False
Anc2 False False
Anc0 False False
['Anc1', 'Anc2', 'Anc0']
Traceback (most recent call last):
  File "/packages/miniconda/20190102/envs/cactus/bin/cactus", line 10, in <module>
    sys.exit(main())
  File "/packages/miniconda/20190102/envs/cactus/lib/python2.7/site-packages/cactus/progressive/cactus_progressive.py", line 471, in main
    runCactusProgressive(options)
  File "/packages/miniconda/20190102/envs/cactus/lib/python2.7/site-packages/cactus/progressive/cactus_progressive.py", line 483, in runCactusProgressive
    projWrapper.writeXml()
  File "/packages/miniconda/20190102/envs/cactus/lib/python2.7/site-packages/cactus/progressive/projectWrapper.py", line 81, in writeXml
    root=self.options.root)
  File "/packages/miniconda/20190102/envs/cactus/lib/python2.7/site-packages/cactus/progressive/cactus_createMultiCactusProject.py", line 267, in runCreateMultiCactusProject
    createFileStructure(mcProj, expTemplate, confTemplate, options)
  File "/packages/miniconda/20190102/envs/cactus/lib/python2.7/site-packages/cactus/progressive/cactus_createMultiCactusProject.py", line 220, in createFileStructure
    config.writeXML(exp.getConfigPath())
  File "/packages/miniconda/20190102/envs/cactus/lib/python2.7/site-packages/cactus/shared/configWrapper.py", line 34, in writeXML
    xmlFile = open(path, "w")
IOError: [Errno 13] Permission denied: '/packages/miniconda/20190102/envs/cactus/lib/python2.7/site-packages/cactus/cactus_config.xml'
```

**Comment by michaelkarlcoleman** [comment]
Following up, at least for this example, it appears that the write isn't doing anything useful.  It's just writing the same contents into the file.

At present, I'm "fixing" this by commenting out this line:
https://github.com/ComparativeGenomicsToolkit/cactus/blob/master/src/cactus/progressive/cactus_createMultiCactusProject.py#L220

Hard to tell, but I wonder whether that statement ever does anything useful.

**Comment by jasonsydes** [comment]
I observed the same thing as @michaelkarlcoleman, as I had removed write permissions from my cactus install as a safety precaution, and watched as cactus crashed complaining of not being able to write to the installed cactus config file.

**Comment by diekhans** [comment]
this is fixed in the python 3 version
