### ISSUE TITLE
ERROR: Exception: Traceback (most recent call last):   

### ISSUE THREAD

**Issue by annabananakobana** [ComparativeGenomicsToolkit/cactus#104]
Trying to install Cactus and dependencies in a server dir and using terminal on Mac.

module purge
module load Python/2.7.16-gimkl-2018b
pip install virtualenv
pip install virtualenv --user
virtualenv cactus_env
source cactus_env/bin/activate
virtualenv cactus_env

The following error was returning upon running "pip install --upgrade toil[all]"...

Processing /home/user/.cache/pip/wheels/99/c4/ed/1b64d2d5809e60d5a3685530432f6159d6a9959739facb61f2/dill-0.2.7.1-cp27-none-any.whl
ERROR: Exception:
Traceback (most recent call last):
  File "/scale_wlg_persistent/filesets/project/username/cactus_env/lib/python2.7/site-packages/pip/_internal/cli/base_command.py", line 153, in _main
    status = self.run(options, args)
  File "/scale_wlg_persistent/filesets/project/username/cactus_env/lib/python2.7/site-packages/pip/_internal/commands/install.py", line 381, in run
    resolver.resolve(requirement_set)
  File "/scale_wlg_persistent/filesets/project/username/cactus_env/lib/python2.7/site-packages/pip/_internal/legacy_resolve.py", line 201, in resolve
    self._resolve_one(requirement_set, req)
  File "/scale_wlg_persistent/filesets/project/username/cactus_env/lib/python2.7/site-packages/pip/_internal/legacy_resolve.py", line 365, in _resolve_one
    abstract_dist = self._get_abstract_dist_for(req_to_install)
  File "/scale_wlg_persistent/filesets/project/username/cactus_env/lib/python2.7/site-packages/pip/_internal/legacy_resolve.py", line 313, in _get_abstract_dist_for
    req, self.session, self.finder, self.require_hashes
  File "/scale_wlg_persistent/filesets/project/username/cactus_env/lib/python2.7/site-packages/pip/_internal/operations/prepare.py", line 194, in prepare_linked_requirement
    progress_bar=self.progress_bar
  File "/scale_wlg_persistent/filesets/project/username/cactus_env/lib/python2.7/site-packages/pip/_internal/download.py", line 452, in unpack_url
    unpack_file_url(link, location, download_dir, hashes=hashes)
  File "/scale_wlg_persistent/filesets/project/username/cactus_env/lib/python2.7/site-packages/pip/_internal/download.py", line 416, in unpack_file_url
    unpack_file(from_path, location, content_type)
  File "/scale_wlg_persistent/filesets/project/username/cactus_env/lib/python2.7/site-packages/pip/_internal/utils/unpacking.py", line 252, in unpack_file
    flatten=not filename.endswith('.whl')
  File "/scale_wlg_persistent/filesets/project/username/cactus_env/lib/python2.7/site-packages/pip/_internal/utils/unpacking.py", line 114, in unzip_file
    zip = zipfile.ZipFile(zipfp, allowZip64=True)
  File "/opt/nesi/CS400_centos7_bdw/Python/2.7.16-gimkl-2018b/lib/python2.7/zipfile.py", line 793, in __init__
    self._RealGetContents()
  File "/opt/nesi/CS400_centos7_bdw/Python/2.7.16-gimkl-2018b/lib/python2.7/zipfile.py", line 834, in _RealGetContents
    raise BadZipfile, "File is not a zip file"
BadZipfile: File is not a zip file

**Comment by diekhans** [comment]
This looks like it could be a corruption of the pip toil download.

Try removing  ~/.cache/pip

**Comment by annabananakobana** [comment]
Thank you, this solved it!

$ rm -r ~/.cache/pip
 $ pip install --upgrade toil[all] --user

But I still got the following errors:

![image](https://user-images.githubusercontent.com/36188174/66974614-241dd000-f0f8-11e9-9186-c95dd3180006.png)

Investigating the disk quota in the meantime.

**Comment by diekhans** [comment]
Looks like this is now a local error.

**Comment by august-li-alt** [comment]
> Thank you, this solved it!
> 
> $ rm -r ~/.cache/pip $ pip install --upgrade toil[all] --user
> 
> But I still got the following errors:
> 
> ![image](https://user-images.githubusercontent.com/36188174/66974614-241dd000-f0f8-11e9-9186-c95dd3180006.png)
> 
> Investigating the disk quota in the meantime.

bro,how did you solve it? I get the same error.
