### ISSUE TITLE
AttributeError in cactus:v2.6.0-gpu 

### ISSUE THREAD

**Issue by GRGong** [ComparativeGenomicsToolkit/cactus#1062]
GPU: Nvidia RTX 4090
Driver version: 525.116.04
System: Ubuntu 20.04

I got AttributeError when using cactus-gpu docker version, and same error in singularity version. But it works well in CPU version.
The command and log look like following:
```
$> sudo docker run --gpus all -v $(pwd):/data --rm -it quay.io/comparative-genomics-toolkit/cactus:v2.6.0-gpu cactus --gpu 1  /data/js /data/examples/evolverMammals.txt /data/evolverMammals.hal

==========
== CUDA ==
==========

CUDA Version 11.4.3

Container image Copyright (c) 2016-2023, NVIDIA CORPORATION & AFFILIATES. All rights reserved.

This container image and its contents are governed by the NVIDIA Deep Learning Container License.
By pulling and using the container, you accept the terms and conditions of this license:
https://developer.nvidia.com/ngc/nvidia-deep-learning-container-license

A copy of this license is made available in this container at /NGC-DL-CONTAINER-LICENSE for your convenience.

[2023-06-19T11:19:05+0000] [MainThread] [I] [toil.statsAndLogging] Enabling realtime logging in Toil
[2023-06-19T11:19:05+0000] [MainThread] [I] [toil.statsAndLogging] Cactus Command: /home/cactus/cactus_env/bin/cactus --gpu 1 /data/js /data/examples/evolverMammals.txt /data/evolverMammals.hal
[2023-06-19T11:19:05+0000] [MainThread] [I] [toil.statsAndLogging] Cactus Commit: ce2bd972d997340845c78f69671106178ce6491e
[2023-06-19T11:19:05+0000] [MainThread] [I] [toil.statsAndLogging] Tree: ((simHuman_chr6:0.144018,(simMouse_chr6:0.084509,simRat_chr6:0.091589)mr:0.271974)Anc1:0.020593,(simCow_chr6:0.18908,simDog_chr6:0.16303)Anc2:0.032898)Anc0;
[2023-06-19T11:19:05+0000] [MainThread] [I] [toil.statsAndLogging] Importing https://raw.githubusercontent.com/ComparativeGenomicsToolkit/cactusTestData/master/evolver/mammals/loci1/simCow.chr6
[2023-06-19T11:19:08+0000] [MainThread] [I] [toil.statsAndLogging] Importing https://raw.githubusercontent.com/ComparativeGenomicsToolkit/cactusTestData/master/evolver/mammals/loci1/simDog.chr6
[2023-06-19T11:19:09+0000] [MainThread] [I] [toil.statsAndLogging] Importing https://raw.githubusercontent.com/ComparativeGenomicsToolkit/cactusTestData/master/evolver/mammals/loci1/simHuman.chr6
[2023-06-19T11:19:09+0000] [MainThread] [I] [toil.statsAndLogging] Importing https://raw.githubusercontent.com/ComparativeGenomicsToolkit/cactusTestData/master/evolver/mammals/loci1/simMouse.chr6
[2023-06-19T11:19:09+0000] [MainThread] [I] [toil.statsAndLogging] Importing https://raw.githubusercontent.com/ComparativeGenomicsToolkit/cactusTestData/master/evolver/mammals/loci1/simRat.chr6
[2023-06-19T11:19:10+0000] [MainThread] [I] [toil.job] Saving graph of 1 jobs, 1 non-service, 1 new
[2023-06-19T11:19:10+0000] [MainThread] [I] [toil.job] Processing job 'progressive_workflow' kind-progressive_workflow/instance-yfx7h3ev v0
[2023-06-19T11:19:10+0000] [MainThread] [I] [toil] Running Toil version 5.10.0-21422a3440f8a6d5e9d2f1c9695c4fbc57fa5372 on host a15c3b72e3c6.
[2023-06-19T11:19:10+0000] [MainThread] [I] [toil.realtimeLogger] Starting real-time logging.
[2023-06-19T11:19:10+0000] [MainThread] [I] [toil.leader] Issued job 'progressive_workflow' kind-progressive_workflow/instance-yfx7h3ev v1 with job batch system ID: 0 and disk: 2.0 Gi, memory: 2.0 Gi, cores: 1, accelerators: [], preemptible: False
[2023-06-19T11:19:10+0000] [MainThread] [I] [toil.worker] Redirecting logging to /tmp/d45b0297e5ba5af68ddcb0330cd31a3c/cde6/worker_log.txt
[2023-06-19T11:19:11+0000] [MainThread] [I] [toil.leader] 0 jobs are running, 0 jobs are issued and waiting to run
[2023-06-19T11:19:11+0000] [MainThread] [I] [toil.leader] Issued job 'sanitize_fasta_header' kind-sanitize_fasta_header/instance-4ct7k4wa v1 with job batch system ID: 1 and disk: 4.0 Mi, memory: 2.0 Gi, cores: 1, accelerators: [], preemptible: False
[2023-06-19T11:19:11+0000] [MainThread] [I] [toil.leader] Issued job 'sanitize_fasta_header' kind-sanitize_fasta_header/instance-l891im3a v1 with job batch system ID: 2 and disk: 4.3 Mi, memory: 2.0 Gi, cores: 1, accelerators: [], preemptible: False
[2023-06-19T11:19:11+0000] [MainThread] [I] [toil.leader] Issued job 'sanitize_fasta_header' kind-sanitize_fasta_header/instance-kfcsd07a v1 with job batch system ID: 3 and disk: 4.1 Mi, memory: 2.0 Gi, cores: 1, accelerators: [], preemptible: False
[2023-06-19T11:19:11+0000] [MainThread] [I] [toil.leader] Issued job 'sanitize_fasta_header' kind-sanitize_fasta_header/instance-mimb6bxo v1 with job batch system ID: 4 and disk: 4.4 Mi, memory: 2.0 Gi, cores: 1, accelerators: [], preemptible: False
[2023-06-19T11:19:11+0000] [MainThread] [I] [toil.leader] Issued job 'sanitize_fasta_header' kind-sanitize_fasta_header/instance-ca6p_2_0 v1 with job batch system ID: 5 and disk: 4.1 Mi, memory: 2.0 Gi, cores: 1, accelerators: [], preemptible: False
[2023-06-19T11:19:11+0000] [MainThread] [I] [toil.worker] Redirecting logging to /tmp/d45b0297e5ba5af68ddcb0330cd31a3c/c6fa/worker_log.txt
[2023-06-19T11:19:11+0000] [MainThread] [I] [toil.worker] Redirecting logging to /tmp/d45b0297e5ba5af68ddcb0330cd31a3c/b0ab/worker_log.txt
[2023-06-19T11:19:11+0000] [MainThread] [I] [toil.worker] Redirecting logging to /tmp/d45b0297e5ba5af68ddcb0330cd31a3c/a046/worker_log.txt
[2023-06-19T11:19:11+0000] [MainThread] [I] [toil.worker] Redirecting logging to /tmp/d45b0297e5ba5af68ddcb0330cd31a3c/3ddb/worker_log.txt
[2023-06-19T11:19:11+0000] [MainThread] [I] [toil.worker] Redirecting logging to /tmp/d45b0297e5ba5af68ddcb0330cd31a3c/5cc0/worker_log.txt
[2023-06-19T11:19:11+0000] [MainThread] [I] [toil-rt] 2023-06-19 11:19:11.835352: Running the command: "cactus_sanitizeFastaHeaders /tmp/d45b0297e5ba5af68ddcb0330cd31a3c/c6fa/2342/tmpavdg426e/simMouse_chr6.fa simMouse_chr6"
[2023-06-19T11:19:11+0000] [MainThread] [I] [toil-rt] 2023-06-19 11:19:11.842770: Running the command: "cactus_sanitizeFastaHeaders /tmp/d45b0297e5ba5af68ddcb0330cd31a3c/b0ab/1a4b/tmp5njkre9c/simCow_chr6.fa simCow_chr6"
[2023-06-19T11:19:11+0000] [MainThread] [I] [toil-rt] 2023-06-19 11:19:11.844584: Running the command: "cactus_sanitizeFastaHeaders /tmp/d45b0297e5ba5af68ddcb0330cd31a3c/a046/ecfb/tmp02xyxf3r/simDog_chr6.fa simDog_chr6"
[2023-06-19T11:19:11+0000] [MainThread] [I] [toil-rt] 2023-06-19 11:19:11.858864: Successfully ran: "cactus_sanitizeFastaHeaders /tmp/d45b0297e5ba5af68ddcb0330cd31a3c/c6fa/2342/tmpavdg426e/simMouse_chr6.fa simMouse_chr6" in 0.0165 seconds and 2.7 Mi memory
[2023-06-19T11:19:11+0000] [MainThread] [I] [toil-rt] 2023-06-19 11:19:11.860148: Running the command: "cactus_analyseAssembly simMouse_chr6.sanitized.fa"
[2023-06-19T11:19:11+0000] [MainThread] [I] [toil-rt] 2023-06-19 11:19:11.864469: Running the command: "cactus_sanitizeFastaHeaders /tmp/d45b0297e5ba5af68ddcb0330cd31a3c/3ddb/7572/tmpfbojug6d/simRat_chr6.fa simRat_chr6"
[2023-06-19T11:19:11+0000] [MainThread] [I] [toil-rt] 2023-06-19 11:19:11.865282: Running the command: "cactus_sanitizeFastaHeaders /tmp/d45b0297e5ba5af68ddcb0330cd31a3c/5cc0/73f2/tmppgcx0g9c/simHuman_chr6.fa simHuman_chr6"
[2023-06-19T11:19:11+0000] [MainThread] [I] [toil-rt] 2023-06-19 11:19:11.868387: Successfully ran: "cactus_sanitizeFastaHeaders /tmp/d45b0297e5ba5af68ddcb0330cd31a3c/b0ab/1a4b/tmp5njkre9c/simCow_chr6.fa simCow_chr6" in 0.0189 seconds and 2.8 Mi memory
[2023-06-19T11:19:11+0000] [MainThread] [I] [toil-rt] 2023-06-19 11:19:11.868818: Successfully ran: "cactus_sanitizeFastaHeaders /tmp/d45b0297e5ba5af68ddcb0330cd31a3c/a046/ecfb/tmp02xyxf3r/simDog_chr6.fa simDog_chr6" in 0.0178 seconds and 2.8 Mi memory
[2023-06-19T11:19:11+0000] [MainThread] [I] [toil-rt] 2023-06-19 11:19:11.869446: Running the command: "cactus_analyseAssembly simCow_chr6.sanitized.fa"
[2023-06-19T11:19:11+0000] [MainThread] [I] [toil-rt] 2023-06-19 11:19:11.870041: Running the command: "cactus_analyseAssembly simDog_chr6.sanitized.fa"
[2023-06-19T11:19:11+0000] [MainThread] [I] [toil-rt] 2023-06-19 11:19:11.886061: Successfully ran: "cactus_analyseAssembly simMouse_chr6.sanitized.fa" in 0.019 seconds and 2.7 Mi memory
[2023-06-19T11:19:11+0000] [MainThread] [I] [toil-rt] 2023-06-19 11:19:11.886964: Successfully ran: "cactus_analyseAssembly simCow_chr6.sanitized.fa" in 0.0111 seconds and 2.7 Mi memory
[2023-06-19T11:19:11+0000] [MainThread] [I] [toil-rt] 2023-06-19 11:19:11.891653: Successfully ran: "cactus_sanitizeFastaHeaders /tmp/d45b0297e5ba5af68ddcb0330cd31a3c/3ddb/7572/tmpfbojug6d/simRat_chr6.fa simRat_chr6" in 0.0202 seconds and 2.7 Mi memory
[2023-06-19T11:19:11+0000] [MainThread] [I] [toil-rt] 2023-06-19 11:19:11.892341: Successfully ran: "cactus_sanitizeFastaHeaders /tmp/d45b0297e5ba5af68ddcb0330cd31a3c/5cc0/73f2/tmppgcx0g9c/simHuman_chr6.fa simHuman_chr6" in 0.0201 seconds and 2.8 Mi memory
[2023-06-19T11:19:11+0000] [MainThread] [I] [toil-rt] 2023-06-19 11:19:11.892754: Running the command: "cactus_analyseAssembly simRat_chr6.sanitized.fa"
[2023-06-19T11:19:11+0000] [MainThread] [I] [toil-rt] 2023-06-19 11:19:11.893574: Running the command: "cactus_analyseAssembly simHuman_chr6.sanitized.fa"
[2023-06-19T11:19:11+0000] [MainThread] [I] [toil-rt] 2023-06-19 11:19:11.896700: Successfully ran: "cactus_analyseAssembly simDog_chr6.sanitized.fa" in 0.0196 seconds and 2.8 Mi memory
[2023-06-19T11:19:11+0000] [MainThread] [I] [toil-rt] 2023-06-19 11:19:11.915644: Successfully ran: "cactus_analyseAssembly simRat_chr6.sanitized.fa" in 0.017 seconds and 2.7 Mi memory
[2023-06-19T11:19:11+0000] [MainThread] [I] [toil-rt] 2023-06-19 11:19:11.916073: Successfully ran: "cactus_analyseAssembly simHuman_chr6.sanitized.fa" in 0.0155 seconds and 2.7 Mi memory
[2023-06-19T11:19:11+0000] [Thread-4  ] [I] [toil.statsAndLogging] Got message from job at time 06-19-2023 11:19:11: Assembly stats for simRat_chr6: Input-sample: simRat_chr6.sanitized.fa Total-sequences: 1 Total-length: 647215 Proportion-repeat-masked: 0.075276 ProportionNs: 0.000000 Total-Ns: 0 N50: 647215 Median-sequence-length: 647215 Max-sequence-length: 647215 Min-sequence-length: 647215

[2023-06-19T11:19:11+0000] [Thread-4  ] [I] [toil.statsAndLogging] Got message from job at time 06-19-2023 11:19:11: Assembly stats for simCow_chr6: Input-sample: simCow_chr6.sanitized.fa Total-sequences: 1 Total-length: 602619 Proportion-repeat-masked: 0.054570 ProportionNs: 0.000000 Total-Ns: 0 N50: 602619 Median-sequence-length: 602619 Max-sequence-length: 602619 Min-sequence-length: 602619

[2023-06-19T11:19:11+0000] [Thread-4  ] [I] [toil.statsAndLogging] Got message from job at time 06-19-2023 11:19:11: Assembly stats for simMouse_chr6: Input-sample: simMouse_chr6.sanitized.fa Total-sequences: 1 Total-length: 636262 Proportion-repeat-masked: 0.056477 ProportionNs: 0.000000 Total-Ns: 0 N50: 636262 Median-sequence-length: 636262 Max-sequence-length: 636262 Min-sequence-length: 636262

[2023-06-19T11:19:11+0000] [Thread-4  ] [I] [toil.statsAndLogging] Got message from job at time 06-19-2023 11:19:11: Assembly stats for simHuman_chr6: Input-sample: simHuman_chr6.sanitized.fa Total-sequences: 1 Total-length: 601863 Proportion-repeat-masked: 0.074751 ProportionNs: 0.000000 Total-Ns: 0 N50: 601863 Median-sequence-length: 601863 Max-sequence-length: 601863 Min-sequence-length: 601863

[2023-06-19T11:19:11+0000] [Thread-4  ] [I] [toil.statsAndLogging] Got message from job at time 06-19-2023 11:19:11: Assembly stats for simDog_chr6: Input-sample: simDog_chr6.sanitized.fa Total-sequences: 1 Total-length: 593897 Proportion-repeat-masked: 0.045009 ProportionNs: 0.000000 Total-Ns: 0 N50: 593897 Median-sequence-length: 593897 Max-sequence-length: 593897 Min-sequence-length: 593897

[2023-06-19T11:19:12+0000] [MainThread] [I] [toil.leader] Issued job 'preprocess_all' kind-preprocess_all/instance-yn8lzzvt v1 with job batch system ID: 6 and disk: 2.0 Gi, memory: 2.0 Gi, cores: 1, accelerators: [], preemptible: False
[2023-06-19T11:19:12+0000] [MainThread] [I] [toil.worker] Redirecting logging to /tmp/d45b0297e5ba5af68ddcb0330cd31a3c/dc11/worker_log.txt
[2023-06-19T11:19:12+0000] [MainThread] [I] [toil.leader] Issued job 'CactusPreprocessor' kind-CactusPreprocessor/instance-a9ofb1me v1 with job batch system ID: 7 and disk: 1.6 Gi, memory: 2.0 Gi, cores: 1, accelerators: [], preemptible: True
[2023-06-19T11:19:13+0000] [MainThread] [I] [toil.worker] Redirecting logging to /tmp/d45b0297e5ba5af68ddcb0330cd31a3c/1293/worker_log.txt
[2023-06-19T11:19:13+0000] [MainThread] [I] [toil.leader] Issued job 'CactusPreprocessor2' kind-CactusPreprocessor2/instance-4nfocsr9 v1 with job batch system ID: 8 and disk: 2.0 Gi, memory: 2.0 Gi, cores: 1, accelerators: [], preemptible: True
[2023-06-19T11:19:13+0000] [MainThread] [I] [toil.leader] Issued job 'CactusPreprocessor2' kind-CactusPreprocessor2/instance-nwp00296 v1 with job batch system ID: 9 and disk: 2.0 Gi, memory: 2.0 Gi, cores: 1, accelerators: [], preemptible: True
[2023-06-19T11:19:13+0000] [MainThread] [I] [toil.leader] Issued job 'CactusPreprocessor2' kind-CactusPreprocessor2/instance-cbzgiyfi v1 with job batch system ID: 10 and disk: 2.0 Gi, memory: 2.0 Gi, cores: 1, accelerators: [], preemptible: True
[2023-06-19T11:19:13+0000] [MainThread] [I] [toil.leader] Issued job 'CactusPreprocessor2' kind-CactusPreprocessor2/instance-kgl3opye v1 with job batch system ID: 11 and disk: 2.0 Gi, memory: 2.0 Gi, cores: 1, accelerators: [], preemptible: True
[2023-06-19T11:19:13+0000] [MainThread] [I] [toil.leader] Issued job 'CactusPreprocessor2' kind-CactusPreprocessor2/instance-c2xufzkl v1 with job batch system ID: 12 and disk: 2.0 Gi, memory: 2.0 Gi, cores: 1, accelerators: [], preemptible: True
[2023-06-19T11:19:14+0000] [MainThread] [I] [toil.worker] Redirecting logging to /tmp/d45b0297e5ba5af68ddcb0330cd31a3c/adc2/worker_log.txt
[2023-06-19T11:19:14+0000] [MainThread] [I] [toil.worker] Redirecting logging to /tmp/d45b0297e5ba5af68ddcb0330cd31a3c/ed15/worker_log.txt
[2023-06-19T11:19:14+0000] [MainThread] [I] [toil.worker] Redirecting logging to /tmp/d45b0297e5ba5af68ddcb0330cd31a3c/509d/worker_log.txt
[2023-06-19T11:19:14+0000] [MainThread] [I] [toil.worker] Redirecting logging to /tmp/d45b0297e5ba5af68ddcb0330cd31a3c/03eb/worker_log.txt
[2023-06-19T11:19:14+0000] [MainThread] [I] [toil.worker] Redirecting logging to /tmp/d45b0297e5ba5af68ddcb0330cd31a3c/34f4/worker_log.txt
[2023-06-19T11:19:14+0000] [MainThread] [I] [toil.leader] Issued job 'CutHeadersJob' kind-CutHeadersJob/instance-xuqc200a v1 with job batch system ID: 13 and disk: 1.6 Gi, memory: 2.0 Gi, cores: 1, accelerators: [], preemptible: True
[2023-06-19T11:19:14+0000] [MainThread] [I] [toil.leader] Issued job 'CutHeadersJob' kind-CutHeadersJob/instance-uzikk971 v1 with job batch system ID: 14 and disk: 1.6 Gi, memory: 2.0 Gi, cores: 1, accelerators: [], preemptible: True
[2023-06-19T11:19:14+0000] [MainThread] [I] [toil.leader] Issued job 'CutHeadersJob' kind-CutHeadersJob/instance-7abxv9lq v1 with job batch system ID: 15 and disk: 1.6 Gi, memory: 2.0 Gi, cores: 1, accelerators: [], preemptible: True
[2023-06-19T11:19:14+0000] [MainThread] [I] [toil.leader] Issued job 'CutHeadersJob' kind-CutHeadersJob/instance-4652fzy1 v1 with job batch system ID: 16 and disk: 1.6 Gi, memory: 2.0 Gi, cores: 1, accelerators: [], preemptible: True
[2023-06-19T11:19:14+0000] [MainThread] [I] [toil.leader] Issued job 'CutHeadersJob' kind-CutHeadersJob/instance-huzwfsu_ v1 with job batch system ID: 17 and disk: 1.6 Gi, memory: 2.0 Gi, cores: 1, accelerators: [], preemptible: True
[2023-06-19T11:19:14+0000] [MainThread] [I] [toil.worker] Redirecting logging to /tmp/d45b0297e5ba5af68ddcb0330cd31a3c/8e5b/worker_log.txt
[2023-06-19T11:19:14+0000] [MainThread] [I] [toil.worker] Redirecting logging to /tmp/d45b0297e5ba5af68ddcb0330cd31a3c/dd9f/worker_log.txt
[2023-06-19T11:19:14+0000] [MainThread] [I] [toil.worker] Redirecting logging to /tmp/d45b0297e5ba5af68ddcb0330cd31a3c/8a31/worker_log.txt
[2023-06-19T11:19:14+0000] [MainThread] [I] [toil.worker] Redirecting logging to /tmp/d45b0297e5ba5af68ddcb0330cd31a3c/fa06/worker_log.txt
[2023-06-19T11:19:14+0000] [MainThread] [I] [toil.worker] Redirecting logging to /tmp/d45b0297e5ba5af68ddcb0330cd31a3c/2dd0/worker_log.txt
[2023-06-19T11:19:15+0000] [MainThread] [I] [toil.leader] Issued job 'BatchPreprocessor' kind-BatchPreprocessor/instance-lafkhaz3 v1 with job batch system ID: 18 and disk: 2.0 Gi, memory: 2.0 Gi, cores: 1, accelerators: [], preemptible: True
[2023-06-19T11:19:15+0000] [MainThread] [I] [toil.leader] Issued job 'BatchPreprocessor' kind-BatchPreprocessor/instance-asb7o6o4 v1 with job batch system ID: 19 and disk: 2.0 Gi, memory: 2.0 Gi, cores: 1, accelerators: [], preemptible: True
[2023-06-19T11:19:15+0000] [MainThread] [I] [toil.leader] Issued job 'BatchPreprocessor' kind-BatchPreprocessor/instance-12vcvh_9 v1 with job batch system ID: 20 and disk: 2.0 Gi, memory: 2.0 Gi, cores: 1, accelerators: [], preemptible: True
[2023-06-19T11:19:15+0000] [MainThread] [I] [toil.leader] Issued job 'BatchPreprocessor' kind-BatchPreprocessor/instance-88qpediq v1 with job batch system ID: 21 and disk: 2.0 Gi, memory: 2.0 Gi, cores: 1, accelerators: [], preemptible: True
[2023-06-19T11:19:15+0000] [MainThread] [I] [toil.leader] Issued job 'BatchPreprocessor' kind-BatchPreprocessor/instance-2a6766wp v1 with job batch system ID: 22 and disk: 2.0 Gi, memory: 2.0 Gi, cores: 1, accelerators: [], preemptible: True
[2023-06-19T11:19:15+0000] [MainThread] [I] [toil.worker] Redirecting logging to /tmp/d45b0297e5ba5af68ddcb0330cd31a3c/b2cc/worker_log.txt
[2023-06-19T11:19:15+0000] [MainThread] [I] [toil.worker] Redirecting logging to /tmp/d45b0297e5ba5af68ddcb0330cd31a3c/61ea/worker_log.txt
[2023-06-19T11:19:15+0000] [MainThread] [I] [toil.worker] Redirecting logging to /tmp/d45b0297e5ba5af68ddcb0330cd31a3c/ea79/worker_log.txt
[2023-06-19T11:19:15+0000] [MainThread] [I] [toil.worker] Redirecting logging to /tmp/d45b0297e5ba5af68ddcb0330cd31a3c/cd29/worker_log.txt
[2023-06-19T11:19:15+0000] [MainThread] [I] [toil.worker] Redirecting logging to /tmp/d45b0297e5ba5af68ddcb0330cd31a3c/2f80/worker_log.txt
[2023-06-19T11:19:16+0000] [MainThread] [I] [toil.leader] Issued job 'BatchPreprocessor' kind-BatchPreprocessor/instance-ewq2slnf v1 with job batch system ID: 23 and disk: 2.0 Gi, memory: 2.0 Gi, cores: 1, accelerators: [], preemptible: True
[2023-06-19T11:19:16+0000] [MainThread] [I] [toil.leader] Issued job 'BatchPreprocessor' kind-BatchPreprocessor/instance-cdtzjhtv v1 with job batch system ID: 24 and disk: 2.0 Gi, memory: 2.0 Gi, cores: 1, accelerators: [], preemptible: True
[2023-06-19T11:19:16+0000] [MainThread] [I] [toil.leader] Issued job 'BatchPreprocessor' kind-BatchPreprocessor/instance-jui9pzpw v1 with job batch system ID: 25 and disk: 2.0 Gi, memory: 2.0 Gi, cores: 1, accelerators: [], preemptible: True
[2023-06-19T11:19:16+0000] [MainThread] [I] [toil.leader] Issued job 'BatchPreprocessor' kind-BatchPreprocessor/instance-_uftuh5q v1 with job batch system ID: 26 and disk: 2.0 Gi, memory: 2.0 Gi, cores: 1, accelerators: [], preemptible: True
[2023-06-19T11:19:16+0000] [MainThread] [I] [toil.leader] Issued job 'BatchPreprocessor' kind-BatchPreprocessor/instance-5_sgbvxj v1 with job batch system ID: 27 and disk: 2.0 Gi, memory: 2.0 Gi, cores: 1, accelerators: [], preemptible: True
[2023-06-19T11:19:16+0000] [MainThread] [I] [toil.worker] Redirecting logging to /tmp/d45b0297e5ba5af68ddcb0330cd31a3c/4f17/worker_log.txt
[2023-06-19T11:19:16+0000] [MainThread] [I] [toil.worker] Redirecting logging to /tmp/d45b0297e5ba5af68ddcb0330cd31a3c/6a7d/worker_log.txt
[2023-06-19T11:19:16+0000] [MainThread] [I] [toil.worker] Redirecting logging to /tmp/d45b0297e5ba5af68ddcb0330cd31a3c/47de/worker_log.txt
[2023-06-19T11:19:16+0000] [MainThread] [I] [toil.worker] Redirecting logging to /tmp/d45b0297e5ba5af68ddcb0330cd31a3c/cce2/worker_log.txt
[2023-06-19T11:19:16+0000] [MainThread] [I] [toil.worker] Redirecting logging to /tmp/d45b0297e5ba5af68ddcb0330cd31a3c/f158/worker_log.txt
[2023-06-19T11:19:16+0000] [MainThread] [I] [toil.leader] Issued job 'LastzRepeatMaskJob' kind-LastzRepeatMaskJob/instance-d1me4107 v1 with job batch system ID: 28 and disk: 1.6 Gi, memory: 4.0 Gi, cores: 128, accelerators: [{'count': 1, 'kind': 'gpu', 'api': 'cuda', 'brand': 'nvidia'}], preemptible: True
[2023-06-19T11:19:16+0000] [Thread-1  ] [C] [toil.batchSystems.singleMachine] Unhandled exception in daddy thread for batch system 140385163003936: Traceback (most recent call last):
  File "/home/cactus/cactus_env/lib/python3.8/site-packages/toil/batchSystems/singleMachine.py", line 228, in daddy
    result = self._startChild(jobCommand, jobID,
  File "/home/cactus/cactus_env/lib/python3.8/site-packages/toil/batchSystems/singleMachine.py", line 604, in _startChild
    snapshot = accelerator_set.get_free_snapshot()
AttributeError: 'ResourcePool' object has no attribute 'get_free_snapshot'

Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/home/cactus/cactus_env/lib/python3.8/site-packages/toil/batchSystems/singleMachine.py", line 228, in daddy
    result = self._startChild(jobCommand, jobID,
  File "/home/cactus/cactus_env/lib/python3.8/site-packages/toil/batchSystems/singleMachine.py", line 604, in _startChild
    snapshot = accelerator_set.get_free_snapshot()
AttributeError: 'ResourcePool' object has no attribute 'get_free_snapshot'
[2023-06-19T11:19:18+0000] [MainThread] [C] [toil.batchSystems.singleMachine] Propagating unhandled exception in daddy thread to main thread

Workflow Progress  86%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████▍                  | 24/28 (0 failures) [00:07<00:01, 3.69 jobs/s]
[2023-06-19T11:19:20+0000] [MainThread] [I] [toil.realtimeLogger] Stopping real-time logging server.
[2023-06-19T11:19:20+0000] [MainThread] [I] [toil.realtimeLogger] Joining real-time logging server thread.
Traceback (most recent call last):
  File "/home/cactus/cactus_env/bin/cactus", line 8, in <module>
    sys.exit(main())
  File "/home/cactus/cactus_env/lib/python3.8/site-packages/cactus/progressive/cactus_progressive.py", line 428, in main
    hal_id = toil.start(Job.wrapJobFn(progressive_workflow, options, config_node, mc_tree, og_map, input_seq_id_map))
  File "/home/cactus/cactus_env/lib/python3.8/site-packages/toil/common.py", line 1064, in start
    return self._runMainLoop(rootJobDescription)
  File "/home/cactus/cactus_env/lib/python3.8/site-packages/toil/common.py", line 1511, in _runMainLoop
    return Leader(config=self.config,
  File "/home/cactus/cactus_env/lib/python3.8/site-packages/toil/leader.py", line 251, in run
    self.innerLoop()
  File "/home/cactus/cactus_env/lib/python3.8/site-packages/toil/leader.py", line 763, in innerLoop
    self.checkForDeadlocks()
  File "/home/cactus/cactus_env/lib/python3.8/site-packages/toil/leader.py", line 797, in checkForDeadlocks
    totalRunningJobs = len(self.batchSystem.getRunningBatchJobIDs())
  File "/home/cactus/cactus_env/lib/python3.8/site-packages/toil/batchSystems/singleMachine.py", line 815, in getRunningBatchJobIDs
    self._checkOnDaddy()
  File "/home/cactus/cactus_env/lib/python3.8/site-packages/toil/batchSystems/singleMachine.py", line 287, in _checkOnDaddy
    raise exc
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/home/cactus/cactus_env/lib/python3.8/site-packages/toil/batchSystems/singleMachine.py", line 228, in daddy
    result = self._startChild(jobCommand, jobID,
  File "/home/cactus/cactus_env/lib/python3.8/site-packages/toil/batchSystems/singleMachine.py", line 604, in _startChild
    snapshot = accelerator_set.get_free_snapshot()
AttributeError: 'ResourcePool' object has no attribute 'get_free_snapshot'

```

**Comment by glennhickey** [comment]
Hi, thanks for raising this issue!  

I'll try to figure out what's going on, but in the meantime it looks like you can work around it by first running
```
pip install -U toil==v5.9.0
```
in your container.

**Comment by GRGong** [comment]
Thanks a lot! It did word.
