### ISSUE TITLE
Question about installing

### ISSUE THREAD

**Issue by YuChrming** [ComparativeGenomicsToolkit/cactus#1064]
I try to install the pipline using the ducument 

Create the Python virtual environment. Install virtualenv first if needed with python3 -m pip install virtualenv.

cd cactus
virtualenv -p python3 cactus_env
echo "export PATH=$(pwd)/bin:\$PATH" >> cactus_env/bin/activate
echo "export PYTHONPATH=$(pwd)/lib:\$PYTHONPATH" >> cactus_env/bin/activate
source cactus_env/bin/activate
python3 -m pip install -U setuptools pip
python3 -m pip install -U .
python3 -m pip install -U -r ./toil-requirement.txt

When I enter `python3 -m pip install -U .` , following Error appeared.
      /ngsproject/qmyu/tool/minigraph/cactus/cactus_env/lib/python3.8/site-packages/setuptools/_distutils/cmd.py:66: SetuptoolsDeprecationWarning: setup.py install is deprecated.
      !!

              ********************************************************************************
              Please avoid running ``setup.py`` directly.
              Instead, use pypa/build, pypa/installer or other
              standards-based tools.

              See https://blog.ganssle.io/articles/2021/10/setup-py-deprecated.html for details.
              ********************************************************************************

      !!
        self.initialize_options()
      installing to build/bdist.linux-x86_64/wheel
      running install
      ERROR: Directory 'submodules/sonLib' is not installable. Neither 'setup.py' nor 'pyproject.toml' found.
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/ngsproject/qmyu/tool/minigraph/cactus/setup.py", line 25, in <module>
          setup(
        File "/ngsproject/qmyu/tool/minigraph/cactus/cactus_env/lib/python3.8/site-packages/setuptools/__init__.py", line 107, in setup
          return distutils.core.setup(**attrs)
        File "/ngsproject/qmyu/tool/minigraph/cactus/cactus_env/lib/python3.8/site-packages/setuptools/_distutils/core.py", line 185, in setup
          return run_commands(dist)
        File "/ngsproject/qmyu/tool/minigraph/cactus/cactus_env/lib/python3.8/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
          dist.run_commands()
        File "/ngsproject/qmyu/tool/minigraph/cactus/cactus_env/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands
          self.run_command(cmd)
        File "/ngsproject/qmyu/tool/minigraph/cactus/cactus_env/lib/python3.8/site-packages/setuptools/dist.py", line 1234, in run_command
          super().run_command(command)
        File "/ngsproject/qmyu/tool/minigraph/cactus/cactus_env/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/ngsproject/qmyu/tool/minigraph/cactus/cactus_env/lib/python3.8/site-packages/wheel/bdist_wheel.py", line 378, in run
          self.run_command("install")
        File "/ngsproject/qmyu/tool/minigraph/cactus/cactus_env/lib/python3.8/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
          self.distribution.run_command(command)
        File "/ngsproject/qmyu/tool/minigraph/cactus/cactus_env/lib/python3.8/site-packages/setuptools/dist.py", line 1234, in run_command
          super().run_command(command)
        File "/ngsproject/qmyu/tool/minigraph/cactus/cactus_env/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/ngsproject/qmyu/tool/minigraph/cactus/setup.py", line 22, in run
          subprocess.run([sys.executable, "-m", "pip", "install", "submodules/sonLib"], check=True)
        File "/ngsproject/qmyu/miniconda3/lib/python3.8/subprocess.py", line 516, in run
          raise CalledProcessError(retcode, process.args,
      subprocess.CalledProcessError: Command '['/ngsproject/qmyu/tool/minigraph/cactus/cactus_env/bin/python3', '-m', 'pip', 'install', 'submodules/sonLib']' returned non-zero exit status 1.
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for Cactus
  Running setup.py clean for Cactus
Failed to build Cactus
ERROR: Could not build wheels for Cactus, which is required to install pyproject.toml-based projects

How could I solve it . Thanks a lot!

**Comment by glennhickey** [comment]
I recommend downloading and installing the binaries from the Release page:

https://github.com/ComparativeGenomicsToolkit/cactus/releases/tag/v2.6.0

If you really want to install from source, follow in the instructions here

https://github.com/ComparativeGenomicsToolkit/cactus/tree/master#installing-manually-from-source

particularly cloning the submodules with --recursive.

**Comment by YuChrming** [comment]
Seams I have forgotten "--recursive", now it is all right.Thanks very much!

**Comment by songxh1996** [comment]
> Seams I have forgotten "--recursive", now it is all right.Thanks very much!

hello,I downloaded the reference genome from ncbi, but I don't know how to generate a tree file, how did you solve it?
