### ISSUE TITLE
 singularity: no run driver found inside container

### ISSUE THREAD

**Issue by lassancejm** [ComparativeGenomicsToolkit/cactus#109]
Hi, 

I am trying to run cactus with `--binariesMode singularity`. I have access to singularity version: 3.4.2-1.el7 and using toil version: 3.20 on a linux HPC. 

The following error message seems to indicate that there is something missing in the container. Any advice on how to get passed this error would be appreciated. 

```WARNING:toil.leader:The job seems to have left a log file, indicating failure: 'logAssemblyStats' r/F/jobzSVk8e
WARNING:toil.leader:r/F/jobzSVk8e    INFO:toil.worker:---TOIL WORKER OUTPUT LOG---
WARNING:toil.leader:r/F/jobzSVk8e    INFO:toil:Running Toil version 3.20.0-cf34ca3416697f2abc816b2538f20ee29ba16932.
WARNING:toil.leader:r/F/jobzSVk8e    WARNING:toil.resource:'JTRES_487db7e35980364bd76c90413e988c94' may exist, but is not yet referenced by the worker (KeyError from os.environ[]).
WARNING:toil.leader:r/F/jobzSVk8e    WARNING:toil.resource:'JTRES_487db7e35980364bd76c90413e988c94' may exist, but is not yet referenced by the worker (KeyError from os.environ[]).
WARNING:toil.leader:r/F/jobzSVk8e    INFO:cactus.shared.common:Work dirs: set([u'/n/scratchlfs/hoekstra_lab/lassance/tmp/toil-12b0e62e-980c-4d17-9832-185653aabc69-4684305a-fb67-4700-894d-b8311de884cb/tmpDlC78x/3ef2a40b-4591-4a1f-b495-0b6797688daf'])
WARNING:toil.leader:r/F/jobzSVk8e    INFO:cactus.shared.common:Docker work dir: /n/scratchlfs/hoekstra_lab/lassance/tmp/toil-12b0e62e-980c-4d17-9832-185653aabc69-4684305a-fb67-4700-894d-b8311de884cb/tmpDlC78x/3ef2a40b-4591-4a1f-b495-0b6797688daf
WARNING:toil.leader:r/F/jobzSVk8e    INFO:cactus.shared.common:Running the command ['singularity', '--silent', 'run', u'/n/scratchlfs/hoekstra_lab/lassance/jobStore/cactus.img', u'cactus_analyseAssembly', u'tmprOIJP9.tmp']
WARNING:toil.leader:r/F/jobzSVk8e    ESC[31mFATAL:  ESC[0m no run driver found inside container
WARNING:toil.leader:r/F/jobzSVk8e    Traceback (most recent call last):
WARNING:toil.leader:r/F/jobzSVk8e      File "/n/home01/lassance/.conda/envs/ENV_CACTUS/lib/python2.7/site-packages/toil/worker.py", line 331, in workerScript
WARNING:toil.leader:r/F/jobzSVk8e        job._runner(jobGraph=jobGraph, jobStore=jobStore, fileStore=fileStore)
WARNING:toil.leader:r/F/jobzSVk8e      File "/n/home01/lassance/.conda/envs/ENV_CACTUS/lib/python2.7/site-packages/toil/job.py", line 1378, in _runner
WARNING:toil.leader:r/F/jobzSVk8e        returnValues = self._run(jobGraph, fileStore)
WARNING:toil.leader:r/F/jobzSVk8e      File "/n/home01/lassance/.conda/envs/ENV_CACTUS/lib/python2.7/site-packages/toil/job.py", line 1323, in _run
WARNING:toil.leader:r/F/jobzSVk8e        return self.run(fileStore)
WARNING:toil.leader:r/F/jobzSVk8e      File "/n/home01/lassance/.conda/envs/ENV_CACTUS/lib/python2.7/site-packages/toil/job.py", line 1511, in run
WARNING:toil.leader:r/F/jobzSVk8e        rValue = userFunction(*((self,) + tuple(self._args)), **self._kwargs)
WARNING:toil.leader:r/F/jobzSVk8e      File "/n/home01/lassance/.conda/envs/ENV_CACTUS/lib/python2.7/site-packages/cactus/progressive/cactus_progressive.py", line 200, in logAssemblyStats
WARNING:toil.leader:r/F/jobzSVk8e        analysisString = cactus_call(parameters=["cactus_analyseAssembly", sequenceFile], check_output=True)
WARNING:toil.leader:r/F/jobzSVk8e      File "/n/home01/lassance/.conda/envs/ENV_CACTUS/lib/python2.7/site-packages/cactus/shared/common.py", line 1056, in cactus_call
WARNING:toil.leader:r/F/jobzSVk8e        raise RuntimeError("Command %s failed with output: %s" % (call, output))
WARNING:toil.leader:r/F/jobzSVk8e    RuntimeError: Command ['singularity', '--silent', 'run', u'/n/scratchlfs/hoekstra_lab/lassance/jobStore/cactus.img', u'cactus_analyseAssembly', u'tmprOIJP9.tmp'] failed with output: 
WARNING:toil.leader:r/F/jobzSVk8e    ERROR:toil.worker:Exiting the worker because of a failed job on host holy2c02201.rc.fas.harvard.edu
WARNING:toil.leader:r/F/jobzSVk8e    WARNING:toil.jobGraph:Due to failure we are reducing the remaining retry count of job 'logAssemblyStats' r/F/jobzSVk8e with ID r/F/jobzSVk8e to 5
```

**Comment by DailyDreaming** [comment]
@lassancejm Looks like this might be a singularity issue.  You might be able to get around it by configuring the umask: https://github.com/sylabs/singularity/issues/4749

**Comment by lassancejm** [comment]
not sure it works as intended: 
 
```
> umask 0002
> singularity run cactus.img
WARNING: passwd file doesn't exist in container, not updating
WARNING: group file doesn't exist in container, not updating
FATAL:   no run driver found inside container
```

**Comment by DailyDreaming** [comment]
@lassancejm Did you try clearing the singularity cache (ref: https://neurostars.org/t/mriqc-in-combination-with-singularity-3/3918/4)?
