### ISSUE TITLE
cactus-pangenome exited due to bgzip failure

### ISSUE THREAD

**Issue by leon945945** [ComparativeGenomicsToolkit/cactus#1090]
Hi, I ran cactus-pangenome pipeline with `--binariesMode local` on server, the pipeline exited because of `bgzip` error.

> [2023-07-01T02:40:58+0800] [MainThread] [I] [toil.leader] Finished toil run with 7 failed jobs.
[2023-07-01T02:40:58+0800] [MainThread] [I] [toil.leader] Failed jobs at end of the run: 'Job' kind-minigraph_workflow/instance-hb9t012h v5 'Job' kind-split_gfa/instance-7macahhg v8 'Job' kind-update_seqfile/instance-slnuqevq v8 'filter_paf' kind-filter_paf/instance-3ibeakqi v2 'sanitize_fasta_headers' kind-pangenome_end_to_end_workflow/instance-iqsx8zlk v6 'mash_sketch' kind-minigraph_construct_workflow/instance-x1kszr2f v9 'split_fa_into_contigs' kind-split_fa_into_contigs/instance-hk6r386n v6
[2023-07-01T02:40:58+0800] [MainThread] [I] [toil.realtimeLogger] Stopping real-time logging server.
[2023-07-01T02:40:58+0800] [MainThread] [I] [toil.realtimeLogger] Joining real-time logging server thread.
Traceback (most recent call last):
  File "/home/songlizhi/software/cactus/cactus_env/bin/cactus-pangenome", line 8, in <module>
    sys.exit(main())
  File "/home/songlizhi/software/cactus/cactus_env/lib/python3.9/site-packages/cactus/refmap/cactus_pangenome.py", line 214, in main
    toil.start(Job.wrapJobFn(pangenome_end_to_end_workflow, options, config_wrapper, input_seq_id_map, input_path_map, input_seq_order))
  File "/home/songlizhi/software/cactus/cactus_env/lib/python3.9/site-packages/toil/common.py", line 1064, in start
    return self._runMainLoop(rootJobDescription)
  File "/home/songlizhi/software/cactus/cactus_env/lib/python3.9/site-packages/toil/common.py", line 1511, in _runMainLoop
    return Leader(config=self.config,
  File "/home/songlizhi/software/cactus/cactus_env/lib/python3.9/site-packages/toil/leader.py", line 289, in run
    raise FailedJobsException(self.jobStore, failed_jobs, exit_code=self.recommended_fail_exit_code)
toil.exceptions.FailedJobsException: The job store '/home02/songlizhi/sports/hifi/gxmy/assembly/pangenome/tmp' contains 7 failed jobs: 'Job' kind-minigraph_workflow/instance-hb9t012h v5, 'Job' kind-split_gfa/instance-7macahhg v8, 'Job' kind-update_seqfile/instance-slnuqevq v8, 'filter_paf' kind-filter_paf/instance-3ibeakqi v2, 'sanitize_fasta_headers' kind-pangenome_end_to_end_workflow/instance-iqsx8zlk v6, 'mash_sketch' kind-minigraph_construct_workflow/instance-x1kszr2f v9, 'split_fa_into_contigs' kind-split_fa_into_contigs/instance-hk6r386n v6
Log from job "'split_fa_into_contigs' kind-split_fa_into_contigs/instance-hk6r386n v6" follows:
=========>
        [2023-07-01T02:39:14+0800] [MainThread] [I] [toil.worker] ---TOIL WORKER OUTPUT LOG---
        [2023-07-01T02:39:14+0800] [MainThread] [I] [toil] Running Toil version 5.11.0-9a04dabb36d6ab13ed1ac7c711dbdc8c71724dc9 on host fat02.
        [2023-07-01T02:39:14+0800] [MainThread] [I] [toil.worker] Working on job 'split_fa_into_contigs' kind-split_fa_into_contigs/instance-hk6r386n v4
        [2023-07-01T02:39:19+0800] [MainThread] [I] [toil.worker] Loaded body Job('split_fa_into_contigs' kind-split_fa_into_contigs/instance-hk6r386n v4) from description 'split_fa_into_contigs' kind-split_fa_into_contigs/instance-hk6r386n v4
        [2023-07-01T02:39:19+0800] [MainThread] [I] [cactus.shared.common] Running the command ['bash', '-c', 'set -eo pipefail && samtools faidx /tmp/8aaeaad7b40d5243a96b21ee36df7668/6e95/dcf1/tmpfaeegpcb/_MINIGRAPH_.fa --region-file /tmp/8aaeaad7b40d5243a96b21ee36df7668/6e95/dcf1/tmpfaeegpcb/h2tg000088l.fa_contigs.clean | sed -e \'s/\\([^:]*\\):\\([0-9]*\\)-\\([0-9]*\\)/echo "\\1_sub_$((\\2-1))_\\3"/e\' | bgzip --threads 1']
        [2023-07-01T02:39:19+0800] [MainThread] [I] [toil-rt] 2023-07-01 02:39:19.666265: Running the command: "bash -c set -eo pipefail && samtools faidx /tmp/8aaeaad7b40d5243a96b21ee36df7668/6e95/dcf1/tmpfaeegpcb/_MINIGRAPH_.fa --region-file /tmp/8aaeaad7b40d5243a96b21ee36df7668/6e95/dcf1/tmpfaeegpcb/h2tg000088l.fa_contigs.clean | sed -e 's/\([^:]*\):\([0-9]*\)-\([0-9]*\)/echo "\1_sub_$((\2-1))_\3"/e' | bgzip --threads 1"
        [2023-07-01T02:39:23+0800] [MainThread] [I] [toil-rt] 2023-07-01 02:39:23.093816: Successfully ran: "bash -c set -eo pipefail && samtools faidx /tmp/8aaeaad7b40d5243a96b21ee36df7668/6e95/dcf1/tmpfaeegpcb/_MINIGRAPH_.fa --region-file /tmp/8aaeaad7b40d5243a96b21ee36df7668/6e95/dcf1/tmpfaeegpcb/h2tg000088l.fa_contigs.clean | sed -e 's/\([^:]*\):\([0-9]*\)-\([0-9]*\)/echo "\1_sub_$((\2-1))_\3"/e' | bgzip --threads 1" in 3.4185 seconds
        [2023-07-01T02:39:23+0800] [MainThread] [I] [toil-rt] 2023-07-01 02:39:23.095459: Running the command: "bash -c set -eo pipefail && bgzip -dc /tmp/8aaeaad7b40d5243a96b21ee36df7668/6e95/dcf1/tmpfaeegpcb/_MINIGRAPH__h2tg000088l.fa --threads 1 | grep -v '>' | wc | awk '{print $3-$1}'"
        [2023-07-01T02:39:23+0800] [MainThread] [W] [toil.fileStores.abstractFileStore] Failed job accessed files:
        [2023-07-01T02:39:23+0800] [MainThread] [W] [toil.fileStores.abstractFileStore] Downloaded file 'files/for-job/kind-make_minigraph_fasta/instance-dns_k2ie/file-a3e9138cb3d746708827a1e699603cf0/minigraph_sequences.fa.gz' to path '/tmp/8aaeaad7b40d5243a96b21ee36df7668/6e95/dcf1/tmpfaeegpcb/_MINIGRAPH_.fa'
        [2023-07-01T02:39:23+0800] [MainThread] [W] [toil.fileStores.abstractFileStore] Downloaded file 'files/for-job/kind-split_gfa/instance-7macahhg/file-2b2eb0159856454abf321255560a4c8b/split_h2tg000088l.fa_contigs' to path '/tmp/8aaeaad7b40d5243a96b21ee36df7668/6e95/dcf1/tmpfaeegpcb/h2tg000088l.fa_contigs'
        Traceback (most recent call last):
          File "/home/songlizhi/software/cactus/cactus_env/lib/python3.9/site-packages/toil/worker.py", line 403, in workerScript
            job._runner(jobGraph=None, jobStore=jobStore, fileStore=fileStore, defer=defer)
          File "/home/songlizhi/software/cactus/cactus_env/lib/python3.9/site-packages/toil/job.py", line 2774, in _runner
            returnValues = self._run(jobGraph=None, fileStore=fileStore)
          File "/home/songlizhi/software/cactus/cactus_env/lib/python3.9/site-packages/toil/job.py", line 2691, in _run
            return self.run(fileStore)
          File "/home/songlizhi/software/cactus/cactus_env/lib/python3.9/site-packages/toil/job.py", line 2919, in run
            rValue = userFunction(*((self,) + tuple(self._args)), **self._kwargs)
          File "/home/songlizhi/software/cactus/cactus_env/lib/python3.9/site-packages/cactus/refmap/cactus_graphmap_split.py", line 511, in split_fa_into_contigs
            num_bases = int(cactus_call(parameters=size_cmd, check_output=True).strip())
          File "/home/songlizhi/software/cactus/cactus_env/lib/python3.9/site-packages/cactus/shared/common.py", line 889, in cactus_call
            raise RuntimeError("{}Command {} exited {}: {}".format(sigill_msg, call, process.returncode, out))
        RuntimeError: Command ['bash', '-c', "set -eo pipefail && bgzip -dc /tmp/8aaeaad7b40d5243a96b21ee36df7668/6e95/dcf1/tmpfaeegpcb/_MINIGRAPH__h2tg000088l.fa --threads 1 | grep -v '>' | wc | awk '{print $3-$1}'"] exited 1: stderr=[bgzip] /tmp/8aaeaad7b40d5243a96b21ee36df7668/6e95/dcf1/tmpfaeegpcb/_MINIGRAPH__h2tg000088l.fa: unknown suffix -- ignored
        [2023-07-01T02:39:23+0800] [MainThread] [E] [toil.worker] Exiting the worker because of a failed job on host fat02
<=========

No idea which step was wrong, please give me a hand, thanks.

**Comment by glennhickey** [comment]
That is indeed strange.  The `bgzip` included in cactus should not give this error
```
bgzip  --version
bgzip (htslib) 1.11
Copyright (C) 2020 Genome Research Ltd.
```

Are you sure this is the version that's being used?

**Comment by leon945945** [comment]
The bgzip version is truely 1.11.
`$~/software/cactus/bin/bgzip --version`
`bgzip (htslib) 1.11`
`Copyright (C) 2020 Genome Research Ltd.`

> bgzip -dc /tmp/8aaeaad7b40d5243a96b21ee36df7668/6e95/dcf1/tmpfaeegpcb/_MINIGRAPH__h2tg000088l.fa

This command wanted to decompress the fasta file, but the fasta file was not a gzipped file, which caused an error `unknown suffix -- ignored`. Do you know what made it incorrect?

**Comment by glennhickey** [comment]
Sorry, I don't believe you.  That error message only occurs in `1.9` and earlier.  

```
./bgzip --version | head -1
bgzip (htslib) 1.9
echo "test" | ./bgzip > test.fa && ./bgzip -dc test.fa
[bgzip] test.fa: unknown suffix -- ignored
```

```
./bgzip --version | head -1
bgzip (htslib) 1.10
echo "test" | ./bgzip > test.fa && ./bgzip -dc test.fa
test
```

```
./bgzip --version | head -1
bgzip (htslib) 1.11
echo "test" | ./bgzip > test.fa && ./bgzip -dc test.fa
test
```

```
./bgzip --version | head -1
bgzip (htslib) 1.17
echo "test" | ./bgzip > test.fa && ./bgzip -dc test.fa
test
```

**Comment by leon945945** [comment]
Well, you are right, bgzip `1.9` besides bgzip `1.11` of cactus exists in my bash environment, and `1.9` was called prior to `1.11`, no error was incurred with `1.11` used.
Thank you very much.
