### ISSUE TITLE
How to restart one job at different machine?

### ISSUE THREAD

**Issue by liu-wq** [ComparativeGenomicsToolkit/cactus#1094]
Hi, manager

Cactus-blast terminated due to memory can not support one sub job. So I want to restart the cactus-blast at another machine. But I don't know how to change the directory of the job.

For example, in which file is this path saved? How should I modify it？
`/sharedata/weiqiangliu/Private/liuwq/cactus/jobstore/12' does not exist, so there is nothing to resta
rt.`

Details: 
```[2023-07-05T21:49:04+0800] [MainThread] [I] [toil.statsAndLogging] Enabling realtime logging in Toil
[2023-07-05T21:49:04+0800] [MainThread] [I] [toil.statsAndLogging] Cactus Command: /media/rocket/program/miniconda3/envs/cactus/bin/cactus-blast jobstore/12 steps-output/33mm.txt steps-output/37.paf --ro
ot 37 --logFile steps-output/logs/blast-37.log --batchSystem single_machine --binariesMode local --maxJobs 3 --maxMemory 500G --restart
[2023-07-05T21:49:04+0800] [MainThread] [I] [toil.statsAndLogging] Cactus Commit: ce2bd972d997340845c78f69671106178ce6491e
[2023-07-05T21:49:04+0800] [MainThread] [I] [toil] Running Toil version 5.10.0-21422a3440f8a6d5e9d2f1c9695c4fbc57fa5372 on host dell-PowerEdge-T640.
[2023-07-05T21:49:04+0800] [MainThread] [I] [toil.realtimeLogger] Starting real-time logging.
[2023-07-05T21:49:05+0800] [MainThread] [I] [toil.leader] Issued job 'tile_alignments' kind-tile_alignments/instance-dozz034g v1 with job batch system ID: 0 and disk: 77.3 Gi, memory: 412.4 Gi, cores: 1,
 accelerators: [], preemptible: False
[2023-07-05T21:49:05+0800] [MainThread] [I] [toil.worker] Redirecting logging to /tmp/c3fc1539ca4559eea1ad4c120aeec9aa/023b/worker_log.txt
[2023-07-05T21:49:06+0800] [Thread-1  ] [E] [toil.batchSystems.singleMachine] Got exit code 1 (indicating failure) from job _toil_worker tile_alignments file:/media/rocket/liuwq/cactus/jobstore/12 kind-t
ile_alignments/instance-dozz034g.
[2023-07-05T21:49:06+0800] [MainThread] [W] [toil.leader] Job failed with exit value 1: 'tile_alignments' kind-tile_alignments/instance-dozz034g v1
Exit reason: None
[2023-07-05T21:49:06+0800] [MainThread] [W] [toil.leader] The job seems to have left a log file, indicating failure: 'tile_alignments' kind-tile_alignments/instance-dozz034g v2
[2023-07-05T21:49:06+0800] [MainThread] [W] [toil.leader] Log from job "kind-tile_alignments/instance-dozz034g" follows:
=========>
        [2023-07-05T21:49:05+0800] [MainThread] [I] [toil.worker] ---TOIL WORKER OUTPUT LOG---
        [2023-07-05T21:49:05+0800] [MainThread] [I] [toil] Running Toil version 5.10.0-21422a3440f8a6d5e9d2f1c9695c4fbc57fa5372 on host dell-PowerEdge-T640.
        [2023-07-05T21:49:05+0800] [MainThread] [I] [toil.worker] Working on job 'tile_alignments' kind-tile_alignments/instance-dozz034g v1
        Traceback (most recent call last):
          File "/media/rocket/program/miniconda3/envs/cactus/lib/python3.9/site-packages/toil/worker.py", line 377, in workerScript
            job = Job.loadJob(jobStore, jobDesc)
          File "/media/rocket/program/miniconda3/envs/cactus/lib/python3.9/site-packages/toil/job.py", line 2653, in loadJob
            job = cls._unpickle(userModule, fileHandle, requireInstanceOf=Job)
          File "/media/rocket/program/miniconda3/envs/cactus/lib/python3.9/site-packages/toil/job.py", line 2275, in _unpickle
            runnable = unpickler.load()
          File "/media/rocket/program/miniconda3/envs/cactus/lib/python3.9/site-packages/toil/job.py", line 3276, in __new__
            return cls._resolve(*args)
          File "/media/rocket/program/miniconda3/envs/cactus/lib/python3.9/site-packages/toil/job.py", line 3283, in _resolve
            cls._jobstore = Toil.resumeJobStore(jobStoreLocator)
          File "/media/rocket/program/miniconda3/envs/cactus/lib/python3.9/site-packages/toil/common.py", line 1160, in resumeJobStore
            jobStore.resume()
          File "/media/rocket/program/miniconda3/envs/cactus/lib/python3.9/site-packages/toil/jobStores/fileJobStore.py", line 130, in resume
            raise NoSuchJobStoreException(self.jobStoreDir)
        toil.jobStores.abstractJobStore.NoSuchJobStoreException: The job store '/sharedata/weiqiangliu/Private/liuwq/cactus/jobstore/12' does not exist, so there is nothing to resta
rt.
        [2023-07-05T21:49:06+0800] [MainThread] [E] [toil.worker] Exiting the worker because of a failed job on host dell-PowerEdge-T640
<=========```

**Comment by liu-wq** [comment]
Well,  I solved this problem with a stupid method. I created a folder with the same path on another fat node based on the missing path and successfully ran it. 

I hope it can be helpful to others.
