### ISSUE TITLE
'minigraph_construct' job failure

### ISSUE THREAD

**Issue by andreagonzam** [ComparativeGenomicsToolkit/cactus#1103]
I'm running cactus-pangenome on 44 genomes (4.2 Gbp) using three references. This is the command:

cactus-pangenome $base_dir/jobstore $data_dir/pan_seqfile.txt --outDir $out_dir --workDir $TMPDIR --outName species_pg --reference ref1 ref2 ref3 --vcf --vcfReference ref1 ref2 ref3 --consMemory 500000000000 --maxCores 45 --maxDisk 950000000000 --consCores 45 --indexCores 45 --mgCores 45 --gfa --gbz --refContigs chr1D chr2D chr3D chr4D chr5D chr6D chr7D --restart

This is the last part of the log file with the error:

[2023-07-18T14:58:50+0300] [MainThread] [I] [toil-rt] 2023-07-18 14:58:50.510995: Running the command: "mash dist TOWWC169.fa TA1675.fa.msh"
[2023-07-18T15:00:43+0300] [MainThread] [I] [toil-rt] 2023-07-18 15:00:43.172656: Successfully ran: "mash dist TOWWC169.fa TA1675.fa.msh" in 112.6582 seconds
[2023-07-18T15:01:05+0300] [MainThread] [I] [toil-rt] mash distance of TOWWC169 (size = 4144003232) to reference TA1675 = 0.00464278 sample distance = 0.00781808
[2023-07-18T15:01:06+0300] [MainThread] [I] [toil.leader] Issued job 'mash_distance_order' kind-mash_distance_order/instance-f9jjzo3p v1 with job batch system ID: 77 and disk: 2.0 Gi, memory: 2.0 Gi, cores: 1, accelerators: [], preemptible: False
[2023-07-18T15:01:08+0300] [MainThread] [I] [toil.worker] Redirecting logging to /ibex/scratch/projects/c2136/cactus/tmp_cactus/33b40a13d7e55dcf93c6d7ab49ebaa51/6f77/worker_log.txt
[2023-07-18T15:01:12+0300] [MainThread] [I] [toil.leader] Issued job 'minigraph_construct' kind-minigraph_construct/instance-hks34jro v1 with job batch system ID: 78 and disk: 863.3 Gi, memory: 2.0 Gi, cores: 45, accelerators: [], preemptible: False
[2023-07-18T15:01:12+0300] [MainThread] [I] [toil.worker] Redirecting logging to /ibex/scratch/projects/c2136/cactus/tmp_cactus/33b40a13d7e55dcf93c6d7ab49ebaa51/e093/worker_log.txt
[2023-07-18T15:02:34+0300] [Thread-1 (daddy)] [E] [toil.batchSystems.singleMachine] Got exit code 120 (indicating failure) from job _toil_worker minigraph_construct file:/ibex/scratch/projects/c2136/cactus/jobstore kind-minigraph_construct/instance-hks34jro.
[2023-07-18T15:02:34+0300] [MainThread] [W] [toil.leader] Job failed with exit value 120: 'minigraph_construct' kind-minigraph_construct/instance-hks34jro v1
Exit reason: None
[2023-07-18T15:02:34+0300] [MainThread] [W] [toil.leader] No log file is present, despite job failing: 'minigraph_construct' kind-minigraph_construct/instance-hks34jro v1
[2023-07-18T15:02:34+0300] [MainThread] [W] [toil.job] Due to failure we are reducing the remaining try count of job 'minigraph_construct' kind-minigraph_construct/instance-hks34jro v1 with ID kind-minigraph_construct/instance-hks34jro to 1
[2023-07-18T15:02:34+0300] [MainThread] [I] [toil.leader] Issued job 'minigraph_construct' kind-minigraph_construct/instance-hks34jro v2 with job batch system ID: 79 and disk: 863.3 Gi, memory: 2.0 Gi, cores: 45, accelerators: [], preemptible: False
[2023-07-18T15:02:35+0300] [MainThread] [I] [toil.worker] Redirecting logging to /ibex/scratch/projects/c2136/cactus/tmp_cactus/33b40a13d7e55dcf93c6d7ab49ebaa51/5c0e/worker_log.txt
Traceback (most recent call last):
  File "/ibex/sw/csi/cactus/2.6.0/el7.9_conda3/miniconda3/bin/_toil_worker", line 8, in <module>
    sys.exit(main())
  File "/ibex/sw/csi/cactus/2.6.0/el7.9_conda3/miniconda3/lib/python3.10/site-packages/toil/worker.py", line 731, in main
    exit_code = workerScript(jobStore, config, options.jobName, options.jobStoreID)
  File "/ibex/sw/csi/cactus/2.6.0/el7.9_conda3/miniconda3/lib/python3.10/site-packages/toil/worker.py", line 264, in workerScript
    logFh = os.open(tempWorkerLogPath, os.O_WRONLY | os.O_CREAT | os.O_APPEND)
OSError: [Errno 122] Disk quota exceeded: '/ibex/scratch/projects/c2136/cactus/tmp_cactus/33b40a13d7e55dcf93c6d7ab49ebaa51/5c0e/worker_log.txt'
[2023-07-18T15:02:35+0300] [Thread-1 (daddy)] [E] [toil.batchSystems.singleMachine] Got exit code 1 (indicating failure) from job _toil_worker minigraph_construct file:/ibex/scratch/projects/c2136/cactus/jobstore kind-minigraph_construct/instance-hks34jro.
[2023-07-18T15:02:35+0300] [MainThread] [W] [toil.leader] Job failed with exit value 1: 'minigraph_construct' kind-minigraph_construct/instance-hks34jro v2
Exit reason: None
[2023-07-18T15:02:35+0300] [MainThread] [W] [toil.leader] No log file is present, despite job failing: 'minigraph_construct' kind-minigraph_construct/instance-hks34jro v2
[2023-07-18T15:02:35+0300] [MainThread] [W] [toil.job] Due to failure we are reducing the remaining try count of job 'minigraph_construct' kind-minigraph_construct/instance-hks34jro v2 with ID kind-minigraph_construct/instance-hks34jro to 0
[2023-07-18T15:02:35+0300] [MainThread] [W] [toil.leader] Job 'minigraph_construct' kind-minigraph_construct/instance-hks34jro v3 is completely failed
[2023-07-18T15:02:43+0300] [MainThread] [I] [toil.leader] Finished toil run with 3 failed jobs.
[2023-07-18T15:02:43+0300] [MainThread] [I] [toil.leader] Failed jobs at end of the run: 'minigraph_construct' kind-minigraph_construct/instance-hks34jro v3 'sanitize_fasta_headers' kind-pangenome_end_to_end_workflow/instance-1luttcim v6 'sort_minigraph_input_with_mash' kind-minigraph_construct_workflow/instance-2kdodtmh v7
[2023-07-18T15:02:43+0300] [MainThread] [I] [toil.realtimeLogger] Stopping real-time logging server.
[2023-07-18T15:02:43+0300] [MainThread] [I] [toil.realtimeLogger] Joining real-time logging server thread.
Traceback (most recent call last):
  File "/ibex/sw/csi/cactus/2.6.0/el7.9_conda3/miniconda3/bin/cactus-pangenome", line 8, in <module>
    sys.exit(main())
  File "/ibex/sw/csi/cactus/2.6.0/el7.9_conda3/miniconda3/lib/python3.10/site-packages/cactus/refmap/cactus_pangenome.py", line 212, in main
    toil.start(Job.wrapJobFn(pangenome_end_to_end_workflow, options, config_wrapper, input_seq_id_map, input_path_map, input_seq_order))
  File "/ibex/sw/csi/cactus/2.6.0/el7.9_conda3/miniconda3/lib/python3.10/site-packages/toil/common.py", line 1064, in start
    return self._runMainLoop(rootJobDescription)
  File "/ibex/sw/csi/cactus/2.6.0/el7.9_conda3/miniconda3/lib/python3.10/site-packages/toil/common.py", line 1516, in _runMainLoop
    jobCache=self._jobCache).run()
  File "/ibex/sw/csi/cactus/2.6.0/el7.9_conda3/miniconda3/lib/python3.10/site-packages/toil/leader.py", line 289, in run
    raise FailedJobsException(self.jobStore, failed_jobs, exit_code=self.recommended_fail_exit_code)
toil.exceptions.FailedJobsException: The job store '/ibex/scratch/projects/c2136/cactus/jobstore' contains 3 failed jobs: 'minigraph_construct' kind-minigraph_construct/instance-hks34jro v3, 'sanitize_fasta_headers' kind-pangenome_end_to_end_workflow/instance-1luttcim v6, 'sort_minigraph_input_with_mash' kind-minigraph_construct_workflow/instance-2kdodtmh v7

I appreciate your help in figuring out where the error comes from.

**Comment by glennhickey** [comment]
Looks like this is probably the key line from your log
```
OSError: [Errno 122] Disk quota exceeded: '/ibex/scratch/projects/c2136/cactus/tmp_cactus/33b40a13d7e55dcf93c6d7ab49ebaa51/5c0e/worker_log.txt'
```

You can set the scratch directory to somewhere with more room using `--workDir` or the `TMPDIR` environment variable.

**Comment by andreagonzam** [comment]
The current scratch directory '/ibex/scratch/projects/c2136/cactus/tmp_cactus' has enough space. I set it using --workDir. I also checked write permissions and they are correct.

**Comment by glennhickey** [comment]
Sorry if you are getting `Disk quota exceeded` error messages for that location, that's between you and your sysadmin and there's not much I can do to help here.
