### ISSUE TITLE
Fatal error: progressive_schedule

### ISSUE THREAD

**Issue by pedro-mmartins** [ComparativeGenomicsToolkit/cactus#1107]
Hello!

I just installed Cactus, but I've come to a failure message I cannot resolve.  That's what I get:

```Due to failure we are reducing the remaining try count of job 'progressive_schedule' kind-progressive_schedule/instance-v7mj8a61 v5 with ID kind-progressive_schedule/instance-v7mj8a61 to 0
Job 'progressive_schedule' kind-progressive_schedule/instance-v7mj8a61 v6 is completely failed
Finished toil run with 3 failed jobs.
Failed jobs at end of the run: 'sanitize_fasta_headers' kind-progressive_workflow/instance-u9i5r6gx v4 'Job' kind-preprocess_all/instance-6074lnkj v5 'progressive_schedule' kind-progressive_schedule/instance-v7mj8a61 v6
Stopping real-time logging server.
Joining real-time logging server thread.
```

I was able to find what I guess is a log file from this specific job. Which says:
```
[2023-07-25T11:37:40-0300] [MainThread] [I] [toil.worker] ---TOIL WORKER OUTPUT LOG---
[2023-07-25T11:37:40-0300] [MainThread] [I] [toil] Running Toil version 5.11.0-9a04dabb36d6ab13ed1ac7c711dbdc8c71724dc9 on host r540.
[2023-07-25T11:37:40-0300] [MainThread] [I] [toil.worker] Working on job 'progressive_schedule' kind-progressive_schedule/instance-v7mj8a61 v4
[2023-07-25T11:37:41-0300] [MainThread] [I] [toil.worker] Loaded body Job('progressive_schedule' kind-progressive_schedule/instance-v7mj8a61 v4) from description 'progressive_schedule' kind-progressive_schedule/instance-v7mj8a61 v4
Traceback (most recent call last):
  File "/dados/home/pedro/Programs/cactus-bin-v2.6.4/cactus_env/lib/python3.8/site-packages/toil/worker.py", line 403, in workerScript
    job._runner(jobGraph=None, jobStore=jobStore, fileStore=fileStore, defer=defer)
  File "/dados/home/pedro/Programs/cactus-bin-v2.6.4/cactus_env/lib/python3.8/site-packages/toil/job.py", line 2774, in _runner
    returnValues = self._run(jobGraph=None, fileStore=fileStore)
  File "/dados/home/pedro/Programs/cactus-bin-v2.6.4/cactus_env/lib/python3.8/site-packages/toil/job.py", line 2691, in _run
    return self.run(fileStore)
  File "/dados/home/pedro/Programs/cactus-bin-v2.6.4/cactus_env/lib/python3.8/site-packages/toil/job.py", line 2919, in run
    rValue = userFunction(*((self,) + tuple(self._args)), **self._kwargs)
  File "/dados/home/pedro/Programs/cactus-bin-v2.6.4/cactus_env/lib/python3.8/site-packages/cactus/progressive/cactus_progressive.py", line 103, in progressive_schedule
    subtree = get_subtree(tree, event, config_wrapper, og_map)
  File "/dados/home/pedro/Programs/cactus-bin-v2.6.4/cactus_env/lib/python3.8/site-packages/cactus/progressive/progressive_decomposition.py", line 169, in get_subtree
    assert sub_tree.hasParent(node)
AssertionError
[2023-07-25T11:37:41-0300] [MainThread] [E] [toil.worker] Exiting the worker because of a failed job on host r540
```

What could be causing this issue? I tried running the example command line, for the mammal WGA, and it worked just fine, so it's not something related to the installation. Could you help me?

Thanks!

**Comment by pedro-mmartins** [comment]
Sure! Here it goes:

```
((((Cmeg:0.0184171866,(Calb:0.0214906882,Cput:0.0361534105)100:0.0090028959)100:0.0294538378,Chom:0.059936427)100:0.0062969344,Pazu:0.0458113245)100:0.0156684299,(((Lser:0.0087193443,Lcup:0.0148439095)100:0.0124624522,Lexi:0.022942623)100:0.0225108246,((Cvom:0.0140741736,Agra:0.0118908115)100:0.0131631142,Bpan:0.0402730073)100:0.0184081765)100:0.0156684299);
```
Also, an example of the path to the genomes:
```
*Bpan /home/pedro/Non_Coding_Element_Evolution/03-Masking/02-RepeatMasker/Bpan_masked.fasta
```


And the command line:
```
cactus WGA Cactus_file.txt Calliphoridae_WGA.hal --maxCores 20 --logCritical --logError --logDebug --logWarning --logInfo --logFile Cactus.log --clean onSuccess
```

**Comment by glennhickey** [comment]
You're ancestor nodes are all labelled `100`.  I guess these are bootstrap values or something, but Cactus is reading them in as names.  And the fact that they are not unique is leading to these very cryptic errors.  

This type of thing has come up many times before and Cactus should be giving a clear error message right away.  Something must have happened to turn the check off, and I'll get it fixed in the next release. 

The problem labels:

((((Cmeg:0.0184171866,(Calb:0.0214906882,Cput:0.0361534105)**100**:0.0090028959)**100**:0.0294538378,Chom:0.059936427)**100**:0.0062969344,Pazu:0.0458113245)**100**:0.0156684299,(((Lser:0.0087193443,Lcup:0.0148439095)**100**:0.0124624522,Lexi:0.022942623)**100**:0.0225108246,((Cvom:0.0140741736,Agra:0.0118908115)**100**:0.0131631142,Bpan:0.0402730073)**100**:0.0184081765)**100**:0.0156684299);

The fixed tree

((((Cmeg:0.0184171866,(Calb:0.0214906882,Cput:0.0361534105):0.0090028959):0.0294538378,Chom:0.059936427):0.0062969344,Pazu:0.0458113245):0.0156684299,(((Lser:0.0087193443,Lcup:0.0148439095):0.0124624522,Lexi:0.022942623):0.0225108246,((Cvom:0.0140741736,Agra:0.0118908115):0.0131631142,Bpan:0.0402730073):0.0184081765):0.0156684299);

**Comment by pedro-mmartins** [comment]
Those were indeed bootstrap values. Thank you so much!
