### ISSUE TITLE
ModuleNotFoundError: No module named 'toil'

### ISSUE THREAD

**Issue by alexvasilikop** [ComparativeGenomicsToolkit/cactus#1119]
Hello,
I downloaded and installed cactus v. 2.6.5 and also the dependencies on a local workstation machine with a Linux ("Ubuntu 18.10 Cosmic Cuttlefish") distribution as described here: https://github.com/ComparativeGenomicsToolkit/cactus/blob/v2.6.5/BIN-INSTALL.md.

After trying to run the test for cactus within the created virtualenvironment:
```
cactus ./jobstore ./examples/evolverMammals.txt ./evolverMammals.hal --realTimeLogging
```

I get the following error:
```
Traceback (most recent call last):
  File "/home/lege/anaconda3/bin/cactus", line 5, in <module>
    from cactus.progressive.cactus_progressive import main
  File "/home/lege/anaconda3/lib/python3.10/site-packages/cactus/progressive/cactus_progressive.py", line 20, in <module>
    from toil.lib.bioio import getTempFile
ModuleNotFoundError: No module named 'toil'
```

However when I run:
```
toil --version
```
I get:
```                                                                        
5.12.0
```

Any ideas what the problem is?
Thanks in advance
Alex

**Comment by alexvasilikop** [comment]
Not sure what the problem was but it is resolved.
