### ISSUE TITLE
Error of running on GPU cluster

### ISSUE THREAD

**Issue by polchan** [ComparativeGenomicsToolkit/cactus#1138]
Hello!

I had an error when I ran Cactus v2.6.4 using the command `cactus ./js2 ./Malus.txt ./Malus.hal --gpu 8`  on a GPU Cluster.

> [2023-08-24T10:48:49+0800] [MainThread] [W] [toil.common] XDG_RUNTIME_DIR is set to nonexistent directory /run/user/10228; your environment may be out of spec!
Traceback (most recent call last):
  File "/storage/public/apps/software/cactus/cactus-2.6.4/cactus_env/bin/cactus", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/storage/public/apps/software/cactus/cactus-2.6.4/cactus_env/lib/python3.11/site-packages/cactus/progressive/cactus_progressive.py", line 430, in main
    hal_id = toil.start(Job.wrapJobFn(progressive_workflow, options, config_node, mc_tree, og_map, input_seq_id_map))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/storage/public/apps/software/cactus/cactus-2.6.4/cactus_env/lib/python3.11/site-packages/toil/common.py", line 1064, in start
    return self._runMainLoop(rootJobDescription)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/storage/public/apps/software/cactus/cactus-2.6.4/cactus_env/lib/python3.11/site-packages/toil/common.py", line 1516, in _runMainLoop
    jobCache=self._jobCache).run()
                             ^^^^^
  File "/storage/public/apps/software/cactus/cactus-2.6.4/cactus_env/lib/python3.11/site-packages/toil/leader.py", line 251, in run
    self.innerLoop()
  File "/storage/public/apps/software/cactus/cactus-2.6.4/cactus_env/lib/python3.11/site-packages/toil/leader.py", line 763, in innerLoop
    self.checkForDeadlocks()
  File "/storage/public/apps/software/cactus/cactus-2.6.4/cactus_env/lib/python3.11/site-packages/toil/leader.py", line 797, in checkForDeadlocks
    totalRunningJobs = len(self.batchSystem.getRunningBatchJobIDs())
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/storage/public/apps/software/cactus/cactus-2.6.4/cactus_env/lib/python3.11/site-packages/toil/batchSystems/singleMachine.py", line 816, in getRunningBatchJobIDs
    self._checkOnDaddy()
  File "/storage/public/apps/software/cactus/cactus-2.6.4/cactus_env/lib/python3.11/site-packages/toil/batchSystems/singleMachine.py", line 288, in _checkOnDaddy
    raise exc
  File "/storage/public/apps/software/conda/Miniconda3-py310_23.3.1-0/envs/cactus_dependency_py311/lib/python3.11/threading.py", line 1038, in _bootstrap_inner
    self.run()
  File "/storage/public/apps/software/conda/Miniconda3-py310_23.3.1-0/envs/cactus_dependency_py311/lib/python3.11/threading.py", line 975, in run
    self._target(*self._args, **self._kwargs)
  File "/storage/public/apps/software/cactus/cactus-2.6.4/cactus_env/lib/python3.11/site-packages/toil/batchSystems/singleMachine.py", line 229, in daddy
    result = self._startChild(jobCommand, jobID,
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/storage/public/apps/software/cactus/cactus-2.6.4/cactus_env/lib/python3.11/site-packages/toil/batchSystems/singleMachine.py", line 605, in _startChild
    snapshot = accelerator_set.get_free_snapshot()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'ResourcePool' object has no attribute 'get_free_snapshot'

I noticed that you have already provided solutions to other issues, so I installed the toil v5.9.0 according to your instructions.

When I ran it again, I encountered a new error.

> [2023-08-24T11:15:09+0800] [MainThread] [I] [toil.statsAndLogging] Cactus Commit: 0121999e9d410535f8ce2e09630aef98fe273482
Traceback (most recent call last):
  File "/storage/public/apps/software/cactus/cactus-2.6.4/cactus_env/lib/python3.11/site-packages/toil/jobStores/fileJobStore.py", line 113, in initialize
    os.mkdir(self.jobStoreDir)
FileExistsError: [Errno 17] File exists: '/storage/public/home/2022060144/project/deleterious_var/msa_gpu/js2'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/storage/public/apps/software/cactus/cactus-2.6.4/cactus_env/bin/cactus", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/storage/public/apps/software/cactus/cactus-2.6.4/cactus_env/lib/python3.11/site-packages/cactus/progressive/cactus_progressive.py", line 388, in main
    with Toil(options) as toil:
  File "/storage/public/apps/software/cactus/cactus-2.6.4/cactus_env/lib/python3.11/site-packages/toil/common.py", line 971, in __enter__
    jobStore.initialize(config)
  File "/storage/public/apps/software/cactus/cactus-2.6.4/cactus_env/lib/python3.11/site-packages/toil/jobStores/fileJobStore.py", line 116, in initialize
    raise JobStoreExistsException(self.jobStoreDir)
toil.jobStores.abstractJobStore.JobStoreExistsException: The job store '/storage/public/home/2022060144/project/deleterious_var/msa_gpu/js2' already exists. Use --restart to resume the workflow, or remove the job store with 'toil clean' to start the workflow from scratch.

I want your help!!

Thanks!

**Comment by glennhickey** [comment]
Your best bet is to use the latest Cactus release, which comes with a fixed Toil.

**Comment by polchan** [comment]
Thanks for your reply! 

I will try again later.

**Comment by polchan** [comment]
> Your best bet is to use the latest Cactus release, which comes with a fixed Toil.

Thanks! I have run `cactus` successfully! But I have a new issue in running `halPhyloP`.

I use the .hal file generated in the previous step, and use the same reference genome to run `halPhyloP`, it remand me:

> hal exception caught: Reference genome, /ngsproject/bcguo/data/genome_data/MdHoney.fa, not found in alignment

so, I need your help again! 

regards

Bocheng

**Comment by glennhickey** [comment]
I don't think halPhyloP is in a great state right now.  I recommend converting to MAF and running phyloP directly on that.
