### ISSUE TITLE
error: cannot allocate memory

### ISSUE THREAD

**Issue by lyt57** [ComparativeGenomicsToolkit/cactus#1139]
when i run :`cactus ./js_grass ./test_grass.txt ./test_grass.hal --binariesMode singularity --batchSystem slurm --consCores 1 --maxJobs 1` ,I get errors :`root filesystem extraction failed: failed to copy content in staging file: write /tmp/rootfs-3900459717/archive-1314953807: cannot allocate memory`. But when i run `cactus ./js_grass ./test_grass.txt ./test_grass.hal --binariesMode singularity `,it get wor. i don't understand why i run in slurm it's can't work.
here is my error log
`[2023-08-24T12:41:14+0800] [MainThread] [W] [toil.leader] Log from job "kind-run_lastz/instance-oja72s5m" follows:
=========>
	[2023-08-24T12:41:12+0800] [MainThread] [I] [toil.worker] ---TOIL WORKER OUTPUT LOG---
	[2023-08-24T12:41:12+0800] [MainThread] [I] [toil] Running Toil version 5.10.0-21422a3440f8a6d5e9d2f1c9695c4fbc57fa5372 on host cc0803.para.bscc.
	[2023-08-24T12:41:12+0800] [MainThread] [I] [toil.worker] Working on job 'run_lastz' kind-run_lastz/instance-oja72s5m v1
	[2023-08-24T12:41:12+0800] [MainThread] [I] [toil.worker] Loaded body Job('run_lastz' kind-run_lastz/instance-oja72s5m v1) from description 'run_lastz' kind-run_lastz/instance-oja72s5m v1
	[2023-08-24T12:41:12+0800] [MainThread] [W] [toil.common] XDG_RUNTIME_DIR is set to nonexistent directory /run/user/1052; your environment may be out of spec!
	[2023-08-24T12:41:12+0800] [MainThread] [I] [toil.statsAndLogging] For distance 2.16884 for genomes files/for-job/kind-make_ingroup_to_outgroup_alignments_1/instance-y4vxqgie/cleanup/file-44e30fbc041f4bfd9e34a965a5c3672c/0.fa, files/for-job/kind-make_ingroup_to_outgroup_alignments_1/instance-y4vxqgie/cleanup/file-1eb86b6cfb2b441296a37c989bcfd241/0.fa using --step=1 --ambiguous=iupac,100,100 --ydrop=3000 lastz parameters
	[2023-08-24T12:41:12+0800] [MainThread] [I] [cactus.shared.common] Docker work dir: /tmp/6435770d63515aff98dcd707d1e5e37c/55b7/29c5/tmp7zfdgc2i
	[2023-08-24T12:41:12+0800] [MainThread] [I] [cactus.shared.common] Running the command ['singularity', '--silent', 'exec', '-u', '-B', '/tmp/6435770d63515aff98dcd707d1e5e37c/55b7/29c5/tmp7zfdgc2i:/mnt', '--pwd', '/mnt', '/public1/home/sc80041/Lyt/B73/evolution/grass/js_grass/cactus.img', 'lastz', 'Miscanthus_floridulus_0.fa[multiple][nameparse=darkspace]', 'Miscanthus_sacchariflorus_0.fa[nameparse=darkspace]', '--format=paf:minimap2', '--step=1', '--ambiguous=iupac,100,100', '--ydrop=3000']
	[2023-08-24T12:41:12+0800] [MainThread] [I] [toil-rt] 2023-08-24 12:41:12.605889: Running the command: "singularity --silent exec -u -B /tmp/6435770d63515aff98dcd707d1e5e37c/55b7/29c5/tmp7zfdgc2i:/mnt --pwd /mnt /public1/home/sc80041/Lyt/B73/evolution/grass/js_grass/cactus.img lastz Miscanthus_floridulus_0.fa[multiple][nameparse=darkspace] Miscanthus_sacchariflorus_0.fa[nameparse=darkspace] --format=paf:minimap2 --step=1 --ambiguous=iupac,100,100 --ydrop=3000"
	[2023-08-24T12:41:13+0800] [MainThread] [W] [toil.fileStores.abstractFileStore] Failed job accessed files:
	[2023-08-24T12:41:13+0800] [MainThread] [W] [toil.fileStores.abstractFileStore] Downloaded file 'files/for-job/kind-make_ingroup_to_outgroup_alignments_1/instance-y4vxqgie/cleanup/file-44e30fbc041f4bfd9e34a965a5c3672c/0.fa' to path '/tmp/6435770d63515aff98dcd707d1e5e37c/55b7/29c5/tmp7zfdgc2i/Miscanthus_floridulus_0.fa'
	[2023-08-24T12:41:13+0800] [MainThread] [W] [toil.fileStores.abstractFileStore] Downloaded file 'files/for-job/kind-make_ingroup_to_outgroup_alignments_1/instance-y4vxqgie/cleanup/file-1eb86b6cfb2b441296a37c989bcfd241/0.fa' to path '/tmp/6435770d63515aff98dcd707d1e5e37c/55b7/29c5/tmp7zfdgc2i/Miscanthus_sacchariflorus_0.fa'
	Traceback (most recent call last):
	  File "/public1/home/sc80041/wongzijie/Maize_embryo/Minigraph-Cactus/lib/python3.7/site-packages/toil/worker.py", line 403, in workerScript
	    job._runner(jobGraph=None, jobStore=jobStore, fileStore=fileStore, defer=defer)
	  File "/public1/home/sc80041/wongzijie/Maize_embryo/Minigraph-Cactus/lib/python3.7/site-packages/toil/job.py", line 2768, in _runner
	    returnValues = self._run(jobGraph=None, fileStore=fileStore)
	  File "/public1/home/sc80041/wongzijie/Maize_embryo/Minigraph-Cactus/lib/python3.7/site-packages/toil/job.py", line 2685, in _run
	    return self.run(fileStore)
	  File "/public1/home/sc80041/wongzijie/Maize_embryo/Minigraph-Cactus/lib/python3.7/site-packages/toil/job.py", line 2913, in run
	    rValue = userFunction(*((self,) + tuple(self._args)), **self._kwargs)
	  File "/public1/home/sc80041/wongzijie/Maize_embryo/Minigraph-Cactus/lib/python3.7/site-packages/cactus/paf/local_alignment.py", line 67, in run_lastz
	    cpus=cpu)
	  File "/public1/home/sc80041/wongzijie/Maize_embryo/Minigraph-Cactus/lib/python3.7/site-packages/cactus/shared/common.py", line 878, in cactus_call
	    raise RuntimeError("{}Command {} signaled {}: {}".format(sigill_msg, call, signal.Signals(-process.returncode).name, out))
	RuntimeError: Command /usr/bin/time -f "CACTUS-LOGGED-MEMORY-IN-KB: %M" singularity --silent exec -u -B /tmp/6435770d63515aff98dcd707d1e5e37c/55b7/29c5/tmp7zfdgc2i:/mnt --pwd /mnt /public1/home/sc80041/Lyt/B73/evolution/grass/js_grass/cactus.img lastz 'Miscanthus_floridulus_0.fa[multiple][nameparse=darkspace]' 'Miscanthus_sacchariflorus_0.fa[nameparse=darkspace]' --format=paf:minimap2 --step=1 --ambiguous=iupac,100,100 --ydrop=3000 signaled SIGKILL: stderr=FATAL:   while extracting /public1/home/sc80041/Lyt/B73/evolution/grass/js_grass/cactus.img: root filesystem extraction failed: failed to copy content in staging file: write /tmp/rootfs-3900459717/archive-1314953807: cannot allocate memory
	
	[2023-08-24T12:41:13+0800] [MainThread] [E] [toil.worker] Exiting the worker because of a failed job on host cc0803.para.bscc
<=========`

**Comment by glennhickey** [comment]
Hmm, that's a new one for me.  Maybe try settting TMPDIR or `--workDir` to a path you are sure exists on all the cluster nodes?

**Comment by lyt57** [comment]
> 
It still can't work and gets more errors. And "out of memory" error still exists!

here is new error logs :
`[2023-08-25T15:53:50+0800] [MainThread] [W] [toil.leader] Log from job "kind-LastzRepeatMaskJob/instance-v15qmv5w" follows:
=========>
	[2023-08-25T15:52:21+0800] [MainThread] [I] [toil.worker] ---TOIL WORKER OUTPUT LOG---
	[2023-08-25T15:52:21+0800] [MainThread] [I] [toil] Running Toil version 5.10.0-21422a3440f8a6d5e9d2f1c9695c4fbc57fa5372 on host cc1102.para.bscc.
	[2023-08-25T15:52:21+0800] [MainThread] [I] [toil.worker] Working on job 'LastzRepeatMaskJob' kind-LastzRepeatMaskJob/instance-v15qmv5w v4
	[2023-08-25T15:52:21+0800] [MainThread] [I] [toil.worker] Loaded body Job('LastzRepeatMaskJob' kind-LastzRepeatMaskJob/instance-v15qmv5w v4) from description 'LastzRepeatMaskJob' kind-LastzRepeatMaskJob/instance-v15qmv5w v4
	[2023-08-25T15:52:21+0800] [MainThread] [W] [toil.common] XDG_RUNTIME_DIR is set to nonexistent directory /run/user/1052; your environment may be out of spec!
	[2023-08-25T15:52:21+0800] [MainThread] [I] [cactus.shared.common] Work dirs: set()
	[2023-08-25T15:52:21+0800] [MainThread] [I] [cactus.shared.common] Docker work dir: /public1/home/sc80041/Lyt/B73/evolution/cactus_temp/3de729f9e398513db24884fff777a443/7329/6a1d
	[2023-08-25T15:52:21+0800] [MainThread] [I] [cactus.shared.common] Running the command ['singularity', '--silent', 'exec', '-u', '-B', '/public1/home/sc80041/Lyt/B73/evolution/cactus_temp/3de729f9e398513db24884fff777a443/7329/6a1d:/mnt', '--pwd', '/mnt', '/public1/home/sc80041/Lyt/B73/evolution/grass/js_grass/cactus.img', 'cactus_fasta_fragments.py', '--fragment=200', '--step=100', '--origin=zero']
	[2023-08-25T15:52:21+0800] [MainThread] [I] [toil-rt] 2023-08-25 15:52:21.747379: Running the command: "singularity --silent exec -u -B /public1/home/sc80041/Lyt/B73/evolution/cactus_temp/3de729f9e398513db24884fff777a443/7329/6a1d:/mnt --pwd /mnt /public1/home/sc80041/Lyt/B73/evolution/grass/js_grass/cactus.img cactus_fasta_fragments.py --fragment=200 --step=100 --origin=zero"
	[2023-08-25T15:52:43+0800] [MainThread] [W] [toil.lib.humanize] Deprecated toil method.  Please use "toil.lib.conversions.bytes2human()" instead."
	[2023-08-25T15:52:43+0800] [MainThread] [I] [toil-rt] 2023-08-25 15:52:43.231346: Successfully ran: "singularity --silent exec -u -B /public1/home/sc80041/Lyt/B73/evolution/cactus_temp/3de729f9e398513db24884fff777a443/7329/6a1d:/mnt --pwd /mnt /public1/home/sc80041/Lyt/B73/evolution/grass/js_grass/cactus.img cactus_fasta_fragments.py --fragment=200 --step=100 --origin=zero" in 21.4812 seconds and 466.1 Mi memory
	[2023-08-25T15:52:43+0800] [MainThread] [I] [toil-rt] 2023-08-25 15:52:43.244594: Running the command: "singularity --silent exec -u -B /public1/home/sc80041/Lyt/B73/evolution/cactus_temp/3de729f9e398513db24884fff777a443/7329/6a1d/tmpui8ctbaa:/mnt --pwd /mnt /public1/home/sc80041/Lyt/B73/evolution/grass/js_grass/cactus.img lastz Miscanthus_floridulus_0.fa[multiple][nameparse=darkspace] Miscanthus_floridulus_0_frag[nameparse=darkspace] --step=3 --ambiguous=iupac,100,100 --ungapped --queryhsplimit=keep,nowarn:1500 --querydepth=keep,nowarn:53 --format=general:name1,zstart1,end1,name2,zstart2+,end2+ --markend"
	[2023-08-25T15:53:07+0800] [MainThread] [W] [toil.lib.humanize] Deprecated toil method.  Please use "toil.lib.conversions.bytes2human()" instead."
	[2023-08-25T15:53:07+0800] [MainThread] [I] [toil-rt] 2023-08-25 15:53:07.010156: Successfully ran: "singularity --silent exec -u -B /public1/home/sc80041/Lyt/B73/evolution/cactus_temp/3de729f9e398513db24884fff777a443/7329/6a1d/tmpui8ctbaa:/mnt --pwd /mnt /public1/home/sc80041/Lyt/B73/evolution/grass/js_grass/cactus.img lastz 'Miscanthus_floridulus_0.fa[multiple][nameparse=darkspace]' 'Miscanthus_floridulus_0_frag[nameparse=darkspace]' --step=3 --ambiguous=iupac,100,100 --ungapped --queryhsplimit=keep,nowarn:1500 --querydepth=keep,nowarn:53 --format=general:name1,zstart1,end1,name2,zstart2+,end2+ --markend" in 23.7623 seconds and 466.3 Mi memory
	[2023-08-25T15:53:07+0800] [MainThread] [I] [toil-rt] 2023-08-25 15:53:07.013215: Running the command: "singularity --silent exec -u -B /public1/home/sc80041/Lyt/B73/evolution/cactus_temp/3de729f9e398513db24884fff777a443/7329/6a1d:/mnt --pwd /mnt /public1/home/sc80041/Lyt/B73/evolution/grass/js_grass/cactus.img cactus_covered_intervals --origin=one M=100 --queryoffsets"
	[2023-08-25T15:53:28+0800] [MainThread] [W] [toil.lib.humanize] Deprecated toil method.  Please use "toil.lib.conversions.bytes2human()" instead."
	[2023-08-25T15:53:28+0800] [MainThread] [I] [toil-rt] 2023-08-25 15:53:28.412988: Successfully ran: "singularity --silent exec -u -B /public1/home/sc80041/Lyt/B73/evolution/cactus_temp/3de729f9e398513db24884fff777a443/7329/6a1d:/mnt --pwd /mnt /public1/home/sc80041/Lyt/B73/evolution/grass/js_grass/cactus.img cactus_covered_intervals --origin=one M=100 --queryoffsets" in 21.3969 seconds and 486.0 Mi memory
	[2023-08-25T15:53:28+0800] [MainThread] [I] [toil-rt] 2023-08-25 15:53:28.416108: Running the command: "singularity --silent exec -u -B /public1/home/sc80041/Lyt/B73/evolution/cactus_temp/3de729f9e398513db24884fff777a443/7329/6a1d/tmpui8ctbaa:/mnt --pwd /mnt /public1/home/sc80041/Lyt/B73/evolution/grass/js_grass/cactus.img cactus_fasta_softmask_intervals.py --origin=one Miscanthus_floridulus_0.maskinfo"
	[2023-08-25T15:53:49+0800] [MainThread] [W] [toil.lib.humanize] Deprecated toil method.  Please use "toil.lib.conversions.bytes2human()" instead."
	[2023-08-25T15:53:49+0800] [MainThread] [I] [toil-rt] 2023-08-25 15:53:49.574811: Successfully ran: "singularity --silent exec -u -B /public1/home/sc80041/Lyt/B73/evolution/cactus_temp/3de729f9e398513db24884fff777a443/7329/6a1d/tmpui8ctbaa:/mnt --pwd /mnt /public1/home/sc80041/Lyt/B73/evolution/grass/js_grass/cactus.img cactus_fasta_softmask_intervals.py --origin=one Miscanthus_floridulus_0.maskinfo" in 21.1558 seconds and 466.2 Mi memory
	[2023-08-25T15:53:49+0800] [MainThread] [I] [toil.job] Saving graph of 1 jobs, 1 non-service, 0 new
	[2023-08-25T15:53:49+0800] [MainThread] [I] [toil.job] Processing job 'LastzRepeatMaskJob' kind-LastzRepeatMaskJob/instance-v15qmv5w v4
	Traceback (most recent call last):
	  File "/public1/home/sc80041/wongzijie/Maize_embryo/Minigraph-Cactus/lib/python3.7/site-packages/toil/worker.py", line 403, in workerScript
	    job._runner(jobGraph=None, jobStore=jobStore, fileStore=fileStore, defer=defer)
	  File "/public1/home/sc80041/wongzijie/Maize_embryo/Minigraph-Cactus/lib/python3.7/contextlib.py", line 119, in __exit__
	    next(self.gen)
	  File "/public1/home/sc80041/wongzijie/Maize_embryo/Minigraph-Cactus/lib/python3.7/site-packages/toil/deferred.py", line 193, in open
	    self._runOrphanedDeferredFunctions()
	  File "/public1/home/sc80041/wongzijie/Maize_embryo/Minigraph-Cactus/lib/python3.7/site-packages/toil/deferred.py", line 285, in _runOrphanedDeferredFunctions
	    for filename in os.listdir(self.stateDir):
	FileNotFoundError: [Errno 2] No such file or directory: '/public1/home/sc80041/Lyt/B73/evolution/cactus_temp/3de729f9e398513db24884fff777a443/deferred'
	[2023-08-25T15:53:49+0800] [MainThread] [E] [toil.worker] Exiting the worker because of a failed job on host cc1102.para.bscc
<=========`
`[2023-08-25T15:58:37+0800] [MainThread] [W] [toil.leader] Log from job "kind-run_lastz/instance-0g5roeac" follows:
=========>
	XDG_RUNTIME_DIR is set to nonexistent directory /run/user/1052; your environment may be out of spec!
	[2023-08-25T15:58:30+0800] [MainThread] [W] [toil.common] XDG_RUNTIME_DIR is set to nonexistent directory /run/user/1052; your environment may be out of spec!
	[2023-08-25T15:58:30+0800] [MainThread] [I] [toil.worker] Redirecting logging to /public1/home/sc80041/Lyt/B73/evolution/cactus_temp/a2472454b7aa5c3d847de385e24975a4/4ac9/worker_log.txt
	/var/spool/slurm/d/job4935478/slurm_script: line 4: 107015 Killed                  _toil_worker run_lastz file:/public1/home/sc80041/Lyt/B73/evolution/grass/js_grass kind-run_lastz/instance-0g5roeac --context gANjdG9pbC5iYXRjaFN5c3RlbXMuY2xlYW51cF9zdXBwb3J0CldvcmtlckNsZWFudXBDb250ZXh0CnEAKYFxAX1xAlgRAAAAd29ya2VyQ2xlYW51cEluZm9xA2N0b2lsLmJhdGNoU3lzdGVtcy5hYnN0cmFjdEJhdGNoU3lzdGVtCldvcmtlckNsZWFudXBJbmZvCnEEKFgzAAAAL3B1YmxpYzEvaG9tZS9zYzgwMDQxL0x5dC9CNzMvZXZvbHV0aW9uL2NhY3R1c190ZW1wcQVOWCQAAAA3MjRlNmNiMS0yNGJlLTQyODAtOGU5Mi1jYzkwNjdjYTcxZTJxBlgGAAAAYWx3YXlzcQd0cQiBcQlzYi4=
	slurmstepd: error: Detected 2 oom-kill event(s) in StepId=4935478.batch. Some of your processes may have been killed by the cgroup out-of-memory handler.
<=========`

**Comment by diekhans** [comment]
This error 
```Detected 2 oom-kill event(s) in StepId=4935478.batch. Some of your processes may have been killed by the cgroup out-of-memory handler
```
Indicates you have exceeded the amount of memory you have requested or are allowed.  New Toil is a good idea, but you are most likely still going to have to up your memory limits.

**Comment by lyt57** [comment]
> 

Thank you, I will try for the latest Cactus (2.6.7) / Toil (5.12.0).

**Comment by lyt57** [comment]
> 
I also think it is a memory allocation problem, but my input file is only 900k which is very small, it can run successfully on a single machine, but switching to slurm mode will report `can not allocate memory` error. Some toil jobs in the background are also killed due to out of memory. And each toil job in the background allocates a different amount of memory, Some are `sbatch -J toil_job_xx_None. --export=ALL,TOIL_RT_LOGGING_ADDRESS=127.0.0.1:49898,TOIL_RT_LOGGING_LEVEL=INFO,OMP_NUM_THREADS=1 --mem=191 --cpus-per-task=1 `(out of memory ), Some are `sbatch -J toil_job_xx_None. - export = ALL, TOIL_RT_LOGGING_ADDRESS = 127.0.0.1:49898, TOIL_RT_LOGGING_LEVEL = INFO, OMP_NUM_THREADS = 1 --mem=2048--cpus-per-task=1 `(succeeded instead). I wonder if it is related to toil job memory allocation, are there any parameters that can control toil job `--mem` size?
