### ISSUE TITLE
KtServerService failure: "too short region"

### ISSUE THREAD

**Issue by jasonsydes** [ComparativeGenomicsToolkit/cactus#114]
Hello Cactus Community!

We're running into a problem that some others have also reported (#49, #95, #97).  We have three jobs that have failed, been reattempted (twice each, which I believe is the default), and eventually landed on "is completely failed".  The job that is failing is the KtServerService job, and it is reporting the error: "too short region".  

Here is the area of the KyotoTycoon code where that "too short region" error can be found:
https://github.com/alticelabs/kyoto/blob/master/kyototycoon/kttimeddb.cc#L288

Here is a gist showing all three of the occurrences of the error in our current cactus runs (note: date/time stamps added by me):
https://gist.github.com/jasonsydes/0a68b73d73aa91d889cdd973f7bf1404
Note that all three (well, nine) failures happened within the same half hour on the same day, in case that is important.

We are running cactus/toil on top of mesos, like so:
```
/usr/bin/time -v cactus jobStore seqFile.txt out.hal \
       --batchSystem Mesos \
       --mesosMaster $leader:$port \
       --binariesMode singularity \
       --retryCount 2 \
       --stats \
       --workDir $(pwd)/workDir \
       --logFile cactus.log \
       --disableCaching \
       --containerImage $SCRIPTS_DIR/cactus-20191011.img \
       --setEnv SINGULARITY_BIND=$SINGULARITY_BIND
```
(The container image we have is the default one downloaded at that time.  We have *not* altered it, we're simply passing it in via --containerImage to save on startup time.)

It looks like we installed cactus per your instructions on Oct 9th, 2019.

Unfortunately, I didn't have "--cleanWorkDir onSuccess" enabled, so I cannot go inspect the contents of that directory.

We are using "well" masked genome assemblies (custom RepeatModeler repeat libraries plus WindowMasker).

We are running this on nodes that have 256GB of RAM and 28 cores each.

Could this be because we are running out of memory on those machines?  We can see with almost certainty that two of the three errors originated from building the ancestor of the following pairs:
1. human and marmoset (~3.3GB and ~2.9GB resp, ~6.2GB total)
2. frog and caecilian (~1.4GB and 5.3GB resp, ~6.75GB total)
Though the likely third pair of species only adds up to about 1.77GB total.

Could it be that all three were launched on the same node or something?  Thus exhausting memory somehow?

Or is this not memory related at all?

Finally, plenty of other parts of the tree have been successfully built by cactus, so the ktserver is working just fine in the vast majority of cases.  (i.e. I can see in the log plenty of messages like this:
```
Got message from job at time .... : Reference ID for experiment Anc19: b/Z/tmpJ0Eihf-run-tmp3K8tmP.tmp
```

At this point, cactus has been saying "Reissued any over long jobs" for the last 36 hours, so I suspect that the run has died.

Any assistance or insight you could provide would be greatly appreciated!!

Thank you for your time!!
Jason Sydes

PS - For your convenience, here is the last instance of failure:
```
2019-11-21 13:49:30 Issued job 'KtServerService' L/r/jobkxQf3a with job batch system ID: 1736567 and cores: 0, disk: 2.0 G, and memory: 54.2 G
2019-11-21 13:52:29 Job ended successfully: 'KtServerService' L/r/jobkxQf3a
2019-11-21 13:52:29 The job seems to have left a log file, indicating failure: 'KtServerService' L/r/jobkxQf3a
2019-11-21 13:52:29 L/r/jobkxQf3a    INFO:toil.worker:---TOIL WORKER OUTPUT LOG---
2019-11-21 13:52:29 L/r/jobkxQf3a    INFO:toil:Running Toil version 3.20.0-cf34ca3416697f2abc816b2538f20ee29ba16932.
2019-11-21 13:52:29 L/r/jobkxQf3a    INFO:cactus.shared.common:Work dirs: set([])
2019-11-21 13:52:29 L/r/jobkxQf3a    INFO:cactus.shared.common:Docker work dir: .
2019-11-21 13:52:29 L/r/jobkxQf3a    INFO:cactus.shared.common:Running the command ['singularity', '--silent', 'run', '/home/sydes/D/cactus/new_cactus_20191101/scripts/cactus-20191011.img', 'netstat', '-tuplen']
2019-11-21 13:52:29 L/r/jobkxQf3a    Running command catchsegv 'netstat' '-tuplen'
2019-11-21 13:52:29 L/r/jobkxQf3a    (Not all processes could be identified, non-owned process info
2019-11-21 13:52:29 L/r/jobkxQf3a     will not be shown, you would have to be root to see it all.)
2019-11-21 13:52:29 L/r/jobkxQf3a    INFO:cactus.shared.common:Work dirs: set([u'/home/sydes/D/cactus/new_cactus_20191101/runs/20191116_84way/workDir/toil-5f69e5e5-7253-4bc1-be04-632e87fc3dd1-a3b4e377-3860-402c-91e4-ab087d64636b/tmp94h20D/c4222ea9-7346-456d-b0c1-c99352c0ee00/trrH4ai', u'/home/sydes/D/cactus/new_cactus_20191101/runs/20191116_84way/workDir/toil-5f69e5e5-7253-4bc1-be04-632e87fc3dd1-a3b4e377-3860-402c-91e4-ab087d64636b/tmp94h20D/c4222ea9-7346-456d-b0c1-c99352c0ee00'])
2019-11-21 13:52:29 L/r/jobkxQf3a    INFO:cactus.shared.common:Docker work dir: /home/sydes/D/cactus/new_cactus_20191101/runs/20191116_84way/workDir/toil-5f69e5e5-7253-4bc1-be04-632e87fc3dd1-a3b4e377-3860-402c-91e4-ab087d64636b/tmp94h20D/c4222ea9-7346-456d-b0c1-c99352c0ee00
2019-11-21 13:52:29 L/r/jobkxQf3a    INFO:cactus.shared.common:Running the command ['singularity', '--silent', 'run', '/home/sydes/D/cactus/new_cactus_20191101/scripts/cactus-20191011.img', u'ktserver', u'-port', u'2204', u'-ls', u'-tout', u'200000', u'-th', u'64', u'-bgs', u'trrH4ai/snapshot', u'-bgsc', u'lzo', u'-bgsi', u'1000000', u'-log', u'tmpcTrpkV.tmp', u':#opts=ls#bnum=30m#msiz=50g#ktopts=p']
2019-11-21 13:52:29 L/r/jobkxQf3a    Running command catchsegv 'ktserver' '-port' '2204' '-ls' '-tout' '200000' '-th' '64' '-bgs' 'trrH4ai/snapshot' '-bgsc' 'lzo' '-bgsi' '1000000' '-log' 'tmpcTrpkV.tmp' ':#opts=ls#bnum=30m#msiz=50g#ktopts=p'
2019-11-21 13:52:29 L/r/jobkxQf3a    CRITICAL:toil.lib.bioio:Error starting ktserver.
2019-11-21 13:52:29 L/r/jobkxQf3a    CRITICAL:toil.lib.bioio:Error starting ktserver.
2019-11-21 13:52:29 L/r/jobkxQf3a    INFO:cactus.shared.common:Work dirs: set([])
2019-11-21 13:52:29 L/r/jobkxQf3a    INFO:cactus.shared.common:Docker work dir: .
2019-11-21 13:52:29 L/r/jobkxQf3a    INFO:cactus.shared.common:Running the command ['singularity', '--silent', 'run', '/home/sydes/D/cactus/new_cactus_20191101/scripts/cactus-20191011.img', 'ktremotemgr', 'remove', '-port', '2204', '-host', '172.20.0.131', 'TERMINATE']
2019-11-21 13:52:29 L/r/jobkxQf3a    WARNING:toil.fileStore:LOG-TO-MASTER: Job used more disk than requested. Consider modifying the user script to avoid the chance of failure due to incorrectly requested resources. Job y/v/jobHScqH8/g/tmpsxfCuF-_serialiseJob-stream used 1372.58% (27.5 GB [29475930112B] used, 2.0 GB [2147483648B] requested) at the end of its run.
2019-11-21 13:52:29 L/r/jobkxQf3a    Traceback (most recent call last):
2019-11-21 13:52:29 L/r/jobkxQf3a      File "/packages/miniconda/20190102/envs/cactus/lib/python2.7/site-packages/toil/worker.py", line 331, in workerScript
2019-11-21 13:52:29 L/r/jobkxQf3a        job._runner(jobGraph=jobGraph, jobStore=jobStore, fileStore=fileStore)
2019-11-21 13:52:29 L/r/jobkxQf3a      File "/packages/miniconda/20190102/envs/cactus/lib/python2.7/site-packages/toil/job.py", line 1378, in _runner
2019-11-21 13:52:29 L/r/jobkxQf3a        returnValues = self._run(jobGraph, fileStore)
2019-11-21 13:52:29 L/r/jobkxQf3a      File "/packages/miniconda/20190102/envs/cactus/lib/python2.7/site-packages/toil/job.py", line 1726, in _run
2019-11-21 13:52:29 L/r/jobkxQf3a        returnValues = self.run(fileStore)
2019-11-21 13:52:29 L/r/jobkxQf3a      File "/packages/miniconda/20190102/envs/cactus/lib/python2.7/site-packages/toil/job.py", line 1676, in run
2019-11-21 13:52:29 L/r/jobkxQf3a        startCredentials = service.start(self)
2019-11-21 13:52:29 L/r/jobkxQf3a      File "/packages/miniconda/20190102/envs/cactus/lib/python2.7/site-packages/cactus/pipeline/ktserverToil.py", line 33, in start
2019-11-21 13:52:29 L/r/jobkxQf3a        snapshotExportID=snapshotExportID)
2019-11-21 13:52:29 L/r/jobkxQf3a      File "/packages/miniconda/20190102/envs/cactus/lib/python2.7/site-packages/cactus/pipeline/ktserverControl.py", line 62, in runKtserver
2019-11-21 13:52:29 L/r/jobkxQf3a        raise RuntimeError("Unable to launch ktserver in time. Log: %s" % log)
2019-11-21 13:52:29 L/r/jobkxQf3a    RuntimeError: Unable to launch ktserver in time. Log: 2019-11-21T21:49:33.220062Z: [SYSTEM]: ================ [START]: pid=156851
2019-11-21 13:52:29 L/r/jobkxQf3a    2019-11-21T21:49:33.220382Z: [SYSTEM]: opening a database: path=:#opts=ls#bnum=30m#msiz=50g#ktopts=p
2019-11-21 13:52:29 L/r/jobkxQf3a    2019-11-21T21:49:33.258708Z: [SYSTEM]: applying a snapshot file: db=0 ts=1574371025648000000 count=86847132 size=52565076395
2019-11-21 13:52:29 L/r/jobkxQf3a    2019-11-21T21:52:28.441406Z: [ERROR]: [DB]: :: 9: system error: too short region
2019-11-21 13:52:29 L/r/jobkxQf3a    2019-11-21T21:52:28.441602Z: [ERROR]: could not apply a snapshot: system error: too short region
2019-11-21 13:52:29 L/r/jobkxQf3a    2019-11-21T21:52:28.441745Z: [SYSTEM]: starting the server: expr=:2204
2019-11-21 13:52:29 L/r/jobkxQf3a    2019-11-21T21:52:28.441834Z: [SYSTEM]: server socket opened: expr=:2204 timeout=200000.0
2019-11-21 13:52:29 L/r/jobkxQf3a    2019-11-21T21:52:28.441858Z: [SYSTEM]: listening server socket started: fd=4
2019-11-21 13:52:29 L/r/jobkxQf3a
2019-11-21 13:52:29 L/r/jobkxQf3a    ERROR:toil.worker:Exiting the worker because of a failed job on host n131
2019-11-21 13:52:29 L/r/jobkxQf3a    WARNING:toil.jobGraph:Due to failure we are reducing the remaining retry count of job 'KtServerService' L/r/jobkxQf3a with ID L/r/jobkxQf3a to 0
2019-11-21 13:52:29 Job 'KtServerService' L/r/jobkxQf3a with ID L/r/jobkxQf3a is completely failed
```

**Comment by jasonsydes** [comment]
We keep running into this error on multiple runs of cactus using 80 or so species.  We don't have this error on smaller trees (e.g. less than 10 species).

We see from here the code (see https://github.com/alticelabs/kyoto/blob/master/kyototycoon/kttimeddb.cc#L288) that kyoto is likely trying to load a snapshot file and failing for some reason (in TimedDB::load_snapshot_atomic())... maybe it's because the snapshot file is too big??

Does cactus depend on that snapshot capability?  Or could we, by hacking around, disable it so as to move past this problem?

Thank you for your help!!
Jason

**Comment by michaelkarlcoleman** [comment]
I'm working with Jason to debug this.  Here's a little more detail for anyone who may encounter this failure, or know of a solution.

It appears that at various times, Cactus will start a `ktserver` process, accumulate some data, and then shut it down in a way that causes a "snapshot" to be written.  Then later, another `ktserver` process is started with the intent that it will read that snapshot as a base for further processing.

In our case, the initial snapshot written, while quite large, is apparently corrupt, in the sense that the second `ktserver` startup cannot read it.  It's that failure than generates the "too short region" error.  As a guess, it seems likely that the snapshot is truncated for some reason, though it's possible that it was corrupted in some other way.

The `ktserver` software seems to have been intended as a _cache_, rather than as a database that can be reliably shut down and restarted without data loss.  In particular, at least under some circumstances, **`ktserver` will completely ignore write errors while writing the snapshot file**.  (We've observed this with `strace` using the `ktserver` in a fairly recent Singularity image.)

When the second `ktserver` is started and cannot read the bad snapshot, it prints some warning messages, as above, but then proceeds as if nothing is wrong.  Both of these instances of ignoring errors sort of make sense for a cache, whose snapshot contents would only be intended to speed warm-up on restart, but the behavior is disastrous if one actually cares about the saved data.

Cactus does seem to see the failure to read the snapshot, but unfortunately, simply retrying the (second) ktserver can never fix the problem with the snapshot, so it fails on every retry.  (As a detail, its attempt to kill these failed ktservers seems not to work, which leaves a number of "zombie" ktservers laying around as well.)

Several questions come to mind:

1. Is there any practical way to avoid the shutdown/startup of ktserver instances?  If we could avoid this, our runs would probably complete.

2. Has anyone looked at adding proper detection of I/O errors to the ktserver snapshot write/read processes?

3. Is it feasible to replace ktserver with a more reliable database?

Thanks for any help!

**Comment by diekhans** [comment]
We do successful shutdown and restart ktserver, however it is a
bit of a fragile piece of software and I suspect you are hitting
a bug of some kind.  We do have plans to replace it ktserver, it
hasn't been maintained for years.  Our current thinking is the
redis would fit the requirements.

sorry you are having so much pain

**Comment by michaelkarlcoleman** [comment]
Cactus does shut down and restart `ktserver`, and it often works.  Our smaller runs go to completion.  For larger runs, the sequence succeeds a number of times, but ultimately we hit a failure.  This is about a week into the run, so we've not been able to determine whether the failure is deterministic or not.

At first, I was thinking that this might be due to `ktserver` ignoring "disk full" and "quota exceeded" sorts of errors (which it does).  But having re-run under circumstances where this should not be a factor and still seeing the failures, I'm inclined to think something else is going on.  It _does_ seem to be related to the size of the run.

Looking around, I'm suspicious of this bit of code (link below).  In English, it seems to say "As soon as I see the snapshot starting to save into the fileStore (i.e., the first byte can be retrieved), I'll assume that it has completed.".  This _might_ be true for some of the fileStore implementations, but it's definitely _not_ true for the filesystem-based fileStore, which is ultimately just doing a `shutil.copyfile`.  For large snapshots, this copy can take a while, and if `ktserver` is subsequently restarted before this copy has completed, one might imagine it retrieving a truncated copy of the snapshot, which is what we seem to be observing.

https://github.com/ComparativeGenomicsToolkit/cactus/blob/master/src/cactus/pipeline/cactus_workflow.py#L301-L309

**Comment by diekhans** [comment]
I have a proposed fix to make the Toil file system job store
atomic if you would like to try it:

   https://github.com/diekhans/toil/tree/atomic-jobstore

Not sure when it will be merged into mainline Toil
due to the holidays.

Please note, if you are using NFS it can be problematic
as it isn't the best behaved file system.

**Comment by michaelkarlcoleman** [comment]
@diekhans Mark, thanks very much for working on this--on Christmas Eve no less!  We really appreciate it.  Will try it out, as soon as we can get to it.

(As a detail, we're running all of this on GPFS.)

Cheers!
Mike

**Comment by diekhans** [comment]
Everyone deserves a Toil Christmas present

Cactus was developed most on GPFS.  It is rock-solid amazing.
