### ISSUE TITLE
Runtime Error

### ISSUE THREAD

**Issue by cutykaka** [ComparativeGenomicsToolkit/cactus#1144]
Hello.

I installed Cactus as follows.

git clone https://github.com/ComparativeGenomicsToolkit/cactus.git --recursive
cd cactus
virtualenv -p python3 cactus_env
echo "export PATH=$(pwd)/bin:\$PATH" >> cactus_env/bin/activate
echo "export PYTHONPATH=$(pwd)/lib:\$PYTHONPATH" >> cactus_env/bin/activate
source cactus_env/bin/activate
python3 -m pip install -U setuptools pip
python3 -m pip install -U .
python3 -m pip install -U -r ./toil-requirement.txt

However, when I try to perform a Cactus-Pangenome analysis, I get a runtime error. Why is that? 
Do I need to install Docker separately?

Traceback (most recent call last):
  File "/BiO/Program/cactus/cactus_env/lib/python3.7/site-packages/cactus/shared/common.py", line 378, in setupBinaries
    verify_local()
  File "/BiO/Program/cactus/cactus_env/lib/python3.7/site-packages/cactus/shared/common.py", line 370, in verify_local
    raise RuntimeError("Cactus isn't using Docker, but it can't find "
RuntimeError: Cactus isn't using Docker, but it can't find the Cactus binaries. Please add Cactus's bin directory to your PATH (and run `make` in the Cactus directory if you haven't already).

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/BiO/Program/cactus/cactus_env/bin/cactus-pangenome", line 8, in <module>
    sys.exit(main())
  File "/BiO/Program/cactus/cactus_env/lib/python3.7/site-packages/cactus/refmap/cactus_pangenome.py", line 117, in main
    setupBinaries(options)
  File "/BiO/Program/cactus/cactus_env/lib/python3.7/site-packages/cactus/shared/common.py", line 381, in setupBinaries
    verify_docker()
  File "/BiO/Program/cactus/cactus_env/lib/python3.7/site-packages/cactus/shared/common.py", line 363, in verify_docker
    raise RuntimeError("The `docker` executable wasn't found on the "
RuntimeError: The `docker` executable wasn't found on the system. Please install Docker if possible, or use --binariesMode local and add cactus's bin directory to your PATH.

This is my command line.
cactus-pangenome ./ testPangenome.txt --reference Bae --outDir test-pg --outName test-pg

Thank you.

**Comment by cutykaka** [comment]
solved! Thank you!!
