### ISSUE TITLE
Unexpected character error with sanitize_fasta_header 

### ISSUE THREAD

**Issue by CDeMasi** [ComparativeGenomicsToolkit/cactus#1170]
Hi! I'm having a problem when trying to run cactus on Slurm. When I run cactus it seems to throw this error for each fasta file during sanitize_fasta_header: ERROR: !!Got an unexpected character in input fasta sequence: '<' . I've checked all the files and confirmed that there is no such character in any of my files. I tried adjusting the amount of memory because I wasn't sure if it was a memory issue, but that didn't fix the problem. I'm not sure what's causing this or how to fix it. The log output looks like this: 

<=========
Log from job "'sanitize_fasta_header' kind-sanitize_fasta_header/instance-n8n1pcet v18" follows:
=========>
        [2023-09-23T17:24:01+0000] [MainThread] [I] [toil.worker] ---TOIL WORKER OUTPUT LOG---
        [2023-09-23T17:24:01+0000] [MainThread] [I] [toil] Running Toil version 5.12.0-6d5a5b83b649cd8adf34a5cfe89e7690c95189d3 on host cpu001.
        [2023-09-23T17:24:01+0000] [MainThread] [I] [toil.worker] Working on job 'sanitize_fasta_header' kind-sanitize_fasta_header/instance-n8n1pcet v16
        [2023-09-23T17:24:01+0000] [MainThread] [I] [toil.worker] Loaded body Job('sanitize_fasta_header' kind-sanitize_fasta_header/instance-n8n1pcet v16) from description 'sanitize_fasta_header' kind-sanitize_fasta_header/instance-n8n
1pcet v16
        [2023-09-23T17:24:01+0000] [MainThread] [I] [cactus.shared.common] Running the command ['cactus_sanitizeFastaHeaders', '/tmp/3a8145aec1d753e4af9706ba3c3adbf5/c13d/eb6b/tmpf13cp_hg/threespine.fa', 'threespine']
        [2023-09-23T17:24:01+0000] [MainThread] [I] [toil-rt] 2023-09-23 17:24:01.641712: Running the command: "cactus_sanitizeFastaHeaders /tmp/3a8145aec1d753e4af9706ba3c3adbf5/c13d/eb6b/tmpf13cp_hg/threespine.fa threespine"
        [2023-09-23T17:24:01+0000] [MainThread] [W] [toil.fileStores.abstractFileStore] Failed job accessed files:
        [2023-09-23T17:24:01+0000] [MainThread] [W] [toil.fileStores.abstractFileStore] Downloaded file 'files/no-job/file-afe451987c9c4b6b9f31383ef6297eac/stream' to path '/tmp/3a8145aec1d753e4af9706ba3c3adbf5/c13d/eb6b/tmpf13cp_hg/thr
eespine.fa'
        Traceback (most recent call last):
          File "/home/cdemasi/.conda/envs/cactus_env/lib/python3.8/site-packages/toil/worker.py", line 403, in workerScript
            job._runner(jobGraph=None, jobStore=jobStore, fileStore=fileStore, defer=defer)
          File "/home/cdemasi/.conda/envs/cactus_env/lib/python3.8/site-packages/toil/job.py", line 2774, in _runner
            returnValues = self._run(jobGraph=None, fileStore=fileStore)
          File "/home/cdemasi/.conda/envs/cactus_env/lib/python3.8/site-packages/toil/job.py", line 2691, in _run
            return self.run(fileStore)
          File "/home/cdemasi/.conda/envs/cactus_env/lib/python3.8/site-packages/toil/job.py", line 2919, in run
            rValue = userFunction(*((self,) + tuple(self._args)), **self._kwargs)
          File "/home/cdemasi/.conda/envs/cactus_env/lib/python3.8/site-packages/cactus/preprocessor/checkUniqueHeaders.py", line 70, in sanitize_fasta_header
            cactus_call(parameters=cmd, outfile=out_fa_path)
          File "/home/cdemasi/.conda/envs/cactus_env/lib/python3.8/site-packages/cactus/shared/common.py", line 889, in cactus_call
            raise RuntimeError("{}Command {} exited {}: {}".format(sigill_msg, call, process.returncode, out))
        RuntimeError: Command ['cactus_sanitizeFastaHeaders', '/tmp/3a8145aec1d753e4af9706ba3c3adbf5/c13d/eb6b/tmpf13cp_hg/threespine.fa', 'threespine'] exited 1: stderr=[0x408d3a]
        [0x403072]
        [0x401ac2]
        [0x411c2a]
        [0x413487]
        [0x401b45]
        ERROR: !!Got an unexpected character in input fasta sequence: '<'

**Comment by glennhickey** [comment]
It's not a memory issue.  Like it says, it's convinced there is a '<' character in `threespine.fa`.  

For reference, the check happens [here](https://github.com/ComparativeGenomicsToolkit/sonLib/blob/master/C/impl/bioioC.c#L196-L199) in the code.

**Comment by GabrieleRigano99** [comment]
Hi, I'm having the same issue

**Comment by glennhickey** [comment]
Can you look in the log and find the FASTA file it's complaining about? In the above log it's
```
Running the command: "cactus_sanitizeFastaHeaders /tmp/3a8145aec1d753e4af9706ba3c3adbf5/c13d/eb6b/tmpf13cp_hg/threespine.fa threespine"
```
so it'd be whichever file corresponds to `threespine` in the input seqfile.  Once you've found that, unzip it (if it's compressed) and then run
```
cactus_sanitizeFastaHeaders <fasta file> threespine
```
If you get the same error, and are sure there is no '<' in this file, please share it with me if possible and I'll figure out what's going on.  Otherwise, I don't have a way of reproducing it.

**Comment by GabrieleRigano99** [comment]
unfortunately i can't find the file in the tmp/ directory. Here there are the files I'm trying to use: https://github.com/GabrieleRigano99/cactus_prv
The command I'm running is this one: cactus-pangenome ./js ../media/cactus_br/CACTUSBRAS.txt --outDir bras1-pg --outName bras-pg --reference foldedSB02 --vcf --giraffe --gfa --gbz

**Comment by GabrieleRigano99** [comment]
this is the CACTUSBRAS.txt file I'm using: 
foldedSB02	https://github.com/GabrieleRigano99/cactus_prv/blob/main/foldedSB02.fa
foldedSB01	https://github.com/GabrieleRigano99/cactus_prv/blob/main/foldedSB01.fa

**Comment by glennhickey** [comment]
According to your log, inside `../media/cactus_br/CACTUSBRAS.txt` you have a line that looks like
```
threespine <path-to-threespine fasta file>
```
This is the fasta file I'd like you to check with `cactus_sanitizeFastaHeaders` as [described above](https://github.com/ComparativeGenomicsToolkit/cactus/issues/1170#issuecomment-1743046947).

**Comment by GabrieleRigano99** [comment]
I'm sorry but i can't find any line with "threespine ecc" in my log.
I tried running cactus_sanitizeFastaHeaders on my files and it didn t give me any error. Could you please try running the commands with my files? sorry for the time waste.

**Comment by GabrieleRigano99** [comment]
at last i managed to understand the problem and fix it: probably when importing the files from my Github page it changed them or something like that.
FIX: I just imported the files into the docker container and ran it locally
making the CACTUSBRAS.txt like this: 
SB02 cactus_assemblies_bras/cactusSB02.fa.gz
SB01 cactus_assemblies_bras/cactusSB01.fa.gz
