### ISSUE TITLE
RuntimeError: Branch length 

### ISSUE THREAD

**Issue by vinitamehlawat** [ComparativeGenomicsToolkit/cactus#1184]
Hi, 
Thank you for this useful tool. 

I wanted to align 12 vertebrate genomes with 4 outgroups. I simply tried `cactus ./js ./seqfile_Noto.txt ./seqfile_Noto.hal`. In seqfile I also put * infront of all 4 outgroups.  **I got this following error:**
`Traceback (most recent call last):
  File "/share/apps/python/anaconda-3.13/envs/cactus-3.13/bin/cactus", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/share/apps/python/anaconda-3.13/envs/cactus-3.13/lib/python3.11/site-packages/cactus/progressive/cactus_progressive.py", line 406, in main
    mc_tree, input_seq_map, og_candidates = parse_seqfile(options.seqFile, config_wrapper, root_name = options.root)
                                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/share/apps/python/anaconda-3.13/envs/cactus-3.13/lib/python3.11/site-packages/cactus/progressive/progressive_decomposition.py", line 47, in parse_seqfile
    check_branch_lengths(mc_tree)
  File "/share/apps/python/anaconda-3.13/envs/cactus-3.13/lib/python3.11/site-packages/cactus/progressive/progressive_decomposition.py", line 258, in check_branch_lengths
    raise RuntimeError("Branch length of {} between {} and {} is too long. Branch lengths of input tree must reflect expected substitutions per (neutral) site and not exceed {}".format(
RuntimeError: Branch length of 38.43094 between Anc01 and Eleginops_maclovinus is too long. Branch lengths of input tree must reflect expected substitutions per (neutral) site and not exceed 25.0`

It would be great if you could suggest  possible solution for this problem.

2. I have another queries regarding timing thing, My each genome is around 600-700Mbp in size so how to assign the node/threads so that I can speed up the alignment process.
 
Thank you

**Comment by glennhickey** [comment]
Let's highlight the the relevant part of the error message

>Branch length of 38.43094 between Anc01 and Eleginops_maclovinus is too long. Branch lengths of input tree must reflect expected substitutions per (neutral) site and not exceed 25.0

In other words, the branch lengths in your input tree must reflect substitutions per site. 38 is not a valid value for this.

**Comment by vinitamehlawat** [comment]
It would be great if you could suggest possible solution to correct this issue, I got the tree from time tree.

**Comment by glennhickey** [comment]
Time tree gives branch lengths in terms of millions of years, which Cactus doesn't support.  Cactus will run if you just don't specify branch lengths, but it is not ideal.  If you can't find a tree for your species in the literature, you can try building your own with something like [mashtree](https://github.com/lskatz/mashtree) (though for longer branch lengths it will be less reliable -- you can check it against the one from time tree) or another tool.

Estimating a good species tree from whole genomes is tricky, We're working on a method to do this in conjunction with Cactus and hoping to release it soon.

**Comment by vinitamehlawat** [comment]
Thank you so much! for your prompt responses. I will work on it

**Comment by vinitamehlawat** [comment]
Hi, I tried out to generate a tree with single busco copy of 1 orthologous group to get the tree topology similar to time tree. I tried cactus with that tree and it's running.

`My question is that , is that correct way to do that or we should include maximum number of genes (Let's say 20 gene)'


Thank you!

**Comment by vinitamehlawat** [comment]
I forgot to tell that tree generated by single orthologous gene have topology similar to what I got from time tree but branch lengths are not clear.
