### ISSUE TITLE
Errors with latest version of minigraph cactus

### ISSUE THREAD

**Issue by CEPHAS-01** [ComparativeGenomicsToolkit/cactus#1185]
Hi
many thanks to you for this tool and maintaining it.

Please I need your help to resolve these issues.

I downloaded the pre-compiled binaries for Linux for the latest release [Cactus 2.6.8 2023-09-28](https://github.com/ComparativeGenomicsToolkit/cactus/releases/tag/v2.6.8) and installed using the information in the BIN-INSTALL.md  file.

On successful installation, I typed in the command "cactus" just to check if it works and I got the following warning messages displayed before the usage information

<frozen importlib._bootstrap>:1049: ImportWarning: _SixMetaPathImporter.find_spec() not found; falling back to find_module()
<frozen importlib._bootstrap>:673: ImportWarning: _SixMetaPathImporter.exec_module() not found; falling back to load_module()
/packages/cactus-bin-v2.6.8/venv-cactus-v2.6.8/lib/python3.11/site-packages/boto/plugin.py:40: DeprecationWarning: the imp module is deprecated in favour of importlib and slated for removal in Python 3.12; see the module's documentation for alternative uses
  import imp
<frozen importlib._bootstrap>:1049: ImportWarning: _SixMetaPathImporter.find_spec() not found; falling back to find_module()
<frozen importlib._bootstrap>:1049: ImportWarning: _SixMetaPathImporter.find_spec() not found; falling back to find_module()
/packages/cactus-bin-v2.6.8/venv-cactus-v2.6.8/lib/python3.11/site-packages/cactus/shared/common.py:14: DeprecationWarning: 'pipes' is deprecated and slated for removal in Python 3.13
  import pipes
<frozen importlib._bootstrap>:1049: ImportWarning: _SixMetaPathImporter.find_spec() not found; falling back to find_module()
<frozen importlib._bootstrap>:1049: ImportWarning: _SixMetaPathImporter.find_spec() not found; falling back to find_module()
/packages/cactus-bin-v2.6.8/venv-cactus-v2.6.8/lib/python3.11/site-packages/toil/cwl/__init__.py:17: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
  from pkg_resources import DistributionNotFound, get_distribution
<frozen importlib._bootstrap>:1049: ImportWarning: _SixMetaPathImporter.find_spec() not found; falling back to find_module()

Afterwards I tried to run a slurm job of the cactus-pangenome pipeline with the following command within a job submission script

cactus-pangenome \
         $jobStorePath \
         $seqFile \
         --outDir $outDir \
         --outName $outNamePrefix \
         --reference $reference \
         --giraffe $typeOptions --vcf $typeOptions --odgi $typeOptions --gbz $typeOptions
         --batchSystem slurm \
         --mgCores $numCores --mapCores $numCores --consCores $numCores
         

I got the following error:

{The warning block posted above, and the following}…

[2023-10-02T18:55:08-0500] [MainThread] [I] [toil.statsAndLogging] Enabling realtime logging in Toil
[2023-10-02T18:55:08-0500] [MainThread] [I] [toil.statsAndLogging] Cactus Command: //packages/cactus-bin-v2.6.8/venv-ca
ctus-v2.6.8/bin/cactus-pangenome /inFilescactus/jobStore/ /cactus/seqFile.txt --outDir /inFilescactus/outDir/ --outName sheepCactus --reference merino --giraffe full clip filter --vcf full clip filter --odgi full clip filter --gbz full clip filter
[2023-10-02T18:55:08-0500] [MainThread] [I] [toil.statsAndLogging] Cactus Commit: ec14dd6d273843b00b13138414bddcf9d5f8d067
//packages/cactus-bin-v2.6.8/venv-cactus-v2.6.8/lib/python3.11/site-packages/cactus/progressive/seqFile.py:68: Resource
Warning: unclosed file <_io.TextIOWrapper name='/inFilescactus/seqFile.txt' mode='r' encoding='UTF-8'>
  self.parseFile(path, root_name)
ResourceWarning: Enable tracemalloc to get the object allocation traceback
[2023-10-02T18:55:08-0500] [MainThread] [I] [toil.statsAndLogging] Importing file:///inFilessample1/sample1_
asm.fasta
//packages/cactus-bin-v2.6.8/venv-cactus-v2.6.8/lib/python3.11/site-packages/toil/lib/compatibility.py:10: DeprecationW
arning: WARNING: "importFile()" is deprecated.  Please use "import_file()" instead.
  warnings.warn(f'WARNING: "{func.__name__}()" is deprecated.  Please use "{new_function_name}()" instead.',
[2023-10-02T18:55:13-0500] [MainThread] [I] [toil.statsAndLogging] Importing file:///inFilessample2/sample2_
asm.fasta
[2023-10-02T18:55:13-0500] [MainThread] [I] [toil.statsAndLogging] Importing file:///inFilessample3/sample3_asm.fasta
[2023-10-02T18:55:13-0500] [MainThread] [I] [toil.statsAndLogging] Importing file:///inFilessample4/sample4_asm.fasta
[2023-10-02T18:55:13-0500] [MainThread] [I] [toil.statsAndLogging] Importing file:///inFilessample5/sample5_asm.fasta
[2023-10-02T18:55:13-0500] [MainThread] [I] [toil.statsAndLogging] Importing file:///inFilessample6/sample6_asm.fasta
[2023-10-02T18:55:13-0500] [MainThread] [I] [toil.statsAndLogging] Importing file:///inFilessample7/sample7_asm.fasta
[2023-10-02T18:55:13-0500] [MainThread] [I] [toil.statsAndLogging] Importing file:///inFilessample8/sample8_asm.fasta
Traceback (most recent call last):
  File "/packages/cactus-bin-v2.6.8/venv-cactus-v2.6.8/bin/cactus-pangenome", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/packages/cactus-bin-v2.6.8/venv-cactus-v2.6.8/lib/python3.11/site-packages/cactus/refmap/cactus_pangenome.py", line 214, in main
    toil.start(Job.wrapJobFn(pangenome_end_to_end_workflow, options, config_wrapper, input_seq_id_map, input_path_map, input_seq_order))
  File "/packages/cactus-bin-v2.6.8/venv-cactus-v2.6.8/lib/python3.11/site-packages/toil/common.py", line 1043, in start
    self._batchSystem = self.createBatchSystem(self.config)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/packages/cactus-bin-v2.6.8/venv-cactus-v2.6.8/lib/python3.11/site-packages/toil/common.py", line 1192, in createBatchSystem
    return batch_system(**kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/packages/cactus-bin-v2.6.8/venv-cactus-v2.6.8/lib/python3.11/site-packages/toil/batchSystems/singleMachine.py", line 163, in __init__
    self.accelerator_identities = get_individual_local_accelerators()
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/packages/cactus-bin-v2.6.8/venv-cactus-v2.6.8/lib/python3.11/site-packages/toil/lib/accelerators.py", line 116, in get_individual_local_accelerators
    return [{'kind': 'gpu', 'brand': 'nvidia', 'api': 'cuda', 'count': 1} for _ in range(count_nvidia_gpus())]
                                                                                         ^^^^^^^^^^^^^^^^^^^
  File "/packages/cactus-bin-v2.6.8/venv-cactus-v2.6.8/lib/python3.11/site-packages/toil/lib/accelerators.py", line 96, in count_nvidia_gpus
    subprocess.check_output(["nvidia-smi", "-q", "-x"])
  File "/software/el9/apps/python_3/3.11.1/lib/python3.11/subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/software/el9/apps/python_3/3.11.1/lib/python3.11/subprocess.py", line 548, in run
    with Popen(*popenargs, **kwargs) as process:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/software/el9/apps/python_3/3.11.1/lib/python3.11/subprocess.py", line 1024, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/software/el9/apps/python_3/3.11.1/lib/python3.11/subprocess.py", line 1901, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
NotADirectoryError: [Errno 20] Not a directory: 'nvidia-smi'
/var/spool/slurmd/job10481790/slurm_script: line 42: --batchSystem: command not found
(END)

Could you please guide me on how to resolve these?
Many thanks in advance.

Temitayo

**Comment by glennhickey** [comment]
I think you have a version of Python that is returning an exception that Toil doesn't expect, presumably because it's so new. So I think you'll have to try using an older version of Python to get this working right away (like 3.11 or 3.10).  I've proposed a Toil patch here: https://github.com/DataBiosphere/toil/pull/4611 but it'll probably take some time to make its way into a release...

**Comment by CEPHAS-01** [comment]
Thanks for the prompt feedback.
I will try an older version of Python as you have suggested and revert.

**Comment by CEPHAS-01** [comment]
Downgrading the Python to 3.8 solved the initial problem.

I was then faced with the issue with accelerators.py looking for nvidia-smi when I clearly do not have any GPUs installed, but I fixed it with the method described here https://github.com/ComparativeGenomicsToolkit/cactus/issues/937 

So far, it is running well.

Thanks for your help.

Temitayo

**Comment by CEPHAS-01** [comment]
Downgrading the Python to 3.8 solved the initial problem.

I was then faced with the issue with accelerators.py looking for nvidia-smi when I clearly do not have any GPUs installed, but I fixed it with the method described here https://github.com/ComparativeGenomicsToolkit/cactus/issues/937 

So far, it is running well.

Thanks for your help.

Temitayo
