### ISSUE TITLE
progressive workflow job failing on slurm

### ISSUE THREAD

**Issue by MCH74** [ComparativeGenomicsToolkit/cactus#1206]
Hi,

I'm trying to run the following script on slurm:

##############
#SBATCH --mem 100G
#SBATCH --cpus-per-task=10
#SBATCH -o cactus_slurm.txt

set -e

source /etc/profile.d/modules.sh

source ~/.bashrc
export PATH=/global/group/home/harrisom/.local/bin/:$PATH
virtualenv -p python3 cactus_env
source cactus_env/bin/activate

export TOIL_SLURM_ARGS="--nice=5000"

cactus ./js cactusIn.txt cactus.out --batchSystem slurm --consCores 10

##############
And getting the error that a progressive workflow job is failing:

[2023-10-26T13:46:29+0200] [MainThread] [W] [toil.leader] Job failed with exit value 1: 'progressive_workflow' kind-progressive_workflow/instance-ashhnp6r v1
Exit reason: None

Any ideas?

Thanks,
Mark

Here is the full output:
##################
created virtual environment CPython3.10.12.final.0-64 in 21697ms
  creator CPython3Posix(dest=/EBB-ZIVNFS/harrisom/SlaveMakerSelection/WithoutTEs/WithoutContamination/WholeGenomeAlignment/cactus_env, clear=False, no_vcs_ignore=False, global=False)
  seeder FromAppData(download=False, pip=bundle, setuptools=bundle, wheel=bundle, via=copy, app_data_dir=/global/group/home/harrisom/.local/share/virtualenv)
    added seed packages: pip==23.2.1, setuptools==68.2.2, wheel==0.41.2
  activators BashActivator,CShellActivator,FishActivator,NushellActivator,PowerShellActivator,PythonActivator
[2023-10-26T13:46:18+0200] [MainThread] [I] [toil.statsAndLogging] Enabling realtime logging in Toil
[2023-10-26T13:46:18+0200] [MainThread] [I] [toil.statsAndLogging] Cactus Command: /global/group/home/harrisom/.local/bin/cactus ./js cactusIn.txt cactus.out --batchSystem slurm --consCores 10
[2023-10-26T13:46:18+0200] [MainThread] [I] [toil.statsAndLogging] Cactus Commit: 0c56e78b93d6e79c2e995b6b7a78cfe3a9958c60
[2023-10-26T13:46:18+0200] [MainThread] [I] [toil.statsAndLogging] Tree: ((mpha:0.0879591833,cobs:0.1023182859)Anc01:0.00491737405,((ppun:0.0723776616,(mgra:0.0717903033,afer:0.0544205725)Anc05:0.0059418947)Anc03:0.0036036103,((lace:0.0047444107,hsub:0.0049109667)Anc06:0.0258005162,(trug:0.0093836724,((tnyl:0.0062972135,tuni:0.0099701548)Anc09:0.0014623369,(mrav:0.0101771647,(tame:0.010978095,(tpil:0.0032367004,(tlon:0.0022592311,tamb:0.0025562235)Anc13:0.0004867098)Anc12:0.004229821)Anc11:0.0014364786)Anc10:0.0032516888)Anc08:0.0034968454)Anc07:0.0215116863)Anc04:0.0156533269)Anc02:0.00491737405)Anc00;
[2023-10-26T13:46:18+0200] [MainThread] [I] [toil.statsAndLogging] Importing file:///EBB-ZIVNFS/harrisom/SlaveMakerSelection/WithoutTEs/WithoutContamination/Genomes/afer.fa
[2023-10-26T13:46:24+0200] [MainThread] [I] [toil.statsAndLogging] Importing file:///EBB-ZIVNFS/harrisom/SlaveMakerSelection/WithoutTEs/WithoutContamination/Genomes/cobs.fa
[2023-10-26T13:46:24+0200] [MainThread] [I] [toil.statsAndLogging] Importing file:///EBB-ZIVNFS/harrisom/SlaveMakerSelection/WithoutTEs/WithoutContamination/Genomes/hsub.fa
[2023-10-26T13:46:24+0200] [MainThread] [I] [toil.statsAndLogging] Importing file:///EBB-ZIVNFS/harrisom/SlaveMakerSelection/WithoutTEs/WithoutContamination/Genomes/lace.fa
[2023-10-26T13:46:24+0200] [MainThread] [I] [toil.statsAndLogging] Importing file:///EBB-ZIVNFS/harrisom/SlaveMakerSelection/WithoutTEs/WithoutContamination/Genomes/mgra.fa
[2023-10-26T13:46:24+0200] [MainThread] [I] [toil.statsAndLogging] Importing file:///EBB-ZIVNFS/harrisom/SlaveMakerSelection/WithoutTEs/WithoutContamination/Genomes/mpha.fa
[2023-10-26T13:46:24+0200] [MainThread] [I] [toil.statsAndLogging] Importing file:///EBB-ZIVNFS/harrisom/SlaveMakerSelection/WithoutTEs/WithoutContamination/Genomes/mrav.fa
[2023-10-26T13:46:24+0200] [MainThread] [I] [toil.statsAndLogging] Importing file:///EBB-ZIVNFS/harrisom/SlaveMakerSelection/WithoutTEs/WithoutContamination/Genomes/ppun.fa
[2023-10-26T13:46:24+0200] [MainThread] [I] [toil.statsAndLogging] Importing file:///EBB-ZIVNFS/harrisom/SlaveMakerSelection/WithoutTEs/WithoutContamination/Genomes/tamb.fa
[2023-10-26T13:46:24+0200] [MainThread] [I] [toil.statsAndLogging] Importing file:///EBB-ZIVNFS/harrisom/SlaveMakerSelection/WithoutTEs/WithoutContamination/Genomes/tame_withoutContamination.fa
[2023-10-26T13:46:24+0200] [MainThread] [I] [toil.statsAndLogging] Importing file:///EBB-ZIVNFS/harrisom/SlaveMakerSelection/WithoutTEs/WithoutContamination/Genomes/tlon_withoutContamination.fa
[2023-10-26T13:46:24+0200] [MainThread] [I] [toil.statsAndLogging] Importing file:///EBB-ZIVNFS/harrisom/SlaveMakerSelection/WithoutTEs/WithoutContamination/Genomes/tnyl_withoutContamination.fa
[2023-10-26T13:46:24+0200] [MainThread] [I] [toil.statsAndLogging] Importing file:///EBB-ZIVNFS/harrisom/SlaveMakerSelection/WithoutTEs/WithoutContamination/Genomes/tpil.fa
[2023-10-26T13:46:24+0200] [MainThread] [I] [toil.statsAndLogging] Importing file:///EBB-ZIVNFS/harrisom/SlaveMakerSelection/WithoutTEs/WithoutContamination/Genomes/trug.fa
[2023-10-26T13:46:24+0200] [MainThread] [I] [toil.statsAndLogging] Importing file:///EBB-ZIVNFS/harrisom/SlaveMakerSelection/WithoutTEs/WithoutContamination/Genomes/tuni.fa
[2023-10-26T13:46:25+0200] [MainThread] [W] [toil.common] Batch system does not support auto-deployment. The user script ModuleDescriptor(dirPath='/home/harrisom/.local/lib/python3.10/site-packages', name='cactus.progressive.cactus_progressive', fromVirtualEnv=False) will have to be present at the same location on every worker.
[2023-10-26T13:46:25+0200] [MainThread] [I] [toil.job] Saving graph of 1 jobs, 1 non-service, 1 new
[2023-10-26T13:46:25+0200] [MainThread] [I] [toil.job] Processing job 'progressive_workflow' kind-progressive_workflow/instance-ashhnp6r v0
[2023-10-26T13:46:25+0200] [MainThread] [I] [toil] Running Toil version 5.12.0-6d5a5b83b649cd8adf34a5cfe89e7690c95189d3 on host ebbsrv04.
[2023-10-26T13:46:25+0200] [MainThread] [I] [toil.realtimeLogger] Starting real-time logging.
[2023-10-26T13:46:25+0200] [MainThread] [I] [toil.leader] Issued job 'progressive_workflow' kind-progressive_workflow/instance-ashhnp6r v1 with job batch system ID: 1 and disk: 2.0 Gi, memory: 2.0 Gi, cores: 1, accelerators: [], preemptible: False
[2023-10-26T13:46:27+0200] [MainThread] [I] [toil.leader] 1 jobs are running, 0 jobs are issued and waiting to run
[2023-10-26T13:46:29+0200] [MainThread] [W] [toil.leader] Job failed with exit value 1: 'progressive_workflow' kind-progressive_workflow/instance-ashhnp6r v1
Exit reason: None
[2023-10-26T13:46:29+0200] [MainThread] [W] [toil.leader] No log file is present, despite job failing: 'progressive_workflow' kind-progressive_workflow/instance-ashhnp6r v1
[2023-10-26T13:46:29+0200] [MainThread] [W] [toil.job] Due to failure we are reducing the remaining try count of job 'progressive_workflow' kind-progressive_workflow/instance-ashhnp6r v1 with ID kind-progressive_workflow/instance-ashhnp6r to 5
[2023-10-26T13:46:29+0200] [MainThread] [I] [toil.leader] Issued job 'progressive_workflow' kind-progressive_workflow/instance-ashhnp6r v2 with job batch system ID: 2 and disk: 2.0 Gi, memory: 2.0 Gi, cores: 1, accelerators: [], preemptible: False
[2023-10-26T13:46:31+0200] [MainThread] [W] [toil.leader] Job failed with exit value 1: 'progressive_workflow' kind-progressive_workflow/instance-ashhnp6r v2
Exit reason: None
[2023-10-26T13:46:31+0200] [MainThread] [W] [toil.leader] No log file is present, despite job failing: 'progressive_workflow' kind-progressive_workflow/instance-ashhnp6r v2
[2023-10-26T13:46:31+0200] [MainThread] [W] [toil.job] Due to failure we are reducing the remaining try count of job 'progressive_workflow' kind-progressive_workflow/instance-ashhnp6r v2 with ID kind-progressive_workflow/instance-ashhnp6r to 4
[2023-10-26T13:46:31+0200] [MainThread] [I] [toil.leader] Issued job 'progressive_workflow' kind-progressive_workflow/instance-ashhnp6r v3 with job batch system ID: 3 and disk: 2.0 Gi, memory: 2.0 Gi, cores: 1, accelerators: [], preemptible: False
[2023-10-26T13:46:34+0200] [MainThread] [W] [toil.leader] Job failed with exit value 1: 'progressive_workflow' kind-progressive_workflow/instance-ashhnp6r v3
Exit reason: None
[2023-10-26T13:46:34+0200] [MainThread] [W] [toil.leader] No log file is present, despite job failing: 'progressive_workflow' kind-progressive_workflow/instance-ashhnp6r v3
[2023-10-26T13:46:34+0200] [MainThread] [W] [toil.job] Due to failure we are reducing the remaining try count of job 'progressive_workflow' kind-progressive_workflow/instance-ashhnp6r v3 with ID kind-progressive_workflow/instance-ashhnp6r to 3
[2023-10-26T13:46:35+0200] [MainThread] [I] [toil.leader] Issued job 'progressive_workflow' kind-progressive_workflow/instance-ashhnp6r v4 with job batch system ID: 4 and disk: 2.0 Gi, memory: 2.0 Gi, cores: 1, accelerators: [], preemptible: False
[2023-10-26T13:46:38+0200] [MainThread] [W] [toil.leader] Job failed with exit value 1: 'progressive_workflow' kind-progressive_workflow/instance-ashhnp6r v4
Exit reason: None
[2023-10-26T13:46:38+0200] [MainThread] [W] [toil.leader] No log file is present, despite job failing: 'progressive_workflow' kind-progressive_workflow/instance-ashhnp6r v4
[2023-10-26T13:46:38+0200] [MainThread] [W] [toil.job] Due to failure we are reducing the remaining try count of job 'progressive_workflow' kind-progressive_workflow/instance-ashhnp6r v4 with ID kind-progressive_workflow/instance-ashhnp6r to 2
[2023-10-26T13:46:38+0200] [MainThread] [I] [toil.leader] Issued job 'progressive_workflow' kind-progressive_workflow/instance-ashhnp6r v5 with job batch system ID: 5 and disk: 2.0 Gi, memory: 2.0 Gi, cores: 1, accelerators: [], preemptible: False
[2023-10-26T13:46:40+0200] [MainThread] [W] [toil.leader] Job failed with exit value 1: 'progressive_workflow' kind-progressive_workflow/instance-ashhnp6r v5
Exit reason: None
[2023-10-26T13:46:40+0200] [MainThread] [W] [toil.leader] No log file is present, despite job failing: 'progressive_workflow' kind-progressive_workflow/instance-ashhnp6r v5
[2023-10-26T13:46:40+0200] [MainThread] [W] [toil.job] Due to failure we are reducing the remaining try count of job 'progressive_workflow' kind-progressive_workflow/instance-ashhnp6r v5 with ID kind-progressive_workflow/instance-ashhnp6r to 1
[2023-10-26T13:46:40+0200] [MainThread] [I] [toil.leader] Issued job 'progressive_workflow' kind-progressive_workflow/instance-ashhnp6r v6 with job batch system ID: 6 and disk: 2.0 Gi, memory: 2.0 Gi, cores: 1, accelerators: [], preemptible: False
[2023-10-26T13:46:43+0200] [MainThread] [W] [toil.leader] Job failed with exit value 1: 'progressive_workflow' kind-progressive_workflow/instance-ashhnp6r v6
Exit reason: None
[2023-10-26T13:46:43+0200] [MainThread] [W] [toil.leader] No log file is present, despite job failing: 'progressive_workflow' kind-progressive_workflow/instance-ashhnp6r v6
[2023-10-26T13:46:43+0200] [MainThread] [W] [toil.job] Due to failure we are reducing the remaining try count of job 'progressive_workflow' kind-progressive_workflow/instance-ashhnp6r v6 with ID kind-progressive_workflow/instance-ashhnp6r to 0
[2023-10-26T13:46:43+0200] [MainThread] [W] [toil.leader] Job 'progressive_workflow' kind-progressive_workflow/instance-ashhnp6r v7 is completely failed
[2023-10-26T13:46:47+0200] [MainThread] [I] [toil.leader] Finished toil run with 1 failed jobs.
[2023-10-26T13:46:47+0200] [MainThread] [I] [toil.leader] Failed jobs at end of the run: 'progressive_workflow' kind-progressive_workflow/instance-ashhnp6r v7
[2023-10-26T13:46:47+0200] [MainThread] [I] [toil.realtimeLogger] Stopping real-time logging server.
[2023-10-26T13:46:48+0200] [MainThread] [I] [toil.realtimeLogger] Joining real-time logging server thread.
[2023-10-26T13:46:48+0200] [MainThread] [W] [toil.common] XDG_RUNTIME_DIR is set to nonexistent directory /run/user/10093827; your environment may be out of spec!
[2023-10-26T13:46:48+0200] [MainThread] [W] [toil.common] XDG_RUNTIME_DIR is set to nonexistent directory /run/user/10093827; your environment may be out of spec!
Traceback (most recent call last):
  File "/global/group/home/harrisom/.local/bin/cactus", line 8, in <module>
    sys.exit(main())
  File "/home/harrisom/.local/lib/python3.10/site-packages/cactus/progressive/cactus_progressive.py", line 436, in main
    hal_id = toil.start(Job.wrapJobFn(progressive_workflow, options, config_node, mc_tree, og_map, input_seq_id_map))
  File "/home/harrisom/.local/lib/python3.10/site-packages/toil/common.py", line 1064, in start
    return self._runMainLoop(rootJobDescription)
  File "/home/harrisom/.local/lib/python3.10/site-packages/toil/common.py", line 1544, in _runMainLoop
    jobCache=self._jobCache).run()
  File "/home/harrisom/.local/lib/python3.10/site-packages/toil/leader.py", line 289, in run
    raise FailedJobsException(self.jobStore, failed_jobs, exit_code=self.recommended_fail_exit_code)
toil.exceptions.FailedJobsException: The job store '/EBB-ZIVNFS/harrisom/SlaveMakerSelection/WithoutTEs/WithoutContamination/WholeGenomeAlignment/js' contains 1 failed jobs: 'progressive_workflow' kind-progressive_workflow/instance-ashhnp6r v7

**Comment by glennhickey** [comment]
You can try `--batchLogsDir` to your command in order to display more SLURM logging.  Ex, 
```
mkdir batch-logs
run cactus with --batchLogsDir ./batch-logs
```

**Comment by MCH74** [comment]
Thanks. I've just tried that. I got the same errors but the batch logs directory is empty.

**Comment by MCH74** [comment]
Hi, it appears our servers are not compatible with AVX2. Thanks
