### ISSUE TITLE
Memory isssue while running cactus-hal2maf

### ISSUE THREAD

**Issue by Alchimic007** [ComparativeGenomicsToolkit/cactus#1224]
Hello, 

I'm having problem trying to run cactus-hal2maf to extract some alignments in maf format. I am working with big (805 Gb) cactus hal 241-mammalian.hal. During cactus workflow I'm getting memory error, no matter with or without specifications of cores and memory it is set. I'm working on qsub Linux RedHat 6.5 server with several nodes (6 to be presize) 20 cores and up to 1000Gb memory  (but average availability is around 500 Gb). How should I set memory so I could run cactus workflow properly. I would be thankful for any help. Here is a log of an error: (cactusenv) [hpctestuser@login1(rvchpc1) mprylutskyi]$ cactus-hal2maf JobStore /users/hpctestuser/241-mammalian-2020v2.hal bosTau_chr1.maf --restart --refGenome Homo_sapiens --refSequence chr1 --chunkSize 1000000 --batchMemory 100G  --workDir /users/hpctestuser/mprylutskyi/HALtools/cactus_alignments/tempdir --targetGenomes Bos_taurus --dupeMode single --noAncestors --maxCores 20
[2023-11-09T14:14:59+0000] [MainThread] [I] [toil.statsAndLogging] Setting batchCores to 2
[2023-11-09T14:14:59+0000] [MainThread] [I] [toil.statsAndLogging] Enabling realtime logging in Toil
[2023-11-09T14:14:59+0000] [MainThread] [I] [toil.statsAndLogging] Cactus Command: /users/hpctestuser/miniconda2/envs/cactusenv/bin/cactus-hal2maf JobStore /users/hpctestuser/241-mammalian-2020v2.hal bosTau_chr1.maf --restart --refGenome Homo_sapiens --refSequence chr1 --chunkSize 1000000 --batchMemory 100G --workDir /users/hpctestuser/mprylutskyi/HALtools/cactus_alignments/tempdir --targetGenomes Bos_taurus --dupeMode single --noAncestors --maxCores 20
[2023-11-09T14:14:59+0000] [MainThread] [I] [toil.statsAndLogging] Cactus Commit: 368b8dfd66c8961955078e807aaec2a55e552ffa
[2023-11-09T14:14:59+0000] [MainThread] [I] [toil.statsAndLogging] Using default batch count of 1
[2023-11-09T14:14:59+0000] [MainThread] [W] [toil.batchSystems.singleMachine] Not enough cores! User limited to 20 but we only have 2.
[2023-11-09T14:14:59+0000] [MainThread] [W] [toil.batchSystems.singleMachine] Not enough memory! User limited to 107374182400 bytes but we only have 4016881664 bytes.
[2023-11-09T14:14:59+0000] [MainThread] [I] [toil] Running Toil version 5.12.0-6d5a5b83b649cd8adf34a5cfe89e7690c95189d3 on host login1.prv.rvchpc1.cluster.
[2023-11-09T14:14:59+0000] [MainThread] [I] [toil.realtimeLogger] Starting real-time logging.

[2023-11-09T14:15:01+0000] [MainThread] [I] [toil.realtimeLogger] Stopping real-time logging server.
[2023-11-09T14:15:01+0000] [MainThread] [I] [toil.realtimeLogger] Joining real-time logging server thread.
Traceback (most recent call last):
  File "/users/hpctestuser/miniconda2/envs/cactusenv/bin/cactus-hal2maf", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/users/hpctestuser/miniconda2/envs/cactusenv/lib/python3.12/site-packages/cactus/maf/cactus_hal2maf.py", line 177, in main
    maf_id = toil.restart()
             ^^^^^^^^^^^^^^
  File "/users/hpctestuser/miniconda2/envs/cactusenv/lib/python3.12/site-packages/toil/common.py", line 1101, in restart
    return self._runMainLoop(rootJobDescription)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/users/hpctestuser/miniconda2/envs/cactusenv/lib/python3.12/site-packages/toil/common.py", line 1544, in _runMainLoop
    jobCache=self._jobCache).run()
                             ^^^^^
  File "/users/hpctestuser/miniconda2/envs/cactusenv/lib/python3.12/site-packages/toil/leader.py", line 251, in run
    self.innerLoop()
  File "/users/hpctestuser/miniconda2/envs/cactusenv/lib/python3.12/site-packages/toil/leader.py", line 741, in innerLoop
    self._processReadyJobs()
  File "/users/hpctestuser/miniconda2/envs/cactusenv/lib/python3.12/site-packages/toil/leader.py", line 636, in _processReadyJobs
    self._processReadyJob(message.job_id, message.result_status)
  File "/users/hpctestuser/miniconda2/envs/cactusenv/lib/python3.12/site-packages/toil/leader.py", line 532, in _processReadyJob
    self.issueJob(readyJob)
  File "/users/hpctestuser/miniconda2/envs/cactusenv/lib/python3.12/site-packages/toil/leader.py", line 896, in issueJob
    jobBatchSystemID = self.batchSystem.issueBatchJob(jobNode, job_environment=job_environment)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/users/hpctestuser/miniconda2/envs/cactusenv/lib/python3.12/site-packages/toil/batchSystems/singleMachine.py", line 755, in issueBatchJob
    self.check_resource_request(scaled_desc)
  File "/users/hpctestuser/miniconda2/envs/cactusenv/lib/python3.12/site-packages/toil/batchSystems/singleMachine.py", line 506, in check_resource_request
    raise e
  File "/users/hpctestuser/miniconda2/envs/cactusenv/lib/python3.12/site-packages/toil/batchSystems/singleMachine.py", line 502, in check_resource_request
    super().check_resource_request(requirer)
  File "/users/hpctestuser/miniconda2/envs/cactusenv/lib/python3.12/site-packages/toil/batchSystems/abstractBatchSystem.py", line 344, in check_resource_request
    raise e
  File "/users/hpctestuser/miniconda2/envs/cactusenv/lib/python3.12/site-packages/toil/batchSystems/abstractBatchSystem.py", line 337, in check_resource_request
    raise InsufficientSystemResources(requirer, resource, available)
toil.batchSystems.abstractBatchSystem.InsufficientSystemResources: The job 'hal2maf_batch' kind-hal2maf_batch/instance-a1eg1dgi v1 is requesting 52416897188 bytes of memory, more than the maximum of 4016881664 bytes of memory that SingleMachineBatchSystem was configured with, or enforced by --maxMemory. Scale is set to 1.0.
(cactusenv) [hpctestuser@login1(rvchpc1) mprylutskyi]$

**Comment by glennhickey** [comment]
I see you're running with `--restart`.  Did you run with `--batchMemory 100G` the first time?  Because unfortunately when you run with `--restart` any changes to cactus's options have no effect.

**Comment by Alchimic007** [comment]
Yes it is my second run that is why I set restart option. Here is my setup for another run ( I deleted previous job) and I get same error (cactusenv) [hpctestuser@login1(rvchpc1) ~]$ cactus-hal2maf JobStore /users/hpctestuser/241-mammalian-2020v2.hal bosTau_chr1.maf --refGenome Homo_sapiens --refSequence chr1 --chunkSize 1000000 --batchCount 5 --batchCores 5  --batchMemory 20G  --workDir /users/hpctestuser/mprylutskyi/HALtools/cactus_alignments/tempdir --targetGenomes Bos_taurus --dupeMode single --noAncestors 
[2023-11-09T14:54:31+0000] [MainThread] [I] [toil.statsAndLogging] Enabling realtime logging in Toil
[2023-11-09T14:54:31+0000] [MainThread] [I] [toil.statsAndLogging] Cactus Command: /users/hpctestuser/miniconda2/envs/cactusenv/bin/cactus-hal2maf JobStore /users/hpctestuser/241-mammalian-2020v2.hal bosTau_chr1.maf --refGenome Homo_sapiens --refSequence chr1 --chunkSize 1000000 --batchCount 5 --batchCores 5 --batchMemory 20G --workDir /users/hpctestuser/mprylutskyi/HALtools/cactus_alignments/tempdir --targetGenomes Bos_taurus --dupeMode single --noAncestors
[2023-11-09T14:54:31+0000] [MainThread] [I] [toil.statsAndLogging] Cactus Commit: 368b8dfd66c8961955078e807aaec2a55e552ffa
[2023-11-09T14:54:31+0000] [MainThread] [I] [toil.statsAndLogging] Importing /users/hpctestuser/241-mammalian-2020v2.hal
[2023-11-09T14:54:31+0000] [MainThread] [I] [toil.job] Saving graph of 1 jobs, 1 non-service, 1 new
[2023-11-09T14:54:31+0000] [MainThread] [I] [toil.job] Processing job 'hal2maf_workflow' kind-hal2maf_workflow/instance-kc4x41hw v0
[2023-11-09T14:54:31+0000] [MainThread] [I] [toil] Running Toil version 5.12.0-6d5a5b83b649cd8adf34a5cfe89e7690c95189d3 on host login1.prv.rvchpc1.cluster.
[2023-11-09T14:54:31+0000] [MainThread] [I] [toil.realtimeLogger] Starting real-time logging.
[2023-11-09T14:54:31+0000] [MainThread] [I] [toil.leader] Issued job 'hal2maf_workflow' kind-hal2maf_workflow/instance-kc4x41hw v1 with job batch system ID: 1 and disk: 2.0 Gi, memory: 2.0 Gi, cores: 1, accelerators: [], preemptible: False
[2023-11-09T14:54:31+0000] [MainThread] [I] [toil.worker] Redirecting logging to /users/hpctestuser/mprylutskyi/HALtools/cactus_alignments/tempdir/c38163a0b09059dc82821f3fece3d0e2/ff24/worker_log.txt
[2023-11-09T14:54:32+0000] [MainThread] [I] [toil.leader] 0 jobs are running, 0 jobs are issued and waiting to run
[2023-11-09T14:54:32+0000] [MainThread] [I] [toil.leader] Issued job 'hal2maf_ranges' kind-hal2maf_ranges/instance-yzi61k0c v1 with job batch system ID: 2 and disk: 805.5 Gi, memory: 2.0 Gi, cores: 1, accelerators: [], preemptible: False
[2023-11-09T14:54:33+0000] [MainThread] [I] [toil.worker] Redirecting logging to /users/hpctestuser/mprylutskyi/HALtools/cactus_alignments/tempdir/c38163a0b09059dc82821f3fece3d0e2/9a11/worker_log.txt
[2023-11-09T14:54:33+0000] [MainThread] [I] [toil-rt] Reading HAL file from job store to /users/hpctestuser/mprylutskyi/HALtools/cactus_alignments/tempdir/c38163a0b09059dc82821f3fece3d0e2/9a11/6492/tmpoz4328g3/241-mammalian-2020v2.hal
[2023-11-09T14:54:33+0000] [MainThread] [I] [toil-rt] Computing range information
[2023-11-09T14:54:33+0000] [MainThread] [I] [toil-rt] 2023-11-09 14:54:33.523852: Running the command: "halStats /users/hpctestuser/mprylutskyi/HALtools/cactus_alignments/tempdir/c38163a0b09059dc82821f3fece3d0e2/9a11/6492/tmpoz4328g3/241-mammalian-2020v2.hal --sequenceStats Homo_sapiens"
[2023-11-09T14:54:33+0000] [MainThread] [I] [toil-rt] 2023-11-09 14:54:33.629674: Successfully ran: "halStats /users/hpctestuser/mprylutskyi/HALtools/cactus_alignments/tempdir/c38163a0b09059dc82821f3fece3d0e2/9a11/6492/tmpoz4328g3/241-mammalian-2020v2.hal --sequenceStats Homo_sapiens" in 0.0885 seconds
[2023-11-09T14:54:33+0000] [MainThread] [I] [toil-rt] Setting batchSize to 50
[2023-11-09T14:54:33+0000] [Thread-4 (statsAndLoggingAggregator)] [W] [toil.statsAndLogging] Got message from job at time 11-09-2023 14:54:33: Job used more disk than requested. For CWL, consider increasing the outdirMin requirement, otherwise, consider increasing the disk requirement. Job files/for-job/kind-hal2maf_ranges/instance-yzi61k0c/cleanup/file-600a149265ba4620adaf084a5caecdb9/stream used 100.00% disk (805.5 GiB [864879493120B] used, 805.5 GiB [864878803587B] requested).

Workflow Progress 100%||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||| 2/2 (0 failures) [00:03<00:00, 0.78 jobs/s]
[2023-11-09T14:54:35+0000] [MainThread] [I] [toil.realtimeLogger] Stopping real-time logging server.
[2023-11-09T14:54:35+0000] [MainThread] [I] [toil.realtimeLogger] Joining real-time logging server thread.
Traceback (most recent call last):
  File "/users/hpctestuser/miniconda2/envs/cactusenv/bin/cactus-hal2maf", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/users/hpctestuser/miniconda2/envs/cactusenv/lib/python3.12/site-packages/cactus/maf/cactus_hal2maf.py", line 186, in main
    maf_id = toil.start(Job.wrapJobFn(hal2maf_workflow, hal_id, options, config))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/users/hpctestuser/miniconda2/envs/cactusenv/lib/python3.12/site-packages/toil/common.py", line 1064, in start
    return self._runMainLoop(rootJobDescription)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/users/hpctestuser/miniconda2/envs/cactusenv/lib/python3.12/site-packages/toil/common.py", line 1544, in _runMainLoop
    jobCache=self._jobCache).run()
                             ^^^^^
  File "/users/hpctestuser/miniconda2/envs/cactusenv/lib/python3.12/site-packages/toil/leader.py", line 251, in run
    self.innerLoop()
  File "/users/hpctestuser/miniconda2/envs/cactusenv/lib/python3.12/site-packages/toil/leader.py", line 741, in innerLoop
    self._processReadyJobs()
  File "/users/hpctestuser/miniconda2/envs/cactusenv/lib/python3.12/site-packages/toil/leader.py", line 636, in _processReadyJobs
    self._processReadyJob(message.job_id, message.result_status)
  File "/users/hpctestuser/miniconda2/envs/cactusenv/lib/python3.12/site-packages/toil/leader.py", line 552, in _processReadyJob
    self._runJobSuccessors(job_id)
  File "/users/hpctestuser/miniconda2/envs/cactusenv/lib/python3.12/site-packages/toil/leader.py", line 442, in _runJobSuccessors
    self.issueJobs(successors)
  File "/users/hpctestuser/miniconda2/envs/cactusenv/lib/python3.12/site-packages/toil/leader.py", line 919, in issueJobs
    self.issueJob(job)
  File "/users/hpctestuser/miniconda2/envs/cactusenv/lib/python3.12/site-packages/toil/leader.py", line 896, in issueJob
    jobBatchSystemID = self.batchSystem.issueBatchJob(jobNode, job_environment=job_environment)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/users/hpctestuser/miniconda2/envs/cactusenv/lib/python3.12/site-packages/toil/batchSystems/singleMachine.py", line 755, in issueBatchJob
    self.check_resource_request(scaled_desc)
  File "/users/hpctestuser/miniconda2/envs/cactusenv/lib/python3.12/site-packages/toil/batchSystems/singleMachine.py", line 506, in check_resource_request
    raise e
  File "/users/hpctestuser/miniconda2/envs/cactusenv/lib/python3.12/site-packages/toil/batchSystems/singleMachine.py", line 502, in check_resource_request
    super().check_resource_request(requirer)
  File "/users/hpctestuser/miniconda2/envs/cactusenv/lib/python3.12/site-packages/toil/batchSystems/abstractBatchSystem.py", line 344, in check_resource_request
    raise e
  File "/users/hpctestuser/miniconda2/envs/cactusenv/lib/python3.12/site-packages/toil/batchSystems/abstractBatchSystem.py", line 337, in check_resource_request
    raise InsufficientSystemResources(requirer, resource, available)
toil.batchSystems.abstractBatchSystem.InsufficientSystemResources: The job 'hal2maf_batch' kind-hal2maf_batch/instance-a2saw1vb v1 is requesting 5.0 cores, more than the maximum of 2 cores that SingleMachineBatchSystem was configured with, or enforced by --maxCores. Scale is set to 1.0.
(cactusenv) [hpctestuser@login1(rvchpc1) ~]$ cactus-hal2maf JobStore /users/hpctestuser/241-mammalian-2020v2.hal bosTau_chr1.maf --refGenome Homo_sapiens --refSequence chr1 --chunkSize 1000000 --batchCount 5 --batchCores 5  --batchMemory 20G  --workDir /users/hpctestuser/mprylutskyi/HALtools/cactus_alignments/tempdir --targetGenomes Bos_taurus --dupeMode single --noAncestors

**Comment by Alchimic007** [comment]
The problem is cactus sees my system as SingleMachineBatchSystem with  2 cores  and 4Gb for each core, and program is needed minimum 5 cores for its work. Could you help me with that?

**Comment by glennhickey** [comment]
If you're running on a slurm cluster, you need to add `--batchSystem slurm` otherwise Cactus will run on your head node.  More information here:

https://github.com/ComparativeGenomicsToolkit/cactus/blob/master/doc/progressive.md#running-on-a-cluster

**Comment by Alchimic007** [comment]
I'm running it on qsub cluster

**Comment by glennhickey** [comment]
You can try other `--batchSystem` values (see `--help`), but I can only support slurm. Otherwise qsub your cactus command and run on one node of your cluster.

**Comment by Alchimic007** [comment]
OK, I will try it thank you

**Comment by Alchimic007** [comment]
Tried to run in bash shell, but still getting an error, now from workers failing their job, because they cannot access node (as I think). Here is bash pipeline I used last: #!/bin/bash -l

#$ -j y
#$ -o /users/hpctestuser/mprylutskyi/HALtools/cactus_alignments/log/$JOB_NAME.$JOB_ID.$TASK_ID.output  #CHANGE!!! (if copied from another user)
#$ -N cactus_cow
#$ -l h_vmem=100G
#$ -pe smp-verbose 5
#$ -l s_rt=999:0:0

source /users/hpctestuser/miniconda2/etc/profile.d/conda.sh
conda activate cactusenv

export PATH=$PATH:/users/hpctestuser/mprylutskyi/cactus/bin

 
cactus-hal2maf JobStore /users/hpctestuser/241-mammalian-2020v2.hal bosTau_chr1.maf --refGenome Homo_sapiens --refSequence chr1 --chunkSize 1000000 --batchCount 5 --batchCores 5  --batchMemory 100G --workDir /users/hpctestuser/mprylutskyi/HALtools/cactus_alignments/tempdir --targetGenomes Bos_taurus --dupeMode single --noAncestors --binariesMode local and I attach log file, could you check it please? I would be grateful for any help and sorry for bothering.
[cactus_cow.70500.$TASK_ID.output.txt](https://github.com/ComparativeGenomicsToolkit/cactus/files/13310855/cactus_cow.70500.TASK_ID.output.txt).

**Comment by glennhickey** [comment]
The error is that it can't find the `parallel` executable
```
exited 127: stderr=bash: parallel: command not found
```
This seems like an installation issue, since `parallel` is included `cactus/bin` in the binary release (and in `/usr/bin` in the docker release).

**Comment by Alchimic007** [comment]
Thank you, so the only way is to recompile cactus right?
