### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'mash'

### ISSUE THREAD

**Issue by HFzzzzzzz** [ComparativeGenomicsToolkit/cactus#1233]
=========>
	[2023-11-25T11:29:52+0800] [MainThread] [I] [toil.worker] ---TOIL WORKER OUTPUT LOG---
	[2023-11-25T11:29:52+0800] [MainThread] [I] [toil] Running Toil version 5.12.0-6d5a5b83b649cd8adf34a5cfe89e7690c95189d3 on host zhf-Precision-5820-Tower.
	[2023-11-25T11:29:52+0800] [MainThread] [I] [toil.worker] Working on job 'mash_sketch' kind-minigraph_construct_workflow/instance-di600br9 v11
	[2023-11-25T11:29:53+0800] [MainThread] [I] [toil.worker] Loaded body Job('mash_sketch' kind-minigraph_construct_workflow/instance-di600br9 v11) from description 'mash_sk
etch' kind-minigraph_construct_workflow/instance-di600br9 v11
	[2023-11-25T11:29:53+0800] [MainThread] [W] [toil.fileStores.nonCachingFileStore] Starting job files/for-job/kind-mash_sketch/instance-32wa1nlj/cleanup/file-cef8e22236e84
60ebf07185014a19298/stream with less than 10%% of disk space remaining.
	[2023-11-25T11:29:53+0800] [MainThread] [I] [cactus.shared.common] Running the command ['mash', 'sketch', 'Y12.fa']
	[2023-11-25T11:29:53+0800] [MainThread] [I] [toil-rt] 2023-11-25 11:29:53.102779: Running the command: "mash sketch Y12.fa"
	[2023-11-25T11:29:53+0800] [MainThread] [W] [toil.fileStores.abstractFileStore] Failed job accessed files:
	[2023-11-25T11:29:53+0800] [MainThread] [W] [toil.fileStores.abstractFileStore] Downloaded file 'files/for-job/kind-sanitize_fasta_header/instance-jhwnsp5h/file-c5acbfa8e
5734d13b2373accec09fc9e/Y12.sanitized.fa' to path '/tmp/fe4fade679d05b678a5a79949fbb696a/f016/3e30/Y12.fa'
	Traceback (most recent call last):
	  File "/media/zhf/ext2/cactus_11_24/cactus/cactus_env/lib/python3.10/site-packages/toil/worker.py", line 403, in workerScript
	    job._runner(jobGraph=None, jobStore=jobStore, fileStore=fileStore, defer=defer)
	  File "/media/zhf/ext2/cactus_11_24/cactus/cactus_env/lib/python3.10/site-packages/toil/job.py", line 2774, in _runner
	    returnValues = self._run(jobGraph=None, fileStore=fileStore)
	  File "/media/zhf/ext2/cactus_11_24/cactus/cactus_env/lib/python3.10/site-packages/toil/job.py", line 2691, in _run
	    return self.run(fileStore)
	  File "/media/zhf/ext2/cactus_11_24/cactus/cactus_env/lib/python3.10/site-packages/toil/job.py", line 2919, in run
	    rValue = userFunction(*((self,) + tuple(self._args)), **self._kwargs)
	  File "/media/zhf/ext2/cactus_11_24/cactus/cactus_env/lib/python3.10/site-packages/cactus/refmap/cactus_minigraph.py", line 221, in mash_sketch
	    cactus_call(parameters=['mash', 'sketch', ref_path])
	  File "/media/zhf/ext2/cactus_11_24/cactus/cactus_env/lib/python3.10/site-packages/cactus/shared/common.py", line 787, in cactus_call
	    process = subprocess.Popen(call, shell=shell, encoding=None,
	  File "/usr/lib/python3.10/subprocess.py", line 969, in __init__
	    self._execute_child(args, executable, preexec_fn, close_fds,
	  File "/usr/lib/python3.10/subprocess.py", line 1845, in _execute_child
	    raise child_exception_type(errno_num, err_msg, err_filename)
	FileNotFoundError: [Errno 2] No such file or directory: 'mash'

When I used cactus-pangenome ./js ./examples/yeastPangenome.txt --outDir primates-pg --outName primates-pg --reference Y12 --vcf --giraffe --gfa --gbz, this happened Question, what is the reason?

**Comment by glennhickey** [comment]
`mash` is included in Cactus, so this is an installation problem.  Please re-install while carefully following the directions, making sure your `$PATH` gets stet up properly.

**Comment by alpapan** [comment]
I don't think it is, certainly not in the recursive git clone config, nor the BIN_INSTALL nor the Makefile.

However it's a simple solution to get it from https://github.com/marbl/Mash/releases/download/v2.3/mash-Linux64-v2.3.tar

**Comment by glennhickey** [comment]
no the simplest solution is to [properly install](https://github.com/ComparativeGenomicsToolkit/cactus/blob/v2.9.3/BIN-INSTALL.md) [cactus](https://github.com/ComparativeGenomicsToolkit/cactus/releases)
```
wget https://github.com/ComparativeGenomicsToolkit/cactus/releases/download/v2.9.3/cactus-bin-v2.9.3.tar.gz
tar zxf cactus-bin-v2.9.3.tar.gz
ls -l cactus-bin-v2.9.3/bin/mash
-rwxr-xr-x 1 hickey hickey 1607248 Nov 18 18:13 cactus-bin-v2.9.3/bin/mash
```

**Comment by alpapan** [comment]
didn't even see that one had to download the cactus-bin, since the BIN-INSTALL.md is in the main cactus repository and this is not in the README.md which states

```
git clone https://github.com/ComparativeGenomicsToolkit/cactus.git --recursive
cd cactus
virtualenv -p python3 cactus_env
echo "export PATH=$(pwd)/bin:\$PATH" >> cactus_env/bin/activate
echo "export PYTHONPATH=$(pwd)/lib:\$PYTHONPATH" >> cactus_env/bin/activate
source cactus_env/bin/activate
python3 -m pip install -U setuptools pip wheel
python3 -m pip install -U .
python3 -m pip install -U -r ./toil-requirement.txt

... etc
```

the BIN-INSTALL.md does say

```
## Extracting
If you have not already extract the distribution and cd into the cactus directory:
tar -xzf cactus-bin-v2.9.3.tar.gz
cd cactus-bin-v2.9.3
```

and i missed the -bin and thought it was the main cactus distribution 

perhaps adding wget https://github.com/ComparativeGenomicsToolkit/cactus/releases/download/v2.9.3/cactus-bin-v2.9.3.tar.gz in the BIN-INSTALL.md or just pointing new users to its existance would be good.

but up to you, i'm just a user
