### ISSUE TITLE
toil.jobStores.abstractJobStore.NoSuchFileException: File 'rootJobReturnValue' does not exist.

### ISSUE THREAD

**Issue by lixiang117423** [ComparativeGenomicsToolkit/cactus#1251]
I am using the Minigraph-Cactus Pangenome pipeline to construct the pan-genome of rice samples. The code to run is as follows:
```
cactus-pangenome ./jb sample.txt --outDir ./cactus-pangenome --outName Acuce --reference 15 --maxMemory 400G --logFile run.log --restart
```

Erros message:
```
[2023-12-14T09:06:07+0000] [MainThread] [I] [toil.statsAndLogging] Enabling realtime logging in Toil
[2023-12-14T09:06:07+0000] [MainThread] [I] [toil.statsAndLogging] Cactus Command: /home/cactus/cactus_env/bin/cactus-pangenome ./jb sample.txt --outDir ./cactus-pangenome --outName Acuce --reference 15 --maxMemory 400G --logFile run.log --restart
[2023-12-14T09:06:07+0000] [MainThread] [I] [toil.statsAndLogging] Cactus Commit: fb04f4f97e9560c435448b90ba08cec400e66c07
[2023-12-14T09:06:07+0000] [MainThread] [W] [toil.common] Requested restart but the workflow has already been completed; allowing exports to rerun.
Traceback (most recent call last):
  File "/home/cactus/cactus_env/lib/python3.10/site-packages/toil/jobStores/fileJobStore.py", line 695, in read_shared_file_stream
    with open(self._get_shared_file_path(shared_file_name), 'rb' if encoding == None else 'rt', encoding=encoding, errors=errors) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/data/jb/files/shared/rootJobStoreID'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/cactus/cactus_env/lib/python3.10/site-packages/toil/jobStores/abstractJobStore.py", line 274, in load_root_job
    with self.read_shared_file_stream(self.rootJobStoreIDFileName) as f:
  File "/usr/lib/python3.10/contextlib.py", line 135, in __enter__
    return next(self.gen)
  File "/home/cactus/cactus_env/lib/python3.10/site-packages/toil/jobStores/fileJobStore.py", line 700, in read_shared_file_stream
    raise NoSuchFileException(shared_file_name)
toil.jobStores.abstractJobStore.NoSuchFileException: File 'rootJobStoreID' does not exist.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/cactus/cactus_env/lib/python3.10/site-packages/toil/common.py", line 1087, in restart
    self._jobStore.load_root_job()
  File "/home/cactus/cactus_env/lib/python3.10/site-packages/toil/jobStores/abstractJobStore.py", line 277, in load_root_job
    raise JobException('No job has been set as the root in this job store')
toil.job.JobException: No job has been set as the root in this job store

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/cactus/cactus_env/lib/python3.10/site-packages/toil/jobStores/fileJobStore.py", line 695, in read_shared_file_stream
    with open(self._get_shared_file_path(shared_file_name), 'rb' if encoding == None else 'rt', encoding=encoding, errors=errors) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/data/jb/files/shared/rootJobReturnValue'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/cactus/cactus_env/bin/cactus-pangenome", line 8, in <module>
    sys.exit(main())
  File "/home/cactus/cactus_env/lib/python3.10/site-packages/cactus/refmap/cactus_pangenome.py", line 165, in main
    toil.restart()
  File "/home/cactus/cactus_env/lib/python3.10/site-packages/toil/common.py", line 1091, in restart
    return self._jobStore.get_root_job_return_value()
  File "/home/cactus/cactus_env/lib/python3.10/site-packages/toil/jobStores/abstractJobStore.py", line 312, in get_root_job_return_value
    with self.read_shared_file_stream('rootJobReturnValue') as fH:
  File "/usr/lib/python3.10/contextlib.py", line 135, in __enter__
    return next(self.gen)
  File "/home/cactus/cactus_env/lib/python3.10/site-packages/toil/jobStores/fileJobStore.py", line 700, in read_shared_file_stream
    raise NoSuchFileException(shared_file_name)
toil.jobStores.abstractJobStore.NoSuchFileException: File 'rootJobReturnValue' does not exist.
````

**Comment by glennhickey** [comment]
This is a strange Toil error.  It looks like something happened to stop your workflow just when it was writing the final output.  You're restarting it, but the jobstore is corrupted and now it won't work.  I don't think there's much you can do here, unfortunately.  Maybe follow up on the Toil github https://github.com/DataBiosphere/toil

**Comment by lixiang117423** [comment]
It works! 

The latest docker version (https://github.com/ComparativeGenomicsToolkit/cactus/releases/tag/v2.7.0) was used.

Thanks.

**Comment by diego-rt** [comment]
Hi, I have a very similar error @glennhickey 

Run finished but the output dir is missing and this is what the log shows after resume:

```
[2024-01-01T20:40:25+0100] [MainThread] [W] [toil.lib.humanize] Deprecated toil method.  Please use "toil.lib.conversions.human2bytes()" instead."
[2024-01-01T20:40:25+0100] [MainThread] [I] [toil.statsAndLogging] Enabling realtime logging in Toil
[2024-01-01T20:40:25+0100] [MainThread] [I] [toil.statsAndLogging] Cactus Command: /groups/tanaka/People/current/Diego/Projects/0_Global/bin/cactus/cactus_env/bin/cactus /groups/tanaka/People/current/Diego/Projects/8_Transxolotl/2_TEmpura//data/3_cactus/0_playground/1_test/work/AmphibiansDirect/jobstore /groups/tanaka/People/current/Diego/Projects/8_Transxolotl/2_TEmpura/data/3_cactus/0_playground/1_test/work/AmphibiansDirect/species_sheet.tsv /groups/tanaka/People/current/Diego/Projects/8_Transxolotl/2_TEmpura/data/3_cactus/0_playground/1_test/work/AmphibiansDirect/output/Amphibians.txt --workDir /groups/tanaka/People/current/Diego/Projects/8_Transxolotl/2_TEmpura/data/3_cactus/0_playground/1_test/work/AmphibiansDirect/workDir/ --batchLogsDir /groups/tanaka/People/current/Diego/Projects/8_Transxolotl/2_TEmpura/data/3_cactus/0_playground/1_test/work/AmphibiansDirect/batch-logs/ --batchSystem slurm --binariesMode singularity --containerImage /groups/tanaka/People/current/Diego/Projects/8_Transxolotl/2_TEmpura/data/3_cactus/0_playground/1_test/work/AmphibiansDirect/cactus_v2.7.0.sif --lastzCores 8 --defaultMemory 30Gi --consCores 38 --consMemory 165Gi --configFile config-slurm.xml --restart
[2024-01-01T20:40:25+0100] [MainThread] [I] [toil.statsAndLogging] Cactus Commit: a4d28540052ed1397b8939af1c0365de0d45c79a
[2024-01-01T20:40:25+0100] [MainThread] [W] [toil.common] Length of workDir path "/groups/tanaka/People/current/Diego/Projects/8_Transxolotl/2_TEmpura/data/3_cactus/0_playground/1_test/work/AmphibiansDirect/workDir" is 132 characters.  Consider setting a shorter path with --workPath or setting TMPDIR to something like "/tmp" to avoid overly long paths.
[2024-01-01T20:40:25+0100] [MainThread] [W] [toil.common] Length of workDir path "/groups/tanaka/People/current/Diego/Projects/8_Transxolotl/2_TEmpura/data/3_cactus/0_playground/1_test/work/AmphibiansDirect/workDir" is 132 characters.  Consider setting a shorter path with --workPath or setting TMPDIR to something like "/tmp" to avoid overly long paths.
[2024-01-01T20:40:25+0100] [MainThread] [I] [toil.statsAndLogging] Using pre-built singularity image: '/groups/tanaka/People/current/Diego/Projects/8_Transxolotl/2_TEmpura/data/3_cactus/0_playground/1_test/work/AmphibiansDirect/cactus_v2.7.0.sif'
[2024-01-01T20:40:25+0100] [MainThread] [W] [toil.common] Requested restart but the workflow has already been completed; allowing exports to rerun.

Traceback (most recent call last):
  File "/groups/tanaka/People/current/Diego/Projects/0_Global/bin/cactus/cactus_env/bin/cactus", line 8, in <module>
    sys.exit(main())
  File "/groups/tanaka/People/current/Diego/Projects/0_Global/bin/cactus/cactus_env/lib/python3.10/site-packages/cactus/progressive/cactus_progressive.py", line 438, in main
    toil.exportFile(hal_id, makeURL(options.outputHal))
  File "/groups/tanaka/People/current/Diego/Projects/0_Global/bin/cactus/cactus_env/lib/python3.10/site-packages/toil/lib/compatibility.py", line 12, in call
    return func(*args, **kwargs)
  File "/groups/tanaka/People/current/Diego/Projects/0_Global/bin/cactus/cactus_env/lib/python3.10/site-packages/toil/common.py", line 1321, in exportFile
    return self.export_file(jobStoreFileID, dstUrl)
  File "/groups/tanaka/People/current/Diego/Projects/0_Global/bin/cactus/cactus_env/lib/python3.10/site-packages/toil/common.py", line 1332, in export_file
    self._jobStore.export_file(file_id, dst_uri)
  File "/groups/tanaka/People/current/Diego/Projects/0_Global/bin/cactus/cactus_env/lib/python3.10/site-packages/toil/jobStores/abstractJobStore.py", line 503, in export_file
    self._export_file(otherCls, file_id, parseResult)
  File "/groups/tanaka/People/current/Diego/Projects/0_Global/bin/cactus/cactus_env/lib/python3.10/site-packages/toil/jobStores/fileJobStore.py", line 348, in _export_file
    atomic_copy(srcPath, destPath, executable=executable)
  File "/groups/tanaka/People/current/Diego/Projects/0_Global/bin/cactus/cactus_env/lib/python3.10/site-packages/toil/lib/io.py", line 127, in atomic_copy
    shutil.copyfile(src_path, dest_path_tmp)
  File "/software/f2022/software/python/3.10.8-gcccore-12.2.0-bare/lib/python3.10/shutil.py", line 256, in copyfile
    with open(dst, 'wb') as fdst:
FileNotFoundError: [Errno 2] No such file or directory: '/groups/tanaka/People/current/Diego/Projects/8_Transxolotl/2_TEmpura/data/3_cactus/0_playground/1_test/work/AmphibiansDirect/output/Amphibians.txt.5a4def11-30be-486c-b793-eefc24998e1b.tmp.txt'
```
