### ISSUE TITLE
Cactus failing invert_alignments for the provided example, need help troubleshooting

### ISSUE THREAD

**Issue by IshaanSD** [ComparativeGenomicsToolkit/cactus#1253]
Please help me figure out why I might be getting the error below.

I working on an linux/arm64/v8 platform

I pull and run the image `quay.io/comparative-genomics-toolkit/cactus:v2.7.0`
I run bash on this image and try to get the Cactus alignment using the provided example by running 
`cactus /data/jobStore /data/examples/evolverMammals.txt /data/examples/evolverMammals.hal`

I have also tried directly running 
`docker run -v $(pwd):/data --rm -it quay.io/comparative-genomics-toolkit/cactus:v2.6.6 cactus /data/jobStore /data/evolverMammals.txt /data/evolverMammals.hal`

I did the same for `evolverPrimates.txt`

In all of these cases, in the invert_alignments step, it seems seems to fail with log
`[MainThread] [W] [toil.leader] Job failed with exit value 1: 'invert_alignments' kind-invert_alignments/instance-1wzorf0z v1
Exit reason: None`
Toil Worker Output log (for evolverMammals):
```
	[2023-12-20T08:00:55+0000] [MainThread] [I] [toil.worker] ---TOIL WORKER OUTPUT LOG---
	[2023-12-20T08:00:55+0000] [MainThread] [I] [toil] Running Toil version 5.12.0-6d5a5b83b649cd8adf34a5cfe89e7690c95189d3 on host eae6f9984423.
	[2023-12-20T08:00:55+0000] [MainThread] [I] [toil.worker] Working on job 'invert_alignments' kind-invert_alignments/instance-ykbx2dmn v4
	[2023-12-20T08:00:56+0000] [MainThread] [I] [toil.worker] Loaded body Job('invert_alignments' kind-invert_alignments/instance-ykbx2dmn v4) from description 'invert_alignments' kind-invert_alignments/instance-ykbx2dmn v4
	[2023-12-20T08:00:56+0000] [MainThread] [I] [cactus.shared.common] Running the command ['paffy', 'invert', '-i', '/tmp/a0520c00ee2b547cb5965b776388d74d/f4b7/231f/tmpu62mjwij.tmp']
	[2023-12-20T08:00:56+0000] [MainThread] [I] [toil-rt] 2023-12-20 08:00:56.860184: Running the command: "paffy invert -i /tmp/a0520c00ee2b547cb5965b776388d74d/f4b7/231f/tmpu62mjwij.tmp"
	[2023-12-20T08:00:56+0000] [MainThread] [W] [toil.fileStores.abstractFileStore] Failed job accessed files:
	[2023-12-20T08:00:56+0000] [MainThread] [W] [toil.fileStores.abstractFileStore] Downloaded file 'files/for-job/kind-make_ingroup_to_outgroup_alignments_3/instance-xv8u9b0v/file-e04bcc739b234c3d8cda8904b1441f44/tmpyzk3w3v2.tmp' to path '/tmp/a0520c00ee2b547cb5965b776388d74d/f4b7/231f/tmpu62mjwij.tmp'
	Traceback (most recent call last):
	  File "/home/cactus/cactus_env/lib/python3.10/site-packages/toil/worker.py", line 403, in workerScript
	    job._runner(jobGraph=None, jobStore=jobStore, fileStore=fileStore, defer=defer)
	  File "/home/cactus/cactus_env/lib/python3.10/site-packages/toil/job.py", line 2774, in _runner
	    returnValues = self._run(jobGraph=None, fileStore=fileStore)
	  File "/home/cactus/cactus_env/lib/python3.10/site-packages/toil/job.py", line 2691, in _run
	    return self.run(fileStore)
	  File "/home/cactus/cactus_env/lib/python3.10/site-packages/toil/job.py", line 2919, in run
	    rValue = userFunction(*((self,) + tuple(self._args)), **self._kwargs)
	  File "/home/cactus/cactus_env/lib/python3.10/site-packages/cactus/paf/local_alignment.py", line 192, in invert_alignments
	    cactus_call(parameters=['paffy', 'invert', "-i", alignment_file_local], outfile=inverted_alignment_file_local, outappend=True,
	  File "/home/cactus/cactus_env/lib/python3.10/site-packages/cactus/shared/common.py", line 891, in cactus_call
	    raise RuntimeError("{}Command {} exited {}: {}".format(sigill_msg, call, process.returncode, out))
	RuntimeError: Command /usr/bin/time -f "CACTUS-LOGGED-MEMORY-IN-KB: %M" paffy invert -i /tmp/a0520c00ee2b547cb5965b776388d74d/f4b7/231f/tmpu62mjwij.tmp exited 1: stderr=paffy(+0x14032)[0x4000014032]
	paffy(+0x71f4)[0x40000071f4]
	paffy(+0xa880)[0x400000a880]
	/lib/x86_64-linux-gnu/libc.so.6(+0x29d90)[0x400197ed90]
	/lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0x80)[0x400197ee40]
	paffy(+0x3a75)[0x4000003a75]
	ERROR: Paf cigar alignment does not match query length: 686 vs. 697 id=simHuman_chr6|simHuman.chr6	601863	3	700	+	id=simDog_chr6|simDog.chr6	593897	2	688	475	732	255	AS:i:24369	cg:Z:1=1X9=1X2=1X8=1X1=1X5=1X3=1X3=1X2I2=1X7=1X7=15I2X1=1X6=3X8=1I7=1X4=2X3=2X2=3X9=1X1=3X2=1X2=1X2=1X1=3X1=1X3=4X1=1X1=1X10=1X2=2X1=1X8=5X3=12D4=1X10=1X1=1X5=1X5=2X9=1X2=1X1=1X9=1X4=2X1=2X2=4X4=1X1=1X4=1X2=3X3=1X10=1X2=1X2=1X3=1X4=1X1=1X1=1X4=2X11=4D4=1X4=1X4=1X7=2X1=1X2=1X1=1X1=1D2=1X6=8D4=1X1=1X3=2X5=2X3=1X6=1X2=3I5=1X6=1X1=1X1=1X1=2X14=2X6=1X3=1X2=1X2=1X3=1X6=1X4=2D4=6D3=3X2=2X8=2X1=1I3=2X1=1X1=2X6=11D6=1X1=3X5=2X4=3X8=1X1=1X4=3X2=2X2=2X1=1X4=2X4=1X3=4X5=1X5=1X4=13I1X6=1X3=3X1=2X4=1X2D4=4X2=1X2=3X10=1X4=1X4=1X2=1X2=1X2=
	Command exited with non-zero status 1
	CACTUS-LOGGED-MEMORY-IN-KB: 10440
	
	[2023-12-20T08:00:57+0000] [MainThread] [E] [toil.worker] Exiting the worker because of a failed job on host eae6f9984423
<=========
Log from job "'invert_alignments' kind-invert_alignments/instance-bm3soe25 v6" follows:
=========>
	[2023-12-20T08:00:55+0000] [MainThread] [I] [toil.worker] ---TOIL WORKER OUTPUT LOG---
	[2023-12-20T08:00:55+0000] [MainThread] [I] [toil] Running Toil version 5.12.0-6d5a5b83b649cd8adf34a5cfe89e7690c95189d3 on host eae6f9984423.
	[2023-12-20T08:00:55+0000] [MainThread] [I] [toil.worker] Working on job 'invert_alignments' kind-invert_alignments/instance-bm3soe25 v4
	[2023-12-20T08:00:56+0000] [MainThread] [I] [toil.worker] Loaded body Job('invert_alignments' kind-invert_alignments/instance-bm3soe25 v4) from description 'invert_alignments' kind-invert_alignments/instance-bm3soe25 v4
	[2023-12-20T08:00:56+0000] [MainThread] [I] [cactus.shared.common] Running the command ['paffy', 'invert', '-i', '/tmp/a0520c00ee2b547cb5965b776388d74d/2cde/6cb3/tmpxg4oap_8.tmp']
	[2023-12-20T08:00:56+0000] [MainThread] [I] [toil-rt] 2023-12-20 08:00:56.541861: Running the command: "paffy invert -i /tmp/a0520c00ee2b547cb5965b776388d74d/2cde/6cb3/tmpxg4oap_8.tmp"
	[2023-12-20T08:00:56+0000] [MainThread] [W] [toil.fileStores.abstractFileStore] Failed job accessed files:
	[2023-12-20T08:00:56+0000] [MainThread] [W] [toil.fileStores.abstractFileStore] Downloaded file 'files/for-job/kind-make_ingroup_to_outgroup_alignments_3/instance-k8sfcuya/file-1e1bf3cb2f0643e3a030ddad82463e90/tmpwp8qvhbd.tmp' to path '/tmp/a0520c00ee2b547cb5965b776388d74d/2cde/6cb3/tmpxg4oap_8.tmp'
	Traceback (most recent call last):
	  File "/home/cactus/cactus_env/lib/python3.10/site-packages/toil/worker.py", line 403, in workerScript
	    job._runner(jobGraph=None, jobStore=jobStore, fileStore=fileStore, defer=defer)
	  File "/home/cactus/cactus_env/lib/python3.10/site-packages/toil/job.py", line 2774, in _runner
	    returnValues = self._run(jobGraph=None, fileStore=fileStore)
	  File "/home/cactus/cactus_env/lib/python3.10/site-packages/toil/job.py", line 2691, in _run
	    return self.run(fileStore)
	  File "/home/cactus/cactus_env/lib/python3.10/site-packages/toil/job.py", line 2919, in run
	    rValue = userFunction(*((self,) + tuple(self._args)), **self._kwargs)
	  File "/home/cactus/cactus_env/lib/python3.10/site-packages/cactus/paf/local_alignment.py", line 192, in invert_alignments
	    cactus_call(parameters=['paffy', 'invert', "-i", alignment_file_local], outfile=inverted_alignment_file_local, outappend=True,
	  File "/home/cactus/cactus_env/lib/python3.10/site-packages/cactus/shared/common.py", line 891, in cactus_call
	    raise RuntimeError("{}Command {} exited {}: {}".format(sigill_msg, call, process.returncode, out))
	RuntimeError: Command /usr/bin/time -f "CACTUS-LOGGED-MEMORY-IN-KB: %M" paffy invert -i /tmp/a0520c00ee2b547cb5965b776388d74d/2cde/6cb3/tmpxg4oap_8.tmp exited 1: stderr=paffy(+0x14032)[0x4000014032]
	paffy(+0x71f4)[0x40000071f4]
	paffy(+0xa880)[0x400000a880]
	/lib/x86_64-linux-gnu/libc.so.6(+0x29d90)[0x400197ed90]
	/lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0x80)[0x400197ee40]
	paffy(+0x3a75)[0x4000003a75]
	ERROR: Paf cigar alignment does not match query length: 2575 vs. 2654 id=simHuman_chr6|simHuman.chr6	601863	0	2654	+	id=simMouse_chr6|simMouse.chr6	636262	0	2575	1559	2946	255	AS:i:38915	cg:Z:1=1X4=1X1=1X7=1X4=1X1=1X1=1X1=1X1=1X1=1X5=1X2I11=1X1=2X1=2X4=2D6=2X9=1X5=1X1=3X3=1X1I3X4=2X2=1X2=1X2=2X2=2X1=1X2=1X1=4X3=1X1=2X4=1X2=1I3=1I7X1=1X3=2X6=1X1=3X1=1X2=1X2=5X1=4X1=2X2=1X10=2X4=1X1=1X2=1X2I3=1X2=1X3=5D1=2X1=1X4=14D1=1X2=5D4=1X4=1X5=1X3=6X2=1X4=1X1=1X1=1X1=1X1=1I8=1X6=4I3=5X3=1X1=1X3=1X3=2X12=1X11=1X4=1X1=1X2=2X6=1D1X1=1X2=1X3=8D1=2X1=3X7=1X1=3X2=2X6=1X2=1I2=1X3=3X2=1X8=2X4=1X1=1D1=1X4=4X4=1X1=2X1=5X3=1X2=1X7=1D4=5D1=2X1=1X3=1X2=3X10=4I4=1X3=2X4=2X1=1X2=1X4=1X5=2X3=1X6=1X1=2X1=26I2=1X3=4X1=1X2=1X2=3X1=2X2=2X1=1X2=1X5=2X3=1X4=1X2=1X1=2X1=2X4=1X2D2=1X1=1X1=2X1=1X5=1X3=1X1=1X4=1X4=1X4=1X2D1=1X6=3X6=1X1=1X3=8D2=2X3=1X1=1X2=1X2=1X3=1X1=1X4=1X1=1X2=1I3=1X3=1D2=1X1=1X1=1X1=3X2=1X2=2D1=1X6=1X2=2X3=5I3=1X1=4X3=2X4=1X2=1X1=1X5=1X1=1X3=1X2=1X5=2X4=15D1X1=2X3=1I1X4=1X1=6D6=7I2=1X3=1X1=1X1=2X1=2X1=1X2=1D2X2=1X1=1X1=1X4=1X2=1X1=1X1=3X2=1X1=2X1=1X1=4X3=2X1=1X6=1X3=1X4=5I4=1X11=17D1=2X1=1X3=2X1=16D3=1X2=1X2=1X6=1X6=1X1=1X4=1X2=4I2X3=1X1=1X3=3D1=1X4=1X1=1I1X2=1X2=2X1=1X2=1X1=16I6=51I5=2X5=2X2=1X3=1X1D1=1X7=1X1=2X3=2X2=1X2=2X2=1I1=3X3=3X5=1X1=8I9=1X4=3X12=2X2=3X4=1X3=1X3=3X6=2X6=1X9=1X4=1I1X2=2X3=2X1=4X1D2=1X1=1X3=4D3=1X1=1X2=2X1=2I5=2I1X6=2X5=1X2=1X2=3X1=1X1=3X2=1X1=1X9=1X1D2X3=2X1=1X2=1X9=1X3=2X5=2X3=3X3=2X1=2X6=1X1=1X5=1X1=4X4=2X4=1X5D1=1X8=12D2X4=2X1=2X1=1X2=1X3=1X3=1X3=4X3=9I7=1X3=1X3=2X1=1X3=2X2=1X17I3=1X2=8I2=1X1=1X5=1X7=1X4=3X2=1X1=1X1=2X4=2I2=1X2=1X1=1X5=1D4=1X1=4D4=8I7=2X4=1X1=1X1=8I2=1X7=3X2=1X1=8D3=1X8D1=2X2=1X6=1X5=1D1X4=14D4=1X1=1X12=2X1=2X1=2X1=1X1=1X1=4D5=2X1=2X2=7I1=1X5=1X2=1X4=1X2=1X3=2X1=1X2=1X5=2X1=2D2X1=1X3=2X5=1X6=1X5=1X3=15D1X1=1X1=1X1=1X5=1X1=9D2=2X1=1X3=1X5=1X1=4X5=1X6=6I2=2X1=1X3=3X2=4X3=1X2=1D1X3=1X1=1X2=1X22D6=6D3=4X2=7D2=1X1=2X1=1X1=1X1=1X5=1X3=1X3=1X1=4D5=15D1X1=1X2=1X1=3X2=7D2=1X1=1X1=3X1=1X3=1X3=4I1=1X2=1X1=2X3=1X1=1X1=2X1=2X2=2X2=2X2=1X1=1X1=2X12=1X2=1X1=3X7=2X1=1X2=2X3=1X10I6=1X17I1=1X1=1X1=3X2=1X2=1X1=1X1=24I4=1X1=3X1=7I6=1I1=1X2=1X5=2X4=5X5=1X3=1X4=1X1=1X1=2X5=3X1=3X2=1X7=1X6=5D1=3X5=2X2=3X2=1X5=2X1=1X3=3X3=1X5I1=1X1=2X1=1X1=1X3=2X3=2X1=2X2=1X1=1X3=1I1=1X1=1X9=1X7=1X2=1X3=1X4=1X3=4X5=8I3=1X3=1X1=1X2=1X1=3X6=1X2=4D1=1X1=1X5=1X4=1X1=1X7=1X3=1X2=2X2=2X3=25D3=2X2=1X9D1=1X2=1X1=1X2=1X3=2X1=2X1=1X1=2X2=28D2=1X1=3X6=1D1X6=4D5=1X2=2X4=12D5=1X1=1X1=1X1=1X5=1X6=1X8=1I10=1X1=1X3=1X2=1X2=1X1=1X1=1X8=16D1X4=1X2=1X6=3X2=1X2=1I8=
	Command exited with non-zero status 1
	CACTUS-LOGGED-MEMORY-IN-KB: 8452
	
	[2023-12-20T08:00:56+0000] [MainThread] [E] [toil.worker] Exiting the worker because of a failed job on host eae6f9984423
<=========
Log from job "'invert_alignments' kind-invert_alignments/instance-1wzorf0z v6" follows:
=========>
	[2023-12-20T08:00:52+0000] [MainThread] [I] [toil.worker] ---TOIL WORKER OUTPUT LOG---
	[2023-12-20T08:00:52+0000] [MainThread] [I] [toil] Running Toil version 5.12.0-6d5a5b83b649cd8adf34a5cfe89e7690c95189d3 on host eae6f9984423.
	[2023-12-20T08:00:53+0000] [MainThread] [I] [toil.worker] Working on job 'invert_alignments' kind-invert_alignments/instance-1wzorf0z v4
	[2023-12-20T08:00:54+0000] [MainThread] [I] [toil.worker] Loaded body Job('invert_alignments' kind-invert_alignments/instance-1wzorf0z v4) from description 'invert_alignments' kind-invert_alignments/instance-1wzorf0z v4
	[2023-12-20T08:00:54+0000] [MainThread] [I] [cactus.shared.common] Running the command ['paffy', 'invert', '-i', '/tmp/a0520c00ee2b547cb5965b776388d74d/c89e/07f4/tmph0lthygy.tmp']
	[2023-12-20T08:00:54+0000] [MainThread] [I] [toil-rt] 2023-12-20 08:00:54.289858: Running the command: "paffy invert -i /tmp/a0520c00ee2b547cb5965b776388d74d/c89e/07f4/tmph0lthygy.tmp"
	[2023-12-20T08:00:54+0000] [MainThread] [W] [toil.fileStores.abstractFileStore] Failed job accessed files:
	[2023-12-20T08:00:54+0000] [MainThread] [W] [toil.fileStores.abstractFileStore] Downloaded file 'files/for-job/kind-make_ingroup_to_outgroup_alignments_3/instance-x3nfz23q/file-01410d5bb16944168839625c2a01b5fb/tmp58mg4xjw.tmp' to path '/tmp/a0520c00ee2b547cb5965b776388d74d/c89e/07f4/tmph0lthygy.tmp'
	Traceback (most recent call last):
	  File "/home/cactus/cactus_env/lib/python3.10/site-packages/toil/worker.py", line 403, in workerScript
	    job._runner(jobGraph=None, jobStore=jobStore, fileStore=fileStore, defer=defer)
	  File "/home/cactus/cactus_env/lib/python3.10/site-packages/toil/job.py", line 2774, in _runner
	    returnValues = self._run(jobGraph=None, fileStore=fileStore)
	  File "/home/cactus/cactus_env/lib/python3.10/site-packages/toil/job.py", line 2691, in _run
	    return self.run(fileStore)
	  File "/home/cactus/cactus_env/lib/python3.10/site-packages/toil/job.py", line 2919, in run
	    rValue = userFunction(*((self,) + tuple(self._args)), **self._kwargs)
	  File "/home/cactus/cactus_env/lib/python3.10/site-packages/cactus/paf/local_alignment.py", line 192, in invert_alignments
	    cactus_call(parameters=['paffy', 'invert', "-i", alignment_file_local], outfile=inverted_alignment_file_local, outappend=True,
	  File "/home/cactus/cactus_env/lib/python3.10/site-packages/cactus/shared/common.py", line 891, in cactus_call
	    raise RuntimeError("{}Command {} exited {}: {}".format(sigill_msg, call, process.returncode, out))
	RuntimeError: Command /usr/bin/time -f "CACTUS-LOGGED-MEMORY-IN-KB: %M" paffy invert -i /tmp/a0520c00ee2b547cb5965b776388d74d/c89e/07f4/tmph0lthygy.tmp exited 1: stderr=paffy(+0x14032)[0x4000014032]
	paffy(+0x71f4)[0x40000071f4]
	paffy(+0xa880)[0x400000a880]
	/lib/x86_64-linux-gnu/libc.so.6(+0x29d90)[0x400197ed90]
	/lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0x80)[0x400197ee40]
	paffy(+0x3a75)[0x4000003a75]
	ERROR: Paf cigar alignment does not match query length: 1237 vs. 1211 id=simHuman_chr6|simHuman.chr6	601863	563	1774	+	id=simRat_chr6|simRat.chr6	647215	643	1880	730	1378	255	AS:i:19077	cg:Z:5=2X2=1X1=1X3=1X5=1X4=1X4=1X4=1X1=2D1X3=1X2=3X8=1X5=1X1=8D3=1X1=1X2=1X1=2X3=1X1=1X4=1X1=1X2=1I3=1X2=1X2=2X4I1=1X1=1X1=1X2=1X2=1X4=1X2=1X1=1X2=2D2=1X3=2X4=2X2=7D2=1X4=1X1=2X1=1X5=3X3=1X5=1X2=15D4=1X3=2X2=1X1I1X4=2X6D8=7I1X3=1X1=1X1=2X2=1X1=1X3=1X4=1X6=1X2=1X1=1X1=2X5=2X1=1X1=4X3=3X1I1=1X8=1X4=5I4=1X1=1X10=11D4=6D3=2X1=16D3=1X2=1X2=1X5=3X5=1X5=2X1=2X1=2X4=3X1=1X1=1X4=13I1=2X4=1X1=4X3=2X1=1X55I3=1X4=2X1=1X3=3X2=1X2=2X1=1X1D2X5=1X1=1X2=1X1=2X2=1X3=1X2=1I1=2X4=3X5=1X3=8I5=1X3=1X2=2X1=1X11=2X2=2X4=3X2=1X3=3X6=2X1=1X4=1X9=1X4=1X1=1X1=2X1=3X1=1X1=3X2=1X3=1X2=4D2=1X4=2X1=4I1=1X2=1X1=2X1=1X2=1I1X4=2X2=1X3=2X1=1X1=3X2=3X12=1D2=2X2=1X12=1X4=1X5=2X3=3X2=3X1=2X6=3X5=1X1=4X4=2X5=5X4=3X4=2X1=2X1=1X2=1X3=9I3=1X2=2X1=1X1=1I9=2X3=1X2=2X2=1X3=2X2=1X25I2=2X4=1X1=1X5=1X7=1X4=3X2=1X1=1X1=2X3=2I3=1X1=1X2=2X4=1X3=1X1=4D4=8I7=2X6=1X1=8I2=1X7=3X1=1I1X6=2X1=17D1=1X6=1X5=15D1X3=1X4=1X1=1X13=1X1=2X1=2X1=1X1=4X1=1I2X1=1X4=3I1=3X1=1X5=1X2=1X1=1X2=1X2=1X3=2X1=1X3=1X4=2X1=2X2D1=1X3=2X5=1X6=1X5=1X3=10D2=1X2=5D7=1X1=5D2=1X3=4D3=1X4=2X1=2I1X13=6I3=1X1=1X3=3X2=4X1=1X1=1X2=1X1=
	Command exited with non-zero status 1
	CACTUS-LOGGED-MEMORY-IN-KB: 10016
	
	[2023-12-20T08:00:54+0000] [MainThread] [E] [toil.worker] Exiting the worker because of a failed job on host eae6f9984423
<=========
Log from job "'invert_alignments' kind-invert_alignments/instance-53wjsmwu v6" follows:
=========>
	[2023-12-20T08:00:56+0000] [MainThread] [I] [toil.worker] ---TOIL WORKER OUTPUT LOG---
	[2023-12-20T08:00:56+0000] [MainThread] [I] [toil] Running Toil version 5.12.0-6d5a5b83b649cd8adf34a5cfe89e7690c95189d3 on host eae6f9984423.
	[2023-12-20T08:00:56+0000] [MainThread] [I] [toil.worker] Working on job 'invert_alignments' kind-invert_alignments/instance-53wjsmwu v4
	[2023-12-20T08:00:57+0000] [MainThread] [I] [toil.worker] Loaded body Job('invert_alignments' kind-invert_alignments/instance-53wjsmwu v4) from description 'invert_alignments' kind-invert_alignments/instance-53wjsmwu v4
	[2023-12-20T08:00:57+0000] [MainThread] [I] [cactus.shared.common] Running the command ['paffy', 'invert', '-i', '/tmp/a0520c00ee2b547cb5965b776388d74d/3437/705d/tmp06t0kulb.tmp']
	[2023-12-20T08:00:57+0000] [MainThread] [I] [toil-rt] 2023-12-20 08:00:57.984376: Running the command: "paffy invert -i /tmp/a0520c00ee2b547cb5965b776388d74d/3437/705d/tmp06t0kulb.tmp"
	[2023-12-20T08:00:58+0000] [MainThread] [W] [toil.fileStores.abstractFileStore] Failed job accessed files:
	[2023-12-20T08:00:58+0000] [MainThread] [W] [toil.fileStores.abstractFileStore] Downloaded file 'files/for-job/kind-make_ingroup_to_outgroup_alignments_3/instance-k79exlly/file-e902efec379347d389a19615df0c38cd/tmpt44lde91.tmp' to path '/tmp/a0520c00ee2b547cb5965b776388d74d/3437/705d/tmp06t0kulb.tmp'
	Traceback (most recent call last):
	  File "/home/cactus/cactus_env/lib/python3.10/site-packages/toil/worker.py", line 403, in workerScript
	    job._runner(jobGraph=None, jobStore=jobStore, fileStore=fileStore, defer=defer)
	  File "/home/cactus/cactus_env/lib/python3.10/site-packages/toil/job.py", line 2774, in _runner
	    returnValues = self._run(jobGraph=None, fileStore=fileStore)
	  File "/home/cactus/cactus_env/lib/python3.10/site-packages/toil/job.py", line 2691, in _run
	    return self.run(fileStore)
	  File "/home/cactus/cactus_env/lib/python3.10/site-packages/toil/job.py", line 2919, in run
	    rValue = userFunction(*((self,) + tuple(self._args)), **self._kwargs)
	  File "/home/cactus/cactus_env/lib/python3.10/site-packages/cactus/paf/local_alignment.py", line 192, in invert_alignments
	    cactus_call(parameters=['paffy', 'invert', "-i", alignment_file_local], outfile=inverted_alignment_file_local, outappend=True,
	  File "/home/cactus/cactus_env/lib/python3.10/site-packages/cactus/shared/common.py", line 891, in cactus_call
	    raise RuntimeError("{}Command {} exited {}: {}".format(sigill_msg, call, process.returncode, out))
	RuntimeError: Command /usr/bin/time -f "CACTUS-LOGGED-MEMORY-IN-KB: %M" paffy invert -i /tmp/a0520c00ee2b547cb5965b776388d74d/3437/705d/tmp06t0kulb.tmp exited 1: stderr=paffy(+0x14032)[0x4000014032]
	paffy(+0x71f4)[0x40000071f4]
	paffy(+0xa880)[0x400000a880]
	/lib/x86_64-linux-gnu/libc.so.6(+0x29d90)[0x400197ed90]
	/lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0x80)[0x400197ee40]
	paffy(+0x3a75)[0x4000003a75]
	ERROR: Paf cigar alignment does not match query length: 1273 vs. 1186 id=simHuman_chr6|simHuman.chr6	601863	0	1186	+	id=simCow_chr6|simCow.chr6	602619	0	1273	807	1352	255	AS:i:36435	cg:Z:12=3X1=1X8=1X1=1X2=1X1=2X1=1X3=1X14=1X3=1X3=15I2X1=1X4=1X1=1X1=1X9=1I6=1X4=2X3=2X2=3X6=1X6=1X2=1X2=1I3=1X1=2X1=1X3=1X2=1X2=1X1I10=1X1=1X3=1X1=1X5=1X1=1X1=2X3=12D6=1X1=1X5=2X1=1X8=1X3=3X5=1X2=1X3=1X9=1X1=1X1=1X7=5X13=2X1=1X13=1X2=2X5=2X4=1X4=1X2=3X7=1X1=1X1=1X7=1X12=1X2=1X4=3X1=1X4=8D1=1X4=1X1=1X9=1X1=1X3=1X2=1X3=1X1=2I2X5=1X3=1X4=1X3=1X8=1X6=2X4=13I3=1X2=1X3=2X3=8D1=1X7=1X2=2X2=4I3=1X2=1X3=1I1=1X12=9D1=1X12=3X2=3X6=1X2=1X2=1X2=2X3=1X3=4X1=3X10=4X5=1X5=1X6=1X11=1X9=5I2=1X2=7X1=2X1=1X2=4X9=1X4=2X3=1X5=1X2=4X1=1X1=2X4=1X1=41I2=2X4=1X1=20I2=1X3=1X14=1X1=1X1=1X5=2X3=2X2=1X12=1X1=19D1=2X3=1X2=2X1=1X4=3D2X5=1X2=2X6=1X3=6X1=3X1=4D13=1X3=2X9=1X1=1X1=2X2=3X2=1X7=2X1=1X3=1X2=3X2=1X5=1X6=1X6=1X3=1X1=2X1=1X2=1X1=2X10=1X1D5=13D4=1X2=1X8=2X1=1X9=2D8=1X2=1X1=1X7I2=1X1=24I1X2=2X2=2X1=3X4=1X3=1X1=4I1=1X1=2X1=2X2=3X2=1X2=2X1=1X2=1X1=13I2X2=1X4=1X2=1X2=1X4=1X1=1I4=1X1=1X5=1X1=8I3=1X10=2X6=1X6=2X6=1X2=1I1=1X1=1X1=1X1=3X1=1X1=1X3=4I5=1X1=1X5=1X1=1X7=1X1=1X1=
	Command exited with non-zero status 1
	CACTUS-LOGGED-MEMORY-IN-KB: 9104
	
	[2023-12-20T08:00:58+0000] [MainThread] [E] [toil.worker] Exiting the worker because of a failed job on host eae6f9984423
```

**Comment by glennhickey** [comment]
The Cactus release (both binaries and docker) is X86-only.  To run on ARM, you need to build it from source.
