### ISSUE TITLE
Error; possibility of Omitting 'sanitize-fasta-header'

### ISSUE THREAD

**Issue by dmjask** [ComparativeGenomicsToolkit/cactus#1271]
Hi,
I've been using Cactus (2.4.2 and 2.6.9) on slurm for a few weeks. 
This week I've encountered the following error when running either version, also for attempts at previously successful reruns:
```
[2024-01-19T13:54:21+0100] [Thread-1 (daddy)] [E] [toil.batchSystems.singleMachine] Got exit code 1 (indicating failure) from job _toil_worker sanitize_fasta_header file:/data/jobstore kind-sanitize_fasta_header/instance-xekaxrra.
[2024-01-19T13:54:21+0100] [MainThread] [W] [toil.leader] Job failed with exit value 1: 'sanitize_fasta_header' kind-sanitize_fasta_header/instance-xekaxrra v1
Exit reason: None
[2024-01-19T13:54:21+0100] [MainThread] [W] [toil.leader] The job seems to have left a log file, indicating failure: 'sanitize_fasta_header' kind-sanitize_fasta_header/instance-xekaxrra v2
[2024-01-19T13:54:21+0100] [MainThread] [W] [toil.leader] Log from job "kind-sanitize_fasta_header/instance-xekaxrra" follows:
=========>
        [2024-01-19T13:54:20+0100] [MainThread] [I] [toil.worker] ---TOIL WORKER OUTPUT LOG---
        [2024-01-19T13:54:20+0100] [MainThread] [I] [toil] Running Toil version 5.9.2-54bfe0b146b76ecc6221de384c255e1be89547c6 on host gn-1.
        [2024-01-19T13:54:20+0100] [MainThread] [I] [toil.worker] Working on job 'sanitize_fasta_header' kind-sanitize_fasta_header/instance-xekaxrra v1
        [2024-01-19T13:54:20+0100] [MainThread] [I] [toil.worker] Loaded body Job('sanitize_fasta_header' kind-sanitize_fasta_header/instance-xekaxrra v1) from description 'sanitize_fasta_header' kind-sanitize_fasta_header/instance-xekax
        [2024-01-19T13:54:20+0100] [MainThread] [I] [cactus.shared.common] Running the command ['cactus_sanitizeFastaHeaders', '/data/6906bc8d337e57d09d3a5eab027c01e4/297f/6a5d/tmp0u8rzoq2/Brian_chr03_tig_0000_5.fa', 'Brian_chr03_tig_000
        [2024-01-19T13:54:20+0100] [MainThread] [I] [toil-rt] 2024-01-19 13:54:20.869052: Running the command: "cactus_sanitizeFastaHeaders /data/6906bc8d337e57d09d3a5eab027c01e4/297f/6a5d/tmp0u8rzoq2/Brian_chr03_tig_0000_5.fa Brian_chr0
        [2024-01-19T13:54:20+0100] [MainThread] [W] [toil.fileStores.abstractFileStore] Failed job accessed files:
        [2024-01-19T13:54:20+0100] [MainThread] [W] [toil.fileStores.abstractFileStore] Downloaded file 'files/no-job/file-d4448562b57e4c3795bac50ff25a7537/Brian_chr03_tig_0000_5.fasta' to path '/data/6906bc8d337e57d09d3a5eab027c01e4/297
        Traceback (most recent call last):
          File "/home/cactus/cactus_env/lib/python3.10/site-packages/toil/worker.py", line 403, in workerScript
            job._runner(jobGraph=None, jobStore=jobStore, fileStore=fileStore, defer=defer)
          File "/home/cactus/cactus_env/lib/python3.10/site-packages/toil/job.py", line 2743, in _runner
            returnValues = self._run(jobGraph=None, fileStore=fileStore)
          File "/home/cactus/cactus_env/lib/python3.10/site-packages/toil/job.py", line 2660, in _run
            return self.run(fileStore)
          File "/home/cactus/cactus_env/lib/python3.10/site-packages/toil/job.py", line 2888, in run
            rValue = userFunction(*((self,) + tuple(self._args)), **self._kwargs)
          File "/home/cactus/cactus_env/lib/python3.10/site-packages/cactus/preprocessor/checkUniqueHeaders.py", line 61, in sanitize_fasta_header
            cactus_call(parameters=cmd, outfile=out_fa_path)
          File "/home/cactus/cactus_env/lib/python3.10/site-packages/cactus/shared/common.py", line 839, in cactus_call
            raise RuntimeError("{}Command {} exited {}: {}".format(sigill_msg, call, process.returncode, out))
        RuntimeError: Command /usr/bin/time -v cactus_sanitizeFastaHeaders /data/6906bc8d337e57d09d3a5eab027c01e4/297f/6a5d/tmp0u8rzoq2/Brian_chr03_tig_0000_5.fa Brian_chr03_tig_0000_5 exited 1: stdout=None, stderr=Error: The fasta heade
        Command exited with non-zero status 1
                Command being timed: "cactus_sanitizeFastaHeaders /data/6906bc8d337e57d09d3a5eab027c01e4/297f/6a5d/tmp0u8rzoq2/Brian_chr03_tig_0000_5.fa Brian_chr03_tig_0000_5"
                User time (seconds): 0.00
                System time (seconds): 0.00
                Percent of CPU this job got: 20%
                Elapsed (wall clock) time (h:mm:ss or m:ss): 0:00.01
                Average shared text size (kbytes): 0
                Average unshared data size (kbytes): 0
                Average stack size (kbytes): 0
                Average total size (kbytes): 0
                Maximum resident set size (kbytes): 1060
                Average resident set size (kbytes): 0
                Major (requiring I/O) page faults: 0
                Minor (reclaiming a frame) page faults: 289
                Voluntary context switches: 8
                Involuntary context switches: 1
                Swaps: 0
                File system inputs: 0
                File system outputs: 120
                Socket messages sent: 0
                Socket messages received: 0
                Signals delivered: 0
                Page size (bytes): 4096
                Exit status: 1

        [2024-01-19T13:54:20+0100] [MainThread] [E] [toil.worker] Exiting the worker because of a failed job on host gn-1
<=========

```

**Comment by glennhickey** [comment]
It's hard to say because the error message seems truncated in your log.  
```
stderr=Error: The fasta heade
```
Could be a duplicate name in your fasta file.  You might be able to get the full message by just rerunning
```
cactus_sanitizeFastaHeaders Brian_chr03_tig_0000_5.fa Brian_chr03_tig_0000_5
```
on the command line.

**Comment by dmjask** [comment]
Yes, the whole log file was a bit much, but I've attached it here:
[cactus_out.txt](https://github.com/ComparativeGenomicsToolkit/cactus/files/13989743/cactus_out.txt)

**Comment by dmjask** [comment]
I see, they have to be unique across files as well. I've adjusted the fasta headers and now run without issue.
Thanks for the help!
