### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by luisacusick** [ComparativeGenomicsToolkit/cactus#133]
Hi! I am trying to run cactus on a slurm job scheduler and am getting toil-related errors when I run the program on the test data. 

Here are my arguments: 
export TOIL_SLURM_ARGS="-q dept_64"
cactus_args="--binariesMode local --batchSystem  slurm --maxCores 360 tmpdir cactus/examples/evolverMammals.txt out"

Here's the error message:
```
INFO:toil.leader:Issued job 'BatchPreprocessor' D/i/jobcEnKUr with job batch system ID: 7 and cores: 1, disk: 2.0 G, and memory: 2.0 G
2020-01-30 11:51:10,362 - toil.leader - INFO - Issued job 'BatchPreprocessor' D/i/jobcEnKUr with job batch system ID: 7 and cores: 1, disk: 2.0 G, and memory: 2.0 G
INFO:toil.leader:Issued job 'logAssemblyStats' o/7/jobwZmBK7 with job batch system ID: 8 and cores: 1, disk: 2.0 G, and memory: 2.0 G
2020-01-30 11:51:10,363 - toil.leader - INFO - Issued job 'logAssemblyStats' o/7/jobwZmBK7 with job batch system ID: 8 and cores: 1, disk: 2.0 G, and memory: 2.0 G
Exception in thread Thread-41:
Traceback (most recent call last):
  File "/net/mahler/opt/anaconda2/envs/cactus/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/net/mahler/opt/anaconda2/envs/cactus/lib/python2.7/site-packages/toil/batchSystems/abstractGridEngineBatchSystem.py", line 219, in run
    activity |= self.createJobs(newJob)
  File "/net/mahler/opt/anaconda2/envs/cactus/lib/python2.7/site-packages/toil/batchSystems/abstractGridEngineBatchSystem.py", line 121, in createJobs
    batchJobID = self.submitJob(subLine)
  File "/net/mahler/opt/anaconda2/envs/cactus/lib/python2.7/site-packages/toil/batchSystems/slurm.py", line 71, in submitJob
    result = int(output.strip().split()[-1])
IndexError: list index out of range
```
Do you know what could be causing this error? Thank you!

**Comment by diekhans** [comment]
Please file a ticket with Toil. https://github.com/DataBiosphere/toil/

Although we don't have the resources to support Toil on the
various batch systems, so anything you can do to debug the
problem would be useful.

**Comment by diekhans** [comment]
Toil bug
