### ISSUE TITLE
hal2maf

### ISSUE THREAD

**Issue by ferninfm** [ComparativeGenomicsToolkit/cactus#1349]
Hi,

I somehow manage to run hal2maf from a native installation but running cactus-hal2maf (v 2.8.1 as implemented to run using docker) gives me the following error:

The hal file validation turned out ok
The maf file created using hal2maf also seems correct

I would appreciate any ideas on this error.
All the best

Fernando

```
	[2024-04-09T12:01:21+0200] [MainThread] [E] [toil.statsAndLogging] sys 0.00
	[2024-04-09T12:01:21+0200] [MainThread] [W] [toil.fileStores.abstractFileStore] Failed job accessed files:
	[2024-04-09T12:01:21+0200] [MainThread] [W] [toil.fileStores.abstractFileStore] Downloaded file 'files/no-job/file-08c96ab151cf4e4983794c5171cea0bb/cactus.hal' to path '/tmp/a1e55c8826cc544187f128c418317f85/d1cd/6892/tmppsyjk1ik/cactus.hal'
	Traceback (most recent call last):
	  File "/mnt/data1/fernando/bin/cactus/cactus_env/lib/python3.12/site-packages/toil/worker.py", line 407, in workerScript
	    job._runner(jobGraph=None, jobStore=jobStore, fileStore=fileStore, defer=defer)
	  File "/mnt/data1/fernando/bin/cactus/cactus_env/lib/python3.12/site-packages/toil/job.py", line 2829, in _runner
	    returnValues = self._run(jobGraph=None, fileStore=fileStore)
	                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
	  File "/mnt/data1/fernando/bin/cactus/cactus_env/lib/python3.12/site-packages/toil/job.py", line 2746, in _run
	    return self.run(fileStore)
	           ^^^^^^^^^^^^^^^^^^^
	  File "/mnt/data1/fernando/bin/cactus/cactus_env/lib/python3.12/site-packages/toil/job.py", line 2974, in run
	    rValue = userFunction(*((self,) + tuple(self._args)), **self._kwargs)
	             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
	  File "/mnt/data1/fernando/bin/cactus/cactus_env/lib/python3.12/site-packages/cactus/maf/cactus_hal2maf.py", line 639, in hal2maf_batch
	    raise e
	  File "/mnt/data1/fernando/bin/cactus/cactus_env/lib/python3.12/site-packages/cactus/maf/cactus_hal2maf.py", line 629, in hal2maf_batch
	    cactus_call(parameters=parallel_cmd, work_dir=work_dir)
	  File "/mnt/data1/fernando/bin/cactus/cactus_env/lib/python3.12/site-packages/cactus/shared/common.py", line 906, in cactus_call
	    raise RuntimeError("{}Command {} exited {}: {}".format(sigill_msg, call, process.returncode, out))
	RuntimeError: Command ['docker', 'run', '--interactive', '--net=host', '--log-driver=none', '-u', '1000:1000', '-v', '/tmp/a1e55c8826cc544187f128c418317f85/d1cd/6892/tmppsyjk1ik:/data', '--entrypoint', '/bin/bash', '--name', 'c88d1980-5ae3-4c8b-a206-6c932f0187f3', '--rm', 'quay.io/comparative-genomics-toolkit/cactus:v2.8.1', '-c', "set -eo pipefail && cat taf_cmds.txt | parallel -j 20 '{}'"] exited 63: stderr=sed: couldn't open file /tmp/a1e55c8826cc544187f128c418317f85/d1cd/6892/tmppsyjk1ik/alnum_to_genome.sed: No such file or directory
	Error, premature end to maf file: -
	Error, premature end to maf file: -

.....Several premature end to maf file lines......

```

**Comment by glennhickey** [comment]
Thanks for raising this.  It should be fixed in #1351.  

Are you running on a single machine?  If so, then you should be able to work around it before the next release by running `cactus-hal2maf` from inside a docker image, kind of like described here:

https://github.com/ComparativeGenomicsToolkit/cactus/blob/master/doc/progressive.md#using-docker
