### ISSUE TITLE
raise RuntimeError("{}Command {} exited {}: {}".format(sigill_msg, call, process.returncode, out))

### ISSUE THREAD

**Issue by 1321425744zy** [ComparativeGenomicsToolkit/cactus#1406]
[2024-06-12T03:09:17+0800] [MainThread] [W] [toil.fileStores.abstractFileStore] Downloaded file 'files/for-job/kind-filter_paf/instance-s12rs4k7/file-4421866d3777474c84511365ecf2e950/mg.paf.filter.overlap' to path '/tmp/71b48063b6315421a2b6d3c1c1327852/c93b/a690/tmp9juo1yll/Anc0.paf'
        Traceback (most recent call last):
          File "/root/cactus/cactus_env/lib/python3.10/site-packages/toil/worker.py", line 407, in workerScript
            job._runner(jobGraph=None, jobStore=jobStore, fileStore=fileStore, defer=defer)
          File "/root/cactus/cactus_env/lib/python3.10/site-packages/toil/job.py", line 2829, in _runner
            returnValues = self._run(jobGraph=None, fileStore=fileStore)
          File "/root/cactus/cactus_env/lib/python3.10/site-packages/toil/job.py", line 2746, in _run
            return self.run(fileStore)
          File "/root/cactus/cactus_env/lib/python3.10/site-packages/toil/job.py", line 2974, in run
            rValue = userFunction(*((self,) + tuple(self._args)), **self._kwargs)
          File "/root/cactus/cactus_env/lib/python3.10/site-packages/cactus/pipeline/cactus_workflow.py", line 143, in cactus_cons
            messages = cactus_call(check_output=True, returnStdErr=True,
          File "/root/cactus/cactus_env/lib/python3.10/site-packages/cactus/shared/common.py", line 910, in cactus_call
            raise RuntimeError("{}Command {} exited {}: {}".format(sigill_msg, call, process.returncode, out))
        RuntimeError: cactus_consolidated(NC_052487.1): Command ['docker', 'run', '--interactive', '--net=host', '--log-driver=none', '-u', '0:0', '-v', '/tmp/71b48063b6315421a2b6d3c1c1327852/c93b/a690/tmp9juo1yll:/data', '--entrypoint', '/opt/cactus/wrapper.sh', '--name', '17f75b85-ce33-4591-846d-6d8d5f5f3125', '--rm', 'quay.io/comparative-genomics-toolkit/cactus:v2.8.2', 'cactus_consolidated', '--sequences', 'GCA002240015.2 GCA002240015.2.fa GCA002260605.1 GCA002260605.1.fa GCA002260645.1 GCA002260645.1.fa GCA002260665.1 GCA002260665.1.fa GCA002904275.2 GCA002904275.2.fa GCA2712375.1 GCA2712375.1.fa GCF730915.1 GCF730915.1.fa _MINIGRAPH_ _MINIGRAPH_.fa', '--speciesTree', '(GCA002240015.2:0.025,GCA002260605.1:0.025,GCA002260645.1:0.025,GCA002260665.1:0.025,GCA002904275.2:0.025,GCA2712375.1:0.025,GCF730915.1:0.025,_MINIGRAPH_:0.025)Anc0;', '--logLevel', 'INFO', '--alignments', 'Anc0_primary.paf', '--params', 'Anc0.config.xml', '--outputFile', 'Anc0.c2h', '--outputHalFastaFile', 'Anc0.c2h.fa', '--outputReferenceFile', 'Anc0.ref', '--outgroupEvents', '', '--referenceEvent', 'Anc0', '--threads', '64'] exited 1:
        [2024-06-12T03:09:18+0800] [MainThread] [E] [toil.worker] Exiting the worker because of a failed job on host node105
<=========

**Comment by 1321425744zy** [comment]
> There's not enough of the log here to diagnose, but it could be that it ran out of memory.

[2024-07-04T11:08:24+0800] [MainThread] [W] [toil.fileStores.abstractFileStore] LOG-TO-MASTER: Job used more disk than requested. For CWL, consider increasing the outdirMin requirement, otherwise, consider increasing the disk requirement. Job 'cactus_cons' kind-cactus_cons/instance-rwbjqr5x v4 used 102.30% disk (13.2 GiB [14186123264B] used, 12.9 GiB [13866772478B] requested).
        Traceback (most recent call last):
          File "/root/cactus/cactus_env/lib/python3.10/site-packages/toil/worker.py", line 407, in workerScript
            job._runner(jobGraph=None, jobStore=jobStore, fileStore=fileStore, defer=defer)
          File "/root/cactus/cactus_env/lib/python3.10/site-packages/toil/job.py", line 2829, in _runner
            returnValues = self._run(jobGraph=None, fileStore=fileStore)
          File "/root/cactus/cactus_env/lib/python3.10/site-packages/toil/job.py", line 2746, in _run
            return self.run(fileStore)
          File "/root/cactus/cactus_env/lib/python3.10/site-packages/toil/job.py", line 2974, in run
            rValue = userFunction(*((self,) + tuple(self._args)), **self._kwargs)
          File "/root/cactus/cactus_env/lib/python3.10/site-packages/cactus/pipeline/cactus_workflow.py", line 143, in cactus_cons
            messages = cactus_call(check_output=True, returnStdErr=True,
          File "/root/cactus/cactus_env/lib/python3.10/site-packages/cactus/shared/common.py", line 910, in cactus_call
            raise RuntimeError("{}Command {} exited {}: {}".format(sigill_msg, call, process.returncode, out))
        RuntimeError: cactus_consolidated(GWHCAYC00000010): Command ['docker', 'run', '--interactive', '--net=host', '--log-driver=none', '-u', '0:0', '-v', '/data01/zyfolder/ZY/Pan-Genome/soybean-pangemone/otherDna/7c321ac2552a5c3ab41adb6d78d3d52d/f6d4/2ce0/tmpcc01ji20:/data', '--entrypoint', '/opt/cactus/wrapper.sh', '--name', '85f882da-0cfa-4abd-9593-8f0403725e8b', '--rm', 'quay.io/comparative-genomics-toolkit/cactus:v2.8.2', 'cactus_consolidated', '--sequences', 'BRS537 BRS537.fa DND252 DND252.fa ENREI ENREI.fa Gma Gma.fa Gso Gso.fa GsojaF GsojaF.fa GWHCAYC00000000 GWHCAYC00000000.fa Hefeng25 Hefeng25.fa HJ117 HJ117.fa Huaxia3 Huaxia3.fa Hwangkeum Hwangkeum.fa Jack Jack.fa Jinyuan Jinyuan.fa Lee Lee.fa PI483463 PI483463.fa PI594527 PI594527.fa SoyC01 SoyC01.fa SoyC02 SoyC02.fa SoyC03 SoyC03.fa SoyC04 SoyC04.fa SoyC05 SoyC05.fa SoyC06 SoyC06.fa SoyC07 SoyC07.fa SoyC08 SoyC08.fa SoyC09 SoyC09.fa SoyC10 SoyC10.fa SoyC11 SoyC11.fa SoyC12 SoyC12.fa SoyC13 SoyC13.fa SoyC14 SoyC14.fa SoyL01 SoyL01.fa SoyL02 SoyL02.fa SoyL03 SoyL03.fa SoyL04 SoyL04.fa SoyL05 SoyL05.fa SoyL06 SoyL06.fa SoyL07 SoyL07.fa SoyL08 SoyL08.fa SoyL09 SoyL09.fa SoyW01 SoyW01.fa SoyW02 SoyW02.fa SoyW03 SoyW03.fa Tianlong1 Tianlong1.fa W05 W05.fa Wenfeng7 Wenfeng7.fa ZH13 ZH13.fa ZH35 ZH35.fa ZN6 ZN6.fa _MINIGRAPH_ _MINIGRAPH_.fa', '--speciesTree', '(BRS537:0.025,DND252:0.025,ENREI:0.025,Gma:0.025,Gso:0.025,GsojaF:0.025,GWHCAYC00000000:0.025,Hefeng25:0.025,HJ117:0.025,Huaxia3:0.025,Hwangkeum:0.025,Jack:0.025,Jinyuan:0.025,Lee:0.025,PI483463:0.025,PI594527:0.025,SoyC01:0.025,SoyC02:0.025,SoyC03:0.025,SoyC04:0.025,SoyC05:0.025,SoyC06:0.025,SoyC07:0.025,SoyC08:0.025,SoyC09:0.025,SoyC10:0.025,SoyC11:0.025,SoyC12:0.025,SoyC13:0.025,SoyC14:0.025,SoyL01:0.025,SoyL02:0.025,SoyL03:0.025,SoyL04:0.025,SoyL05:0.025,SoyL06:0.025,SoyL07:0.025,SoyL08:0.025,SoyL09:0.025,SoyW01:0.025,SoyW02:0.025,SoyW03:0.025,Tianlong1:0.025,W05:0.025,Wenfeng7:0.025,ZH13:0.025,ZH35:0.025,ZN6:0.025,_MINIGRAPH_:0.025)Anc0;', '--logLevel', 'INFO', '--alignments', 'Anc0_primary.paf', '--params', 'Anc0.config.xml', '--outputFile', 'Anc0.c2h', '--outputHalFastaFile', 'Anc0.c2h.fa', '--outputReferenceFile', 'Anc0.ref', '--outgroupEvents', '', '--referenceEvent', 'Anc0', '--threads', '20'] exited 1:
        [2024-07-04T11:08:31+0800] [MainThread] [E] [toil.worker] Exiting the worker because of a failed job on host node105
