### ISSUE TITLE
error cactus-align

### ISSUE THREAD

**Issue by anamatgu** [ComparativeGenomicsToolkit/cactus#1444]
Hi,

I'm trying to run cactus-align (v2.8.4) skipping the Splitting By Chromosome step with the following comand:

cactus-align ./jobstore asmhifi_217.txt cactus1.paf cactus1.hal --pangenome --outVG --reference MTBanc

And I get the following error (I've tried to run the same command using the yeast_test and I got the same error):

[2024-07-22T16:52:03+0200] [MainThread] [I] [toil.realtimeLogger] Stopping real-time logging server.
[2024-07-22T16:52:03+0200] [MainThread] [I] [toil.realtimeLogger] Joining real-time logging server thread.
Traceback (most recent call last):
  File "/home/ana/SoftAna/miniconda3/envs/py3.8/bin/cactus-align", line 8, in <module>
    sys.exit(main())
  File "/home/ana/SoftAna/miniconda3/envs/py3.8/lib/python3.8/site-packages/cactus/setup/cactus_align.py", line 178, in main
    results_dict = toil.start(Job.wrapJobFn(batch_align_jobs, align_jobs))
  File "/home/ana/SoftAna/miniconda3/envs/py3.8/lib/python3.8/site-packages/toil/common.py", line 930, in start
    return self._runMainLoop(rootJobDescription)
  File "/home/ana/SoftAna/miniconda3/envs/py3.8/lib/python3.8/site-packages/toil/common.py", line 1412, in _runMainLoop
    return Leader(config=self.config,
  File "/home/ana/SoftAna/miniconda3/envs/py3.8/lib/python3.8/site-packages/toil/leader.py", line 304, in run
    raise FailedJobsException(self.jobStore, failed_jobs, exit_code=self.recommended_fail_exit_code)
toil.exceptions.FailedJobsException: The job store '/data2/ana_compartido/pacbio_asm_fbAG75/cactus_steps/js-test' contains 3 failed jobs: 'Job' kind-batch_align_jobs/instance-p5z5a6x5 v6, 'cactus_cons' kind-cactus_cons/instance-yutzvyvi v6, 'cactus_cons_with_resources' kind-cactus_cons_with_resources/instance-ymvoc7ra v3
Log from job "'cactus_cons' kind-cactus_cons/instance-yutzvyvi v6" follows:
=========>
	[2024-07-22T16:51:54+0200] [MainThread] [I] [toil.worker] ---TOIL WORKER OUTPUT LOG---
	[2024-07-22T16:51:54+0200] [MainThread] [I] [toil] Running Toil version 7.0.0-d569ea5711eb310ffd5703803f7250ebf7c19576 on host yersin.
	[2024-07-22T16:51:54+0200] [MainThread] [I] [toil.worker] Working on job 'cactus_cons' kind-cactus_cons/instance-yutzvyvi v4
	[2024-07-22T16:51:54+0200] [MainThread] [I] [toil.worker] Loaded body Job('cactus_cons' kind-cactus_cons/instance-yutzvyvi v4) from description 'cactus_cons' kind-cactus_cons/instance-yutzvyvi v4
	[2024-07-22T16:51:54+0200] [MainThread] [W] [toil.statsAndLogging] Deprecated toil method that will be moved/replaced in a future release."
	[2024-07-22T16:51:54+0200] [MainThread] [W] [root] Deprecated toil method.  Please call "logging.getLevelName" directly.
	[2024-07-22T16:51:54+0200] [MainThread] [I] [cactus.shared.common] Docker work dir: /tmp/toilwf-38a9b08ec48b55aca9e2d24a016f3757/61c1/job/tmpap567twv
	[2024-07-22T16:51:54+0200] [MainThread] [I] [cactus.shared.common] Running the command ['docker', 'run', '--interactive', '--net=host', '--log-driver=none', '-u', '3008:100', '-v', '/tmp/toilwf-38a9b08ec48b55aca9e2d24a016f3757/61c1/job/tmpap567twv:/data', '--entrypoint', '/opt/cactus/wrapper.sh', '--name', 'c1b188b6-f193-47f0-876b-8a7f69ea63f0', '--rm', 'quay.io/comparative-genomics-toolkit/cactus:v2.8.4', 'cactus_consolidated', '--seqFile', 'Anc0.seqfile', '--logLevel', 'INFO', '--alignments', 'Anc0_primary.paf', '--params', 'Anc0.config.xml', '--outputFile', 'Anc0.c2h', '--outputHalFastaFile', 'Anc0.c2h.fa', '--outputReferenceFile', 'Anc0.ref', '--outgroupEvents', '', '--referenceEvent', 'Anc0', '--threads', '24']
	[2024-07-22T16:51:54+0200] [MainThread] [I] [toil-rt] 2024-07-22 16:51:54.993469: Running the command: "docker run --interactive --net=host --log-driver=none -u 3008:100 -v /tmp/toilwf-38a9b08ec48b55aca9e2d24a016f3757/61c1/job/tmpap567twv:/data --entrypoint /opt/cactus/wrapper.sh --name c1b188b6-f193-47f0-876b-8a7f69ea63f0 --rm quay.io/comparative-genomics-toolkit/cactus:v2.8.4 cactus_consolidated --seqFile Anc0.seqfile --logLevel INFO --alignments Anc0_primary.paf --params Anc0.config.xml --outputFile Anc0.c2h --outputHalFastaFile Anc0.c2h.fa --outputReferenceFile Anc0.ref --outgroupEvents  --referenceEvent Anc0 --threads 24"
	[2024-07-22T16:51:55+0200] [MainThread] [I] [toil-rt] cactus_consolidated(Anc0): Running command catchsegv 'cactus_consolidated' '--seqFile' 'Anc0.seqfile' '--logLevel' 'INFO' '--alignments' 'Anc0_primary.paf' '--params' 'Anc0.config.xml' '--outputFile' 'Anc0.c2h' '--outputHalFastaFile' 'Anc0.c2h.fa' '--outputReferenceFile' 'Anc0.ref' '--outgroupEvents' '' '--referenceEvent' 'Anc0' '--threads' '24'
	**[2024-07-22T16:51:55+0200] [MainThread] [I] [toil-rt] cactus_consolidated(Anc0): cactus_consolidated: unrecognized option '--seqFile'**
	[2024-07-22T16:51:55+0200] [MainThread] [I] [toil-rt] cactus_consolidated(Anc0): cactus_consolidated, version 0.2
	[2024-07-22T16:51:55+0200] [MainThread] [I] [toil-rt] cactus_consolidated(Anc0): -l --logLevel : Set the log level
	[2024-07-22T16:51:55+0200] [MainThread] [I] [toil-rt] cactus_consolidated(Anc0): -p --params : [Required] The cactus config file
	[2024-07-22T16:51:55+0200] [MainThread] [I] [toil-rt] cactus_consolidated(Anc0): -f --outputFile : [Required] The file to write the combined cactus to hal output
	[2024-07-22T16:51:55+0200] [MainThread] [I] [toil-rt] cactus_consolidated(Anc0): -F --outputHalFastaFile : The file to write the sequences in to build the hal file.
	[2024-07-22T16:51:55+0200] [MainThread] [I] [toil-rt] cactus_consolidated(Anc0): -G --outputReferenceFile : The file to write the sequences of the reference in (used in the progressive recursion).
	[2024-07-22T16:51:55+0200] [MainThread] [I] [toil-rt] cactus_consolidated(Anc0): -s --sequences [Required] [eventName fastaFile/Directory]xN: The sequences
	[2024-07-22T16:51:55+0200] [MainThread] [I] [toil-rt] cactus_consolidated(Anc0): -a --alignments : [Required] The alignments file
	[2024-07-22T16:51:55+0200] [MainThread] [I] [toil-rt] cactus_consolidated(Anc0): -S --secondaryAlignments : The secondary alignments file
	[2024-07-22T16:51:55+0200] [MainThread] [I] [toil-rt] cactus_consolidated(Anc0): -c --constraintAlignments : The constraint alignments file
	[2024-07-22T16:51:55+0200] [MainThread] [I] [toil-rt] cactus_consolidated(Anc0): -g --speciesTree : [Required] The species tree, which will form the skeleton of the event tree
	[2024-07-22T16:51:55+0200] [MainThread] [I] [toil-rt] cactus_consolidated(Anc0): -o --outgroupEvents : Leaf events in the species tree identified as outgroups
	[2024-07-22T16:51:55+0200] [MainThread] [I] [toil-rt] cactus_consolidated(Anc0): -r --referenceEvent : [Required] The name of the reference event
	[2024-07-22T16:51:55+0200] [MainThread] [I] [toil-rt] cactus_consolidated(Anc0): -t --runChecks : Run cactus checks after each stage, used for debugging
	[2024-07-22T16:51:55+0200] [MainThread] [I] [toil-rt] cactus_consolidated(Anc0): -T --threads : (int > 0) Use up to this many threads [default: all available]
	[2024-07-22T16:51:55+0200] [MainThread] [I] [toil-rt] cactus_consolidated(Anc0): -h --help : Print this help message
	[2024-07-22T16:51:55+0200] [MainThread] [W] [toil.fileStores.abstractFileStore] Failed job accessed files:
	[2024-07-22T16:51:55+0200] [MainThread] [W] [toil.fileStores.abstractFileStore] Downloaded file 'files/for-job/kind-sanitize_fasta_header/instance-u22hnp34/file-2aa7abd0fc1e4fd7914621cde374494e/S288C.sanitized.fa' to path '/tmp/toilwf-38a9b08ec48b55aca9e2d24a016f3757/61c1/job/tmpap567twv/S288C.fa'
	[2024-07-22T16:51:55+0200] [MainThread] [W] [toil.fileStores.abstractFileStore] Downloaded file 'files/for-job/kind-sanitize_fasta_header/instance-3bdck4c_/file-a061ce0132b74a9fb244a7cf3214072c/SK1.sanitized.fa' to path '/tmp/toilwf-38a9b08ec48b55aca9e2d24a016f3757/61c1/job/tmpap567twv/SK1.fa'
	[2024-07-22T16:51:55+0200] [MainThread] [W] [toil.fileStores.abstractFileStore] Downloaded file 'files/for-job/kind-sanitize_fasta_header/instance-8jona048/file-73ca973a34b747109af1c76e2ff59971/DBVPG6044.sanitized.fa' to path '/tmp/toilwf-38a9b08ec48b55aca9e2d24a016f3757/61c1/job/tmpap567twv/DBVPG6044.fa'
	[2024-07-22T16:51:55+0200] [MainThread] [W] [toil.fileStores.abstractFileStore] Downloaded file 'files/for-job/kind-sanitize_fasta_header/instance-qi4br674/file-9b5053cb927849c587d3a96b93718bc5/UWOPS034614.sanitized.fa' to path '/tmp/toilwf-38a9b08ec48b55aca9e2d24a016f3757/61c1/job/tmpap567twv/UWOPS034614.fa'
	[2024-07-22T16:51:55+0200] [MainThread] [W] [toil.fileStores.abstractFileStore] Downloaded file 'files/for-job/kind-sanitize_fasta_header/instance-jjtt1zg1/file-c8ff690bff6b47ffb1e6caf54f3fbe1e/Y12.sanitized.fa' to path '/tmp/toilwf-38a9b08ec48b55aca9e2d24a016f3757/61c1/job/tmpap567twv/Y12.fa'
	[2024-07-22T16:51:55+0200] [MainThread] [W] [toil.fileStores.abstractFileStore] Downloaded file 'files/for-job/kind-sanitize_fasta_header/instance-95b8nd55/file-9e2febadf05949f18b7a773b31b397f3/YPS128.sanitized.fa' to path '/tmp/toilwf-38a9b08ec48b55aca9e2d24a016f3757/61c1/job/tmpap567twv/YPS128.fa'
	[2024-07-22T16:51:55+0200] [MainThread] [W] [toil.fileStores.abstractFileStore] Downloaded file 'files/for-job/kind-sanitize_fasta_header/instance-_ioa6y7b/file-f493414ab24a4210b4662922538f7e0e/_MINIGRAPH_.sanitized.fa' to path '/tmp/toilwf-38a9b08ec48b55aca9e2d24a016f3757/61c1/job/tmpap567twv/_MINIGRAPH_.fa'
	[2024-07-22T16:51:55+0200] [MainThread] [W] [toil.fileStores.abstractFileStore] Downloaded file 'files/for-job/kind-filter_paf/instance-wqyenccg/file-e430da78f2fc44c3a5f7b3a1e335db5d/mg.paf.filter.overlap' to path '/tmp/toilwf-38a9b08ec48b55aca9e2d24a016f3757/61c1/job/tmpap567twv/Anc0.paf'
	[2024-07-22T16:51:55+0200] [MainThread] [C] [toil.worker] Worker crashed with traceback:
	Traceback (most recent call last):
	  File "/home/ana/SoftAna/miniconda3/envs/py3.8/lib/python3.8/site-packages/toil/worker.py", line 438, in workerScript
	    job._runner(jobGraph=None, jobStore=job_store, fileStore=fileStore, defer=defer)
	  File "/home/ana/SoftAna/miniconda3/envs/py3.8/lib/python3.8/site-packages/toil/job.py", line 2984, in _runner
	    returnValues = self._run(jobGraph=None, fileStore=fileStore)
	  File "/home/ana/SoftAna/miniconda3/envs/py3.8/lib/python3.8/site-packages/toil/job.py", line 2895, in _run
	    return self.run(fileStore)
	  File "/home/ana/SoftAna/miniconda3/envs/py3.8/lib/python3.8/site-packages/toil/job.py", line 3158, in run
	    rValue = userFunction(*((self,) + tuple(self._args)), **self._kwargs)
	  File "/home/ana/SoftAna/miniconda3/envs/py3.8/lib/python3.8/site-packages/cactus/pipeline/cactus_workflow.py", line 148, in cactus_cons
	    messages = cactus_call(check_output=True, returnStdErr=True,
	  File "/home/ana/SoftAna/miniconda3/envs/py3.8/lib/python3.8/site-packages/cactus/shared/common.py", line 910, in cactus_call
	    raise RuntimeError("{}Command {} exited {}: {}".format(sigill_msg, call, process.returncode, out))
	RuntimeError: cactus_consolidated(Anc0): Command ['docker', 'run', '--interactive', '--net=host', '--log-driver=none', '-u', '3008:100', '-v', '/tmp/toilwf-38a9b08ec48b55aca9e2d24a016f3757/61c1/job/tmpap567twv:/data', '--entrypoint', '/opt/cactus/wrapper.sh', '--name', 'c1b188b6-f193-47f0-876b-8a7f69ea63f0', '--rm', 'quay.io/comparative-genomics-toolkit/cactus:v2.8.4', 'cactus_consolidated', '--seqFile', 'Anc0.seqfile', '--logLevel', 'INFO', '--alignments', 'Anc0_primary.paf', '--params', 'Anc0.config.xml', '--outputFile', 'Anc0.c2h', '--outputHalFastaFile', 'Anc0.c2h.fa', '--outputReferenceFile', 'Anc0.ref', '--outgroupEvents', '', '--referenceEvent', 'Anc0', '--threads', '24'] exited 1: 
	
	[2024-07-22T16:51:55+0200] [MainThread] [E] [toil.worker] Exiting the worker because of a failed job on host yersin
<=========

I'd really appreciate any suggestions to solve this problem.

Thank you very much in advance!

Ana

**Comment by glennhickey** [comment]
You are using the Cactus master branch (which I guess you installed with `git clone`), not v2.8.4.  The easiest way to install Cactus locally is to download the binaries from the release page https://github.com/ComparativeGenomicsToolkit/cactus#getting-cactus and follow the instructions there to install (BIN-INSTALL.md)
