### ISSUE TITLE
CDS

### ISSUE THREAD

**Issue by aebaci** [ComparativeGenomicsToolkit/cactus#1463]
Can Cactus be used to align the list of CDS from several species? Impliying that none of the sequences will be masked.I've tried it and I got an error (below).
I thought it was a version problem, but after installing 2.9 it didn't work again. Seems to be at the hal export phase. I have attached the log from the run with cactus 2.8 and 2.9.
Thanks.

[log2-8.txt](https://github.com/user-attachments/files/16617841/log2-8.txt)
[log2-9.txt](https://github.com/user-attachments/files/16617891/log2-9.txt)
Below is the last message from the run with 2.9
[2024-08-14T17:24:46+0100] [MainThread] [C] [toil.worker] Worker crashed with traceback:
        Traceback (most recent call last):
          File "/home/antonella/cactus-bin-v2.9.0/venv-cactus-v2.9.0/lib/python3.10/site-packages/toil/worker.py", line 438, in workerScript
            job._runner(jobGraph=None, jobStore=job_store, fileStore=fileStore, defer=defer)
          File "/home/antonella/cactus-bin-v2.9.0/venv-cactus-v2.9.0/lib/python3.10/site-packages/toil/job.py", line 2984, in _runner
            returnValues = self._run(jobGraph=None, fileStore=fileStore)
          File "/home/antonella/cactus-bin-v2.9.0/venv-cactus-v2.9.0/lib/python3.10/site-packages/toil/job.py", line 2895, in _run
            return self.run(fileStore)
          File "/home/antonella/cactus-bin-v2.9.0/venv-cactus-v2.9.0/lib/python3.10/site-packages/toil/job.py", line 3158, in run
            rValue = userFunction(*((self,) + tuple(self._args)), **self._kwargs)
          File "/home/antonella/cactus-bin-v2.9.0/venv-cactus-v2.9.0/lib/python3.10/site-packages/cactus/progressive/cactus_progressive.py", line 268, in export_hal
            cactus_call(parameters=args, job_memory=job.memory)
          File "/home/antonella/cactus-bin-v2.9.0/venv-cactus-v2.9.0/lib/python3.10/site-packages/cactus/shared/common.py", line 912, in cactus_call
            raise RuntimeError("{}Command {} signaled {}: {}".format(sigill_msg, call, signal.Signals(-process.returncode).name, out))
        RuntimeError: Command ['halAppendCactusSubtree', '/tmp/toilwf-0a5809edfa225b61820ea0c9e64dccad/fa00/job/tmp1c2cq32i/Anc07.hal.c2h', '/tmp/toilwf-0a5809edfa225b61820ea0c9e64dccad/fa00/job/tmp1c2cq32i/Anc07.hal.fa', '/tmp/toilwf-0a5809edfa225b61820ea0c9e64dccad/fa00/job/tmp1c2cq32i/Anc07.newick', '/tmp/toilwf-0a5809edfa225b61820ea0c9e64dccad/fa00/job/tmp1c2cq32i/Anc00.hal', '--outgroups', 'RHOEC.Rhodnius_ecuadoriensis,RHOBR.Rhodnius_brethesi'] signaled SIGABRT: stderr=terminate called after throwing an instance of 'hal_exception'
          what():  DnaAccess is dirty, flush() should have been called

        [2024-08-14T17:24:46+0100] [MainThread] [E] [toil.worker] Exiting the worker because of a failed job on host obelix

**Comment by glennhickey** [comment]
Are your two logs on the same data?  They seem quite different, apart from the 2.8 one not crashing, the alignment stats seem quite different.  Ex in 2.8

>cactus_consolidated(Anc00): Sequence graph statistics after annealing:
>cactus_consolidated(Anc00): There were 553175 blocks in the sequence graph, representing 51022420 total aligned bases

vs 2.9

>cactus_consolidated(Anc00): Sequence graph statistics after annealing:
>cactus_consolidated(Anc00): There were 97456 blocks in the sequence graph, representing 20691777 total aligned bases

where there aren't any changes between the versions that should have any effect.  If you are able to share the input data, I can try to reproduce the crash here.
