### ISSUE TITLE
Failed job cactus_consolidate

### ISSUE THREAD

**Issue by jallen73** [ComparativeGenomicsToolkit/cactus#1471]
I've spent most of the day now trying to get cactus to run and I keep getting errors. I've tried uninstalling and reinstalling it. When I run it on the test data it works well, but I can't seem to get it to run on my data. Would definitely appreciate some insight here.

THE FIRST ERROR:
[2024-08-27T16:24:01-0700] [MainThread] [I] [toil-rt] cactus_consolidated(0.62587): Killed
[2024-08-27T16:24:02-0700] [Thread-1 (daddy)] [E] [toil.batchSystems.singleMachine] Got exit code 1 (indicating failure) from job _toil_worker cactus_cons file:/mnt/c/Users/jessi/Documents/tools/cactus/jobstore kind-cactus_cons/instance-084c0khg.
[2024-08-27T16:24:02-0700] [MainThread] [W] [toil.leader] Job failed with exit value 1: 'cactus_cons' kind-cactus_cons/instance-084c0khg v1
Exit reason: None
[2024-08-27T16:24:02-0700] [MainThread] [W] [toil.leader] The job seems to have left a log file, indicating failure: 'cactus_cons' kind-cactus_cons/instance-084c0khg v2
[2024-08-27T16:24:02-0700] [MainThread] [W] [toil.leader] Log from job "kind-cactus_cons/instance-084c0khg" follows:

THE LAST ERROR:
[2024-08-27T16:27:30-0700] [MainThread] [C] [toil.worker] Worker crashed with traceback:
        Traceback (most recent call last):
          File "/mnt/c/Users/jessi/Documents/tools/cactus/cactus_env/lib/python3.10/site-packages/toil/worker.py", line 438, in workerScript
            job._runner(jobGraph=None, jobStore=job_store, fileStore=fileStore, defer=defer)
          File "/mnt/c/Users/jessi/Documents/tools/cactus/cactus_env/lib/python3.10/site-packages/toil/job.py", line 2984, in _runner
            returnValues = self._run(jobGraph=None, fileStore=fileStore)
          File "/mnt/c/Users/jessi/Documents/tools/cactus/cactus_env/lib/python3.10/site-packages/toil/job.py", line 2895, in _run
            return self.run(fileStore)
          File "/mnt/c/Users/jessi/Documents/tools/cactus/cactus_env/lib/python3.10/site-packages/toil/job.py", line 3158, in run
            rValue = userFunction(*((self,) + tuple(self._args)), **self._kwargs)
          File "/mnt/c/Users/jessi/Documents/tools/cactus/cactus_env/lib/python3.10/site-packages/cactus/pipeline/cactus_workflow.py", line 148, in cactus_cons
            messages = cactus_call(check_output=True, returnStdErr=True,
          File "/mnt/c/Users/jessi/Documents/tools/cactus/cactus_env/lib/python3.10/site-packages/cactus/shared/common.py", line 910, in cactus_call
            raise RuntimeError("{}Command {} exited {}: {}".format(sigill_msg, call, process.returncode, out))
        RuntimeError: cactus_consolidated(0.6139): Command ['docker', 'run', '--interactive', '--net=host', '--log-driver=none', '-u', '1000:1000', '-v', '/tmp/toilwf-08311a21086f5e9082f108730814374c/3342/job/tmpkix1u6mn:/data', '--entrypoint', '/opt/cactus/wrapper.sh', '--name', 'f4374f11-87c3-4638-873d-1c36f0785598', '--rm', 'quay.io/comparative-genomics-toolkit/cactus:v2.9.0', 'cactus_consolidated', '--seqFile', '0.6139.seqfile', '--logLevel', 'INFO', '--alignments', '0.6139_primary.paf', '--params', '0.6139.config.xml', '--outputFile', '0.6139.c2h', '--outputHalFastaFile', '0.6139.c2h.fa', '--outputReferenceFile', '0.6139.ref', '--outgroupEvents', 'Aspfov Aspnid', '--referenceEvent', '0.6139', '--threads', '22'] exited 1:

        [2024-08-27T16:27:30-0700] [MainThread] [E] [toil.worker] Exiting the worker because of a failed job on host jallen

**Comment by glennhickey** [comment]
When you see `Killed` that generally means the job was stopped by your system due to using too much memory.
