### ISSUE TITLE
Job ends at RunCactusPreprocessorThenProgressiveDown

### ISSUE THREAD

**Issue by ShoumikSaha** [ComparativeGenomicsToolkit/cactus#149]
After running cactus with given basic format (**cactus jobstore examples/evolverMammals.txt examples/evolverMammals.hal --root mr --restart**), 
This error message is being shown- 
"INFO:toil.worker:Redirecting logging to /tmp/toil-df965cc4-0d0e-4824-9066-36fa9efecae3-3a82b8c940344fe39ed4b367a7e64d29/tmpFTE0XV/worker_log.txt
Job ended: 'RunCactusPreprocessorThenProgressiveDown' kind-RunCactusPreprocessorThenProgressiveDown/instance95jhxi
The job seems to have left a log file, indicating failure: 'RunCactusPreprocessorThenProgressiveDown' kind-RunCactusPreprocessorThenProgressiveDown/instance95jhxi
kind-RunCactusPreprocessorThenProgressiveDown/instance95jhxi    INFO:toil.worker:---TOIL WORKER OUTPUT LOG---
kind-RunCactusPreprocessorThenProgressiveDown/instance95jhxi    INFO:toil:Running Toil version 3.24.0-de586251cb579bcb80eef435825cb3cedc202f52.
kind-RunCactusPreprocessorThenProgressiveDown/instance95jhxi    WARNING:toil.resource:'JTRES_364ad79b7ea1161545b6a7d31aa12b81' may exist, but is not yet referenced by the worker (KeyError from os.environ[]).
kind-RunCactusPreprocessorThenProgressiveDown/instance95jhxi    WARNING:toil.fileStores.nonCachingFileStore:Starting job files/for-job/kind-RunCactusPreprocessorThenProgressiveDown/instance95jhxi/cleanup/file-0v1ioi/stream with less than 10% of disk space remaining.
kind-RunCactusPreprocessorThenProgressiveDown/instance95jhxi    Traceback (most recent call last):
kind-RunCactusPreprocessorThenProgressiveDown/instance95jhxi      File "/home/shoumik/Thesis/cactus_env/local/lib/python2.7/site-packages/toil/worker.py", line 366, in workerScript
kind-RunCactusPreprocessorThenProgressiveDown/instance95jhxi        job._runner(jobGraph=jobGraph, jobStore=jobStore, fileStore=fileStore, defer=defer)
kind-RunCactusPreprocessorThenProgressiveDown/instance95jhxi    TypeError: _runner() got an unexpected keyword argument 'defer'
kind-RunCactusPreprocessorThenProgressiveDown/instance95jhxi    ERROR:toil.worker:Exiting the worker because of a failed job on host shoumik-Aspire-E5-573G
kind-RunCactusPreprocessorThenProgressiveDown/instance95jhxi    WARNING:toil.jobGraph:Due to failure we are reducing the remaining retry count of job 'RunCactusPreprocessorThenProgressiveDown' kind-RunCactusPreprocessorThenProgressiveDown/instance95jhxi with ID kind-RunCactusPreprocessorThenProgressiveDown/instance95jhxi to 5"

A log.txt file is being attached containing the log.
[log.txt](https://github.com/ComparativeGenomicsToolkit/cactus/files/4228221/log.txt)

**Comment by joelarmstrong** [comment]
It sounds like you may need to either update your cactus version or
downgrade your toil version. I think support for toil >3.21 or so was only
recently added to cactus.

**Comment by diekhans** [comment]
please use the latest toil and cactus, it is easier for us tto
support just one version.

**Comment by ShoumikSaha** [comment]
I'm trying to install cactus once again. This time, I'm using **python 3.6.8** and **toil 3.24.0**
After creating the environment and upgrading toil, I'm executing **pip install --upgrade .** from the environment but it's failing to install cactus showing this error - 
"Building wheels for collected packages: Cactus
  Building wheel for Cactus (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /home/shoumik/Thesis2/cactus_env/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-req-build-r718fzym/setup.py'"'"'; __file__='"'"'/tmp/pip-req-build-r718fzym/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-1vsn59pa
       cwd: /tmp/pip-req-build-r718fzym/
  Complete output (122 lines):
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib
  creating build/lib/cactus
  copying src/cactus/__init__.py -> build/lib/cactus
  creating build/lib/cactus/setup
  copying src/cactus/setup/__init__.py -> build/lib/cactus/setup
  creating build/lib/cactus/pipeline
  copying src/cactus/pipeline/cactus_evolverTest.py -> build/lib/cactus/pipeline
  copying src/cactus/pipeline/ktserverControl.py -> build/lib/cactus/pipeline
  copying src/cactus/pipeline/__init__.py -> build/lib/cactus/pipeline
  copying src/cactus/pipeline/ktserverToil.py -> build/lib/cactus/pipeline
  copying src/cactus/pipeline/cactus_workflow.py -> build/lib/cactus/pipeline
  copying src/cactus/pipeline/cactus_workflowTest.py -> build/lib/cactus/pipeline
  creating build/lib/cactus/phylogeny
  copying src/cactus/phylogeny/__init__.py -> build/lib/cactus/phylogeny
  copying src/cactus/phylogeny/cactus_phylogenyTest.py -> build/lib/cactus/phylogeny
  creating build/lib/cactus/reference
  copying src/cactus/reference/cactus_referenceTest.py -> build/lib/cactus/reference
  copying src/cactus/reference/__init__.py -> build/lib/cactus/reference
  creating build/lib/cactus/api
  copying src/cactus/api/__init__.py -> build/lib/cactus/api
  creating build/lib/cactus/preprocessor
  copying src/cactus/preprocessor/checkUniqueHeaders.py -> build/lib/cactus/preprocessor
  copying src/cactus/preprocessor/preprocessorTest.py -> build/lib/cactus/preprocessor
  copying src/cactus/preprocessor/cactus_preprocessor.py -> build/lib/cactus/preprocessor
  copying src/cactus/preprocessor/__init__.py -> build/lib/cactus/preprocessor
  copying src/cactus/preprocessor/cactus_preprocessorTest.py -> build/lib/cactus/preprocessor
  creating build/lib/cactus/progressive
  copying src/cactus/progressive/outgroup.py -> build/lib/cactus/progressive
  copying src/cactus/progressive/schedule.py -> build/lib/cactus/progressive
  copying src/cactus/progressive/multiCactusTreeTest.py -> build/lib/cactus/progressive
  copying src/cactus/progressive/scheduleTest.py -> build/lib/cactus/progressive
  copying src/cactus/progressive/projectWrapper.py -> build/lib/cactus/progressive
  copying src/cactus/progressive/cactus_createMultiCactusProject.py -> build/lib/cactus/progressive
  copying src/cactus/progressive/cactus_progressive.py -> build/lib/cactus/progressive
  copying src/cactus/progressive/seqFile.py -> build/lib/cactus/progressive
  copying src/cactus/progressive/__init__.py -> build/lib/cactus/progressive
  copying src/cactus/progressive/multiCactusProject.py -> build/lib/cactus/progressive
  copying src/cactus/progressive/cactus_constructFromIntermediates.py -> build/lib/cactus/progressive
  copying src/cactus/progressive/outgroupTest.py -> build/lib/cactus/progressive
  copying src/cactus/progressive/cactus_progressiveTest.py -> build/lib/cactus/progressive
  copying src/cactus/progressive/multiCactusTree.py -> build/lib/cactus/progressive
  creating build/lib/cactus/hal
  copying src/cactus/hal/cactus_halTest.py -> build/lib/cactus/hal
  copying src/cactus/hal/__init__.py -> build/lib/cactus/hal
  creating build/lib/cactus/normalisation
  copying src/cactus/normalisation/__init__.py -> build/lib/cactus/normalisation
  copying src/cactus/normalisation/cactus_normalisationTest.py -> build/lib/cactus/normalisation
  creating build/lib/cactus/shared
  copying src/cactus/shared/common.py -> build/lib/cactus/shared
  copying src/cactus/shared/configWrapper.py -> build/lib/cactus/shared
  copying src/cactus/shared/version.py -> build/lib/cactus/shared
  copying src/cactus/shared/commonTest.py -> build/lib/cactus/shared
  copying src/cactus/shared/test.py -> build/lib/cactus/shared
  copying src/cactus/shared/experimentWrapperTest.py -> build/lib/cactus/shared
  copying src/cactus/shared/__init__.py -> build/lib/cactus/shared
  copying src/cactus/shared/experimentWrapper.py -> build/lib/cactus/shared
  creating build/lib/cactus/bar
  copying src/cactus/bar/__init__.py -> build/lib/cactus/bar
  copying src/cactus/bar/cactus_barTest.py -> build/lib/cactus/bar
  creating build/lib/cactus/blast
  copying src/cactus/blast/blast.py -> build/lib/cactus/blast
  copying src/cactus/blast/cactus_coverageTest.py -> build/lib/cactus/blast
  copying src/cactus/blast/blastParametersScript.py -> build/lib/cactus/blast
  copying src/cactus/blast/mappingQualityRescoringAndFiltering.py -> build/lib/cactus/blast
  copying src/cactus/blast/trimSequences.py -> build/lib/cactus/blast
  copying src/cactus/blast/__init__.py -> build/lib/cactus/blast
  copying src/cactus/blast/blastTest.py -> build/lib/cactus/blast
  copying src/cactus/blast/cactus_realignTest.py -> build/lib/cactus/blast
  copying src/cactus/blast/mappingQualityRescoringAndFilteringTest.py -> build/lib/cactus/blast
  copying src/cactus/blast/upconvertCoordinates.py -> build/lib/cactus/blast
  copying src/cactus/blast/trimSequencesTest.py -> build/lib/cactus/blast
  creating build/lib/cactus/caf
  copying src/cactus/caf/__init__.py -> build/lib/cactus/caf
  creating build/lib/cactus/faces
  copying src/cactus/faces/cactus_fillAdjacenciesTest.py -> build/lib/cactus/faces
  copying src/cactus/faces/__init__.py -> build/lib/cactus/faces
  creating build/lib/cactus/preprocessor/lastzRepeatMasking
  copying src/cactus/preprocessor/lastzRepeatMasking/cactus_lastzRepeatMaskTest.py -> build/lib/cactus/preprocessor/lastzRepeatMasking
  copying src/cactus/preprocessor/lastzRepeatMasking/__init__.py -> build/lib/cactus/preprocessor/lastzRepeatMasking
  copying src/cactus/preprocessor/lastzRepeatMasking/cactus_lastzRepeatMask.py -> build/lib/cactus/preprocessor/lastzRepeatMasking
  running egg_info
  creating src/Cactus.egg-info
  writing src/Cactus.egg-info/PKG-INFO
  writing dependency_links to src/Cactus.egg-info/dependency_links.txt
  writing entry points to src/Cactus.egg-info/entry_points.txt
  writing requirements to src/Cactus.egg-info/requires.txt
  writing top-level names to src/Cactus.egg-info/top_level.txt
  writing manifest file 'src/Cactus.egg-info/SOURCES.txt'
  reading manifest file 'src/Cactus.egg-info/SOURCES.txt'
  writing manifest file 'src/Cactus.egg-info/SOURCES.txt'
  copying src/cactus/cactus_progressive_config.xml -> build/lib/cactus
  copying src/cactus/cactus_config.xml -> build/lib/cactus
  installing to build/bdist.linux-x86_64/wheel
  running install
  ERROR: Directory 'submodules/sonLib' is not installable. Neither 'setup.py' nor 'pyproject.toml' found.
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/tmp/pip-req-build-r718fzym/setup.py", line 49, in <module>
      'cactus_preprocess = cactus.preprocessor.cactus_preprocessor:main']},)
    File "/home/shoumik/Thesis2/cactus_env/lib/python3.6/site-packages/setuptools/__init__.py", line 144, in setup
      return distutils.core.setup(**attrs)
    File "/usr/lib/python3.6/distutils/core.py", line 148, in setup
      dist.run_commands()
    File "/usr/lib/python3.6/distutils/dist.py", line 955, in run_commands
      self.run_command(cmd)
    File "/usr/lib/python3.6/distutils/dist.py", line 974, in run_command
      cmd_obj.run()
    File "/home/shoumik/Thesis2/cactus_env/lib/python3.6/site-packages/wheel/bdist_wheel.py", line 259, in run
      self.run_command('install')
    File "/usr/lib/python3.6/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/usr/lib/python3.6/distutils/dist.py", line 974, in run_command
      cmd_obj.run()
    File "/tmp/pip-req-build-r718fzym/setup.py", line 18, in run
      subprocess.run(["pip", "install", "submodules/sonLib"], check=True)
    File "/usr/lib/python3.6/subprocess.py", line 438, in run
      output=stdout, stderr=stderr)
  subprocess.CalledProcessError: Command '['pip', 'install', 'submodules/sonLib']' returned non-zero exit status 1.
  ERROR: Failed building wheel for Cactus
  Running setup.py clean for Cactus
Failed to build Cactus
Installing collected packages: Cactus
    Running setup.py install for Cactus ... error
    ERROR: Command errored out with exit status 1:
     command: /home/shoumik/Thesis2/cactus_env/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-req-build-r718fzym/setup.py'"'"'; __file__='"'"'/tmp/pip-req-build-r718fzym/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-zaaathwp/install-record.txt --single-version-externally-managed --compile --install-headers /home/shoumik/Thesis2/cactus_env/include/site/python3.6/Cactus
         cwd: /tmp/pip-req-build-r718fzym/
    Complete output (19 lines):
    running install
    ERROR: Directory 'submodules/sonLib' is not installable. Neither 'setup.py' nor 'pyproject.toml' found.
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-req-build-r718fzym/setup.py", line 49, in <module>
        'cactus_preprocess = cactus.preprocessor.cactus_preprocessor:main']},)
      File "/home/shoumik/Thesis2/cactus_env/lib/python3.6/site-packages/setuptools/__init__.py", line 144, in setup
        return distutils.core.setup(**attrs)
      File "/usr/lib/python3.6/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/usr/lib/python3.6/distutils/dist.py", line 955, in run_commands
        self.run_command(cmd)
      File "/usr/lib/python3.6/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/tmp/pip-req-build-r718fzym/setup.py", line 18, in run
        subprocess.run(["pip", "install", "submodules/sonLib"], check=True)
      File "/usr/lib/python3.6/subprocess.py", line 438, in run
        output=stdout, stderr=stderr)
    subprocess.CalledProcessError: Command '['pip', 'install', 'submodules/sonLib']' returned non-zero exit status 1.
    ----------------------------------------
ERROR: Command errored out with exit status 1: /home/shoumik/Thesis2/cactus_env/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-req-build-r718fzym/setup.py'"'"'; __file__='"'"'/tmp/pip-req-build-r718fzym/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-zaaathwp/install-record.txt --single-version-externally-managed --compile --install-headers /home/shoumik/Thesis2/cactus_env/include/site/python3.6/Cactus Check the logs for full command output."

A log file is being attached here-
[log.txt](https://github.com/ComparativeGenomicsToolkit/cactus/files/4230981/log.txt)

**Comment by zhanghaoipp** [comment]
> I'm trying to install cactus once again. This time, I'm using **python 3.6.8** and **toil 3.24.0**
> After creating the environment and upgrading toil, I'm executing **pip install --upgrade .** from the environment but it's failing to install cactus showing this error -
> "Building wheels for collected packages: Cactus
> Building wheel for Cactus (setup.py) ... error
> ERROR: Command errored out with exit status 1:
> command: /home/shoumik/Thesis2/cactus_env/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-req-build-r718fzym/setup.py'"'"'; **file**='"'"'/tmp/pip-req-build-r718fzym/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(**file**);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, **file**, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-1vsn59pa
> cwd: /tmp/pip-req-build-r718fzym/
> Complete output (122 lines):
> running bdist_wheel
> running build
> running build_py
> creating build
> creating build/lib
> creating build/lib/cactus
> copying src/cactus/**init**.py -> build/lib/cactus
> creating build/lib/cactus/setup
> copying src/cactus/setup/**init**.py -> build/lib/cactus/setup
> creating build/lib/cactus/pipeline
> copying src/cactus/pipeline/cactus_evolverTest.py -> build/lib/cactus/pipeline
> copying src/cactus/pipeline/ktserverControl.py -> build/lib/cactus/pipeline
> copying src/cactus/pipeline/**init**.py -> build/lib/cactus/pipeline
> copying src/cactus/pipeline/ktserverToil.py -> build/lib/cactus/pipeline
> copying src/cactus/pipeline/cactus_workflow.py -> build/lib/cactus/pipeline
> copying src/cactus/pipeline/cactus_workflowTest.py -> build/lib/cactus/pipeline
> creating build/lib/cactus/phylogeny
> copying src/cactus/phylogeny/**init**.py -> build/lib/cactus/phylogeny
> copying src/cactus/phylogeny/cactus_phylogenyTest.py -> build/lib/cactus/phylogeny
> creating build/lib/cactus/reference
> copying src/cactus/reference/cactus_referenceTest.py -> build/lib/cactus/reference
> copying src/cactus/reference/**init**.py -> build/lib/cactus/reference
> creating build/lib/cactus/api
> copying src/cactus/api/**init**.py -> build/lib/cactus/api
> creating build/lib/cactus/preprocessor
> copying src/cactus/preprocessor/checkUniqueHeaders.py -> build/lib/cactus/preprocessor
> copying src/cactus/preprocessor/preprocessorTest.py -> build/lib/cactus/preprocessor
> copying src/cactus/preprocessor/cactus_preprocessor.py -> build/lib/cactus/preprocessor
> copying src/cactus/preprocessor/**init**.py -> build/lib/cactus/preprocessor
> copying src/cactus/preprocessor/cactus_preprocessorTest.py -> build/lib/cactus/preprocessor
> creating build/lib/cactus/progressive
> copying src/cactus/progressive/outgroup.py -> build/lib/cactus/progressive
> copying src/cactus/progressive/schedule.py -> build/lib/cactus/progressive
> copying src/cactus/progressive/multiCactusTreeTest.py -> build/lib/cactus/progressive
> copying src/cactus/progressive/scheduleTest.py -> build/lib/cactus/progressive
> copying src/cactus/progressive/projectWrapper.py -> build/lib/cactus/progressive
> copying src/cactus/progressive/cactus_createMultiCactusProject.py -> build/lib/cactus/progressive
> copying src/cactus/progressive/cactus_progressive.py -> build/lib/cactus/progressive
> copying src/cactus/progressive/seqFile.py -> build/lib/cactus/progressive
> copying src/cactus/progressive/**init**.py -> build/lib/cactus/progressive
> copying src/cactus/progressive/multiCactusProject.py -> build/lib/cactus/progressive
> copying src/cactus/progressive/cactus_constructFromIntermediates.py -> build/lib/cactus/progressive
> copying src/cactus/progressive/outgroupTest.py -> build/lib/cactus/progressive
> copying src/cactus/progressive/cactus_progressiveTest.py -> build/lib/cactus/progressive
> copying src/cactus/progressive/multiCactusTree.py -> build/lib/cactus/progressive
> creating build/lib/cactus/hal
> copying src/cactus/hal/cactus_halTest.py -> build/lib/cactus/hal
> copying src/cactus/hal/**init**.py -> build/lib/cactus/hal
> creating build/lib/cactus/normalisation
> copying src/cactus/normalisation/**init**.py -> build/lib/cactus/normalisation
> copying src/cactus/normalisation/cactus_normalisationTest.py -> build/lib/cactus/normalisation
> creating build/lib/cactus/shared
> copying src/cactus/shared/common.py -> build/lib/cactus/shared
> copying src/cactus/shared/configWrapper.py -> build/lib/cactus/shared
> copying src/cactus/shared/version.py -> build/lib/cactus/shared
> copying src/cactus/shared/commonTest.py -> build/lib/cactus/shared
> copying src/cactus/shared/test.py -> build/lib/cactus/shared
> copying src/cactus/shared/experimentWrapperTest.py -> build/lib/cactus/shared
> copying src/cactus/shared/**init**.py -> build/lib/cactus/shared
> copying src/cactus/shared/experimentWrapper.py -> build/lib/cactus/shared
> creating build/lib/cactus/bar
> copying src/cactus/bar/**init**.py -> build/lib/cactus/bar
> copying src/cactus/bar/cactus_barTest.py -> build/lib/cactus/bar
> creating build/lib/cactus/blast
> copying src/cactus/blast/blast.py -> build/lib/cactus/blast
> copying src/cactus/blast/cactus_coverageTest.py -> build/lib/cactus/blast
> copying src/cactus/blast/blastParametersScript.py -> build/lib/cactus/blast
> copying src/cactus/blast/mappingQualityRescoringAndFiltering.py -> build/lib/cactus/blast
> copying src/cactus/blast/trimSequences.py -> build/lib/cactus/blast
> copying src/cactus/blast/**init**.py -> build/lib/cactus/blast
> copying src/cactus/blast/blastTest.py -> build/lib/cactus/blast
> copying src/cactus/blast/cactus_realignTest.py -> build/lib/cactus/blast
> copying src/cactus/blast/mappingQualityRescoringAndFilteringTest.py -> build/lib/cactus/blast
> copying src/cactus/blast/upconvertCoordinates.py -> build/lib/cactus/blast
> copying src/cactus/blast/trimSequencesTest.py -> build/lib/cactus/blast
> creating build/lib/cactus/caf
> copying src/cactus/caf/**init**.py -> build/lib/cactus/caf
> creating build/lib/cactus/faces
> copying src/cactus/faces/cactus_fillAdjacenciesTest.py -> build/lib/cactus/faces
> copying src/cactus/faces/**init**.py -> build/lib/cactus/faces
> creating build/lib/cactus/preprocessor/lastzRepeatMasking
> copying src/cactus/preprocessor/lastzRepeatMasking/cactus_lastzRepeatMaskTest.py -> build/lib/cactus/preprocessor/lastzRepeatMasking
> copying src/cactus/preprocessor/lastzRepeatMasking/**init**.py -> build/lib/cactus/preprocessor/lastzRepeatMasking
> copying src/cactus/preprocessor/lastzRepeatMasking/cactus_lastzRepeatMask.py -> build/lib/cactus/preprocessor/lastzRepeatMasking
> running egg_info
> creating src/Cactus.egg-info
> writing src/Cactus.egg-info/PKG-INFO
> writing dependency_links to src/Cactus.egg-info/dependency_links.txt
> writing entry points to src/Cactus.egg-info/entry_points.txt
> writing requirements to src/Cactus.egg-info/requires.txt
> writing top-level names to src/Cactus.egg-info/top_level.txt
> writing manifest file 'src/Cactus.egg-info/SOURCES.txt'
> reading manifest file 'src/Cactus.egg-info/SOURCES.txt'
> writing manifest file 'src/Cactus.egg-info/SOURCES.txt'
> copying src/cactus/cactus_progressive_config.xml -> build/lib/cactus
> copying src/cactus/cactus_config.xml -> build/lib/cactus
> installing to build/bdist.linux-x86_64/wheel
> running install
> ERROR: Directory 'submodules/sonLib' is not installable. Neither 'setup.py' nor 'pyproject.toml' found.
> Traceback (most recent call last):
> File "", line 1, in 
> File "/tmp/pip-req-build-r718fzym/setup.py", line 49, in 
> 'cactus_preprocess = cactus.preprocessor.cactus_preprocessor:main']},)
> File "/home/shoumik/Thesis2/cactus_env/lib/python3.6/site-packages/setuptools/**init**.py", line 144, in setup
> return distutils.core.setup(**attrs)
> File "/usr/lib/python3.6/distutils/core.py", line 148, in setup
> dist.run_commands()
> File "/usr/lib/python3.6/distutils/dist.py", line 955, in run_commands
> self.run_command(cmd)
> File "/usr/lib/python3.6/distutils/dist.py", line 974, in run_command
> cmd_obj.run()
> File "/home/shoumik/Thesis2/cactus_env/lib/python3.6/site-packages/wheel/bdist_wheel.py", line 259, in run
> self.run_command('install')
> File "/usr/lib/python3.6/distutils/cmd.py", line 313, in run_command
> self.distribution.run_command(command)
> File "/usr/lib/python3.6/distutils/dist.py", line 974, in run_command
> cmd_obj.run()
> File "/tmp/pip-req-build-r718fzym/setup.py", line 18, in run
> subprocess.run(["pip", "install", "submodules/sonLib"], check=True)
> File "/usr/lib/python3.6/subprocess.py", line 438, in run
> output=stdout, stderr=stderr)
> subprocess.CalledProcessError: Command '['pip', 'install', 'submodules/sonLib']' returned non-zero exit status 1.
> ERROR: Failed building wheel for Cactus
> Running setup.py clean for Cactus
> Failed to build Cactus
> Installing collected packages: Cactus
> Running setup.py install for Cactus ... error
> ERROR: Command errored out with exit status 1:
> command: /home/shoumik/Thesis2/cactus_env/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-req-build-r718fzym/setup.py'"'"'; **file**='"'"'/tmp/pip-req-build-r718fzym/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(**file**);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, **file**, '"'"'exec'"'"'))' install --record /tmp/pip-record-zaaathwp/install-record.txt --single-version-externally-managed --compile --install-headers /home/shoumik/Thesis2/cactus_env/include/site/python3.6/Cactus
> cwd: /tmp/pip-req-build-r718fzym/
> Complete output (19 lines):
> running install
> ERROR: Directory 'submodules/sonLib' is not installable. Neither 'setup.py' nor 'pyproject.toml' found.
> Traceback (most recent call last):
> File "", line 1, in 
> File "/tmp/pip-req-build-r718fzym/setup.py", line 49, in 
> 'cactus_preprocess = cactus.preprocessor.cactus_preprocessor:main']},)
> File "/home/shoumik/Thesis2/cactus_env/lib/python3.6/site-packages/setuptools/**init**.py", line 144, in setup
> return distutils.core.setup(**attrs)
> File "/usr/lib/python3.6/distutils/core.py", line 148, in setup
> dist.run_commands()
> File "/usr/lib/python3.6/distutils/dist.py", line 955, in run_commands
> self.run_command(cmd)
> File "/usr/lib/python3.6/distutils/dist.py", line 974, in run_command
> cmd_obj.run()
> File "/tmp/pip-req-build-r718fzym/setup.py", line 18, in run
> subprocess.run(["pip", "install", "submodules/sonLib"], check=True)
> File "/usr/lib/python3.6/subprocess.py", line 438, in run
> output=stdout, stderr=stderr)
> subprocess.CalledProcessError: Command '['pip', 'install', 'submodules/sonLib']' returned non-zero exit status 1.
> ----------------------------------------
> ERROR: Command errored out with exit status 1: /home/shoumik/Thesis2/cactus_env/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-req-build-r718fzym/setup.py'"'"'; **file**='"'"'/tmp/pip-req-build-r718fzym/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(**file**);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, **file**, '"'"'exec'"'"'))' install --record /tmp/pip-record-zaaathwp/install-record.txt --single-version-externally-managed --compile --install-headers /home/shoumik/Thesis2/cactus_env/include/site/python3.6/Cactus Check the logs for full command output."
> 
> A log file is being attached here-
> [log.txt](https://github.com/ComparativeGenomicsToolkit/cactus/files/4230981/log.txt)

You did not download the submodules, run 'git submodule update --init' first.

**Comment by ShoumikSaha** [comment]
Yes, installation is done successfully but now it's getting **deadlocked** when I'm running.
**cactus jobStore examples/evolverMammals.txt examples/evolverMammals.hal --root mr --restart**, this command took almost 2 hours and after that it shows a **deadlock exception**!

"Traceback (most recent call last):
  File "/home/shoumik/Thesis2/cactus_env/bin/cactus", line 8, in <module>
    sys.exit(main())
  File "/home/shoumik/Thesis2/cactus_env/lib/python3.6/site-packages/cactus/progressive/cactus_progressive.py", line 474, in main
    runCactusProgressive(options)
  File "/home/shoumik/Thesis2/cactus_env/lib/python3.6/site-packages/cactus/progressive/cactus_progressive.py", line 484, in runCactusProgressive
    halID = toil.restart()
  File "/home/shoumik/Thesis2/cactus_env/lib/python3.6/site-packages/toil/common.py", line 832, in restart
    return self._runMainLoop(rootJobGraph)
  File "/home/shoumik/Thesis2/cactus_env/lib/python3.6/site-packages/toil/common.py", line 1070, in _runMainLoop
    jobCache=self._jobCache).run()
  File "/home/shoumik/Thesis2/cactus_env/lib/python3.6/site-packages/toil/leader.py", line 212, in run
    self.innerLoop()
  File "/home/shoumik/Thesis2/cactus_env/lib/python3.6/site-packages/toil/leader.py", line 557, in innerLoop
    self.checkForDeadlocks()
  File "/home/shoumik/Thesis2/cactus_env/lib/python3.6/site-packages/toil/leader.py", line 589, in checkForDeadlocks
    raise DeadlockException("The system is service deadlocked - all %d running jobs are active services" % totalRunningJobs)
toil.leader.DeadlockException"

The log file is being attached here - 
[log.txt](https://github.com/ComparativeGenomicsToolkit/cactus/files/4233809/log.txt)
