### ISSUE TITLE
toiler.leader.DeadlockException

### ISSUE THREAD

**Issue by ShoumikSaha** [ComparativeGenomicsToolkit/cactus#150]
It's getting deadlocked when I'm running 
**cactus jobStore examples/evolverMammals.txt examples/evolverMammals.hal --root mr --restart**. This took almost 2 hours and after that it shows a **deadlock exception**!

"Traceback (most recent call last):
File "/home/shoumik/Thesis2/cactus_env/bin/cactus", line 8, in 
sys.exit(main())
File "/home/shoumik/Thesis2/cactus_env/lib/python3.6/site-packages/cactus/progressive/cactus_progressive.py", line 474, in main
runCactusProgressive(options)
File "/home/shoumik/Thesis2/cactus_env/lib/python3.6/site-packages/cactus/progressive/cactus_progressive.py", line 484, in runCactusProgressive
halID = toil.restart()
File "/home/shoumik/Thesis2/cactus_env/lib/python3.6/site-packages/toil/common.py", line 832, in restart
return self._runMainLoop(rootJobGraph)
File "/home/shoumik/Thesis2/cactus_env/lib/python3.6/site-packages/toil/common.py", line 1070, in _runMainLoop
jobCache=self._jobCache).run()
File "/home/shoumik/Thesis2/cactus_env/lib/python3.6/site-packages/toil/leader.py", line 212, in run
self.innerLoop()
File "/home/shoumik/Thesis2/cactus_env/lib/python3.6/site-packages/toil/leader.py", line 557, in innerLoop
self.checkForDeadlocks()
File "/home/shoumik/Thesis2/cactus_env/lib/python3.6/site-packages/toil/leader.py", line 589, in checkForDeadlocks
raise DeadlockException("The system is service deadlocked - all %d running jobs are active services" % totalRunningJobs)
toil.leader.DeadlockException"

I tried with different dataset but still facing the same deadlock exception. Thanks in advance.
A log file is being attached here- 
[log.txt](https://github.com/ComparativeGenomicsToolkit/cactus/files/4235779/log.txt)

**Comment by glennhickey** [comment]
It seems to be failing to start the ktserver, but it's hard to say beyond that from the logs, unfortunately.  You may get a more informative error with `--logDebug`.  Also, I'd definitely try without `--restart`.

**Comment by ShoumikSaha** [comment]
With -logDebug and without --restart, I'm still having the same **deadlock exception**!
**Final error message-**
"Traceback (most recent call last):
  File "/home/shoumik/Thesis2/cactus_env/bin/cactus", line 8, in <module>
    sys.exit(main())
  File "/home/shoumik/Thesis2/cactus_env/lib/python3.6/site-packages/cactus/progressive/cactus_progressive.py", line 474, in main
    runCactusProgressive(options)
  File "/home/shoumik/Thesis2/cactus_env/lib/python3.6/site-packages/cactus/progressive/cactus_progressive.py", line 524, in runCactusProgressive
    halID = toil.start(RunCactusPreprocessorThenProgressiveDown(options, project, memory=configWrapper.getDefaultMemory()))
  File "/home/shoumik/Thesis2/cactus_env/lib/python3.6/site-packages/toil/common.py", line 800, in start
    return self._runMainLoop(rootJobGraph)
  File "/home/shoumik/Thesis2/cactus_env/lib/python3.6/site-packages/toil/common.py", line 1070, in _runMainLoop
    jobCache=self._jobCache).run()
  File "/home/shoumik/Thesis2/cactus_env/lib/python3.6/site-packages/toil/leader.py", line 212, in run
    self.innerLoop()
  File "/home/shoumik/Thesis2/cactus_env/lib/python3.6/site-packages/toil/leader.py", line 557, in innerLoop
    self.checkForDeadlocks()
  File "/home/shoumik/Thesis2/cactus_env/lib/python3.6/site-packages/toil/leader.py", line 589, in checkForDeadlocks
    raise DeadlockException("The system is service deadlocked - all %d running jobs are active services" % totalRunningJobs)
toil.leader.DeadlockException"

**But it was showing this message repeatedly for a long time-**
"Acquiring 3565158400 bytes of memory from a pool of 5774743296.
Acquiring 10 fractional cores from a pool of 39 to satisfy a request of 1.000000 cores
Could not acquire enough (disk) to run job (152). Requested: (2147483648), Avaliable: 71405568. Sleeping for 10s."

**At last, before termination it showed this-**
"DEBUG:toil.deferred:Deleting /tmp/toil-3cfb180b-6c93-49da-af21-a52169564aa4-3a82b8c940344fe39ed4b367a7e64d29/deferred/funcd6_ydw2g
Finished job. self.coreFractions ~ 40 and self.memory ~ 8274743296
Acquiring 3565158400 bytes of memory from a pool of 8274743296.
Acquiring 10 fractional cores from a pool of 40 to satisfy a request of 1.000000 cores
DEBUG:toil.common:Obtained node ID 3a82b8c940344fe39ed4b367a7e64d29 from file /var/lib/dbus/machine-id
INFO:toil.worker:Redirecting logging to /tmp/toil-3cfb180b-6c93-49da-af21-a52169564aa4-3a82b8c940344fe39ed4b367a7e64d29/tmpnuqxs8ce/worker_log.txt
DEBUG:toil.deferred:Deleting /tmp/toil-3cfb180b-6c93-49da-af21-a52169564aa4-3a82b8c940344fe39ed4b367a7e64d29/deferred/funcsc9guru2
Finished job. self.coreFractions ~ 40 and self.memory ~ 8274743296
Obtained node ID 3a82b8c940344fe39ed4b367a7e64d29 from file /var/lib/dbus/machine-id
Cleaning up deferred functions system
Running for file /tmp/toil-3cfb180b-6c93-49da-af21-a52169564aa4-3a82b8c940344fe39ed4b367a7e64d29/deferred/funcxwkelmxm
Running orphaned deferred functions
Deleting /tmp/toil-3cfb180b-6c93-49da-af21-a52169564aa4-3a82b8c940344fe39ed4b367a7e64d29/deferred/funcxwkelmxm
... finished shutting down the batch system in 4193.903902769089 seconds."

**Comment by glennhickey** [comment]
Here's the important line from the log:
```
Could not acquire enough (disk) to run job (152). Requested: (2147483648), Avaliable: 71405568. Sleeping for 10s."
```
There's not enough space in the working directory to schedule jobs.  It wants `2GB`, you have `71MB`.  You can use the `--workDir` option to specify a working directory with more space.

**Comment by ShoumikSaha** [comment]
I have specified a work directory with memory size of **67GB** but it's still showing the error - 
"**AssertionError**: The job LastzRepeatMaskJob is requesting **4299161600** bytes of memory, more than the maximum of **3942834176** this batch system was configured with."

**Comment by glennhickey** [comment]
It looks like you need a bit more memory, then.

Is it technically possible to align the evolver test set utilizing fewer resources?  Probably, yes.  But I wouldn't recommend changing the defaults at this point, as the `--configFile` option doesn't seem to work properly (#151).
