### ISSUE TITLE
cactus-hal2maf fails on test suite 

### ISSUE THREAD

**Issue by alpapan** [ComparativeGenomicsToolkit/cactus#1541]
trying the example from the docs but added memory JustInCase TM and binaries local / batch system for debugging 

```
cactus-hal2maf ./js evolverMammals.hal evolverMammals.maf.gz --refGenome simHuman_chr6 --chunkSize 1000000 --dupeMode single  --batchMemory 50G --maxMemory 400G  --binariesMode local --batchSystem single_machine  --cleanWorkDir onSuccess
```

gives an error which shouldn't be there:
```
[2024-11-24T20:56:49+1100] [MainThread] [I] [toil.statsAndLogging] Setting batchCores to 62
[2024-11-24T20:56:49+1100] [MainThread] [I] [toil.statsAndLogging] Enabling realtime logging in Toil
[2024-11-24T20:56:49+1100] [MainThread] [W] [toil.lib.humanize] Deprecated toil method.  Please use "toil.lib.conversions.human2bytes()" instead."
[2024-11-24T20:56:49+1100] [MainThread] [W] [toil.lib.humanize] Deprecated toil method.  Please use "toil.lib.conversions.human2bytes()" instead."
[2024-11-24T20:56:49+1100] [MainThread] [I] [toil.statsAndLogging] Cactus Command: /apps/packages/miniconda/3.1/envs/cactus/bin/cactus-hal2maf ./js evolverMammals.hal evolverMammals.maf.gz --refGenome simHuman_chr6 --chunkSize 1000000 --dupeMode single --batchMemory 50G --maxMemory 400G --binariesMode local --batchSystem single_machine
[2024-11-24T20:56:49+1100] [MainThread] [I] [toil.statsAndLogging] Cactus Commit: 85462e49ed032c86b8deb94e1e0d39581c2fbeed
[2024-11-24T20:56:49+1100] [MainThread] [I] [toil.statsAndLogging] Using default batch count of 1
[2024-11-24T20:56:49+1100] [MainThread] [I] [toil.statsAndLogging] Importing evolverMammals.hal
[2024-11-24T20:56:49+1100] [MainThread] [I] [toil] Running Toil version 7.0.0-d569ea5711eb310ffd5703803f7250ebf7c19576 on host montessori.
[2024-11-24T20:56:49+1100] [MainThread] [I] [toil.realtimeLogger] Starting real-time logging.
[2024-11-24T20:56:49+1100] [MainThread] [I] [toil.leader] Issued job 'hal2maf_workflow' kind-hal2maf_workflow/instance-wmzr8ru0 v1 with job batch system ID: 1 and disk: 2.0 Gi, memory: 2.0 Gi, cores: 1, accelerators: [], preemptible: False
[2024-11-24T20:56:50+1100] [MainThread] [I] [toil-rt] Reading HAL file from job store to /mnt/lazebnik/home/30042108/tmp/toilwf-2e3e4248b1b55097aff45f59fe9bfc20/bb86/5582/tmpa3chsi2y/evolverMammals.hal
[2024-11-24T20:56:50+1100] [MainThread] [I] [toil-rt] Computing range information
[2024-11-24T20:56:50+1100] [MainThread] [I] [toil-rt] 2024-11-24 20:56:50.416445: Running the command: "halStats /mnt/lazebnik/home/30042108/tmp/toilwf-2e3e4248b1b55097aff45f59fe9bfc20/bb86/5582/tmpa3chsi2y/evolverMammals.hal --sequenceStats simHuman_chr6"
[2024-11-24T20:56:50+1100] [MainThread] [I] [toil-rt] 2024-11-24 20:56:50.430587: Successfully ran: "halStats /mnt/lazebnik/home/30042108/tmp/toilwf-2e3e4248b1b55097aff45f59fe9bfc20/bb86/5582/tmpa3chsi2y/evolverMammals.hal --sequenceStats simHuman_chr6" in 0.0089 seconds
[2024-11-24T20:56:50+1100] [MainThread] [I] [toil-rt] 2024-11-24 20:56:50.430915: Running the command: "halStats /mnt/lazebnik/home/30042108/tmp/toilwf-2e3e4248b1b55097aff45f59fe9bfc20/bb86/5582/tmpa3chsi2y/evolverMammals.hal --tree"
[2024-11-24T20:56:50+1100] [MainThread] [I] [toil-rt] 2024-11-24 20:56:50.440286: Successfully ran: "halStats /mnt/lazebnik/home/30042108/tmp/toilwf-2e3e4248b1b55097aff45f59fe9bfc20/bb86/5582/tmpa3chsi2y/evolverMammals.hal --tree" in 0.0037 seconds
[2024-11-24T20:56:50+1100] [MainThread] [I] [toil.leader] 0 jobs are running, 0 jobs are issued and waiting to run
[2024-11-24T20:56:50+1100] [MainThread] [I] [toil.leader] Issued job 'hal2maf_all' kind-hal2maf_all/instance-hbxv24n9 v1 with job batch system ID: 2 and disk: 2.0 Gi, memory: 2.0 Gi, cores: 1, accelerators: [], preemptible: False
[2024-11-24T20:56:50+1100] [Thread-4] [W] [toil.statsAndLogging] Got message from job at time 11-24-2024 20:56:50: Job used more disk than requested. For CWL, consider increasing the outdirMin requirement, otherwise, consider increasing the disk requirement. Job 'hal2maf_ranges' kind-hal2maf_workflow/instance-wmzr8ru0 v3 used 100.08% disk (4.4 MiB [4657152B] used, 4.4 MiB [4653603B] requested).
[2024-11-24T20:56:51+1100] [MainThread] [I] [toil-rt] Setting batchSize to 1
[2024-11-24T20:56:51+1100] [MainThread] [I] [toil.leader] Issued job 'hal2maf_batch' kind-hal2maf_batch/instance-1zha8fem v1 with job batch system ID: 3 and disk: 11.1 Mi, memory: 46.6 Gi, cores: 62, accelerators: [], preemptible: False
[2024-11-24T20:56:51+1100] [MainThread] [I] [toil-rt] Reading HAL file from job store to /mnt/lazebnik/home/30042108/tmp/toilwf-2e3e4248b1b55097aff45f59fe9bfc20/c959/job/tmpv4dktg42/evolverMammals.hal
[2024-11-24T20:56:51+1100] [MainThread] [I] [toil-rt] First of 1 commands in parallel batch: set -eo pipefail && (time -p  hal2maf evolverMammals.hal stdout --refGenome simHuman_chr6 --refSequence simHuman.chr6 --start 0 --length 601863 --maxBlockLen 10000) 2> 0.h2m.time | grep -v "^s   _MINIGRAPH_" | bgzip > evolverMammals_chunk_0.maf.gz
[2024-11-24T20:56:51+1100] [MainThread] [I] [toil-rt] 2024-11-24 20:56:51.647060: Running the command: "bash -c set -eo pipefail && cat /mnt/lazebnik/home/30042108/tmp/toilwf-2e3e4248b1b55097aff45f59fe9bfc20/c959/job/tmpv4dktg42/hal2maf_cmds.txt | parallel -j 62 '{}'"
[2024-11-24T20:56:51+1100] [MainThread] [I] [toil-rt] 2024-11-24 20:56:51.670732: Successfully ran: "bash -c set -eo pipefail && cat /mnt/lazebnik/home/30042108/tmp/toilwf-2e3e4248b1b55097aff45f59fe9bfc20/c959/job/tmpv4dktg42/hal2maf_cmds.txt | parallel -j 62 '{}'" in 0.0183 seconds
[2024-11-24T20:56:51+1100] [Thread-1] [E] [toil.batchSystems.singleMachine] Got exit code 1 (indicating failure) from job _toil_worker hal2maf_batch file:/mnt/lazebnik/home/30042108/software/cactus/js kind-hal2maf_batch/instance-1zha8fem.
[2024-11-24T20:56:51+1100] [MainThread] [W] [toil.leader] Job failed with exit value 1: 'hal2maf_batch' kind-hal2maf_batch/instance-1zha8fem v1
Exit reason: None
[2024-11-24T20:56:51+1100] [MainThread] [W] [toil.leader] The job seems to have left a log file, indicating failure: 'hal2maf_batch' kind-hal2maf_batch/instance-1zha8fem v2
[2024-11-24T20:56:51+1100] [MainThread] [W] [toil.leader] Log from job "kind-hal2maf_batch/instance-1zha8fem" follows:
=========>
        [2024-11-24T20:56:51+1100] [MainThread] [I] [toil.worker] ---TOIL WORKER OUTPUT LOG---
        [2024-11-24T20:56:51+1100] [MainThread] [I] [toil] Running Toil version 7.0.0-d569ea5711eb310ffd5703803f7250ebf7c19576 on host montessori.
        [2024-11-24T20:56:51+1100] [MainThread] [I] [toil.worker] Working on job 'hal2maf_batch' kind-hal2maf_batch/instance-1zha8fem v1
        [2024-11-24T20:56:51+1100] [MainThread] [I] [toil.worker] Loaded body Job('hal2maf_batch' kind-hal2maf_batch/instance-1zha8fem v1) from description 'hal2maf_batch' kind-hal2maf_batch/instance-1zha8fem v1
        [2024-11-24T20:56:51+1100] [MainThread] [I] [toil-rt] Reading HAL file from job store to /mnt/lazebnik/home/30042108/tmp/toilwf-2e3e4248b1b55097aff45f59fe9bfc20/c959/job/tmpv4dktg42/evolverMammals.hal
        [2024-11-24T20:56:51+1100] [MainThread] [I] [toil-rt] First of 1 commands in parallel batch: set -eo pipefail && (time -p  hal2maf evolverMammals.hal stdout --refGenome simHuman_chr6 --refSequence simHuman.chr6 --start 0 --length 601863 --maxBlockLen 10000) 2> 0.h2m.time | grep -v "^s   _MINIGRAPH_" | bgzip > evolverMammals_chunk_0.maf.gz
        [2024-11-24T20:56:51+1100] [MainThread] [I] [toil-rt] 2024-11-24 20:56:51.647060: Running the command: "bash -c set -eo pipefail && cat /mnt/lazebnik/home/30042108/tmp/toilwf-2e3e4248b1b55097aff45f59fe9bfc20/c959/job/tmpv4dktg42/hal2maf_cmds.txt | parallel -j 62 '{}'"
        [2024-11-24T20:56:51+1100] [MainThread] [I] [toil-rt] 2024-11-24 20:56:51.670732: Successfully ran: "bash -c set -eo pipefail && cat /mnt/lazebnik/home/30042108/tmp/toilwf-2e3e4248b1b55097aff45f59fe9bfc20/c959/job/tmpv4dktg42/hal2maf_cmds.txt | parallel -j 62 '{}'" in 0.0183 seconds
        [2024-11-24T20:56:51+1100] [MainThread] [W] [toil.fileStores.abstractFileStore] Failed job accessed files:
        [2024-11-24T20:56:51+1100] [MainThread] [W] [toil.fileStores.abstractFileStore] Downloaded file 'files/no-job/file-892314ef425b4e45a3abe908b2e0ce09/evolverMammals.hal' to path '/mnt/lazebnik/home/30042108/tmp/toilwf-2e3e4248b1b55097aff45f59fe9bfc20/c959/job/tmpv4dktg42/evolverMammals.hal'
        [2024-11-24T20:56:51+1100] [MainThread] [C] [toil.worker] Worker crashed with traceback:
        Traceback (most recent call last):
          File "/apps/packages/miniconda/3.1/envs/cactus/lib/python3.8/site-packages/toil/worker.py", line 438, in workerScript
            job._runner(jobGraph=None, jobStore=job_store, fileStore=fileStore, defer=defer)
          File "/apps/packages/miniconda/3.1/envs/cactus/lib/python3.8/site-packages/toil/job.py", line 2984, in _runner
            returnValues = self._run(jobGraph=None, fileStore=fileStore)
          File "/apps/packages/miniconda/3.1/envs/cactus/lib/python3.8/site-packages/toil/job.py", line 2895, in _run
            return self.run(fileStore)
          File "/apps/packages/miniconda/3.1/envs/cactus/lib/python3.8/site-packages/toil/job.py", line 3158, in run
            rValue = userFunction(*((self,) + tuple(self._args)), **self._kwargs)
          File "/apps/packages/miniconda/3.1/envs/cactus/lib/python3.8/site-packages/cactus/maf/cactus_hal2maf.py", line 603, in hal2maf_batch
            chunk_msg += "{}{} {} ".format('' if cmd == 'hal2maf' else 'and ', tag_cmd, read_time_mem(os.path.join(work_dir, '{}.{}.time'.format(chunk_num, tag))))
          File "/apps/packages/miniconda/3.1/envs/cactus/lib/python3.8/site-packages/cactus/maf/cactus_hal2maf.py", line 485, in read_time_mem
            with open(timefile_path, 'r') as timefile:
        FileNotFoundError: [Errno 2] No such file or directory: '/mnt/lazebnik/home/30042108/tmp/toilwf-2e3e4248b1b55097aff45f59fe9bfc20/c959/job/tmpv4dktg42/0.h2m.time'

        [2024-11-24T20:56:51+1100] [MainThread] [E] [toil.worker] Exiting the worker because of a failed job on host montessori
<=========
[2024-11-24T20:56:51+1100] [MainThread] [W] [toil.job] Due to failure we are reducing the remaining try count of job 'hal2maf_batch' kind-hal2maf_batch/instance-1zha8fem v2 with ID kind-hal2maf_batch/instance-1zha8fem to 1
[2024-11-24T20:56:51+1100] [MainThread] [W] [toil.job] We have increased the disk of the failed job 'hal2maf_batch' kind-hal2maf_batch/instance-1zha8fem v2 to the default of 2147483648 bytes
[2024-11-24T20:56:51+1100] [MainThread] [I] [toil.leader] Issued job 'hal2maf_batch' kind-hal2maf_batch/instance-1zha8fem v3 with job batch system ID: 4 and disk: 2.0 Gi, memory: 46.6 Gi, cores: 62, accelerators: [], preemptible: False
[2024-11-24T20:56:52+1100] [MainThread] [I] [toil-rt] Reading HAL file from job store to /mnt/lazebnik/home/30042108/tmp/toilwf-2e3e4248b1b55097aff45f59fe9bfc20/ae7c/job/tmpiqbhtte_/evolverMammals.hal
[2024-11-24T20:56:52+1100] [MainThread] [I] [toil-rt] First of 1 commands in parallel batch: set -eo pipefail && (time -p  hal2maf evolverMammals.hal stdout --refGenome simHuman_chr6 --refSequence simHuman.chr6 --start 0 --length 601863 --maxBlockLen 10000) 2> 0.h2m.time | grep -v "^s   _MINIGRAPH_" | bgzip > evolverMammals_chunk_0.maf.gz
[2024-11-24T20:56:52+1100] [MainThread] [I] [toil-rt] 2024-11-24 20:56:52.284853: Running the command: "bash -c set -eo pipefail && cat /mnt/lazebnik/home/30042108/tmp/toilwf-2e3e4248b1b55097aff45f59fe9bfc20/ae7c/job/tmpiqbhtte_/hal2maf_cmds.txt | parallel -j 62 '{}'"
[2024-11-24T20:56:52+1100] [MainThread] [I] [toil-rt] 2024-11-24 20:56:52.307277: Successfully ran: "bash -c set -eo pipefail && cat /mnt/lazebnik/home/30042108/tmp/toilwf-2e3e4248b1b55097aff45f59fe9bfc20/ae7c/job/tmpiqbhtte_/hal2maf_cmds.txt | parallel -j 62 '{}'" in 0.0161 seconds
[2024-11-24T20:56:52+1100] [Thread-1] [E] [toil.batchSystems.singleMachine] Got exit code 1 (indicating failure) from job _toil_worker hal2maf_batch file:/mnt/lazebnik/home/30042108/software/cactus/js kind-hal2maf_batch/instance-1zha8fem.
[2024-11-24T20:56:52+1100] [MainThread] [W] [toil.leader] Job failed with exit value 1: 'hal2maf_batch' kind-hal2maf_batch/instance-1zha8fem v3
Exit reason: None
[2024-11-24T20:56:52+1100] [MainThread] [W] [toil.leader] The job seems to have left a log file, indicating failure: 'hal2maf_batch' kind-hal2maf_batch/instance-1zha8fem v5
[2024-11-24T20:56:52+1100] [MainThread] [W] [toil.leader] Log from job "kind-hal2maf_batch/instance-1zha8fem" follows:
=========>
        [2024-11-24T20:56:52+1100] [MainThread] [I] [toil.worker] ---TOIL WORKER OUTPUT LOG---
        [2024-11-24T20:56:52+1100] [MainThread] [I] [toil] Running Toil version 7.0.0-d569ea5711eb310ffd5703803f7250ebf7c19576 on host montessori.
        [2024-11-24T20:56:52+1100] [MainThread] [I] [toil.worker] Working on job 'hal2maf_batch' kind-hal2maf_batch/instance-1zha8fem v4
        [2024-11-24T20:56:52+1100] [MainThread] [I] [toil.worker] Loaded body Job('hal2maf_batch' kind-hal2maf_batch/instance-1zha8fem v4) from description 'hal2maf_batch' kind-hal2maf_batch/instance-1zha8fem v4
        [2024-11-24T20:56:52+1100] [MainThread] [I] [toil-rt] Reading HAL file from job store to /mnt/lazebnik/home/30042108/tmp/toilwf-2e3e4248b1b55097aff45f59fe9bfc20/ae7c/job/tmpiqbhtte_/evolverMammals.hal
        [2024-11-24T20:56:52+1100] [MainThread] [I] [toil-rt] First of 1 commands in parallel batch: set -eo pipefail && (time -p  hal2maf evolverMammals.hal stdout --refGenome simHuman_chr6 --refSequence simHuman.chr6 --start 0 --length 601863 --maxBlockLen 10000) 2> 0.h2m.time | grep -v "^s   _MINIGRAPH_" | bgzip > evolverMammals_chunk_0.maf.gz
        [2024-11-24T20:56:52+1100] [MainThread] [I] [toil-rt] 2024-11-24 20:56:52.284853: Running the command: "bash -c set -eo pipefail && cat /mnt/lazebnik/home/30042108/tmp/toilwf-2e3e4248b1b55097aff45f59fe9bfc20/ae7c/job/tmpiqbhtte_/hal2maf_cmds.txt | parallel -j 62 '{}'"
        [2024-11-24T20:56:52+1100] [MainThread] [I] [toil-rt] 2024-11-24 20:56:52.307277: Successfully ran: "bash -c set -eo pipefail && cat /mnt/lazebnik/home/30042108/tmp/toilwf-2e3e4248b1b55097aff45f59fe9bfc20/ae7c/job/tmpiqbhtte_/hal2maf_cmds.txt | parallel -j 62 '{}'" in 0.0161 seconds
        [2024-11-24T20:56:52+1100] [MainThread] [W] [toil.fileStores.abstractFileStore] Failed job accessed files:
        [2024-11-24T20:56:52+1100] [MainThread] [W] [toil.fileStores.abstractFileStore] Downloaded file 'files/no-job/file-892314ef425b4e45a3abe908b2e0ce09/evolverMammals.hal' to path '/mnt/lazebnik/home/30042108/tmp/toilwf-2e3e4248b1b55097aff45f59fe9bfc20/ae7c/job/tmpiqbhtte_/evolverMammals.hal'
        [2024-11-24T20:56:52+1100] [MainThread] [C] [toil.worker] Worker crashed with traceback:
        Traceback (most recent call last):
          File "/apps/packages/miniconda/3.1/envs/cactus/lib/python3.8/site-packages/toil/worker.py", line 438, in workerScript
            job._runner(jobGraph=None, jobStore=job_store, fileStore=fileStore, defer=defer)
          File "/apps/packages/miniconda/3.1/envs/cactus/lib/python3.8/site-packages/toil/job.py", line 2984, in _runner
            returnValues = self._run(jobGraph=None, fileStore=fileStore)
          File "/apps/packages/miniconda/3.1/envs/cactus/lib/python3.8/site-packages/toil/job.py", line 2895, in _run
            return self.run(fileStore)
          File "/apps/packages/miniconda/3.1/envs/cactus/lib/python3.8/site-packages/toil/job.py", line 3158, in run
            rValue = userFunction(*((self,) + tuple(self._args)), **self._kwargs)
          File "/apps/packages/miniconda/3.1/envs/cactus/lib/python3.8/site-packages/cactus/maf/cactus_hal2maf.py", line 603, in hal2maf_batch
            chunk_msg += "{}{} {} ".format('' if cmd == 'hal2maf' else 'and ', tag_cmd, read_time_mem(os.path.join(work_dir, '{}.{}.time'.format(chunk_num, tag))))
          File "/apps/packages/miniconda/3.1/envs/cactus/lib/python3.8/site-packages/cactus/maf/cactus_hal2maf.py", line 485, in read_time_mem
            with open(timefile_path, 'r') as timefile:
        FileNotFoundError: [Errno 2] No such file or directory: '/mnt/lazebnik/home/30042108/tmp/toilwf-2e3e4248b1b55097aff45f59fe9bfc20/ae7c/job/tmpiqbhtte_/0.h2m.time'

        [2024-11-24T20:56:52+1100] [MainThread] [E] [toil.worker] Exiting the worker because of a failed job on host montessori
<=========
[2024-11-24T20:56:52+1100] [MainThread] [W] [toil.job] Due to failure we are reducing the remaining try count of job 'hal2maf_batch' kind-hal2maf_batch/instance-1zha8fem v5 with ID kind-hal2maf_batch/instance-1zha8fem to 0
[2024-11-24T20:56:52+1100] [MainThread] [W] [toil.leader] Job 'hal2maf_batch' kind-hal2maf_batch/instance-1zha8fem v6 is completely failed
[2024-11-24T20:56:59+1100] [MainThread] [I] [toil.leader] Finished toil run with 3 failed jobs.
[2024-11-24T20:56:59+1100] [MainThread] [I] [toil.leader] Failed jobs at end of the run: 'hal2maf_ranges' kind-hal2maf_workflow/instance-wmzr8ru0 v4 'hal2maf_batch' kind-hal2maf_batch/instance-1zha8fem v6 'hal2maf_all' kind-hal2maf_all/instance-hbxv24n9 v3

Workflow Progress 100%| 4/4 (2 failures) [00:09<00:00, 0.46 jobs/s]
[2024-11-24T20:56:59+1100] [MainThread] [I] [toil.realtimeLogger] Stopping real-time logging server.
[2024-11-24T20:57:00+1100] [MainThread] [I] [toil.realtimeLogger] Joining real-time logging server thread.
Traceback (most recent call last):
  File "/apps/packages/miniconda/3.1/envs/cactus/bin/cactus-hal2maf", line 8, in <module>
    sys.exit(main())
  File "/apps/packages/miniconda/3.1/envs/cactus/lib/python3.8/site-packages/cactus/maf/cactus_hal2maf.py", line 228, in main
    maf_id = toil.start(Job.wrapJobFn(hal2maf_workflow, hal_id, bed_id, options, config))
  File "/apps/packages/miniconda/3.1/envs/cactus/lib/python3.8/site-packages/toil/common.py", line 930, in start
    return self._runMainLoop(rootJobDescription)
  File "/apps/packages/miniconda/3.1/envs/cactus/lib/python3.8/site-packages/toil/common.py", line 1412, in _runMainLoop
    return Leader(config=self.config,
  File "/apps/packages/miniconda/3.1/envs/cactus/lib/python3.8/site-packages/toil/leader.py", line 304, in run
    raise FailedJobsException(self.jobStore, failed_jobs, exit_code=self.recommended_fail_exit_code)
toil.exceptions.FailedJobsException: The job store '/mnt/lazebnik/home/30042108/software/cactus/js' contains 3 failed jobs: 'hal2maf_ranges' kind-hal2maf_workflow/instance-wmzr8ru0 v4, 'hal2maf_batch' kind-hal2maf_batch/instance-1zha8fem v6, 'hal2maf_all' kind-hal2maf_all/instance-hbxv24n9 v3
Log from job "'hal2maf_batch' kind-hal2maf_batch/instance-1zha8fem v6" follows:
=========>
        [2024-11-24T20:56:52+1100] [MainThread] [I] [toil.worker] ---TOIL WORKER OUTPUT LOG---
        [2024-11-24T20:56:52+1100] [MainThread] [I] [toil] Running Toil version 7.0.0-d569ea5711eb310ffd5703803f7250ebf7c19576 on host montessori.
        [2024-11-24T20:56:52+1100] [MainThread] [I] [toil.worker] Working on job 'hal2maf_batch' kind-hal2maf_batch/instance-1zha8fem v4
        [2024-11-24T20:56:52+1100] [MainThread] [I] [toil.worker] Loaded body Job('hal2maf_batch' kind-hal2maf_batch/instance-1zha8fem v4) from description 'hal2maf_batch' kind-hal2maf_batch/instance-1zha8fem v4
        [2024-11-24T20:56:52+1100] [MainThread] [I] [toil-rt] Reading HAL file from job store to /mnt/lazebnik/home/30042108/tmp/toilwf-2e3e4248b1b55097aff45f59fe9bfc20/ae7c/job/tmpiqbhtte_/evolverMammals.hal
        [2024-11-24T20:56:52+1100] [MainThread] [I] [toil-rt] First of 1 commands in parallel batch: set -eo pipefail && (time -p  hal2maf evolverMammals.hal stdout --refGenome simHuman_chr6 --refSequence simHuman.chr6 --start 0 --length 601863 --maxBlockLen 10000) 2> 0.h2m.time | grep -v "^s   _MINIGRAPH_" | bgzip > evolverMammals_chunk_0.maf.gz
        [2024-11-24T20:56:52+1100] [MainThread] [I] [toil-rt] 2024-11-24 20:56:52.284853: Running the command: "bash -c set -eo pipefail && cat /mnt/lazebnik/home/30042108/tmp/toilwf-2e3e4248b1b55097aff45f59fe9bfc20/ae7c/job/tmpiqbhtte_/hal2maf_cmds.txt | parallel -j 62 '{}'"
        [2024-11-24T20:56:52+1100] [MainThread] [I] [toil-rt] 2024-11-24 20:56:52.307277: Successfully ran: "bash -c set -eo pipefail && cat /mnt/lazebnik/home/30042108/tmp/toilwf-2e3e4248b1b55097aff45f59fe9bfc20/ae7c/job/tmpiqbhtte_/hal2maf_cmds.txt | parallel -j 62 '{}'" in 0.0161 seconds
        [2024-11-24T20:56:52+1100] [MainThread] [W] [toil.fileStores.abstractFileStore] Failed job accessed files:
        [2024-11-24T20:56:52+1100] [MainThread] [W] [toil.fileStores.abstractFileStore] Downloaded file 'files/no-job/file-892314ef425b4e45a3abe908b2e0ce09/evolverMammals.hal' to path '/mnt/lazebnik/home/30042108/tmp/toilwf-2e3e4248b1b55097aff45f59fe9bfc20/ae7c/job/tmpiqbhtte_/evolverMammals.hal'
        [2024-11-24T20:56:52+1100] [MainThread] [C] [toil.worker] Worker crashed with traceback:
        Traceback (most recent call last):
          File "/apps/packages/miniconda/3.1/envs/cactus/lib/python3.8/site-packages/toil/worker.py", line 438, in workerScript
            job._runner(jobGraph=None, jobStore=job_store, fileStore=fileStore, defer=defer)
          File "/apps/packages/miniconda/3.1/envs/cactus/lib/python3.8/site-packages/toil/job.py", line 2984, in _runner
            returnValues = self._run(jobGraph=None, fileStore=fileStore)
          File "/apps/packages/miniconda/3.1/envs/cactus/lib/python3.8/site-packages/toil/job.py", line 2895, in _run
            return self.run(fileStore)
          File "/apps/packages/miniconda/3.1/envs/cactus/lib/python3.8/site-packages/toil/job.py", line 3158, in run
            rValue = userFunction(*((self,) + tuple(self._args)), **self._kwargs)
          File "/apps/packages/miniconda/3.1/envs/cactus/lib/python3.8/site-packages/cactus/maf/cactus_hal2maf.py", line 603, in hal2maf_batch
            chunk_msg += "{}{} {} ".format('' if cmd == 'hal2maf' else 'and ', tag_cmd, read_time_mem(os.path.join(work_dir, '{}.{}.time'.format(chunk_num, tag))))
          File "/apps/packages/miniconda/3.1/envs/cactus/lib/python3.8/site-packages/cactus/maf/cactus_hal2maf.py", line 485, in read_time_mem
            with open(timefile_path, 'r') as timefile:
        FileNotFoundError: [Errno 2] No such file or directory: '/mnt/lazebnik/home/30042108/tmp/toilwf-2e3e4248b1b55097aff45f59fe9bfc20/ae7c/job/tmpiqbhtte_/0.h2m.time'

        [2024-11-24T20:56:52+1100] [MainThread] [E] [toil.worker] Exiting the worker because of a failed job on host montessori
<=========


when i check locally:

```
cd /mnt/lazebnik/home/30042108/tmp/toilwf-5d818653347a506bb818ab13b4959782/6f32/job/tmp6ypr5r3i/
ll
total 4.5M
-rw-r--r-- 3 30042108 alexielab 4.5M Nov 22 21:35 evolverMammals.hal
-rw-r--r-- 1 30042108 alexielab   82 Nov 24 20:58 genome.list
-rw-r--r-- 1 30042108 alexielab  246 Nov 24 20:58 hal2maf_cmds.txt
head -1 hal2maf_cmds.txt
set -eo pipefail && (time -p  hal2maf evolverMammals.hal stdout --refGenome simHuman_chr6 --refSequence simHuman.chr6 --start 0 --length 601863 --maxBlockLen 10000) 2> 0.h2m.time | grep -v "^s        _MINIGRAPH_" | bgzip > evolverMammals_chunk_0.maf.gz
```

then run it i get the file toil finds missing and shows it completes ok 
```
set -eo pipefail && (time -p  hal2maf evolverMammals.hal stdout --refGenome simHuman_chr6 --refSequence simHuman.chr6 --start 0 --length 601863 --maxBlockLen 10000) 2> 0.h2m.time | grep -v "^s_MINIGRAPH_" | bgzip > evolverMammals_chunk_0.maf.gz
ll
total 6.9M
-rw-r--r-- 1 30042108 alexielab   29 Nov 24 21:00 0.h2m.time
-rw-r--r-- 1 30042108 alexielab 2.4M Nov 24 21:00 evolverMammals_chunk_0.maf.gz
-rw-r--r-- 3 30042108 alexielab 4.5M Nov 22 21:35 evolverMammals.hal
-rw-r--r-- 1 30042108 alexielab   82 Nov 24 20:58 genome.list
-rw-r--r-- 1 30042108 alexielab  246 Nov 24 20:58 hal2maf_cmds.txt

cat 0.h2m.time
real 3.29
user 3.13
sys 0.03

```

**Comment by alpapan** [comment]
ignore me, this was solved by [realising the cactus-bin is a separate package](https://github.com/ComparativeGenomicsToolkit/cactus/issues/1233). it must have been a version difference in parallel
