### ISSUE TITLE
Unable to run test data or any other data due to unrecognize arguments or files

### ISSUE THREAD

**Issue by MauriAndresMU1313** [ComparativeGenomicsToolkit/cactus#1548]
Good morning, I have trying to run Cactus for a while without any success, I hate to do this question but my current testing process is not working at all. 
So, I'm using `Singularity` to run one of the images that I downloaded from the current release of cactus: `cactus-v2.9.3.simg`.  I check if the image worked using the following command:
```
singularity exec /home/mmora30/singularity/cactus-v2.9.3.simg cactus -h
```
With the expected output: ```usage: cactus [-h]...```. Then, I follow the examples shown in multiple pages:
```
singularity exec /home/mmora30/singularity/cactus-v2.9.3.simg cactus ./js ./examples/evolverMammals.txt ./evolverMammals.hal
```
First, the option `./js` never made sense to me, because is not present in the directory that I clone from the main repository, so I did not use it at the beginning but then I realized that I needed to (still not make sense to me). 

The previous line returns me the following error:
```
[2024-11-27T17:16:11+0000] [MainThread] [I] [toil.statsAndLogging] Enabling realtime logging in Toil
[2024-11-27T17:16:11+0000] [MainThread] [W] [toil.lib.humanize] Deprecated toil method.  Please use "toil.lib.conversions.human2bytes()" instead."
[2024-11-27T17:16:11+0000] [MainThread] [W] [toil.lib.humanize] Deprecated toil method.  Please use "toil.lib.conversions.human2bytes()" instead."
[2024-11-27T17:16:11+0000] [MainThread] [I] [toil.statsAndLogging] Cactus Command: /home/cactus/cactus_env/bin/cactus ./js ./examples/evolverMammals.txt ./evolverMammals.hal --logError --logInfo
[2024-11-27T17:16:11+0000] [MainThread] [I] [toil.statsAndLogging] Cactus Commit: 20488aeb80c3ef985034e538b36ad97ed632cad2
Traceback (most recent call last):
  File "/home/cactus/cactus_env/lib/python3.10/site-packages/toil/jobStores/fileJobStore.py", line 113, in initialize
    os.mkdir(self.jobStoreDir)
FileExistsError: [Errno 17] File exists: '/home/mmora30/js'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/cactus/cactus_env/bin/cactus", line 8, in <module>
    sys.exit(main())
  File "/home/cactus/cactus_env/lib/python3.10/site-packages/cactus/progressive/cactus_progressive.py", line 405, in main
    with Toil(options) as toil:
  File "/home/cactus/cactus_env/lib/python3.10/site-packages/toil/common.py", line 827, in __enter__
    jobStore.initialize(config)
  File "/home/cactus/cactus_env/lib/python3.10/site-packages/toil/jobStores/fileJobStore.py", line 116, in initialize
    raise JobStoreExistsException(self.jobStoreDir, "file")
toil.jobStores.abstractJobStore.JobStoreExistsException: The job store 'file:/home/mmora30/js' already exists. Use --restart to resume the workflow, or remove the job store with 'toil clean' to start the workflow from scratch.
```
So, I used the `--restart` flag. However, then I got the following error:
```
[2024-11-27T17:17:16+0000] [MainThread] [I] [toil.statsAndLogging] Enabling realtime logging in Toil
[2024-11-27T17:17:16+0000] [MainThread] [W] [toil.lib.humanize] Deprecated toil method.  Please use "toil.lib.conversions.human2bytes()" instead."
[2024-11-27T17:17:16+0000] [MainThread] [W] [toil.lib.humanize] Deprecated toil method.  Please use "toil.lib.conversions.human2bytes()" instead."
[2024-11-27T17:17:16+0000] [MainThread] [I] [toil.statsAndLogging] Cactus Command: /home/cactus/cactus_env/bin/cactus ./js ./examples/evolverMammals.txt ./evolverMammals.hal --restart --logError --logInfo
[2024-11-27T17:17:16+0000] [MainThread] [I] [toil.statsAndLogging] Cactus Commit: 20488aeb80c3ef985034e538b36ad97ed632cad2
[2024-11-27T17:17:17+0000] [MainThread] [W] [toil.common] Requested restart but the workflow has already been completed; allowing exports to rerun.
Traceback (most recent call last):
  File "/home/cactus/cactus_env/lib/python3.10/site-packages/toil/jobStores/fileJobStore.py", line 710, in read_shared_file_stream
    with open(self._get_shared_file_path(shared_file_name), 'rb' if encoding == None else 'rt', encoding=encoding, errors=errors) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/home/mmora30/js/files/shared/rootJobStoreID'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/cactus/cactus_env/lib/python3.10/site-packages/toil/jobStores/abstractJobStore.py", line 283, in load_root_job
    with self.read_shared_file_stream(self.rootJobStoreIDFileName) as f:
  File "/usr/lib/python3.10/contextlib.py", line 135, in __enter__
    return next(self.gen)
  File "/home/cactus/cactus_env/lib/python3.10/site-packages/toil/jobStores/fileJobStore.py", line 715, in read_shared_file_stream
    raise NoSuchFileException(shared_file_name)
toil.jobStores.abstractJobStore.NoSuchFileException: File 'rootJobStoreID' does not exist.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/cactus/cactus_env/lib/python3.10/site-packages/toil/common.py", line 953, in restart
    self._jobStore.load_root_job()
  File "/home/cactus/cactus_env/lib/python3.10/site-packages/toil/jobStores/abstractJobStore.py", line 286, in load_root_job
    raise JobException('No job has been set as the root in this job store')
toil.job.JobException: No job has been set as the root in this job store

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/cactus/cactus_env/lib/python3.10/site-packages/toil/jobStores/fileJobStore.py", line 710, in read_shared_file_stream
    with open(self._get_shared_file_path(shared_file_name), 'rb' if encoding == None else 'rt', encoding=encoding, errors=errors) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/home/mmora30/js/files/shared/rootJobReturnValue'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/cactus/cactus_env/bin/cactus", line 8, in <module>
    sys.exit(main())
  File "/home/cactus/cactus_env/lib/python3.10/site-packages/cactus/progressive/cactus_progressive.py", line 409, in main
    hal_id = toil.restart()
  File "/home/cactus/cactus_env/lib/python3.10/site-packages/toil/common.py", line 957, in restart
    return self._jobStore.get_root_job_return_value()
  File "/home/cactus/cactus_env/lib/python3.10/site-packages/toil/jobStores/abstractJobStore.py", line 321, in get_root_job_return_value
    with self.read_shared_file_stream('rootJobReturnValue') as fH:
  File "/usr/lib/python3.10/contextlib.py", line 135, in __enter__
    return next(self.gen)
  File "/home/cactus/cactus_env/lib/python3.10/site-packages/toil/jobStores/fileJobStore.py", line 715, in read_shared_file_stream
    raise NoSuchFileException(shared_file_name)
toil.jobStores.abstractJobStore.NoSuchFileException: File 'rootJobReturnValue' does not exist.
```
Obviously, makes sense that the directory `js` is not found, because does not exist. So I checked on the internet what this file is and, unfortunately, I still do not find out what it is. Any comment to explain that is more than welcome. 

In another post that I found in the ```GitHub issues``` section, some people share ```log.error``` files, where are those files? I could not find it, even if I used the following flags:
```
singularity exec /home/mmora30/singularity/cactus-v2.9.3.simg cactus ./js ./examples/evolverMammals.txt ./evolverMammals.hal --restart --logError --logInfo
```
This is not the main topic of my post, my point is that I tried different combinations, and all of them ended with files or directories that had the error: **NOT EXIST** or **NOT FOUND**. I even followed this tutorial on youtube: [Cactus-seminar](https://www.youtube.com/watch?app=desktop&v=TqlzNswt8JU&ab_channel=BiodiversityGenomicsAcademy), using the same examples without any success.

The issue is basic, I know. But any comment or help will be great! If you need that I to add more information, please let me know.

**Comment by glennhickey** [comment]
The first argument is the `<jobStorePath>` as described in the [interface documentation](https://github.com/ComparativeGenomicsToolkit/cactus/blob/master/doc/progressive.md#interface).  It is the name of a directory for temporary files that must not exist before running cactus.  If it exists because it was created by a previous run of cactus that you want to resume, then you can try to resume with `--restart`.  Otherwise you will get an error.  If it exists and is a file and not a directory, you will get a harder-to-interpret error.  Hope this helps.

**Comment by MauriAndresMU1313** [comment]
Thank you for the clarification, however, still not make thank the error that I got. I ran the following command:
```
singularity exec /home/mmora30/singularity/cactus-v2.9.3.simg cactus ./js ./examples/evolverMammals.txt ./evolverMammals.hal --logError --logInfo
```
which got the following error:
```
toil.jobStores.abstractJobStore.JobStoreExistsException: The job store 'file:/home/mmora30/js' already exists. Use --restart to resume the workflow, or remove the job store with 'toil clean' to start the workflow from scratch.
```
so I installed toil in a mamba environment, to then run the command `toil clean jobStore`:
```
[2024-11-27T18:13:11+0000] [MainThread] [W] [toil.utils.toilClean] Job store does not appear to exist. Deleting anyway.
[2024-11-27T18:13:11+0000] [MainThread] [I] [toil.utils.toilClean] Successfully deleted the job store: jobStore
```
then I ran the same previous line, with the same error, and the loop start again:
```
toil.jobStores.abstractJobStore.JobStoreExistsException: The job store 'file:/home/mmora30/js' already exists. Use --restart to resume the workflow, or remove the job store with 'toil clean' to start the workflow from scratch.
```
Any comment? please do not close immediately, that will be great

**Comment by MauriAndresMU1313** [comment]
Even if I ran the following line successfully:
```
toil clean /home/mmora30/js
[2024-11-27T18:27:01+0000] [MainThread] [I] [toil.utils.toilClean] Successfully deleted the job store: /home/mmora30/js
```
And, run the following command:
```
singularity exec /home/mmora30/singularity/cactus-v2.9.3.simg cactus ./js /home/mmora30/localData/workspace_mm/temporal_tasks/cactus/cactus-1/cactus/examples/evolverMammals.txt ./evolverMammals.hal --logError --logInfo
```
I got the error:
```
[2024-11-27T18:26:38+0000] [MainThread] [I] [toil.statsAndLogging] Enabling realtime logging in Toil
[2024-11-27T18:26:38+0000] [MainThread] [W] [toil.lib.humanize] Deprecated toil method.  Please use "toil.lib.conversions.human2bytes()" instead."
[2024-11-27T18:26:38+0000] [MainThread] [W] [toil.lib.humanize] Deprecated toil method.  Please use "toil.lib.conversions.human2bytes()" instead."
[2024-11-27T18:26:38+0000] [MainThread] [I] [toil.statsAndLogging] Cactus Command: /home/cactus/cactus_env/bin/cactus ./js /home/mmora30/localData/workspace_mm/temporal_tasks/cactus/cactus-1/cactus/examples/evolverMammals.txt ./evolverMammals.hal --logError --logInfo
[2024-11-27T18:26:38+0000] [MainThread] [I] [toil.statsAndLogging] Cactus Commit: 20488aeb80c3ef985034e538b36ad97ed632cad2
Traceback (most recent call last):
  File "/home/cactus/cactus_env/bin/cactus", line 8, in <module>
    sys.exit(main())
  File "/home/cactus/cactus_env/lib/python3.10/site-packages/cactus/progressive/cactus_progressive.py", line 423, in main
    mc_tree, input_seq_map, og_candidates = parse_seqfile(options.seqFile, config_wrapper, root_name = options.root)
  File "/home/cactus/cactus_env/lib/python3.10/site-packages/cactus/progressive/progressive_decomposition.py", line 41, in parse_seqfile
    seq_file = SeqFile(seqfile_path, root_name = root_name, defaultBranchLen=config_wrapper.getDefaultBranchLen(pangenome=pangenome))
  File "/home/cactus/cactus_env/lib/python3.10/site-packages/cactus/progressive/seqFile.py", line 68, in __init__
    self.parseFile(path, root_name)
  File "/home/cactus/cactus_env/lib/python3.10/site-packages/cactus/progressive/seqFile.py", line 72, in parseFile
    raise RuntimeError("File not found: %s" % path)
RuntimeError: File not found: /home/mmora30/localData/workspace_mm/temporal_tasks/cactus/cactus-1/cactus/examples/evolverMammals.txt
```
So, no make sense. The file is there but I still got that error. Any comment?

**Comment by glennhickey** [comment]
You seem to be having trouble differentiating between your file system, and the file system inside the singularity container.  I suggest running 

```
singularity exec /home/mmora30/singularity/cactus-v2.9.3.simg bash
```

and then continuing interactively inside the container, running cactus directly.  That way the files you see with `ls` will have paths that are valid in the container.

**Comment by MauriAndresMU1313** [comment]
Now makes sense, my bad. I did not realize about that. Now is running properly inside the container!
Thank you for the clarification.
