### ISSUE TITLE
toil.batchSystems.abstractBatchSystem.InsufficientSystemResources

### ISSUE THREAD

**Issue by Johnsonzcode** [ComparativeGenomicsToolkit/cactus#1551]
Hi @glennhickey 
Thanks for your work.

Here is my command:
```shell
#!/bin/bash
#SBATCH --job-name=cactus
#SBATCH --partition=debug
#SBATCH --ntasks=1
#SBATCH --ntasks-per-node=1
#SBATCH --mem=4GB
#SBATCH --output=cactus_%j.o
#SBATCH --error=cactus_%j.e

source ~/workspace/software/cactus-bin-v2.9.3/venv-cactus-v2.9.3/bin/activate
export PATH=$PATH:~/miniforge-pypy3/bin
export OMP_THREAD_LIMIT=128
cactus-pangenome ./js xx.pan.genome.txt \
        --outDir xx-pg --outName xx-pg --reference Cxx \
        --vcf --giraffe --gfa --gbz \
        --batchLogsDir /tmp/cactus/logs \
        --workDir /tmp/cactus --restart \
        --mgCores 128 --mgMemory 400Gb --mapCores 4 --odgi --maxMemory 400Gb \
        --vcfwaveCores 128 --vcfwaveMemory 400Gb --chrom-vg --chrom-og  --maxCores 128
```

I am encountering the issue:

```shell
[2024-12-02T11:00:50+0800] [MainThread] [I] [toil.realtimeLogger] Stopping real-time logging server.
[2024-12-02T11:00:50+0800] [MainThread] [I] [toil.realtimeLogger] Joining real-time logging server thread.
Traceback (most recent call last):
  File "/storage-05/poultrylab5/miniforge-pypy3/bin/cactus-pangenome", line 8, in <module>
    sys.exit(main())
  File "/storage-05/poultrylab5/miniforge-pypy3/lib/python3.9/site-packages/cactus/refmap/cactus_pangenome.py", line 190, in main
    toil.restart()
  File "/storage-05/poultrylab5/miniforge-pypy3/lib/python3.9/site-packages/toil/common.py", line 967, in restart
    return self._runMainLoop(rootJobDescription)
  File "/storage-05/poultrylab5/miniforge-pypy3/lib/python3.9/site-packages/toil/common.py", line 1412, in _runMainLoop
    return Leader(config=self.config,
  File "/storage-05/poultrylab5/miniforge-pypy3/lib/python3.9/site-packages/toil/leader.py", line 262, in run
    self.innerLoop()
  File "/storage-05/poultrylab5/miniforge-pypy3/lib/python3.9/site-packages/toil/leader.py", line 765, in innerLoop
    self._processReadyJobs()
  File "/storage-05/poultrylab5/miniforge-pypy3/lib/python3.9/site-packages/toil/leader.py", line 658, in _processReadyJobs
    self._processReadyJob(message.job_id, message.result_status)
  File "/storage-05/poultrylab5/miniforge-pypy3/lib/python3.9/site-packages/toil/leader.py", line 551, in _processReadyJob
    self.issueJob(readyJob)
  File "/storage-05/poultrylab5/miniforge-pypy3/lib/python3.9/site-packages/toil/leader.py", line 918, in issueJob
    jobBatchSystemID = self.batchSystem.issueBatchJob(' '.join(workerCommand), jobNode, job_environment=job_environment)
  File "/storage-05/poultrylab5/miniforge-pypy3/lib/python3.9/site-packages/toil/batchSystems/singleMachine.py", line 759, in issueBatchJob
    self.check_resource_request(scaled_desc)
  File "/storage-05/poultrylab5/miniforge-pypy3/lib/python3.9/site-packages/toil/batchSystems/singleMachine.py", line 509, in check_resource_request
    raise e
  File "/storage-05/poultrylab5/miniforge-pypy3/lib/python3.9/site-packages/toil/batchSystems/singleMachine.py", line 505, in check_resource_request
    super().check_resource_request(requirer)
  File "/storage-05/poultrylab5/miniforge-pypy3/lib/python3.9/site-packages/toil/batchSystems/abstractBatchSystem.py", line 371, in check_resource_request
    raise e
  File "/storage-05/poultrylab5/miniforge-pypy3/lib/python3.9/site-packages/toil/batchSystems/abstractBatchSystem.py", line 364, in check_resource_request
    raise InsufficientSystemResources(requirer, resource, available)
toil.batchSystems.abstractBatchSystem.InsufficientSystemResources: The job 'cactus_cons' kind-cactus_cons/instance-q9oyx6eb v1 is requesting 128.0 cores, more than the maximum of 2 cores that SingleMachineBatchSystem was configured with, or enforced by --maxCores. Scale is set to 1.
```
This means that the config file only contains 2 cores. How do I change the config file, and where is the config?

Best
Johnson

**Comment by glennhickey** [comment]
No, the error is saying you are specifying 128 cores but running on a system with only 2 cores.  To fix this you need to either specify fewer cores, or run on a system with more cores...

**Comment by Johnsonzcode** [comment]
But my system is about 208 cores.

**Comment by Johnsonzcode** [comment]
Oh, thank you! I thought I was using the slurm batch method in Cactus. So, the main script only uses one or two, which is enough.
