### ISSUE TITLE
Installation problem

### ISSUE THREAD

**Issue by RenzoTale88** [ComparativeGenomicsToolkit/cactus#187]
Hi,
I am in need to reinstall cactus on a gridEngine system without docker. I've created a virtualenv with python 3.6, installed the lastest commit of toil, and cloned the latest version of cactus.
I have downloaded and compiled both HDF5 locally, added that to the path and proceeded with the compilation. All the compilations are performed through gcc 9.2.0. 
However, the software stops when starting to compile kyoto stating it cannot find lzo. I've then installed that locally, and added that to my LD_INCLUDE_PATH, but still it gives the same problem:
```
make suball1
make[1]: Entering directory `/PATH/TO/Andrea/cactus'
cd submodules/kyoto && make PREFIX=/PATH/TO/Andrea/cactus
make[2]: Entering directory `/PATH/TO/Andrea/cactus/submodules/kyoto'
test -x kyotocabinet/configure && cd kyotocabinet && ./configure --prefix="/PATH/TO/Andrea/cactus" --enable-lzo --disable-shared
#================================================================
# Configuring Kyoto Cabinet version 1.2.76a (no-shared) (lzo).
#================================================================
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking whether we are using the GNU C++ compiler... yes
checking whether g++ accepts -g... yes
checking how to run the C++ preprocessor... g++ -E
checking for grep that handles long lines and -e... /usr/bin/grep
checking for egrep... /usr/bin/grep -E
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking whether byte ordering is bigendian... no
checking for useless warnings... yes
checking for 8 byte atomic operations... yes
checking for main in -lc... yes
checking for main in -lm... yes
checking for main in -lpthread... yes
checking for main in -lrt... yes
checking for main in -lstdc++... yes
checking for main in -lregex... no
checking for main in -lz... yes
checking for main in -llzo2... no
checking for main in -lkyotocabinet... no
checking for stdlib.h... (cached) yes
checking for stdint.h... (cached) yes
checking for unistd.h... (cached) yes
checking fcntl.h usability... yes
checking fcntl.h presence... yes
checking for fcntl.h... yes
checking dirent.h usability... yes
checking dirent.h presence... yes
checking for dirent.h... yes
checking pthread.h usability... yes
checking pthread.h presence... yes
checking for pthread.h... yes
checking regex.h usability... yes
checking regex.h presence... yes
checking for regex.h... yes
checking zlib.h usability... yes
checking zlib.h presence... yes
checking for zlib.h... yes
checking lzo/lzo1x.h usability... no
checking lzo/lzo1x.h presence... no
checking for lzo/lzo1x.h... no
configure: error: lzo/lzo1x.h is required
make[2]: *** [kyotocabinet/Makefile] Error 1
make[2]: Leaving directory `/PATH/TO/Andrea/cactus/submodules/kyoto'
make[1]: *** [suball.kyoto] Error 2
make[1]: Leaving directory `/PATH/TO/Andrea/cactus'
make: *** [all] Error 2
```
Is there some configuration/system variable I'm missing?
Thank you in advance for the help
Andrea

**Comment by diekhans** [comment]
you need add the location of the include files

Something like exporting
export cppflags='-I <your_include_dir>'
export flags='-I <your_include_dir>'

sorry that all of the makefiles uses non-standard variable names.

**Comment by RenzoTale88** [comment]
Hi @diekhans thanks for the quick answer! I've just gave it a go, but I still get the same error:
```
checking for zlib.h... yes
checking lzo/lzo1x.h usability... no
checking lzo/lzo1x.h presence... no
checking for lzo/lzo1x.h... no
configure: error: lzo/lzo1x.h is required
make[2]: *** [kyotocabinet/Makefile] Error 1
make[2]: Leaving directory `/PATH/TO/Andrea/cactus/submodules/kyoto'
make[1]: *** [suball.kyoto] Error 2
make[1]: Leaving directory `/PATH/TO/Andrea/cactus'
make: *** [all] Error 2
```

When I look at the varariables, this is how I set them:
```
(cactus_env3) [atalenti@node2i15(eddie) cactus]$ echo $cppflags
-I/PATH/TO/Andrea/LZO/include -I/PATH/TO/Andrea/PROTOBUF/include -I/PATH/TO/gcc/7.3.0/include -I/PATH/TO/Andrea/LZO/include -I/PATH/TO/Andrea/PROTOBUF/include -I/PATH/TO/gcc/7.3.0/include -I/PATH/TO/kyoto/20170410//lib
```
Is this correct?

**Comment by diekhans** [comment]
Sorry, I misread the output.  You actually need to get the kyoto
cabinet configure to see your include.  It does use the standard
names, so also do

export CPPFLAGS="-Ithedir"

**Comment by RenzoTale88** [comment]
Ok, now it's finding the libraries and proceeding with the compilation. However, it soon stop while compiling kyototycoon with the following error:
```
g++ -g -O2 -Wall -fPIC -fsigned-char -g0 -O2 -Wno-unused-but-set-variable -Wno-unused-but-set-parameter -o kcutiltest kcutiltest.o -L. -L/PATH/TO/Andrea/cactus/lib -L/usr/local/lib -Wl,-rpath-link,.:/usr/local/lib:.:/usr/local/lib:/PATH/TO/gcc/7.3.0/lib64:/PATH/TO/Andrea/PROTOBUF/lib:/PATH/TO/gcc/7.3.0/lib64:/PATH/TO/kyoto/20170410//lib:/PATH/TO/kyoto/20170410//lib -Wl,--as-needed  -lkyotocabinet -lz -lstdc++ -lrt -lpthread -lm -lc 
g++ -g -O2 -Wall -fPIC -fsigned-char -g0 -O2 -Wno-unused-but-set-variable -Wno-unused-but-set-parameter -o kcutilmgr kcutilmgr.o -L. -L/PATH/TO/Andrea/cactus/lib -L/usr/local/lib -Wl,-rpath-link,.:/usr/local/lib:.:/usr/local/lib:/PATH/TO/gcc/7.3.0/lib64:/PATH/TO/Andrea/PROTOBUF/lib:/PATH/TO/gcc/7.3.0/lib64:/PATH/TO/kyoto/20170410//lib:/PATH/TO/kyoto/20170410//lib -Wl,--as-needed  -lkyotocabinet -lz -lstdc++ -lrt -lpthread -lm -lc 
./libkyotocabinet.a(kccompress.o): In function `kyotocabinet::LZO::compress(void const*, unsigned long, unsigned long*, kyotocabinet::LZO::Mode)':
kccompress.cc:(.text+0x313): undefined reference to `lzo1x_1_compress'
kccompress.cc:(.text+0x34e): undefined reference to `lzo_crc32'
./libkyotocabinet.a(kccompress.o): In function `kyotocabinet::LZO::decompress(void const*, unsigned long, unsigned long*, kyotocabinet::LZO::Mode)':
kccompress.cc:(.text+0x421): undefined reference to `lzo1x_decompress_safe'
kccompress.cc:(.text+0x46a): undefined reference to `lzo1x_decompress'
kccompress.cc:(.text+0x4f0): undefined reference to `lzo_crc32'
./libkyotocabinet.a(kccompress.o): In function `kyotocabinet::LZO::calculate_crc(void const*, unsigned long, unsigned int)':
kccompress.cc:(.text+0x50c): undefined reference to `lzo_crc32'
./libkyotocabinet.a(kccompress.o): In function `_GLOBAL__sub_I_kccompress.cc':
kccompress.cc:(.text.startup+0x55): undefined reference to `__lzo_init_v2'
collect2: error: ld returned 1 exit status
.make[3]: *** [kcutiltest] Error 1/
libkyotocabinet.a(kccompress.o): In function `kyotocabinetmake[3]: :*** Waiting for unfinished jobs....:
LZO::compress(void const*, unsigned long, unsigned long*, kyotocabinet::LZO::Mode)':
kccompress.cc:(.text+0x313): undefined reference to `lzo1x_1_compress'
kccompress.cc:(.text+0x34e): undefined reference to `lzo_crc32'
./libkyotocabinet.a(kccompress.o): In function `kyotocabinet::LZO::decompress(void const*, unsigned long, unsigned long*, kyotocabinet::LZO::Mode)':
kccompress.cc:(.text+0x421): undefined reference to `lzo1x_decompress_safe'
kccompress.cc:(.text+0x46a): undefined reference to `lzo1x_decompress'
kccompress.cc:(.text+0x4f0): undefined reference to `lzo_crc32'
./libkyotocabinet.a(kccompress.o): In function `kyotocabinet::LZO::calculate_crc(void const*, unsigned long, unsigned int)':
kccompress.cc:(.text+0x50c): undefined reference to `lzo_crc32'
./libkyotocabinet.a(kccompress.o): In function `_GLOBAL__sub_I_kccompress.cc':
kccompress.cc:(.text.startup+0x55): undefined reference to `__lzo_init_v2'
collect2: error: ld returned 1 exit status
make[3]: *** [kcutilmgr] Error 1
make[3]: Leaving directory `/PATH/TO/Andrea/cactus/submodules/kyoto/kyotocabinet'
make[2]: *** [cabinet] Error 2
make[2]: Leaving directory `/PATH/TO/Andrea/cactus/submodules/kyoto'
make[1]: *** [suball.kyoto] Error 2
make[1]: Leaving directory `/PATH/TO/Andrea/cactus'
make: *** [all] Error 2
```
Seems it doesn't like lzo for some reasons, althoug I've compiled it as everything else.
Thanks for the help
Andrea

**Comment by diekhans** [comment]
try

  export LDFLAGS="-L<libdir> -llzo"

**Comment by RenzoTale88** [comment]
Ok now using the exact same script I get the following error:
```
#================================================================
# Configuring Kyoto Cabinet version 1.2.76a (no-shared) (lzo).
#================================================================
checking for gcc... gcc
checking whether the C compiler works... no
configure: error: in `/PATH/TO/Andrea/cactus/submodules/kyoto/kyotocabinet':
configure: error: C compiler cannot create executables
See `config.log' for more details
make[2]: *** [kyotocabinet/Makefile] Error 77
make[2]: Leaving directory `/PATH/TO/Andrea/cactus/submodules/kyoto'
make[1]: *** [suball.kyoto] Error 2
make[1]: Leaving directory `/PATH/TO/Andrea/cactus'
make: *** [all] Error 2
```
It doesn't even start compiling this time. Which is rather confusing, considering that I am literally copying and pasting commands from the same script.

**Comment by diekhans** [comment]
this looks like CC environment variable is set to /PATH/TO/Andrea/cactus/submodules/kyoto/kyotocabinet

**Comment by RenzoTale88** [comment]
Ok, I've set CC and also CXX to gcc and g++, but the error didn't change:
```
#================================================================
# Configuring Kyoto Cabinet version 1.2.76a (no-shared) (lzo).
#================================================================
checking for gcc... /exports/applications/apps/community/roslin/gcc/7.3.0/bin/gcc
checking whether the C compiler works... no
configure: error: in `/exports/cmvm/eddie/eb/groups/prendergast_grp/Andrea/cactus/submodules/kyoto/kyotocabinet':
configure: error: C compiler cannot create executables
See `config.log' for more details
make[2]: *** [kyotocabinet/Makefile] Error 77
make[2]: Leaving directory `/exports/cmvm/eddie/eb/groups/prendergast_grp/Andrea/cactus/submodules/kyoto'
make[1]: *** [suball.kyoto] Error 2
make[1]: Leaving directory `/exports/cmvm/eddie/eb/groups/prendergast_grp/Andrea/cactus'
make: *** [all] Error 2
```

**Comment by RenzoTale88** [comment]
I get the chance to signal a small problem with the python 2 final release. I managed to install that and run it. However I came across a couple of issues:
1. Since the package doesn't come with the submodules, I've tried to download them. ```gitgit submodule update --init ``` didn't work (```Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set)```). To make it work, I had to download each dependency in ```.gitmodule``` through ```git clone``` and then compile.
2. Installation through pip didn't work as well. To make it work, I had to clone the current git repository, and copy all .git* files and folders into the python 2 version. At that point, installation worked just fine.

Prior using these solutions, I've tried using ```git init``` to see whether reinitiating git in the folder would fix the issue, but it didn't work.

It's just a minor git issue, hopefully easy to fix.

Andrea

**Comment by glennhickey** [comment]
I'm just curious, how did you install `kyoto tycoon` with the python 2 version.  Are you using the apt package?  If you have access to apt, then you should just be able to use it to install lzo as well.  That's how we do it: https://github.com/ComparativeGenomicsToolkit/cactus/blob/master/Dockerfile#L4

**Comment by RenzoTale88** [comment]
@glennhickey unfortunately I do not have access to apt, and I don't have admin rights either. kyototycoon has been installed by the IT support, and set all the paths consequently.
But you're right, I haven't thought about it, and I've found lzo installed in another path in the cluster. I'll give it a go adding that to the path instead of locally install it.

**Comment by diekhans** [comment]
what Linux distribution and release are you building on?

**Comment by RenzoTale88** [comment]
Ok after setting LDFLAGS (without ```-llzo```) and CPPFLAGS as following:
```
export LDFLAGS='-L/PATH/TO/gcc/7.3.0/lib64/ -L/PATH/TO/lzo/2.10/lib/ -LPATH/TO/kyoto/20170410/lib'
export CPPFLAGS='-I/PATH/TO/gcc/7.3.0/include -IPATH/TO/lzo/2.10/include -I/PATH/TO/kyoto/20170410/include'
export CC='/PATH/TO/gcc/7.3.0/bin/gcc'
export CXX='/PATH/TO/gcc/7.3.0/bin/g++'
```
With these set, compilation progressed a bit. Now it failed when compiling ```sonLib```:
```
mv ../lib/sonLibString.h.tmp ../lib/sonLibString.h
/PATH/TO/gcc/7.3.0/bin/gcc -std=c99 -O3 -g -Wall --pedantic -funroll-loops -DNDEBUG   -I./include -DHAVE_KYOTO_TYCOON=1    -I../externalTools/quicktree_1.1/include/  -I inc -I ../lib/  -c impl/*.c
/PATH/TO/roslin/gcc/7.3.0/bin/g++  -O3 -g -Wall -funroll-loops -DNDEBUG  -I./include -DHAVE_KYOTO_TYCOON=1    -I../externalTools/quicktree_1.1/include/  -I inc -I ../lib/ -c impl/*.cpp
impl/sonLibKVDatabase_KyotoTycoon.cpp:36:10: fatal error: ktremotedb.h: No such file or directory
 #include <ktremotedb.h>
          ^~~~~~~~~~~~~~
compilation terminated.
make[3]: *** [../lib/sonLib.a] Error 1
make[3]: Leaving directory `/PATH/TO/Andrea/cactus/submodules/sonLib/C'
make[2]: *** [cP] Error 2
make[2]: Leaving directory `/PATH/TO/Andrea/cactus/submodules/sonLib'
make[1]: *** [suball.sonLib] Error 2
make[1]: Leaving directory `/PATH/TO/Andrea/cactus'
make: *** [all] Error 2
```
The system is a Scientific Linux 7.5.
Thank you again for your help
Andrea

**Comment by RenzoTale88** [comment]
Hi again,
I got some advances into this. Recently, I found out that now the gridEngine cluster I work on has singularity installed. Therefore, I managed to run everything without the need to compile anything. Everything worked fine as a single machine job, which is great. 
However, when I try to run it adding the ```--batchSystem gridEngine --disableCaching```, the software returns the following error:
```
Traceback (most recent call last):
  File "/PATH/TO/Andrea/cactus_env3/bin/cactus", line 8, in <module>
    sys.exit(main())
  File "/PATH/TO/Andrea/cactus_env3/lib/python3.6/site-packages/cactus/progressive/cactus_progressive.py", line 401, in main
    runCactusProgressive(options)
  File "/PATH/TO/Andrea/cactus_env3/lib/python3.6/site-packages/cactus/progressive/cactus_progressive.py", line 449, in runCactusProgressive
    halID = toil.start(RunCactusPreprocessorThenProgressiveDown(options, project, memory=configWrapper.getDefaultMemory()))
  File "/PATH/TO/Andrea/cactus_env3/lib/python3.6/site-packages/toil/common.py", line 779, in start
    self._batchSystem = self.createBatchSystem(self.config)
  File "/PATH/TO/Andrea/cactus_env3/lib/python3.6/site-packages/toil/common.py", line 924, in createBatchSystem
    return batchSystemClass(**kwargs)
  File "/PATH/TO/Andrea/cactus_env3/lib/python3.6/site-packages/toil/batchSystems/abstractGridEngineBatchSystem.py", line 308, in __init__
    self.maxCPU, self.maxMEM = self.obtainSystemConstants()
  File "/PATH/TO/Andrea/cactus_env3/lib/python3.6/site-packages/toil/batchSystems/gridengine.py", line 166, in obtainSystemConstants
    if items[cpu_index] != '-' and items[cpu_index] > maxCPU:
TypeError: list indices must be integers or slices, not NoneType
^CException ignored in: <module 'threading' from '/PATH/TO/python/3.6.8/lib/python3.6/threading.py'>
Traceback (most recent call last):
  File "/PATH/TO/python/3.6.8/lib/python3.6/threading.py", line 1294, in _shutdown
    t.join()
  File "/PATH/TO/python/3.6.8/lib/python3.6/threading.py", line 1056, in join
    self._wait_for_tstate_lock()
  File "/PATH/TO/python/3.6.8/lib/python3.6/threading.py", line 1072, in _wait_for_tstate_lock
    elif lock.acquire(block, timeout):
KeyboardInterrupt
```

There is a problem in the toil ```gridengine.py``` script. Not sure how to fix this though.

Thank you again 
Andrea

**Comment by diekhans** [comment]
I happen to be helping someone on a grid engine cluster and get the same
error.  Stand by.

**Comment by RenzoTale88** [comment]
@diekhans thank you very much, let me know if you need it to be tested.
Andrea

**Comment by diekhans** [comment]
hi @RenzoTale88 

I have a cactus run that now seems to be moving along with using this
toil branch:
  https://github.com/DataBiosphere/toil/tree/issues/2951-slurm-logging

Please give it a try.  Also, what version of gridengine are you using?

**Comment by RenzoTale88** [comment]
Hi @diekhans , sure I'll give it a try now. Is there some instruction to use to install that specific branch?
I've tried with:
```
pip install --upgrade git+https://github.com/DataBiosphere/toil/tree/issues/2951-slurm-logging
```
But it gave me this error:
```
Collecting git+https://github.com/DataBiosphere/toil/tree/issues/2951-slurm-logging
  Cloning https://github.com/DataBiosphere/toil/tree/issues/2951-slurm-logging to /PATH/TO/Andrea/cactus/examples/TMP/pip-req-build-0auh9qsk
  Running command git clone -q https://github.com/DataBiosphere/toil/tree/issues/2951-slurm-logging /PATH/TO/Andrea/cactus/examples/TMP/pip-req-build-0auh9qsk
  fatal: repository 'https://github.com/DataBiosphere/toil/tree/issues/2951-slurm-logging/' not found
ERROR: Command errored out with exit status 128: git clone -q https://github.com/DataBiosphere/toil/tree/issues/2951-slurm-logging /PATH/TO/Andrea/cactus/examples/TMP/pip-req-build-0auh9qsk Check the logs for full command output.
```

The system has installed UGE 8.6.5.

Andrea

**Comment by RenzoTale88** [comment]
Ok sorry, ignore the previous message. I managed to install it, but I'm encountering the following issue:
```
Log from job kind-logAssemblyStats/instance-1cuunp64 follows:
=========>
        INFO:toil.worker:---TOIL WORKER OUTPUT LOG---
        INFO:toil:Running Toil version 4.1.0a1-c412f9e06d79544f1575ec1e9473299553cb80e0-dirty.
        INFO:cactus.shared.common:Work dirs: {'/PATH/TO/Andrea/cactus/examples/TMP/node-7484df35-5c91-478d-a9ee-0e09c68179ec-b5ecd264-25fd-4f86-ac49-899b2ce1cce6/tmp3gkffgw7/ab5fefde-a030-48f3-97da-57a
294882335'}
        INFO:cactus.shared.common:Docker work dir: /PATH/TO/Andrea/cactus/examples/TMP/node-7484df35-5c91-478d-a9ee-0e09c68179ec-b5ecd264-25fd-4f86-ac49-899b2ce1cce6/tmp3gkffgw7/ab5fefde-a030-48f3-97da
-57a294882335
        INFO:cactus.shared.common:Running the command ['singularity', '--silent', 'run', '/PATH/TO/Andrea/cactus/examples/jobStore/cactus.img', 'cactus_analyseAssembly', 'tmp3kbbb70g.tmp']
        FATAL:   while extracting /PATH/TO/Andrea/cactus/examples/jobStore/cactus.img: root filesystem extraction failed: extract command failed: 
        FATAL ERROR:Out of memory in cache_get
        Parallel unsquashfs: Using 32 processors
        23128 inodes (26382 blocks) to write

        : exit status 1
        Traceback (most recent call last):
          File "/PATH/TO/Andrea/cactus_env3/lib/python3.6/site-packages/toil/worker.py", line 366, in workerScript
            job._runner(jobGraph=jobGraph, jobStore=jobStore, fileStore=fileStore, defer=defer)
          File "/PATH/TO/Andrea/cactus_env3/lib/python3.6/site-packages/toil/job.py", line 1392, in _runner
            returnValues = self._run(jobGraph, fileStore)
          File "/PATH/TO/Andrea/cactus_env3/lib/python3.6/site-packages/toil/job.py", line 1329, in _run
            return self.run(fileStore)
          File "/PATH/TO/Andrea/cactus_env3/lib/python3.6/site-packages/toil/job.py", line 1533, in run
            rValue = userFunction(*((self,) + tuple(self._args)), **self._kwargs)
          File "/PATH/TO/Andrea/cactus_env3/lib/python3.6/site-packages/cactus/progressive/cactus_progressive.py", line 204, in logAssemblyStats
            analysisString = cactus_call(parameters=["cactus_analyseAssembly", sequenceFile], check_output=True)
          File "/PATH/TO/Andrea/cactus_env3/lib/python3.6/site-packages/cactus/shared/common.py", line 1261, in cactus_call
            raise RuntimeError("Command %s failed with output: %s" % (call, output))
        RuntimeError: Command ['singularity', '--silent', 'run', '/PATH/TO/Andrea/cactus/examples/jobStore/cactus.img', 'cactus_analyseAssembly', 'tmp3kbbb70g.tmp'] failed with output: 
        ERROR:toil.worker:Exiting the worker because of a failed job on host node1c11
        WARNING:toil.jobGraph:Due to failure we are reducing the remaining retry count of job 'logAssemblyStats' kind-logAssemblyStats/instance-1cuunp64 with ID kind-logAssemblyStats/instance-1cuunp64 to 3
<=========
Issued job 'logAssemblyStats' kind-logAssemblyStats/instance-1cuunp64 with job batch system ID: 21 and cores: 1, disk: 8.0 G, and memory: 2.0 G
```
Toil seems to be submitting, but jobs seems to fail since they cannot find singularity on each single node. I'll speak to IT people to see whether there is a solution for this problem.
In the meanwhile, do you think there is a wway to automatically load singularity when submitting a job to the scheduler?
Thank you 
Andrea

**Comment by diekhans** [comment]
The way I do it is to clone and checkout the branch, and then, inside
of a virtual environment, do

make prepare
make develop

as described here:

   https://toil.readthedocs.io/en/latest/gettingStarted/install.html#buildfromsource

**Comment by diekhans** [comment]
this seems like an error with singularity:
        FATAL:   while extracting /PATH/TO/Andrea/cactus/examples/jobStore/cactus.img: root filesystem extraction failed: extract command failed: 
        FATAL ERROR:Out of memory in cache_get

although I don't know what this means.

**Comment by AlisaGU** [comment]
> try export LDFLAGS="-L<libdir> -llzo" RenzoTale88 <notifications@github.com> writes:
> […](#)

Hi,
I tried `export LDFLAGS="-L/picb/evolgen/users/gushanshan/software/myC/lzo/lzo_install/lib"`.
However, this error didn't change:
```
kccompress.cc:(.text.startup._GLOBAL__sub_I_kccompress.cc+0x58): undefined reference to `__lzo_init_v2'
collect2: error: ld returned 1 exit status
make[3]: *** [Makefile:1091: kcgrasstest] Error 1
make[3]: Leaving directory '/picb/evolgen/users/gushanshan/software/Cactus/cactus/submodules/kyoto/kyotocabinet'
make[2]: *** [Makefile:64: cabinet] Error 2
make[2]: Leaving directory '/picb/evolgen/users/gushanshan/software/Cactus/cactus/submodules/kyoto'
make[1]: *** [Makefile:185: suball.kyoto] Error 2
make[1]: Leaving directory '/picb/evolgen/users/gushanshan/software/Cactus/cactus'
make: *** [Makefile:32: all] Error 2
```
Did I miss sth?

**Comment by alptaciroglu** [comment]
I am having a similar issue in the installation of Cactus on Ubuntu version 18.04.5 LTS. I followed the 'Build From Source' directive. 

I would appreciate any help. 

Things I have tried so far: 

Tried to install HDF5 through CMake & apt-get   
Tried to install kyotocabinet separately (I am aware the issue might not be related to these)

![image](https://user-images.githubusercontent.com/13270606/100768893-701af980-340c-11eb-8025-661d19d1485f.png)

**Comment by glennhickey** [comment]
On ubuntu, you should be able to install all the build dependencies [with apt as shown here](https://github.com/ComparativeGenomicsToolkit/cactus/blob/master/Dockerfile#L4), which includes the `liblzo2-dev` package.

**Comment by alptaciroglu** [comment]
> On ubuntu, you should be able to install all the build dependencies [with apt as shown here](https://github.com/ComparativeGenomicsToolkit/cactus/blob/master/Dockerfile#L4), which includes the `liblzo2-dev` package.

I was able to run the dependencies listed in Dockerfile with 'docker build' command. Thanks
