### ISSUE TITLE
Issue with singularity

### ISSUE THREAD

**Issue by RenzoTale88** [ComparativeGenomicsToolkit/cactus#196]
Hi,just wanted to signal a minor bug. While trying to run cactus with singularity, I've came across the following error:
```
Traceback (most recent call last):
  File "/exports/cmvm/eddie/eb/groups/prendergast_grp/Andrea/cactus_env3/lib/python3.6/site-packages/cactus/shared/common.py", line 961, in importSingularityImage
    check_call(["singularity", "pull", "--size", "2000", "--name", os.path.basename(imgPath),
NameError: name 'check_call' is not defined

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/PATH/TO/Andrea/cactus_env3/bin/cactus", line 8, in <module>
    sys.exit(main())
  File "/PATH/TO/Andrea/cactus_env3/lib/python3.6/site-packages/cactus/progressive/cactus_progressive.py", line 401, in main
    runCactusProgressive(options)
  File "/PATH/TO/Andrea/cactus_env3/lib/python3.6/site-packages/cactus/progressive/cactus_progressive.py", line 408, in runCactusProgressive
    importSingularityImage(options)
  File "/PATH/TO/Andrea/cactus_env3/lib/python3.6/site-packages/cactus/shared/common.py", line 963, in importSingularityImage
    except CalledProcessError:
NameError: name 'CalledProcessError' is not defined
```

I've fixed it simply adding the line:
```
from subprocess import check_call, CalledProcessError
```
At the beginnning of the file. 
Cheers
Andrea

**Comment by diekhans** [comment]
will get a fix for this ASAP
