### ISSUE TITLE
cactus-prepare requiring docker in local/singleMachine mode 

### ISSUE THREAD

**Issue by egoltsman** [ComparativeGenomicsToolkit/cactus#244]
Hello,
I am trying to run cactus piecemeal to get a better handle on the resource requirements.  Our system doesn't support/allow docker, so I'm forces to run the binaries locally.  However, even with --batchSystem singleMachine and --binariesMode local  it still searches for a docker environment.  Below is my full command and the error.  Please advise. 

Thank you!

```
cactus-preprocess jobstore 3-samples.CHR1.input 3-samples.CHR1__steps/3-samples.CHR1.txt --inputNames Ref Bd21-3 Bd21-3_r **--batchSystem singleMachine  --binariesMode local** --realTimeLogging --maxCores 64 --maxMemory 128Gi --metrics --writeLogs 3-samples.CHR1__steps/workerLogs

No branch length for Ref: setting to 1
No branch length for Bd21-3: setting to 1
No branch length for Bd21-3_r: setting to 1
No branch length for : setting to 1
No branch length for : setting to 1
Limiting maxMemory to physically available memory (135060561920).
Limiting maxDisk to physically available disk (67530170368).
Running Toil version 3.24.0-de586251cb579bcb80eef435825cb3cedc202f52.
Starting real-time logging.
Using default docker registry of quay.io/ucsc_cgl as TOIL_DOCKER_REGISTRY is not set.
Stopping real-time logging server.
Joining real-time logging server thread.
Traceback (most recent call last):
  File "/global/homes/e/eugeneg/.conda/envs/pan-gen/bin/cactus-preprocess", line 8, in <module>
    sys.exit(main())
  File "/global/homes/e/eugeneg/.conda/envs/pan-gen/lib/python3.6/site-packages/cactus/preprocessor/cactus_preprocessor.py", line 335, in main
    stageWorkflow(outputSequenceDir=None, configFile=options.configFile, inputSequences=inSeqPaths, toil=toil, restart=options.restart, outputSequences=outSeqPaths)
  File "/global/homes/e/eugeneg/.conda/envs/pan-gen/lib/python3.6/site-packages/cactus/preprocessor/cactus_preprocessor.py", line 272, in stageWorkflow
    outputSequenceIDs = toil.start(CactusPreprocessor(inputSequenceIDs, configNode))
  File "/global/homes/e/eugeneg/.conda/envs/pan-gen/lib/python3.6/site-packages/toil/common.py", line 800, in start
    return self._runMainLoop(rootJobGraph)
  File "/global/homes/e/eugeneg/.conda/envs/pan-gen/lib/python3.6/site-packages/toil/common.py", line 1070, in _runMainLoop
    jobCache=self._jobCache).run()
  File "/global/homes/e/eugeneg/.conda/envs/pan-gen/lib/python3.6/site-packages/toil/leader.py", line 198, in run
    self.toilMetrics = ToilMetrics(provisioner=self.provisioner)
  File "/global/homes/e/eugeneg/.conda/envs/pan-gen/lib/python3.6/site-packages/toil/common.py", line 1132, in __init__
    self.startDashboard(clusterName=clusterName, zone=region)
  File "/global/homes/e/eugeneg/.conda/envs/pan-gen/lib/python3.6/site-packages/toil/common.py", line 1188, in startDashboard
    if not self._containerRunning("toil_prometheus"):
  File "/global/homes/e/eugeneg/.conda/envs/pan-gen/lib/python3.6/site-packages/toil/common.py", line 1181, in _containerRunning
    "'{{.State.Running}}'", containerName]).decode('utf-8') == "true"
  File "/global/homes/e/eugeneg/.conda/envs/pan-gen/lib/python3.6/subprocess.py", line 356, in check_output
    **kwargs).stdout
  File "/global/homes/e/eugeneg/.conda/envs/pan-gen/lib/python3.6/subprocess.py", line 423, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/global/homes/e/eugeneg/.conda/envs/pan-gen/lib/python3.6/subprocess.py", line 729, in __init__
    restore_signals, start_new_session)
  File "/global/homes/e/eugeneg/.conda/envs/pan-gen/lib/python3.6/subprocess.py", line 1364, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'docker': 'docker'
^CException ignored in: <module 'threading' from '/global/homes/e/eugeneg/.conda/envs/pan-gen/lib/python3.6/threading.py'>
Traceback (most recent call last):
  File "/global/homes/e/eugeneg/.conda/envs/pan-gen/lib/python3.6/threading.py", line 1294, in _shutdown
    t.join()
  File "/global/homes/e/eugeneg/.conda/envs/pan-gen/lib/python3.6/threading.py", line 1056, in join
    self._wait_for_tstate_lock()
  File "/global/homes/e/eugeneg/.conda/envs/pan-gen/lib/python3.6/threading.py", line 1072, in _wait_for_tstate_lock
    elif lock.acquire(block, timeout):

```

**Comment by egoltsman** [comment]
Ah, it was the --metrics option.   Sorry, you can disregard this ticket.
