### ISSUE TITLE
Cactus breaks due to missing HOME

### ISSUE THREAD

**Issue by adamnovak** [ComparativeGenomicsToolkit/cactus#246]
I tried to run Cactus on Toil AWS autoscaling , with Flatcar replacing the defunct CoreOS.

I got this:

```
Traceback (most recent call last):
      File "/usr/local/lib/python3.7/dist-packages/toil/worker.py", line 368, in workerScript
        job._runner(jobGraph=jobGraph, jobStore=jobStore, fileStore=fileStore, defer=defer)
      File "/tmp/tmp40r0tifx/222c566bfb3f926185a9ad38be3e7016/cactus/shared/common.py", line 1335, in _runner
        super(RoundedJob, self)._runner(jobGraph=jobGraph, jobStore=jobStore, fileStore=fileStore, defer=defer)
      File "/usr/local/lib/python3.7/dist-packages/toil/job.py", line 1392, in _runner
        returnValues = self._run(jobGraph, fileStore)
      File "/usr/local/lib/python3.7/dist-packages/toil/job.py", line 1329, in _run
        return self.run(fileStore)
      File "/tmp/tmp40r0tifx/222c566bfb3f926185a9ad38be3e7016/cactus/preprocessor/cactus_preprocessor.py", line 141, in run
        overlapSize=0)
      File "/tmp/tmp40r0tifx/222c566bfb3f926185a9ad38be3e7016/cactus/shared/common.py", line 811, in runGetChunks
        chunksDir] + sequenceFiles)
      File "/tmp/tmp40r0tifx/222c566bfb3f926185a9ad38be3e7016/cactus/shared/common.py", line 1205, in cactus_call
        parameters=parameters, port=port, file_store=fileStore)
      File "/tmp/tmp40r0tifx/222c566bfb3f926185a9ad38be3e7016/cactus/shared/common.py", line 1014, in singularityCommand
        cache_dir = os.path.join(os.environ.get('SINGULARITY_CACHEDIR',  os.path.join(os.environ.get('HOME'), '.singularity')), 'toil')
      File "/usr/lib/python3.7/posixpath.py", line 80, in join
        a = os.fspath(a)
    TypeError: expected str, bytes or os.PathLike object, not NoneType
```

The only way I can see for this to happen is if `HOME` is not set. We maybe should use [Python's official way to find a home directory](https://docs.python.org/3/library/pathlib.html#pathlib.Path.home) instead.

**Comment by adamnovak** [comment]
This also occurs when running on actual CoreOS; I guess Toil doesn't run things under a login shell at all, and it explicitly avoids propagating the HOME set on the leader, so it doesn't guarantee that HOME is set.
