### ISSUE TITLE
Cactus fails on simple tree with internal node labels

### ISSUE THREAD

**Issue by glennhickey** [ComparativeGenomicsToolkit/cactus#324]
Here's a simple tree from @mhaukness-ucsc that seems to break cactus. 
```
(Chimp:0.00655,(GRCh38:0.0005,CHM13:0.0005)Anc1:0.006)Anc0:0.00122;
Chimp  http://s3-us-west-2.amazonaws.com/jcarmstr-misc/testRegions/evolverMammals/simCow.chr6
GRCh38 http://s3-us-west-2.amazonaws.com/jcarmstr-misc/testRegions/evolverMammals/simDog.chr6
CHM13   http://s3-us-west-2.amazonaws.com/jcarmstr-misc/testRegions/evolverMammals/simHuman.chr6
```
where running it
```
cactus ./js input.txt --binariesMode local --realTimeLogging output.hal
```
leads to a `halAppendSubtree` error (perhaps it's getting called more than it should?)
```
Running the command: "halAppendCactusSubtree tmpidgyuwgw.tmp tmp181gyx00.tmp (Chimp:0.00655,Anc1:0.006)Anc0; tmp_alignment.hal"
	hal exception caught: Fatal Tree error.  converter does not support adding more than one non-leaf:Chimp
	Traceback (most recent call last):
	  File "/home/hickey/dev/cactus-2/venv2/lib/python3.6/site-packages/toil/worker.py", line 368, in workerScript
	    job._runner(jobGraph=jobGraph, jobStore=jobStore, fileStore=fileStore, defer=defer)
	  File "/home/hickey/dev/cactus-2/venv2/lib/python3.6/site-packages/toil/job.py", line 1424, in _runner
	    returnValues = self._run(jobGraph, fileStore)
	  File "/home/hickey/dev/cactus-2/venv2/lib/python3.6/site-packages/toil/job.py", line 1361, in _run
	    return self.run(fileStore)
	  File "/home/hickey/dev/cactus-2/venv2/lib/python3.6/site-packages/toil/job.py", line 1565, in run
	    rValue = userFunction(*((self,) + tuple(self._args)), **self._kwargs)
	  File "/home/hickey/dev/cactus-2/venv2/lib/python3.6/site-packages/cactus/progressive/cactus_progressive.py", line 331, in exportHal
	    cactus_call(parameters=["halAppendCactusSubtree"] + args)
	  File "/home/hickey/dev/cactus-2/venv2/lib/python3.6/site-packages/cactus/shared/common.py", line 1306, in cactus_call
	    raise RuntimeError("Command {} exited {}: {}".format(call, process.returncode, out))
	RuntimeError: Command ['halAppendCactusSubtree', 'tmpidgyuwgw.tmp', 'tmp181gyx00.tmp', '(Chimp:0.00655,Anc1:0.006)Anc0;', 'tmp_alignment.hal'] exited 1: stdout=None
```
This command runs fine when the Ancestor labels are stripped out of the tree:
```
(Chimp:0.00655,(GRCh38:0.0005,CHM13:0.0005));
```

**Comment by TUANNN518** [comment]
hi,
I test the example in the software, Ancestor labels are not in input .txt file. When i convert the HAL result to the MAF format using **hal2maf**, the Ancestor labels can be found in the MAF file.

Here is the input .txt file:
((simHuman_chr6:0.144018,(simMouse_chr6:0.084509,simRat_chr6:0.091589)mr:0.271974):0.020593,(simCow_chr6:0.18908,simDog_chr6:0.16303):0.032898);

simCow_chr6 http://s3-us-west-2.amazonaws.com/jcarmstr-misc/testRegions/evolverMammals/simCow.chr6
simDog_chr6 http://s3-us-west-2.amazonaws.com/jcarmstr-misc/testRegions/evolverMammals/simDog.chr6
simHuman_chr6 http://s3-us-west-2.amazonaws.com/jcarmstr-misc/testRegions/evolverMammals/simHuman.chr6
simMouse_chr6 http://s3-us-west-2.amazonaws.com/jcarmstr-misc/testRegions/evolverMammals/simMouse.chr6
simRat_chr6 http://s3-us-west-2.amazonaws.com/jcarmstr-misc/testRegions/evolverMammals/simRat.chr6

Here is the MAF format file:
##maf version=1 scoring=N/A
# hal ((simHuman_chr6:0.144018,(simMouse_chr6:0.084509,simRat_chr6:0.091589)mr:0.271974)**Anc1**:0.020593,(simCow_chr6:0.18908,simDog_chr6:0.16303)**Anc2**:0.032898)**Anc0**;

a
s	simHuman_chr6.simHuman.chr6	0	1	+	601863	T
s	Anc1.Anc1refChr0	0	1	+	43783	T

a
s	simHuman_chr6.simHuman.chr6	1	4	+	601863	CTTT
s	Anc1.Anc1refChr0	1	4	+	43783	CTTT
s	mr.mrrefChr0	0	4	+	131077	TTTT
s	simMouse_chr6.simMouse.chr6	1	4	+	636262	TTTT
s	simRat_chr6.simRat.chr6	0	4	+	647215	TTTT

I hope that will be helpful.
