### ISSUE TITLE
Running cactus gpu as singularity image

### ISSUE THREAD

**Issue by RenzoTale88** [ComparativeGenomicsToolkit/cactus#339]
Hello,
I'm trying to run cactus on our cluster, running UGE grid engine. So far, I've been running cactus as a singularity image:
```
singularity exec --bin $PWD:/mnt cactus.sif cactus
```
However, I've seen that you've released a docker image with gpu support, and since our cluster has several gpu nodes, I'd like to try and use those instead.
I've been downloading the cactus gpu image using ```singularity pull docker://quay.io/comparative-genomics-toolkit/cactus:v1.2.3-gpu``` and then ran it as:
```
SINGULARITYENV_CUDA_VISIBLE_DEVICES=0 singularity exec --nv --bind $PWD:/mnt cactus_v1.2.3-gpu.sif cactus jobStore confile.txt
```
The job run the first steps successfully, but then fails not finding any GPU in the system:
```
[2020-10-27T15:06:43+0000] [MainThread] [W] [toil.leader] The job seems to have left a log file, indicating failure: 'LastzRepeatMaskJob' kind-LastzRepeatMaskJob/instance-ttb3lx60
[2020-10-27T15:06:43+0000] [MainThread] [W] [toil.leader] Log from job kind-LastzRepeatMaskJob/instance-ttb3lx60 follows:
=========>
        [2020-10-27T15:06:43+0000] [MainThread] [I] [toil.worker] ---TOIL WORKER OUTPUT LOG---
        [2020-10-27T15:06:43+0000] [MainThread] [I] [toil] Running Toil version 4.2.0-3aa1da130141039cb357efe36d7df9b9f6ae9b5b on host node1f04.
        [2020-10-27T15:06:43+0000] [MainThread] [I] [cactus.shared.common] Running the command ['segalign_repeat_masker', '/PATH/TO/HAL/TMP/node-3b7fafc6-513c-4313-abfd-3c594a7f838c-8f2b36e7-1b77-4c8c-b7cc-4700f
96ade05/tmp5oz3faq4/2334004a-fa87-41e6-9972-ac77bcb4f519/tmpwx_i9h7t.tmp', '--lastz_interval=3000000', '--markend', '--neighbor_proportion', '0.2', '--M', '10', '--step=3', '--ambiguous=iupac,100,100']
        Using 2 threads
        Error: No GPU device found!
        Traceback (most recent call last):
          File "/usr/local/lib/python3.6/dist-packages/toil/worker.py", line 368, in workerScript
            job._runner(jobGraph=jobGraph, jobStore=jobStore, fileStore=fileStore, defer=defer)
          File "/usr/local/lib/python3.6/dist-packages/cactus/shared/common.py", line 1369, in _runner
            super(RoundedJob, self)._runner(jobGraph=jobGraph, jobStore=jobStore, fileStore=fileStore, defer=defer)
          File "/usr/local/lib/python3.6/dist-packages/toil/job.py", line 1424, in _runner
            returnValues = self._run(jobGraph, fileStore)
          File "/usr/local/lib/python3.6/dist-packages/toil/job.py", line 1361, in _run
            return self.run(fileStore)
          File "/usr/local/lib/python3.6/dist-packages/cactus/preprocessor/lastzRepeatMasking/cactus_lastzRepeatMask.py", line 189, in run
            alignment = self.gpuRepeatMask(fileStore, targetFiles[0])
          File "/usr/local/lib/python3.6/dist-packages/cactus/preprocessor/lastzRepeatMasking/cactus_lastzRepeatMask.py", line 127, in gpuRepeatMask
            cactus_call(parameters=cmd, work_dir=alignment_dir)
          File "/usr/local/lib/python3.6/dist-packages/cactus/shared/common.py", line 1306, in cactus_call
            raise RuntimeError("Command {} exited {}: {}".format(call, process.returncode, out))
        RuntimeError: Command ['segalign_repeat_masker', '/PATH/TO/HAL/TMP/node-3b7fafc6-513c-4313-abfd-3c594a7f838c-8f2b36e7-1b77-4c8c-b7cc-4700f96ade05/tmp5oz3faq4/2334004a-fa87-41e6-9972-ac77bcb4f519/tmpwx_i9
h7t.tmp', '--lastz_interval=3000000', '--markend', '--neighbor_proportion', '0.2', '--M', '10', '--step=3', '--ambiguous=iupac,100,100'] exited 1: stdout=None
        [2020-10-27T15:06:43+0000] [MainThread] [E] [toil.worker] Exiting the worker because of a failed job on host node1f04
<=========
``` 

Is there something I'm missing in the configuration to run the container successfully?

Thank you for your help,
Andrea

**Comment by glennhickey** [comment]
I've never run the GPU image on singularity before.  I know that on docker, you need to pas `--gpus all` to `docker run` in order for it to detect the gpu nodes.  Perhaps there is an equivalent option for singularity?

**Comment by RenzoTale88** [comment]
@glennhickey that should be allowed by the flag ```--nv```. In fact, if I run nvidia-smi inside the container, I successfully see the list of GPU installed:
```
singularity exec --nv --bind $PWD:/mnt ./cactus_v1.2.3-gpu.sif nvidia-smi
INFO:    Convert SIF file to sandbox...
WARNING: underlay of /etc/localtime required more than 50 (95) bind mounts
WARNING: underlay of /usr/bin/nvidia-smi required more than 50 (291) bind mounts
Wed Oct 28 11:44:45 2020
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 418.40.04    Driver Version: 418.40.04    CUDA Version: 10.1     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  Tesla K80           Off  | 00000000:06:00.0 Off |                    0 |
| N/A   27C    P8    26W / 149W |     11MiB / 11441MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   1  Tesla K80           Off  | 00000000:07:00.0 Off |                    0 |
| N/A   33C    P8    30W / 149W |     11MiB / 11441MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   2  Tesla K80           Off  | 00000000:0A:00.0 Off |                    0 |
| N/A   25C    P8    26W / 149W |     11MiB / 11441MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   3  Tesla K80           Off  | 00000000:0B:00.0 Off |                    0 |
| N/A   33C    P8    30W / 149W |     11MiB / 11441MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   4  Tesla K80           Off  | 00000000:86:00.0 Off |                    0 |
| N/A   26C    P8    26W / 149W |     11MiB / 11441MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   5  Tesla K80           Off  | 00000000:87:00.0 Off |                    0 |
| N/A   33C    P8    29W / 149W |     11MiB / 11441MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   6  Tesla K80           Off  | 00000000:8A:00.0 Off |                    0 |
| N/A   28C    P8    27W / 149W |     11MiB / 11441MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   7  Tesla K80           Off  | 00000000:8B:00.0 Off |                    0 |
| N/A   33C    P8    29W / 149W |     11MiB / 11441MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+

+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
|  No running processes found                                                 |
+-----------------------------------------------------------------------------+
INFO:    Cleaning up image...
```

**Comment by glennhickey** [comment]
I just tried this on my desktop
```
singularity shell --nv docker://quay.io/comparative-genomics-toolkit/cactus:v1.2.3-gpu
```
and ran
```
cactus ./js.sing ./examples/evolverMammals.txt out.hal --realTimeLogging
```
and it seems to be working, notably:
```
[2020-10-28T09:24:44-0400] [MainThread] [I] [toil-rt] 2020-10-28 09:24:44.575886: Successfully ran the command: "segalign_repeat_masker /tmp/node-c799a1d6-0334-470d-a4c3-5cb3b53bd699-d8031482-3dd1-4895-b619-bcc9a43bbc59/tmpw6m7_a4e/27428c15-76d0-4c2a-914d-7ae5bfae5622/tmpl694db37.tmp --lastz_interval=3000000 --markend --neighbor_proportion 0.2 --M 10 --step=3 --ambiguous=iupac,100,100" in 2.619093656539917 seconds
```
and `nvidia-smi`
```
Singularity cactus:v1.2.3-gpu:~> nvidia-smi 
Wed Oct 28 09:23:59 2020       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 450.80.02    Driver Version: 450.80.02    CUDA Version: 11.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  GeForce GTX 105...  Off  | 00000000:01:00.0  On |                  N/A |
| 20%   45C    P8    N/A /  75W |    418MiB /  4038MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|    0   N/A  N/A      2472      G   /usr/lib/xorg/Xorg                 30MiB |
|    0   N/A  N/A      2984      G   /usr/bin/gnome-shell               47MiB |
|    0   N/A  N/A      4495      G   /usr/lib/xorg/Xorg                205MiB |
|    0   N/A  N/A      4925      G   /usr/bin/gnome-shell              101MiB |
|    0   N/A  N/A      9301      G   ...AAAAAAAAA= --shared-files       28MiB |
+-----------------------------------------------------------------------------+
```

The Cactus image is built against [cuda 10.2](https://github.com/ComparativeGenomicsToolkit/cactus/blob/master/Dockerfile.segalign#L19).  Perhaps the fact that you have an older cuda version (10.1) on your system is the issue?  I don't really have any other ideas beyond that there is somehow an incompatibility between the image and your system.  To check this, you could edit that line I linked to above to use 10.1 instead of 10.2, then run `build-tools/makeGpuDockerRelease` and select `N` when it asks you to upload to quay.  This will build you a local version of `docker://quay.io/comparative-genomics-toolkit/cactus:v1.2.3-gpu` that you can try.  Otherwise, next time I have a chance, I'll make a 10.1 system to test on to see if this is the issue.

**Comment by glennhickey** [comment]
that will build an image for segalign, which will be enough to test.

**Comment by RenzoTale88** [comment]
@glennhickey I've changed the dockerfile as follow:
```
FROM nvidia/cuda:10.1-devel as builder

# system dependencies are installed by ./installUbuntu.sh below, but we need sudo first
RUN apt-get -qq -y update && \
    apt-get -qq -y upgrade && \
    apt-get -qq -y install \
    sudo git

# Use the commit from the file
COPY build-tools/Segalign.commit /

# clone Segalign
RUN git clone https://github.com/ComparativeGenomicsToolkit/SegAlign.git --recursive /WGA_GPU && cd WGA_GPU && git checkout $(cat /Segalign.commit)

# build and install everything but cuda using the install script
RUN cd /WGA_GPU && rm -rf build && ./scripts/installUbuntu.sh -c && git rev-parse HEAD > /Segalign.commit

# Create a thinner final Docker image with only runtime dependencies
FROM nvidia/cuda:10.1-runtime

# Install runtime dependencies
RUN apt-get -qq -y update && \
    apt-get -qq -y upgrade && \
    apt-get -qq -y install \
    libkrb5-3 \
    libk5crypto3 \
    libboost-dev \
    libboost-program-options-dev \
    zlib1g \
    parallel

# copy all the binaries
COPY --from=builder /usr/local/bin /usr/local/bin

# copy the tbb shared library
COPY --from=builder /WGA_GPU/tbb*/lib/intel64/gcc*/lib* /usr/local/lib/

# add the library path
ENV LD_LIBRARY_PATH="/usr/local/lib/:${LD_LIBRARY_PATH}"

# remember that commit
COPY --from=builder /Segalign.commit /

# UCSC convention is to work in /data
RUN mkdir -p /data
WORKDIR /data
```
Then, after building a docker image, extracting it as a tar file and converting to singularity, I can start the software. However, I get the following error:
```
singularity exec --nv --bind $PWD:/mnt ../cactus_cuda10.1.sif segalign_repeat_masker chr16.fna --num_gpu 1
INFO:    Convert SIF file to sandbox...
WARNING: underlay of /etc/localtime required more than 50 (90) bind mounts
WARNING: underlay of /usr/bin/nvidia-smi required more than 50 (283) bind mounts
Using 2 threads
Using 1 GPU(s)
terminate called after throwing an instance of 'thrust::system::system_error'
  what():  parallel_for failed: cudaErrorInvalidDeviceFunction: invalid device function
INFO:    Cleaning up image...
```
This time it does recognize the GPU, but it fails. I'm guessing the problem is with the cuda libraries not being compatible with the software. I've dropped an email to our IT to ask for the installation of CUDA 10.2, hopefully that will fix the problem more easily.
Judt in case, can I as how can I build a GPU-enabled docker version of cactus locally?

Thanks again
Andrea

**Comment by RenzoTale88** [comment]
Ok ignore my previous comment, I've found the makeGpuDockerRelease script, tresting it now!

Andrea

**Comment by zhenzhenyang-psu** [comment]
hello, I had a similar issue with same error message:
"Error: No GPU device found"
See the detailed message attached. 


However, I did use cuda version 10.2. I wonder any clue for the failure. 

Also, I wonder if the HPC cluster we used is a centos7 based system, would this docker image not be able to work?


[PBS_cactus_4genomes_local_v7_gpuq.109638.e.txt](https://github.com/ComparativeGenomicsToolkit/cactus/files/5780305/PBS_cactus_4genomes_local_v7_gpuq.109638.e.txt)


In fact, I tried to install GPU version of cactus (SegAlign) manually by following this link:
https://github.com/ComparativeGenomicsToolkit/SegAlign
However, as the HPC cluster we used is Centos7 based. When I tried to compile it with the following command:
cmake -DCMAKE_BUILD_TYPE=Release -DTBB_ROOT=${PWD}/../tbb2019_20191006oss -DCMAKE_PREFIX_PATH=${PWD}/../tbb2019_20191006oss/cmake ..

an error occurred. 

https://github.com/gsneha26/SegAlign/issues/44

I am seeking help from here because I didn't get reply there.

Looking forward to a solution for GPU version of cactus!
thanks much,
Zhenzhen

**Comment by glennhickey** [comment]
Which command did you use to run cactus?

**Comment by zhenzhenyang-psu** [comment]
I used this:


module load singularity

module load cuda/10.2


export myRepository=$MYSCRATCH/tools/cactus_image

export containerImage=$myRepository/cactus_v1.2.3-gpu.sif


srun --export=ALL singularity exec $containerImage cactus  --workDir temp_workdir2 jobstore2 4genomes.tree.and.seq.in.txt  examples4genomes/4genomes.gpu.hal --binariesMode local


________________________________

**Comment by glennhickey** [comment]
Did you read [this comment upthread](https://github.com/ComparativeGenomicsToolkit/cactus/issues/339#issuecomment-717881466)?  It is important to use the `--nv` flag to enable your gpu.  Running `nvidia-smi` is also a good check.

**Comment by zhenzhenyang-psu** [comment]
Hi Glenn,
Thanks for your help.
I ran 'singularity exec --nv --bind $PWD:/mnt ./cactus_v1.2.3-gpu.sif nvidia-smi ' and had this error message:

INFO:    Could not find any nv files on this host!
FATAL:   "nvidia-smi": executable file not found in $PATH

So this means GPU is not successfully installed? I will ask the IT-support for this matter.
thanks,
Zhenzhen

**Comment by gsneha26** [comment]
You would need to reinstall the driver. try
'
sudo yum -y install epel-release
sudo yum -y install dkms
wget https://developer.download.nvidia.com/compute/cuda/10.2/Prod/local_installers/cuda-repo-rhel7-10-2-local-10.2.89-440.33.01-1.0-1.x86_64.rpm
sudo rpm -i cuda-repo-rhel7-10-2-local-10.2.89-440.33.01-1.0-1.x86_64.rpm
sudo yum clean all
sudo yum -y install nvidia-driver-latest-dkms cuda
sudo yum -y install cuda-drivers
'
