### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: '.nfs00000025f8adba0c0000004c'

### ISSUE THREAD

**Issue by metoru** [ComparativeGenomicsToolkit/cactus#350]
Hello
i try  to run cactus-preprocess with cromwell server ,the commad in the script file:
``` shell
cactus-preprocess ./jobstore --inPaths /sfs/cactus_prepared/762d515d-2872-435d-bf9b-fc9e1f0773b4/call-cactus_preprocess/inputs/test/simHuman.chr6 /sfs/cactus_prepared/762d515d-2872-435d-bf9b-fc9e1f0773b4/call-cactus_preprocess/inputs/test/simCow.chr6 /sfs/cactus_prepared/762d515d-2872-435d-bf9b-fc9e1f0773b4/call-cactus_preprocess/inputs/test/simDog.chr6  --outPaths simHuman.chr6.pp simCow.chr6.pp simDog.chr6.pp --realTimeLogging --logInfo --retryCount 0  --workDir .
```
It runs into this issue then gets stuck in reissuing jobs - is this a bug or is it an easy fix?
>[2020-11-12T08:01:19+0000] [MainThread] [I] [toil.leader] Job ended: 'CactusPreprocessor2' kind-CactusPreprocessor2/instance-rf4e8jjp
[2020-11-12T08:01:19+0000] [MainThread] [I] [toil.worker] Redirecting logging to /sfs/cactus_prepared/762d515d-2872-435d-bf9b-fc9e1f0773b4/call-cactus_preprocess/execution/node-43e91bf5-c87a-4acb-9d33-d2be1d8120d5-eb984481-90d5-4438-a0a3-c7c35a8f702b/tmpdkh9k87j/worker_log.txt
[2020-11-12T08:01:19+0000] [MainThread] [I] [toil.leader] Job ended: 'CactusPreprocessor2' kind-CactusPreprocessor2/instance-m6kkaw1t
[2020-11-12T08:01:19+0000] [MainThread] [I] [toil.leader] Issued job 'CactusPreprocessor' kind-CactusPreprocessor/instance-ofj76yvf with job batch system ID: 46 and cores: 1, disk: 1.6 G, and memory: 2.0 G
[2020-11-12T08:01:20+0000] [MainThread] [I] [toil.worker] Redirecting logging to /sfs/cactus_prepared/762d515d-2872-435d-bf9b-fc9e1f0773b4/call-cactus_preprocess/execution/node-43e91bf5-c87a-4acb-9d33-d2be1d8120d5-eb984481-90d5-4438-a0a3-c7c35a8f702b/tmpx3d2jq90/worker_log.txt
[2020-11-12T08:01:20+0000] [MainThread] [I] [toil.leader] Job ended: 'CactusPreprocessor' kind-CactusPreprocessor/instance-ofj76yvf
[2020-11-12T08:01:23+0000] [MainThread] [I] [toil.leader] Finished toil run successfully.
[2020-11-12T08:01:23+0000] [MainThread] [I] [toil.realtimeLogger] Stopping real-time logging server.
[2020-11-12T08:01:23+0000] [MainThread] [I] [toil.realtimeLogger] Joining real-time logging server thread.
Traceback (most recent call last):
  File "/usr/local/bin/cactus-preprocess", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.6/dist-packages/cactus/preprocessor/cactus_preprocessor.py", line 376, in main
    stageWorkflow(outputSequenceDir=None, configFile=options.configFile, inputSequences=inSeqPaths, toil=toil, restart=options.restart, outputSequences=outSeqPaths)
  File "/usr/local/lib/python3.6/dist-packages/cactus/preprocessor/cactus_preprocessor.py", line 288, in stageWorkflow
    outputSequenceIDs = toil.start(CactusPreprocessor(inputSequenceIDs, configNode))
  File "/usr/local/lib/python3.6/dist-packages/toil/common.py", line 848, in start
    self._shutdownBatchSystem()
  File "/usr/local/lib/python3.6/dist-packages/toil/common.py", line 1148, in _shutdownBatchSystem
    self._batchSystem.shutdown()
  File "/usr/local/lib/python3.6/dist-packages/toil/batchSystems/singleMachine.py", line 566, in shutdown
    BatchSystemSupport.workerCleanup(self.workerCleanupInfo)
  File "/usr/local/lib/python3.6/dist-packages/toil/batchSystems/abstractBatchSystem.py", line 371, in workerCleanup
    DeferredFunctionManager.cleanupWorker(workflowDir)
  File "/usr/local/lib/python3.6/dist-packages/toil/deferred.py", line 221, in cleanupWorker
    shutil.rmtree(os.path.join(stateDirBase, cls.STATE_DIR_STEM))
  File "/usr/lib/python3.6/shutil.py", line 486, in rmtree
    _rmtree_safe_fd(fd, path, onerror)
  File "/usr/lib/python3.6/shutil.py", line 444, in _rmtree_safe_fd
    onerror(os.unlink, fullname, sys.exc_info())
  File "/usr/lib/python3.6/shutil.py", line 442, in _rmtree_safe_fd
    os.unlink(name, dir_fd=topfd)
FileNotFoundError: [Errno 2] No such file or directory: '.nfs00000025f8adba0c0000004c'
>
Thanks,

**Comment by glennhickey** [comment]
Hmm, so I take it you're running a WDL through cromwell and are seeing this error then?  

I know that cromwell likes to make read-only files that I've needed `sudo` to delete.  It can come up in the tests (#255) but doesn't lead to a crash there -- just some files that trail in the directory cromwell is run from.  

Here it looks like there's a file within your work directory that toil can't delete.  In the tests, [these options](https://github.com/ComparativeGenomicsToolkit/cactus/blob/master/test/evolverTest.py#L106-L110) are passed to cromwell.  I'm not sure if they could help here, but it might be worth a try.

**Comment by metoru** [comment]
I added a few commands to the script ' dist-packages/toil/deferred.py' in the image "quay.io/comparative-genomics-toolkit/cactus:18d1df3e3fb4d9cf1c377d69778d3fbcce14cccc"  to  output a list of execute permissions for file or directory called '.nfs00000025cbf2b00200000074',Interestingly,The previous problem did not arise！I also don't know why?

the commands like this 
![image](https://user-images.githubusercontent.com/46242303/99035295-4a8f9280-25ba-11eb-91c2-bad223d5cd9d.png)
