### ISSUE TITLE
toil.batchSystems.singleMachine failure

### ISSUE THREAD

**Issue by AlisaGU** [ComparativeGenomicsToolkit/cactus#352]
Hi,
there is an error when I run the test script.
`cactus ./jobstore ./examples/evolverMammals.txt ./evolverMammals.hal --realTimeLogging`
Here is part of log:
```
[2020-11-16T17:01:31+0800] [MainThread] [I] [toil.worker] Redirecting logging to /tmp/node-a190fa75-f538-42be-a3c4-3f8f7577fb3d-e5378d27-b8c2-41f2-b1cf-b06d78663c37/tmpvcsqfqdw/worker_log.txt
[2020-11-16T17:01:31+0800] [MainThread] [I] [toil.worker] Redirecting logging to /tmp/node-a190fa75-f538-42be-a3c4-3f8f7577fb3d-e5378d27-b8c2-41f2-b1cf-b06d78663c37/tmpufsdpkj5/worker_log.txt
[2020-11-16T17:01:32+0800] [MainThread] [I] [toil.worker] Redirecting logging to /tmp/node-a190fa75-f538-42be-a3c4-3f8f7577fb3d-e5378d27-b8c2-41f2-b1cf-b06d78663c37/tmpxmaod01h/worker_log.txt
[2020-11-16T17:01:34+0800] [Thread-1  ] [E] [toil.batchSystems.singleMachine] Got exit code 1 (indicating failure) from job _toil_worker LastzRepeatMaskJob file:/picb/evolgen/users/gushanshan/software/Cactus/cactus-bin-v1.2.3/jobStore kind-LastzRepeatMaskJob/instance-mgetgooc.
[2020-11-16T17:01:34+0800] [MainThread] [W] [toil.leader] Job failed with exit value 1: 'LastzRepeatMaskJob' kind-LastzRepeatMaskJob/instance-mgetgooc
[2020-11-16T17:01:34+0800] [MainThread] [W] [toil.leader] The job seems to have left a log file, indicating failure: 'LastzRepeatMaskJob' kind-LastzRepeatMaskJob/instance-mgetgooc
[2020-11-16T17:01:34+0800] [MainThread] [W] [toil.leader] Log from job kind-LastzRepeatMaskJob/instance-mgetgooc follows:
=========>
	[2020-11-16T17:01:31+0800] [MainThread] [I] [toil.worker] ---TOIL WORKER OUTPUT LOG---
	[2020-11-16T17:01:31+0800] [MainThread] [I] [toil] Running Toil version 4.2.0-3aa1da130141039cb357efe36d7df9b9f6ae9b5b on host lih005.icb.ac.cn.
	[2020-11-16T17:01:31+0800] [MainThread] [I] [cactus.shared.common] Running the command ['cactus_fasta_fragments.py', '--fragment=200', '--step=100', '--origin=zero']
	[2020-11-16T17:01:32+0800] [MainThread] [I] [cactus.shared.common] Running the command ['cPecanLastz', 'tmpd08gpo0i.tmp[multiple][nameparse=darkspace]', 'tmppnfxtupn.tmp[nameparse=darkspace]', '--step=3', '--ambiguous=iupac,100,100', '--ungapped', '--queryhsplimit=keep,nowarn:1500', '--querydepth=keep,nowarn:53', '--format=general:name1,zstart1,end1,name2,zstart2+,end2+', '--markend']
	[2020-11-16T17:01:34+0800] [MainThread] [I] [cactus.shared.common] Running the command ['cactus_covered_intervals', '--origin=one', 'M=100', '--queryoffsets']
	Traceback (most recent call last):
	  File "/picb/evolgen/users/gushanshan/software/Cactus/cactus-bin-v1.2.3/venv/lib/python3.7/site-packages/toil/worker.py", line 368, in workerScript
	    job._runner(jobGraph=jobGraph, jobStore=jobStore, fileStore=fileStore, defer=defer)
	  File "/picb/evolgen/users/gushanshan/software/Cactus/cactus-bin-v1.2.3/venv/lib/python3.7/site-packages/cactus/shared/common.py", line 1369, in _runner
	    super(RoundedJob, self)._runner(jobGraph=jobGraph, jobStore=jobStore, fileStore=fileStore, defer=defer)
	  File "/picb/evolgen/users/gushanshan/software/Cactus/cactus-bin-v1.2.3/venv/lib/python3.7/site-packages/toil/job.py", line 1424, in _runner
	    returnValues = self._run(jobGraph, fileStore)
	  File "/picb/evolgen/users/gushanshan/software/Cactus/cactus-bin-v1.2.3/venv/lib/python3.7/site-packages/toil/job.py", line 1361, in _run
	    return self.run(fileStore)
	  File "/picb/evolgen/users/gushanshan/software/Cactus/cactus-bin-v1.2.3/venv/lib/python3.7/site-packages/cactus/preprocessor/lastzRepeatMasking/cactus_lastzRepeatMask.py", line 193, in run
	    maskedQuery = self.maskCoveredIntervals(fileStore, queryFile, alignment)
	  File "/picb/evolgen/users/gushanshan/software/Cactus/cactus-bin-v1.2.3/venv/lib/python3.7/site-packages/cactus/preprocessor/lastzRepeatMasking/cactus_lastzRepeatMask.py", line 162, in maskCoveredIntervals
	    cactus_call(infile=alignment, outfile=maskInfo, parameters=covered_call_cmd)
	  File "/picb/evolgen/users/gushanshan/software/Cactus/cactus-bin-v1.2.3/venv/lib/python3.7/site-packages/cactus/shared/common.py", line 1308, in cactus_call
	    raise RuntimeError("Command {} signaled {}: {}".format(call, signal.Signals(-process.returncode).name, out))
	RuntimeError: Command ['cactus_covered_intervals', '--origin=one', 'M=100', '--queryoffsets'] signaled SIGILL: stdout=None
	[2020-11-16T17:01:34+0800] [MainThread] [E] [toil.worker] Exiting the worker because of a failed job on host lih005.icb.ac.cn
<=========

```

Can you give me some tips?

Here is the complete log.
[LOG.txt.zip](https://github.com/ComparativeGenomicsToolkit/cactus/files/5546408/LOG.txt.zip)

**Comment by glennhickey** [comment]
It is crashing because `cactus_covered_intervals` is failing with `SIGILL` (illegal instruction) which suggests an incompatibility between this binary and your CPU architecture. 
```
RuntimeError: Command ['cactus_covered_intervals', '--origin=one', 'M=100', '--queryoffsets'] signaled SIGILL
```
The cactus binary releases and Dockerfiles are compiled with [-march=nehalem](https://en.wikipedia.org/wiki/Nehalem_(microarchitecture)), which we've found to be broadly compatible with both new and fairly old systems.  Do you know which type of CPU you are running on?

**Comment by AlisaGU** [comment]
Is it right?
```
Linux lih005.icb.ac.cn 3.10.0-1062.el7.x86_64 #1 SMP Wed Aug 7 18:08:02 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by AlisaGU** [comment]
Is it too old?

**Comment by glennhickey** [comment]
Yes, from what I can tell that's a "Clovertown" chip which is a few years older than Nehalem and is unfortunately not compatible with the Cactus binary release.  If you want to run Cactus on this system right now you will need to build it yourself.  

I will look into adding a version that supports this chipset in the next release.

**Comment by AlisaGU** [comment]
Thanks for your quick reply.
I will build it. :)

**Comment by cistarsa** [comment]
hello again. I'm wondering if this chip incompatibility issue would also explain the error I've been having when running the example data via docker on CHTC cluster:
```bash
[2020-12-01T06:33:53+0000] [Thread-1  ] [E] [toil.batchSystems.singleMachine] Got exit code 1 (indicating failure) from job _toil_worker LastzRepeatMaskJob file:/var/lib/condor/execute/slot1/dir_40127/evo_tigs2 kind-LastzRepeatMaskJob/instance-u0yrl050.
[2020-12-01T06:33:53+0000] [MainThread] [W] [toil.leader] The job seems to have left a log file, indicating failure: 'LastzRepeatMaskJob' kind-LastzRepeatMaskJob/instance-u0yrl050
[2020-12-01T06:33:53+0000] [MainThread] [W] [toil.jobGraph] Due to failure we are reducing the remaining retry count of job 'LastzRepeatMaskJob' kind-LastzRepeatMaskJob/instance-u0yrl050 with ID kind-LastzRepeatMaskJob/instance-u0yrl050 to 1
```

here's the complete [log](https://github.com/ComparativeGenomicsToolkit/cactus/files/5620677/cactus_out1.txt)

**Comment by glennhickey** [comment]
Yes, that is the exact same error.  Whenever you see `signaled SIGILL` in the log, cpu incompatibility is probably the reason.

**Comment by cistarsa** [comment]
Thank you, good to know! While I have your attention, could you recommend how much RAM I should request to align 4 genomes of 700-880MB size?

**Comment by glennhickey** [comment]
Older CPUs are supported in the "legacy" binaries available in the new release https://github.com/ComparativeGenomicsToolkit/cactus/releases/tag/v1.3.0
