### ISSUE TITLE
running my own data---AssertionError 

### ISSUE THREAD

**Issue by flzh628** [ComparativeGenomicsToolkit/cactus#355]
hello,

I have run test data successfully. However, when I use my own data, it reported an error. And the detail of the error, and seqFile are as follows. I want to know how to solve it ? Does my tree file not fit ? Thanks very much !

**the detail of the error:**

nohup: ignoring input
[2020-11-17T16:18:42+0800] [MainThread] [I] [cactus.progressive.projectWrapper] Using config from path /public/home/zhaoFL/software/cactus_env/lib/python3.7/site-packages/cactus/cactus_progressive_config.xml.
Traceback (most recent call last):
  File "/public/home/zhaoFL/software/cactus_env/bin/cactus", line 8, in <module>
    sys.exit(main())
  File "/public/home/zhaoFL/software/cactus_env/lib/python3.7/site-packages/cactus/progressive/cactus_progressive.py", line 386, in main
    runCactusProgressive(options)
  File "/public/home/zhaoFL/software/cactus_env/lib/python3.7/site-packages/cactus/progressive/cactus_progressive.py", line 402, in runCactusProgressive
    projWrapper.writeXml()
  File "/public/home/zhaoFL/software/cactus_env/lib/python3.7/site-packages/cactus/progressive/projectWrapper.py", line 76, in writeXml
    root=self.options.root)
  File "/public/home/zhaoFL/software/cactus_env/lib/python3.7/site-packages/cactus/progressive/cactus_createMultiCactusProject.py", line 263, in runCreateMultiCactusProject
    mcProj = createMCProject(tree, expTemplate, confTemplate, options)
  File "/public/home/zhaoFL/software/cactus_env/lib/python3.7/site-packages/cactus/progressive/cactus_createMultiCactusProject.py", line 49, in createMCProject
    fillInOutgroups(mcProj, options.outgroupNames, config, alignmentRootId)
  File "/public/home/zhaoFL/software/cactus_env/lib/python3.7/site-packages/cactus/progressive/cactus_createMultiCactusProject.py", line 87, in fillInOutgroups
    maxNumOutgroups=config.getMaxNumOutgroups())
  File "/public/home/zhaoFL/software/cactus_env/lib/python3.7/site-packages/cactus/progressive/outgroup.py", line 218, in greedy
    assert existingOutgroupDist[sinkName] == dist
AssertionError

**the seqFile:**

((CW19:0.06519,CW31:0.05929)1.000:0.03404,((CW17:0.09198,((CW23:0.08999,(CW14:0.07282,CW16:0.09857)1.000:0.03932)1.000:0.01487,((CW12:0.03106,CW13:0.03393)1.000:0.07818,(((NH281:0.11495,CW03:0.11552)1.000:0.01330,((NH188:0.10853,(CW10:0.03726,(CW06:0.05557,CW07:0.04640)1.000:0.02201)1.000:0.05229)1.000:0.01570,(CW34:0.12460,((CW36:0.07439,(CW09:0.02954,CW11:0.02264)1.000:0.04878)1.000:0.03408,(CW35:0.10466,(CW33:0.13401,CW37:0.10279)1.000:0.01587)1.000:0.01207)0.860:0.00895)1.000:0.01359)1.000:0.00819)0.989:0.01129,AAA:0.04797)1.000:0.00872)1.000:0.00565)0.988:0.00502)1.000:0.00654,((CW22:0.08614,(CW18:0.06362,(CW08:0.04768,(CW05:0.04082,CW15:0.04262)1.000:0.01090)1.000:0.01622)1.000:0.01975)1.000:0.00800,CW32:0.09174)0.576:0.00523)1.000:0.00596,((CW01:0.05921,CW02:0.05760)1.000:0.03912,CW21:0.08017)0.957:0.00598);

CW01 ./cw_try/CW01.soft_masked.fa
CW02 ./cw_try/CW02.soft_masked.fa
CW03 ./cw_try/CW03.soft_masked.fa
CW05 ./cw_try/CW05.soft_masked.fa
CW06 ./cw_try/CW06.soft_masked.fa
CW07 ./cw_try/CW07.soft_masked.fa
CW08 ./cw_try/CW08.soft_masked.fa
CW09 ./cw_try/CW09.soft_masked.fa
CW10 ./cw_try/CW10.soft_masked.fa
CW11 ./cw_try/CW11.soft_masked.fa
CW12 ./cw_try/CW12.soft_masked.fa
CW13 ./cw_try/CW13.soft_masked.fa
CW14 ./cw_try/CW14.soft_masked.fa
CW15 ./cw_try/CW15.soft_masked.fa
CW16 ./cw_try/CW16.soft_masked.fa
CW17 ./cw_try/CW17.soft_masked.fa
CW18 ./cw_try/CW18.soft_masked.fa
CW19 ./cw_try/CW19.soft_masked.fa
CW21 ./cw_try/CW21.soft_masked.fa
CW22 ./cw_try/CW22.soft_masked.fa
CW23 ./cw_try/CW23.soft_masked.fa
CW31 ./cw_try/CW31.soft_masked.fa
CW32 ./cw_try/CW32.soft_masked.fa
CW33 ./cw_try/CW33.soft_masked.fa
CW34 ./cw_try/CW34.soft_masked.fa
CW35 ./cw_try/CW35.soft_masked.fa
CW36 ./cw_try/CW36.soft_masked.fa
CW37 ./cw_try/CW37.soft_masked.fa
*NH188 ./cw_try/NH188.soft_masked.fa
*AAA ./cw_try/AAA.soft_masked.fa
NH281 ./cw_try/NH281.soft_masked.fa

**Comment by glennhickey** [comment]
The problem is the internal node labels on your tree.  Cactus doesn't always properly support them (#324).  But even when that's fixed they would have to be unique.  There should, of course, be a more reasonable error message in this case.  To fix now, make sure only leaves are labeled in your input Newick tree. 

By internal node labels, I'm referring to the numbers between **)** and **:**

((CW19:0.06519,CW31:0.05929)**1.000**:0.03404,((CW17:0.09198,((CW23:0.08999,(CW14:0.07282,CW16:0.09857)**1.000**:0.03932)**1.000**:0.01487,((CW12:0.03106,CW13:0.03393)**1.000**:0.07818  **etc**

I've tried removing them from your tree and this error goes away.

**Comment by flzh628** [comment]
Yeah, I have corrected it and now the program is running. Thanks very much !
