### ISSUE TITLE
cactus stopped an RuntimeError with cactus_bar

### ISSUE THREAD

**Issue by TUANNN518** [ComparativeGenomicsToolkit/cactus#357]
Hi:
I run the cactus using 18 ~300M genome, after 3 days, it stopped.
I found lots of RuntimeError in the log file, almost the 'cactus_bar' error:
raise RuntimeError("Command {} exited {}: {}".format(call, process.returncode, out))
	RuntimeError: Command ['cactus_bar', '--logLevel', 'INFO', '--cactusDisk', '<st_kv_database_conf type="kyoto_tycoon">\n\t\t\t<kyoto_tycoon database_dir="fakepath" host="192.168.1.143" port="8032" />\n\t\t</st_kv_database_conf>\n\t', '--maximumLength', '1000000.0', '--spanningTrees', '5', '--gapGamma', '0.0', '--matchGamma', '0.2', '--splitMatrixBiggerThanThis', '3000', '--anchorMatrixBiggerThanThis', '500', '--repeatMaskMatrixBiggerThanThis', '500', '--diagonalExpansion', '20', '--constraintDiagonalTrim', '14', '--minimumDegree', '2', '--minimumIngroupDegree', '1', '--minimumOutgroupDegree', '0', '--pruneOutStubAlignments', '--alignAmbiguityCharacters', '--useProgressiveMerging', '--largeEndSize', '5000', '--minimumSizeToRescue', '100', '--minimumCoverageToRescue', '0.5', '--minimumNumberOfSpecies', '1'] exited 128: stdout=
	[2020-11-17T17:27:09+0800] [MainThread] [E] [toil.worker] Exiting the worker because of a failed job on host localhost.localdomain

Here is my command:
nohup cactus --workDir /data/share_data/genome/whole_genome_align/1.cactus_result/18samples/workdir --stats /data/share_data/genome/whole_genome_align/1.cactus_result/18samples/jobstore /data/share_data/genome/whole_genome_align/18samples/18sample_for_cactus.txt /data/share_data/genome/whole_genome_align/1.cactus_result/18samples/18samples.hal&

Is the error due to CPU or memory? Because I run other software at the same time.
Now I add the --restart command, and cactus is running now. I don't know if it will stop again.

Thanks.

**Comment by glennhickey** [comment]
There's not enough information in the log snippet you posted to tell what's going on.  Running out of memory is definitely a possibility, though.

**Comment by TUANNN518** [comment]
> There's not enough information in the log snippet you posted to tell what's going on. Running out of memory is definitely a possibility, though.

Thanks,  I add the --restart command, and here the new error:
[2020-11-19T09:56:19+0800] [MainThread] [W] [toil.leader] Log from job kind-CactusHalGeneratorUpWrapper/instance-l9x_b6om follows:
=========>
	[2020-11-19T09:56:18+0800] [MainThread] [I] [toil.worker] ---TOIL WORKER OUTPUT LOG---
	[2020-11-19T09:56:18+0800] [MainThread] [I] [toil] Running Toil version 4.2.0-3aa1da130141039cb357efe36d7df9b9f6ae9b5b on host localhost.localdomain.
	Traceback (most recent call last):
	  File "/home/genome/tools/cactus-bin-v1.2.3/venv/lib/python3.6/site-packages/toil/worker.py", line 364, in workerScript
	    with fileStore.open(job):
	  File "/usr/lib64/python3.6/contextlib.py", line 81, in __enter__
	    return next(self.gen)
	  File "/home/genome/tools/cactus-bin-v1.2.3/venv/lib/python3.6/site-packages/toil/fileStores/nonCachingFileStore.py", line 59, in open
	    self._removeDeadJobs(self.workDir)
	  File "/home/genome/tools/cactus-bin-v1.2.3/venv/lib/python3.6/site-packages/toil/fileStores/nonCachingFileStore.py", line 186, in _removeDeadJobs
	    if not process_name_exists(nodeInfo, jobState['jobProcessName']):
	  File "/home/genome/tools/cactus-bin-v1.2.3/venv/lib/python3.6/site-packages/toil/lib/threading.py", line 313, in process_name_exists
	    nameFD = os.open(nameFileName, os.O_RDONLY)
	FileNotFoundError: [Errno 2] No such file or directory: '/data/share_data/genome/whole_genome_align/1.cactus_result/18samples/workdir/node-670ee851-7d12-442d-873f-75c2673999da-d87eb9ff-6a1a-480f-8a07-8b0007f85552/tmp3s2ph99j'
	[2020-11-19T09:56:19+0800] [MainThread] [E] [toil.worker] Exiting the worker because of a failed job on host localhost.localdomain
<=========

**Comment by glennhickey** [comment]
Sorry, I'm still not sure what's going on.  As the error says, it's failling to load a temporary file.  Perhaps it's running out of disk, though in my experience that usually manifests with a more explicit message.

**Comment by xiaolongtu** [comment]
HI， I  have met the same problem , Do you got the way to solve it ?   @glennhickey @TUANNN518 
......................................................
......................................................
2021-03-18 17:20:49.488538: Running the command: "cactus_fasta_softmask_intervals.py --origin=one /gpfs/home/tuxl/project/20210106_kangaroo_denovo/03.evo/01.result/result/cactus/workdir/node-eca5af6e-7a7c-4400-a5e5-52a475662774-e10f5528880c419688c859bb88739f3d/tmpfbu47kxk/d3bb3511-ec3e-41f2-a9c0-3d07412fcf9f/tmgevnf_f/node-d93dfd25-a718-4bdd-bdc7-05586f25f61e-e10f5528880c419688c859bb88739f3d/tmpq0te_a2d/adf2861a-050e-44bd-9638-954ff2392595/tmpzkk7wiz7.tmp"
2021-03-18 17:20:49.615369: Successfully ran: "cactus_fasta_softmask_intervals.py --origin=one /gpfs/home/tuxl/project/20210106_kangaroo_denovo/03.evo/01.result/result/cactus/workdir/node-eca5af6e-7a7c-4400-a5e5-52a475662774-e10f5528880c419688c859bb88739f3d/tmpfbu47kxk/d3bb3511-ec3e-41f2-a9c0-3d07412fcf9f/tmgevnf_f/node-d93dfd25-a718-4bdd-bdc7-05586f25f61e-e10f5528880c419688c859bb88739f3d/tmpq0te_a2d/adf2861a-050e-44bd-9638-954ff2392595/tmpzkk7wiz7.tmp" in 0.1143 seconds
Got exit code 1 (indicating failure) from job _toil_worker toil_call_preprocess file:/gpfs/home/tuxl/project/20210106_kangaroo_denovo/03.evo/01.result/result/cactus/jobstore kind-toil_call_preprocess/instance-d0l22oq4.
Job failed with exit value 1: 'toil_call_preprocess' kind-toil_call_preprocess/instance-d0l22oq4
The job seems to have left a log file, indicating failure: 'toil_call_preprocess' kind-toil_call_preprocess/instance-d0l22oq4
Log from job kind-toil_call_preprocess/instance-d0l22oq4 follows:
=========>
	rkdir/node-eca5af6e-7a7c-4400-a5e5-52a475662774-e10f5528880c419688c859bb88739f3d/tmpfbu47kxk/d3bb3511-ec3e-41f2-a9c0-3d07412fcf9f/tmgevnf_f/node-d93dfd25-a718-4bdd-bdc7-05586f25f61e-e10f5528880c419688c859bb88739f3d/tmpc_zuc8vs/worker_log.txt
	[2021-03-18T16:58:50+0800] [MainThread] [I] [toil.worker] Redirecting logging to 
......................................................
......................................................
'LastzRepeatMaskJob' kind-LastzRepeatMaskJob/instance-2fe0n4e0, 'LastzRepeatMaskJob' kind-LastzRepeatMaskJob/instance-xjsjsh5y, 'LastzRepeatMaskJob' kind-LastzRepeatMaskJob/instance-7y96x2w5, 'LastzRepeatMaskJob' kind-LastzRepeatMaskJob/instance-340xmqcv, 'LastzRepeatMaskJob' kind-LastzRepeatMaskJob/instance-w2qiibq2
	Traceback (most recent call last):
	  File "/gpfs/home/tuxl/software/genome/cactus-bin-v1.3.0/venv/lib/python3.6/site-packages/toil/worker.py", line 368, in workerScript
	    job._runner(jobGraph=jobGraph, jobStore=jobStore, fileStore=fileStore, defer=defer)
	  File "/gpfs/home/tuxl/software/genome/cactus-bin-v1.3.0/venv/lib/python3.6/site-packages/toil/job.py", line 1424, in _runner
	    returnValues = self._run(jobGraph, fileStore)
	  File "/gpfs/home/tuxl/software/genome/cactus-bin-v1.3.0/venv/lib/python3.6/site-packages/toil/job.py", line 1361, in _run
	    return self.run(fileStore)
	  File "/gpfs/home/tuxl/software/genome/cactus-bin-v1.3.0/venv/lib/python3.6/site-packages/toil/job.py", line 1565, in run
	    rValue = userFunction(*((self,) + tuple(self._args)), **self._kwargs)
	  File "/gpfs/home/tuxl/software/genome/cactus-bin-v1.3.0/venv/lib/python3.6/site-packages/cactus/progressive/cactus_prepare.py", line 770, in toil_call_preprocess
	    cactus_call(parameters=cmd)
	  File "/gpfs/home/tuxl/software/genome/cactus-bin-v1.3.0/venv/lib/python3.6/site-packages/cactus/shared/common.py", line 1357, in cactus_call
	    raise RuntimeError("Command {} exited {}: {}".format(call, process.returncode, out))
	RuntimeError: Command ['cactus-preprocess', '/gpfs/home/tuxl/project/20210106_kangaroo_denovo/03.evo/01.result/result/cactus/workdir/node-eca5af6e-7a7c-4400-a5e5-52a475662774-e10f5528880c419688c859bb88739f3d/tmpfbu47kxk/d3bb3511-ec3e-41f2-a9c0-3d07412fcf9f/tmgevnf_f/js', '--inPaths', '/gpfs/home/tuxl/project/20210106_kangaroo_denovo/03.evo/01.result/result/cactus/fa/G.gallus.sm.fa', '--outPaths', 'G.gallus.sm.fa', '--workDir', '/gpfs/home/tuxl/project/20210106_kangaroo_denovo/03.evo/01.result/result/cactus/workdir/node-eca5af6e-7a7c-4400-a5e5-52a475662774-e10f5528880c419688c859bb88739f3d/tmpfbu47kxk/d3bb3511-ec3e-41f2-a9c0-3d07412fcf9f/tmgevnf_f', '--maxCores', '200', '--maxDisk', '3.9 T', '--maxMemory', '500.0 G', '--realTimeLogging', '--logInfo', '--retryCount', '0', '--binariesMode', 'local'] exited 1: stdout=None
	[2021-03-18T17:21:08+0800] [MainThread] [E] [toil.worker] Exiting the worker because of a failed job on host cu54
