### ISSUE TITLE
Error in the log file

### ISSUE THREAD

**Issue by TUANNN518** [ComparativeGenomicsToolkit/cactus#358]
I found the error in the log file:
[2020-11-19T09:56:19+0800] [MainThread] [W] [toil.leader] Log from job kind-CactusHalGeneratorUpWrapper/instance-l9x_b6om follows:
=========>
	[2020-11-19T09:56:18+0800] [MainThread] [I] [toil.worker] ---TOIL WORKER OUTPUT LOG---
	[2020-11-19T09:56:18+0800] [MainThread] [I] [toil] Running Toil version 4.2.0-3aa1da130141039cb357efe36d7df9b9f6ae9b5b on host localhost.localdomain.
	Traceback (most recent call last):
	  File "/home/genome/tools/cactus-bin-v1.2.3/venv/lib/python3.6/site-packages/toil/worker.py", line 364, in workerScript
	    with fileStore.open(job):
	  File "/usr/lib64/python3.6/contextlib.py", line 81, in __enter__
	    return next(self.gen)
	  File "/home/genome/tools/cactus-bin-v1.2.3/venv/lib/python3.6/site-packages/toil/fileStores/nonCachingFileStore.py", line 59, in open
	    self._removeDeadJobs(self.workDir)
	  File "/home/genome/tools/cactus-bin-v1.2.3/venv/lib/python3.6/site-packages/toil/fileStores/nonCachingFileStore.py", line 186, in _removeDeadJobs
	    if not process_name_exists(nodeInfo, jobState['jobProcessName']):
	  File "/home/genome/tools/cactus-bin-v1.2.3/venv/lib/python3.6/site-packages/toil/lib/threading.py", line 313, in process_name_exists
	    nameFD = os.open(nameFileName, os.O_RDONLY)
	FileNotFoundError: [Errno 2] No such file or directory: '/data/share_data/genome/whole_genome_align/1.cactus_result/18samples/workdir/node-670ee851-7d12-442d-873f-75c2673999da-d87eb9ff-6a1a-480f-8a07-8b0007f85552/tmp3s2ph99j'
	[2020-11-19T09:56:19+0800] [MainThread] [E] [toil.worker] Exiting the worker because of a failed job on host localhost.localdomain
<=========

Cactus is running now, but it stopped with no result befor, I use --restart to run continue.
what is the error mean? Is it the stop reason?

**Comment by Rusfell** [comment]
Hi， I have met the same problem , Do you got the way to solve it ?
