### ISSUE TITLE
error with "config.pickle" file non-exist

### ISSUE THREAD

**Issue by WeiWei1112** [ComparativeGenomicsToolkit/cactus#36]
Hi,
Lately I am stuck in the following error while I am testing the example data:

`INFO:toil.lib.bioio:Root` logger is at level 'INFO', 'toil' logger at level 'INFO'.
INFO:toil.lib.bioio:Logging to file 'try.log'.
INFO:toil.lib.bioio:Root logger is at level 'INFO', 'toil' logger at level 'INFO'.
INFO:toil.lib.bioio:Logging to file 'try.log'.
Traceback (most recent call last):
  File "/home/apps/software/cactus/20180705-IGB-gcc-4.9.4-Python-2.7.13/cactus_env/bin/cactus", line 11, in <module>
    sys.exit(main())
  File "/home/apps/software/cactus/20180705-IGB-gcc-4.9.4-Python-2.7.13/cactus_env/lib/python2.7/site-packages/cactus/progressive/cactus_progressive.py", line 447, in main
    with Toil(options) as toil:
  File "/home/apps/software/cactus/20180705-IGB-gcc-4.9.4-Python-2.7.13/cactus_env/lib/python2.7/site-packages/toil/common.py", line 714, in __enter__
    jobStore.resume()
  File "/home/apps/software/cactus/20180705-IGB-gcc-4.9.4-Python-2.7.13/cactus_env/lib/python2.7/site-packages/toil/jobStores/fileJobStore.py", line 90, in resume
    super(FileJobStore, self).resume()
  File "/home/apps/software/cactus/20180705-IGB-gcc-4.9.4-Python-2.7.13/cactus_env/lib/python2.7/site-packages/toil/jobStores/abstractJobStore.py", line 156, in resume
    with self.readSharedFileStream('config.pickle') as fileHandle:
  File "/home/apps/software/Python/2.7.13-IGB-gcc-4.9.4/lib/python2.7/contextlib.py", line 17, in __enter__
    return self.gen.next()
  File "/home/apps/software/cactus/20180705-IGB-gcc-4.9.4-Python-2.7.13/cactus_env/lib/python2.7/site-packages/toil/jobStores/fileJobStore.py", line 400, in readSharedFileStream
    raise NoSuchFileException(sharedFileName,sharedFileName)
toil.jobStores.abstractJobStore.NoSuchFileException: File 'config.pickle' (config.pickle) does not exist`

I really don't know where this config.pickle file could come from. 
The command I ran is
`cactus --logFile try.log --binariesMode local --restart output/ seqfile try.hal`
Anyone has ideas? Thanks.

Wei Wei

**Comment by joelarmstrong** [comment]
Hi Wei Wei,

I think the jobstore directory you specified (`output/`) may have already existed before you ran cactus. The jobstore directory is meant to be a non-existent directory where we can store temporary files during the workflow.

So something like ` cactus --logFile try.log --binariesMode local new_jobstore seqfile try.hal` might work.
