### ISSUE TITLE
Uncaught exception

### ISSUE THREAD

**Issue by StanQiu** [ComparativeGenomicsToolkit/cactus#364]
Dear authors,

I tried to run cactus on our Torque system with the following setting ( I am able to finish the test example (mammals)). However I got an uncaught exception (see below) and failed to finish the alignment. Would you be so kind to point out how to resolve this? 

`qsub -W group_list=ku_00039 -A ku_00039 -l nodes=1:ppn=30,mem=520gb,walltime=60:00:00 two_ants_cactus.sh
`
two_ants_cactus.sh
`cactus ./jobStore ./two_ants.txt ./two_ants.hal --batchSystem Torque --defaultDisk 20G --defaultMemory 12G --defaultCores 4 --restart --realTimeLogging
`
Part of the errors
=========>
        [2020-12-01T14:10:30+0100] [MainThread] [I] [toil.worker] ---TOIL WORKER OUTPUT LOG---
        [2020-12-01T14:10:30+0100] [MainThread] [I] [toil] Running Toil version 4.2.0-3aa1da130141039cb357efe36d7df9b9f6ae9b5b on host g-01-c0014.
        [2020-12-01T14:10:31+0100] [MainThread] [I] [toil.lib.bioio] Alignments file: /tmp/node-e17d134b-adc2-4d84-a57f-946f1987d38a-f24dccde-57f0-4aeb-a555-331676af3ba9/tmp4_vc8x_k/1ccb4e60-c4f4-4870-8840-eee01a5ea043/tmpkc4au8vs.tmp
        [2020-12-01T14:10:33+0100] [MainThread] [I] [cactus.shared.common] Running the command ['cactus_caf', '--logLevel', 'INFO', '--alignments', '/tmp/node-e17d134b-adc2-4d84-a57f-946f1987d38a-f24dccde-57f0-4aeb-a555-331676af3ba9/tmp4_vc8x_k/1ccb4e60-c4f4-4870-8840-eee01a5ea043/tmpkc4au8vs.tmp', '--cactusDisk', '<st_kv_database_conf type="kyoto_tycoon">\n\t\t\t<kyoto_tycoon database_dir="fakepath" host="10.45.12.133" port="7379" />\n\t\t</st_kv_database_conf>\n\t', '--secondaryAlignments', '/tmp/node-e17d134b-adc2-4d84-a57f-946f1987d38a-f24dccde-57f0-4aeb-a555-331676af3ba9/tmp4_vc8x_k/1ccb4e60-c4f4-4870-8840-eee01a5ea043/tmp84cqokc7.tmp', '--annealingRounds', '128', '--deannealingRounds', '2 8', '--trim', '0 0', '--lastzArguments', '--step=1 --ambiguous=iupac,100,100 --ydrop=3000', '--minimumTreeCoverage', '0.0', '--blockTrim', '5.0', '--minimumDegree', '2', '--minimumSequenceLengthForBlast', '30', '--minimumIngroupDegree', '1', '--minimumOutgroupDegree', '0', '--alignmentFilter', 'filterSecondariesByMultipleSpecies', '--maxAdjacencyComponentSizeRatio', '50.0', '--realign', '--realignArguments', '--gapGamma 0.0 --matchGamma 0.9 --diagonalExpansion 4 --splitMatrixBiggerThanThis 10 --constraintDiagonalTrim 0 --alignAmbiguityCharacters --splitIndelsLongerThanThis 99', '--phylogenyNumTrees', '30', '--phylogenyRootingMethod', 'bestRecon', '--phylogenyScoringMethod', 'reconCost', '--phylogenyBreakpointScalingFactor', '1.0', '--phylogenySkipSingleCopyBlocks', '--phylogenyMaxBaseDistance', '100', '--phylogenyMaxBlockDistance', '50', '--phylogenyTreeBuildingMethod', 'guidedNeighborJoining,splitDecomposition', '--phylogenyCostPerDupPerBase', '0.00', '--phylogenyCostPerLossPerBase', '0.02', '--referenceEventHeader', 'Anc0', '--phylogenyDoSplitsWithSupportHigherThanThisAllAtOnce', '0.44', '--numTreeBuildingThreads', '2', '--minimumBlockDegreeToCheckSupport', '10', '--minimumBlockHomologySupport', '0.05', '--removeRecoverableChains', 'unequalNumberOfIngroupCopies', '--minimumNumberOfSpecies', '1', '--maxRecoverableChainsIterations', '5', '--maxRecoverableChainLength', '500000', '--phylogenyHomologyUnitType', 'chain', '--phylogenyDistanceCorrectionMethod', 'jukesCantor', '--minLengthForChromosome', '1000000', '--proportionOfUnalignedBasesForNewChromosome', '0.8', '--maximumMedianSequenceLengthBetweenLinkedEnds', '1000']
        [2020-12-01T14:10:33+0100] [MainThread] [I] [toil-rt] 2020-12-01 14:10:33.232881: Running the command: "cactus_caf --logLevel INFO --alignments /tmp/node-e17d134b-adc2-4d84-a57f-946f1987d38a-f24dccde-57f0-4aeb-a555-331676af3ba9/tmp4_vc8x_k/1ccb4e60-c4f4-4870-8840-eee01a5ea043/tmpkc4au8vs.tmp --cactusDisk <st_kv_database_conf type="kyoto_tycoon">
                                <kyoto_tycoon database_dir="fakepath" host="10.45.12.133" port="7379" />
                        </st_kv_database_conf>
                 --secondaryAlignments /tmp/node-e17d134b-adc2-4d84-a57f-946f1987d38a-f24dccde-57f0-4aeb-a555-331676af3ba9/tmp4_vc8x_k/1ccb4e60-c4f4-4870-8840-eee01a5ea043/tmp84cqokc7.tmp --annealingRounds 128 --deannealingRounds 2 8 --trim 0 0 --lastzArguments --step=1 --ambiguous=iupac,100,100 --ydrop=3000 --minimumTreeCoverage 0.0 --blockTrim 5.0 --minimumDegree 2 --minimumSequenceLengthForBlast 30 --minimumIngroupDegree 1 --minimumOutgroupDegree 0 --alignmentFilter filterSecondariesByMultipleSpecies --maxAdjacencyComponentSizeRatio <...> -proportionOfUnalignedBasesForNewChromosome 0.8 --maximumMedianSequenceLengthBetweenLinkedEnds 1000"
        Flower disk name : <st_kv_database_conf type="kyoto_tycoon">
                                <kyoto_tycoon database_dir="fakepath" host="10.45.12.133" port="7379" />
                        </st_kv_database_conf>

        Exception: ST_KV_DATABASE_EXCEPTION: Opening connection to host: 10.45.12.133 with error: network error
        Uncaught exception
        Traceback (most recent call last):
          File "/home/projects/ku_00039/apps/miniconda3/lib/python3.8/site-packages/toil/worker.py", line 368, in workerScript
            job._runner(jobGraph=jobGraph, jobStore=jobStore, fileStore=fileStore, defer=defer)
          File "/home/projects/ku_00039/apps/miniconda3/lib/python3.8/site-packages/cactus/shared/common.py", line 1369, in _runner
            super(RoundedJob, self)._runner(jobGraph=jobGraph, jobStore=jobStore, fileStore=fileStore, defer=defer)
          File "/home/projects/ku_00039/apps/miniconda3/lib/python3.8/site-packages/toil/job.py", line 1424, in _runner
            returnValues = self._run(jobGraph, fileStore)
          File "/home/projects/ku_00039/apps/miniconda3/lib/python3.8/site-packages/toil/job.py", line 1361, in _run
            return self.run(fileStore)
          File "/home/projects/ku_00039/apps/miniconda3/lib/python3.8/site-packages/cactus/pipeline/cactus_workflow.py", line 816, in run
            self.runCactusCafInWorkflow(alignmentFile=alignments, secondaryAlignmentFile=secondaryAlignments, fileStore=fileStore,
          File "/home/projects/ku_00039/apps/miniconda3/lib/python3.8/site-packages/cactus/pipeline/cactus_workflow.py", line 750, in runCactusCafInWorkflow
            messages = runCactusCaf(cactusDiskDatabaseString=self.cactusDiskDatabaseString,
          File "/home/projects/ku_00039/apps/miniconda3/lib/python3.8/site-packages/cactus/shared/common.py", line 421, in runCactusCaf
            masterMessages = cactus_call(stdin_string=flowerNames, check_output=True,
          File "/home/projects/ku_00039/apps/miniconda3/lib/python3.8/site-packages/cactus/shared/common.py", line 1306, in cactus_call
            raise RuntimeError("Command {} exited {}: {}".format(call, process.returncode, out))
        RuntimeError: Command ['cactus_caf', '--logLevel', 'INFO', '--alignments', '/tmp/node-e17d134b-adc2-4d84-a57f-946f1987d38a-f24dccde-57f0-4aeb-a555-331676af3ba9/tmp4_vc8x_k/1ccb4e60-c4f4-4870-8840-eee01a5ea043/tmpkc4au8vs.tmp', '--cactusDisk', '<st_kv_database_conf type="kyoto_tycoon">\n\t\t\t<kyoto_tycoon database_dir="fakepath" host="10.45.12.133" port="7379" />\n\t\t</st_kv_database_conf>\n\t', '--secondaryAlignments', '/tmp/node-e17d134b-adc2-4d84-a57f-946f1987d38a-f24dccde-57f0-4aeb-a555-331676af3ba9/tmp4_vc8x_k/1ccb4e60-c4f4-4870-8840-eee01a5ea043/tmp84cqokc7.tmp', '--annealingRounds', '128', '--deannealingRounds', '2 8', '--trim', '0 0', '--lastzArguments', '--step=1 --ambiguous=iupac,100,100 --ydrop=3000', '--minimumTreeCoverage', '0.0', '--blockTrim', '5.0', '--minimumDegree', '2', '--minimumSequenceLengthForBlast', '30', '--minimumIngroupDegree', '1', '--minimumOutgroupDegree', '0', '--alignmentFilter', 'filterSecondariesByMultipleSpecies', '--maxAdjacencyComponentSizeRatio', '50.0', '--realign', '--realignArguments', '--gapGamma 0.0 --matchGamma 0.9 --diagonalExpansion 4 --splitMatrixBiggerThanThis 10 --constraintDiagonalTrim 0 --alignAmbiguityCharacters --splitIndelsLongerThanThis 99', '--phylogenyNumTrees', '30', '--phylogenyRootingMethod', 'bestRecon', '--phylogenyScoringMethod', 'reconCost', '--phylogenyBreakpointScalingFactor', '1.0', '--phylogenySkipSingleCopyBlocks', '--phylogenyMaxBaseDistance', '100', '--phylogenyMaxBlockDistance', '50', '--phylogenyTreeBuildingMethod', 'guidedNeighborJoining,splitDecomposition', '--phylogenyCostPerDupPerBase', '0.00', '--phylogenyCostPerLossPerBase', '0.02', '--referenceEventHeader', 'Anc0', '--phylogenyDoSplitsWithSupportHigherThanThisAllAtOnce', '0.44', '--numTreeBuildingThreads', '2', '--minimumBlockDegreeToCheckSupport', '10', '--minimumBlockHomologySupport', '0.05', '--removeRecoverableChains', 'unequalNumberOfIngroupCopies', '--minimumNumberOfSpecies', '1', '--maxRecoverableChainsIterations', '5', '--maxRecoverableChainLength', '500000', '--phylogenyHomologyUnitType', 'chain', '--phylogenyDistanceCorrectionMethod', 'jukesCantor', '--minLengthForChromosome', '1000000', '--proportionOfUnalignedBasesForNewChromosome', '0.8', '--maximumMedianSequenceLengthBetweenLinkedEnds', '1000'] exited 128: stdout=
        [2020-12-01T14:10:33+0100] [MainThread] [E] [toil.worker] Exiting the worker because of a failed job on host g-01-c0014
<=========
[2020-12-01T14:10:35+0100] [MainThread] [W] [toil.jobGraph] Due to failure we are reducing the remaining retry count of job 'CactusCafWrapper' kind-CactusCafWrapper/instance-566_8yxk with ID kind-CactusCafWrapper/instance-566_8yxk to 3
[2020-12-01T14:10:35+0100] [MainThread] [I] [toil.leader] Issued job 'CactusCafWrapper' kind-CactusCafWrapper/instance-566_8yxk with job batch system ID: 8 and cores: 4, disk: 20.0 G, and memory: 12.0 G
[2020-12-01T14:11:09+0100] [MainThread] [I] [toil-rt] 2020-12-01 14:11:09.579981: Running the command: "cactus_caf --logLevel INFO --alignments /tmp/node-e17d134b-adc2-4d84-a57f-946f1987d38a-f24dccde-57f0-4aeb-a555-331676af3ba9/tmpmquiqgar/18c185b1-10c4-4f01-b58d-8065a767b0f1/tmpo8n34q53.tmp --cactusDisk <st_kv_database_conf type="kyoto_tycoon">
                        <kyoto_tycoon database_dir="fakepath" host="10.45.12.133" port="7379" />
                </st_kv_database_conf>
         --secondaryAlignments /tmp/node-e17d134b-adc2-4d84-a57f-946f1987d38a-f24dccde-57f0-4aeb-a555-331676af3ba9/tmpmquiqgar/18c185b1-10c4-4f01-b58d-8065a767b0f1/tmpb8g0h993.tmp --annealingRounds 128 --deannealingRounds 2 8 --trim 0 0 --lastzArguments --step=1 --ambiguous=iupac,100,100 --ydrop=3000 --minimumTreeCoverage 0.0 --blockTrim 5.0 --minimumDegree 2 --minimumSequenceLengthForBlast 30 --minimumIngroupDegree 1 --minimumOutgroupDegree 0 --alignmentFilter filterSecondariesByMultipleSpecies --maxAdjacencyComponentSizeRatio <...> -proportionOfUnalignedBasesForNewChromosome 0.8 --maximumMedianSequenceLengthBetweenLinkedEnds 1000"
[2020-12-01T14:11:12+0100] [MainThread] [W] [toil.leader] Job failed with exit value 1: 'CactusCafWrapper' kind-CactusCafWrapper/instance-566_8yxk
[2020-12-01T14:11:12+0100] [MainThread] [W] [toil.leader] The job seems to have left a log file, indicating failure: 'CactusCafWrapper' kind-CactusCafWrapper/instance-566_8yxk
[2020-12-01T14:11:12+0100] [MainThread] [W] [toil.leader] Log from job kind-CactusCafWrapper/instance-566_8yxk follows:
=========>

**Comment by glennhickey** [comment]
The key line is `    Exception: ST_KV_DATABASE_EXCEPTION: Opening connection to host: 10.45.12.133 with error: network error` which means it was unable to open the `ktserver` that was launched in another Toil job.  There could be any number of reasons (process got lost, firewall issue etc),  In general, cactus does not work well with Tourque as it creates too many jobs.  

The workaround is to make a few large self-contained (make their own servers) jobs.  This can be done with the [cactus-prepare](https://github.com/ComparativeGenomicsToolkit/cactus#running-step-by-step) pipeline, and can be automated on a cluster with [cactus-prepare-toil](https://github.com/ComparativeGenomicsToolkit/cactus#running-the-step-by-step-workflow-direclty-in-toil)

**Comment by StanQiu** [comment]
Thanks, the problem was solved with cactus-prepare.
