### ISSUE TITLE
CactusTrimmingBlastPhase failing

### ISSUE THREAD

**Issue by Tierhon** [ComparativeGenomicsToolkit/cactus#378]
Hi,
I'm trying to align some genomes on a single large node (3 TB, 64 CPUs), but having some issues. I gave up trying to get SLURM to work (sinfo not found on for some reason). 

This is the error:
```
[2020-12-18T07:42:29+0100] [MainThread] [W] [toil.leader] Job 'CactusTrimmingBlastPhase' kind-CactusTrimmingBlastPhase/instance-cehv6252 with ID kind-CactusTrimmingBlastPhase/instance-ce
hv6252 is completely failed
[2020-12-18T07:42:30+0100] [Thread-1  ] [E] [toil.batchSystems.singleMachine] Got exit code 1 (indicating failure) from job _toil_worker CactusTrimmingBlastPhase file:/data/jobStore kind
-CactusTrimmingBlastPhase/instance-f1uvtkbd.
[2020-12-18T07:42:30+0100] [MainThread] [W] [toil.leader] Job failed with exit value 1: 'CactusTrimmingBlastPhase' kind-CactusTrimmingBlastPhase/instance-f1uvtkbd
[2020-12-18T07:42:30+0100] [MainThread] [W] [toil.leader] The job seems to have left a log file, indicating failure: 'CactusTrimmingBlastPhase' kind-CactusTrimmingBlastPhase/instance-f1uvtkbd
[2020-12-18T07:42:30+0100] [MainThread] [W] [toil.leader] Log from job kind-CactusTrimmingBlastPhase/instance-f1uvtkbd follows:
=========>
        [2020-12-18T07:42:26+0100] [MainThread] [I] [toil.worker] ---TOIL WORKER OUTPUT LOG---
        [2020-12-18T07:42:26+0100] [MainThread] [I] [toil] Running Toil version 4.2.0-3aa1da130141039cb357efe36d7df9b9f6ae9b5b on host c6-8.
        [2020-12-18T07:42:26+0100] [MainThread] [I] [toil.fileStores.abstractFileStore] LOG-TO-MASTER: Running blast using the trimming strategy
        Traceback (most recent call last):
          File "/usr/local/lib/python3.6/dist-packages/toil/worker.py", line 368, in workerScript
            job._runner(jobGraph=jobGraph, jobStore=jobStore, fileStore=fileStore, defer=defer)
          File "/usr/local/lib/python3.6/dist-packages/cactus/shared/common.py", line 1369, in _runner
            super(RoundedJob, self)._runner(jobGraph=jobGraph, jobStore=jobStore, fileStore=fileStore, defer=defer)
          File "/usr/local/lib/python3.6/dist-packages/toil/job.py", line 1424, in _runner
            returnValues = self._run(jobGraph, fileStore)
          File "/usr/local/lib/python3.6/dist-packages/toil/job.py", line 1361, in _run
            return self.run(fileStore)
          File "/usr/local/lib/python3.6/dist-packages/cactus/pipeline/cactus_workflow.py", line 526, in run
            sequences = [fileStore.readGlobalFile(id) for id in map(itemgetter(1), ingroupsAndOriginalIDs + outgroupsAndOriginalIDs)]
          File "/usr/local/lib/python3.6/dist-packages/cactus/pipeline/cactus_workflow.py", line 526, in <listcomp>
            sequences = [fileStore.readGlobalFile(id) for id in map(itemgetter(1), ingroupsAndOriginalIDs + outgroupsAndOriginalIDs)]
          File "/usr/local/lib/python3.6/dist-packages/toil/fileStores/nonCachingFileStore.py", line 103, in readGlobalFile
            self.jobStore.readFile(fileStoreID, localFilePath, symlink=symlink)
          File "/usr/local/lib/python3.6/dist-packages/toil/jobStores/fileJobStore.py", line 415, in readFile
            self._checkJobStoreFileID(jobStoreFileID)
          File "/usr/local/lib/python3.6/dist-packages/toil/jobStores/fileJobStore.py", line 685, in _checkJobStoreFileID
            if not self.fileExists(jobStoreFileID):
          File "/usr/local/lib/python3.6/dist-packages/toil/jobStores/fileJobStore.py", line 489, in fileExists
            absPath = self._getFilePathFromId(jobStoreFileID)
          File "/usr/local/lib/python3.6/dist-packages/toil/jobStores/fileJobStore.py", line 665, in _getFilePathFromId
            absPath = os.path.join(self.jobStoreDir, jobStoreFileID)
          File "/usr/lib/python3.6/posixpath.py", line 94, in join
            genericpath._check_arg_types('join', a, *p)
          File "/usr/lib/python3.6/genericpath.py", line 149, in _check_arg_types
            (funcname, s.__class__.__name__)) from None
        TypeError: join() argument must be str or bytes, not 'NoneType'
        [2020-12-18T07:42:29+0100] [MainThread] [E] [toil.worker] Exiting the worker because of a failed job on host c6-8
        ((Gouania_willdenowi:0.1707,(Astatotilapia_calliptera:0.112212,(Cottoperca_gobio:0.1171,0.406171:0.0195162)0.267363:0.0198738)0.403934:0.0277285)0.710171:0.0465413)0.844877;
        0.267363
        [('Cottoperca_gobio', 'files/for-job/kind-MergeChunks2/instance-h79ysylk/file-jkmokvu_/tmpjycu_ii6.tmp'), ('0.406171', 'files/for-job/kind-CactusExtractReferencePhase/instance-4pbjkwxu/file-_hn3t3ik/tmppjcrjdjx.tmp')]
        [('Astatotilapia_calliptera', 'files/for-job/kind-MergeChunks2/instance-2f47iqza/file-94udrgh7/tmpuwyzw0dv.tmp'), ('0.844877', None), ('Gouania_willdenowi', 'files/for-job/kind-MergeChunks2/instance-rm6jgpco/file-dp3rjy0m/tmp2ed_dx6q.tmp')]
<=========
[2020-12-18T07:42:30+0100] [MainThread] [W] [toil.jobGraph] Due to failure we are reducing the remaining retry count of job 'CactusTrimmingBlastPhase' kind-CactusTrimmingBlastPhase/instance-f1uvtkbd with ID kind-CactusTrimmingBlastPhase/instance-f1uvtkbd to 0
[2020-12-18T07:42:30+0100] [MainThread] [W] [toil.leader] Job 'CactusTrimmingBlastPhase' kind-CactusTrimmingBlastPhase/instance-f1uvtkbd with ID kind-CactusTrimmingBlastPhase/instance-f1uvtkbd is completely failed
[2020-12-18T07:43:09+0100] [MainThread] [I] [toil.leader] Finished toil run with 17 failed jobs.
```
Any idea what has gone wrong?

Thank you.

Ole

**Comment by glennhickey** [comment]
Not too sure what this is.  But I think I've seen errors like this due to empty input sequence files and/or empty input fasta contigs.  Or some type of formatting issue where Cactus mistakenly interprets them as empty.

**Comment by Tierhon** [comment]
Hmm, how do I track this down? I don't think any of the input assemblies have scaffolds of 0 bp length, both several have scaffolds that are shorter than 500 bp. Should that matter?

The fasta files all have 50 nucleotides on each line (direct softmasked output from RepeatMasker). 

Can I check in some way if Cactus parses the fasta files correctly?

Thank you.

**Comment by Tierhon** [comment]
This was run with Singularity. Could that be an issue? 

It looks like there are some issues with fileStore and Singularity, for instance: https://github.com/DataBiosphere/toil/issues/3461#issue-809782064 

But I don't understand these things that well.

**Comment by Tierhon** [comment]
Removing bootstrap values led to a successful Cactus alignment.
