### ISSUE TITLE
Slurm RunBlast took too long time

### ISSUE THREAD

**Issue by hehuiying1125** [ComparativeGenomicsToolkit/cactus#381]
Hi,
I tested  aligning 2 genomes with 2 outgroups on a single-machine. Jobs of  RunBlast part finished from 10mins to 45mins. The whole cactus work took only 8 hours (--maxcores 48). The I tried to test the same work on a slurm batch system (--maxLocalJobs 150 --statePollingWait 120 --batchSystem slurm  --targetTime 1). Jobs of RunBlast took more than 24 hours. Is this normal? Is there anyway to acclerate it?

**Comment by glennhickey** [comment]
The only practical to run cactus on Slurm is if you have large compute nodes and can run the [step-by-step workflow(https://github.com/ComparativeGenomicsToolkit/cactus#running-step-by-step) as described [here](https://github.com/ComparativeGenomicsToolkit/cactus#running-the-step-by-step-workflow-direclty-in-toil).

**Comment by hehuiying1125** [comment]
Thank you for your suggestion. I have tried the step-by-step workflow yesterday. Some jobs were failed in the cactus-blast part and I restart them. But I always met the sample problem to #320 . " The problem is "
Traceback (most recent call last):
  File "/public/home/liyongyao/liyongyao/liyongyao1/software/Python-3.8.6/bin/cactus-blast", line 8, in <module>
    sys.exit(main())
  File "/public/home/liyongyao/liyongyao/liyongyao1/software/Python-3.8.6/lib/python3.8/site-packages/cactus/blast/cactus_blast.py", line 88, in main
    runCactusBlastOnly(options)
  File "/public/home/liyongyao/liyongyao/liyongyao1/software/Python-3.8.6/lib/python3.8/site-packages/cactus/blast/cactus_blast.py", line 188, in runCactusBlastOnly
    toil.exportFile(outWorkFlowArgs.alignmentsID, makeURL(options.outputFile))
UnboundLocalError: local variable 'outWorkFlowArgs' referenced before assignment"

What should  I do to make it work successfully?
