### ISSUE TITLE
kernel too old and singularity

### ISSUE THREAD

**Issue by zhenzhenyang-psu** [ComparativeGenomicsToolkit/cactus#383]
HI Glenn,
I was earlier running cactus on our HPC cluster with machines of Centos6 system, and it quit because of complaint on "kernel too old". So I switched to centos7 nodes, these errors disappeared. However, because of the centos7 nodes don't have sufficient RAM, my jobs were stuck in the blast stage. I was wondering if by installing singularity on the HPC for centos6 nodes and running the cactus singularity version may get around the issue of kernel being too old. 
Could you provide your opinion?
thanks a lot,
Zhenzhen

Log from job 'logAssemblyStats' kind-logAssemblyStats/instance-g_5mgybo follows:
=========>
	[2020-12-14T17:58:58+0800] [MainThread] [I] [toil.worker] ---TOIL WORKER OUTPUT LOG---
	[2020-12-14T17:58:58+0800] [MainThread] [I] [toil] Running Toil version 4.2.0-3aa1da130141039cb357efe36d7df9b9f6ae9b5b on host node50.
	[2020-12-14T17:59:17+0800] [MainThread] [I] [cactus.shared.common] Running the command ['cactus_analyseAssembly', '/tmp/node-aa690206-eacd-4d9d-bf17-a1d9f82cae17-3dc508330ca15d09117670120000003c/tmp87e59sie/48f7a7a2-3189-41c7-b1a8-ab159c836d7a/tmpqw8dhfwf.tmp']
	FATAL: kernel too old
	[2020-12-14T17:59:17+0800] [MainThread] [W] [toil.fileStores.abstractFileStore] LOG-TO-MASTER: Job used more disk than requested. Consider modifying the user script to avoid the chance of failure due to incorrectly requested resources. Job files/for-job/kind-RunCactusPreprocessorThenProgressiveDown/instance-u3zkesl1/cleanup/file-ldzi4qxm/stream used 135.44% (2.7 GB [2908655616B] used, 2.0 GB [2147483648B] requested) at the end of its run.
	Traceback (most recent call last):
	  File "/public/home/yangzhzh/tools_zz/cactus_Dec2020/v2/cactus_env/lib/python3.7/site-packages/toil/worker.py", line 368, in workerScript
	    job._runner(jobGraph=jobGraph, jobStore=jobStore, fileStore=fileStore, defer=defer)
	  File "/public/home/yangzhzh/tools_zz/cactus_Dec2020/v2/cactus_env/lib/python3.7/site-packages/toil/job.py", line 1424, in _runner
	    returnValues = self._run(jobGraph, fileStore)
	  File "/public/home/yangzhzh/tools_zz/cactus_Dec2020/v2/cactus_env/lib/python3.7/site-packages/toil/job.py", line 1361, in _run
	    return self.run(fileStore)
	  File "/public/home/yangzhzh/tools_zz/cactus_Dec2020/v2/cactus_env/lib/python3.7/site-packages/toil/job.py", line 1565, in run
	    rValue = userFunction(*((self,) + tuple(self._args)), **self._kwargs)
	  File "/public/home/yangzhzh/tools_zz/cactus_Dec2020/v2/cactus_env/lib/python3.7/site-packages/cactus/progressive/cactus_progressive.py", line 209, in logAssemblyStats
	    analysisString = cactus_call(parameters=["cactus_analyseAssembly", sequenceFile], check_output=True)
	  File "/public/home/yangzhzh/tools_zz/cactus_Dec2020/v2/cactus_env/lib/python3.7/site-packages/cactus/shared/common.py", line 1308, in cactus_call
	    raise RuntimeError("Command {} signaled {}: {}".format(call, signal.Signals(-process.returncode).name, out))
	RuntimeError: Command ['cactus_analyseAssembly', '/tmp/node-aa690206-eacd-4d9d-bf17-a1d9f82cae17-3dc508330ca15d09117670120000003c/tmp87e59sie/48f7a7a2-3189-41c7-b1a8-ab159c836d7a/tmpqw8dhfwf.tmp'] signaled SIGABRT: stdout=
	[2020-12-14T17:59:17+0800] [MainThread] [E] [toil.worker] Exiting the worker because of a failed job on host node50
<=========

**Comment by glennhickey** [comment]
I don't think that will work.  Using containers does not change the underlying CPU architecture.  The next cactus release (sometime in January) will include a binary package for older systems that should work on most cpus from 2004 and newer.

**Comment by zhenzhenyang-psu** [comment]
that will be awesome! looking forward to it!

获取 Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by glennhickey** [comment]
Legacy binaries are available in the new release here : https://github.com/ComparativeGenomicsToolkit/cactus/releases/tag/v1.3.0

**Comment by zhenzhenyang-psu** [comment]
Hi Glenn,
Thanks very much for providing a version for older kernel system.
While I was following instructions to install the binary version, I had the following error while executing "pip install -U -r ./toil-requirement.txt". The error message is something like below:

Traceback (most recent call last):
  File "/public/home/yangzhzh/tools_zz/cactus_Feb2021_centos6/cactus-bin-v1.3.0/venv/lib/python3.7/site-packages/pip/_vendor/resolvelib/resolvers.py", line 171, in _merge_into_criterion
    crit = self.state.criteria[name]
KeyError: 'botocore'

The detailed output of this error message is attached. 
[cactus_centos6_install_issue.txt](https://github.com/ComparativeGenomicsToolkit/cactus/files/6007520/cactus_centos6_install_issue.txt)

Originally I thought this is a network issue, so I repeated this command yet the error remained. 
Any insights? thanks very much,
Zhenzhen
