### ISSUE TITLE
hal2assemblyHub.py error: GetCladeExclusive fails

### ISSUE THREAD

**Issue by ybukhman** [ComparativeGenomicsToolkit/cactus#402]
Hi,

this is my hal2assemblyHub.py command
`hal2assemblyHub.py jobstore mAcoRus1.1_vs_mm10.hal mAcoRus1.1_vs_mm10_hub --lod --alignability --gcContent --cladeExclusiveRegions --maxCores 20 --hub mAcoRus1.1_vs_mm10 --shortLabel mAcoRus1.1_vs_mm10 --longLabel "Cactus alignment of golden spiny mouse assembly mAcoRus1.1 vs house mouse assembly mm10" |& tee hal2assemblyHub.out`

It failed with the following error:
> [2021-01-15T01:13:15-0600] [Thread-1  ] [E] [toil.batchSystems.singleMachine] Got exit code 1 (indicating failure) from job _toil_worker GetCladeExclusive file
> :/mnt/isi5home/ybukhman/Projects/NILERAT/NILERAT-39_pairwise_Cactus_vs_mouse/mAcoRus1.1_vs_mm10/jobstore kind-GetCladeExclusive/instance-6kvrir4r.
> [2021-01-15T01:13:15-0600] [MainThread] [W] [toil.leader] Job failed with exit value 1: 'GetCladeExclusive' kind-GetCladeExclusive/instance-6kvrir4r
> [2021-01-15T01:13:15-0600] [MainThread] [W] [toil.leader] The job seems to have left a log file, indicating failure: 'GetCladeExclusive' kind-GetCladeExclusive
> /instance-6kvrir4r
> [2021-01-15T01:13:15-0600] [MainThread] [W] [toil.leader] Log from job kind-GetCladeExclusive/instance-6kvrir4r follows:
> =========>
>         [2021-01-14T19:43:25-0600] [MainThread] [I] [toil.worker] ---TOIL WORKER OUTPUT LOG---
>         [2021-01-14T19:43:25-0600] [MainThread] [I] [toil] Running Toil version 4.2.0-3aa1da130141039cb357efe36d7df9b9f6ae9b5b on host mir-81.
>         /mnt/isi5home/ybukhman/Projects/NILERAT/NILERAT-39_pairwise_Cactus_vs_mouse/mAcoRus1.1_vs_mm10/mAcoRus1.1_vs_mm10_hub/liftoverbeds/CladeExclusive/mAcoR
> us1.1_mm10_anc/mAcoRus1.1_mm10_anc.bed is empty
>         Traceback (most recent call last):
>           File "/isitools/Python3.7.2/lib/python3.7/site-packages/toil/worker.py", line 368, in workerScript
>             job._runner(jobGraph=jobGraph, jobStore=jobStore, fileStore=fileStore, defer=defer)
>           File "/isitools/Python3.7.2/lib/python3.7/site-packages/toil/job.py", line 1424, in _runner
>             returnValues = self._run(jobGraph, fileStore)
>           File "/isitools/Python3.7.2/lib/python3.7/site-packages/toil/job.py", line 1361, in _run
>             return self.run(fileStore)
>           File "/isitools/cactus-bin-v1.2.3/lib/hal/assemblyHub/groupExclusiveRegions.py", line 67, in run
>             system("bedToBigBed %s %s %s" %(outbed, chrsizefile, outbigbed))
>           File "/isitools/Python3.7.2/lib/python3.7/site-packages/sonLib/bioio.py", line 194, in system
>             raise RuntimeError("Command: %s exited with non-zero status %i" % (command, sts))
>         RuntimeError: Command: bedToBigBed /mnt/isi5home/ybukhman/Projects/NILERAT/NILERAT-39_pairwise_Cactus_vs_mouse/mAcoRus1.1_vs_mm10/mAcoRus1.1_vs_mm10_hub/liftoverbeds/CladeExclusive/mAcoRus1.1_mm10_anc/mAcoRus1.1_mm10_anc.bed /mnt/isi5home/ybukhman/Projects/NILERAT/NILERAT-39_pairwise_Cactus_vs_mouse/mAcoRus1.1_vs_mm10/mAcoRus1.1_vs_mm10_hub/liftoverbeds/CladeExclusive/../../mAcoRus1.1_mm10_anc/chrom.sizes /mnt/isi5home/ybukhman/Projects/NILERAT/NILERAT-39_pairwise_Cactus_vs_mouse/mAcoRus1.1_vs_mm10/mAcoRus1.1_vs_mm10_hub/liftoverbeds/CladeExclusive/mAcoRus1.1_mm10_anc/mAcoRus1.1_mm10_anc.bb exited with non-zero status 255
>         [2021-01-15T01:13:15-0600] [MainThread] [E] [toil.worker] Exiting the worker because of a failed job on host mir-81
>         ['mAcoRus1.1_mm10_anc', 'Acomys_russatus_mAcoRus1.1', 'Mus_musculus_mm10']
>         /mnt/isi5home/ybukhman/Projects/NILERAT/NILERAT-39_pairwise_Cactus_vs_mouse/mAcoRus1.1_vs_mm10/mAcoRus1.1_vs_mm10_hub/liftoverbeds/CladeExclusive/mAcoRus1.1_mm10_anc
> <=========
> 

I have just two genomes in my alignment. It seems that GetCladeExclusive jobs completed successfully on the two genomes but failed on their inferred ancestor. Of course, the ancestor is not supposed to have any regions that are exclusive to it, right? Do I need to specify another option to make hal2assemblyHub.py handle it correctly?

Thanks!

Yury

**Comment by ybukhman** [comment]
I have updated my UCSC standalone utilities. Now conversion of non-empty bed files to BigBed also fails with the same error, e.g.:

> RuntimeError: Command: bedToBigBed /mnt/isi5home/ybukhman/Projects/NILERAT/NILERAT-39_pairwise_Cactus_vs_mouse/mAcoRus1.1_vs_mm10/mAcoRus1.1_vs_mm10_hub/liftoverbeds/CladeExclusive/Acomys_russatus_mAcoRus1.1/Acomys_russatus_mAcoRus1.1.bed /mnt/isi5home/ybukhman/Projects/NILERAT/NILERAT-39_pairwise_Cactus_vs_mouse/mAcoRus1.1_vs_mm10/mAcoRus1.1_vs_mm10_hub/liftoverbeds/CladeExclusive/../../Acomys_russatus_mAcoRus1.1/chrom.sizes /mnt/isi5home/ybukhman/Projects/NILERAT/NILERAT-39_pairwise_Cactus_vs_mouse/mAcoRus1.1_vs_mm10/mAcoRus1.1_vs_mm10_hub/liftoverbeds/CladeExclusive/Acomys_russatus_mAcoRus1.1/Acomys_russatus_mAcoRus1.1.bb exited with non-zero status 255
 
Trying to run bedToBigBed directly produces a meaningful error:

> (cactus_env_v1.2.3) bash-4.2$ bedToBigBed Acomys_russatus_mAcoRus1.1.bed ../../../Acomys_russatus_mAcoRus1.1/chrom.sizes Acomys_russatus_mAcoRus1.1.bb
> Acomys_russatus_mAcoRus1.1.bed is not case-sensitive sorted at line 2595550.  Please use "sort -k1,1 -k2,2n" with LC_COLLATE=C,  or bedSort and try again.
> 

The bed file is indeed not alphabetically sorted at the specified position:

> (cactus_env_v1.2.3) bash-4.2$ head -n 2595553 Acomys_russatus_mAcoRus1.1.bed \| tail
> LR877225.1      62741576        62741577
> LR877225.1      62741763        62741764
> LR877225.1      62741887        62741888
> LR877225.1      62741921        62741923
> LR877225.1      62742048        62742058
> LR877225.1      62742072        62749010
> CAJFAB010000417.1       0       106434
> CAJFAB010000417.1       106523  106527
> CAJFAB010000417.1       106538  106542
> CAJFAB010000417.1       106703  106710
> 

Updated bedToBigBed still does not like empty files:

> (cactus_env_v1.2.3) bash-4.2$ bedToBigBed mAcoRus1.1_mm10_anc.bed ../../../mAcoRus1.1_mm10_anc/chrom.sizes mAcoRus1.1_mm10_anc.bb
> mAcoRus1.1_mm10_anc.bed is empty
> (cactus_env_v1.2.3) bash-4.2$ $?
> bash: 255: command not found
> 

Thanks.

Yury
