### ISSUE TITLE
`cap_getCoordinate(cap) == INT64_MAX' failed

### ISSUE THREAD

**Issue by zhenzhenyang-psu** [ComparativeGenomicsToolkit/cactus#404]
HI Glenn,
I have been running cactus with the input of 9 mammalian-sized genomes on a PBS Torque system. It has run for 13 days, yet threw an error since. 
the error message is here (https://s3.wasabisys.com/aiden-zhenzhen/public/temp/test_9genomes_os7_t10_v5_350GB_restart.e2218022).
I am copying and pasting what I think as the most relevant information:
	[2021-01-17T08:10:08+0800] [MainThread] [I] [cactus.shared.common] Running the command ['ktremotemgr', 'set', '-port', '22357', '-host', '127.0.0.1', 'TERMINATE', '1']
	[2021-01-17T08:10:18+0800] [MainThread] [I] [cactus.shared.common] Running the command ['ktremotemgr', 'get', '-port', '22357', '-host', '127.0.0.1', 'TERMINATE']
	1
	[2021-01-17T08:19:03+0800] [MainThread] [W] [toil.fileStores.abstractFileStore] LOG-TO-MASTER: Job used more disk than requested. Consider modifying the user script to avoid the chance of failure due to incorrectly requested resources. Job files/for-job/kind-StartPrimaryDB/instance-_fs7m3qm/cleanup/file-igkk5sdq/stream used 1530.33% (30.6 GB [32863598592B] used, 2.0 GB [2147483648B] requested) at the end of its run.
	Traceback (most recent call last):
	  File "/public/home/yangzhzh/tools_zz/cactus_Dec2020/v2/cactus_env/lib/python3.7/site-packages/toil/worker.py", line 368, in workerScript
	    job._runner(jobGraph=jobGraph, jobStore=jobStore, fileStore=fileStore, defer=defer)
	  File "/public/home/yangzhzh/tools_zz/cactus_Dec2020/v2/cactus_env/lib/python3.7/site-packages/toil/job.py", line 1424, in _runner
	    returnValues = self._run(jobGraph, fileStore)
	  File "/public/home/yangzhzh/tools_zz/cactus_Dec2020/v2/cactus_env/lib/python3.7/site-packages/toil/job.py", line 1780, in _run
	    returnValues = self.run(fileStore)
	  File "/public/home/yangzhzh/tools_zz/cactus_Dec2020/v2/cactus_env/lib/python3.7/site-packages/toil/job.py", line 1754, in run
	    raise RuntimeError("Detected the error jobStoreID has been removed so exiting with an error")
	RuntimeError: Detected the error jobStoreID has been removed so exiting with an error
	[2021-01-17T08:19:03+0800] [MainThread] [E] [toil.worker] Exiting the worker because of a failed job on host node33
<=========
Log from job 'CactusSetReferenceCoordinatesUpWrapper' kind-CactusSetReferenceCoordinatesUpWrapper/instance-btul5jyt follows:
=========>
	[2021-01-17T07:31:45+0800] [MainThread] [I] [toil.worker] ---TOIL WORKER OUTPUT LOG---
	[2021-01-17T07:31:45+0800] [MainThread] [I] [toil] Running Toil version 4.2.0-3aa1da130141039cb357efe36d7df9b9f6ae9b5b on host node33.
	[2021-01-17T07:31:47+0800] [MainThread] [I] [cactus.shared.common] Running the command ['cactus_addReferenceCoordinates', '--logLevel', 'INFO', '--cactusDisk', '<st_kv_database_conf type="kyoto_tycoon">\n\t\t\t<kyoto_tycoon database_dir="fakepath" host="127.0.0.1" port="22357" />\n\t\t</st_kv_database_conf>\n\t', '--bottomUpPhase', '--referenceEventString', 'Anc09', '--secondaryDisk', '<st_kv_database_conf type="kyoto_tycoon">\n\t\t\t<kyoto_tycoon database_dir="fakepath" host="127.0.0.1" port="32430" />\n\t\t</st_kv_database_conf>\n\t']
	referenceEventString = Anc09
	bottomUpPhase = 1
	Set up the flower disk
	((((Macaca_fuscata:0.00371195,Allenopithecus_nigroviridis:0.00625139)Anc11:0.0173392,(Saimiri_boliviensis:0.0156333,Cebuella_pygmaea:0.0146098)Anc09:0.016024)Anc06:0.0243215,Propithecus_coquereli:0.0432926)Anc05:9.22337e+18)ROOT:9.22337e+18;
	cactus_addReferenceCoordinates: impl/addReferenceCoordinates.c:100: setAdjacencyLengthsAndRecoverNewCapsAndBrokenAdjacencies: Assertion `cap_getCoordinate(cap) == INT64_MAX' failed.
	Traceback (most recent call last):
	  File "/public/home/yangzhzh/tools_zz/cactus_Dec2020/v2/cactus_env/lib/python3.7/site-packages/toil/worker.py", line 368, in workerScript
	    job._runner(jobGraph=jobGraph, jobStore=jobStore, fileStore=fileStore, defer=defer)
	  File "/public/home/yangzhzh/tools_zz/cactus_Dec2020/v2/cactus_env/lib/python3.7/site-packages/cactus/shared/common.py", line 1369, in _runner
	    super(RoundedJob, self)._runner(jobGraph=jobGraph, jobStore=jobStore, fileStore=fileStore, defer=defer)
	  File "/public/home/yangzhzh/tools_zz/cactus_Dec2020/v2/cactus_env/lib/python3.7/site-packages/toil/job.py", line 1424, in _runner
	    returnValues = self._run(jobGraph, fileStore)
	  File "/public/home/yangzhzh/tools_zz/cactus_Dec2020/v2/cactus_env/lib/python3.7/site-packages/toil/job.py", line 1361, in _run
	    return self.run(fileStore)
	  File "/public/home/yangzhzh/tools_zz/cactus_Dec2020/v2/cactus_env/lib/python3.7/site-packages/cactus/pipeline/cactus_workflow.py", line 1161, in run
	    bottomUpPhase=True)
	  File "/public/home/yangzhzh/tools_zz/cactus_Dec2020/v2/cactus_env/lib/python3.7/site-packages/cactus/shared/common.py", line 631, in runCactusAddReferenceCoordinates
	    fileStore=fileStore)
	  File "/public/home/yangzhzh/tools_zz/cactus_Dec2020/v2/cactus_env/lib/python3.7/site-packages/cactus/shared/common.py", line 1308, in cactus_call
	    raise RuntimeError("Command {} signaled {}: {}".format(call, signal.Signals(-process.returncode).name, out))
	RuntimeError: Command ['cactus_addReferenceCoordinates', '--logLevel', 'INFO', '--cactusDisk', '<st_kv_database_conf type="kyoto_tycoon">\n\t\t\t<kyoto_tycoon database_dir="fakepath" host="127.0.0.1" port="22357" />\n\t\t</st_kv_database_conf>\n\t', '--bottomUpPhase', '--referenceEventString', 'Anc09', '--secondaryDisk', '<st_kv_database_conf type="kyoto_tycoon">\n\t\t\t<kyoto_tycoon database_dir="fakepath" host="127.0.0.1" port="32430" />\n\t\t</st_kv_database_conf>\n\t'] signaled SIGABRT: stdout=None
	[2021-01-17T07:31:49+0800] [MainThread] [E] [toil.worker] Exiting the worker because of a failed job on host node33
<=========

 Any insights on how to fix?
thanks,
Zhenzhen

**Comment by glennhickey** [comment]
It looks like the database is somehow corrupt.  Beyond retrying with `--restart`,there's not too much to try to fix.  Which command are you running?  In particular, see the [note here about the work-around for running cactus on a cluster](https://github.com/ComparativeGenomicsToolkit/cactus#running-on-a-cluster) if you haven't already

**Comment by zhenzhenyang-psu** [comment]
Hi Glenn,
thanks for the reply. I resubmitted and see if it will finish. I guess resubmitting it is also a way to get around the overwhelming number of jobs on the torque cluster?
the command I used is as follows:

source /public/home/yangzhzh/tools_zz/cactus_Dec2020/v2/cactus_env/bin/activate
/public/home/yangzhzh/tools_zz/cactus_Dec2020/v2/cactus_env/bin/cactus --restart --workDir temp_workdir jobstore3_t10 9genomes.tree.and.seq.in.txt  example9genomes/9genomes.centos7.t10.hal

Would you recommend running "cactus-prepare" or "cactus-prepare-toil" to generate the commands for each step separately?
thanks much,
Zhenzhen

**Comment by glennhickey** [comment]
`cactus-prepare` then running one command at a time is probably easier to debug locally.  `cactus-prepare-toil` will run each command for you, so will be more convenient for bigger trees, as well as on cluster-based toil batch systems.
