### ISSUE TITLE
Fatal Python error: initfsencoding: Unable to get the locale encoding

### ISSUE THREAD

**Issue by DieTANG** [ComparativeGenomicsToolkit/cactus#420]
Hi,
I am running cactus for 47 genomes (~ 700 Mb per genome) alignment with 88 cores and 2T RAM. And i get this error after 'CactusSetReferenceCoordinatesUpWrapper'. By the way, I run the test successfully. I don't know how to solve this probrem, and i am running this task for 4 days. Whether i can continue run with the previews jobStore?

[2021-02-08T12:20:19+0800] [MainThread] [I] [toil.leader] Job ended: 'CactusSetReferenceCoordinatesUpWrapper' kind-CactusSetReferenceCoordinatesUpWrapper/instance-ttojmvxu [2021-02-08T12:20:19+0800] [MainThread] [I] [toil.leader] Job ended: 'CactusSetReferenceCoordinatesUpWrapper' kind-CactusSetReferenceCoordinatesUpWrapper/instance-7_u9njl5 [2021-02-08T12:20:19+0800] [MainThread] [I] [toil.worker] Redirecting logging to /tmp/node-828c82b0-25a3-4e72-8e0f-6dcca50a49e2-e5ad1da3-f13d-4120-9442-aa3daa61d299/tmprj3n1dxb/worker_log.txt Fatal Python error: initfsencoding: Unable to get the locale encoding Traceback (most recent call last): File "<frozen importlib._bootstrap>", line 983, in _find_and_load File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked Fatal Python error: initsite: Failed to import the site module File "<frozen importlib._bootstrap>", line 677, in _load_unlocked File "<frozen importlib._bootstrap_external>", line 724, in exec_module File "<frozen importlib._bootstrap_external>", line 859, in get_code File "<frozen importlib._bootstrap_external>", line 916, in get_data BrokenPipeError: [Errno 108] Cannot send after transport endpoint shutdown: '/lustre/home/tangdie/anaconda3/lib/python3.7/encodings/__init__.py' [2021-02-08T12:20:19+0800] [MainThread] [I] [toil.leader] Job ended: 'CactusSetReferenceCoordinatesUpWrapper' kind-CactusSetReferenceCoordinatesUpWrapper/instance-bgkahh0_ Traceback (most recent call last): File "/lustre/home/tangdie/anaconda3/bin/_toil_worker", line 8, in <module> File "/lustre/home/tangdie/anaconda3/lib/python3.7/site-packages/toil/worker.py", line 590, in main File "/lustre/home/tangdie/anaconda3/lib/python3.7/site-packages/toil/worker.py", line 557, in workerScript File "/lustre/home/tangdie/anaconda3/lib/python3.7/site-packages/toil/jobStores/fileJobStore.py", line 237, in delete File "/lustre/home/tangdie/anaconda3/lib/python3.7/site-packages/toil/lib/misc.py", line 56, in robust_rmtree File "/lustre/home/tangdie/anaconda3/lib/python3.7/shutil.py", line 498, in rmtree File "/lustre/home/tangdie/anaconda3/lib/python3.7/shutil.py", line 496, in rmtree

[bug_cactus.log](https://github.com/ComparativeGenomicsToolkit/cactus/files/5943783/bug_cactus.log)
Attached with my log file with bug reports.

Waiting for your reply.
Thanks!
TANG

**Comment by glennhickey** [comment]
That's a new one to me.  Does the error repeat if you run the same command again with `--restart` ? (making sure *not* to delete your jobstore first)
