### ISSUE TITLE
Best settings

### ISSUE THREAD

**Issue by francicco** [ComparativeGenomicsToolkit/cactus#43]
Hi,

I'm trying to align the genomes of these 6 species:

<img width="1004" alt="screen shot 2018-09-20 at 10 25 54" src="https://user-images.githubusercontent.com/9006870/45809257-a3f02580-bcbf-11e8-963a-725a82ad5323.png">

For Talp I have 12 resequenced genomes plus the reference, for a total of 18 genomes to align. 
This is how I set the control file:

```
((((((((((bkp55bd,bkp67ad),bkp73bd),bkp88bd),(((wk44ad,wk59bd),wk77bd),wk86ad)),(((wp45ad,wp45bd),wp87bd),wp96bd)),Talp),Timm),(Tbic,Tsim)),Tpar),Veme);
bkp55bd 433_bkp55bd.fasta
bkp67ad 433_bkp67ad.fasta
bkp73bd 433_bkp73bd.fasta
bkp88bd 433_bkp88bd.fasta
wk44ad 433_wk44ad.fasta
wk59bd 433_wk59bd.fasta
wk77bd 433_wk77bd.fasta
wk86ad 433_wk86ad.fasta
wp45ad 433_wp45ad.fasta
wp45bd 433_wp45bd.fasta
wp87bd 433_wp87bd.fasta
wp96bd 433_wp96bd.fasta
*Talp Talp.v2.0.assembly.fasta
Tbic Tbic.v1.0.assembly.fasta
Timm Timm.v1.0.assembly.fasta
Tpar Tpar.v1.0.assembly.fasta
Tsim Tsim.v1.0.assembly.fasta
*Veme V.emery_V1.0.fasta
```

I'm now running the job using the default settings. Would be the settings to play with?

Thanks
F

**Comment by joelarmstrong** [comment]
Hi Francesco,

The main setting to play with is the branch lengths in the tree. If I'm understanding the situation right, you probably want a fairly short branch length (~0.01 or so) within the clade representing the resequenced species--assuming they are all going to be very close together.

That said, the default settings should probably be OK. The more accurate branch lengths will mostly just help speed things up, but also potentially reduce ortholog/paralog confusion a bit.

**Comment by francicco** [comment]
So, I can use a BL of 2 for the outgruop and gradually reduce till 0.01? Does Cactus accept unresolved nodes?

One oder thing. I got this error:

```
2018-09-20 19:06:41,543 - toil.leader - INFO - Finished toil run with 252 failed jobs.
INFO:toil.leader:Failed jobs at end of the run: 'LastzRepeatMaskJob' w/w/jobZYX4Tq 'PreprocessChunk' m/q/jobK95ZUe 'PreprocessChunk' b/p/jobvTlHBj 'PreprocessChunk' D/x/jobAib6H_ 'AlignFastaFragments' 1/6/jobAk2H2d 'PreprocessChunk' l/L/job05R5vX 'PreprocessChunk' 8/0/jobNKMQEY 'AlignFastaFragments' z/A/jobpMdRje 'AlignFastaFragments' F/1/jobZjvtUf 'PreprocessChunk' E/3/jobemSYvt 'PreprocessChunk' T/K/jobCauPza 'LastzRepeatMaskJob' u/4/jobKOJM3c 'PreprocessChunk' M/D/jobnSITFA 'LastzRepeatMaskJob' S/B/jobw5CAnJ 'PreprocessChunk' Y/H/jobHQ0Ggh 'AlignFastaFragments' f/F/jobwaU8cm 'PreprocessChunk' 1/B/jobuzKAMQ 'LastzRepeatMaskJob' 3/n/jobzU07_L 'LastzRepeatMaskJob' W/1/job1C21z_ 'PreprocessChunk' k/K/jobTGDBP0 'PreprocessChunk' r/a/jobTIYlKw 'AlignFastaFragments' q/F/jobFH_1gx 'PreprocessChunk' p/W/jobMPuzTa 'AlignFastaFragments' 2/M/job90lCeH 'AlignFastaFragments' c/x/jobVxW9uN 'AlignFastaFragments' q/q/jobwxsXuN 'LastzRepeatMaskJob' g/V/jobkrK3kR 'AlignFastaFragments' k/u/jobUONjxk 'AlignFastaFragments' g/x/jobQUVOPS 'LastzRepeatMaskJob' K/6/jobmgYEdj 'LastzRepeatMaskJob' N/L/jobDbGikg 'PreprocessChunk' f/j/jobpJH0hA 'PreprocessChunk' M/m/jobJk_pXH 'LastzRepeatMaskJob' Q/x/jobGDLwwS 'PreprocessChunk' 6/U/jobOSIV1V 'LastzRepeatMaskJob' I/x/jobi83QgC 'AlignFastaFragments' S/J/jobJtcHOE 'PreprocessChunk' y/E/job9YU0SK 'LastzRepeatMaskJob' e/w/jobn1p7GK 'AlignFastaFragments' s/n/jobKK_5LJ 'LastzRepeatMaskJob' o/b/jobygmBKj 'AlignFastaFragments' P/8/jobfYNi9Y 'LastzRepeatMaskJob' S/Z/jobeiNFB_ 'PreprocessChunk' n/E/jobYEarIS 'AlignFastaFragments' b/S/jobv3F6b5 'PreprocessChunk' d/x/jobsJpxYT 'LastzRepeatMaskJob' w/h/jobAocZlR 'LastzRepeatMaskJob' O/R/jobcn4djw 'PreprocessChunk' X/P/jobzM6KxI 'LastzRepeatMaskJob' T/o/jobvyrXQy 'LastzRepeatMaskJob' c/9/jobJR0ljq 'LastzRepeatMaskJob' q/R/jobjzJUYQ 'AlignFastaFragments' T/G/job0nqUM3 'LastzRepeatMaskJob' 9/L/jobRBf6a5 'AlignFastaFragments' u/d/job0zgSP9 'PreprocessChunk' 5/M/job0OQ9i3 'PreprocessChunk' f/p/jobG7R7pc 'LastzRepeatMaskJob' p/C/jobtOQ_5P 'AlignFastaFragments' X/j/jobNcPWNZ 'LastzRepeatMaskJob' c/L/jobNx_V9T 'PreprocessChunk' h/y/jobaieQr7 'AlignFastaFragments' I/i/joboiJS3e 'PreprocessChunk' I/b/jobdwfpb1 'PreprocessChunk' 4/A/joboXoNrA 'LastzRepeatMaskJob' 1/L/jobQSVi1X 'PreprocessChunk' t/k/jobaJOOAP 'PreprocessChunk' e/N/job811xWO 'AlignFastaFragments' X/s/jobDN9_x1 'PreprocessChunk' z/t/job4VJHIc 'RunCactusPreprocessorThenProgressiveDown' B/H/jobPu8wcG 'AlignFastaFragments' i/d/jobBKmOCa 'AlignFastaFragments' b/5/jobEVQMrL 'LastzRepeatMaskJob' n/9/jobTltu9r 'AlignFastaFragments' L/C/jobKSRZMS 'LastzRepeatMaskJob' F/J/jobvcg9y0 'AlignFastaFragments' 1/m/job77VT2y 'LastzRepeatMaskJob' O/F/jobGwQd5b 'LastzRepeatMaskJob' y/M/jobN8w3yW 'AlignFastaFragments' P/Z/jobG2Lhmr 'AlignFastaFragments' 9/j/jobjFaZo6 'PreprocessChunk' w/y/jobvWD5Se 'AlignFastaFragments' E/j/job21GByO 'LastzRepeatMaskJob' 9/k/jobeLRKe4 'PreprocessChunk' D/C/jobk4WfzB 'AlignFastaFragments' O/J/jobsY1DUq 'LastzRepeatMaskJob' 9/g/jobT8s4xi 'LastzRepeatMaskJob' i/p/jobC8dbHk 'LastzRepeatMaskJob' j/K/jobBSbbpd 'AlignFastaFragments' n/F/jobqRdF4t 'PreprocessChunk' p/Z/jobDVQuvF 'LastzRepeatMaskJob' U/f/job2NcdLw 'PreprocessChunk' O/2/job4MgAdt 'PreprocessChunk' c/f/jobLTDNVI 'AlignFastaFragments' t/y/jobr8VTza 'AlignFastaFragments' T/l/jobTY5fiw 'LastzRepeatMaskJob' a/G/jobox0SNb 'PreprocessChunk' Q/F/joblFUZVM 'PreprocessChunk' m/m/jobWvH3Co 'LastzRepeatMaskJob' U/Z/jobyrpG5c 'BatchPreprocessor' J/b/jobBEWUPr 'AlignFastaFragments' o/D/jobYGxTHF 'LastzRepeatMaskJob' l/5/jobzwwhUV 'PreprocessSequence' 5/G/jobI3j3jj 'LastzRepeatMaskJob' t/J/jobyVcWkO 'AlignFastaFragments' T/k/jobNnWrvg 'LastzRepeatMaskJob' R/y/job402Zbc 'AlignFastaFragments' T/f/jobh9sDd5 'PreprocessChunk' Z/y/jobTb2yJP 'PreprocessChunk' R/N/jobjzqAXK 'AlignFastaFragments' g/W/jobAmOfjo 'AlignFastaFragments' b/F/jobEZ7ywS 'LastzRepeatMaskJob' v/b/jobUH8pwg 'LastzRepeatMaskJob' 5/P/jobWACd20 'PreprocessChunk' x/B/jobtpU3R_ 'PreprocessChunk' v/b/job_JeAc4 'PreprocessChunk' 2/1/joblbf8k_ 'PreprocessChunk' 0/6/jobupZjzw 'LastzRepeatMaskJob' z/u/jobXPF_Ir 'AlignFastaFragments' D/V/jobU5clmr 'AlignFastaFragments' r/N/jobxLTxuZ 'AlignFastaFragments' B/8/job2S8brV 'AlignFastaFragments' D/n/jobeXAA45 'LastzRepeatMaskJob' P/I/jobIyRO_u 'PreprocessChunk' r/7/jobGkYy59 'PreprocessChunk' x/M/jobjy8Hr8 'PreprocessChunk' 2/w/jobzVZDQa 'PreprocessChunk' X/u/job1ncaQB 'LastzRepeatMaskJob' K/v/jobr2ouih 'PreprocessChunk' 5/M/jobUj6RG4 'LastzRepeatMaskJob' e/7/jobE7JOw7 'AlignFastaFragments' a/Q/jobHtaJgg 'AlignFastaFragments' P/x/jobTyS_Jq 'LastzRepeatMaskJob' h/o/jobT72Zt3 'PreprocessChunk' G/1/jobzRT8H9 'LastzRepeatMaskJob' e/c/jobZdSw6x 'AlignFastaFragments' b/w/jobL05ycC 'PreprocessChunk' O/F/jobF9i5kG 'AlignFastaFragments' y/5/jobfLPrlg 'PreprocessChunk' R/G/job3Vjxhu 'AlignFastaFragments' Q/g/job0SDpU3 'AlignFastaFragments' 9/F/jobiqgVdd 'LastzRepeatMaskJob' S/C/job6Rc9KJ 'AlignFastaFragments' q/o/jobQMER_p 'PreprocessChunk' 8/H/jobvjBouh 'PreprocessChunk' m/z/jobInu4ma 'LastzRepeatMaskJob' H/n/jobYm1I61 'AlignFastaFragments' V/2/joby1iM2s 'LastzRepeatMaskJob' K/l/jobYHkrW2 'PreprocessChunk' O/c/job0AW0Ot 'LastzRepeatMaskJob' r/N/jobzHJEek 'PreprocessChunk' r/f/job73MQSC 'AlignFastaFragments' 9/n/job4OIwff 'AlignFastaFragments' o/q/jobJekTFK 'LastzRepeatMaskJob' R/4/job6KUKyx 'LastzRepeatMaskJob' 3/T/jobYKvexQ 'AlignFastaFragments' f/V/jobglAw8H 'LastzRepeatMaskJob' g/m/jobk9MkbW 'AlignFastaFragments' S/2/jobmVff53 'PreprocessChunk' 6/0/jobvyt3Bn 'LastzRepeatMaskJob' M/n/jobZPVYYU 'PreprocessChunk' d/a/jobAxi7Vi 'PreprocessChunk' b/w/jobrBUs_l 'AlignFastaFragments' 0/G/jobJ7U4R5 'AlignFastaFragments' L/K/jobWDWj9u 'LastzRepeatMaskJob' g/2/jobe0HLHo 'AlignFastaFragments' A/W/jobifTNFO 'PreprocessChunk' d/r/job14zL74 'PreprocessChunk' M/l/jobL7fz5E 'LastzRepeatMaskJob' f/P/jobH9QAzr 'LastzRepeatMaskJob' I/v/jobZmqk_a 'AlignFastaFragments' d/u/jobjjnz8s 'PreprocessChunk' r/C/jobrboBrZ 'PreprocessChunk' F/z/jobz3YHXr 'AlignFastaFragments' h/Y/jobbLz23Y 'LastzRepeatMaskJob' E/1/jobnDteom 'AlignFastaFragments' g/j/jobHhzdKb 'LastzRepeatMaskJob' e/o/jobKf6W6g 'PreprocessChunk' J/S/jobg99ARj 'AlignFastaFragments' q/a/job8Fcnvi 'AlignFastaFragments' U/O/jobWewBTJ 'AlignFastaFragments' q/9/jobMWLSJH 'LastzRepeatMaskJob' v/I/job3h_mcO 'LastzRepeatMaskJob' C/S/job9QFpv8 'AlignFastaFragments' e/r/jobtF8tHm 'PreprocessChunk' E/Z/jobDBHCBG 'AlignFastaFragments' Q/C/jobpc62Ib 'PreprocessChunk' 5/d/jobKOpXj6 'AlignFastaFragments' H/x/jobJ_v8Wb 'PreprocessChunk' B/f/jobzj275b 'PreprocessChunk' 5/X/jobeLsmWh 'CactusPreprocessor' U/S/jobC7AAEO 'PreprocessChunk' C/Q/job2b_rXR 'PreprocessChunk' 1/G/jobgqcAGw 'AlignFastaFragments' d/r/jobfiP3v6 'PreprocessChunk' s/w/job3xSrYI 'AlignFastaFragments' k/P/joby_d4PU 'PreprocessChunk' h/v/jobPrnp5D 'AlignFastaFragments' 9/c/job0XwaiT 'AlignFastaFragments' 2/9/jobHHA6px 'AlignFastaFragments' R/0/joby0ayoy 'PreprocessChunk' 8/K/jobDmxFMe 'PreprocessChunk' l/q/jobTEifZX 'PreprocessChunk' i/W/jobNesQSj 'CactusPreprocessor2' I/P/job6RU5cE 'LastzRepeatMaskJob' l/3/jobKd__k1 'LastzRepeatMaskJob' 8/l/jobsJkMii 'LastzRepeatMaskJob' 6/G/jobFcbTKF 'AlignFastaFragments' t/N/jobeu9Yr3 'AlignFastaFragments' 2/W/jobsXp8r2 'PreprocessChunk' 0/T/job4AqmEU 'AlignFastaFragments' a/j/jobVLQNfT 'AlignFastaFragments' Q/j/jobFVQb9R 'AlignFastaFragments' v/n/jobKHy6_L 'LastzRepeatMaskJob' w/0/jobf7Y9ks 'PreprocessChunk' T/P/jobkvKai9 'LastzRepeatMaskJob' 9/d/jobmeNi6p 'PreprocessChunk' m/x/jobBQ2uNt 'LastzRepeatMaskJob' y/N/jobckRI02 'AlignFastaFragments' h/3/jobRnoNMR 'LastzRepeatMaskJob' h/z/jobuRLpen 'LastzRepeatMaskJob' A/H/jobUrSX0b 'AlignFastaFragments' c/n/jobQULy4e 'LastzRepeatMaskJob' O/v/job6ax2zn 'PreprocessChunk' k/J/jobIX7lVA 'AlignFastaFragments' U/h/job1yBM2x 'AlignFastaFragments' D/M/jobhtbfgC 'LastzRepeatMaskJob' v/y/jobJoYz4J 'LastzRepeatMaskJob' g/e/jobs2ZXAn 'LastzRepeatMaskJob' k/n/jobCNaSx6 'LastzRepeatMaskJob' 0/W/jobrbIbUj 'PreprocessChunk' z/C/jobZPiYOj 'AlignFastaFragments' 1/e/jobppIxsq 'LastzRepeatMaskJob' p/d/job215ljC 'PreprocessChunk' H/Z/jobzsEXm_ 'LastzRepeatMaskJob' n/u/jobOYeKNb 'BatchPreprocessor' 5/A/jobiNAUie 'AlignFastaFragments' 1/n/job3DI2JJ 'PreprocessChunk' Q/f/jobZ2Cptd 'AlignFastaFragments' d/v/job3YL83X 'LastzRepeatMaskJob' v/z/job4aSNdO 'LastzRepeatMaskJob' F/o/jobUQaTSk 'PreprocessChunk' d/s/job7jc9a8 'LastzRepeatMaskJob' E/Y/jobYdMsvY 'LastzRepeatMaskJob' d/V/job7rsP_h 'PreprocessChunk' Q/A/joblTjvWG 'LastzRepeatMaskJob' B/e/jobELQfgW 'PreprocessChunk' I/S/jobZo43mA 'LastzRepeatMaskJob' f/R/job4Ve4Ru 'AlignFastaFragments' L/K/job0LHl7m 'LastzRepeatMaskJob' p/r/job336ZpW 'LastzRepeatMaskJob' 8/g/jobi649op 'AlignFastaFragments' X/b/jobg_v3dn
2018-09-20 19:06:41,545 - toil.leader - INFO - Failed jobs at end of the run: 'LastzRepeatMaskJob' w/w/jobZYX4Tq 'PreprocessChunk' m/q/jobK95ZUe 'PreprocessChunk' b/p/jobvTlHBj 'PreprocessChunk' D/x/jobAib6H_ 'AlignFastaFragments' 1/6/jobAk2H2d 'PreprocessChunk' l/L/job05R5vX 'PreprocessChunk' 8/0/jobNKMQEY 'AlignFastaFragments' z/A/jobpMdRje 'AlignFastaFragments' F/1/jobZjvtUf 'PreprocessChunk' E/3/jobemSYvt 'PreprocessChunk' T/K/jobCauPza 'LastzRepeatMaskJob' u/4/jobKOJM3c 'PreprocessChunk' M/D/jobnSITFA 'LastzRepeatMaskJob' S/B/jobw5CAnJ 'PreprocessChunk' Y/H/jobHQ0Ggh 'AlignFastaFragments' f/F/jobwaU8cm 'PreprocessChunk' 1/B/jobuzKAMQ 'LastzRepeatMaskJob' 3/n/jobzU07_L 'LastzRepeatMaskJob' W/1/job1C21z_ 'PreprocessChunk' k/K/jobTGDBP0 'PreprocessChunk' r/a/jobTIYlKw 'AlignFastaFragments' q/F/jobFH_1gx 'PreprocessChunk' p/W/jobMPuzTa 'AlignFastaFragments' 2/M/job90lCeH 'AlignFastaFragments' c/x/jobVxW9uN 'AlignFastaFragments' q/q/jobwxsXuN 'LastzRepeatMaskJob' g/V/jobkrK3kR 'AlignFastaFragments' k/u/jobUONjxk 'AlignFastaFragments' g/x/jobQUVOPS 'LastzRepeatMaskJob' K/6/jobmgYEdj 'LastzRepeatMaskJob' N/L/jobDbGikg 'PreprocessChunk' f/j/jobpJH0hA 'PreprocessChunk' M/m/jobJk_pXH 'LastzRepeatMaskJob' Q/x/jobGDLwwS 'PreprocessChunk' 6/U/jobOSIV1V 'LastzRepeatMaskJob' I/x/jobi83QgC 'AlignFastaFragments' S/J/jobJtcHOE 'PreprocessChunk' y/E/job9YU0SK 'LastzRepeatMaskJob' e/w/jobn1p7GK 'AlignFastaFragments' s/n/jobKK_5LJ 'LastzRepeatMaskJob' o/b/jobygmBKj 'AlignFastaFragments' P/8/jobfYNi9Y 'LastzRepeatMaskJob' S/Z/jobeiNFB_ 'PreprocessChunk' n/E/jobYEarIS 'AlignFastaFragments' b/S/jobv3F6b5 'PreprocessChunk' d/x/jobsJpxYT 'LastzRepeatMaskJob' w/h/jobAocZlR 'LastzRepeatMaskJob' O/R/jobcn4djw 'PreprocessChunk' X/P/jobzM6KxI 'LastzRepeatMaskJob' T/o/jobvyrXQy 'LastzRepeatMaskJob' c/9/jobJR0ljq 'LastzRepeatMaskJob' q/R/jobjzJUYQ 'AlignFastaFragments' T/G/job0nqUM3 'LastzRepeatMaskJob' 9/L/jobRBf6a5 'AlignFastaFragments' u/d/job0zgSP9 'PreprocessChunk' 5/M/job0OQ9i3 'PreprocessChunk' f/p/jobG7R7pc 'LastzRepeatMaskJob' p/C/jobtOQ_5P 'AlignFastaFragments' X/j/jobNcPWNZ 'LastzRepeatMaskJob' c/L/jobNx_V9T 'PreprocessChunk' h/y/jobaieQr7 'AlignFastaFragments' I/i/joboiJS3e 'PreprocessChunk' I/b/jobdwfpb1 'PreprocessChunk' 4/A/joboXoNrA 'LastzRepeatMaskJob' 1/L/jobQSVi1X 'PreprocessChunk' t/k/jobaJOOAP 'PreprocessChunk' e/N/job811xWO 'AlignFastaFragments' X/s/jobDN9_x1 'PreprocessChunk' z/t/job4VJHIc 'RunCactusPreprocessorThenProgressiveDown' B/H/jobPu8wcG 'AlignFastaFragments' i/d/jobBKmOCa 'AlignFastaFragments' b/5/jobEVQMrL 'LastzRepeatMaskJob' n/9/jobTltu9r 'AlignFastaFragments' L/C/jobKSRZMS 'LastzRepeatMaskJob' F/J/jobvcg9y0 'AlignFastaFragments' 1/m/job77VT2y 'LastzRepeatMaskJob' O/F/jobGwQd5b 'LastzRepeatMaskJob' y/M/jobN8w3yW 'AlignFastaFragments' P/Z/jobG2Lhmr 'AlignFastaFragments' 9/j/jobjFaZo6 'PreprocessChunk' w/y/jobvWD5Se 'AlignFastaFragments' E/j/job21GByO 'LastzRepeatMaskJob' 9/k/jobeLRKe4 'PreprocessChunk' D/C/jobk4WfzB 'AlignFastaFragments' O/J/jobsY1DUq 'LastzRepeatMaskJob' 9/g/jobT8s4xi 'LastzRepeatMaskJob' i/p/jobC8dbHk 'LastzRepeatMaskJob' j/K/jobBSbbpd 'AlignFastaFragments' n/F/jobqRdF4t 'PreprocessChunk' p/Z/jobDVQuvF 'LastzRepeatMaskJob' U/f/job2NcdLw 'PreprocessChunk' O/2/job4MgAdt 'PreprocessChunk' c/f/jobLTDNVI 'AlignFastaFragments' t/y/jobr8VTza 'AlignFastaFragments' T/l/jobTY5fiw 'LastzRepeatMaskJob' a/G/jobox0SNb 'PreprocessChunk' Q/F/joblFUZVM 'PreprocessChunk' m/m/jobWvH3Co 'LastzRepeatMaskJob' U/Z/jobyrpG5c 'BatchPreprocessor' J/b/jobBEWUPr 'AlignFastaFragments' o/D/jobYGxTHF 'LastzRepeatMaskJob' l/5/jobzwwhUV 'PreprocessSequence' 5/G/jobI3j3jj 'LastzRepeatMaskJob' t/J/jobyVcWkO 'AlignFastaFragments' T/k/jobNnWrvg 'LastzRepeatMaskJob' R/y/job402Zbc 'AlignFastaFragments' T/f/jobh9sDd5 'PreprocessChunk' Z/y/jobTb2yJP 'PreprocessChunk' R/N/jobjzqAXK 'AlignFastaFragments' g/W/jobAmOfjo 'AlignFastaFragments' b/F/jobEZ7ywS 'LastzRepeatMaskJob' v/b/jobUH8pwg 'LastzRepeatMaskJob' 5/P/jobWACd20 'PreprocessChunk' x/B/jobtpU3R_ 'PreprocessChunk' v/b/job_JeAc4 'PreprocessChunk' 2/1/joblbf8k_ 'PreprocessChunk' 0/6/jobupZjzw 'LastzRepeatMaskJob' z/u/jobXPF_Ir 'AlignFastaFragments' D/V/jobU5clmr 'AlignFastaFragments' r/N/jobxLTxuZ 'AlignFastaFragments' B/8/job2S8brV 'AlignFastaFragments' D/n/jobeXAA45 'LastzRepeatMaskJob' P/I/jobIyRO_u 'PreprocessChunk' r/7/jobGkYy59 'PreprocessChunk' x/M/jobjy8Hr8 'PreprocessChunk' 2/w/jobzVZDQa 'PreprocessChunk' X/u/job1ncaQB 'LastzRepeatMaskJob' K/v/jobr2ouih 'PreprocessChunk' 5/M/jobUj6RG4 'LastzRepeatMaskJob' e/7/jobE7JOw7 'AlignFastaFragments' a/Q/jobHtaJgg 'AlignFastaFragments' P/x/jobTyS_Jq 'LastzRepeatMaskJob' h/o/jobT72Zt3 'PreprocessChunk' G/1/jobzRT8H9 'LastzRepeatMaskJob' e/c/jobZdSw6x 'AlignFastaFragments' b/w/jobL05ycC 'PreprocessChunk' O/F/jobF9i5kG 'AlignFastaFragments' y/5/jobfLPrlg 'PreprocessChunk' R/G/job3Vjxhu 'AlignFastaFragments' Q/g/job0SDpU3 'AlignFastaFragments' 9/F/jobiqgVdd 'LastzRepeatMaskJob' S/C/job6Rc9KJ 'AlignFastaFragments' q/o/jobQMER_p 'PreprocessChunk' 8/H/jobvjBouh 'PreprocessChunk' m/z/jobInu4ma 'LastzRepeatMaskJob' H/n/jobYm1I61 'AlignFastaFragments' V/2/joby1iM2s 'LastzRepeatMaskJob' K/l/jobYHkrW2 'PreprocessChunk' O/c/job0AW0Ot 'LastzRepeatMaskJob' r/N/jobzHJEek 'PreprocessChunk' r/f/job73MQSC 'AlignFastaFragments' 9/n/job4OIwff 'AlignFastaFragments' o/q/jobJekTFK 'LastzRepeatMaskJob' R/4/job6KUKyx 'LastzRepeatMaskJob' 3/T/jobYKvexQ 'AlignFastaFragments' f/V/jobglAw8H 'LastzRepeatMaskJob' g/m/jobk9MkbW 'AlignFastaFragments' S/2/jobmVff53 'PreprocessChunk' 6/0/jobvyt3Bn 'LastzRepeatMaskJob' M/n/jobZPVYYU 'PreprocessChunk' d/a/jobAxi7Vi 'PreprocessChunk' b/w/jobrBUs_l 'AlignFastaFragments' 0/G/jobJ7U4R5 'AlignFastaFragments' L/K/jobWDWj9u 'LastzRepeatMaskJob' g/2/jobe0HLHo 'AlignFastaFragments' A/W/jobifTNFO 'PreprocessChunk' d/r/job14zL74 'PreprocessChunk' M/l/jobL7fz5E 'LastzRepeatMaskJob' f/P/jobH9QAzr 'LastzRepeatMaskJob' I/v/jobZmqk_a 'AlignFastaFragments' d/u/jobjjnz8s 'PreprocessChunk' r/C/jobrboBrZ 'PreprocessChunk' F/z/jobz3YHXr 'AlignFastaFragments' h/Y/jobbLz23Y 'LastzRepeatMaskJob' E/1/jobnDteom 'AlignFastaFragments' g/j/jobHhzdKb 'LastzRepeatMaskJob' e/o/jobKf6W6g 'PreprocessChunk' J/S/jobg99ARj 'AlignFastaFragments' q/a/job8Fcnvi 'AlignFastaFragments' U/O/jobWewBTJ 'AlignFastaFragments' q/9/jobMWLSJH 'LastzRepeatMaskJob' v/I/job3h_mcO 'LastzRepeatMaskJob' C/S/job9QFpv8 'AlignFastaFragments' e/r/jobtF8tHm 'PreprocessChunk' E/Z/jobDBHCBG 'AlignFastaFragments' Q/C/jobpc62Ib 'PreprocessChunk' 5/d/jobKOpXj6 'AlignFastaFragments' H/x/jobJ_v8Wb 'PreprocessChunk' B/f/jobzj275b 'PreprocessChunk' 5/X/jobeLsmWh 'CactusPreprocessor' U/S/jobC7AAEO 'PreprocessChunk' C/Q/job2b_rXR 'PreprocessChunk' 1/G/jobgqcAGw 'AlignFastaFragments' d/r/jobfiP3v6 'PreprocessChunk' s/w/job3xSrYI 'AlignFastaFragments' k/P/joby_d4PU 'PreprocessChunk' h/v/jobPrnp5D 'AlignFastaFragments' 9/c/job0XwaiT 'AlignFastaFragments' 2/9/jobHHA6px 'AlignFastaFragments' R/0/joby0ayoy 'PreprocessChunk' 8/K/jobDmxFMe 'PreprocessChunk' l/q/jobTEifZX 'PreprocessChunk' i/W/jobNesQSj 'CactusPreprocessor2' I/P/job6RU5cE 'LastzRepeatMaskJob' l/3/jobKd__k1 'LastzRepeatMaskJob' 8/l/jobsJkMii 'LastzRepeatMaskJob' 6/G/jobFcbTKF 'AlignFastaFragments' t/N/jobeu9Yr3 'AlignFastaFragments' 2/W/jobsXp8r2 'PreprocessChunk' 0/T/job4AqmEU 'AlignFastaFragments' a/j/jobVLQNfT 'AlignFastaFragments' Q/j/jobFVQb9R 'AlignFastaFragments' v/n/jobKHy6_L 'LastzRepeatMaskJob' w/0/jobf7Y9ks 'PreprocessChunk' T/P/jobkvKai9 'LastzRepeatMaskJob' 9/d/jobmeNi6p 'PreprocessChunk' m/x/jobBQ2uNt 'LastzRepeatMaskJob' y/N/jobckRI02 'AlignFastaFragments' h/3/jobRnoNMR 'LastzRepeatMaskJob' h/z/jobuRLpen 'LastzRepeatMaskJob' A/H/jobUrSX0b 'AlignFastaFragments' c/n/jobQULy4e 'LastzRepeatMaskJob' O/v/job6ax2zn 'PreprocessChunk' k/J/jobIX7lVA 'AlignFastaFragments' U/h/job1yBM2x 'AlignFastaFragments' D/M/jobhtbfgC 'LastzRepeatMaskJob' v/y/jobJoYz4J 'LastzRepeatMaskJob' g/e/jobs2ZXAn 'LastzRepeatMaskJob' k/n/jobCNaSx6 'LastzRepeatMaskJob' 0/W/jobrbIbUj 'PreprocessChunk' z/C/jobZPiYOj 'AlignFastaFragments' 1/e/jobppIxsq 'LastzRepeatMaskJob' p/d/job215ljC 'PreprocessChunk' H/Z/jobzsEXm_ 'LastzRepeatMaskJob' n/u/jobOYeKNb 'BatchPreprocessor' 5/A/jobiNAUie 'AlignFastaFragments' 1/n/job3DI2JJ 'PreprocessChunk' Q/f/jobZ2Cptd 'AlignFastaFragments' d/v/job3YL83X 'LastzRepeatMaskJob' v/z/job4aSNdO 'LastzRepeatMaskJob' F/o/jobUQaTSk 'PreprocessChunk' d/s/job7jc9a8 'LastzRepeatMaskJob' E/Y/jobYdMsvY 'LastzRepeatMaskJob' d/V/job7rsP_h 'PreprocessChunk' Q/A/joblTjvWG 'LastzRepeatMaskJob' B/e/jobELQfgW 'PreprocessChunk' I/S/jobZo43mA 'LastzRepeatMaskJob' f/R/job4Ve4Ru 'AlignFastaFragments' L/K/job0LHl7m 'LastzRepeatMaskJob' p/r/job336ZpW 'LastzRepeatMaskJob' 8/g/jobi649op 'AlignFastaFragments' X/b/jobg_v3dn
Traceback (most recent call last):
  File "/home/fc464/software/cactus/cactus_env/bin/cactus", line 11, in <module>
    sys.exit(main())
  File "/home/fc464/software/cactus/cactus_env/lib/python2.7/site-packages/cactus/progressive/cactus_progressive.py", line 493, in main
    halID = toil.start(RunCactusPreprocessorThenProgressiveDown(options, project, memory=configWrapper.getDefaultMemory()))
  File "/home/fc464/software/cactus/cactus_env/lib/python2.7/site-packages/toil/common.py", line 783, in start
    return self._runMainLoop(rootJobGraph)
  File "/home/fc464/software/cactus/cactus_env/lib/python2.7/site-packages/toil/common.py", line 1057, in _runMainLoop
    jobCache=self._jobCache).run()
  File "/home/fc464/software/cactus/cactus_env/lib/python2.7/site-packages/toil/leader.py", line 242, in run
    raise FailedJobsException(self.config.jobStore, self.toilState.totalFailedJobs, self.jobStore)
toil.leader.FailedJobsException

```

The whole log is attached.
F
[Cactus.slurm.log](https://github.com/ComparativeGenomicsToolkit/cactus/files/2404623/Cactus.slurm.log)

**Comment by francicco** [comment]
What about something like this?
<img width="1111" alt="screen shot 2018-09-21 at 10 36 46" src="https://user-images.githubusercontent.com/9006870/45873405-5096d980-bd8a-11e8-8376-5bbea04763fb.png">
