### ISSUE TITLE
Problem installing

### ISSUE THREAD

**Issue by EdYSChuang815** [ComparativeGenomicsToolkit/cactus#430]
I'm trying to install it from the Precompiled Binaries.
After setting up the virtual environment, I stuck at this step:

```
pip install -U -r ./toil-requirement.txt
```
It gives the following error message:
```
[all]==4.2.0->-r ./toil-requirement.txt (line 1)) (5.8.0)
Collecting addict<=2.2.0
  Downloading addict-2.2.0.tar.gz (5.1 kB)
    ERROR: Command errored out with exit status 1:
     command: /work/workspaces/edchuang/pyenv36/bin/python3.6 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-vu0bo2ft/addict_e6123a375e85445e8addaad9759cc46a/setup.py'"'"'; __file__='"'"'/tmp/pip-install-vu0bo2ft/addict_e6123a375e85445e8addaad9759cc46a/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-bnesda7t
         cwd: /tmp/pip-install-vu0bo2ft/addict_e6123a375e85445e8addaad9759cc46a/
    Complete output (11 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/work/workspaces/edchuang/pyenv36/lib/python3.6/site-packages/setuptools/__init__.py", line 18, in <module>
        from setuptools.dist import Distribution
      File "/work/workspaces/edchuang/pyenv36/lib/python3.6/site-packages/setuptools/dist.py", line 32, in <module>
        from setuptools import windows_support
      File "/work/workspaces/edchuang/pyenv36/lib/python3.6/site-packages/setuptools/windows_support.py", line 2, in <module>
        import ctypes
      File "/work/workspaces/mvidal/localpython36/lib/python3.6/ctypes/__init__.py", line 7, in <module>
        from _ctypes import Union, Structure, Array
    ImportError: libffi.so.5: cannot open shared object file: No such file or directory
    ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/ca/25/784dc859c978401cb7fba2ad3a29bb51a989abb618b8558cbc89dc2a8a5f/addict-2.2.0.tar.gz#sha256=57c41c427cb355e17f01d836a47aeae51e2175cf334e5d58e78476c77b224da1 (from https://pypi.org/simple/addict/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

Did anyone encounter same problem and knows how to fix it?

**Comment by glennhickey** [comment]
I haven't seen this before.  Searching around for those types of errors makes it seem like a problem with your python environment.

**Comment by EdYSChuang815** [comment]
I find out that it seems to be the problem installing toil. It seems that now it's impossible to install toil in my environment. Thank you for your reply.

**Comment by diekhans** [comment]
I believe your python is compiled without FFI support or the FFI libraries are somehow missing.  See python documentation for details.

**Comment by EdYSChuang815** [comment]
@diekhans Thank you for you reply. I just installed libffi but it still doesn't work.
