### ISSUE TITLE
error, possibly with newick tree

### ISSUE THREAD

**Issue by jodyhey** [ComparativeGenomicsToolkit/cactus#439]
I installed cactus on linux 20.04 following instructions in BIN-INSTALL.md, except I used conda to create a python 3.6 environment.  The mammal example ran fine in about 40 minutes. 
Am trying a set of 36 Drosophila genomes (attached) 
[drosophila_cactus.txt](https://github.com/ComparativeGenomicsToolkit/cactus/files/6144717/drosophila_cactus.txt)

I get the following error,   thanks for help
J. Hey

(cactus) tuf29449@cstbioinform:~/p/drosophila/cactus$ cactus ./jobstore ./drosophila_cactus.txt ./drosophila_cactus.hal --realTimeLogging --binariesMode local
[2021-03-15T17:43:24-0400] [MainThread] [I] [cactus.progressive.projectWrapper] Using config from path /home/TU/tuf29449/.conda/envs/cactus/lib/python3.6/site-packages/cactus/cactus_progressive_config.xml.
Traceback (most recent call last):
  File "/home/TU/tuf29449/.conda/envs/cactus/bin/cactus", line 8, in <module>
    sys.exit(main())
  File "/home/TU/tuf29449/.conda/envs/cactus/lib/python3.6/site-packages/cactus/progressive/cactus_progressive.py", line 397, in main
    runCactusProgressive(options)
  File "/home/TU/tuf29449/.conda/envs/cactus/lib/python3.6/site-packages/cactus/progressive/cactus_progressive.py", line 413, in runCactusProgressive
    projWrapper.writeXml()
  File "/home/TU/tuf29449/.conda/envs/cactus/lib/python3.6/site-packages/cactus/progressive/projectWrapper.py", line 76, in writeXml
    root=self.options.root)
  File "/home/TU/tuf29449/.conda/envs/cactus/lib/python3.6/site-packages/cactus/progressive/cactus_createMultiCactusProject.py", line 263, in runCreateMultiCactusProject
    mcProj = createMCProject(tree, expTemplate, confTemplate, options)
  File "/home/TU/tuf29449/.conda/envs/cactus/lib/python3.6/site-packages/cactus/progressive/cactus_createMultiCactusProject.py", line 49, in createMCProject
    fillInOutgroups(mcProj, options.outgroupNames, config, alignmentRootId)
  File "/home/TU/tuf29449/.conda/envs/cactus/lib/python3.6/site-packages/cactus/progressive/cactus_createMultiCactusProject.py", line 87, in fillInOutgroups
    maxNumOutgroups=config.getMaxNumOutgroups())
  File "/home/TU/tuf29449/.conda/envs/cactus/lib/python3.6/site-packages/cactus/progressive/outgroup.py", line 218, in greedy
    assert existingOutgroupDist[sinkName] == dist
AssertionError

**Comment by glennhickey** [comment]
This looks like a duplicate of #355 (and #374)..  We really need to print a better error message.

**Comment by jodyhey** [comment]
Yes,  I removed the internal node labels and it is running.  Thanks.
