### ISSUE TITLE
LastzRepeatMaskJob failed jobs

### ISSUE THREAD

**Issue by francicco** [ComparativeGenomicsToolkit/cactus#44]
Hi, 

I'm testing Cactus. I already tried the example you provide and it works. Now I'm trying to use it on a very small dataset: 3 very closely related genomes, 2 of them the same species. Unfortunately Cactus is not work properly and returns me several warnings and errors. This is one of many.

```
WARNING:toil.leader:The job seems to have left a log file, indicating failure: 'AlignFastaFragments' N/C/jobdFq6BM
2018-09-26 12:31:07,637 - toil.leader - WARNING - The job seems to have left a log file, indicating failure: 'AlignFastaFragments' N/C/jobdFq6BM
WARNING:toil.leader:N/C/jobdFq6BM    INFO:toil.worker:---TOIL WORKER OUTPUT LOG---
2018-09-26 12:31:07,638 - toil.leader - WARNING - N/C/jobdFq6BM    INFO:toil.worker:---TOIL WORKER OUTPUT LOG---
WARNING:toil.leader:N/C/jobdFq6BM    INFO:toil:Running Toil version 3.17.0-585383ed5c4453b556269818571d3c7419c613b0.
2018-09-26 12:31:07,638 - toil.leader - WARNING - N/C/jobdFq6BM    INFO:toil:Running Toil version 3.17.0-585383ed5c4453b556269818571d3c7419c613b0.
WARNING:toil.leader:N/C/jobdFq6BM    WARNING:toil.resource:'JTRES_89337c6db946d31e57196f911b74762f' may exist, but is not yet referenced by the worker (KeyError from os.environ[]).
2018-09-26 12:31:07,639 - toil.leader - WARNING - N/C/jobdFq6BM    WARNING:toil.resource:'JTRES_89337c6db946d31e57196f911b74762f' may exist, but is not yet referenced by the worker (KeyError from os.environ[]).
WARNING:toil.leader:N/C/jobdFq6BM    INFO:cactus.shared.common:Work dirs: set([])
2018-09-26 12:31:07,639 - toil.leader - WARNING - N/C/jobdFq6BM    INFO:cactus.shared.common:Work dirs: set([])
WARNING:toil.leader:N/C/jobdFq6BM    INFO:cactus.shared.common:Docker work dir: .
2018-09-26 12:31:07,639 - toil.leader - WARNING - N/C/jobdFq6BM    INFO:cactus.shared.common:Docker work dir: .
WARNING:toil.leader:N/C/jobdFq6BM    INFO:cactus.shared.common:Running the command ['singularity', '--silent', 'run', u'/rds/user/fc464/hpc-work/TetramoriumProject/jobStore.Cactus.Talpestre3Genomes.Cactus/cactus.img', 'cPecanLastz', u'tmpnfN6c2.tmp[multiple][nameparse=darkspace]', u'tmpEguE1j.tmp[nameparse=darkspace]', '--querydepth=keep,nowarn:13', '--format=general:name1,zstart1,end1,name2,zstart2+,end2+', '--markend']
2018-09-26 12:31:07,639 - toil.leader - WARNING - N/C/jobdFq6BM    INFO:cactus.shared.common:Running the command ['singularity', '--silent', 'run', u'/rds/user/fc464/hpc-work/TetramoriumProject/jobStore.Cactus.Talpestre3Genomes.Cactus/cactus.img', 'cPecanLastz', u'tmpnfN6c2.tmp[multiple][nameparse=darkspace]', u'tmpEguE1j.tmp[nameparse=darkspace]', '--querydepth=keep,nowarn:13', '--format=general:name1,zstart1,end1,name2,zstart2+,end2+', '--markend']
WARNING:toil.leader:N/C/jobdFq6BM    Running command catchsegv 'cPecanLastz' 'tmpnfN6c2.tmp[multiple][nameparse=darkspace]' 'tmpEguE1j.tmp[nameparse=darkspace]' '--querydepth=keep,nowarn:13' '--format=general:name1,zstart1,end1,name2,zstart2+,end2+' '--markend'
2018-09-26 12:31:07,639 - toil.leader - WARNING - N/C/jobdFq6BM    Running command catchsegv 'cPecanLastz' 'tmpnfN6c2.tmp[multiple][nameparse=darkspace]' 'tmpEguE1j.tmp[nameparse=darkspace]' '--querydepth=keep,nowarn:13' '--format=general:name1,zstart1,end1,name2,zstart2+,end2+' '--markend'
WARNING:toil.leader:N/C/jobdFq6BM    FAILURE: bad fasta character in tmpnfN6c2.tmp, >scaffold_16|848048 (uppercase R)
2018-09-26 12:31:07,639 - toil.leader - WARNING - N/C/jobdFq6BM    FAILURE: bad fasta character in tmpnfN6c2.tmp, >scaffold_16|848048 (uppercase R)
WARNING:toil.leader:N/C/jobdFq6BM    remove or replace non-ACGTN characters or consider using --ambiguous=iupac
2018-09-26 12:31:07,640 - toil.leader - WARNING - N/C/jobdFq6BM    remove or replace non-ACGTN characters or consider using --ambiguous=iupac
WARNING:toil.leader:N/C/jobdFq6BM    Traceback (most recent call last):
2018-09-26 12:31:07,640 - toil.leader - WARNING - N/C/jobdFq6BM    Traceback (most recent call last):
WARNING:toil.leader:N/C/jobdFq6BM      File "/home/fc464/software/cactus/cactus_env/lib/python2.7/site-packages/toil/worker.py", line 314, in workerScript
2018-09-26 12:31:07,640 - toil.leader - WARNING - N/C/jobdFq6BM      File "/home/fc464/software/cactus/cactus_env/lib/python2.7/site-packages/toil/worker.py", line 314, in workerScript
WARNING:toil.leader:N/C/jobdFq6BM        job._runner(jobGraph=jobGraph, jobStore=jobStore, fileStore=fileStore)
2018-09-26 12:31:07,640 - toil.leader - WARNING - N/C/jobdFq6BM        job._runner(jobGraph=jobGraph, jobStore=jobStore, fileStore=fileStore)
WARNING:toil.leader:N/C/jobdFq6BM      File "/home/fc464/software/cactus/cactus_env/lib/python2.7/site-packages/cactus/shared/common.py", line 1082, in _runner
2018-09-26 12:31:07,640 - toil.leader - WARNING - N/C/jobdFq6BM      File "/home/fc464/software/cactus/cactus_env/lib/python2.7/site-packages/cactus/shared/common.py", line 1082, in _runner
WARNING:toil.leader:N/C/jobdFq6BM        super(RoundedJob, self)._runner(jobGraph=jobGraph, jobStore=jobStore, fileStore=fileStore)
2018-09-26 12:31:07,640 - toil.leader - WARNING - N/C/jobdFq6BM        super(RoundedJob, self)._runner(jobGraph=jobGraph, jobStore=jobStore, fileStore=fileStore)
WARNING:toil.leader:N/C/jobdFq6BM      File "/home/fc464/software/cactus/cactus_env/lib/python2.7/site-packages/toil/job.py", line 1350, in _runner
2018-09-26 12:31:07,640 - toil.leader - WARNING - N/C/jobdFq6BM      File "/home/fc464/software/cactus/cactus_env/lib/python2.7/site-packages/toil/job.py", line 1350, in _runner
WARNING:toil.leader:N/C/jobdFq6BM        returnValues = self._run(jobGraph, fileStore)
2018-09-26 12:31:07,640 - toil.leader - WARNING - N/C/jobdFq6BM        returnValues = self._run(jobGraph, fileStore)
WARNING:toil.leader:N/C/jobdFq6BM      File "/home/fc464/software/cactus/cactus_env/lib/python2.7/site-packages/toil/job.py", line 1295, in _run
2018-09-26 12:31:07,640 - toil.leader - WARNING - N/C/jobdFq6BM      File "/home/fc464/software/cactus/cactus_env/lib/python2.7/site-packages/toil/job.py", line 1295, in _run
WARNING:toil.leader:N/C/jobdFq6BM        return self.run(fileStore)
2018-09-26 12:31:07,640 - toil.leader - WARNING - N/C/jobdFq6BM        return self.run(fileStore)
WARNING:toil.leader:N/C/jobdFq6BM      File "/home/fc464/software/cactus/cactus_env/lib/python2.7/site-packages/cactus/preprocessor/lastzRepeatMasking/cactus_lastzRepeatMask.py", line 80, in run
2018-09-26 12:31:07,640 - toil.leader - WARNING - N/C/jobdFq6BM      File "/home/fc464/software/cactus/cactus_env/lib/python2.7/site-packages/cactus/preprocessor/lastzRepeatMasking/cactus_lastzRepeatMask.py", line 80, in run
WARNING:toil.leader:N/C/jobdFq6BM        "--markend"])
2018-09-26 12:31:07,640 - toil.leader - WARNING - N/C/jobdFq6BM        "--markend"])
WARNING:toil.leader:N/C/jobdFq6BM      File "/home/fc464/software/cactus/cactus_env/lib/python2.7/site-packages/cactus/shared/common.py", line 1026, in cactus_call
2018-09-26 12:31:07,641 - toil.leader - WARNING - N/C/jobdFq6BM      File "/home/fc464/software/cactus/cactus_env/lib/python2.7/site-packages/cactus/shared/common.py", line 1026, in cactus_call
WARNING:toil.leader:N/C/jobdFq6BM        raise RuntimeError("Command %s failed with output: %s" % (call, output))
2018-09-26 12:31:07,641 - toil.leader - WARNING - N/C/jobdFq6BM        raise RuntimeError("Command %s failed with output: %s" % (call, output))
WARNING:toil.leader:N/C/jobdFq6BM    RuntimeError: Command ['singularity', '--silent', 'run', u'/rds/user/fc464/hpc-work/TetramoriumProject/jobStore.Cactus.Talpestre3Genomes.Cactus/cactus.img', 'cPecanLastz', u'tmpnfN6c2.tmp[multiple][nameparse=darkspace]', u'tmpEguE1j.tmp[nameparse=darkspace]', '--querydepth=keep,nowarn:13', '--format=general:name1,zstart1,end1,name2,zstart2+,end2+', '--markend'] failed with output: None
2018-09-26 12:31:07,641 - toil.leader - WARNING - N/C/jobdFq6BM    RuntimeError: Command ['singularity', '--silent', 'run', u'/rds/user/fc464/hpc-work/TetramoriumProject/jobStore.Cactus.Talpestre3Genomes.Cactus/cactus.img', 'cPecanLastz', u'tmpnfN6c2.tmp[multiple][nameparse=darkspace]', u'tmpEguE1j.tmp[nameparse=darkspace]', '--querydepth=keep,nowarn:13', '--format=general:name1,zstart1,end1,name2,zstart2+,end2+', '--markend'] failed with output: None
WARNING:toil.leader:N/C/jobdFq6BM    ERROR:toil.worker:Exiting the worker because of a failed job on host cpu-e-470
2018-09-26 12:31:07,641 - toil.leader - WARNING - N/C/jobdFq6BM    ERROR:toil.worker:Exiting the worker because of a failed job on host cpu-e-470
WARNING:toil.leader:N/C/jobdFq6BM    WARNING:toil.jobGraph:Due to failure we are reducing the remaining retry count of job 'AlignFastaFragments' N/C/jobdFq6BM with ID N/C/jobdFq6BM to 5
2018-09-26 12:31:07,641 - toil.leader - WARNING - N/C/jobdFq6BM    WARNING:toil.jobGraph:Due to failure we are reducing the remaining retry count of job 'AlignFastaFragments' N/C/jobdFq6BM with ID N/C/jobdFq6BM to 5
```

The whole log is attached.
F

[Cactus.slurm.log](https://github.com/ComparativeGenomicsToolkit/cactus/files/2419665/Cactus.slurm.log)

**Comment by francicco** [comment]
Hi @joelarmstrong,

I'm very sorry to bother you, but I can't make Cactus work. I tried using progressiveCactus for the same dataset and it seems to work, so I guess the problem in is Cactus itself. Would you please help me with these series of errors?

```
2018-09-27 08:58:37,349 - toil.leader - INFO - Job ended successfully: 'CactusAVGWrapper' v/w/job_HcYTp
WARNING:toil.leader:The job seems to have left a log file, indicating failure: 'CactusAVGWrapper' v/w/job_HcYTp
2018-09-27 08:58:37,351 - toil.leader - WARNING - The job seems to have left a log file, indicating failure: 'CactusAVGWrapper' v/w/job_HcYTp
WARNING:toil.leader:v/w/job_HcYTp    ower
2018-09-27 08:58:37,351 - toil.leader - WARNING - v/w/job_HcYTp    ower
WARNING:toil.leader:v/w/job_HcYTp    Constructed the block trees for the non-trivial chains in the flower in: 0 seconds
2018-09-27 08:58:37,351 - toil.leader - WARNING - v/w/job_HcYTp    Constructed the block trees for the non-trivial chains in the flower in: 0 seconds
WARNING:toil.leader:v/w/job_HcYTp    Constructed the block trees for the trivial chains in the flower in: 0 seconds
2018-09-27 08:58:37,351 - toil.leader - WARNING - v/w/job_HcYTp    Constructed the block trees for the trivial chains in the flower in: 0 seconds
WARNING:toil.leader:v/w/job_HcYTp    Started Bernard's function
2018-09-27 08:58:37,351 - toil.leader - WARNING - v/w/job_HcYTp    Started Bernard's function
WARNING:toil.leader:v/w/job_HcYTp    	BN start: 0 of 1
2018-09-27 08:58:37,351 - toil.leader - WARNING - v/w/job_HcYTp    	BN start: 0 of 1
WARNING:toil.leader:v/w/job_HcYTp    	End the loop
2018-09-27 08:58:37,351 - toil.leader - WARNING - v/w/job_HcYTp    	End the loop
WARNING:toil.leader:v/w/job_HcYTp    Ended Bernard's function
2018-09-27 08:58:37,352 - toil.leader - WARNING - v/w/job_HcYTp    Ended Bernard's function
WARNING:toil.leader:v/w/job_HcYTp    Augmented the block trees in: 0 seconds
2018-09-27 08:58:37,352 - toil.leader - WARNING - v/w/job_HcYTp    Augmented the block trees in: 0 seconds
WARNING:toil.leader:v/w/job_HcYTp    Filled in end trees and augmented the event trees for the child flowers in: 0 seconds
2018-09-27 08:58:37,352 - toil.leader - WARNING - v/w/job_HcYTp    Filled in end trees and augmented the event trees for the child flowers in: 0 seconds
WARNING:toil.leader:v/w/job_HcYTp    Processing a flower
2018-09-27 08:58:37,352 - toil.leader - WARNING - v/w/job_HcYTp    Processing a flower
WARNING:toil.leader:v/w/job_HcYTp    Constructed the block trees for the non-trivial chains in the flower in: 0 seconds
2018-09-27 08:58:37,352 - toil.leader - WARNING - v/w/job_HcYTp    Constructed the block trees for the non-trivial chains in the flower in: 0 seconds
WARNING:toil.leader:v/w/job_HcYTp    Constructed the block trees for the trivial chains in the flower in: 0 seconds
2018-09-27 08:58:37,352 - toil.leader - WARNING - v/w/job_HcYTp    Constructed the block trees for the trivial chains in the flower in: 0 seconds
```

Here the complete log

[CACTUS.failed.log](https://github.com/ComparativeGenomicsToolkit/cactus/files/2425529/CACTUS.failed.log)
 
Thanks for your help.
F

**Comment by joelarmstrong** [comment]
Hi Francesco,

Apologies for the delay, just had time to catch up on email today.

The key part of the first error is: `FAILURE: bad fasta character in tmpnfN6c2.tmp, >scaffold_16|848048 (uppercase R)`. Basically, we only allow either fully ambiguous or unambiguous nucleotides (ACGTN); characters like R represent a possibility of a few but not all nucleotides, which we don't have support for.

The second error is interesting. Are you running with a custom config file (using the `--config` parameter)? This AVG code should not be running--it's disabled by default, because it can only be used in very specific situations.

**Comment by francicco** [comment]
Yes, I spotted and fixed the first error, but for the second I'm not using that flag. I'm running Cactus like this

```
cactus $BATCHSYSTEM $RESTART --buildAvgs --maxMemory $MEM --stats --maxMemory $MEM \
                --maxCores $THREADS --binariesMode singularity $TMPDIR $CONFIG $OUTHAL.hal
```

**Comment by joelarmstrong** [comment]
Ah, sorry about that!, the `--buildAvgs` option has the same effect as a custom config file enabling the AVG functionality. I didn't even realize we still exposed the option, it's left over from a previous version. I'll disable that option, because right now it has no real use except to crash the program.

But in the meantime, if you rerun without using `--buildAvgs`, you should hopefully be able to run it without problems.

**Comment by francicco** [comment]
Great! It looks like it worked!!!
Now I try a bigger dataset.
Thank you for your support!
F
