### ISSUE TITLE
Consistent Error? assert len(genomeNodes) == 1 

### ISSUE THREAD

**Issue by Jome0169** [ComparativeGenomicsToolkit/cactus#448]
Hello,

I've been using  cactus, and have recently hit a snag. I've added additional species to the alignment and went from 8 genomes to 11. However after attempting to run progressive cactus I'm greeted with the below error:

```
=========>
        [2021-03-28T17:36:17-0400] [MainThread] [I] [toil.worker] ---TOIL WORKER OUTPUT LOG---
        [2021-03-28T17:36:17-0400] [MainThread] [I] [toil] Running Toil version 4.2.0-3aa1da130141039cb357efe36d7df9b9f6ae9b5b on host d4-12.compute.lan.
        [2021-03-28T17:36:17-0400] [MainThread] [I] [cactus.progressive.cactus_progressive] Progressive Up: 0.0295389
        [2021-03-28T17:36:17-0400] [MainThread] [I] [cactus.progressive.cactus_progressive] Sequences in progressive, 0.0295389: ['oryza_sativa', 'Zm-B73']
        Traceback (most recent call last):
          File "/usr/local/lib/python3.6/dist-packages/toil/worker.py", line 368, in workerScript
            job._runner(jobGraph=jobGraph, jobStore=jobStore, fileStore=fileStore, defer=defer)
          File "/usr/local/lib/python3.6/dist-packages/cactus/shared/common.py", line 1369, in _runner
            super(RoundedJob, self)._runner(jobGraph=jobGraph, jobStore=jobStore, fileStore=fileStore, defer=defer)
          File "/usr/local/lib/python3.6/dist-packages/toil/job.py", line 1424, in _runner
            returnValues = self._run(jobGraph, fileStore)
          File "/usr/local/lib/python3.6/dist-packages/toil/job.py", line 1361, in _run
            return self.run(fileStore)
          File "/usr/local/lib/python3.6/dist-packages/cactus/progressive/cactus_progressive.py", line 189, in run
            workFlowArgs = CactusWorkflowArguments(self.options, experimentFile=experimentFile, configNode=configNode, seqIDMap = seqIDMap)
          File "/usr/local/lib/python3.6/dist-packages/cactus/pipeline/cactus_workflow.py", line 1378, in __init__
            self.experimentWrapper.setSequenceID(genome, seqID)
          File "/usr/local/lib/python3.6/dist-packages/cactus/shared/experimentWrapper.py", line 354, in setSequenceID
            assert len(genomeNodes) == 1
        AssertionError
        [2021-03-28T17:36:17-0400] [MainThread] [E] [toil.worker] Exiting the worker because of a failed job on host d4-12.compute.lan
        ('setting this', 'oryza_sativa', 'files/for-job/kind-MergeChunks2/instance-grynzyyy/file-mw2cbxhl/tmp8zal6kt_.tmp')
<=========
Traceback (most recent call last):
  File "/usr/local/bin/cactus", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.6/dist-packages/cactus/progressive/cactus_progressive.py", line 386, in main
    runCactusProgressive(options)
  File "/usr/local/lib/python3.6/dist-packages/cactus/progressive/cactus_progressive.py", line 434, in runCactusProgressive
    halID = toil.start(RunCactusPreprocessorThenProgressiveDown(options, project, memory=configWrapper.getDefaultMemory()))
  File "/usr/local/lib/python3.6/dist-packages/toil/common.py", line 846, in start
    return self._runMainLoop(rootJobGraph)
  File "/usr/local/lib/python3.6/dist-packages/toil/common.py", line 1138, in _runMainLoop
    jobCache=self._jobCache).run()
  File "/usr/local/lib/python3.6/dist-packages/toil/leader.py", line 235, in run
    self.innerLoop()
  File "/usr/local/lib/python3.6/dist-packages/toil/leader.py", line 567, in innerLoop
    self._gatherUpdatedJobs(updatedJobTuple)
  File "/usr/local/lib/python3.6/dist-packages/toil/leader.py", line 527, in _gatherUpdatedJobs
    self.processFinishedJob(jobID, exitStatus, wallTime=wallTime, exitReason=exitReason)
  File "/usr/local/lib/python3.6/dist-packages/toil/leader.py", line 920, in processFinishedJob
    StatsAndLogging.writeLogFiles(jobGraph.chainedJobs, logFileStream, self.config, failed=True)
  File "/usr/local/lib/python3.6/dist-packages/toil/statsAndLogging.py", line 132, in writeLogFiles
    with writeFn(fullName, 'wb') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'LOGS/failed_ProgressiveUp_kind--ProgressiveUp-instance--00c5_m8m000.log'

```

Initially I thought this error was related to #355 and #439 .  I went ahead and removed internal node labels from my newick tree file at the top of the file and I'm still greeted with the same error.

Here is the input evolver which I'm using.

```
((brachypodium_distachyon:0.126086,hordeum_vulgare:0.179736)0.0295389,(oryza_sativa:0.16186,(((saccharum_spontaneum:0.14352,sorghum_bicolor:0.0446281)0.0307306,Zm-B73:0.0888332)0.0453924,((panicum_halli:0.0244534,proso_millet:0.0376069)0.0425762,(setaria_virdis:0.00621369,setaria_italica:0.00843566)0.0562577)0.0332277)0.0735879)0.0295389);

*oryza_sativa /scratch/jpm73279/13.ACR_CNS_analysis/01.analysis/run_cactus/all_plant_genomes_final/Osativa_323_v7.0.softmasked.final.fa
*panicum_halli /scratch/jpm73279/13.ACR_CNS_analysis/01.analysis/run_cactus/all_plant_genomes_final/Phallii_495_v3.0.softmasked.final.fa
*sorghum_bicolor /scratch/jpm73279/13.ACR_CNS_analysis/01.analysis/run_cactus/all_plant_genomes_final/Sbicolor_454_v3.0.1.softmasked.final.fa
*setaria_italica /scratch/jpm73279/13.ACR_CNS_analysis/01.analysis/run_cactus/all_plant_genomes_final/Sitalica_312_v2.softmasked.final.fa
*setaria_virdis /scratch/jpm73279/13.ACR_CNS_analysis/01.analysis/run_cactus/all_plant_genomes_final/Sviridis_500_v2.0.softmasked.final.fa
*Zm-B73 /scratch/jpm73279/13.ACR_CNS_analysis/01.analysis/run_cactus/all_plant_genomes_final/Zm-B73-REFERENCE-NAM-5.0.final.fa
saccharum_spontaneum /scratch/jpm73279/13.ACR_CNS_analysis/01.analysis/run_cactus/all_plant_genomes_final/Sspontaneum.softmasked.final.fa
*proso_millet /scratch/jpm73279/13.ACR_CNS_analysis/01.analysis/run_cactus/all_plant_genomes_final/Pmiliaceum.softmasked.final.fa
*hordeum_vulgare /scratch/jpm73279/13.ACR_CNS_analysis/01.analysis/run_cactus/all_plant_genomes_final/Hvulgare_462_r1.softmasked.final.fa
*brachypodium_distachyon /scratch/jpm73279/13.ACR_CNS_analysis/01.analysis/run_cactus/all_plant_genomes_final/Bdistachyon_556_v3.0.softmasked.final.fa

```

Any input you have would be greatly appreciated.

**Comment by Jome0169** [comment]
Thanks @glennhickey that seems to have resolved the issues. For others running into similar issues spend some time reading over newick tree specifications - this helped me: https://evolution.genetics.washington.edu/phylip/newicktree.html
