### ISSUE TITLE
trouble installing cactus 

### ISSUE THREAD

**Issue by ShwethaMurali** [ComparativeGenomicsToolkit/cactus#45]
Hi there, if one does not have any of various dependencies already installed, which versions of the following do you suggest? 
kyoto 
lua 
lzo 
zlib 
gcc  
toil
I am having issues with installing cactus, and my group very much wants to use it , but I am having trouble installing it correctly. I even got it installed at one point, but  there was a discrepancy with the versions, which I couldn't trace down so I thought I'd just ask here beforehand. 
Thanks,
Shwetha

**Comment by joelarmstrong** [comment]
Just for reference, these are the corresponding versions we currently have in the cactus Docker container, so these should work:

kyototycoon: 0.9.56-1build2
lua: 5.1.5-8ubuntu1
lzo: 2.08-1.2
zlib: 1.2.8
gcc: 5.4.0
toil==3.17.0

**Comment by apredeus** [comment]
We're trying to install cactus on a HPC cluster (with no docker and no root privileges) and having a very hard time, too. So far the thing that worked best is making a conda virtual environment with python 2.7, and installing several dependencies there. However for the life of me I could not compile KyotoTycoon there - if you install lua to a non-standard location, it just refuses to find lua headers.. 

If there's a docker, would you consider making a bioconda recipe for this installation? I think it would save lots of headache to many users. Thank you!

**Comment by joelarmstrong** [comment]
Yeah, KyotoTycoon is a real PITA to compile. Kyototycoon doesn't seem to be maintained, currently, so not only does it have trouble with lua installs, it also doesn't compile with newer gcc versions. I'll look into adding a bioconda recipe.

**Comment by simonkidd** [comment]
Hi, after going to war with kyoto and appearing to win I'm having compile issues with Cactus as it's running through it's make. It appears to be stalling around building hdf5, any guidance would great help!

Thanks
S

CXX    H5CommonFG.lo
  CXX    H5Group.lo
  CXX    H5File.lo
  CXXLD  libhdf5_cpp.la
/.../gcc/5.5.0/lib/../lib/**libstdc++.so: could not read symbols: File in wrong format**
collect2: error: ld returned 1 exit status
make[3]: *** [libhdf5_cpp.la] Error 1
make[3]: Leaving directory `/.../Cactus-Install/submodules/hdf5/c++/src'
make[2]: *** [all-recursive] Error 1
make[2]: Leaving directory `/.../Cactus-Install/submodules/hdf5/c++'
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory `/.../Cactus-Install/submodules/hdf5'
make: *** [/.../Cactus-Install/submodules/hdf5/bin/h5c++] Error 1

As for Kyoto I managed to get the version below to install but only after while making some changes:
https://github.com/carlosefr/kyoto.git

Edit the Kyototycoon MYLDFLAGS entry in it's configure file: https://github.com/glennhickey/progressiveCactus/issues/27
> make PREFIX=/Install-Path/kyoto/20170410 KC_OPTIONS=/LZO-Install_path/lzo/2.10/include/lzo KT_OPTIONS=/LUA-Install-Path/lua/5.3.5/src

**Comment by amizeranschi** [comment]
Hi @joelarmstrong,

Are you still planning to create a bioconda recipe for cactus? It really would help a lot, given how difficult it is sometimes to compile it when using Docker isn't an option.

**Comment by nathanweeks** [comment]
Looks like a bioconda recipe was recently added: https://bioconda.github.io/recipes/cactus/README.html

**Comment by fmarletaz** [comment]
Hi - I did try the bioconda recipe, but when I try to run the example job, I end with the following error: 
```
cactus jobStore examples/evolverMammals.txt examples/evolverMammals.hal --root mr --binariesMode local
Logging set at level: INFO
Traceback (most recent call last):
  File "/home/f/fmarletaz/work/miniconda2/envs/cactus/bin/cactus", line 11, in <module>
    load_entry_point('progressiveCactus==1.0', 'console_scripts', 'cactus')()
  File "/home/f/fmarletaz/work/miniconda2/envs/cactus/lib/python2.7/site-packages/cactus/progressive/cactus_progressive.py", line 466, in main
    if options.deadlockWait is None or options.deadlockWait < 3600:
AttributeError: 'Namespace' object has no attribute 'deadlockWait'
```
I assumed Bioconda would install the local binaries, is there something I am missing?

**Comment by yuzhenpeng** [comment]
> Hi - I did try the bioconda recipe, but when I try to run the example job, I end with the following error:
> 
> ```
> cactus jobStore examples/evolverMammals.txt examples/evolverMammals.hal --root mr --binariesMode local
> Logging set at level: INFO
> Traceback (most recent call last):
>   File "/home/f/fmarletaz/work/miniconda2/envs/cactus/bin/cactus", line 11, in <module>
>     load_entry_point('progressiveCactus==1.0', 'console_scripts', 'cactus')()
>   File "/home/f/fmarletaz/work/miniconda2/envs/cactus/lib/python2.7/site-packages/cactus/progressive/cactus_progressive.py", line 466, in main
>     if options.deadlockWait is None or options.deadlockWait < 3600:
> AttributeError: 'Namespace' object has no attribute 'deadlockWait'
> ```
> 
> I assumed Bioconda would install the local binaries, is there something I am missing?

I also met the same warning with you. Do you had fix it now？

**Comment by mdondrup** [comment]
Hi, I am wondering if this is still being worked on. The conda package still faults. Would it be possible to make a recipe based on a recent  python3 version?

**Comment by amizeranschi** [comment]
Hi @mdondrup,

Please see this recent related thread: https://github.com/ComparativeGenomicsToolkit/cactus/issues/910
