### ISSUE TITLE
RuntimeError: Command: halPhyloP 

### ISSUE THREAD

**Issue by Rusfell** [ComparativeGenomicsToolkit/cactus#451]
Hi,

I'd like to run  halPhyloPMP.py with on neutral model, and I got an error like this:

root@d9b8d1004562:/data/neut_ver# halPhyloPMP.py --numProc 12 ../output/test.hal Medicago_truncatula neut4d_final_corrected_named.mod Medicago_truncatula_phyloP.wig
/bin/sh: 1: halPhyloP: not found
/bin/sh: 1: halPhyloP: not found
/bin/sh: 1: halPhyloP: not found
/bin/sh: 1: halPhyloP: not found
/bin/sh: 1: halPhyloP: not found
/bin/sh: 1: halPhyloP: not found
/bin/sh: 1: halPhyloP: not found
/bin/sh: 1: halPhyloP: not found
/bin/sh: 1: halPhyloP: not found
/bin/sh: 1: halPhyloP: not found
/bin/sh: 1: halPhyloP: not found
/bin/sh: 1: halPhyloP: not found
multiprocessing.pool.RemoteTraceback:
"""
Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "/usr/lib/python3.6/multiprocessing/pool.py", line 44, in mapstar
    return list(map(*args))
  File "/usr/local/lib/hal/stats/halStats.py", line 28, in runShellCommand
    (command, sts))
RuntimeError: Command: halPhyloP ../output/test.hal Medicago_truncatula neut4d_final_corrected_named.mod Medicago_truncatula_phyloP_halPhyloPTemp0RFOK_0.wig --start 0 --length 35834002 exited with non-zero status 127
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/hal/phyloP/halPhyloPMP.py", line 306, in <module>
    sys.exit(main())
  File "/usr/local/lib/hal/phyloP/halPhyloPMP.py", line 303, in main
    runParallelSlices(args)
  File "/usr/local/lib/hal/phyloP/halPhyloPMP.py", line 166, in runParallelSlices
    runParallelShellCommands(sliceCmds, options.numProc)
  File "/usr/local/lib/hal/stats/halStats.py", line 43, in runParallelShellCommands
    result.get(20000000)
  File "/usr/lib/python3.6/multiprocessing/pool.py", line 644, in get
    raise self._value
RuntimeError: Command: halPhyloP ../output/test.hal Medicago_truncatula neut4d_final_corrected_named.mod Medicago_truncatula_phyloP_halPhyloPTemp0RFOK_0.wig --start 0 --length 35834002 exited with non-zero status 127

cactus version is quay.io/comparative-genomics-toolkit/cactus:v1.3.0

How can I fix it?
I can find halPhyloPMP.py under /usr/local/lib/hal/phyloP, but where is halPhyloP?

**Comment by glennhickey** [comment]
The `halPhyloP` binary is not included in the Cactus release, unfortunately, so the only way to use it would be to [build it yourself](https://github.com/ComparativeGenomicsToolkit/hal#optional-support-of-phylop-evolutionary-constraint-annotation)

I don't think there's any particular reason for this other than nobody has had time to tackle it yet.  I will try to add it to the next release.

**Comment by Rusfell** [comment]
> The `halPhyloP` binary is not included in the Cactus release, unfortunately, so the only way to use it would be to [build it yourself](https://github.com/ComparativeGenomicsToolkit/hal#optional-support-of-phylop-evolutionary-constraint-annotation)
> 
> I don't think there's any particular reason for this other than nobody has had time to tackle it yet. I will try to add it to the next release.

Thanks a lot.
