### ISSUE TITLE
OSError: [Errno 28] No space left on device

### ISSUE THREAD

**Issue by Rusfell** [ComparativeGenomicsToolkit/cactus#457]
Hi,

I'd like to learn to use cactus with ratite data:

nohup cactus temp ratite.seqFile output/ratite.hal &

 and I got an error like this:

> OSError: [Errno 28] No space left on device: '/tmp/node-99f5f6d4-b056-49d2-827f-ab42bb93445c-e77b7035-f30b-43fb-969d-80179674a2a5/tmp2tukhvg3'
> 	[2021-03-25T02:43:36+0000] [MainThread] [E] [toil.worker] Exiting the worker because of a failed job on host 9192a259c70d
> <=========
> [2021-03-25T02:43:37+0000] [MainThread] [W] [toil.jobGraph] Due to failure we are reducing the remaining retry count of job 'RunBlast' kind-RunBlast/J/instance-2cew_d9m with ID kind-RunBlast/J/instance-2cew_d9m to 1
> [2021-03-25T02:43:37+0000] [MainThread] [W] [toil.jobGraph] We have increased the default memory of the failed job 'RunBlast' kind-RunBlast/J/instance-2cew_d9m to 2147483648 bytes
> [2021-03-25T02:43:37+0000] [MainThread] [W] [toil.jobGraph] We have increased the disk of the failed job 'RunBlast' kind-RunBlast/J/instance-2cew_d9m to the default of 2147483648 bytes
> [2021-03-25T02:43:37+0000] [MainThread] [I] [toil.leader] Issued job 'RunBlast' kind-RunBlast/J/instance-2cew_d9m with job batch system ID: 786824 and cores: 1, disk: 2.0 G, and memory: 2.0 G
> [2021-03-25T02:43:37+0000] [Thread-1  ] [E] [toil.batchSystems.singleMachine] Got exit code 1 (indicating failure) from job _toil_worker RunBlast file:/data/temp kind-RunBlast/S/instance-qv2gkfe8.
> [2021-03-25T02:43:37+0000] [MainThread] [W] [toil.leader] Job failed with exit value 1: 'RunBlast' kind-RunBlast/S/instance-qv2gkfe8
> [2021-03-25T02:43:37+0000] [MainThread] [W] [toil.leader] The job seems to have left a log file, indicating failure: 'RunBlast' kind-RunBlast/S/instance-qv2gkfe8
> [2021-03-25T02:43:37+0000] [MainThread] [W] [toil.leader] Log from job kind-RunBlast/S/instance-qv2gkfe8 follows:
> =========>
> 	[2021-03-25T02:43:17+0000] [MainThread] [I] [toil.worker] ---TOIL WORKER OUTPUT LOG---
> 	[2021-03-25T02:43:17+0000] [MainThread] [I] [toil] Running Toil version 4.2.0-3aa1da130141039cb357efe36d7df9b9f6ae9b5b on host 9192a259c70d.
> 	Traceback (most recent call last):
> 	  File "/usr/local/lib/python3.6/dist-packages/toil/worker.py", line 364, in workerScript
> 	    with fileStore.open(job):
> 	  File "/usr/lib/python3.6/contextlib.py", line 81, in __enter__
> 	    return next(self.gen)
> 	  File "/usr/local/lib/python3.6/dist-packages/toil/fileStores/nonCachingFileStore.py", line 60, in open
> 	    self.jobStateFile = self._createJobStateFile()
> 	  File "/usr/local/lib/python3.6/dist-packages/toil/fileStores/nonCachingFileStore.py", line 264, in _createJobStateFile
> 	    with open(jobStateFile + '.tmp', 'wb') as fH:
> 	OSError: [Errno 28] No space left on device: '/tmp/node-99f5f6d4-b056-49d2-827f-ab42bb93445c-e77b7035-f30b-43fb-969d-80179674a2a5/tmpghsoo_4_/5f1282e1-c506-426f-81b2-f3b9932109ec/.jobState.tmp'
> 	[2021-03-25T02:43:36+0000] [MainThread] [E] [toil.worker] Exiting the worker because of a failed job on host 9192a259c70d
> <=========
> [2021-03-25T02:43:37+0000] [MainThread] [W] [toil.jobGraph] Due to failure we are reducing the remaining retry count of job 'RunBlast' kind-RunBlast/S/instance-qv2gkfe8 with ID kind-RunBlast/S/instance-qv2gkfe8 to 1
> [2021-03-25T02:43:37+0000] [MainThread] [W] [toil.jobGraph] We have increased the default memory of the failed job 'RunBlast' kind-RunBlast/S/instance-qv2gkfe8 to 2147483648 bytes
> [2021-03-25T02:43:37+0000] [MainThread] [W] [toil.jobGraph] We have increased the disk of the failed job 'RunBlast' kind-RunBlast/S/instance-qv2gkfe8 to the default of 2147483648 bytes
> [2021-03-25T02:43:37+0000] [MainThread] [I] [toil.leader] Issued job 'RunBlast' kind-RunBlast/S/instance-qv2gkfe8 with job batch system ID: 786825 and cores: 1, disk: 2.0 G, and memory: 2.0 G
> [2021-03-25T02:43:37+0000] [Thread-1  ] [E] [toil.batchSystems.singleMachine] Got exit code 1 (indicating failure) from job _toil_worker RoundedJob file:/data/temp kind-RoundedJob/instance-17g1tl9d.
> [2021-03-25T02:43:37+0000] [MainThread] [W] [toil.leader] Job failed with exit value 1: 'RoundedJob' kind-RoundedJob/instance-17g1tl9d
> [2021-03-25T02:43:37+0000] [MainThread] [W] [toil.leader] The job seems to have left a log file, indicating failure: 'RoundedJob' kind-RoundedJob/instance-17g1tl9d
> [2021-03-25T02:43:37+0000] [MainThread] [W] [toil.leader] Log from job kind-RoundedJob/instance-17g1tl9d follows:
> =========>
> 	[2021-03-25T02:43:17+0000] [MainThread] [I] [toil.worker] ---TOIL WORKER OUTPUT LOG---
> 	[2021-03-25T02:43:17+0000] [MainThread] [I] [toil] Running Toil version 4.2.0-3aa1da130141039cb357efe36d7df9b9f6ae9b5b on host 9192a259c70d.
> 	Traceback (most recent call last):
> 	  File "/usr/local/lib/python3.6/dist-packages/toil/worker.py", line 364, in workerScript
> 	    with fileStore.open(job):
> 	  File "/usr/lib/python3.6/contextlib.py", line 81, in __enter__
> 	    return next(self.gen)
> 	  File "/usr/local/lib/python3.6/dist-packages/toil/fileStores/nonCachingFileStore.py", line 60, in open
> 	    self.jobStateFile = self._createJobStateFile()
> 	  File "/usr/local/lib/python3.6/dist-packages/toil/fileStores/nonCachingFileStore.py", line 261, in _createJobStateFile
> 	    jobState = {'jobProcessName': get_process_name(self.workDir),
> 	  File "/usr/local/lib/python3.6/dist-packages/toil/lib/threading.py", line 264, in get_process_name
> 	    nameFD, nameFileName = tempfile.mkstemp(dir=workDir)
> 	  File "/usr/lib/python3.6/tempfile.py", line 483, in mkstemp
> 	    return _mkstemp_inner(dir, prefix, suffix, flags, output_type)
> 	  File "/usr/lib/python3.6/tempfile.py", line 401, in _mkstemp_inner
> 	    fd = _os.open(file, flags, 0o600)
> 	OSError: [Errno 28] No space left on device: '/tmp/node-99f5f6d4-b056-49d2-827f-ab42bb93445c-e77b7035-f30b-43fb-969d-80179674a2a5/tmpna1iuohl'
> 	[2021-03-25T02:43:36+0000] [MainThread] [E] [toil.worker] Exiting the worker because of a failed job on host 9192a259c70d
> <=========

then i checked issues on GitHub：
https://github.com/ComparativeGenomicsToolkit/cactus/issues/84
https://github.com/ComparativeGenomicsToolkit/cactus/issues/301

so i add the `--workDir` option:
`nohup cactus --workDir workDirToil temp ratite.seqFile output/ratite.hal &`

but still got the same error:

>  [2021-04-13T01:07:34+0000] [MainThread] [I] [toil.worker] Redirecting logging to /data/workDirToil/node-8765e968-3d2d-4da2-b65a-d079bdda7ca9-e77b7035-f30b-43fb-969d-80179674a2a5/tmpbikhezdm/worker_log.txt
> [2021-04-13T01:07:34+0000] [Thread-1  ] [E] [toil.batchSystems.singleMachine] Got exit code 1 (indicating failure) from job _toil_worker CactusBarWrapper file:/data/temp kind-CactusBarWrapper/n/instance-sul5a4t0.
> [2021-04-13T01:07:34+0000] [MainThread] [W] [toil.leader] Job failed with exit value 1: 'CactusBarWrapper' kind-CactusBarWrapper/n/instance-sul5a4t0
> [2021-04-13T01:07:34+0000] [MainThread] [W] [toil.leader] The job seems to have left a log file, indicating failure: 'CactusBarWrapper' kind-CactusBarWrapper/n/instance-sul5a4t0
> [2021-04-13T01:07:34+0000] [MainThread] [W] [toil.leader] Log from job kind-CactusBarWrapper/n/instance-sul5a4t0 follows:
> =========>
> 	[2021-04-13T01:07:34+0000] [MainThread] [I] [toil.worker] ---TOIL WORKER OUTPUT LOG---
> 	[2021-04-13T01:07:34+0000] [MainThread] [I] [toil] Running Toil version 4.2.0-3aa1da130141039cb357efe36d7df9b9f6ae9b5b on host 8a19afc7be45.
> 	Traceback (most recent call last):
> 	  File "/usr/local/lib/python3.6/dist-packages/toil/worker.py", line 352, in workerScript
> 	    job = Job._loadJob(jobGraph.command, jobStore)
> 	  File "/usr/local/lib/python3.6/dist-packages/toil/job.py", line 923, in _loadJob
> 	    directory = tempfile.mkdtemp()
> 	  File "/usr/lib/python3.6/tempfile.py", line 509, in mkdtemp
> 	    _os.mkdir(file, 0o700)
> 	OSError: [Errno 28] No space left on device: '/tmp/tmpsuxt7d4u'
> 	[2021-04-13T01:07:34+0000] [MainThread] [E] [toil.worker] Exiting the worker because of a failed job on host 8a19afc7be45
> <=========
> [2021-04-13T01:07:35+0000] [MainThread] [W] [toil.jobGraph] Due to failure we are reducing the remaining retry count of job 'CactusBarWrapper' kind-CactusBarWrapper/n/instance-sul5a4t0 with ID kind-CactusBarWrapper/n/instance-sul5a4t0 to 1
> [2021-04-13T01:07:35+0000] [MainThread] [I] [toil.leader] Issued job 'CactusBarWrapper' kind-CactusBarWrapper/n/instance-sul5a4t0 with job batch system ID: 344330 and cores: 1, disk: 2.0 G, and memory: 5.9 G
> [2021-04-13T01:07:35+0000] [MainThread] [I] [toil.worker] Redirecting logging to /data/workDirToil/node-8765e968-3d2d-4da2-b65a-d079bdda7ca9-e77b7035-f30b-43fb-969d-80179674a2a5/tmpzd6eiufl/worker_log.txt
> [2021-04-13T01:07:36+0000] [MainThread] [I] [toil.worker] Redirecting logging to /data/workDirToil/node-8765e968-3d2d-4da2-b65a-d079bdda7ca9-e77b7035-f30b-43fb-969d-80179674a2a5/tmphg9qbho2/worker_log.txt
> [2021-04-13T01:07:38+0000] [MainThread] [I] [toil.leader] Job ended: 'CactusBarWrapper' kind-CactusBarWrapper/instance-ykwv74dx
> [2021-04-13T01:07:39+0000] [MainThread] [I] [toil.worker] Redirecting logging to /data/workDirToil/node-8765e968-3d2d-4da2-b65a-d079bdda7ca9-e77b7035-f30b-43fb-969d-80179674a2a5/tmpdkaocfrb/worker_log.txt
> [2021-04-13T01:07:47+0000] [MainThread] [I] [toil.leader] Job ended: 'CactusBarWrapper' kind-CactusBarWrapper/n/instance-_bfsci82
> [2021-04-13T01:07:49+0000] [MainThread] [I] [toil.worker] Redirecting logging to /data/workDirToil/node-8765e968-3d2d-4da2-b65a-d079bdda7ca9-e77b7035-f30b-43fb-969d-80179674a2a5/tmpjz_5bzxg/worker_log.txt
> [2021-04-13T01:07:50+0000] [MainThread] [I] [toil.leader] Job ended: 'CactusBarWrapper' kind-CactusBarWrapper/s/instance-dgbfy_bd
> [2021-04-13T01:07:51+0000] [MainThread] [I] [toil.worker] Redirecting logging to /data/workDirToil/node-8765e968-3d2d-4da2-b65a-d079bdda7ca9-e77b7035-f30b-43fb-969d-80179674a2a5/tmp1sen4i5w/worker_log.txt
> [2021-04-13T01:07:51+0000] [MainThread] [I] [toil.leader] Job ended: 'CactusBarWrapper' kind-CactusBarWrapper/instance-202grydl
> [2021-04-13T01:07:53+0000] [MainThread] [I] [toil.worker] Redirecting logging to /data/workDirToil/node-8765e968-3d2d-4da2-b65a-d079bdda7ca9-e77b7035-f30b-43fb-969d-80179674a2a5/tmpc0at6u0g/worker_log.txt
> [2021-04-13T01:07:53+0000] [MainThread] [I] [toil.leader] Job ended: 'CactusBarWrapper' kind-CactusBarWrapper/instance-qudn4ut0
> [2021-04-13T01:07:55+0000] [MainThread] [I] [toil.leader] Job ended: 'CactusBarWrapper' kind-CactusBarWrapper/instance-2ig41uto
> [2021-04-13T01:07:58+0000] [MainThread] [I] [toil.worker] Redirecting logging to /data/workDirToil/node-8765e968-3d2d-4da2-b65a-d079bdda7ca9-e77b7035-f30b-43fb-969d-80179674a2a5/tmpof6dk2v2/worker_log.txt
> [2021-04-13T01:07:58+0000] [MainThread] [I] [toil.worker] Redirecting logging to /data/workDirToil/node-8765e968-3d2d-4da2-b65a-d079bdda7ca9-e77b7035-f30b-43fb-969d-80179674a2a5/tmpupgo5ifg/worker_log.txt
> [2021-04-13T01:07:59+0000] [Thread-1  ] [E] [toil.batchSystems.singleMachine] Got exit code 1 (indicating failure) from job _toil_worker CactusBarWrapper file:/data/temp kind-CactusBarWrapper/instance-yus13ocm.
> [2021-04-13T01:07:59+0000] [MainThread] [W] [toil.leader] Job failed with exit value 1: 'CactusBarWrapper' kind-CactusBarWrapper/instance-yus13ocm
> [2021-04-13T01:07:59+0000] [MainThread] [W] [toil.leader] The job seems to have left a log file, indicating failure: 'CactusBarWrapper' kind-CactusBarWrapper/instance-yus13ocm
> [2021-04-13T01:07:59+0000] [MainThread] [W] [toil.leader] Log from job kind-CactusBarWrapper/instance-yus13ocm follows:
> =========>
> 	[2021-04-13T01:07:58+0000] [MainThread] [I] [toil.worker] ---TOIL WORKER OUTPUT LOG---
> 	[2021-04-13T01:07:58+0000] [MainThread] [I] [toil] Running Toil version 4.2.0-3aa1da130141039cb357efe36d7df9b9f6ae9b5b on host 8a19afc7be45.
> 	Traceback (most recent call last):
> 	  File "/usr/local/lib/python3.6/dist-packages/toil/worker.py", line 352, in workerScript
> 	    job = Job._loadJob(jobGraph.command, jobStore)
> 	  File "/usr/local/lib/python3.6/dist-packages/toil/job.py", line 923, in _loadJob
> 	    directory = tempfile.mkdtemp()
> 	  File "/usr/lib/python3.6/tempfile.py", line 509, in mkdtemp
> 	    _os.mkdir(file, 0o700)
> 	OSError: [Errno 28] No space left on device: '/tmp/tmpxvm9v8ro'
> 	[2021-04-13T01:07:58+0000] [MainThread] [E] [toil.worker] Exiting the worker because of a failed job on host 8a19afc7be45
> <=========
> [2021-04-13T01:07:59+0000] [MainThread] [W] [toil.jobGraph] Due to failure we are reducing the remaining retry count of job 'CactusBarWrapper' kind-CactusBarWrapper/instance-yus13ocm with ID kind-CactusBarWrapper/instance-yus13ocm to 1
> [2021-04-13T01:07:59+0000] [MainThread] [I] [toil.leader] Issued job 'CactusBarWrapper' kind-CactusBarWrapper/instance-yus13ocm with job batch system ID: 344331 and cores: 1, disk: 2.0 G, and memory: 5.3 G
> [2021-04-13T01:07:59+0000] [Thread-1  ] [E] [toil.batchSystems.singleMachine] Got exit code 1 (indicating failure) from job _toil_worker CactusBarWrapper file:/data/temp kind-CactusBarWrapper/instance-6crcqcqb.
> [2021-04-13T01:07:59+0000] [MainThread] [W] [toil.leader] Job failed with exit value 1: 'CactusBarWrapper' kind-CactusBarWrapper/instance-6crcqcqb
> [2021-04-13T01:07:59+0000] [MainThread] [W] [toil.leader] The job seems to have left a log file, indicating failure: 'CactusBarWrapper' kind-CactusBarWrapper/instance-6crcqcqb
> [2021-04-13T01:07:59+0000] [MainThread] [W] [toil.leader] Log from job kind-CactusBarWrapper/instance-6crcqcqb follows:
> =========>
> 	[2021-04-13T01:07:58+0000] [MainThread] [I] [toil.worker] ---TOIL WORKER OUTPUT LOG---
> 	[2021-04-13T01:07:58+0000] [MainThread] [I] [toil] Running Toil version 4.2.0-3aa1da130141039cb357efe36d7df9b9f6ae9b5b on host 8a19afc7be45.
> 	Traceback (most recent call last):
> 	  File "/usr/local/lib/python3.6/dist-packages/toil/worker.py", line 352, in workerScript
> 	    job = Job._loadJob(jobGraph.command, jobStore)
> 	  File "/usr/local/lib/python3.6/dist-packages/toil/job.py", line 923, in _loadJob
> 	    directory = tempfile.mkdtemp()
> 	  File "/usr/lib/python3.6/tempfile.py", line 509, in mkdtemp
> 	    _os.mkdir(file, 0o700)
> 	OSError: [Errno 28] No space left on device: '/tmp/tmpjqxj2mqb'
> 	[2021-04-13T01:07:58+0000] [MainThread] [E] [toil.worker] Exiting the worker because of a failed job on host 8a19afc7be45
> <=========

Could you help me about it?
 cactus version is quay.io/comparative-genomics-toolkit/cactus:v1.3.0

**Comment by diekhans** [comment]
trying setting the TMPDIR environment variable
to point to a directory on a file system with
more free disk space.

**Comment by Rusfell** [comment]
thanks.
the file system  to do have enough free disk space, see below:

> /data# df -Th
> Filesystem     Type     Size  Used Avail Use% Mounted on
> overlay        overlay  414G  311G  104G  76% /
> tmpfs          tmpfs     64M     0   64M   0% /dev
> tmpfs          tmpfs    189G     0  189G   0% /sys/fs/cgroup
> shm            tmpfs     64M  408K   64M   1% /dev/shm
> /dev/sdb       xfs       82T  3.6T   79T   5% /data
> /dev/sda3      xfs      414G  311G  104G  76% /etc/hosts
> tmpfs          tmpfs    189G     0  189G   0% /proc/acpi
> tmpfs          tmpfs    189G     0  189G   0% /proc/scsi
> tmpfs          tmpfs    189G     0  189G   0% /sys/firmware
> /data# du -sh temp/
> 831G    temp/

we have 82T space for the disk, (79T free), and the `temp/ ` only 831G.
what should i do?

**Comment by Rusfell** [comment]
> trying setting the TMPDIR environment variable to point to a directory on a file system with more free disk space.

thanks.
the file system to do have enough free disk space, see below:

> /data# df -Th
> Filesystem Type Size Used Avail Use% Mounted on
> overlay overlay 414G 311G 104G 76% /
> tmpfs tmpfs 64M 0 64M 0% /dev
> tmpfs tmpfs 189G 0 189G 0% /sys/fs/cgroup
> shm tmpfs 64M 408K 64M 1% /dev/shm
> /dev/sdb xfs 82T 3.6T 79T 5% /data
> /dev/sda3 xfs 414G 311G 104G 76% /etc/hosts
> tmpfs tmpfs 189G 0 189G 0% /proc/acpi
> tmpfs tmpfs 189G 0 189G 0% /proc/scsi
> tmpfs tmpfs 189G 0 189G 0% /sys/firmware
> /data# du -sh temp/
> 831G temp/

we have 82T space for the disk, (79T free), and the temp/ only 831G.
what should i do?

**Comment by diekhans** [comment]
Error is OSError: [Errno 28] No space left on device: '/tmp/node-99f5f6d4-b056-49d2-827f-ab42bb93445c-e77b7035-f30b-43fb-969d-80179674a2a5/tmp2tukhvg3'

You might have to talk your sys admins, we can't really tell what is going on beyond this error.

**Comment by glennhickey** [comment]
I'll echo the `TMPDIR` suggestion.   Something like `export TMPDIR=/data/temp` should avoid all writes to `/tmp`.  Judging from the `df` output you have "only" 104G in /tmp.  

But I'm still confused why Toil is writing anything to `/tmp` when `--workDir` is specified.  I can imagine a few small things leaking through, but something to the tune of 100's of gigs seems like a bug.

**Comment by zuodabin** [comment]
Hi，I also  encounter this problem，what should I do to solve the problem？
thanks  !!!!!!!
Filesystem              Type      Size  Used Avail Use% Mounted on
devtmpfs                devtmpfs  126G     0  126G   0% /dev
tmpfs                   tmpfs     126G   72K  126G   1% /dev/shm
tmpfs                   tmpfs     126G  357M  126G   1% /run
tmpfs                   tmpfs     126G     0  126G   0% /sys/fs/cgroup
/dev/mapper/centos-root xfs        50G   50G   44M 100% /
/dev/sda2               xfs      1014M  214M  801M  22% /boot
/dev/sda1               vfat      200M   12M  189M   6% /boot/efi
/dev/mapper/centos-home xfs       392G   60G  332G  16% /home
tmpfs                   tmpfs      26G   32K   26G   1% /run/user/0
/dev/sdb1               ext4       58T  1.9T   54T   4% /data
tmpfs                   tmpfs      26G  2.1M   26G   1% /run/user/1002
tmpfs                   tmpfs      26G     0   26G   0% /run/user/1003
