### ISSUE TITLE
hal2assemblyHub.py error: singleMachine is the only supported batchSystem

### ISSUE THREAD

**Issue by ybukhman** [ComparativeGenomicsToolkit/cactus#463]
Hi,

hal2assemblyHub.py seems to be confused about command line options. See my commands and errors below.

**Try 1**
Shell command:
```
hal2assemblyHub.py jobstore 4_rodents.hal 4_rodents_hub --lod \
--alignability --gcContent --hub 4_rodents --shortLabel 4_rodents \
|& tee hal2assemblyHub.out

```
Error:

> Traceback (most recent call last):
>   File "/isitools/cactus/bin/hal2assemblyHub.py", line 450, in <module>
>     main()
>   File "/isitools/cactus/submodules/hal/assemblyHub/hal2assemblyHub.py", line 443, in main
>     checkOptions(parser, options)
>   File "/isitools/cactus/submodules/hal/assemblyHub/hal2assemblyHub.py", line 419, in checkOptions
>     raise RuntimeError("singleMachine is the only supported batchSystem")
> RuntimeError: singleMachine is the only supported batchSystem
> 

**Try 2**
Command:
```
hal2assemblyHub.py jobstore 4_rodents.hal 4_rodents_hub --lod \
--alignability --gcContent --hub 4_rodents --shortLabel 4_rodents \
--batchSystem singleMachine |& tee hal2assemblyHub.out

```
Error:

> hal2assemblyHub.py: error: argument --batchSystem: invalid choice: 'singleMachine' (choose from 'parasol', 'single_machine', 'grid_engine', 'lsf', 'mesos', 'slurm', 'torque', 'htcondor', 'kubernetes')

**Try 3**
Command:
```
hal2assemblyHub.py jobstore 4_rodents.hal 4_rodents_hub --lod \
--alignability --gcContent --hub 4_rodents --shortLabel 4_rodents \
--batchSystem single_machine |& tee hal2assemblyHub.out
```
Error:

> Traceback (most recent call last):
>   File "/isitools/cactus/bin/hal2assemblyHub.py", line 450, in <module>
>     main()
>   File "/isitools/cactus/submodules/hal/assemblyHub/hal2assemblyHub.py", line 443, in main
>     checkOptions(parser, options)
>   File "/isitools/cactus/submodules/hal/assemblyHub/hal2assemblyHub.py", line 419, in checkOptions
>     raise RuntimeError("singleMachine is the only supported batchSystem")
> RuntimeError: singleMachine is the only supported batchSystem
> 

I have cactus version 1.3.0

System info:
```
(cactus_env) bash-4.2$ uname -a
Linux mir-49 3.10.0-1127.19.1.el7.x86_64 #1 SMP Tue Aug 25 17:23:54 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

```
Thanks!

Yury

**Comment by glennhickey** [comment]
This was fixed back [here](https://github.com/ComparativeGenomicsToolkit/hal/pull/200) and will be built into the next cactus release.

**Comment by ybukhman** [comment]
Thanks! What do I do in the meantime to build my assembly hub? Should I just get the latest version of hal off GitHub? If so, how do I configure my environment to use it instead of the one that came with cactus 1.3.0? Or should I revert to a previous cactus release?
