### ISSUE TITLE
 No such file or directory

### ISSUE THREAD

**Issue by Rusfell** [ComparativeGenomicsToolkit/cactus#464]
Dear team,

I am a new user for cactus (cactus version is quay.io/comparative-genomics-toolkit/cactus:v1.3.0). 

I have 80 genomes with 52G total size. 
`nohup cactus --workDir workDirToil temp cacuts.config output/symbiosis.hal &`

I found the error in the log file:

 

> [2021-04-22T01:35:44+0000] [MainThread] [I] [toil.leader] Issued job 'CactusHalGeneratorUpWrapper' kind-CactusHalGeneratorUpWrapper/D/instance-ogxc88vo with job batch system ID: 1345488 and cores: 1, disk: 2.0 G, and memory: 3.8 G
> [2021-04-22T01:35:44+0000] [MainThread] [I] [toil.leader] Job ended: 'CactusHalGeneratorUpWrapper' kind-CactusHalGeneratorUpWrapper/N/instance-u0i60y94
> [2021-04-22T01:35:44+0000] [MainThread] [I] [toil.leader] Issued job 'CactusHalGeneratorRecursion' kind-CactusHalGeneratorRecursion/k/instance-f2ge8b6q with job batch system ID: 1345489 and cores: 1, disk: 2.0 G, and memory: 2.0 G
> [2021-04-22T01:35:44+0000] [MainThread] [I] [toil.worker] Redirecting logging to /data/workDirToil/node-ce7bc531-5c0e-471b-bf5d-63b6daff1fd7-1f39fb3e-7291-4efe-986a-c3772070dab9/tmpeqkd8qo7/worker_log.txt
> [2021-04-22T01:35:44+0000] [Thread-1  ] [E] [toil.batchSystems.singleMachine] Got exit code 1 (indicating failure) from job _toil_worker CactusHalGeneratorUpWrapper file:/data/temp kind-CactusHalGeneratorUpWrapper/instance-d677lxd9.
> [2021-04-22T01:35:44+0000] [MainThread] [W] [toil.leader] Job failed with exit value 1: 'CactusHalGeneratorUpWrapper' kind-CactusHalGeneratorUpWrapper/instance-d677lxd9
> [2021-04-22T01:35:44+0000] [MainThread] [W] [toil.leader] The job seems to have left a log file, indicating failure: 'CactusHalGeneratorUpWrapper' kind-CactusHalGeneratorUpWrapper/instance-d677lxd9
> [2021-04-22T01:35:44+0000] [MainThread] [W] [toil.leader] Log from job kind-CactusHalGeneratorUpWrapper/instance-d677lxd9 follows:
> =========>
> 	[2021-04-22T01:35:42+0000] [MainThread] [I] [toil.worker] ---TOIL WORKER OUTPUT LOG---
> 	[2021-04-22T01:35:42+0000] [MainThread] [I] [toil] Running Toil version 4.2.0-3aa1da130141039cb357efe36d7df9b9f6ae9b5b on host e610d6c8ced0.
> 	Traceback (most recent call last):
> 	  File "/usr/local/lib/python3.6/dist-packages/toil/worker.py", line 364, in workerScript
> 	    with fileStore.open(job):
> 	  File "/usr/lib/python3.6/contextlib.py", line 81, in __enter__
> 	    return next(self.gen)
> 	  File "/usr/local/lib/python3.6/dist-packages/toil/fileStores/nonCachingFileStore.py", line 59, in open
> 	    self._removeDeadJobs(self.workDir)
> 	  File "/usr/local/lib/python3.6/dist-packages/toil/fileStores/nonCachingFileStore.py", line 186, in _removeDeadJobs
> 	    if not process_name_exists(nodeInfo, jobState['jobProcessName']):
> 	  File "/usr/local/lib/python3.6/dist-packages/toil/lib/threading.py", line 313, in process_name_exists
> 	    nameFD = os.open(nameFileName, os.O_RDONLY)
> 	c: [Errno 2] No such file or directory: '/data/workDirToil/node-ce7bc531-5c0e-471b-bf5d-63b6daff1fd7-1f39fb3e-7291-4efe-986a-c3772070dab9/tmpwsgd0oe8'
> 	[2021-04-22T01:35:42+0000] [MainThread] [E] [toil.worker] Exiting the worker because of a failed job on host e610d6c8ced0
> <=========
> [2021-04-22T01:35:44+0000] [MainThread] [W] [toil.jobGraph] Due to failure we are reducing the remaining retry count of job 'CactusHalGeneratorUpWrapper' kind-CactusHalGeneratorUpWrapper/instance-d677lxd9 with ID kind-CactusHalGeneratorUpWrapper/instance-d677lxd9 to 1
> [2021-04-22T01:35:44+0000] [MainThread] [I] [toil.leader] Issued job 'CactusHalGeneratorUpWrapper' kind-CactusHalGeneratorUpWrapper/instance-d677lxd9 with job batch system ID: 1345490 and cores: 1, disk: 2.0 G, and memory: 3.8 G
> [2021-04-22T01:35:44+0000] [MainThread] [I] [toil.worker] Redirecting logging to /data/workDirToil/node-ce7bc531-5c0e-471b-bf5d-63b6daff1fd7-1f39fb3e-7291-4efe-986a-c3772070dab9/tmpo2y1pjv4/worker_log.txt
> [2021-04-22T01:35:45+0000] [MainThread] [I] [toil.worker] Redirecting logging to /data/workDirToil/node-ce7bc531-5c0e-471b-bf5d-63b6daff1fd7-1f39fb3e-7291-4efe-986a-c3772070dab9/tmpj7i0oqw2/worker_log.txt
> [2021-04-22T01:35:45+0000] [MainThread] [I] [toil.leader] Job ended: 'CactusHalGeneratorRecursion' kind-CactusHalGeneratorRecursion/instance-uqij1eq5
> 

Disk and memory are enough:

> root@e610d6c8ced0:/data# free -h
>               total        used        free      shared  buff/cache   available
> Mem:           376G         14G        119G         24M        242G        358G
> Swap:           31G        798M         31G
> root@e610d6c8ced0:/data# dt -Th
> bash: dt: command not found
> root@e610d6c8ced0:/data# df -Th
> Filesystem     Type     Size  Used Avail Use% Mounted on
> overlay        overlay  414G   33G  382G   8% /
> tmpfs          tmpfs     64M     0   64M   0% /dev
> tmpfs          tmpfs    189G     0  189G   0% /sys/fs/cgroup
> shm            tmpfs     64M   24K   64M   1% /dev/shm
> /dev/sdb       xfs       28T  2.5T   25T  10% /data
> /dev/sda3      xfs      414G   33G  382G   8% /etc/hosts
> tmpfs          tmpfs    189G     0  189G   0% /proc/acpi
> tmpfs          tmpfs    189G     0  189G   0% /proc/scsi
> tmpfs          tmpfs    189G     0  189G   0% /sys/firmware

Cactus still running. What should i do?

Thanks!

**Comment by Rusfell** [comment]
This error ocurred when i followed the bird article.

` grep -A 10 -B 20 -i error nohup.out`

> [2021-05-12T14:32:23+0000] [MainThread] [I] [toil.leader] Issued job 'CactusHalGeneratorRecursion' kind-CactusHalGeneratorRecursion/F/instance-ul0iofau with job batch system ID: 1040804 and cores: 1, disk: 2.0 G, and memory: 2.0 G
> [2021-05-12T14:32:23+0000] [MainThread] [I] [toil.worker] Redirecting logging to /data/workDirToil/node-e3c232c2-ab25-4ffb-8b55-ece809a73525-1f39fb3e-7291-4efe-986a-c3772070dab9/tmpvwtmpf8h/worker_log.txt
> [2021-05-12T14:32:23+0000] [Thread-1  ] [E] [toil.batchSystems.singleMachine] Got exit code 1 (indicating failure) from job _toil_worker CactusHalGeneratorUpWrapper file:/data/temp kind-CactusHalGeneratorUpWrapper/e/instance-mxe_va42.
> [2021-05-12T14:32:23+0000] [MainThread] [W] [toil.leader] Job failed with exit value 1: 'CactusHalGeneratorUpWrapper' kind-CactusHalGeneratorUpWrapper/e/instance-mxe_va42
> [2021-05-12T14:32:23+0000] [MainThread] [W] [toil.leader] The job seems to have left a log file, indicating failure: 'CactusHalGeneratorUpWrapper' kind-CactusHalGeneratorUpWrapper/e/instance-mxe_va42
> [2021-05-12T14:32:23+0000] [MainThread] [W] [toil.leader] Log from job kind-CactusHalGeneratorUpWrapper/e/instance-mxe_va42 follows:
> =========>
>         [2021-05-12T14:32:23+0000] [MainThread] [I] [toil.worker] ---TOIL WORKER OUTPUT LOG---
>         [2021-05-12T14:32:23+0000] [MainThread] [I] [toil] Running Toil version 4.2.0-3aa1da130141039cb357efe36d7df9b9f6ae9b5b on host 239617015dc5.
>         Traceback (most recent call last):
>           File "/usr/local/lib/python3.6/dist-packages/toil/worker.py", line 364, in workerScript
>             with fileStore.open(job):
>           File "/usr/lib/python3.6/contextlib.py", line 81, in __enter__
>             return next(self.gen)
>           File "/usr/local/lib/python3.6/dist-packages/toil/fileStores/nonCachingFileStore.py", line 59, in open
>             self._removeDeadJobs(self.workDir)
>           File "/usr/local/lib/python3.6/dist-packages/toil/fileStores/nonCachingFileStore.py", line 186, in _removeDeadJobs
>             if not process_name_exists(nodeInfo, jobState['jobProcessName']):
>           File "/usr/local/lib/python3.6/dist-packages/toil/lib/threading.py", line 313, in process_name_exists
>             nameFD = os.open(nameFileName, os.O_RDONLY)
>         FileNotFoundError: [Errno 2] No such file or directory: '/data/workDirToil/node-e3c232c2-ab25-4ffb-8b55-ece809a73525-1f39fb3e-7291-4efe-986a-c3772070dab9/tmpp169spqf'
>         [2021-05-12T14:32:23+0000] [MainThread] [E] [toil.worker] Exiting the worker because of a failed job on host 239617015dc5
> <=========
> [2021-05-12T14:32:23+0000] [MainThread] [W] [toil.jobGraph] Due to failure we are reducing the remaining retry count of job 'CactusHalGeneratorUpWrapper' kind-CactusHalGeneratorUpWrapper/e/instance-mxe_va42 with ID kind-CactusHalGeneratorUpWrapper/e/instance-mxe_va42 to 1
> [2021-05-12T14:32:23+0000] [MainThread] [I] [toil.leader] Issued job 'CactusHalGeneratorUpWrapper' kind-CactusHalGeneratorUpWrapper/e/instance-mxe_va42 with job batch system ID: 1040805 and cores: 1, disk: 2.0 G, and memory: 3.8 G
> [2021-05-12T14:32:23+0000] [MainThread] [I] [toil.worker] Redirecting logging to /data/workDirToil/node-e3c232c2-ab25-4ffb-8b55-ece809a73525-1f39fb3e-7291-4efe-986a-c3772070dab9/tmpu0maxrwc/worker_log.txt
> [2021-05-12T14:32:23+0000] [MainThread] [I] [toil.worker] Redirecting logging to /data/workDirToil/node-e3c232c2-ab25-4ffb-8b55-ece809a73525-1f39fb3e-7291-4efe-986a-c3772070dab9/tmpu13q2p1d/worker_log.txt
> [2021-05-12T14:32:23+0000] [MainThread] [I] [toil.leader] Job ended: 'CactusHalGeneratorRecursion' kind-CactusHalGeneratorRecursion/c/instance-ij9hrhoc
> [2021-05-12T14:32:23+0000] [MainThread] [I] [toil.leader] Issued job 'CactusHalGeneratorUpWrapper' kind-CactusHalGeneratorUpWrapper/instance-r2645qk9 with job batch system ID: 1040806 and cores: 1, disk: 2.0 G, and memory: 3.8 G
> [2021-05-12T14:32:23+0000] [MainThread] [I] [toil.worker] Redirecting logging to /data/workDirToil/node-e3c232c2-ab25-4ffb-8b55-ece809a73525-1f39fb3e-7291-4efe-986a-c3772070dab9/tmpnbz8zzm0/worker_log.txt
> [2021-05-12T14:32:23+0000] [MainThread] [I] [toil.leader] Job ended: 'CactusHalGeneratorRecursion' kind-CactusHalGeneratorRecursion/q/instance-2jjiih4n

This seems to be a bug?
