### ISSUE TITLE
KtServerService error

### ISSUE THREAD

**Issue by RomainFeron** [ComparativeGenomicsToolkit/cactus#49]
Hi,

I'm having an error with KtServerService when running cactus on a dataset with 7 genomes. I was able to run cactus on 2 genomes without encountering this issue. Here are some parts of the logs I thought would be relevant :

> INFO:toil.leader:Issued job 'StartPrimaryDB' n/C/job05D_Ff with job batch system ID: 0 and cores: 1, disk: 2.0 G, and memory: 3.3 G
> INFO:toil.leader:Job ended successfully: 'StartPrimaryDB' n/C/job05D_Ff
> INFO:toil.leader:Issued job 'KtServerService' g/f/job6l7svt with job batch system ID: 1 and cores: 0, disk: 2.0 G, and memory: 4.3 G
> INFO:toil.leader:Job ended successfully: 'KtServerService' g/f/job6l7svt
> WARNING:toil.leader:The job seems to have left a log file, indicating failure: 'KtServerService' g/f/job6l7svt
> WARNING:toil.leader:g/f/job6l7svt    INFO:toil.worker:---TOIL WORKER OUTPUT LOG---
> WARNING:toil.leader:g/f/job6l7svt    INFO:toil:Running Toil version 3.18.0-84239d802248a5f4a220e762b3b8ce5cc92af0be.
> WARNING:toil.leader:g/f/job6l7svt    WARNING:toil.resource:'JTRES_01944ae18e37adfa915b306be00f52e1' may exist, but is not yet referenced by the worker (KeyError from os.environ[]).
> WARNING:toil.leader:g/f/job6l7svt    WARNING:toil.resource:'JTRES_01944ae18e37adfa915b306be00f52e1' may exist, but is not yet referenced by the worker (KeyError from os.environ[]).
> WARNING:toil.leader:g/f/job6l7svt    INFO:cactus.shared.common:Running the command ['netstat', '-tuplen']
> WARNING:toil.leader:g/f/job6l7svt    (No info could be read for "-p": geteuid()=24224 but you should be root.)
> WARNING:toil.leader:g/f/job6l7svt    INFO:cactus.shared.common:Running the command ['ktserver', '-port', '30496', '-ls', '-tout', '200000', '-th', '64', '-bgs', u'/tmp/toil-d112ee36-cbf0-4c80-ad4f-0366e64760c3-d94d914f-1b6f-4938-8699-7357c3f3f800/tmpCFu2R3/21cf6aff-a6b2-4ef3-b0a1-d78f892741db/tbfTb5i/snapshot', '-bgsc', 'lzo', '-bgsi', '1000000', '-log', u'/tmp/toil-d112ee36-cbf0-4c80-ad4f-0366e64760c3-d94d914f-1b6f-4938-8699-7357c3f3f800/tmpCFu2R3/21cf6aff-a6b2-4ef3-b0a1-d78f892741db/tmpPyS64o.tmp', ':#opts=ls#bnum=30m#msiz=50g#ktopts=p']
> WARNING:toil.leader:g/f/job6l7svt    CRITICAL:toil.lib.bioio:Error starting ktserver.
> WARNING:toil.leader:g/f/job6l7svt    INFO:cactus.shared.common:Running the command ['ktremotemgr', 'remove', '-port', '30496', '-host', '10.0.20.57', 'TERMINATE']
> WARNING:toil.leader:g/f/job6l7svt    ktremotemgr: DB::remove failed: 10.0.20.57:30496: 3: logical inconsistency: DB: 7: no record: no record
> WARNING:toil.leader:g/f/job6l7svt    Process ServerProcess-1:
> WARNING:toil.leader:g/f/job6l7svt    Traceback (most recent call last):
> WARNING:toil.leader:g/f/job6l7svt      File "/software/lib64/python2.7/multiprocessing/process.py", line 258, in _bootstrap
> WARNING:toil.leader:g/f/job6l7svt        self.run()
> WARNING:toil.leader:g/f/job6l7svt      File "/Home/rferon/tools/cactus/cactus_env/lib/python2.7/site-packages/cactus/pipeline/ktserverControl.py", line 82, in run
> WARNING:toil.leader:g/f/job6l7svt        self.tryRun(*self.args, **self.kwargs)
> WARNING:toil.leader:g/f/job6l7svt      File "/Home/rferon/tools/cactus/cactus_env/lib/python2.7/site-packages/cactus/pipeline/ktserverControl.py", line 102, in tryRun
> WARNING:toil.leader:g/f/job6l7svt        cactus_call(parameters=["ktremotemgr", "remove"] + getRemoteParams(dbElem) + ["TERMINATE"])
> WARNING:toil.leader:g/f/job6l7svt      File "/Home/rferon/tools/cactus/cactus_env/lib/python2.7/site-packages/cactus/shared/common.py", line 1038, in cactus_call
> WARNING:toil.leader:g/f/job6l7svt        raise RuntimeError("Command %s failed with output: %s" % (call, output))
> WARNING:toil.leader:g/f/job6l7svt    RuntimeError: Command ['ktremotemgr', 'remove', '-port', '30496', '-host', '10.0.20.57', 'TERMINATE'] failed with output: None
> WARNING:toil.leader:g/f/job6l7svt    CRITICAL:toil.lib.bioio:Error starting ktserver.
> WARNING:toil.leader:g/f/job6l7svt    Traceback (most recent call last):
> WARNING:toil.leader:g/f/job6l7svt      File "/Home/rferon/tools/cactus/cactus_env/lib/python2.7/site-packages/toil/worker.py", line 314, in workerScript
> WARNING:toil.leader:g/f/job6l7svt        job._runner(jobGraph=jobGraph, jobStore=jobStore, fileStore=fileStore)
> WARNING:toil.leader:g/f/job6l7svt      File "/Home/rferon/tools/cactus/cactus_env/lib/python2.7/site-packages/toil/job.py", line 1351, in _runner
> WARNING:toil.leader:g/f/job6l7svt        returnValues = self._run(jobGraph, fileStore)
> WARNING:toil.leader:g/f/job6l7svt      File "/Home/rferon/tools/cactus/cactus_env/lib/python2.7/site-packages/toil/job.py", line 1694, in _run
> WARNING:toil.leader:g/f/job6l7svt        returnValues = self.run(fileStore)
> WARNING:toil.leader:g/f/job6l7svt      File "/Home/rferon/tools/cactus/cactus_env/lib/python2.7/site-packages/toil/job.py", line 1644, in run
> WARNING:toil.leader:g/f/job6l7svt        startCredentials = service.start(self)
> WARNING:toil.leader:g/f/job6l7svt      File "/Home/rferon/tools/cactus/cactus_env/lib/python2.7/site-packages/cactus/pipeline/ktserverToil.py", line 33, in start
> WARNING:toil.leader:g/f/job6l7svt        snapshotExportID=snapshotExportID)
> WARNING:toil.leader:g/f/job6l7svt      File "/Home/rferon/tools/cactus/cactus_env/lib/python2.7/site-packages/cactus/pipeline/ktserverControl.py", line 62, in runKtserver
> WARNING:toil.leader:g/f/job6l7svt        raise RuntimeError("Unable to launch ktserver in time. Log: %s" % log)
> WARNING:toil.leader:g/f/job6l7svt    RuntimeError: Unable to launch ktserver in time. Log: 2018-11-23T11:23:32.793822+01:00: [SYSTEM]: ================ [START]: pid=5130
> WARNING:toil.leader:g/f/job6l7svt    2018-11-23T11:23:32.794104+01:00: [SYSTEM]: opening a database: path=:#opts=ls#bnum=30m#msiz=50g#ktopts=p
> WARNING:toil.leader:g/f/job6l7svt    2018-11-23T11:23:32.794554+01:00: [SYSTEM]: applying a snapshot file: db=0 ts=1542963976113000000 count=6467072 size=4381380962
> WARNING:toil.leader:g/f/job6l7svt    2018-11-23T11:23:33.493808+01:00: [ERROR]: [DB]: :: 9: system error: too short region
> WARNING:toil.leader:g/f/job6l7svt    2018-11-23T11:23:33.493932+01:00: [ERROR]: could not apply a snapshot: system error: too short region
> WARNING:toil.leader:g/f/job6l7svt    2018-11-23T11:23:33.494107+01:00: [SYSTEM]: starting the server: expr=:30496
> WARNING:toil.leader:g/f/job6l7svt    2018-11-23T11:23:33.494221+01:00: [SYSTEM]: server socket opened: expr=:30496 timeout=200000.0
> WARNING:toil.leader:g/f/job6l7svt    2018-11-23T11:23:33.494251+01:00: [SYSTEM]: listening server socket started: fd=4
> WARNING:toil.leader:g/f/job6l7svt    
> WARNING:toil.leader:g/f/job6l7svt    ERROR:toil.worker:Exiting the worker because of a failed job on host dee-serv07.vital-it.ch
> WARNING:toil.leader:g/f/job6l7svt    WARNING:toil.jobGraph:Due to failure we are reducing the remaining retry count of job 'KtServerService' g/f/job6l7svt with ID g/f/job6l7svt to 5

This error message is repeated many times in the log. After all these messages, the logs end with this message :

> INFO:toil.leader:Finished toil run with 13 failed jobs.
> INFO:toil.leader:Failed jobs at end of the run: 'ProgressiveUp' A/r/job5PkiIS 'ProgressiveDown' k/l/jobdOQ_ns 'StartPrimaryDB' n/C/job05D_Ff 'CactusReferenceCheckpoint' C/D/jobBHqaG0 'ProgressiveDown' O/u/jobfg6RgM 'CactusBarCheckpoint' L/D/jobdgkHCw 'CactusTrimmingBlastPhase' t/b/job2IlD62 'ProgressiveDown' W/R/jobbZsCWY 'ProgressiveNext' R/k/job3m5wZm 'RunCactusPreprocessorThenProgressiveDown' T/P/jobzfQQNe 'KtServerService' d/C/jobbFkXe9 'CactusSetupCheckpoint' e/e/job7mK2be 'RunCactusPreprocessorThenProgressiveDown2' x/U/jobJAPrbP
> Traceback (most recent call last):
>   File "/Home/rferon/tools/cactus/cactus_env/bin/cactus", line 11, in <module>
>     sys.exit(main())
>   File "/Home/rferon/tools/cactus/cactus_env/lib/python2.7/site-packages/cactus/progressive/cactus_progressive.py", line 458, in main
>     halID = toil.restart()
>   File "/Home/rferon/tools/cactus/cactus_env/lib/python2.7/site-packages/toil/common.py", line 816, in restart
>     return self._runMainLoop(rootJobGraph)
>   File "/Home/rferon/tools/cactus/cactus_env/lib/python2.7/site-packages/toil/common.py", line 1059, in _runMainLoop
>     jobCache=self._jobCache).run()
>   File "/Home/rferon/tools/cactus/cactus_env/lib/python2.7/site-packages/toil/leader.py", line 237, in run
>     raise FailedJobsException(self.config.jobStore, self.toilState.totalFailedJobs, self.jobStore)
> toil.leader.FailedJobsException

I'm running cactus on a cluster in local dependency mode (the dependencies were installed on the cluster). Here is the command :

`cactus --restart --binariesMode local --maxCores 32 temp cactus_test_7_genomes.txt cactus_test_2_genomes.hal`

Does this error come from the database, or is it another problem (suggested by this line : [DB]: :: 9: system error: too short region)
Thanks !

**Comment by lassancejm** [comment]
Did you get pass this error? 

I am seeing a lot of message similar to yours, but I am uncertain what is causing this error or how to get passed it. 

Tips are welcome!

JM

```
INFO:toil.leader:Issued job 'KtServerService' A/q/jobvU4WyV with job batch system ID: 3 and cores: 0, disk: 2.8 G, and memory: 50.3 G
INFO:toil.leader:Job ended successfully: 'KtServerService' A/q/jobvU4WyV
WARNING:toil.leader:The job seems to have left a log file, indicating failure: 'KtServerService' A/q/jobvU4WyV
WARNING:toil.leader:A/q/jobvU4WyV    INFO:toil.worker:---TOIL WORKER OUTPUT LOG---
WARNING:toil.leader:A/q/jobvU4WyV    INFO:toil:Running Toil version 3.19.0-0feb1d4d1b4fc66062fc4dbc5d8f7fb046df39e6.
WARNING:toil.leader:A/q/jobvU4WyV    WARNING:toil.resource:'JTRES_487db7e35980364bd76c90413e988c94' may exist, but is not yet referenced by the worker (KeyError from os.environ[]).
WARNING:toil.leader:A/q/jobvU4WyV    WARNING:toil.resource:'JTRES_487db7e35980364bd76c90413e988c94' may exist, but is not yet referenced by the worker (KeyError from os.environ[]).
WARNING:toil.leader:A/q/jobvU4WyV    INFO:cactus.shared.common:Running the command ['netstat', '-tuplen']
WARNING:toil.leader:A/q/jobvU4WyV    (No info could be read for "-p": geteuid()=56685 but you should be root.)
WARNING:toil.leader:A/q/jobvU4WyV    INFO:cactus.shared.common:Running the command ['ktserver', '-port', '19362', '-ls', '-tout', '200000', '-th', '64', '-bgs', u'/tmp/toil-d26cb8ff-cabd-4073-9dff-c78622313dd7-24b9bf83-4de6-4cc2-806a-6f9b1f77386a/tmpsPKhar/e5afee6e-3501-486e-8a88-350bae38f4cf/tQlq7b6/snapshot', '-bgsc', 'lzo', '-bgsi', '1000000', '-log', u'/tmp/toil-d26cb8ff-cabd-4073-9dff-c78622313dd7-24b9bf83-4de6-4cc2-806a-6f9b1f77386a/tmpsPKhar/e5afee6e-3501-486e-8a88-350bae38f4cf/tmpXUtETZ.tmp', ':#opts=ls#bnum=30m#msiz=50g#ktopts=p']
WARNING:toil.leader:A/q/jobvU4WyV    CRITICAL:toil.lib.bioio:Error starting ktserver.
WARNING:toil.leader:A/q/jobvU4WyV    INFO:cactus.shared.common:Running the command ['ktremotemgr', 'remove', '-port', '19362', '-host', '10.31.138.118', 'TERMINATE']
WARNING:toil.leader:A/q/jobvU4WyV    INFO:cactus.shared.common:Running the command ['ktremotemgr', 'get', '-port', '19362', '-host', '10.31.138.118', 'TERMINATE']
WARNING:toil.leader:A/q/jobvU4WyV    Process ServerProcess-1:
WARNING:toil.leader:A/q/jobvU4WyV    Traceback (most recent call last):
WARNING:toil.leader:A/q/jobvU4WyV      File "/n/home01/lassance/.conda/envs/ENV_CACTUS/lib/python2.7/multiprocessing/process.py", line 267, in _bootstrap
WARNING:toil.leader:A/q/jobvU4WyV        self.run()
WARNING:toil.leader:A/q/jobvU4WyV      File "/n/home01/lassance/.conda/envs/ENV_CACTUS/lib/python2.7/site-packages/cactus/pipeline/ktserverControl.py", line 82, in run
WARNING:toil.leader:A/q/jobvU4WyV        self.tryRun(*self.args, **self.kwargs)
WARNING:toil.leader:A/q/jobvU4WyV      File "/n/home01/lassance/.conda/envs/ENV_CACTUS/lib/python2.7/site-packages/cactus/pipeline/ktserverControl.py", line 118, in tryRun
WARNING:toil.leader:A/q/jobvU4WyV        raise RuntimeError("KTServer failed. Log: %s" % f.read())
WARNING:toil.leader:A/q/jobvU4WyV    RuntimeError: KTServer failed. Log: 2019-08-28T08:50:23.431847-05:00: [SYSTEM]: ================ [START]: pid=111118
WARNING:toil.leader:A/q/jobvU4WyV    2019-08-28T08:50:23.432018-05:00: [SYSTEM]: opening a database: path=:#opts=ls#bnum=30m#msiz=50g#ktopts=p
WARNING:toil.leader:A/q/jobvU4WyV    2019-08-28T08:50:23.432332-05:00: [SYSTEM]: applying a snapshot file: db=0 ts=1566409684634000000 count=20479544 size=15187944389
WARNING:toil.leader:A/q/jobvU4WyV    2019-08-28T08:50:36.618643-05:00: [ERROR]: [DB]: :: 9: system error: too short region
WARNING:toil.leader:A/q/jobvU4WyV    2019-08-28T08:50:36.618705-05:00: [ERROR]: could not apply a snapshot: system error: too short region
WARNING:toil.leader:A/q/jobvU4WyV    2019-08-28T08:50:36.618807-05:00: [SYSTEM]: starting the server: expr=:19362
WARNING:toil.leader:A/q/jobvU4WyV    2019-08-28T08:50:36.618869-05:00: [SYSTEM]: server socket opened: expr=:19362 timeout=200000.0
WARNING:toil.leader:A/q/jobvU4WyV    2019-08-28T08:50:36.618880-05:00: [SYSTEM]: listening server socket started: fd=4
WARNING:toil.leader:A/q/jobvU4WyV    
WARNING:toil.leader:A/q/jobvU4WyV    CRITICAL:toil.lib.bioio:Error starting ktserver.
WARNING:toil.leader:A/q/jobvU4WyV    WARNING:toil.fileStore:LOG-TO-MASTER: Job used more disk than requested. Consider modifying the user script to avoid the chance of failure due to incorrectly requested resources. Job t/V/jobTdd5ip/g/tmpFoOJp5-_serialiseJob-stream used 401.26% (11.4 GB [12187840512B] used, 2.8 GB [3037418200B] requested) at the end of its run.
WARNING:toil.leader:A/q/jobvU4WyV    Traceback (most recent call last):
WARNING:toil.leader:A/q/jobvU4WyV      File "/n/home01/lassance/.conda/envs/ENV_CACTUS/lib/python2.7/site-packages/toil/worker.py", line 324, in workerScript
WARNING:toil.leader:A/q/jobvU4WyV        job._runner(jobGraph=jobGraph, jobStore=jobStore, fileStore=fileStore)
WARNING:toil.leader:A/q/jobvU4WyV      File "/n/home01/lassance/.conda/envs/ENV_CACTUS/lib/python2.7/site-packages/toil/job.py", line 1351, in _runner
WARNING:toil.leader:A/q/jobvU4WyV        returnValues = self._run(jobGraph, fileStore)
WARNING:toil.leader:A/q/jobvU4WyV      File "/n/home01/lassance/.conda/envs/ENV_CACTUS/lib/python2.7/site-packages/toil/job.py", line 1694, in _run
WARNING:toil.leader:A/q/jobvU4WyV        returnValues = self.run(fileStore)
WARNING:toil.leader:A/q/jobvU4WyV      File "/n/home01/lassance/.conda/envs/ENV_CACTUS/lib/python2.7/site-packages/toil/job.py", line 1644, in run
WARNING:toil.leader:A/q/jobvU4WyV        startCredentials = service.start(self)
WARNING:toil.leader:A/q/jobvU4WyV      File "/n/home01/lassance/.conda/envs/ENV_CACTUS/lib/python2.7/site-packages/cactus/pipeline/ktserverToil.py", line 33, in start
WARNING:toil.leader:A/q/jobvU4WyV        snapshotExportID=snapshotExportID)
WARNING:toil.leader:A/q/jobvU4WyV      File "/n/home01/lassance/.conda/envs/ENV_CACTUS/lib/python2.7/site-packages/cactus/pipeline/ktserverControl.py", line 62, in runKtserver
WARNING:toil.leader:A/q/jobvU4WyV        raise RuntimeError("Unable to launch ktserver in time. Log: %s" % log)
WARNING:toil.leader:A/q/jobvU4WyV    RuntimeError: Unable to launch ktserver in time. Log: 2019-08-28T08:50:23.431847-05:00: [SYSTEM]: ================ [START]: pid=111118
WARNING:toil.leader:A/q/jobvU4WyV    2019-08-28T08:50:23.432018-05:00: [SYSTEM]: opening a database: path=:#opts=ls#bnum=30m#msiz=50g#ktopts=p
WARNING:toil.leader:A/q/jobvU4WyV    2019-08-28T08:50:23.432332-05:00: [SYSTEM]: applying a snapshot file: db=0 ts=1566409684634000000 count=20479544 size=15187944389
WARNING:toil.leader:A/q/jobvU4WyV    2019-08-28T08:50:36.618643-05:00: [ERROR]: [DB]: :: 9: system error: too short region
WARNING:toil.leader:A/q/jobvU4WyV    2019-08-28T08:50:36.618705-05:00: [ERROR]: could not apply a snapshot: system error: too short region
WARNING:toil.leader:A/q/jobvU4WyV    2019-08-28T08:50:36.618807-05:00: [SYSTEM]: starting the server: expr=:19362
WARNING:toil.leader:A/q/jobvU4WyV    2019-08-28T08:50:36.618869-05:00: [SYSTEM]: server socket opened: expr=:19362 timeout=200000.0
WARNING:toil.leader:A/q/jobvU4WyV    2019-08-28T08:50:36.618880-05:00: [SYSTEM]: listening server socket started: fd=4
WARNING:toil.leader:A/q/jobvU4WyV    
WARNING:toil.leader:A/q/jobvU4WyV    ERROR:toil.worker:Exiting the worker because of a failed job on host holy2b17215.rc.fas.harvard.edu
WARNING:toil.leader:A/q/jobvU4WyV    WARNING:toil.jobGraph:Due to failure we are reducing the remaining retry count of job 'KtServerService' A/q/jobvU4WyV with ID A/q/jobvU4WyV to 5
```

**Comment by RomainFeron** [comment]
Hi @lassancejm, if I remember correctly, my solution was to run Cactus with singularity. It ran better this way. Sorry I can't help you more !

**Comment by jasonsydes** [comment]
Hi @RomainFeron, thanks for posting about this.  I'm receiving the same error as well. Unfortunately, we're running under Cactus under Singularity already...  Do you happen to know what version of cactus you're using?

**Comment by RomainFeron** [comment]
Hi @jasonsydes,
I have not tried to run Cactus since I posted this issue; I was cloning cactus from the git repository, so the version I ran was ~1 year older than yours.

**Comment by jasonsydes** [comment]
Hi @RomainFeron, thanks for that info, that's helpful.
