### ISSUE TITLE
error on gridEngine

### ISSUE THREAD

**Issue by Juke34** [ComparativeGenomicsToolkit/cactus#51]
I don't succeed to make cactus run. I have tried on three different job management systems (SLURM, LSF and now gridEngine). So I'm focusing now only on gridEngine that sounds the most easy to make it run according of different external reason.

We are using toil 3.18.0 (released on October 2nd)

I do  
```
     export TOIL_GRIDENGINE_PE='smp'  
     export TOIL_GRIDENGINE_ARGS='-V -q all.q'  
     cactus --batchSystem gridEngine /projects/annotation/cactus/cactus_intermediate_files /sw/bioinfo/cactus/latest/cactus/examples/evolverMammals.txt outputHal --logFile LOGFILE

```
and I end up with that message:

```INFO:toil.statsAndLogging:Got message from job at time 12-07-2018 10:29:00: Leaf names = ['simHuman_chr6', 'simCow_chr6', 'simDog_chr6', 'simMouse_chr6', 'simRat_chr6']
INFO:toil.leader:Job ended successfully: 'RunCactusPreprocessorThenProgressiveDown' w/A/job7Y0wzz
INFO:toil.leader:Finished toil run successfully.
Traceback (most recent call last):
  File "/sw/bioinfo/cactus/latest/bin/cactus", line 11, in <module>
    sys.exit(main())
  File "/sw/bioinfo/cactus/d2cae96/lib/python2.7/site-packages/cactus/progressive/cactus_progressive.py", line 500, in main
    halID = toil.start(RunCactusPreprocessorThenProgressiveDown(options, project, memory=configWrapper.getDefaultMemory()))
  File "/sw/bioinfo/cactus/d2cae96/lib/python2.7/site-packages/toil/common.py", line 784, in start
    return self._runMainLoop(rootJobGraph)
  File "/sw/bioinfo/cactus/d2cae96/lib/python2.7/site-packages/toil/common.py", line 1059, in _runMainLoop
    jobCache=self._jobCache).run()
  File "/sw/bioinfo/cactus/d2cae96/lib/python2.7/site-packages/toil/leader.py", line 239, in run
    return self.jobStore.getRootJobReturnValue()
  File "/sw/bioinfo/cactus/d2cae96/lib/python2.7/site-packages/toil/jobStores/abstractJobStore.py", line 218, in getRootJobReturnValue
    return safeUnpickleFromStream(fH)
  File "/sw/bioinfo/cactus/d2cae96/lib/python2.7/site-packages/toil/common.py", line 1360, in safeUnpickleFromStream
    return pickle.loads(string)
  File "/sw/bioinfo/cactus/d2cae96/lib/python2.7/site-packages/toil/job.py", line 1763, in __new__
    return cls._resolve(*args)
  File "/sw/bioinfo/cactus/d2cae96/lib/python2.7/site-packages/toil/job.py", line 1775, in _resolve
    value = safeUnpickleFromStream(fileHandle)
  File "/sw/bioinfo/cactus/d2cae96/lib/python2.7/site-packages/toil/common.py", line 1360, in safeUnpickleFromStream
    return pickle.loads(string)
  File "/sw/bioinfo/cactus/d2cae96/lib/python2.7/site-packages/toil/job.py", line 1763, in __new__
    return cls._resolve(*args)
  File "/sw/bioinfo/cactus/d2cae96/lib/python2.7/site-packages/toil/job.py", line 1775, in _resolve
    value = safeUnpickleFromStream(fileHandle)
  File "/sw/bioinfo/cactus/d2cae96/lib/python2.7/site-packages/toil/common.py", line 1360, in safeUnpickleFromStream
    return pickle.loads(string)
  File "/sw/bioinfo/cactus/d2cae96/lib/python2.7/site-packages/toil/job.py", line 1853, in __setstate__
    "this job as a child/follow-on of {jobName}.".format(jobName=jobName))
RuntimeError: This job was passed a promise that wasn't yet resolved when it ran. The job 'RunCactusPreprocessorThenProgressiveDown2' that fulfills this promise hasn't yet finished. This means that there aren't enough constraints to ensure the current job always runs after 'RunCactusPreprocessorThenProgressiveDown2'. Consider adding a follow-on indirection between this job and its parent, or adding this job as a child/follow-on of 'RunCactusPreprocessorThenProgressiveDown2'.
```
Any help would be much appreciated.

**Comment by joelarmstrong** [comment]
Hi Jacques,

Sorry that you're running into trouble. This message is interesting. That error implies that a job hasn't completed at the right time. It's possible that it's a logic error in Cactus (if we didn't represent the dependencies between jobs correctly); however, I've just rerun that same example and everything seems to work. It's hard to tell for sure, but I think it may mean that a job was marked completed despite not running. So this may indeed be a toil issue.

Could you upload the full log file? It would really help track this down. It would be even better if you could rerun adding the `--logLevel DEBUG` option and provide that log file instead.

Thanks for the bug report!

**Comment by Juke34** [comment]
With the DEBUG option I had the impression it has run a while before to crash while without after 20 sec it crashed. Here is the [LOGFILE](https://www.dropbox.com/s/9a6vr5djiqk4p93/LOGFILE?dl=0)

**Comment by diekhans** [comment]
gone stale and probably a Toil problem.
