### ISSUE TITLE
too little default memory for Runblast

### ISSUE THREAD

**Issue by lassancejm** [ComparativeGenomicsToolkit/cactus#52]
Hi, 
I am using Cactus on a linux cluster using Slurm. 

I have noticed that a large number of jobs run out of memory. They get resubmitted with increased memory, but this IMO creates unnecessary burden on the scheduler (plus negatively impacts my fairshare). 

As you can see in the example below, the memory appears to be set to 100M, which seems to be different than `--defaultMemory` which I thought was set to 2 G. 

Any idea what is happening here?

```
Issued job 'RunBlast' Q/O/jobExNWJB with job batch system ID: 10974 and cores: 1, disk: 100.0 M, and memory: 100.0 M
Job ended successfully: 'RunBlast' Q/O/jobExNWJB
The job seems to have left a log file, indicating failure: 'RunBlast' Q/O/jobExNWJB
Q/O/jobExNWJB    INFO:toil.worker:---TOIL WORKER OUTPUT LOG---
Q/O/jobExNWJB    INFO:toil:Running Toil version 3.18.0-84239d802248a5f4a220e762b3b8ce5cc92af0be.
Q/O/jobExNWJB    WARNING:toil.resource:'JTRES_b2dc083614dd582f2772f871e1b81eef' may exist, but is not yet referenced by the worker (KeyError from os.environ[]).
Q/O/jobExNWJB    INFO:cactus.shared.common:Docker work dir: /tmp/toil-68ba9d40-d272-4d3a-82d7-37579919f5d7-1e4ee729-0a33-477c-9099-d1a437c00af4/tmpbRhvn2/bbb7f143-3e34-46b2-b48c-df6fea1565f2
Q/O/jobExNWJB    INFO:cactus.shared.common:Running the command ['singularity', '--silent', 'run', u'/n/regal/hoekstra_lab/lassance/ProgressiveCactus/Pman1_Pman2/jobstore/cactus.img', u'cPecanLastz', u'--format=cigar', u'--notrivial', u'--step=1', u'--ambiguous=iupac,100,100', u'--ydrop=3000', u'tmpDACbhQ.tmp[multiple][nameparse=darkspace]', u'tmpidyx89.tmp[nameparse=darkspace]']
Q/O/jobExNWJB    Running command catchsegv 'cPecanLastz' '--format=cigar' '--notrivial' '--step=1' '--ambiguous=iupac,100,100' '--ydrop=3000' 'tmpDACbhQ.tmp[multiple][nameparse=darkspace]' 'tmpidyx89.tmp[nameparse=darkspace]'
Q/O/jobExNWJB    Killed
Q/O/jobExNWJB    Traceback (most recent call last):
Q/O/jobExNWJB      File "/n/home01/lassance/.conda/envs/ENV_CACTUS/lib/python2.7/site-packages/toil/worker.py", line 314, in workerScript
Q/O/jobExNWJB        job._runner(jobGraph=jobGraph, jobStore=jobStore, fileStore=fileStore)
Q/O/jobExNWJB      File "/n/home01/lassance/.conda/envs/ENV_CACTUS/lib/python2.7/site-packages/cactus/shared/common.py", line 1094, in _runner
Q/O/jobExNWJB        super(RoundedJob, self)._runner(jobGraph=jobGraph, jobStore=jobStore, fileStore=fileStore)
Q/O/jobExNWJB      File "/n/home01/lassance/.conda/envs/ENV_CACTUS/lib/python2.7/site-packages/toil/job.py", line 1351, in _runner
Q/O/jobExNWJB        returnValues = self._run(jobGraph, fileStore)
Q/O/jobExNWJB      File "/n/home01/lassance/.conda/envs/ENV_CACTUS/lib/python2.7/site-packages/toil/job.py", line 1296, in _run
Q/O/jobExNWJB        return self.run(fileStore)
Q/O/jobExNWJB      File "/n/home01/lassance/.conda/envs/ENV_CACTUS/lib/python2.7/site-packages/cactus/blast/blast.py", line 443, in run
Q/O/jobExNWJB        runLastz(seqFile1, seqFile2, blastResultsFile, lastzArguments = self.blastOptions.lastzArguments)
Q/O/jobExNWJB      File "/n/home01/lassance/.conda/envs/ENV_CACTUS/lib/python2.7/site-packages/cactus/shared/common.py", line 758, in runLastz
Q/O/jobExNWJB        soft_timeout=5400)
Q/O/jobExNWJB      File "/n/home01/lassance/.conda/envs/ENV_CACTUS/lib/python2.7/site-packages/cactus/shared/common.py", line 1038, in cactus_call
Q/O/jobExNWJB        raise RuntimeError("Command %s failed with output: %s" % (call, output))
Q/O/jobExNWJB    RuntimeError: Command ['singularity', '--silent', 'run', u'/n/regal/hoekstra_lab/lassance/ProgressiveCactus/Pman1_Pman2/jobstore/cactus.img', u'cPecanLastz', u'--format=cigar', u'--notrivial', u'--step=1', u'--ambiguous=iupac,100,100', u'--ydrop=3000', u'tmpDACbhQ.tmp[multiple][nameparse=darkspace]', u'tmpidyx89.tmp[nameparse=darkspace]'] failed with output: None
Q/O/jobExNWJB    ERROR:toil.worker:Exiting the worker because of a failed job on host holy7b01214.rc.fas.harvard.edu
Q/O/jobExNWJB    WARNING:toil.jobGraph:Due to failure we are reducing the remaining retry count of job 'RunBlast' Q/O/jobExNWJB with ID Q/O/jobExNWJB to 5
Q/O/jobExNWJB    WARNING:toil.jobGraph:We have increased the default memory of the failed job 'RunBlast' Q/O/jobExNWJB to 2147483648 bytes
Issued job 'RunBlast' Q/O/jobExNWJB with job batch system ID: 32089 and cores: 1, disk: 100.0 M, and memory: 2.0 G
Job ended successfully: 'RunBlast' Q/O/jobExNWJB
```

**Comment by lparsons** [comment]
I have this same issue which causes quite a few jobs to need to be reissued.

**Comment by swomics** [comment]
I'm having the same issue on a Slurm system.

**Comment by nwvankuren** [comment]
Hello @joelarmstrong,

I can confirm this same issue with PBS (Torque) using singularity, despite upping defaultMemory. Jobs are not being reissued, but they are running quite slowly with only 100M mem. Thanks for any help!

**Comment by amizeranschi** [comment]
I'm also running into this issue, using SGE. After a few retries and successively increasing the memory, it eventually goes through.

@lassancejm did you explicitly specify the `--defaultMemory` setting and is this getting ignored by Cactus?

To be fair, the Cactus help message for this option does specify the following:

```
--defaultMemory INT   The default amount of memory to request for a job.
                        Only applicable to jobs that do not specify an
                        explicit value for this requirement. Standard suffixes
                        like K, Ki, M, Mi, G or Gi are supported. Default is
                        2.0 Gi
```

So, if I interpret this correctly, it looks like Cactus specifies `--defaultMemory ` by default to `100M` for `RunBlast` and other jobs. 

My guess is that this is by design, but it is strange, indeed, that the `--defaultMemory` setting would get ignored when the user actually specifies it.

@joelarmstrong, is there a chance that the user's option could be set as default for all the jobs?

**Comment by lassancejm** [comment]
@amizeranschi : playing with `--defaultMemory` doesn't do anything, most likely because the memory for `Runblast` is set to `100M` somewhere in the code, which supersede any user-specified value. 
I tried, without success, to identify the specific line of code before posting the issue.

**Comment by amizeranschi** [comment]
Hey @lassancejm 

See here (and the following posts) for the lines where the `RunBlast` memory is being set: https://github.com/ComparativeGenomicsToolkit/cactus/issues/63#issuecomment-474961046.

**Comment by lassancejm** [comment]
@amizeranschi: thanks for sharing the info!

**Comment by jasonsydes** [comment]
I'm running into the same problem.  

Would it be possible to increase the default value for RunBlast from 100MB up to 500MB or 2.0GB ?

When I run the evolverMammals.txt demo data, `toil stats jobStore` tells me that the memory consumed ranges from 119MB to 125MB.  Here are three different runs showing that:
```
 RunBlast
    Count |                                    Time* |                                    Clock |                                     Wait |                                   Memory
        n |      min    med*     ave     max   total |      min     med     ave     max   total |      min     med     ave     max   total |      min     med     ave     max   total
        3 |     1.63    1.75    5.76   13.90   17.27 |     1.56    1.63    5.66   13.81   16.99 |     0.07    0.09    0.09    0.12    0.28 |  119184K 119576K 121112K 124576K 363336K

 RunBlast
    Count |                                    Time* |                                    Clock |                                     Wait |                                   Memory
        n |      min    med*     ave     max   total |      min     med     ave     max   total |      min     med     ave     max   total |      min     med     ave     max   total
        3 |     1.48    2.23    5.36   12.36   16.07 |     1.41    2.16    5.29   12.29   15.86 |     0.07    0.07    0.07    0.07    0.21 |  119184K 119580K 121113K 124576K 363340K

 RunBlast
    Count |                                    Time* |                                    Clock |                                     Wait |                                   Memory
        n |      min    med*     ave     max   total |      min     med     ave     max   total |      min     med     ave     max   total |      min     med     ave     max   total
        3 |     0.82    1.16    4.07   10.24   12.22 |     0.71    1.06    3.97   10.13   11.91 |     0.10    0.11    0.10    0.11    0.31 |  119168K 119564K 121098K 124564K 363296K
```
When I do a more real world example, a 4-way run on the following species:
```
size assembly
1.2G astMex102.fa
1.4G danRer10.fa
921M lepOcu2.fa
705M xipMac1.fa
```
then it ranges from 195MB to 318MB.  Here is `toil stats jobStore` from two *partially* complete runs showing that:
```
 RunBlast
    Count |                                       Time* |                                       Clock |                                     Wait |                                    Memory
        n |      min    med*     ave     max      total |      min     med     ave     max      total |      min     med     ave     max   total |      min     med     ave     max    total
     3682 |    34.76  219.27  231.71  604.66  853164.53 |    34.55  218.97  231.33  604.97  851741.08 |    -0.68    0.28    0.39   66.08 1423.46 |  195376K 298380K 287605K 318188K1058961772K

 RunBlast
    Count |                                      Time* |                                      Clock |                                     Wait |                                    Memory
        n |      min    med*     ave     max     total |      min     med     ave     max     total |      min     med     ave     max   total |      min     med     ave     max    total
     1251 |    35.32  188.86  195.63  561.78 244735.13 |    35.10  188.28  194.99  529.80 243933.04 |    -0.81    0.25    0.64   67.35  802.08 |  259440K 276400K 286214K 314248K358054276K
```
That 4-way alignment run launches a bit over 8,000 RunBlast jobs, so it takes over an hour for all the 100MB jobs to launch and die before it moves on to the 2.0 GB version of the RunBlast jobs. 
```
$ grep Issued cactus.log | grep 'and memory: 100.0 M' | grep RunBlast | wc -l
8240
```
Perhaps a 2.0 GB default would be better?

Thank you!!
Jason
