### ISSUE TITLE
Issues with running the example

### ISSUE THREAD

**Issue by lningyawen** [ComparativeGenomicsToolkit/cactus#526]
Hello,

         I encountered some problems when I ran the example. First, I use command line `cactus jobStore examples/evolverMammals.txt examples/evolverMammals.hal --root mr` to test. Then I got this error reported: 
Traceback (most recent call last):
  File "/gpfs/home/liunyw/miniconda3/envs/cact/lib/python3.6/urllib/request.py", line 1349, in do_open
    encode_chunked=req.has_header('Transfer-encoding'))
  File "/gpfs/home/liunyw/miniconda3/envs/cact/lib/python3.6/http/client.py", line 1287, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/gpfs/home/liunyw/miniconda3/envs/cact/lib/python3.6/http/client.py", line 1333, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/gpfs/home/liunyw/miniconda3/envs/cact/lib/python3.6/http/client.py", line 1282, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/gpfs/home/liunyw/miniconda3/envs/cact/lib/python3.6/http/client.py", line 1042, in _send_output
    self.send(msg)
  File "/gpfs/home/liunyw/miniconda3/envs/cact/lib/python3.6/http/client.py", line 980, in send
    self.connect()
  File "/gpfs/home/liunyw/miniconda3/envs/cact/lib/python3.6/http/client.py", line 1440, in connect
    super().connect()
  File "/gpfs/home/liunyw/miniconda3/envs/cact/lib/python3.6/http/client.py", line 952, in connect
    (self.host,self.port), self.timeout, self.source_address)
  File "/gpfs/home/liunyw/miniconda3/envs/cact/lib/python3.6/socket.py", line 704, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
  File "/gpfs/home/liunyw/miniconda3/envs/cact/lib/python3.6/socket.py", line 745, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -2] Name or service not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/gpfs/home/liunyw/biosoft/cactus_env/bin/cactus", line 8, in <module>
    sys.exit(main())
  File "/gpfs/home/liunyw/biosoft/cactus_env/lib/python3.6/site-packages/cactus/progressive/cactus_progressive.py", line 406, in main
    runCactusProgressive(options)
  File "/gpfs/home/liunyw/biosoft/cactus_env/lib/python3.6/site-packages/cactus/progressive/cactus_progressive.py", line 441, in runCactusProgressive
    project.inputSequenceIDMap[genome] = toil.importFile(seq)
  File "/gpfs/home/liunyw/biosoft/cactus_env/lib/python3.6/site-packages/toil/common.py", line 1004, in importFile
    return self._jobStore.importFile(srcUrl, sharedFileName=sharedFileName, symlink=symlink)
  File "/gpfs/home/liunyw/biosoft/cactus_env/lib/python3.6/site-packages/toil/jobStores/abstractJobStore.py", line 307, in importFile
    return self._importFile(otherCls, srcUrl, sharedFileName=sharedFileName, hardlink=hardlink, symlink=symlink)
  File "/gpfs/home/liunyw/biosoft/cactus_env/lib/python3.6/site-packages/toil/jobStores/fileJobStore.py", line 303, in _importFile
    sharedFileName=sharedFileName)
  File "/gpfs/home/liunyw/biosoft/cactus_env/lib/python3.6/site-packages/toil/jobStores/abstractJobStore.py", line 328, in _importFile
    size, executable = otherCls._readFromUrl(url, writable)
  File "/gpfs/home/liunyw/biosoft/cactus_env/lib/python3.6/site-packages/toil/lib/retry.py", line 256, in call
    return func(*args, **kwargs)
  File "/gpfs/home/liunyw/biosoft/cactus_env/lib/python3.6/site-packages/toil/jobStores/abstractJobStore.py", line 1203, in _readFromUrl
    with closing(urlopen(url.geturl())) as readable:
  File "/gpfs/home/liunyw/miniconda3/envs/cact/lib/python3.6/urllib/request.py", line 223, in urlopen
    return opener.open(url, data, timeout)
  File "/gpfs/home/liunyw/miniconda3/envs/cact/lib/python3.6/urllib/request.py", line 526, in open
    response = self._open(req, data)
  File "/gpfs/home/liunyw/miniconda3/envs/cact/lib/python3.6/urllib/request.py", line 544, in _open
    '_open', req)
  File "/gpfs/home/liunyw/miniconda3/envs/cact/lib/python3.6/urllib/request.py", line 504, in _call_chain
    result = func(*args)
  File "/gpfs/home/liunyw/miniconda3/envs/cact/lib/python3.6/urllib/request.py", line 1392, in https_open
    context=self._context, check_hostname=self._check_hostname)
  File "/gpfs/home/liunyw/miniconda3/envs/cact/lib/python3.6/urllib/request.py", line 1351, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [Errno -2] Name or service not known>

I found `socket.gaierror` and `urllib.error.URLError` were about the network. Then I realized that I should use the parameter about the cluster, so I added the `--batchSystem torque`.  Then I encountered another error reporting: `--consCores required for non single_machine batch systems`. So I added the `--conScores 25` parameter.  

However,  I encountered the same problem I had at the beginning. What should I do about`socket.gaierror` and `urllib.error.URLError` ? And is it possible to write the parameter "--conScores 25" in this way, and what should follow after the "--conScores"?

Any help will be much appreciated, Thanks.

Yawen

**Comment by lningyawen** [comment]
Hi,
    I found that the reason for this error was that I needed to connect to the network to download the data when running the example, and the nodes on the cluster server were not connected to the network.
    Thank you for building such a great software!

Yawen
