### ISSUE TITLE
  FAILURE: in load_fasta_sequence for tmpfn4ja99_.tmp, sequence length 2,145,000,731+3,000,000

### ISSUE THREAD

**Issue by bioinformaticspcj** [ComparativeGenomicsToolkit/cactus#547]
Dear the authors,

Thanks a lot for devoloping such an useful program.  But, I still need your help since I met a error when I ran it with two genomes and do not have any idea to deal with.
The error is as follows:
 [2021-06-18T22:41:38+0800] [MainThread] [I] [cactus.shared.common] Running the command ['cPecanLastz', 'tmpfn4ja99_.tmp[multiple][nameparse=darkspace]', 'tmpqtkehfl5.tmp[nameparse=darkspace]', '--step=3', '--ambiguous=iupac,100,100', '--ungapped', '--queryhsplim
        FAILURE: in load_fasta_sequence for tmpfn4ja99_.tmp, sequence length 2,145,000,731+3,000,000 exceeds maximum (2,147,483,637)
        Traceback (most recent call last):
          File "/data/share/OriginTools/OriginTools/cactus/venv/lib/python3.6/site-packages/toil/worker.py", line 368, in workerScript
            job._runner(jobGraph=jobGraph, jobStore=jobStore, fileStore=fileStore, defer=defer)
          File "/data/share/OriginTools/OriginTools/cactus/venv/lib/python3.6/site-packages/cactus/shared/common.py", line 1424, in _runner
            fileStore=fileStore, **kwargs)
          File "/data/share/OriginTools/OriginTools/cactus/venv/lib/python3.6/site-packages/toil/job.py", line 1424, in _runner
            returnValues = self._run(jobGraph, fileStore)
          File "/data/share/OriginTools/OriginTools/cactus/venv/lib/python3.6/site-packages/toil/job.py", line 1361, in _run
            return self.run(fileStore)
          File "/data/share/OriginTools/OriginTools/cactus/venv/lib/python3.6/site-packages/cactus/preprocessor/lastzRepeatMasking/cactus_lastzRepeatMask.py", line 192, in run
            alignment = self.alignFastaFragments(fileStore, targetFiles, fragments)
          File "/data/share/OriginTools/OriginTools/cactus/venv/lib/python3.6/site-packages/cactus/preprocessor/lastzRepeatMasking/cactus_lastzRepeatMask.py", line 92, in alignFastaFragments
            "--markend"])
          File "/data/share/OriginTools/OriginTools/cactus/venv/lib/python3.6/site-packages/cactus/shared/common.py", line 1357, in cactus_call
            raise RuntimeError("Command {} exited {}: {}".format(call, process.returncode, out))
        RuntimeError: Command ['cPecanLastz', 'tmpfn4ja99_.tmp[multiple][nameparse=darkspace]', 'tmpqtkehfl5.tmp[nameparse=darkspace]', '--step=3', '--ambiguous=iupac,100,100', '--ungapped', '--queryhsplimit=keep,nowarn:1500', '--querydepth=keep,nowarn:13', '--format=ge
        [2021-06-18T22:43:31+0800] [MainThread] [E] [toil.worker] Exiting the worker because of a failed job on host toad

The command used is cactus --binariesMode local --logFile out_cactus.log cactusWorkPlace/ configure.txt mouse_Tdia.hal --disableCaching --disableHotDeployment --maxCores 30 --stats

Could you give me some advice?
Thanks again. 

Best,
Bob

**Comment by glennhickey** [comment]
This seems to be a duplicate of #356.  Reducing [the value of proportionSampled](https://github.com/ComparativeGenomicsToolkit/cactus/issues/356#issue-744943737) may be a workaround.  But be warned, Cactus has never been tested on 10G+ genomes.
