### ISSUE TITLE
ST_KV_DATABASE_EXCEPTION

### ISSUE THREAD

**Issue by lparsons** [ComparativeGenomicsToolkit/cactus#57]
I've been able to get the example data to run to completion on my workstation, but not on our cluster yet. I'm using Singularity 3.0.3 with the patch described in #55. We are using SLURM as the `batchSystem`. I'm running into two (possibly related) problems:

1. The workflow hangs on the `SavePrimaryDB` job. There seem to be two jobs running, one for the `KtServerService` and the second the `SavePrimaryDB` job. Neither is using any CPU or appears to be doing anything. Is it perhaps hung on writing to some filesystem? I've created a separate issue #60 for this.

2. `Exception: ST_KV_DATABASE_EXCEPTION: Opening connection to host: 127.0.0.1 with error: network error`
    I suspect this is due to the fact that the `KtServerService` job isn't running properly, or isn't running on the same node as the job trying to communicate with it? I'm not sure, but cactus retries the jobs and they seem to eventually succeed, except for the `SavePrimaryDB`, which simply never completes.

```
WARNING:toil.leader:The job seems to have left a log file, indicating failure: 'CactusSetupPhase' y/x/jobBBlOvT                          
WARNING:toil.leader:y/x/jobBBlOvT    INFO:toil.worker:---TOIL WORKER OUTPUT LOG---                                                       
WARNING:toil.leader:y/x/jobBBlOvT    INFO:toil:Running Toil version 3.18.0-84239d802248a5f4a220e762b3b8ce5cc92af0be.                     
WARNING:toil.leader:y/x/jobBBlOvT    WARNING:toil.resource:'JTRES_3ef5b3ea0b822be113fb2928b0c49342' may exist, but is not yet referenced by the worker (KeyError from os.environ[]).                                                                                               WARNING:toil.leader:y/x/jobBBlOvT    INFO:toil.lib.bioio:Sequences in cactus setup: ['simHuman_chr6', 'simMouse_chr6', 'simRat_chr6', 'simCow_chr6', 'simDog_chr6']                                                                                                                
WARNING:toil.leader:y/x/jobBBlOvT    INFO:toil.lib.bioio:Sequences in cactus setup filenames: ['>id=1|simHuman.chr6|0\n', '>id=0|simMouse.chr6\n', '>id=2|simRat.chr6\n', '>id=4|simCow.chr6|0\n', '>id=3|simDog.chr6|0\n']                                                        WARNING:toil.leader:y/x/jobBBlOvT    INFO:cactus.shared.common:Work dirs: set([u'/tmp/toil-36105e42-53df-4919-84a4-5a8802fd18bd-4c0800dd-a2a1-4d1f-84f4-956467d8a8ed/tmpPahA7T/db9e39ee-495d-440c-86dd-74fff75bac68'])                                                             
WARNING:toil.leader:y/x/jobBBlOvT    INFO:cactus.shared.common:Docker work dir: /tmp/toil-36105e42-53df-4919-84a4-5a8802fd18bd-4c0800dd-a2a1-4d1f-84f4-956467d8a8ed/tmpPahA7T/db9e39ee-495d-440c-86dd-74fff75bac68                                                                 
WARNING:toil.leader:y/x/jobBBlOvT    INFO:cactus.shared.common:Running the command ['singularity', '--silent', 'run', u'/tigress/lparsons/kocher_lab/cactus/jobStore/cactus.img', u'cactus_setup', u'--speciesTree', u'((simHuman_chr6:0.144018,(simMouse_chr6:0.084509,simRat_chr6:0.091589)mr:0.271974)Anc1:0.020593,(simCow_chr6:0.18908,simDog_chr6:0.16303)Anc2:0.032898)Anc0;', u'--cactusDisk', u'<st_kv_database_conf type="kyoto_tycoon">\n\t\t\t<kyoto_tycoon database_dir="fakepath" host="127.0.0.1" port="17863" />\n\t\t</st_kv_database_conf>\n\t', u'--logLevel', u'INFO', u'--outgroupEvents', u'simHuman_chr6 simDog_chr6 simCow_chr6', u'tmpjdxHjy.tmp', u'tmpwWt5NL.tmp', u'tmpa3RrMG.tmp', u'tmpzPWIax.tmp', u'tmpLU024t.tmp']                                                                                                      
WARNING:toil.leader:y/x/jobBBlOvT    Running command catchsegv 'cactus_setup' '--speciesTree' '((simHuman_chr6:0.144018,(simMouse_chr6:0.084509,simRat_chr6:0.091589)mr:0.271974)Anc1:0.020593,(simCow_chr6:0.18908,simDog_chr6:0.16303)Anc2:0.032898)Anc0;' '--cactusDisk' '<st_kv_database_conf type=kyoto_tycoon> <kyoto_tycoon database_dir=fakepath host=127.0.0.1 port=17863 /> </st_kv_database_conf> ' '--logLevel' 'INFO' '--outgroupEvents' 'simHuman_chr6 simDog_chr6 simCow_chr6' 'tmpjdxHjy.tmp' 'tmpwWt5NL.tmp' 'tmpa3RrMG.tmp' 'tmpzPWIax.tmp' 'tmpLU024t.tmp'                                                             
WARNING:toil.leader:y/x/jobBBlOvT    Set log level to INFO          
WARNING:toil.leader:y/x/jobBBlOvT    Flower disk name : <st_kv_database_conf type=kyoto_tycoon> <kyoto_tycoon database_dir=fakepath host=127.0.0.1 port=17863 /> </st_kv_database_conf>                                                                                            
WARNING:toil.leader:y/x/jobBBlOvT    Sequence file/directory tmpjdxHjy.tmp                                                               
WARNING:toil.leader:y/x/jobBBlOvT    Sequence file/directory tmpwWt5NL.tmp                                                               
WARNING:toil.leader:y/x/jobBBlOvT    Sequence file/directory tmpa3RrMG.tmp                                                               
WARNING:toil.leader:y/x/jobBBlOvT    Sequence file/directory tmpzPWIax.tmp                                                               
WARNING:toil.leader:y/x/jobBBlOvT    Sequence file/directory tmpLU024t.tmp                                                               
WARNING:toil.leader:y/x/jobBBlOvT    Exception: ST_KV_DATABASE_EXCEPTION: Opening connection to host: 127.0.0.1 with error: network error                                                                                                                                          
WARNING:toil.leader:y/x/jobBBlOvT    Uncaught exception             
WARNING:toil.leader:y/x/jobBBlOvT    Traceback (most recent call last):                                                                  
WARNING:toil.leader:y/x/jobBBlOvT      File "/home/lparsons/miniconda3/envs/cactus/lib/python2.7/site-packages/toil/worker.py", line 314, in workerScript                                                                                                                          
WARNING:toil.leader:y/x/jobBBlOvT        job._runner(jobGraph=jobGraph, jobStore=jobStore, fileStore=fileStore)                          
WARNING:toil.leader:y/x/jobBBlOvT      File "/home/lparsons/miniconda3/envs/cactus/lib/python2.7/site-packages/cactus/shared/common.py", line 1094, in _runner                                                                                                                     
WARNING:toil.leader:y/x/jobBBlOvT        super(RoundedJob, self)._runner(jobGraph=jobGraph, jobStore=jobStore, fileStore=fileStore)      
WARNING:toil.leader:y/x/jobBBlOvT      File "/home/lparsons/miniconda3/envs/cactus/lib/python2.7/site-packages/toil/job.py", line 1351, in _runner                                                                                                                                 
WARNING:toil.leader:y/x/jobBBlOvT        returnValues = self._run(jobGraph, fileStore)                                                   
WARNING:toil.leader:y/x/jobBBlOvT      File "/home/lparsons/miniconda3/envs/cactus/lib/python2.7/site-packages/toil/job.py", line 1296, in _run                                                                                                                                    
WARNING:toil.leader:y/x/jobBBlOvT        return self.run(fileStore) 
WARNING:toil.leader:y/x/jobBBlOvT      File "/home/lparsons/miniconda3/envs/cactus/lib/python2.7/site-packages/cactus/pipeline/cactus_workflow.py", line 641, in run                                                                                                               WARNING:toil.leader:y/x/jobBBlOvT        makeEventHeadersAlphaNumeric=self.getOptionalPhaseAttrib("makeEventHeadersAlphaNumeric", bool, False))                                                                                                                                    
WARNING:toil.leader:y/x/jobBBlOvT      File "/home/lparsons/miniconda3/envs/cactus/lib/python2.7/site-packages/cactus/shared/common.py", line 220, in runCactusSetup                                                                                                               
WARNING:toil.leader:y/x/jobBBlOvT        parameters=["cactus_setup"] + args + sequences)                                                 
WARNING:toil.leader:y/x/jobBBlOvT      File "/home/lparsons/miniconda3/envs/cactus/lib/python2.7/site-packages/cactus/shared/common.py", line 1038, in cactus_call                                                                                                                 
WARNING:toil.leader:y/x/jobBBlOvT        raise RuntimeError("Command %s failed with output: %s" % (call, output))                        
WARNING:toil.leader:y/x/jobBBlOvT    RuntimeError: Command ['singularity', '--silent', 'run', u'/tigress/lparsons/kocher_lab/cactus/jobStore/cactus.img', u'cactus_setup', u'--speciesTree', u'((simHuman_chr6:0.144018,(simMouse_chr6:0.084509,simRat_chr6:0.091589)mr:0.271974)Anc1:0.020593,(simCow_chr6:0.18908,simDog_chr6:0.16303)Anc2:0.032898)Anc0;', u'--cactusDisk', u'<st_kv_database_conf type="kyoto_tycoon">\n\t\t\t<kyoto_tycoon database_dir="fakepath" host="127.0.0.1" port="17863" />\n\t\t</st_kv_database_conf>\n\t', u'--logLevel', u'INFO', u'--outgroupEvents', u'simHuman_chr6 simDog_chr6 simCow_chr6', u'tmpjdxHjy.tmp', u'tmpwWt5NL.tmp', u'tmpa3RrMG.tmp', u'tmpzPWIax.tmp', u'tmpLU024t.tmp'] failed with output:                                                                                                          
WARNING:toil.leader:y/x/jobBBlOvT    ERROR:toil.worker:Exiting the worker because of a failed job on host della-r4c4n14                  
WARNING:toil.leader:y/x/jobBBlOvT    WARNING:toil.jobGraph:Due to failure we are reducing the remaining retry count of job 'CactusSetupPhase' y/x/jobBBlOvT with ID y/x/jobBBlOvT to 5                                                                                             
```

**Comment by tsackton** [comment]
I am also seeing the ST_KV_DATABASE_EXCEPTION error, running with singularity 2.6.1 and latest version of progressiveCactus on the same test data.

Specifically, I see a lot of network errors, e.g., 
```
(py27) [tsackton@bioinf02 cactus]$ grep "Exception: ST_KV_DATABASE_EXCEPTION: Opening connection to host: " *.log
logfile_slurm_3.log:WARNING:toil.leader:W/u/jobMAMhgY    Exception: ST_KV_DATABASE_EXCEPTION: Opening connection to host: 10.31.130.249 with error: network error
logfile_slurm_3.log:WARNING:toil.leader:W/u/jobMAMhgY    Exception: ST_KV_DATABASE_EXCEPTION: Opening connection to host: 10.31.130.249 with error: network error
logfile_slurm_3.log:WARNING:toil.leader:W/u/jobMAMhgY    Exception: ST_KV_DATABASE_EXCEPTION: Opening connection to host: 10.31.130.249 with error: network error
logfile_slurm_3.log:WARNING:toil.leader:W/u/jobMAMhgY    Exception: ST_KV_DATABASE_EXCEPTION: Opening connection to host: 10.31.130.249 with error: network error
logfile_slurm_3.log:WARNING:toil.leader:W/u/jobMAMhgY    Exception: ST_KV_DATABASE_EXCEPTION: Opening connection to host: 10.31.130.249 with error: network error
logfile_slurm_3.log:WARNING:toil.leader:W/u/jobMAMhgY    Exception: ST_KV_DATABASE_EXCEPTION: Opening connection to host: 10.31.130.249 with error: network error
logfile_slurm_3.log:WARNING:toil.leader:Y/4/jobT1BXlw    Exception: ST_KV_DATABASE_EXCEPTION: Opening connection to host: 10.31.130.249 with error: network error
logfile_slurm_3.log:WARNING:toil.leader:0/W/jobcYd5p3    Exception: ST_KV_DATABASE_EXCEPTION: Opening connection to host: 10.31.130.249 with error: network error
logfile_slurm_3.log:WARNING:toil.leader:0/K/jobT_Nt8l    Exception: ST_KV_DATABASE_EXCEPTION: Opening connection to host: 10.31.130.249 with error: network error
logfile_slurm_3.log:WARNING:toil.leader:0/W/jobcYd5p3    Exception: ST_KV_DATABASE_EXCEPTION: Opening connection to host: 10.31.130.249 with error: network error
logfile_slurm_3.log:WARNING:toil.leader:0/K/jobT_Nt8l    Exception: ST_KV_DATABASE_EXCEPTION: Opening connection to host: 10.31.130.249 with error: network error
logfile_slurm_3.log:WARNING:toil.leader:0/K/jobT_Nt8l    Exception: ST_KV_DATABASE_EXCEPTION: Opening connection to host: 10.31.130.249 with error: network error
logfile_slurm_3.log:WARNING:toil.leader:0/K/jobT_Nt8l    Exception: ST_KV_DATABASE_EXCEPTION: Opening connection to host: 10.31.130.249 with error: network error
logfile_slurm_3.log:WARNING:toil.leader:0/W/jobcYd5p3    Exception: ST_KV_DATABASE_EXCEPTION: Opening connection to host: 10.31.130.249 with error: network error
logfile_slurm_3.log:WARNING:toil.leader:0/W/jobcYd5p3    Exception: ST_KV_DATABASE_EXCEPTION: Opening connection to host: 10.31.130.249 with error: network error
logfile_slurm_3.log:WARNING:toil.leader:0/K/jobT_Nt8l    Exception: ST_KV_DATABASE_EXCEPTION: Opening connection to host: 10.31.130.249 with error: network error
logfile_slurm_3.log:WARNING:toil.leader:0/W/jobcYd5p3    Exception: ST_KV_DATABASE_EXCEPTION: Opening connection to host: 10.31.130.249 with error: network error
logfile_slurm_3.log:WARNING:toil.leader:Y/4/jobT1BXlw    Exception: ST_KV_DATABASE_EXCEPTION: Opening connection to host: 10.31.130.249 with error: network error
logfile_slurm_3.log:WARNING:toil.leader:0/K/jobT_Nt8l    Exception: ST_KV_DATABASE_EXCEPTION: Opening connection to host: 10.31.130.249 with error: network error
logfile_slurm_3.log:WARNING:toil.leader:Y/4/jobT1BXlw    Exception: ST_KV_DATABASE_EXCEPTION: Opening connection to host: 10.31.130.249 with error: network error
logfile_slurm_3.log:WARNING:toil.leader:Y/4/jobT1BXlw    Exception: ST_KV_DATABASE_EXCEPTION: Opening connection to host: 10.31.130.249 with error: network error
logfile_slurm_3.log:WARNING:toil.leader:Y/4/jobT1BXlw    Exception: ST_KV_DATABASE_EXCEPTION: Opening connection to host: 10.31.130.249 with error: network error
logfile_slurm_3.log:WARNING:toil.leader:Y/4/jobT1BXlw    Exception: ST_KV_DATABASE_EXCEPTION: Opening connection to host: 10.31.130.249 with error: network error
logfile_slurm_3.log:WARNING:toil.leader:8/b/jobjS_1G2    Exception: ST_KV_DATABASE_EXCEPTION: Opening connection to host: 10.31.128.184 with error: network error
logfile_slurm_3.log:WARNING:toil.leader:8/b/jobjS_1G2    Exception: ST_KV_DATABASE_EXCEPTION: Opening connection to host: 10.31.128.184 with error: network error
logfile_slurm_3.log:WARNING:toil.leader:8/b/jobjS_1G2    Exception: ST_KV_DATABASE_EXCEPTION: Opening connection to host: 10.31.128.184 with error: network error
logfile_slurm_3.log:WARNING:toil.leader:8/b/jobjS_1G2    Exception: ST_KV_DATABASE_EXCEPTION: Opening connection to host: 10.31.128.184 with error: network error
logfile_slurm_3.log:WARNING:toil.leader:8/b/jobjS_1G2    Exception: ST_KV_DATABASE_EXCEPTION: Opening connection to host: 10.31.128.184 with error: network error
logfile_slurm_3.log:WARNING:toil.leader:8/b/jobjS_1G2    Exception: ST_KV_DATABASE_EXCEPTION: Opening connection to host: 10.31.128.184 with error: network error
logfile_slurm_3.log:WARNING:toil.leader:J/O/jobZkDBNH    Exception: ST_KV_DATABASE_EXCEPTION: Opening connection to host: 10.31.130.249 with error: network error
logfile_slurm_3.log:WARNING:toil.leader:R/Y/jobziuk_f    Exception: ST_KV_DATABASE_EXCEPTION: Opening connection to host: 10.31.130.249 with error: network error
logfile_slurm_3.log:WARNING:toil.leader:J/O/jobZkDBNH    Exception: ST_KV_DATABASE_EXCEPTION: Opening connection to host: 10.31.130.249 with error: network error
logfile_slurm_3.log:WARNING:toil.leader:M/U/jobPEGnpz    Exception: ST_KV_DATABASE_EXCEPTION: Opening connection to host: 10.31.130.249 with error: network error
logfile_slurm_3.log:WARNING:toil.leader:R/Y/jobziuk_f    Exception: ST_KV_DATABASE_EXCEPTION: Opening connection to host: 10.31.130.249 with error: network error
logfile_slurm_3.log:WARNING:toil.leader:M/U/jobPEGnpz    Exception: ST_KV_DATABASE_EXCEPTION: Opening connection to host: 10.31.130.249 with error: network error
logfile_slurm_3.log:WARNING:toil.leader:R/Y/jobziuk_f    Exception: ST_KV_DATABASE_EXCEPTION: Opening connection to host: 10.31.130.249 with error: network error
logfile_slurm_3.log:WARNING:toil.leader:M/U/jobPEGnpz    Exception: ST_KV_DATABASE_EXCEPTION: Opening connection to host: 10.31.130.249 with error: network error
logfile_slurm_3.log:WARNING:toil.leader:R/Y/jobziuk_f    Exception: ST_KV_DATABASE_EXCEPTION: Opening connection to host: 10.31.130.249 with error: network error
logfile_slurm_3.log:WARNING:toil.leader:J/O/jobZkDBNH    Exception: ST_KV_DATABASE_EXCEPTION: Opening connection to host: 10.31.130.249 with error: network error
logfile_slurm_3.log:WARNING:toil.leader:R/Y/jobziuk_f    Exception: ST_KV_DATABASE_EXCEPTION: Opening connection to host: 10.31.130.249 with error: network error
logfile_slurm_3.log:WARNING:toil.leader:J/O/jobZkDBNH    Exception: ST_KV_DATABASE_EXCEPTION: Opening connection to host: 10.31.130.249 with error: network error
logfile_slurm_3.log:WARNING:toil.leader:R/Y/jobziuk_f    Exception: ST_KV_DATABASE_EXCEPTION: Opening connection to host: 10.31.130.249 with error: network error
logfile_slurm_3.log:WARNING:toil.leader:J/O/jobZkDBNH    Exception: ST_KV_DATABASE_EXCEPTION: Opening connection to host: 10.31.130.249 with error: network error
logfile_slurm_3.log:WARNING:toil.leader:J/O/jobZkDBNH    Exception: ST_KV_DATABASE_EXCEPTION: Opening connection to host: 10.31.130.249 with error: network error
logfile_slurm_3.log:WARNING:toil.leader:M/U/jobPEGnpz    Exception: ST_KV_DATABASE_EXCEPTION: Opening connection to host: 10.31.130.249 with error: network error
logfile_slurm_3.log:WARNING:toil.leader:M/U/jobPEGnpz    Exception: ST_KV_DATABASE_EXCEPTION: Opening connection to host: 10.31.130.249 with error: network error
logfile_slurm_3.log:WARNING:toil.leader:M/U/jobPEGnpz    Exception: ST_KV_DATABASE_EXCEPTION: Opening connection to host: 10.31.130.249 with error: network error
logfile_slurm_3.log:WARNING:toil.leader:T/k/jobH39D4e    Exception: ST_KV_DATABASE_EXCEPTION: Opening connection to host: 10.31.128.189 with error: network error
logfile_slurm_3.log:WARNING:toil.leader:T/k/jobH39D4e    Exception: ST_KV_DATABASE_EXCEPTION: Opening connection to host: 10.31.128.189 with error: network error
logfile_slurm_3.log:WARNING:toil.leader:T/k/jobH39D4e    Exception: ST_KV_DATABASE_EXCEPTION: Opening connection to host: 10.31.128.189 with error: network error
logfile_slurm_3.log:WARNING:toil.leader:T/k/jobH39D4e    Exception: ST_KV_DATABASE_EXCEPTION: Opening connection to host: 10.31.128.189 with error: network error
logfile_slurm_3.log:WARNING:toil.leader:T/k/jobH39D4e    Exception: ST_KV_DATABASE_EXCEPTION: Opening connection to host: 10.31.128.189 with error: network error
logfile_slurm_3.log:WARNING:toil.leader:T/k/jobH39D4e    Exception: ST_KV_DATABASE_EXCEPTION: Opening connection to host: 10.31.128.189 with error: network error
logfile_slurm_3.log:WARNING:toil.leader:X/x/jobuUaQQ2    Exception: ST_KV_DATABASE_EXCEPTION: Opening connection to host: 10.31.133.81 with error: network error
logfile_slurm_3.log:WARNING:toil.leader:X/x/jobuUaQQ2    Exception: ST_KV_DATABASE_EXCEPTION: Opening connection to host: 10.31.133.81 with error: network error
logfile_slurm_3.log:WARNING:toil.leader:X/x/jobuUaQQ2    Exception: ST_KV_DATABASE_EXCEPTION: Opening connection to host: 10.31.133.81 with error: network error
logfile_slurm_3.log:WARNING:toil.leader:X/x/jobuUaQQ2    Exception: ST_KV_DATABASE_EXCEPTION: Opening connection to host: 10.31.133.81 with error: network error
logfile_slurm_3.log:WARNING:toil.leader:X/x/jobuUaQQ2    Exception: ST_KV_DATABASE_EXCEPTION: Opening connection to host: 10.31.133.81 with error: network error
logfile_slurm_3.log:WARNING:toil.leader:X/x/jobuUaQQ2    Exception: ST_KV_DATABASE_EXCEPTION: Opening connection to host: 10.31.133.81 with error: network error
```

The jobs that fail with this error are not always SavePrimaryDB, and some jobs succeed, so it seems to have to do with whether the host that the ktserver is running on is reachable from the specific compute node a later job lands on. 

Is there any way to control the node that the ktserver lands on, e.g. force it to run on the high memory machine the job is launched from? In previous versions of progressiveCactus I've managed this by tinkering with the bigBatchSystem options (to force the ktserver job to use the bigBatchSystem), but it is not clear if this is still an option with the new Toil version.

**Comment by lparsons** [comment]
In looking into this a bit more, it seems that perhaps the processes are getting the wrong port number. When I log into the node that is running `ktserver` it seems to be listening on a different port than what is being used in the commands. Going to investigate further...

**Comment by lparsons** [comment]
I'm not sure about the ports (thus removed that comment)... digging through so many scattered logs and temp directories is confusing. I'll put more info if/when I can confirm anything.

On my system at least, there *should* be no issues connecting from one node to another, so I'm a bit confused about the errors. Any ideas as to how we can possibly get some more detail on this problem? Or perhaps a some easier way to test/debug the ktserver stuff? I'm thinking something like running a simple ktserver instance and issuing some commands to see what does/doesn't work.

**Comment by lparsons** [comment]
OK, a bit more testing has revealed two separate issues. I am now simple trying to run the example workflow on our interactive node and it gets "stuck" on the `SavePrimaryDB` step every time. No errors that I can find, but things just stop. See attached logfile: [cactus_localrun.log.gz](https://github.com/ComparativeGenomicsToolkit/cactus/files/2822978/cactus_localrun.log.gz)

The other issue occurs when I run using SLURM. That's were I run into `ST_KV_DATABASE_EXCEPTION`, even when trying to connect on localhost. Nodes on my system should be able to communicate with one another, so I'm not sure what the problem actually is.

**Comment by lparsons** [comment]
I seem to be able to get things to complete (with various workarounds for Singularity 3) now. However, whenever I set `--logLevel DEBUG` or `--logDebug` I run into this problem. This leads me to believe that it is not an actual network error, but instead some invalid argument formatting that is causing a non-zero exit code from a process, which is incorrectly interpreted as a network error. 

@tsackton Could you try running *without* turning on `--logLevel DEBUG` and see if you can get things to complete? Thanks.

**Comment by lparsons** [comment]
Oddly enough, I seem to be able to rerun the pipeline with debug on, I still got errors, but this time it completed successfully (eventually). This appears to be something that happens occasionally. Is there some non-deterministic part of this workflow? Also, any thoughts as to why I see this only with DEBUG on? Is that because the error is silenced otherwise?

**Comment by lparsons** [comment]
Continued testing shows that I get this error *even when the server is on the same host*:
```
Exception: ST_KV_DATABASE_EXCEPTION: Opening connection to host: 127.0.0.1 with error: network error
```

This occurs with debug off, at least on some runs and at least on some cluster systems. At this point, I am not able to replicate runs *even on the same system* when using the example data. 

@joelarmstrong Is there some way to set a random seed to ensure any non-deterministic parts of the workflow run the same? The inability to get the same errors or results from one run to the next is disconcerting, and makes debugging quite difficult.

**Comment by lparsons** [comment]
On at leaast one of our clusters, the code used to determine a "public IP" doesn't work and ends up returning 127.0.0.1 which inevitably fails. I'm not sure of the appropriate fix at the moment, except that it seems it would be necessary to be able to choose a method that would work for the given grid environment as the current approach doesn't generalize well.

https://github.com/ComparativeGenomicsToolkit/cactus/blob/d9039e7118a71fd7fbe1344b9c5f76845f30f28f/src/cactus/pipeline/ktserverControl.py#L239-L257

**Comment by amizeranschi** [comment]
@lparsons and @tsackton, did you ever get this fixed somehow? I'm having a similar issue on a SGE cluster while running the evolverMammals example: https://github.com/ComparativeGenomicsToolkit/cactus/issues/63.

Things run fine on a single node, but fail with `Exception: ST_KV_DATABASE_EXCEPTION: Opening connection to host: 172.16.13.37 with error: network error` when running distributed on an SGE queue. The cluster nodes should be able to communicate with each other, so I'm not sure what could cause the connection to fail.

I'm using a local Cactus install, as Docker and Singularity aren't supported by the cluster.

**Comment by lparsons** [comment]
I ended up with a couple of different solutions to this. The first was a simple firewall rule that was preventing communication (despite assurances communication was allowed ;-) ). 

The second was resolved by the system admins who kinda changed the cluster configuration to allow the `getPublicIP` code to work. I'd prefer to get a more robust (or at least configurable) method for the `getPublicIP`, but I don't have any great options at the moment.

**Comment by amizeranschi** [comment]
@lparsons Thanks a lot for the reply. Do you remember anything more specific about the firewall rule that was preventing communication? I've gotten in touch with the cluster admin and I suspect that it may be a similar issue, so any further clues you could provide would be much appreciated.

**Comment by lparsons** [comment]
The issue on the cluster where the `getPublicIP` did work, but I still got the error (which seems more similar to your case) was a problem with `iptables`. The fix implemented was to turn off `iptables` completely on the nodes (which are only on the private cluster network).

**Comment by lparsons** [comment]
I believe I have addressed all of the reasons that this error occurred for us. See #60 and #67 for additional info.
