### ISSUE TITLE
Runtime error on example data

### ISSUE THREAD

**Issue by SidG13** [ComparativeGenomicsToolkit/cactus#574]
I'm running the example evolverMammals.txt file after downloading and installing from the precompiled binaries and ran into a runtime error. 

I'm using Ubuntu 14.04.6 LTS with 32GB of RAM on 12 cores, which should be enough for the small example dataset. I wasn't able to find solutions by looking at the previous issues. Is there a problem with my version of Ubuntu being to old?

`Traceback (most recent call last):
	  File "/home/lab/Desktop/Sid/apps/cactus-bin-v2.0.3/cactus_env/lib/python3.6/site-packages/toil/worker.py", line 393, in workerScript
	    job._runner(jobGraph=None, jobStore=jobStore, fileStore=fileStore, defer=defer)
	  File "/home/lab/Desktop/Sid/apps/cactus-bin-v2.0.3/cactus_env/lib/python3.6/site-packages/cactus/shared/common.py", line 933, in _runner
	    fileStore=fileStore, **kwargs)
	  File "/home/lab/Desktop/Sid/apps/cactus-bin-v2.0.3/cactus_env/lib/python3.6/site-packages/toil/job.py", line 2360, in _runner
	    returnValues = self._run(jobGraph=None, fileStore=fileStore)
	  File "/home/lab/Desktop/Sid/apps/cactus-bin-v2.0.3/cactus_env/lib/python3.6/site-packages/toil/job.py", line 2281, in _run
	    return self.run(fileStore)
	  File "/home/lab/Desktop/Sid/apps/cactus-bin-v2.0.3/cactus_env/lib/python3.6/site-packages/cactus/pipeline/cactus_workflow.py", line 420, in run
	    cores=self.cores)
	  File "/home/lab/Desktop/Sid/apps/cactus-bin-v2.0.3/cactus_env/lib/python3.6/site-packages/cactus/shared/common.py", line 198, in runCactusConsolidated
	    parameters=["cactus_consolidated"] + args)[1] # Get just the standard error output
	  File "/home/lab/Desktop/Sid/apps/cactus-bin-v2.0.3/cactus_env/lib/python3.6/site-packages/cactus/shared/common.py", line 868, in cactus_call
	    raise RuntimeError("Command {} signaled {}: {}".format(call, signal.Signals(-process.returncode).name, out))
	RuntimeError: Command ['cactus_consolidated', '--sequences', 'simCow_chr6 /tmp/1fc2688f980b5cffbc4c22d3c34bfd13/8821/7946/tmp061qasul.tmp simDog_chr6 /tmp/1fc2688f980b5cffbc4c22d3c34bfd13/8821/7946/tmpa8n_uq3b.tmp simHuman_chr6 /tmp/1fc2688f980b5cffbc4c22d3c34bfd13/8821/7946/tmpy02rnw52.tmp simMouse_chr6 /tmp/1fc2688f980b5cffbc4c22d3c34bfd13/8821/7946/tmpk8xdddnt.tmp simRat_chr6 /tmp/1fc2688f980b5cffbc4c22d3c34bfd13/8821/7946/tmpsjzu9vnx.tmp', '--speciesTree', '((simHuman_chr6:0.144018,(simMouse_chr6:0.084509,simRat_chr6:0.091589)mr:0.271974)Anc1:0.020593,(simCow_chr6:0.18908,simDog_chr6:0.16303)Anc2:0.032898)Anc0;', '--logLevel', 'INFO', '--alignments', '/tmp/1fc2688f980b5cffbc4c22d3c34bfd13/8821/7946/tmp8no_bvz5.tmp', '--params', '/tmp/1fc2688f980b5cffbc4c22d3c34bfd13/8821/7946/tmpxk77wwip.tmp', '--outputFile', '/tmp/1fc2688f980b5cffbc4c22d3c34bfd13/8821/7946/tmpmg8kl67p.tmp', '--outputHalFastaFile', '/tmp/1fc2688f980b5cffbc4c22d3c34bfd13/8821/7946/tmphskuiipo.tmp', '--outputReferenceFile', '/tmp/1fc2688f980b5cffbc4c22d3c34bfd13/8821/7946/tmpdf_6vc0n.tmp', '--outgroupEvents', 'simHuman_chr6 simMouse_chr6 simRat_chr6', '--referenceEvent', 'Anc2', '--secondaryAlignments', '/tmp/1fc2688f980b5cffbc4c22d3c34bfd13/8821/7946/tmp7q5gxj9j.tmp', '--threads', '12'] signaled SIGILL: stdout=, stderr=None
	[2021-09-04T16:40:13-0500] [MainThread] [E] [toil.worker] Exiting the worker because of a failed job on host computer1`

**Comment by LQHHHHH** [comment]
I also meet the same problem. Have you addressed this problem?

**Comment by glennhickey** [comment]
`SIGILL` means your cpu is too old to support Cactus.  From the [release page](https://github.com/ComparativeGenomicsToolkit/cactus/releases/tag/v2.0.3)

> The Docker images and binaries linked above are built using AVX2 extensions, and require a CPU that supports them, except the "Pre-compiled Binaries For Older CPU Architectures" which should be compatible with any 64-bit architecture (but don't yet support the Cactus's pangenome pipeline).

Really should add a more informative error message for this...
