### ISSUE TITLE
File not found error

### ISSUE THREAD

**Issue by kushalsuryamohan** [ComparativeGenomicsToolkit/cactus#577]
Hello,
I am trying to run Progressive cactus using Docker for 4 species of interest.
I am able to successfully run cactus using the example command provided:

```
docker run -v $(pwd):/data --rm -it quay.io/comparative-genomics-toolkit/cactus:v2.0.3 cactus /data/jobStore /data/evolverMammals.txt /data/evolverMammals.hal --root mr --binariesMode local

```

Next, I created a seqFile to specify my genomes of interest in the seqFile as below:
```
(BUN:35.00000000,(DEN:35.00000000,(NAJ:20.54730333,NIG:20.54730333)'14':14.45269667)'13':0.00000000);
BUN /home/kushal.s/bun_HiC_scaffs_over_10Mb.fasta
DEN /home/kushal.s/den_HiC_scaffs_over_10Mb.fasta
NAJ /home/kushal.s/naj_HiC_scaffs_over_10Mb.fasta
NIG /home/kushal.s/nig_HiC_scaffs_over_10Mb.fasta
```

However, when I try to run cactus, I am faced with the following error:
```

-bash-4.2$ docker run -v $(pwd):/data --rm quay.io/comparative-genomics-toolkit/cactus:v2.0.3 cactus /data/jobStore seqfile.txt /data/rept.hal --binariesMode local

[2021-09-24T22:40:59+0000] [MainThread] [I] [toil.statsAndLogging] xmlRoot = <multi_cactus inputSequenceNames="BUN DEN NAJ NIG" inputSequences="/home/kushal.s/bun_HiC_scaffs_over_10Mb.fasta  /home/kushal.s/den_HiC_scaffs_over_10Mb.fasta /home/kushal.s/naj_HiC_scaffs_over_10Mb.fasta  /home/kushal.s/nig_HiC_scaffs_over_10Mb.fasta">
        <tree>(BUN:35.0,(DEN:35.0,(NAJ:20.54730333,NIG:20.54730333)14:14.45269667)13:0.0)Anc0;</tree>
        <cactus experiment_path="/tmp/tmpdti92dzc/progressiveAlignment/Anc0/Anc0_experiment.xml" name="Anc0" />
        <cactus experiment_path="/tmp/tmpdti92dzc/progressiveAlignment/13/13_experiment.xml" name="13" />
        <cactus experiment_path="/tmp/tmpdti92dzc/progressiveAlignment/14/14_experiment.xml" name="14" />
</multi_cactus>
Traceback (most recent call last):
  File "/usr/local/bin/cactus", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.6/dist-packages/cactus/progressive/cactus_progressive.py", line 406, in main
    runCactusProgressive(options)
  File "/usr/local/lib/python3.6/dist-packages/cactus/progressive/cactus_progressive.py", line 441, in runCactusProgressive
    project.inputSequenceIDMap[genome] = toil.importFile(seq)
  File "/usr/local/lib/python3.6/dist-packages/toil/common.py", line 1025, in importFile
    return self._jobStore.importFile(srcUrl, sharedFileName=sharedFileName, symlink=symlink)
  File "/usr/local/lib/python3.6/dist-packages/toil/jobStores/abstractJobStore.py", line 324, in importFile
    return self._importFile(otherCls, parseResult, sharedFileName=sharedFileName, hardlink=hardlink, symlink=symlink)
  File "/usr/local/lib/python3.6/dist-packages/toil/jobStores/fileJobStore.py", line 290, in _importFile
    executable = os.stat(url.path).st_mode & stat.S_IXUSR != 0
FileNotFoundError: [Errno 2] No such file or directory: '/home/kushal.s/bun_HiC_scaffs_over_10Mb.fasta'
```

The file in question exists and I am not sure what the problem/issue here is. 

Any help is much appreciated.

Thanks!

**Comment by glennhickey** [comment]
Docker containers can't access arbitrary file locations.  You need to mount them with `-v`.  If you want to see what files docker sees, run `bash` instead of the `cactus` command after `docker run` to open an interactive session.

**Comment by glennhickey** [comment]
Not really, those warnings can usually be safely ignored.  It's on us to make cactus jobs more conservative about estimating their disk usage, and it hasn't been a super high priority
