### ISSUE TITLE
AssertionError when running on aws

### ISSUE THREAD

**Issue by xieduo7** [ComparativeGenomicsToolkit/cactus#58]
Run the command:
```
nohup cactus --stats --nodeTypes c4.8xlarge:0.9,r3.8xlarge --minNodes 0,0 --maxNodes 70,4 --provisioner aws --batchSystem mesos --metrics aws:us-east-1:primate-jobstore seqFile.txt s3://primate-output/cactus.hal > cactus.log 2>&1
```
And then cactus report error:
```
nohup: ignoring input
/usr/local/lib/python2.7/dist-packages/cryptography/hazmat/primitives/constant_time.py:26: CryptographyDeprecationWarning: Support for your Python version is deprecated. The next version of cryptography will remove support. Please upgrade to a 2.7.x release that supports hmac.compare_digest as soon as possible.
  utils.DeprecatedIn23,
WARNING:toil.jobStores.aws.jobStore:Exception during panic
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/toil/jobStores/aws/jobStore.py", line 135, in initialize
    self.destroy()
  File "/usr/local/lib/python2.7/dist-packages/toil/jobStores/aws/jobStore.py", line 1255, in destroy
    self._bind(create=False, block=False)
  File "/usr/local/lib/python2.7/dist-packages/toil/jobStores/aws/jobStore.py", line 167, in _bind
    versioning=True)
  File "/usr/local/lib/python2.7/dist-packages/toil/jobStores/aws/jobStore.py", line 736, in _bindBucket
    assert False, 'Cannot modify versioning on existing bucket'
AssertionError: Cannot modify versioning on existing bucket
Traceback (most recent call last):
  File "/venv/bin/cactus", line 10, in <module>
    sys.exit(main())
  File "/venv/local/lib/python2.7/site-packages/cactus/progressive/cactus_progressive.py", line 454, in main
    with Toil(options) as toil:
  File "/usr/local/lib/python2.7/dist-packages/toil/common.py", line 712, in __enter__
    jobStore.initialize(config)
  File "/usr/local/lib/python2.7/dist-packages/toil/jobStores/aws/jobStore.py", line 135, in initialize
    self.destroy()
  File "/usr/local/lib/python2.7/dist-packages/toil/lib/exceptions.py", line 55, in __exit__
    raise_(exc_type, exc_value, traceback)
  File "/usr/local/lib/python2.7/dist-packages/toil/jobStores/aws/jobStore.py", line 132, in initialize
    self._bind(create=True)
  File "/usr/local/lib/python2.7/dist-packages/toil/jobStores/aws/jobStore.py", line 167, in _bind
    versioning=True)
  File "/usr/local/lib/python2.7/dist-packages/toil/jobStores/aws/jobStore.py", line 736, in _bindBucket
    assert False, 'Cannot modify versioning on existing bucket'
AssertionError: Cannot modify versioning on existing bucket
```
I have set the versioning of the bucket(s3://primate-output/) and it still doesn't work.

**Comment by joelarmstrong** [comment]
Ah, interesting, I didn't know that toil required the destination buckets to have versioning. If someone runs into this problem in the future and can't delete the destination bucket, you can likely turn on versioning for that bucket (in the web UI), then turn it back off after you're done.
