### ISSUE TITLE
 Job used more disk than requested error

### ISSUE THREAD

**Issue by samkleeman1** [ComparativeGenomicsToolkit/cactus#582]
Hi,

I am trying to align two mouse sub-strains using the pangenome approach, with cactus run as a singularity container. I can see that Toil is only assigning itself 2GB of disk space, which it then exceeds. I have tried setting the 'workdir' parameter but that does not resolve it. I would be incredibly grateful for any assistance.

See script and error message copied below.

Kind regards,

Dr Sam Kleeman MD
PhD Student, Cold Spring Harbor Laboratory, NY

```
minigraph -xggs /mnt/grid/janowitz/rdata/balbc_assembly/final/cactus/GRCm39.genome.fa /mnt/grid/janowitz/rdata/balbc_assembly/final/B_assembly_NMSK.fasta > mouse.gfa

singularity exec -B /mnt/grid/:/mnt/grid/ cactus_v2.0.3.sif cactus-graphmap /mnt/grid/janowitz/rdata/balbc_assembly/final/cactus/mouse_align /mnt/grid/janowitz/rdata/balbc_assembly/final/cactus/fof.txt mouse.gfa mouse.paf --outputFasta mouse.gfa.fa --realTimeLogging --binariesMode local

singularity exec -B /mnt/grid/:/mnt/grid/ cactus_v2.0.3.sif cactus-align /mnt/grid/janowitz/rdata/balbc_assembly/final/cactus/mouse_align /mnt/grid/janowitz/rdata/balbc_assembly/final/cactus/fof.txt mouse.paf mouse.hal --pangenome --pafInput --realTimeLogging --outVG --reference c57bl6_grcm39 --binariesMode local  --workDir /mnt/grid/janowitz/rdata/tmp
```
```
	[2021-10-21T11:37:40-0400] [MainThread] [W] [toil.fileStores.abstractFileStore] LOG-TO-MASTER: Job used more disk than requested. For CWL, consider increasing the outdirMin requirement, otherwise, consider increasing the disk requirement. Job files/for-job/kind-JobFunctionWrappingJob/instance-13qvzvbl/cleanup/file-50a480d678e74700938377b99f7de9ca/stream used 613.23% disk (12.3 GiB [13169100288B] used, 2.0 GiB [2147483648B] requested).
	Traceback (most recent call last):
	  File "/usr/local/lib/python3.6/dist-packages/toil/worker.py", line 393, in workerScript
	    job._runner(jobGraph=None, jobStore=jobStore, fileStore=fileStore, defer=defer)
	  File "/usr/local/lib/python3.6/dist-packages/toil/job.py", line 2360, in _runner
	    returnValues = self._run(jobGraph=None, fileStore=fileStore)
	  File "/usr/local/lib/python3.6/dist-packages/toil/job.py", line 2281, in _run
	    return self.run(fileStore)
	  File "/usr/local/lib/python3.6/dist-packages/toil/job.py", line 2504, in run
	    rValue = userFunction(*((self,) + tuple(self._args)), **self._kwargs)
	  File "/usr/local/lib/python3.6/dist-packages/cactus/progressive/cactus_progressive.py", line 333, in exportHal
	    cactus_call(parameters=["halAppendCactusSubtree"] + args)
	  File "/usr/local/lib/python3.6/dist-packages/cactus/shared/common.py", line 866, in cactus_call
	    raise RuntimeError("Command {} exited {}: {}".format(call, process.returncode, out))
	RuntimeError: Command /usr/bin/time -v halAppendCactusSubtree tmphvx0xfl2.tmp tmpo0c_7i3b.tmp '(balbc_balbie:1.0,c57bl6_grcm39:1.0,_MINIGRAPH_:1.0)Anc0;' tmp_alignment.hal --inMemory exited 1: stdout=None, stderr=Warning: --inMemory is obsolete, use --hdf5InMemory
	Exception caught: expected a or s token, got '
	Command exited with non-zero status 1
		Command being timed: "halAppendCactusSubtree tmphvx0xfl2.tmp tmpo0c_7i3b.tmp (balbc_balbie:1.0,c57bl6_grcm39:1.0,_MINIGRAPH_:1.0)Anc0; tmp_alignment.hal --inMemory"
		User time (seconds): 81.64
		System time (seconds): 2.48
		Percent of CPU this job got: 99%
		Elapsed (wall clock) time (h:mm:ss or m:ss): 1:24.41
		Average shared text size (kbytes): 0
		Average unshared data size (kbytes): 0
		Average stack size (kbytes): 0
		Average total size (kbytes): 0
		Maximum resident set size (kbytes): 25608
		Average resident set size (kbytes): 0
		Major (requiring I/O) page faults: 0
		Minor (reclaiming a frame) page faults: 4335
		Voluntary context switches: 72
		Involuntary context switches: 71
		Swaps: 0
		File system inputs: 0
		File system outputs: 0
		Socket messages sent: 0
		Socket messages received: 0
		Signals delivered: 0
		Page size (bytes): 4096
		Exit status: 1
	
	[2021-10-21T11:37:40-0400] [MainThread] [E] [toil.worker] Exiting the worker because of a failed job on host bam28
<=========

```

**Comment by glennhickey** [comment]
I reproduced this error while debugging something else just now.  It seems to arise from empty sequence names in the input fasta, ex something like
```
>
AACC...
```
This code gets through the pipeline but `halAppendCactusSubtree` can't handle empty names. 

I haven't yet figure out what the root cause is, but my prime suspect so far is the Cactus preprocessor.

**Comment by YuJimlong** [comment]
Hi，
I reproduced this error when runing cactus pangenome pipeline 
```
minigraph -t 24 -xggs ASM129832v2.fna ASM159420v1.fna ASM171797v3.fna ASM62661v3.fna > Saureus.gfa
docker run --rm -it -v /home/***/exp0402:/data/exp0402 cactus:v2.0.5 cactus-graphmap /data/exp0402/jobstore /data/exp0402/seqfile.txt /data/exp0402/Saureus.gfa /data/exp0402/Saureus.paf --outputFasta /data/exp0402/Saureus.gfa.fa --realTimeLogging
docker run --rm -it -v /home/***/exp0402:/data/exp0402 cactus:v2.0.5 cactus-align /data/exp0402/jobstore /data/exp0402/seqfile.txt /data/exp0402/Saureus.paf /data/exp0402/Saureus.hal --defaultDisk 20 --defaultMemory 20 --pangenome --pafInput --realTimeLogging --outVG --reference ASM129832v2
```
the sequence name is
```
>NZ_CP014791.1 Staphylococcus aureus strain MCRF184 chromosome, complete genome
>NZ_CP019945.1 Staphylococcus aureus strain BA01611 chromosome, complete genome
>NZ_CP017094.1 Staphylococcus aureus strain 2148.C01 chromosome, complete genome
>……
```
after changed the sequence name into 
```
>ASM62661v3
>ASM129832v2
>ASM159420v1
>……
```
The code ran successfully
