### ISSUE TITLE
Running cactus-preprocess error on example data: tree line parsing error

### ISSUE THREAD

**Issue by lucky-syn** [ComparativeGenomicsToolkit/cactus#609]
Hi, I had a same issue as #236. 

On running the following:
cactus-preprocess ./jobstore evolverPrimates.txt seqfile.masked.txt  --realTimeLogging --logFile preprocess.log   --maxCores 28 --defaultCores 28 --defaultPreemptable --betaInertia 0 --maskFile primates.gfa --maskAction softmask --minLength 100000 --maskAlpha

I got the error message as following:
Traceback (most recent call last):
  File "env/cactus_env/cactus_env/bin/cactus-preprocess", line 8, in <module>
    sys.exit(main())
  File "env/cactus_env/cactus_env/lib/python3.8/site-packages/cactus/preprocessor/cactus_preprocessor.py", line 480, in main
    outSeqFile = SeqFile(options.outSeqFile)
  File "env/cactus_env/cactus_env/lib/python3.8/site-packages/cactus/progressive/seqFile.py", line 64, in __init__
    self.parseFile(path)
  File "env/cactus_env/cactus_env/lib/python3.8/site-packages/cactus/progressive/seqFile.py", line 103, in parseFile
    self.cleanTree()
  File "env/cactus_env/cactus_env/lib/python3.8/site-packages/cactus/progressive/seqFile.py", line 184, in cleanTree
    raise RuntimeError("At least two valid leaf genomes required in"
RuntimeError: At least two valid leaf genomes required in input tree

I had tested to change the tree to a binary tree, but there was the same error.  Please advise on what I'm doing wrong here.

Thank you

**Comment by glennhickey** [comment]
This sounds like a formatting error in your input NEWICK tree, as suggested in that issue.  Please double check it.

**Comment by lucky-syn** [comment]
Many thanks for your kind reply.  I have solved the problem by re-preparing the evolverPrimates.txt file.
