### ISSUE TITLE
cactus-graphmap-join fails combining

### ISSUE THREAD

**Issue by RenzoTale88** [ComparativeGenomicsToolkit/cactus#619]
Hello,
I've managed to follow the worklfow described [here](https://github.com/ComparativeGenomicsToolkit/cactus/blob/master/doc/pangenome.md) all the way to the very end of the generation of the alignment files. 
However, when I try to combine the resulting hal and vg files, I get the following error at the `vg validate` step:
```
[2021-12-12T14:32:49+0000] [Thread-1  ] [E] [toil.batchSystems.singleMachine] Got exit code 1 (indicating failure) from job _toil_worker JobFunctionWrappingJob file:/PATH/TO/Andrea/GraphGenomes/Graph_122021/jobstore kind-JobFunctionWrappingJob/instance-1hnnblyb.
[2021-12-12T14:32:49+0000] [MainThread] [W] [toil.leader] Job failed with exit value 1: 'JobFunctionWrappingJob' kind-JobFunctionWrappingJob/instance-1hnnblyb
Exit reason: None
[2021-12-12T14:32:49+0000] [MainThread] [W] [toil.leader] The job seems to have left a log file, indicating failure: 'JobFunctionWrappingJob' kind-JobFunctionWrappingJob/instance-1hnnblyb
[2021-12-12T14:32:49+0000] [MainThread] [W] [toil.leader] Log from job "kind-JobFunctionWrappingJob/instance-1hnnblyb" follows:
=========>
        [2021-12-12T13:59:08+0000] [MainThread] [I] [toil.worker] ---TOIL WORKER OUTPUT LOG---
        [2021-12-12T13:59:08+0000] [MainThread] [I] [toil] Running Toil version 5.4.0-87293d63fa6c76f03bed3adf93414ffee67bf9a7 on host node2i01.ecdf.ed.ac.uk.
        [2021-12-12T13:59:08+0000] [MainThread] [I] [toil.worker] Working on job 'JobFunctionWrappingJob' kind-JobFunctionWrappingJob/instance-1hnnblyb
        [2021-12-12T13:59:14+0000] [MainThread] [I] [toil.worker] Loaded body Job('JobFunctionWrappingJob' kind-JobFunctionWrappingJob/instance-1hnnblyb) from description 'JobFunctionWrappingJob' kind-JobFunctionWrappingJob/instance-1hnnblyb
        [2021-12-12T13:59:15+0000] [MainThread] [I] [cactus.shared.common] Running the command ['clip-vg', '/PATH/TO/Andrea/GraphGenomes/Graph_122021/tmp/f84a8257ab3d5ec2a2ad398c885f2cf4/000f/e2ac/tmpbbumu8hj/11.vg', '-f', '-u', '100000', '-e', 'ARS-UCD1_2', '-d', '_MINIGRAPH_']
        [2021-12-12T13:59:15+0000] [MainThread] [I] [toil-rt] 2021-12-12 13:59:15.031563: Running the command: "clip-vg /PATH/TO/Andrea/GraphGenomes/Graph_122021/tmp/f84a8257ab3d5ec2a2ad398c885f2cf4/000f/e2ac/tmpbbumu8hj/11.vg -f -u 100000 -e ARS-UCD1_2 -d _MINIGRAPH_"
        [2021-12-12T14:30:00+0000] [MainThread] [I] [toil-rt] 2021-12-12 14:30:00.241038: Successfully ran: "clip-vg /PATH/TO/Andrea/GraphGenomes/Graph_122021/tmp/f84a8257ab3d5ec2a2ad398c885f2cf4/000f/e2ac/tmpbbumu8hj/11.vg -f -u 100000 -e ARS-UCD1_2 -d _MINIGRAPH_" in 1845.1309 seconds
        [2021-12-12T14:30:00+0000] [MainThread] [I] [toil-rt] 2021-12-12 14:30:00.245077: Running the command: "vg ids -s /PATH/TO/Andrea/GraphGenomes/Graph_122021/tmp/f84a8257ab3d5ec2a2ad398c885f2cf4/000f/e2ac/tmpbbumu8hj/11.vg.clip"
        [2021-12-12T14:31:48+0000] [MainThread] [I] [toil-rt] 2021-12-12 14:31:48.161276: Successfully ran: "vg ids -s /PATH/TO/Andrea/GraphGenomes/Graph_122021/tmp/f84a8257ab3d5ec2a2ad398c885f2cf4/000f/e2ac/tmpbbumu8hj/11.vg.clip" in 107.8723 seconds
        [2021-12-12T14:31:48+0000] [MainThread] [I] [toil-rt] 2021-12-12 14:31:48.165734: Running the command: "vg validate /PATH/TO/Andrea/GraphGenomes/Graph_122021/tmp/f84a8257ab3d5ec2a2ad398c885f2cf4/000f/e2ac/tmpbbumu8hj/11.vg.out"
        [2021-12-12T14:32:48+0000] [MainThread] [W] [toil.fileStores.abstractFileStore] Failed job accessed files:
        [2021-12-12T14:32:48+0000] [MainThread] [W] [toil.fileStores.abstractFileStore] Downloaded file 'files/no-job/file-8d5d3f7a1e884b6c957c212444e9d345/11.vg' to path '/PATH/TO/Andrea/GraphGenomes/Graph_122021/tmp/f84a8257ab3d5ec2a2ad398c885f2cf4/000f/e2ac/tmpbbumu8hj/11.vg'
        Traceback (most recent call last):
          File "/PATH/TO/Andrea/cactus-bin-v2.0.4/venv/lib/python3.6/site-packages/toil/worker.py", line 393, in workerScript
            job._runner(jobGraph=None, jobStore=jobStore, fileStore=fileStore, defer=defer)
          File "/PATH/TO/Andrea/cactus-bin-v2.0.4/venv/lib/python3.6/site-packages/toil/job.py", line 2360, in _runner
            returnValues = self._run(jobGraph=None, fileStore=fileStore)
          File "/PATH/TO/Andrea/cactus-bin-v2.0.4/venv/lib/python3.6/site-packages/toil/job.py", line 2281, in _run
            return self.run(fileStore)
          File "/PATH/TO/Andrea/cactus-bin-v2.0.4/venv/lib/python3.6/site-packages/toil/job.py", line 2504, in run
            rValue = userFunction(*((self,) + tuple(self._args)), **self._kwargs)
          File "/PATH/TO/Andrea/cactus-bin-v2.0.4/venv/lib/python3.6/site-packages/cactus/refmap/cactus_graphmap_join.py", line 351, in clip_vg
            cactus_call(parameters=['vg', 'validate', out_path])
          File "/PATH/TO/Andrea/cactus-bin-v2.0.4/venv/lib/python3.6/site-packages/cactus/shared/common.py", line 866, in cactus_call
            raise RuntimeError("Command {} exited {}: {}".format(call, process.returncode, out))
        RuntimeError: Command ['vg', 'validate', '/PATH/TO/Andrea/GraphGenomes/Graph_122021/tmp/f84a8257ab3d5ec2a2ad398c885f2cf4/000f/e2ac/tmpbbumu8hj/11.vg.out'] exited 1: stdout=None, stderr=graph invalid: missing edge between 158th step (994254:1) and 159th step (994254:0) of path genome1.seq1
        graph invalid: missing edge between 159th step (994254:1) and 158th step (994254:1) of path genome1.seq1
        graph: invalid

        [2021-12-12T14:32:48+0000] [MainThread] [E] [toil.worker] Exiting the worker because of a failed job on host node2i01.ecdf.ed.ac.uk
<=========
[2021-12-12T14:32:49+0000] [MainThread] [W] [toil.job] Due to failure we are reducing the remaining try count of job 'JobFunctionWrappingJob' kind-JobFunctionWrappingJob/instance-1hnnblyb with ID ki
```
Not sure if it is a bug or what. When I try to run the `vg validate` command in the input vg file I get that the vg file is valid.

**Comment by glennhickey** [comment]
I haven't seen this error before.  Are you able to share your input (it looks like 11.vg?) by any chance?

**Comment by RenzoTale88** [comment]
@glennhickey I've posted this in the wrong issue, apologies for this. I'm currently re-running the whole workflow, which should complete by tomorrow. If I come across the same error again I'll arrange the file transfer. Thanks again for the quick response anyway!

**Comment by RenzoTale88** [comment]
Hi @glennhickey I've got the file ready to share. Do you have an email I can use to share the link to the VG file with you?
Than you again!
Andrea

**Comment by glennhickey** [comment]
Sure, it's my github user name at gmail. Thanks!

**Comment by RenzoTale88** [comment]
Ok great thanks! Although, I might have figured out the issue (the reference fasta names were not in the format genome.sequence), so it might be causing this problem. I'll have a run this way and check whether this will sort the issue out or not. If not, I'll arrange the data transfer. Thanks again! :)

**Comment by glennhickey** [comment]
Thanks for sharing the data.  There was a bug in `clip-vg` where, when it was trying to forwardize your reference paths, it wasn't handling a reversing self-loop in another paths.  This will be fixed in the next release.  You can patch your cactus installation by:
```
wget https://github.com/ComparativeGenomicsToolkit/hal2vg/releases/download/v1.0.16/clip-vg
chmod u+x clip-vg
cp clip-vg <your cactus dir>/bin
```

**Comment by RenzoTale88** [comment]
Thank you very much, the job finished successfully!

One more question: when I run the command `vg paths` on the resulting gbwt/gg pairs to see the path as follow:
```vg paths -L -x PANGENOME/final/pangenome_15asm.xg -g PANGENOME/final/pangenome_15asm.gbwt```

I see no path with the `_gbwt_ref` naming, which in turn causes the conversion to `.pg` format to rise the warning below:
```
vg convert PANGENOME/final/pangenome_15asm.gg -b PANGENOME/final/pangenome_15asm.gbwt -p -t 4 > PANGENOME/final/pangenome_15asm.pg
warning [vg convert]: no threads for reference sample _gbwt_ref in the GBWT index
```

Do you think this will affect any downstream analyses?

Thank you again!
