### ISSUE TITLE
AssertionError in checkForDeadlocks: assert len(runningServiceJobs) <= totalRunningJobs

### ISSUE THREAD

**Issue by lparsons** [ComparativeGenomicsToolkit/cactus#62]
When running cactus using Slurm, I ran into an exception `AssertionError` thrown by Toil:
```
File "/Genomics/grid/users/lparsons/miniconda3/envs/cactus/lib/python2.7/site-packages/toil/leader.py", line 524, in checkForDeadlocks
    assert len(runningServiceJobs) <= totalRunningJobs
```
I'm not sure if this is actually a problem with Toil and Slurm or if there is something going on with how cactus is using Toil. I'm adding this issue here to track it in case anyone else has a similar problem. Will update if I find new details.

```
Traceback (most recent call last):
  File "/Genomics/grid/users/lparsons/miniconda3/envs/cactus/bin/cactus", line 10, in <module>
    sys.exit(main())
  File "/Genomics/grid/users/lparsons/miniconda3/envs/cactus/lib/python2.7/site-packages/cactus/progressive/cactus_progressive.py", line 477, in main                                                                                                                             
    halID = toil.restart()
  File "/Genomics/grid/users/lparsons/miniconda3/envs/cactus/lib/python2.7/site-packages/toil/common.py", line 773, in restart
    return self._runMainLoop(rootJobGraph)
  File "/Genomics/grid/users/lparsons/miniconda3/envs/cactus/lib/python2.7/site-packages/toil/common.py", line 1018, in _runMainLoop
    jobCache=self._jobCache).run()
  File "/Genomics/grid/users/lparsons/miniconda3/envs/cactus/lib/python2.7/site-packages/toil/leader.py", line 197, in run
    self.innerLoop()
  File "/Genomics/grid/users/lparsons/miniconda3/envs/cactus/lib/python2.7/site-packages/toil/leader.py", line 501, in innerLoop
    self.checkForDeadlocks()
  File "/Genomics/grid/users/lparsons/miniconda3/envs/cactus/lib/python2.7/site-packages/toil/leader.py", line 524, in checkForDeadlocks
    assert len(runningServiceJobs) <= totalRunningJobs
AssertionError
```

**Comment by lparsons** [comment]
I believe this error was occurring due to problems we had with `sacct` and SLURM, which I have now worked around. See #67 .
