### ISSUE TITLE
cactus_consolidated failed in cactus-align

### ISSUE THREAD

**Issue by lucky-syn** [ComparativeGenomicsToolkit/cactus#631]
Hi, I am running cactus-align and getting fails.

On running the following:
#SBATCH  --mem 3000GB
cactus-align ./jobstore 251sample.path sample251.paf  sample251.hal  --pangenome --pafInput --realTimeLogging --outVG --reference ref --maxCores 30 --defaultCores 30 --restart --maxDisk 3000000000000  --workDir ./tmp/

I got the error message as following:
......
[2021-12-30T22:29:04+0800] [MainThread] [I] [toil-rt] cactus_consolidated(Anc0): Ran cactus caf, 169814 seconds have elapsed
[2021-12-30T23:36:13+0800] [MainThread] [I] [toil-rt] cactus_consolidated(Anc0): Ran extended flowers ready for bar, 173843 seconds have elapsed
......
[2022-01-04T15:20:30+0800] [MainThread] [I] [toil.leader] 1 jobs are running, 0 jobs are issued and waiting to run
[2022-01-04T15:29:52+0800] [MainThread] [I] [toil-rt] cactus_consolidated(Anc0): [SIMDMalloc] mm_Malloc fail!
[2022-01-04T15:29:52+0800] [MainThread] [I] [toil-rt] cactus_consolidated(Anc0): Size: 8589934592
[2022-01-04T15:36:12+0800] [Thread-1  ] [E] [toil.batchSystems.singleMachine] Got exit code 1 (indicating failure) from job _toil_worker CactusConsolidated file:/jobstore kind-CactusConsolidated/instance-9pbjy3he.
[2022-01-04T15:36:12+0800] [MainThread] [W] [toil.leader] Job failed with exit value 1: 'CactusConsolidated' kind-CactusConsolidated/instance-9pbjy3he
Exit reason: None
[2022-01-04T15:36:12+0800] [MainThread] [W] [toil.leader] The job seems to have left a log file, indicating failure: 'CactusConsolidated' kind-CactusConsolidated/instance-9pbjy3he
[2022-01-04T15:36:12+0800] [MainThread] [W] [toil.leader] Log from job "kind-CactusConsolidated/instance-9pbjy3he" follows:
=========>
        929b69c853f84c0e8c20d4894827c04f/tmps_2ucla3.tmp.fa' to path 'tmp73_h5i9_.tmp'
        [2022-01-04T15:36:04+0800] [MainThread] [W] [toil.fileStores.abstractFileStore] Downloaded file 'tmpj9zw9gq1.tmp.fa' to path 'tmpd2wehpgf.tmp'
      ......
              Traceback (most recent call last):
          File "/env1/cactus_env/lib/python3.8/site-packages/toil/worker.py", line 393, in workerScript
            job._runner(jobGraph=None, jobStore=jobStore, fileStore=fileStore, defer=defer)
          File "/env1/cactus_env/lib/python3.8/site-packages/cactus/shared/common.py", line 932, in _runner
            super(RoundedJob, self)._runner(*args, jobStore=jobStore,
          File "/env1/cactus_env/lib/python3.8/site-packages/toil/job.py", line 2360, in _runner
            returnValues = self._run(jobGraph=None, fileStore=fileStore)
          File "/env1/cactus_env/lib/python3.8/site-packages/toil/job.py", line 2281, in _run
            return self.run(fileStore)
          File "/env1/cactus_env/lib/python3.8/site-packages/cactus/pipeline/cactus_workflow.py", line 408, in run
            messages = runCactusConsolidated(seqMap=seqMap,
          File "/env1/cactus_env/lib/python3.8/site-packages/cactus/shared/common.py", line 197, in runCactusConsolidated
            masterMessages = cactus_call(check_output=True, returnStdErr=True, 
                                            realtimeStderrPrefix='cactus_consolidated({})'.format(referenceEvent),
          File "/env1/cactus_env/lib/python3.8/site-packages/cactus/shared/common.py", line 866, in cactus_call
            raise RuntimeError("Command {} exited {}: {}".format(call, process.returncode, out))       
        Attaching the sequence to the cactus root 855149, header Chr2 with length 3593725 and 525078 total bases aligned and 1500 bases aligned to other chromosome threads
        Attaching the sequence to the cactus root 855161, header Chr4 with length 3550269 and 412312 total bases aligned and 3555 bases aligned to other chromosome threads
        .......
        RuntimeError: Command ['cactus_consolidated', '--sequences', 'sample1 sample1.fa ....', '--outputFile', 'tmp40eum61v.tmp', '--outputHalFastaFile', 'tmp7c_kh_hv.tmp', '--outputReferenceFile', 'z4w4m.tmp', '--referenceEvent', 'Anc0', '--threads', '30'] exited 1: stdout=Attaching the sequence to the cactus root 602033, header sample100_ctg1 with length 44436328 and 5908443 total bases aligned and 0 bases aligned to other chromosome threads
        [2022-01-04T15:36:05+0800] [MainThread] [E] [toil.worker] Exiting the worker because of a failed job on host smp5
<=========

According to the above information, I guessed which error was caused by lacking memory (8589934592 memory should be setted) . Please advise on what I'm doing wrong here.

Thank you

**Comment by glennhickey** [comment]
Yeah, it looks like it's running out of memory.  How much memory to you have available?  How big are your input sequences?

**Comment by lucky-syn** [comment]
Thanks for you reply.  I had set 3T memory for cactus-align and the input sequences were 91Gb (including 250 genomes).

**Comment by glennhickey** [comment]
Hmm.  For reference, the biggest dataset I've run on is 22Gb (90 human chr1s with centromeres removed), and that took about 200G memory. 

Memory is going to be proportional to sequence size (so I'd expect 91Gb of equivalent human data to be about 800G), but also genome divergence.  I'm guessing there's more variation in your set that's pushing the memory way up.  All I could suggest would be to try a smaller set, or split by chromosome if possible.
