### ISSUE TITLE
cPecanLastz RuntimeError SIGSEGV

### ISSUE THREAD

**Issue by mdpllard** [ComparativeGenomicsToolkit/cactus#641]
Hello,

After running cactus-prepare and getting through the first round of alignment (round 0), I am having trouble running at least one of the cactus-blast commands in the next round (round 1).

I'm getting several errors like this:
```
[2022-01-19T09:18:40-0600] [Thread-1  ] [E] [toil.batchSystems.singleMachine] Got exit code 1 (indicating failure) from job _toil_worker RunBlast file:/home/mdpllard/Cactus/Chapter2/jobstore_1/30 kind-RunBlast/b/instance-63seeu9j.
[2022-01-19T09:18:40-0600] [MainThread] [W] [toil.leader] Job failed with exit value 1: 'RunBlast' kind-RunBlast/b/instance-63seeu9j
Exit reason: None
[2022-01-19T09:18:40-0600] [MainThread] [W] [toil.leader] The job seems to have left a log file, indicating failure: 'RunBlast' kind-RunBlast/b/instance-63seeu9j
[2022-01-19T09:18:40-0600] [MainThread] [W] [toil.leader] Log from job "kind-RunBlast/b/instance-63seeu9j" follows:
=========>
        [2022-01-19T09:15:48-0600] [MainThread] [I] [toil.worker] ---TOIL WORKER OUTPUT LOG---
        [2022-01-19T09:15:48-0600] [MainThread] [I] [toil] Running Toil version 5.4.0-87293d63fa6c76f03bed3adf93414ffee67bf9a7 on host b001.
        [2022-01-19T09:15:48-0600] [MainThread] [I] [toil.worker] Working on job 'RunBlast' kind-RunBlast/b/instance-63seeu9j
        [2022-01-19T09:15:49-0600] [MainThread] [I] [toil.worker] Loaded body Job('RunBlast' kind-RunBlast/b/instance-63seeu9j) from description 'RunBlast' kind-RunBlast/b/instance-63seeu9j
        [2022-01-19T09:15:50-0600] [MainThread] [I] [cactus.shared.common] Running the command ['cPecanLastz', '/home/mdpllard/Cactus/Chapter2/workdir_tmp/0198c3d421b052e7ba685cdcd6b2ae54/7105/0882/tmpqwzqpk5t.tmp[multiple][nameparse=darkspace]', '/home/mdpllard/Cactus/Chapter2/workdir_tmp/0198c3d421b052e7ba685cdcd6b2ae54/7105/0882/tmpzuf6oh72.tmp[nameparse=darkspace]', '--format=cigar', '--notrivial', '--step=1', '--ambiguous=iupac,100,100', '--ydrop=3000']
        [2022-01-19T09:15:50-0600] [MainThread] [I] [toil-rt] 2022-01-19 09:15:50.022164: Running the command: "cPecanLastz /home/mdpllard/Cactus/Chapter2/workdir_tmp/0198c3d421b052e7ba685cdcd6b2ae54/7105/0882/tmpqwzqpk5t.tmp[multiple][nameparse=darkspace] /home/mdpllard/Cactus/Chapter2/workdir_tmp/0198c3d421b052e7ba685cdcd6b2ae54/7105/0882/tmpzuf6oh72.tmp[nameparse=darkspace] --format=cigar --notrivial --step=1 --ambiguous=iupac,100,100 --ydrop=3000"
        [2022-01-19T09:18:39-0600] [MainThread] [W] [toil.fileStores.abstractFileStore] Failed job accessed files:
        [2022-01-19T09:18:39-0600] [MainThread] [W] [toil.fileStores.abstractFileStore] Downloaded file 'files/for-job/kind-BlastSequencesAllAgainstAll/instance-saul1zoq/cleanup/file-0171f58122c9421b81fd7cee9e7b2095/85' to path '/home/mdpllard/Cactus/Chapter2/workdir_tmp/0198c3d421b052e7ba685cdcd6b2ae54/7105/0882/tmpqwzqpk5t.tmp'
        [2022-01-19T09:18:39-0600] [MainThread] [W] [toil.fileStores.abstractFileStore] Downloaded file 'files/for-job/kind-BlastSequencesAllAgainstAll/instance-saul1zoq/cleanup/file-a231bf6a388041f18c777fb373965321/92' to path '/home/mdpllard/Cactus/Chapter2/workdir_tmp/0198c3d421b052e7ba685cdcd6b2ae54/7105/0882/tmpzuf6oh72.tmp'
        Traceback (most recent call last):
          File "/home/mdpllard/.local/lib/python3.7/site-packages/toil/worker.py", line 393, in workerScript
            job._runner(jobGraph=None, jobStore=jobStore, fileStore=fileStore, defer=defer)
          File "/home/mdpllard/.local/lib/python3.7/site-packages/cactus/shared/common.py", line 933, in _runner
            fileStore=fileStore, **kwargs)
          File "/home/mdpllard/.local/lib/python3.7/site-packages/toil/job.py", line 2360, in _runner
            returnValues = self._run(jobGraph=None, fileStore=fileStore)
          File "/home/mdpllard/.local/lib/python3.7/site-packages/toil/job.py", line 2281, in _run
            return self.run(fileStore)
          File "/home/mdpllard/.local/lib/python3.7/site-packages/cactus/blast/blast.py", line 462, in run
            gpuLastz = self.blastOptions.gpuLastz)
          File "/home/mdpllard/.local/lib/python3.7/site-packages/cactus/shared/common.py", line 324, in runLastz
            parameters=[lastzCommand, seq1, seq2, "--format=cigar", "--notrivial"] + lastzArguments.split())
          File "/home/mdpllard/.local/lib/python3.7/site-packages/cactus/shared/common.py", line 868, in cactus_call
            raise RuntimeError("Command {} signaled {}: {}".format(call, signal.Signals(-process.returncode).name, out))
        RuntimeError: Command ['cPecanLastz', '/home/mdpllard/Cactus/Chapter2/workdir_tmp/0198c3d421b052e7ba685cdcd6b2ae54/7105/0882/tmpqwzqpk5t.tmp[multiple][nameparse=darkspace]', '/home/mdpllard/Cactus/Chapter2/workdir_tmp/0198c3d421b052e7ba685cdcd6b2ae54/7105/0882/tmpzuf6oh72.tmp[nameparse=darkspace]', '--format=cigar', '--notrivial', '--step=1', '--ambiguous=iupac,100,100', '--ydrop=3000'] signaled SIGSEGV: stdout=None, stderr=
```

And occasionally this error:
```
[2022-01-19T03:23:21-0600] [Thread-1  ] [E] [toil.batchSystems.singleMachine] Got exit code 1 (indicating failure) from job _toil_worker RunSelfBlast file:/home/mdpllard/Cactus/Chapter2/jobstore_1/30 kind-RunSelfBlast/instance-xn_3dpys.
[2022-01-19T03:23:21-0600] [MainThread] [W] [toil.leader] Job failed with exit value 1: 'RunSelfBlast' kind-RunSelfBlast/instance-xn_3dpys
Exit reason: None
[2022-01-19T03:23:21-0600] [MainThread] [W] [toil.leader] The job seems to have left a log file, indicating failure: 'RunSelfBlast' kind-RunSelfBlast/instance-xn_3dpys
[2022-01-19T03:23:21-0600] [MainThread] [W] [toil.leader] Log from job "kind-RunSelfBlast/instance-xn_3dpys" follows:
=========>
        [2022-01-19T03:22:21-0600] [MainThread] [I] [toil.worker] ---TOIL WORKER OUTPUT LOG---
        [2022-01-19T03:22:21-0600] [MainThread] [I] [toil] Running Toil version 5.4.0-87293d63fa6c76f03bed3adf93414ffee67bf9a7 on host b001.
        [2022-01-19T03:22:21-0600] [MainThread] [I] [toil.worker] Working on job 'RunSelfBlast' kind-RunSelfBlast/instance-xn_3dpys
        [2022-01-19T03:22:24-0600] [MainThread] [I] [toil.worker] Loaded body Job('RunSelfBlast' kind-RunSelfBlast/instance-xn_3dpys) from description 'RunSelfBlast' kind-RunSelfBlast/instance-xn_3dpys
        [2022-01-19T03:22:24-0600] [MainThread] [I] [cactus.shared.common] Running the command ['cPecanLastz', '/home/mdpllard/Cactus/Chapter2/workdir_tmp/0198c3d421b052e7ba685cdcd6b2ae54/5db7/8f8c/tmpbjivbrzl.tmp[multiple][nameparse=darkspace]', '/home/mdpllard/Cactus/Chapter2/workdir_tmp/0198c3d421b052e7ba685cdcd6b2ae54/5db7/8f8c/tmpbjivbrzl.tmp[nameparse=darkspace]', '--format=cigar', '--notrivial', '--step=1', '--ambiguous=iupac,100,100', '--ydrop=3000']
        [2022-01-19T03:22:24-0600] [MainThread] [I] [toil-rt] 2022-01-19 03:22:24.235920: Running the command: "cPecanLastz /home/mdpllard/Cactus/Chapter2/workdir_tmp/0198c3d421b052e7ba685cdcd6b2ae54/5db7/8f8c/tmpbjivbrzl.tmp[multiple][nameparse=darkspace] /home/mdpllard/Cactus/Chapter2/workdir_tmp/0198c3d421b052e7ba685cdcd6b2ae54/5db7/8f8c/tmpbjivbrzl.tmp[nameparse=darkspace] --format=cigar --notrivial --step=1 --ambiguous=iupac,100,100 --ydrop=3000"
        [2022-01-19T03:23:21-0600] [MainThread] [W] [toil.fileStores.abstractFileStore] Failed job accessed files:
        [2022-01-19T03:23:21-0600] [MainThread] [W] [toil.fileStores.abstractFileStore] Downloaded file 'files/for-job/kind-BlastSequencesAllAgainstAll/instance-saul1zoq/cleanup/file-b96408faeafb4023884762ec28691605/88' to path '/home/mdpllard/Cactus/Chapter2/workdir_tmp/0198c3d421b052e7ba685cdcd6b2ae54/5db7/8f8c/tmpbjivbrzl.tmp'
        Traceback (most recent call last):
          File "/home/mdpllard/.local/lib/python3.7/site-packages/toil/worker.py", line 393, in workerScript
            job._runner(jobGraph=None, jobStore=jobStore, fileStore=fileStore, defer=defer)
          File "/home/mdpllard/.local/lib/python3.7/site-packages/cactus/shared/common.py", line 933, in _runner
            fileStore=fileStore, **kwargs)
          File "/home/mdpllard/.local/lib/python3.7/site-packages/toil/job.py", line 2360, in _runner
            returnValues = self._run(jobGraph=None, fileStore=fileStore)
          File "/home/mdpllard/.local/lib/python3.7/site-packages/toil/job.py", line 2281, in _run
            return self.run(fileStore)
          File "/home/mdpllard/.local/lib/python3.7/site-packages/cactus/blast/blast.py", line 416, in run
            gpuLastz = self.blastOptions.gpuLastz)
          File "/home/mdpllard/.local/lib/python3.7/site-packages/cactus/shared/common.py", line 327, in runSelfLastz
            return runLastz(seq, seq, alignmentsFile, lastzArguments, work_dir, gpuLastz)
          File "/home/mdpllard/.local/lib/python3.7/site-packages/cactus/shared/common.py", line 324, in runLastz
            parameters=[lastzCommand, seq1, seq2, "--format=cigar", "--notrivial"] + lastzArguments.split())
          File "/home/mdpllard/.local/lib/python3.7/site-packages/cactus/shared/common.py", line 866, in cactus_call
            raise RuntimeError("Command {} exited {}: {}".format(call, process.returncode, out))
        RuntimeError: Command ['cPecanLastz', '/home/mdpllard/Cactus/Chapter2/workdir_tmp/0198c3d421b052e7ba685cdcd6b2ae54/5db7/8f8c/tmpbjivbrzl.tmp[multiple][nameparse=darkspace]', '/home/mdpllard/Cactus/Chapter2/workdir_tmp/0198c3d421b052e7ba685cdcd6b2ae54/5db7/8f8c/tmpbjivbrzl.tmp[nameparse=darkspace]', '--format=cigar', '--notrivial', '--step=1', '--ambiguous=iupac,100,100', '--ydrop=3000'] exited 1: stdout=None, stderr=FAILURE: (in ydrop_one_sided_align:3547, dq-dynProg->p==9774, dynProg->len=1106)
```

As I mentioned, I am only getting this problem with some of my cactus-blast commands. Others in the same round seem to run with no issue. Could somebody explain to me what is going wrong and how I can fix the issue?

Thanks very much for any help you can provide,
Matthew

**Comment by glennhickey** [comment]
I've never seen anything like these errors.  My only guess would be running out of memory.  If you can share your input, I will take a look here.  If it's too big, you can also rerun with `--cleanWorkDir never` then just send me the two files and command line that are crashing, ex

```
/home/mdpllard/Cactus/Chapter2/workdir_tmp/0198c3d421b052e7ba685cdcd6b2ae54/7105/0882/tmpqwzqpk5t.tmp
/home/mdpllard/Cactus/Chapter2/workdir_tmp/0198c3d421b052e7ba685cdcd6b2ae54/7105/0882/tmpzuf6oh72.tmp

['cPecanLastz', '/home/mdpllard/Cactus/Chapter2/workdir_tmp/0198c3d421b052e7ba685cdcd6b2ae54/7105/0882/tmpqwzqpk5t.tmp[multiple][nameparse=darkspace]', '/home/mdpllard/Cactus/Chapter2/workdir_tmp/0198c3d421b052e7ba685cdcd6b2ae54/7105/0882/tmpzuf6oh72.tmp[nameparse=darkspace]', '--format=cigar', '--notrivial', '--step=1', '--ambiguous=iupac,100,100', '--ydrop=3000']
```
(Those files will be kept around after running with the `--cleanWorkDir never` option)

**Comment by mdpllard** [comment]
Hi Glenn,

Thanks so much for looking into this for me.

The cactus-blast command that has been failing is:
`cactus-blast jobstore_1/30 steps-output_1/carnivora_outSeqFile.txt steps-output_1/Anc12.cigar --root Anc12 --realTimeLogging --logInfo --retryCount 10 --maxCores 40 --maxMemory 250Gi --workDir workdir_tmp`

The seqFile (carnivora_outputSeqFile.txt) contains this:
```
(((Vulpes_vulpes:6.681489035,((Chrysocyon_brachyurus:3.783475875,Canis_lupus:3.783475391)Anc11:2.232503637,Nyctereutes_procyonoides:6.015979302)Anc07:0.6655095241)Anc03:17.59759613,(((Mirounga_angustirostris:10.90392942,(Odobenus_rosmarus:6.606732192,Zalophus_californianus:6.60673236)Anc17:4.297196385)Anc12:8.304206066,(Spilogale_gracilis:17.27815913,(((Potos_flavus:13.46121335,((Procyon_lotor:3.755739584,Bassariscus_sumichrasti:3.755739375)Anc25:6.102399902,Nasua_narica:9.858139066)Anc23:3.60307344)Anc21:2.465115632,(Martes_foina:8.035466082,(Mustela_putorius:7.2858075,(Lutra_lutra:2.892663988,Aonyx_cinereus:2.892663988)Anc26:4.393143574)Anc24:0.7496590018)Anc22:7.890861216)Anc20:0.7859385403,Ailurus_fulgens:16.71226584)Anc18:0.565892867)Anc13:1.9299772)Anc08:1.190732575,(((Ursus_maritimus:1.577712637,Ursus_americanus:1.577712448)Anc19:0.2260325685,Helarctos_malayanus:1.803744996)Anc14:4.38906621,Ailuropoda_melanoleuca:6.192811837)Anc09:14.20605769)Anc04:3.880215635)Anc01:4.321233928,((((Hyaena_hyaena:3.029818393,Crocuta_crocuta:3.029817131)Anc15:8.307787316,(Cryptoprocta_ferox:9.772298384,Suricata_suricatta:9.772299225)Anc16:1.565306482)Anc10:2.557581141,Paradoxurus_hermaphroditus:13.89518622)Anc05:0.7610831405,(Panthera_pardus:4.633796333,Felis_catus:4.633796397)Anc06:10.02247422)Anc02:13.94404721)Anc00;
Vulpes_vulpes	steps-output_1/Vulpes_vulpes_HiC.fasta.masked
Chrysocyon_brachyurus	steps-output_1/Chrysocyon_brachyurus_HiC.fasta.masked
*Canis_lupus	steps-output_1/CanFam3.1.fna.masked
Nyctereutes_procyonoides	steps-output_1/Nyctereutes_procyonoides.fna.masked
Mirounga_angustirostris	steps-output_1/Mirounga_angustirostris_HiC.fasta.masked
Odobenus_rosmarus	steps-output_1/Odobenus_rosmarus_HiC.fasta.masked
Zalophus_californianus	steps-output_1/Zalophus_californianus.fna.masked
Spilogale_gracilis	steps-output_1/Spilogale_gracilis.fna.masked
Potos_flavus	steps-output_1/Potos_flavus_HiC.fasta.masked
Procyon_lotor	steps-output_1/Procyon_lotor_HiC.fasta.masked
Bassariscus_sumichrasti	steps-output_1/Bassariscus_sumichrasti_HiC.fasta.masked
Nasua_narica	steps-output_1/Nasua_narica_HiC.fasta.masked
Martes_foina	steps-output_1/Martes_foina_HiC.fasta.masked
Mustela_putorius	steps-output_1/Mustela_putorius_HiC.fasta.masked
*Lutra_lutra	steps-output_1/Lutra_lutra_HiC.fasta.masked
Aonyx_cinereus	steps-output_1/Aonyx_cinereus_HiC.fasta.masked
Ailurus_fulgens	steps-output_1/Ailurus_fulgens_HiC.fasta.masked
Ursus_maritimus	steps-output_1/Ursus_maritimus_UrsMar_1.0_HiC.fasta.masked
Ursus_americanus	steps-output_1/Ursus_americanus_ASM334442v1_HiC.fasta.masked
Helarctos_malayanus	steps-output_1/Ursus_malayanus_HiC.fasta.masked
Ailuropoda_melanoleuca	steps-output_1/Ailuropoda_melanoleuca.fna.masked
Hyaena_hyaena	steps-output_1/Hyaena_hyaena.fna.masked
Crocuta_crocuta	steps-output_1/Crocuta_crocuta_HiC.fasta.masked
Cryptoprocta_ferox	steps-output_1/Cryptoprocta_ferox_HiC.fasta.masked
Suricata_suricatta	steps-output_1/Suricata_suricatta_HiC.fasta.masked
Paradoxurus_hermaphroditus	steps-output_1/Paradoxurus_hermaphroditus.fna.masked
Panthera_pardus	steps-output_1/Panthera_pardus_HiC.fasta.masked
*Felis_catus	steps-output_1/Felis_catus_9.0.fna.masked
Anc00	steps-output_1/Anc00.fa
Anc01	steps-output_1/Anc01.fa
Anc02	steps-output_1/Anc02.fa
Anc03	steps-output_1/Anc03.fa
Anc04	steps-output_1/Anc04.fa
Anc05	steps-output_1/Anc05.fa
Anc06	steps-output_1/Anc06.fa
Anc07	steps-output_1/Anc07.fa
Anc08	steps-output_1/Anc08.fa
Anc09	steps-output_1/Anc09.fa
Anc10	steps-output_1/Anc10.fa
Anc11	steps-output_1/Anc11.fa
Anc12	steps-output_1/Anc12.fa
Anc13	steps-output_1/Anc13.fa
Anc14	steps-output_1/Anc14.fa
Anc15	steps-output_1/Anc15.fa
Anc16	steps-output_1/Anc16.fa
Anc17	steps-output_1/Anc17.fa
Anc18	steps-output_1/Anc18.fa
Anc19	steps-output_1/Anc19.fa
Anc20	steps-output_1/Anc20.fa
Anc21	steps-output_1/Anc21.fa
Anc22	steps-output_1/Anc22.fa
Anc23	steps-output_1/Anc23.fa
Anc24	steps-output_1/Anc24.fa
Anc25	steps-output_1/Anc25.fa
Anc26	steps-output_1/Anc26.fa
```

I'll send you a link to the genomes used by this failing command in an email to the address you specify in your GitHub profile. If these were not the inputs you were thinking of, I apologize. When I get a chance, I will rerun with `--cleanWorkDir never`.

Additionally, from looking at other issues posted here, I noticed that my branch lengths are not in the correct units, so are too long. Could this contribute to the failure? If so, is it possible to change the branch lengths (while keeping the same topology) midway through the cactus pipeline (i.e., here at round 1), or would I have to start from the beginning?

Thanks again,
Matthew

**Comment by glennhickey** [comment]
I don't think the branch lengths are related to this error.  I'm running the same command locally, and have seen a few errors but they seem to be succesfully retrying.  Did your `cactus-blast` command completely fail with an error?  Anyway, I'll let mine run to completion to see what happens.

**Comment by mdpllard** [comment]
I ran the command previously and it completely failed. However, that was on a node that has failed to run cactus in the past (I have had issued with `cactus-align` on this node, but never `cactus-blast` until now). I am currently running it on a different node on the HPC and am having the same issue as before. It is still running so not completely failed, but I am noticing some jobs are repeatedly failing each time they are retried.

Unfortunately, it takes a while to run large jobs like cactus on my HPC due to sharing of the resources. Once my current run of the failing `cactus-blast` command finishes, I can attempt to run it again using `--cleanWorkDir never` as you previously recommended, then send you those trouble files.

Hopefully your run completes with no issues and reveals why I am having trouble!

Thank again.

**Comment by mdpllard** [comment]
A follow-up to my previous comment: the `cactus-blast` command completely failed. I copied the end of the log file and have attached it [here](https://github.com/ComparativeGenomicsToolkit/cactus/files/7926731/cactus-blast_final_error_log.txt) in case it would be useful. I'm still working on running it with `--cleanWorkDir never`. So far, none of the other `cactus-blast` commands in this round have had any issues.

**Comment by mdpllard** [comment]
Another update: I used `--restart` and `--cleanWorkDir never` on the failed `cactus-blast` command so that I could get input files from one of the failing `cPecanLastz` jobs.

Here are the files (as .txt because GitHub does not support sharing .tmp):
[tmprlvjs7d8.txt](https://github.com/ComparativeGenomicsToolkit/cactus/files/7929142/tmprlvjs7d8.txt)
[tmp3hx3ut4r.txt](https://github.com/ComparativeGenomicsToolkit/cactus/files/7929143/tmp3hx3ut4r.txt)

The failed command to go with the files is:
```
['cPecanLastz', '/home/mdpllard/Cactus/Chapter2/workdir_tmp/0198c3d421b052e7ba685cdcd6b2ae54/30b0/f363/tmprlvjs7d8.tmp[multiple][nameparse=darkspace]', '/home/mdpllard/Cactus/Chapter2/workdir_tmp/0198c3d421b052e7ba685cdcd6b2ae54/30b0/f363/tmp3hx3ut4r.tmp[nameparse=darkspace]', '--format=cigar', '--notrivial', '--step=1', '--ambiguous=iupac,100,100', '--ydrop=3000']
```

I hope this is useful! Thanks again.

**Comment by glennhickey** [comment]
The example you posted [above](https://github.com/ComparativeGenomicsToolkit/cactus/issues/641#issuecomment-1020599920) is fixed in the [latest release](https://github.com/ComparativeGenomicsToolkit/cactus/releases/tag/v2.0.5) -- hopefully it'll work for the whole dataset too.

**Comment by mdpllard** [comment]
Update: The latest release fixed the RuntimeError I was having with cPecanLastz. However, when `cactus-blast` gets to running this command:
```
bash -c set -eo pipefail && cat /home/mdpllard/Cactus/Chapter2/workdir_tmp/1ee5a79304205c08864052e8153db38d/f906/34e2/tmpj4t59yd9.tmp | cactus_mirrorAndOrientAlignments INFO | sort -T/home/mdpllard/Cactus/Chapter2/workdir_tmp/1ee5a79304205c08864052e8153db38d/f906/34e2/tmpybdab8t2 -k6,6 -k7,7n -k8,8n | uniq | cactus_splitAlignmentOverlaps INFO | cactus_calculateMappingQualities INFO 5 0.0 0.001 /home/mdpllard/Cactus/Chapter2/workdir_tmp/1ee5a79304205c08864052e8153db38d/f906/34e2/tmp1itzhb_7.tmp /home/mdpllard/Cactus/Chapter2/workdir_tmp/1ee5a79304205c08864052e8153db38d/f906/34e2/tmpgi02jlmw.tmp /home/mdpllard/Cactus/Chapter2/workdir_tmp/1ee5a79304205c08864052e8153db38d/f906/34e2/tmp7lsr9b13.tmp /home/mdpllard/Cactus/Chapter2/workdir_tmp/1ee5a79304205c08864052e8153db38d/f906/34e2/tmpbp8r5jv0.tmp /home/mdpllard/Cactus/Chapter2/workdir_tmp/1ee5a79304205c08864052e8153db38d/f906/34e2/tmpa1uapq2z.tmp
```
It takes a very long time to run (at least several days), even though it used to finish for me after ~2 hours with the previous release. This caused a timeout issue with the node I was using on my HPC. The command didn't get a chance to complete before the timeout so I don't know how long it would take to actually finish. Is this expected when changing from cPecanLastz to lastz?

Regardless, this is now a different problem. For now, I will close this issue. If the new problem persists, I will open up another issue.

**Comment by glennhickey** [comment]
Thanks for the update.  It is a bit worrisome if the newer lastz affects the runtime so much.  The command you posted (`cactus_mirrorAndOrientAlignments` ...) is a longtime annoyance, though I don't think I've ever seen it take *days*.  It's going to be replaced with something much faster in the next major release, but we are still testing it.
