### ISSUE TITLE
No log file is present, despite job failing: 'RoundedJob' kind-RoundedJob/instance-nkuv_zv7

### ISSUE THREAD

**Issue by charles-gumbi** [ComparativeGenomicsToolkit/cactus#665]
Hello  cactus support team
Thank you for providing and maintaining this fascinating program.  I'm running cactus o the cluster using the command below. 
Im getting the error below and, it what confusing that I can even get the logfile which might give me more info as to why the  'RoundedJob' id failing. 
Could somebody please help me decipher this error? 
humble regards 
Charles  

Camand ran on three mice genomes: 
cactus-prepare-toil ./jobStore ./seqFile.txt --binariesMode singularity --batchSystem slurm --realTimeLogging --outHal ./out.hal --defaultDisk 20G --defaultMemory 12G --defaultCores 4 --disableCaching

Error Logfile : 
[2022-02-15T12:13:11-0500] [MainThread] [I] [toil.job] Saving graph of 9 jobs, 9 new
[2022-02-15T12:13:11-0500] [MainThread] [I] [toil.job] Processing job 'JobFunctionWrappingJob' kind-JobFunctionWrappingJob/instance-kxfco8jv
[2022-02-15T12:13:11-0500] [MainThread] [I] [toil.job] Processing job 'Job' kind-Job/instance-j1dvckft
[2022-02-15T12:13:11-0500] [MainThread] [I] [toil.job] Processing job 'JobFunctionWrappingJob' kind-JobFunctionWrappingJob/instance-z6dnx2g3
[2022-02-15T12:13:11-0500] [MainThread] [I] [toil.job] Processing job 'JobFunctionWrappingJob' kind-JobFunctionWrappingJob/instance-w10ggyg3
[2022-02-15T12:13:11-0500] [MainThread] [I] [toil.job] Processing job 'Job' kind-Job/instance-dqspfy55
[2022-02-15T12:13:11-0500] [MainThread] [I] [toil.job] Processing job 'JobFunctionWrappingJob' kind-JobFunctionWrappingJob/instance-xgpo_2yp
[2022-02-15T12:13:11-0500] [MainThread] [I] [toil.job] Processing job 'JobFunctionWrappingJob' kind-JobFunctionWrappingJob/instance-x_yxjggw
[2022-02-15T12:13:11-0500] [MainThread] [I] [toil.job] Processing job 'JobFunctionWrappingJob' kind-JobFunctionWrappingJob/instance-t6zxw4o2
[2022-02-15T12:13:11-0500] [MainThread] [I] [toil.job] Processing job 'RoundedJob' kind-RoundedJob/instance-nkuv_zv7
[2022-02-15T12:13:11-0500] [MainThread] [I] [toil] Running Toil version 5.4.0-87293d63fa6c76f03bed3adf93414ffee67bf9a7 on host c0709a-s11.ufhpc.
[2022-02-15T12:13:11-0500] [MainThread] [I] [toil.realtimeLogger] Starting real-time logging.
[2022-02-15T12:13:11-0500] [MainThread] [I] [toil.leader] Issued job 'RoundedJob' kind-RoundedJob/instance-nkuv_zv7 with job batch system ID: 0 and cores: 4, disk: 18.6 Gi, and memory: 11.2 Gi
[2022-02-15T12:13:13-0500] [MainThread] [I] [toil.leader] 0 jobs are running, 1 jobs are issued and waiting to run
[2022-02-15T12:18:53-0500] [MainThread] [W] [toil.leader] Job failed with exit value 1: 'RoundedJob' kind-RoundedJob/instance-nkuv_zv7
Exit reason: None
[2022-02-15T12:18:53-0500] [MainThread] [W] [toil.leader] No log file is present, despite job failing: 'RoundedJob' kind-RoundedJob/instance-nkuv_zv7
[2022-02-15T12:18:53-0500] [MainThread] [W] [toil.job] Due to failure we are reducing the remaining try count of job 'RoundedJob' kind-RoundedJob/instance-nkuv_zv7 with ID kind-RoundedJob/instance-nkuv_zv7 to 1
[2022-02-15T12:18:54-0500] [MainThread] [I] [toil.leader] Issued job 'RoundedJob' kind-RoundedJob/instance-nkuv_zv7 with job batch system ID: 1 and cores: 4, disk: 18.6 Gi, and memory: 11.2 Gi
[2022-02-15T12:22:24-0500] [MainThread] [W] [toil.leader] Job failed with exit value 1: 'RoundedJob' kind-RoundedJob/instance-nkuv_zv7
Exit reason: None
[2022-02-15T12:22:24-0500] [MainThread] [W] [toil.leader] No log file is present, despite job failing: 'RoundedJob' kind-RoundedJob/instance-nkuv_zv7
[2022-02-15T12:22:24-0500] [MainThread] [W] [toil.job] Due to failure we are reducing the remaining try count of job 'RoundedJob' kind-RoundedJob/instance-nkuv_zv7 with ID kind-RoundedJob/instance-nkuv_zv7 to 0
[2022-02-15T12:22:25-0500] [MainThread] [W] [toil.leader] Job 'RoundedJob' kind-RoundedJob/instance-nkuv_zv7 is completely failed
[2022-02-15T12:22:36-0500] [MainThread] [I] [toil.leader] Finished toil run with 1 failed jobs.
[2022-02-15T12:22:36-0500] [MainThread] [I] [toil.leader] Failed jobs at end of the run: 'RoundedJob' kind-RoundedJob/instance-nkuv_zv7
[2022-02-15T12:22:36-0500] [MainThread] [I] [toil.realtimeLogger] Stopping real-time logging server.
[2022-02-15T12:22:36-0500] [MainThread] [I] [toil.realtimeLogger] Joining real-time logging server thread.
Traceback (most recent call last):
  File "/apps/cactus/2.0.3/bin/cactus-prepare-toil", line 33, in <module>
    sys.exit(load_entry_point('Cactus==1.0', 'console_scripts', 'cactus-prepare-toil')())
  File "/apps/cactus/2.0.3/lib/python3.6/site-packages/cactus/progressive/cactus_prepare.py", line 46, in main_toil
    return main(toil_mode=True)
  File "/apps/cactus/2.0.3/lib/python3.6/site-packages/cactus/progressive/cactus_prepare.py", line 230, in main
    cactusPrepare(options, project)
  File "/apps/cactus/2.0.3/lib/python3.6/site-packages/cactus/progressive/cactus_prepare.py", line 395, in cactusPrepare
    get_plan(options, project, seqFile, outSeqFile, toil=toil)
  File "/apps/cactus/2.0.3/lib/python3.6/site-packages/cactus/progressive/cactus_prepare.py", line 603, in get_plan
    toil.start(start_job)
  File "/apps/cactus/2.0.3/lib/python3.6/site-packages/toil/common.py", line 841, in start
    return self._runMainLoop(rootJobDescription)
  File "/apps/cactus/2.0.3/lib/python3.6/site-packages/toil/common.py", line 1132, in _runMainLoop
    jobCache=self._jobCache).run()
  File "/apps/cactus/2.0.3/lib/python3.6/site-packages/toil/leader.py", line 261, in run
    raise FailedJobsException(self.config.jobStore, self.toilState.totalFailedJobs, self.jobStore)
toil.leader.FailedJobsException: The job store 'file:/blue/austin/bonginkosi.gumbi/mastomys/genome/wtdg/progressive_cactus/jobStore' contains 1 failed jobs: 'RoundedJob' kind-RoundedJob/instance-nkuv_zv7
(END)

**Comment by glennhickey** [comment]
`cactus-parepare-toil` runs toil-within-toil jobs which makes logging and error handling a headache.  You can try adding --cactusOptions ' --realTimeLogging` to get more information.  

I would like to discontinue `cactus-prepare-toil` in favour of Cromwell/WDL eventually.
