### ISSUE TITLE
getpwuid() error using the Docker container

### ISSUE THREAD

**Issue by TomHarrop** [ComparativeGenomicsToolkit/cactus#677]
I have a question about an issue running the Docker container. I'm using the evolverMammal example as follows:

```bash
cactus jobStore seqfile.txt alignment.hal --binariesMode local --workDir ./
```
I'm getting the following error:

```python
Traceback (most recent call last):
  File "/usr/local/bin/cactus", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.8/dist-packages/cactus/progressive/cactus_progressive.py", line 349, in main
    Job.Runner.addToilOptions(parser)
  File "/usr/local/lib/python3.8/dist-packages/toil/job.py", line 1773, in addToilOptions
    addOptions(parser)
  File "/usr/local/lib/python3.8/dist-packages/toil/common.py", line 491, in addOptions
    add_all_batchsystem_options(batchsystem_options)
  File "/usr/local/lib/python3.8/dist-packages/toil/batchSystems/options.py", line 143, in add_all_batchsystem_options
    batch_system_type.add_options(parser)
  File "/usr/local/lib/python3.8/dist-packages/toil/batchSystems/kubernetes.py", line 1210, in add_options
    parser.add_argument("--kubernetesOwner", dest="kubernetes_owner", default=cls.get_default_kubernetes_owner(),
  File "/usr/local/lib/python3.8/dist-packages/toil/batchSystems/kubernetes.py", line 1203, in get_default_kubernetes_owner
    return ''.join([c for c in getpass.getuser().lower() if c in acceptable_chars])[:100]
  File "/usr/lib/python3.8/getpass.py", line 169, in getuser
    return pwd.getpwuid(os.getuid())[0]
KeyError: 'getpwuid(): uid not found: 998'
```
I've tried the v.2.0.5 release container ([c227e8d8aa41](https://quay.io/repository/comparative-genomics-toolkit/cactus/manifest/sha256:c227e8d8aa41739667f54edbf19902d872dd07cba4c5046d613fe4ba2eb12a0d)) and also a `latest` container (last week, [668fa4f38b5b](https://quay.io/repository/comparative-genomics-toolkit/cactus/manifest/sha256:668fa4f38b5b778770a9dc3eaeeafc230b4351cd78dc8bc720c71ab416ccba83)).

I'm writing a Galaxy wrapper for Cactus, and I've seen this on our dev servers and on GitHub CI runners. On our dev servers Docker jobs are meant to run as user `galaxy`, which has UID 998 (i.e. the UID in the error message).

Unfortunately I only have limited access to the Docker config on those systems, but if it seems like a config issue with our Docker setup I'd appreciate some advice. 

The same container runs fine with Singularity, and FWIW, other Docker containers have been OK so far with this setup.

Thanks for reading!

**Comment by glennhickey** [comment]
It'd be cool to get Cactus on Galaxy!  

Any ideas about this one, @adamnovak ?

**Comment by adamnovak** [comment]
Well the situation that causes this is the UID in use (998) doesn't have an entry in `/etc/passwd` as viewed in the container, and so when we go to get a user name we can't.

This is a Toil bug where Toil can't start up because Kubernetes batch system can't handle the nonexistence of a username (as reported by a `KeyError` when you call `getpass.getuser()`). I'll go ahead and open that.

A workaround would be to assign a username to UID 998 in the container, either by changing the `/etc/passwd` file in the container, or mounting it in from the enclosing system.

**Comment by bgruening** [comment]
An alternative approach would be to help updating the bioconda package: https://github.com/bioconda/bioconda-recipes/pulls?q=is%3Apr+is%3Aopen+cactus

This will give you a minimal container and singularity image for free and would help as well with the Galaxy deployment.

**Comment by TomHarrop** [comment]
The Cactus developers recommend against using the conda package.
