### ISSUE TITLE
TrimAndRecurseOnOutgroups: MemoryError

### ISSUE THREAD

**Issue by mdpllard** [ComparativeGenomicsToolkit/cactus#681]
Hello,

I have been running cactus step-by-step. During the third round of alignments, I came upon an error while running `cactus-blast`, specifically with `TrimAndRecurseOnOutgroups`. Originally, the job would completely fail due to not having enough memory. I increased the amount of memory available to it to 1500 gb and eventually got a different error message. Here is the error:
```
[2022-03-10T02:37:39-0600] [Thread-1  ] [E] [toil.batchSystems.singleMachine] Got exit code 1 (indicating failure) from job _toil_worker TrimAndRecurseOnOutgroups file:/home/mdpllard/Cactus/Chapter2/jobstore_1/50 kind-TrimAndRecurseOnOutgroups/instance-h64vg21t.
[2022-03-10T02:37:39-0600] [MainThread] [W] [toil.leader] Job failed with exit value 1: 'TrimAndRecurseOnOutgroups' kind-TrimAndRecurseOnOutgroups/instance-h64vg21t v1
Exit reason: None
[2022-03-10T02:37:40-0600] [MainThread] [W] [toil.leader] The job seems to have left a log file, indicating failure: 'TrimAndRecurseOnOutgroups' kind-TrimAndRecurseOnOutgroups/instance-h64vg21t v2
[2022-03-10T02:37:40-0600] [MainThread] [W] [toil.leader] Log from job "kind-TrimAndRecurseOnOutgroups/instance-h64vg21t" follows:
=========>
        [2022-03-08T10:21:07-0600] [MainThread] [I] [toil.worker] ---TOIL WORKER OUTPUT LOG---
        [2022-03-08T10:21:07-0600] [MainThread] [I] [toil] Running Toil version 5.6.0-c34146a6437e4407a61e946e968bcce67a0ebbca on host b002.
        [2022-03-08T10:21:07-0600] [MainThread] [I] [toil.worker] Working on job 'TrimAndRecurseOnOutgroups' kind-TrimAndRecurseOnOutgroups/instance-h64vg21t v1
        [2022-03-08T10:21:12-0600] [MainThread] [I] [toil.worker] Loaded body Job('TrimAndRecurseOnOutgroups' kind-TrimAndRecurseOnOutgroups/instance-h64vg21t v1) from description 'TrimAndRecurseOnOutgroups' kind-TrimAndRecurseOnOutgroups/instance-h64vg21t v1
        [2022-03-08T10:21:12-0600] [MainThread] [I] [toil.statsAndLogging] Calculating coverage of cigar file /home/mdpllard/Cactus/Chapter2/workdir_tmp/000d66a1647753f5b1a8fbee95ea4f69/b52c/03ff/tmpe9ufyhgp.tmp on /home/mdpllard/Cactus/Chapter2/workdir_tmp/000d66a1647753f5b1a8fbee95ea4f69/b52c/03ff/tmpaoo6jw9x.tmp, writing to /home/mdpllard/Cactus/Chapter2/workdir_tmp/000d66a1647753f5b1a8fbee95ea4f69/b52c/03ff/tmpww896wxg.tmp
        [2022-03-08T10:21:12-0600] [MainThread] [I] [cactus.shared.common] Running the command ['cactus_coverage', '/home/mdpllard/Cactus/Chapter2/workdir_tmp/000d66a1647753f5b1a8fbee95ea4f69/b52c/03ff/tmpaoo6jw9x.tmp', '/home/mdpllard/Cactus/Chapter2/workdir_tmp/000d66a1647753f5b1a8fbee95ea4f69/b52c/03ff/tmpe9ufyhgp.tmp']
        [2022-03-08T10:21:12-0600] [MainThread] [I] [toil-rt] 2022-03-08 10:21:12.296354: Running the command: "cactus_coverage /home/mdpllard/Cactus/Chapter2/workdir_tmp/000d66a1647753f5b1a8fbee95ea4f69/b52c/03ff/tmpaoo6jw9x.tmp /home/mdpllard/Cactus/Chapter2/workdir_tmp/000d66a1647753f5b1a8fbee95ea4f69/b52c/03ff/tmpe9ufyhgp.tmp"
        [2022-03-10T02:29:26-0600] [MainThread] [W] [toil.fileStores.abstractFileStore] Failed job accessed files:
        [2022-03-10T02:29:26-0600] [MainThread] [W] [toil.fileStores.abstractFileStore] Downloaded file 'files/for-job/kind-CactusBlastPhase/instance-e55uenmm/cleanup/file-f007479c8cbd41c38b43be8a1df7a23f/tmp3z5v2afu.tmp' to path '/home/mdpllard/Cactus/Chapter2/workdir_tmp/000d66a1647753f5b1a8fbee95ea4f69/b52c/03ff/tmpaoo6jw9x.tmp'
        [2022-03-10T02:29:26-0600] [MainThread] [W] [toil.fileStores.abstractFileStore] Downloaded file 'files/for-job/kind-CactusBlastPhase/instance-e55uenmm/cleanup/file-858b165db26f49c5b51495b225626ca2/tmpr6a3fb0c.tmp' to path '/home/mdpllard/Cactus/Chapter2/workdir_tmp/000d66a1647753f5b1a8fbee95ea4f69/b52c/03ff/tmp9gpypio3.tmp'
        [2022-03-10T02:29:26-0600] [MainThread] [W] [toil.fileStores.abstractFileStore] Downloaded file 'files/for-job/kind-CactusBlastPhase/instance-e55uenmm/cleanup/file-ee20011ed4e14903bc4aae9410baa67d/tmpkeklp0ye.tmp' to path '/home/mdpllard/Cactus/Chapter2/workdir_tmp/000d66a1647753f5b1a8fbee95ea4f69/b52c/03ff/tmpuid32axp.tmp'
        [2022-03-10T02:29:26-0600] [MainThread] [W] [toil.fileStores.abstractFileStore] Downloaded file 'files/for-job/kind-CollateBlasts2/instance-x6u1_oww/file-0ed414a735c240dead09b16f898aa9a7/tmp9dezzxm4.tmp' to path '/home/mdpllard/Cactus/Chapter2/workdir_tmp/000d66a1647753f5b1a8fbee95ea4f69/b52c/03ff/tmpe9ufyhgp.tmp'
        [2022-03-10T02:29:39-0600] [MainThread] [W] [toil.fileStores.abstractFileStore] LOG-TO-MASTER: Job used more disk than requested. For CWL, consider increasing the outdirMin requirement, otherwise, consider increasing the disk requirement. Job files/for-job/kind-TrimAndRecurseOnOutgroups/instance-h64vg21t/cleanup/file-ca6a29582b9d409f935f69f0ff73b5fb/stream used 932.82% disk (18.7 GiB [20032126976B] used, 2.0 GiB [2147483648B] requested).
        Traceback (most recent call last):
          File "/home/mdpllard/cactus-bin-v2.0.5/cactus_env/lib/python3.9/site-packages/toil/worker.py", line 405, in workerScript
            job._runner(jobGraph=None, jobStore=jobStore, fileStore=fileStore, defer=defer)
          File "/home/mdpllard/cactus-bin-v2.0.5/cactus_env/lib/python3.9/site-packages/cactus/shared/common.py", line 943, in _runner
            super(RoundedJob, self)._runner(*args, jobStore=jobStore,
          File "/home/mdpllard/cactus-bin-v2.0.5/cactus_env/lib/python3.9/site-packages/toil/job.py", line 2399, in _runner
            returnValues = self._run(jobGraph=None, fileStore=fileStore)
          File "/home/mdpllard/cactus-bin-v2.0.5/cactus_env/lib/python3.9/site-packages/toil/job.py", line 2317, in _run
            return self.run(fileStore)
          File "/home/mdpllard/cactus-bin-v2.0.5/cactus_env/lib/python3.9/site-packages/cactus/blast/blast.py", line 287, in run
            calculateCoverage(outgroupSequenceFiles[0],
          File "/home/mdpllard/cactus-bin-v2.0.5/cactus_env/lib/python3.9/site-packages/cactus/blast/blast.py", line 551, in calculateCoverage
            cactus_call(outfile=outputFile, work_dir=work_dir,
          File "/home/mdpllard/cactus-bin-v2.0.5/cactus_env/lib/python3.9/site-packages/cactus/shared/common.py", line 825, in cactus_call
            output, stderr = process.communicate(stdin_string if first_run else None, timeout=10)
          File "/home/mdpllard/miniconda3/envs/py39/lib/python3.9/subprocess.py", line 1134, in communicate
            stdout, stderr = self._communicate(input, endtime, timeout)
          File "/home/mdpllard/miniconda3/envs/py39/lib/python3.9/subprocess.py", line 1980, in _communicate
            self._check_timeout(endtime, orig_timeout, stdout, stderr)
          File "/home/mdpllard/miniconda3/envs/py39/lib/python3.9/subprocess.py", line 1181, in _check_timeout
            stderr=b''.join(stderr_seq) if stderr_seq else None)
        MemoryError
        [2022-03-10T02:29:40-0600] [MainThread] [E] [toil.worker] Exiting the worker because of a failed job on host b002
<=========
[2022-03-10T02:37:40-0600] [MainThread] [W] [toil.job] Due to failure we are reducing the remaining try count of job 'TrimAndRecurseOnOutgroups' kind-TrimAndRecurseOnOutgroups/instance-h64vg21t v2 with ID kind-TrimAndRecurseOnOutgroups/instance-h64vg21t to 10
```
Besides increasing the memory, I also reinstalled cactus in a new environment and started the job again (I'm not sure if changing cactus version halfway through a step-by-step pipeline is a bad thing to do). I still got the same error with the new install of cactus.

Is there a solution to the issue I am having? Any advice would be very much appreciated.

Thanks in advance,
Matthew Pollard

**Comment by mdpllard** [comment]
Hi Glenn,

I will try to email you the input genome files.

The `cactus-blast` command that has been failing is:
`cactus-blast jobstore_1/50 steps-output_1/carnivora_outSeqFile_shortbranch.txt steps-output_1/Anc20.cigar --root Anc20 --realTimeLogging --logInfo --retryCount 10 --maxCores 40 --maxMemory 530Gi --workDir workdir_tmp`

The seqFile (carnivora_outSeqFile_shortbranch.txt) contains this:
```
(((Vulpes_vulpes:0.0085743917,((Chrysocyon_brachyurus:0.00485535544,Canis_lupus:0.00485535482)Anc11:0.00286498422,Nyctereutes_procyonoides:0.00772033939)Anc07:0.00085405204)Anc03:0.0225830921,(((Mirounga_angustirostris:0.01399307272,(Odobenus_rosmarus:0.00847845583,Zalophus_californianus:0.00847845605)Anc17:0.0055146158)Anc12:0.01065683341,(Spilogale_gracilis:0.02217315683,(((Potos_flavus:0.01727484928,((Procyon_lotor:0.0048197613,Bassariscus_sumichrasti:0.00481976103)Anc25:0.00783124342,Nasua_narica:0.01265100419)Anc23:0.004623844)Anc21:0.00316349647,(Martes_foina:0.01031195791,(Mustela_putorius:0.00934991692,(Lutra_lutra:0.00371217163,Aonyx_cinereus:0.00371217163)Anc26:0.00563774536)Anc24:0.00096204152)Anc22:0.01012638568)Anc20:0.00100859926,Ailurus_fulgens:0.02144694286)Anc18:0.00072621343)Anc13:0.00247675037)Anc08:0.00152807367,(((Ursus_maritimus:0.00202468732,Ursus_americanus:0.00202468708)Anc19:0.00029006884,Helarctos_malayanus:0.00231475589)Anc14:0.00563251285,Ailuropoda_melanoleuca:0.00794726956)Anc09:0.01823071212)Anc04:0.00497950211)Anc01:0.00554546331,((((Hyaena_hyaena:0.00388818264,Crocuta_crocuta:0.00388818102)Anc15:0.01066142925,(Cryptoprocta_ferox:0.01254084437,Suricata_suricatta:0.01254084545)Anc16:0.00200876643)Anc10:0.00328215797,Paradoxurus_hermaphroditus:0.01783176905)Anc05:0.00097670218,(Panthera_pardus:0.00594657637,Felis_catus:0.00594657645)Anc06:0.0128618964)Anc02:0.01789447263)Anc00;
Vulpes_vulpes	steps-output_1/Vulpes_vulpes_HiC.fasta.masked
Chrysocyon_brachyurus	steps-output_1/Chrysocyon_brachyurus_HiC.fasta.masked
*Canis_lupus	steps-output_1/CanFam3.1.fna.masked
Nyctereutes_procyonoides	steps-output_1/Nyctereutes_procyonoides.fna.masked
Mirounga_angustirostris	steps-output_1/Mirounga_angustirostris_HiC.fasta.masked
Odobenus_rosmarus	steps-output_1/Odobenus_rosmarus_HiC.fasta.masked
Zalophus_californianus	steps-output_1/Zalophus_californianus.fna.masked
Spilogale_gracilis	steps-output_1/Spilogale_gracilis.fna.masked
Potos_flavus	steps-output_1/Potos_flavus_HiC.fasta.masked
Procyon_lotor	steps-output_1/Procyon_lotor_HiC.fasta.masked
Bassariscus_sumichrasti	steps-output_1/Bassariscus_sumichrasti_HiC.fasta.masked
Nasua_narica	steps-output_1/Nasua_narica_HiC.fasta.masked
Martes_foina	steps-output_1/Martes_foina_HiC.fasta.masked
Mustela_putorius	steps-output_1/Mustela_putorius_HiC.fasta.masked
*Lutra_lutra	steps-output_1/Lutra_lutra_HiC.fasta.masked
Aonyx_cinereus	steps-output_1/Aonyx_cinereus_HiC.fasta.masked
Ailurus_fulgens	steps-output_1/Ailurus_fulgens_HiC.fasta.masked
Ursus_maritimus	steps-output_1/Ursus_maritimus_UrsMar_1.0_HiC.fasta.masked
Ursus_americanus	steps-output_1/Ursus_americanus_ASM334442v1_HiC.fasta.masked
Helarctos_malayanus	steps-output_1/Ursus_malayanus_HiC.fasta.masked
Ailuropoda_melanoleuca	steps-output_1/Ailuropoda_melanoleuca.fna.masked
Hyaena_hyaena	steps-output_1/Hyaena_hyaena.fna.masked
Crocuta_crocuta	steps-output_1/Crocuta_crocuta_HiC.fasta.masked
Cryptoprocta_ferox	steps-output_1/Cryptoprocta_ferox_HiC.fasta.masked
Suricata_suricatta	steps-output_1/Suricata_suricatta_HiC.fasta.masked
Paradoxurus_hermaphroditus	steps-output_1/Paradoxurus_hermaphroditus.fna.masked
Panthera_pardus	steps-output_1/Panthera_pardus_HiC.fasta.masked
*Felis_catus	steps-output_1/Felis_catus_9.0.fna.masked
Anc00	steps-output_1/Anc00.fa
Anc01	steps-output_1/Anc01.fa
Anc02	steps-output_1/Anc02.fa
Anc03	steps-output_1/Anc03.fa
Anc04	steps-output_1/Anc04.fa
Anc05	steps-output_1/Anc05.fa
Anc06	steps-output_1/Anc06.fa
Anc07	steps-output_1/Anc07.fa
Anc08	steps-output_1/Anc08.fa
Anc09	steps-output_1/Anc09.fa
Anc10	steps-output_1/Anc10.fa
Anc11	steps-output_1/Anc11.fa
Anc12	steps-output_1/Anc12.fa
Anc13	steps-output_1/Anc13.fa
Anc14	steps-output_1/Anc14.fa
Anc15	steps-output_1/Anc15.fa
Anc16	steps-output_1/Anc16.fa
Anc17	steps-output_1/Anc17.fa
Anc18	steps-output_1/Anc18.fa
Anc19	steps-output_1/Anc19.fa
Anc20	steps-output_1/Anc20.fa
Anc21	steps-output_1/Anc21.fa
Anc22	steps-output_1/Anc22.fa
Anc23	steps-output_1/Anc23.fa
Anc24	steps-output_1/Anc24.fa
Anc25	steps-output_1/Anc25.fa
Anc26	steps-output_1/Anc26.fa
```
Let me know if you need anything else from me, or if I haven't sent the input genome files to the correct email address.

Thanks again,
Matthew

**Comment by glennhickey** [comment]
OK, thanks, I'm running it now.

**Comment by glennhickey** [comment]
Looks like I can reproduce:
```
11145 hickey    20   0  434.5g 381.0g   5352 R 100.0 37.8   2397:28 /public/groups/cgl/graph-genomes/hickey/work/cactus-bin-v2.0.5/venv-cactus-bin-2.0.5/bin/python3 /public/groups/cgl/graph-genomes/hickey/work/cactus-bin-v2.0.5/venv-cactus-bin-2.0.5/bin/_toil_worker TrimAndRecurseOnO+
50652 hickey    20   0 3105388 200164   8760 S  65.7  0.0   2320:10 /public/groups/cgl/graph-genomes/hickey/work/cactus-bin-v2.0.5/venv-cactus-bin-2.0.5/bin/python3 /public/groups/cgl/graph-genomes/hickey/work/cactus-bin-v2.0.5/venv-cactus-bin-2.0.5/bin/cactus-blast jobstore_1 carniv+
23796 hickey    20   0  173972   4108   1936 R   2.9  0.0   0:00.34 top                                                                                                                                                                                                                      
 4522 hickey    20   0  128056   3692   1040 S   0.0  0.0   0:06.33 /bin/bash
 7701 hickey    20   0  128192   3656    924 S   0.0  0.0   0:16.17 /bin/bash
11152 hickey    20   0    4360    272    188 S   0.0  0.0   0:00.00 /usr/bin/time -v cactus_coverage /public/groups/cgl/graph-genomes/hickey/work/pollard/work/2a6260f2225d54a2a7ae6cd16a2eee58/f667/d5d6/tmpp_clrfy9.tmp /public/groups/cgl/graph-genomes/hickey/work/pollard/work/2a6260f2+
11153 hickey    20   0 4396380   4.2g    272 S   0.0  0.4  96:25.18 cactus_coverage /public/groups/cgl/graph-genomes/hickey/work/pollard/work/2a6260f2225d54a2a7ae6cd16a2eee58/f667/d5d6/tmpp_clrfy9.tmp /public/groups/cgl/graph-genomes/hickey/work/pollard/work/2a6260f2225d54a2a7ae6cd16+
```
Pretty weird.  `cactus_coverage` has stalled out completely, and the calling python process is sucking up more memory by the second.  All it's supposed to be doing is just waiting until `cactus_coverage` is complete.  

`cactus_coverage` is writing a big file.  Maybe there's a bug somewhere where this isn't getting buffered properly.  I'll check but don't have any answers for now, unfortunately.

**Comment by glennhickey** [comment]
Work-around:
```
http://public.gi.ucsc.edu/~hickey/cactus_coverage
chmod +x cactus_coverage
cp cactus_coverage <CACTUS_INSTALL_DIR>/bin  ## replacing old cactus_coverage
```
Run again (with `--restart` if you still have the jobstore)
