### ISSUE TITLE
Anc0-1-2-3-4-5-n_experiment.xml does not exist.

### ISSUE THREAD

**Issue by eskutkaan** [ComparativeGenomicsToolkit/cactus#683]
`        [2022-03-19T19:09:34-0400] [MainThread] [I] [toil.worker] Loaded body Job('ProgressiveNext' kind-ProgressiveNext/instance-a03j9v37 v4) from description 'ProgressiveNext' kind-ProgressiveNext/instance-a03j9v37 v4
        [2022-03-19T19:09:34-0400] [MainThread] [I] [toil.fileStores.abstractFileStore] LOG-TO-MASTER: Project has 2 dependencies
        [2022-03-19T19:09:34-0400] [MainThread] [W] [toil.fileStores.abstractFileStore] Failed job accessed files:
        [2022-03-19T19:09:34-0400] [MainThread] [W] [toil.fileStores.abstractFileStore] Downloaded file 'files/no-job/file-1f1dc728b5774b0291739205c7fdbd0d/cpu-config-20.xml' to path '/scratch/kies222/tempcactus20/3960d044c95e51799db9582ff208e748/f4c2/2a1c/tmpq2c8b0ji.tmp'
        Traceback (most recent call last):
          File "/usr/local/lib/python3.8/dist-packages/toil/worker.py", line 405, in workerScript
            job._runner(jobGraph=None, jobStore=jobStore, fileStore=fileStore, defer=defer)
          File "/usr/local/lib/python3.8/dist-packages/cactus/shared/common.py", line 943, in _runner
            super(RoundedJob, self)._runner(*args, jobStore=jobStore,
          File "/usr/local/lib/python3.8/dist-packages/toil/job.py", line 2399, in _runner
            returnValues = self._run(jobGraph=None, fileStore=fileStore)
          File "/usr/local/lib/python3.8/dist-packages/toil/job.py", line 2317, in _run
            return self.run(fileStore)
          File "/usr/local/lib/python3.8/dist-packages/cactus/progressive/cactus_progressive.py", line 102, in run
            experiment = ExperimentWrapper(ET.parse(fileStore.readGlobalFile(expID)).getroot())
          File "/usr/local/lib/python3.8/dist-packages/toil/fileStores/nonCachingFileStore.py", line 111, in readGlobalFile
            self.jobStore.read_file(fileStoreID, localFilePath, symlink=symlink)
          File "/usr/local/lib/python3.8/dist-packages/toil/jobStores/fileJobStore.py", line 444, in read_file
            self._check_job_store_file_id(file_id)
          File "/usr/local/lib/python3.8/dist-packages/toil/jobStores/fileJobStore.py", line 779, in _check_job_store_file_id
            raise NoSuchFileException(jobStoreFileID)
        toil.jobStores.abstractJobStore.NoSuchFileException: File 'files/no-job/file-c9fc1f23b4af40019fdb5b58c192c17a/Anc0_experiment.xml' does not exist.`

I have several jobs running with different options and genomes. Every one of them failed with indicating AncN_experiment.xml does not exist after 6 days of running. When I restart the jobs, this keeps happening. I checked and saw the experiment files in the written path. I even tried to submit the cactus job from the jobstore directory to make sure there is no problem with path calling.

Kaan.

**Comment by eskutkaan** [comment]
just found #562, a duplicate of the issue. 
Broken symlink 'files/no-job/file-c9fc1f23b4af40019fdb5b58c192c17a/Anc0_experiment.xml'
<img width="1282" alt="Screen Shot 2022-03-21 at 3 16 49 PM" src="https://user-images.githubusercontent.com/98606896/159347647-00641caf-7b2a-4484-8a31-1aad3653095a.png">

**Comment by eskutkaan** [comment]
see #580's last comment for the solution, closing the issue. Just a bug that needs to be fixed.
