### ISSUE TITLE
Missing .hal files

### ISSUE THREAD

**Issue by davidaray** [ComparativeGenomicsToolkit/cactus#724]
Hi Glen et al.,

After our discussions on slack, I've been able to get things running on our HPCC and performed a test run on five assemblies. The program ran well for several days and appeared to complete last night but I see the following in my log file:

[2022-05-23T03:28:59-0500] [MainThread] [I] [toil.leader] Finished toil run successfully.
[2022-05-23T03:28:59-0500] [MainThread] [I] [toil.realtimeLogger] Stopping real-time logging server.
[2022-05-23T03:29:00-0500] [MainThread] [I] [toil.realtimeLogger] Joining real-time logging server thread.
[2022-05-23T03:29:06-0500] [MainThread] [I] [toil.common] Successfully deleted the job store: FileJobStore(/lustre/scratch/daray/cactus/jobstore/7)
[2022-05-23T03:29:06-0500] [MainThread] [I] [toil.statsAndLogging] cactus-align has finished after 10501.21617486293 seconds
terminate called after throwing an instance of 'hal_errno_exception'
  what():  ../steps-output_5bats/Anc1.hal: can't open HAL file: No such file or directory
/var/spool/slurmd/job5973376/slurm_script: line 52: 19183 Aborted                 (core dumped) halAppendSubtree ../steps-output_5bats/5bats.hal ../steps-output_5bats/Anc1.hal Anc1 Anc1 --merge --hdf5InMemory
terminate called after throwing an instance of 'hal_errno_exception'
  what():  ../steps-output_5bats/Anc2.hal: can't open HAL file: No such file or directory
/var/spool/slurmd/job5973376/slurm_script: line 53: 19192 Aborted                 (core dumped) halAppendSubtree ../steps-output_5bats/5bats.hal ../steps-output_5bats/Anc2.hal Anc2 Anc2 --merge --hdf5InMemory

Furthermore, the Anc1.fa and Anc2.fa files are empty. 

$ ls -lhrt
total 21G
-rw-r----- 1 daray bio 2.1G May 19 07:36 aJam.sm.fa
-rw-r----- 1 daray bio 1.8G May 19 07:36 rAeg.sm.fa
-rw-r----- 1 daray bio 2.3G May 19 07:36 hLar.sm.fa
-rw-r----- 1 daray bio  480 May 20 16:46 SeqFile_5bats.txt
-rw-r----- 1 daray bio 1.9G May 21 00:23 mMyo.sm.fa
-rw-r----- 1 daray bio 1.9G May 21 00:23 eFus.sm.fa
-rw-r----- 1 daray bio    0 May 21 00:24 Anc1.fa
-rw-r----- 1 daray bio 2.1G May 22 11:31 Anc2.cigar
-rw-r----- 1 daray bio 3.6G May 22 11:31 Anc2.cigar.secondary
-rw-r----- 1 daray bio 1.9G May 22 11:31 Anc2.cigar.og_fragment_0
-rw-r----- 1 daray bio 742M May 22 11:31 Anc2.cigar.og_fragment_1
-rw-r----- 1 daray bio 282M May 22 11:31 Anc2.cigar.og_fragment_2
-rw-r----- 1 daray bio 503M May 22 11:31 Anc2.cigar.ig_coverage_0
-rw-r----- 1 daray bio 705M May 22 11:31 Anc2.cigar.ig_coverage_1
-rw-r----- 1 daray bio    0 May 22 21:00 Anc2.fa
-rw-r----- 1 daray bio 149M May 23 00:33 Anc0.cigar
-rw-r----- 1 daray bio 311M May 23 00:33 Anc0.cigar.secondary
-rw-r----- 1 daray bio 201M May 23 03:29 Anc0.fa
-rw-r----- 1 daray bio 971M May 23 03:29 5bats.hal

What's interesting is that you'll notice that the hal output I'm interested in, 5bats.hal, appears to be present. 

Not sure if this worked or not.

If it helps, here is the run script. Any help in determining if the ran was successful would be appreciated.

David

```
#!/bin/bash 
#SBATCH --job-name=cactus5xl
#SBATCH --output=%x.%j.out
#SBATCH --error=%x.%j.err
#SBATCH --partition=xlquanah
#SBATCH --nodes=1
#SBATCH --ntasks=36
#SBATCH --account=xlquanah
#SBATCH --time=336:00:00

. ~/conda/etc/profile.d/conda.sh
conda activate cactus

cd /lustre/work/daray/software/cactus
source cactus-virt/bin/activate

export PATH=$PATH:/lustre/work/daray/software/cactus/cactus-bin-v2.0.5/bin

#Set the default number of processors to be used.
MAXCORES=36

cd /lustre/scratch/daray/cactus/bin



## generated by : /lustre/work/daray/software/cactus/cactus-virt/bin/cactus-prepare seqFile_5bats --outDir ../steps-output_5bats/ --outSeqFile ../steps-output_5bats/SeqFile_5bats.txt --outHal ../steps-output_5bats/5bats.hal --jobStore ../jobstore/
## date : 2022-05-16 15:30:16.675199
## cactus commit : f1eef4024bc70da92e1d269028613f16ec1a774b


## Preprocessor
cactus-preprocess ../jobstore/0 seqFile_5bats ../steps-output_5bats/SeqFile_5bats.txt --inputNames aJam.sm.fa rAeg.sm.fa hLar.sm.fa --realTimeLogging --logInfo --retryCount 0 
cactus-preprocess ../jobstore/1 seqFile_5bats ../steps-output_5bats/SeqFile_5bats.txt --inputNames mMyo.sm.fa eFus.sm.fa --realTimeLogging --logInfo --retryCount 0 

## Alignment

### Round 0
cactus-blast ../jobstore/2 ../steps-output_5bats/SeqFile_5bats.txt ../steps-output_5bats/Anc1.cigar --root Anc1 --realTimeLogging --logInfo --retryCount 0 
cactus-align ../jobstore/3 ../steps-output_5bats/SeqFile_5bats.txt ../steps-output_5bats/Anc1.cigar ../steps-output_5bats/Anc1.hal --root Anc1 --realTimeLogging --logInfo --retryCount 0 --maxCores $MAXCORES 
hal2fasta ../steps-output_5bats/Anc1.hal Anc1 --hdf5InMemory > ../steps-output_5bats/Anc1.fa

cactus-blast ../jobstore/4 ../steps-output_5bats/SeqFile_5bats.txt ../steps-output_5bats/Anc2.cigar --root Anc2 --realTimeLogging --logInfo --retryCount 0 
cactus-align ../jobstore/5 ../steps-output_5bats/SeqFile_5bats.txt ../steps-output_5bats/Anc2.cigar ../steps-output_5bats/Anc2.hal --root Anc2 --realTimeLogging --logInfo --retryCount 0 --maxCores $MAXCORES 
hal2fasta ../steps-output_5bats/Anc2.hal Anc2 --hdf5InMemory > ../steps-output_5bats/Anc2.fa

### Round 1
cactus-blast ../jobstore/6 ../steps-output_5bats/SeqFile_5bats.txt ../steps-output_5bats/Anc0.cigar --root Anc0 --realTimeLogging --logInfo --retryCount 0 
cactus-align ../jobstore/7 ../steps-output_5bats/SeqFile_5bats.txt ../steps-output_5bats/Anc0.cigar ../steps-output_5bats/5bats.hal --root Anc0 --realTimeLogging --logInfo --retryCount 0 --maxCores $MAXCORES 
hal2fasta ../steps-output_5bats/5bats.hal Anc0 --hdf5InMemory > ../steps-output_5bats/Anc0.fa

## HAL merging
halAppendSubtree ../steps-output_5bats/5bats.hal ../steps-output_5bats/Anc1.hal Anc1 Anc1 --merge --hdf5InMemory
halAppendSubtree ../steps-output_5bats/5bats.hal ../steps-output_5bats/Anc2.hal Anc2 Anc2 --merge --hdf5InMemory

```

**Comment by glennhickey** [comment]
Yeah, that definitely didn't work.  Looking quickly at your directories, it looks like maybe every command after `cactus-preprocess` failed?

**Comment by davidaray** [comment]
That was helpful. Now that I know where to look I can see that the failures began with oine 13518 in the .err file. I think I know what happened. There was an interruption at HPCC and the job was restarted by HPCC staff. Thus cactus thought I was restarting the run and found the previously made files and didn't know what to do. 

It appears to me that my best option is to add the '--restart' option after cactus-blast. Then restart the run.

However, I'm unclear on where exactly I should add the --restart. After just cactus-blast or after all commands?

Of course the other option is to just restart from the beginning but I'd lose several days with that. 

```
[2022-05-21T00:24:12-0500] [MainThread] [I] [toil.common] Successfully deleted the job store: FileJobStore(/lustre/scratch/daray/cactus/jobstore/1)
Traceback (most recent call last):
  File "/lustre/work/daray/software/cactus/cactus-virt/lib/python3.8/site-packages/toil/jobStores/fileJobStore.py", line 99, in initialize
    os.mkdir(self.jobStoreDir)
FileExistsError: [Errno 17] File exists: '/lustre/scratch/daray/cactus/jobstore/2'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/lustre/work/daray/software/cactus/cactus-virt/bin/cactus-blast", line 8, in <module>
    sys.exit(main())
  File "/lustre/work/daray/software/cactus/cactus-virt/lib/python3.8/site-packages/cactus/blast/cactus_blast.py", line 88, in main
    runCactusBlastOnly(options)
  File "/lustre/work/daray/software/cactus/cactus-virt/lib/python3.8/site-packages/cactus/blast/cactus_blast.py", line 94, in runCactusBlastOnly
    with Toil(options) as toil:
  File "/lustre/work/daray/software/cactus/cactus-virt/lib/python3.8/site-packages/toil/common.py", line 870, in __enter__
    jobStore.initialize(config)
  File "/lustre/work/daray/software/cactus/cactus-virt/lib/python3.8/site-packages/toil/jobStores/fileJobStore.py", line 102, in initialize
    raise JobStoreExistsException(self.jobStoreDir)
toil.jobStores.abstractJobStore.JobStoreExistsException: The job store '/lustre/scratch/daray/cactus/jobstore/2' already exists. Use --restart to resume the workflow, or remove the job store with 'toil clean' to start the workflow from scratch.
```

**Comment by glennhickey** [comment]
If a job failed because your cluster went down, rerunning it with `--restart` makes sense.  If a job failed because the preceding job, on which it depends for its input, failed then you definitely need to run from scratch.  You'll have to carefully inspect your logs to see which situation applies.
