### ISSUE TITLE
Cactus or Toil not seeing correct amount of disk space and can't override

### ISSUE THREAD

**Issue by tommathers** [ComparativeGenomicsToolkit/cactus#73]
Hi @joelarmstrong and others,

I have managed to get cactus running with local binaries on our slurm cluster. Note that I am running it as a local job because our slurm set up will not allow toil to launch independent jobs.

I am trying to align 14 300 - 400 Mb insect genomes. I have tested on a small dataset of two genomes and the job finished successfully, generating a hal file.

The larger job is failing due to running out of disk space. However this seems to be caused by toil or cactus incorrectly detecting how much space is available and limiting disk space for the job. I am working in scatch space in the cluster and have > 2Tb free space:

```
df -h .
Filesystem                                                          Size  Used Avail Use% Mounted on
jic-hpc-data.hpccluster:/ifs/apricot/JIC/PrimaryData/GROUP_SCRATCH   11T  8.3T  2.8T  75% /jic/scratch/groups
```
However, when toil launches is only detects around 60Gb and then sets this as the limit for max disk. Manually setting the --Max

```
source cactus-20180108;cactus --binariesMode local --restart --maxCores 30 --defaultDisk 200G --maxDisk 500G --maxMemory 250G Myzus_Bach_OG_species_level seq_file.txt Myzus_Bach_OG_species_level.hal
##########################

WARNING:toil.batchSystems.singleMachine:Limiting maxDisk to physically available disk **(6115602432).**
```

Subsequently, when the job reaches the extractHal phase it runs out of space and dies:

```
WARNING:toil.leader:A/1/jobO9MSpf    WARNING:toil.fileStore:LOG-TO-MASTER: Job used more disk than requested. Consider modifying the user script to avoid the chance of failure due to incorrectly requested resources. Job 9/h/job4wOYRU/g/tmpqvymAV-_serialiseJob-stream used 2681.34% (49.9 GB [53626814464B] used, 1.9 GB [2000000000B] requested) at the end of its run.
WARNING:toil.leader:A/1/jobO9MSpf    Traceback (most recent call last):
WARNING:toil.leader:A/1/jobO9MSpf      File "/usr/lib/python2.7/site-packages/toil/worker.py", line 314, in workerScript
WARNING:toil.leader:A/1/jobO9MSpf        job._runner(jobGraph=jobGraph, jobStore=jobStore, fileStore=fileStore)
WARNING:toil.leader:A/1/jobO9MSpf      File "/usr/lib/python2.7/site-packages/toil/job.py", line 1351, in _runner
WARNING:toil.leader:A/1/jobO9MSpf        returnValues = self._run(jobGraph, fileStore)
WARNING:toil.leader:A/1/jobO9MSpf      File "/usr/lib/python2.7/site-packages/toil/job.py", line 1296, in _run
WARNING:toil.leader:A/1/jobO9MSpf        return self.run(fileStore)
WARNING:toil.leader:A/1/jobO9MSpf      File "/usr/lib/python2.7/site-packages/toil/job.py", line 1480, in run
WARNING:toil.leader:A/1/jobO9MSpf        rValue = userFunction(*((self,) + tuple(self._args)), **self._kwargs)
WARNING:toil.leader:A/1/jobO9MSpf      File "/usr/lib/python2.7/site-packages/cactus/progressive/cactus_progressive.py", line 300, in exportHal
WARNING:toil.leader:A/1/jobO9MSpf        subHALPath = job.fileStore.readGlobalFile(experiment.getHalID())
WARNING:toil.leader:A/1/jobO9MSpf      File "/usr/lib/python2.7/site-packages/toil/fileStore.py", line 1661, in readGlobalFile
WARNING:toil.leader:A/1/jobO9MSpf        self.jobStore.readFile(fileStoreID, localFilePath, symlink=symlink)
WARNING:toil.leader:A/1/jobO9MSpf      File "/usr/lib/python2.7/site-packages/toil/jobStores/fileJobStore.py", line 392, in readFile
WARNING:toil.leader:A/1/jobO9MSpf        shutil.copyfile(jobStoreFilePath, localFilePath)
WARNING:toil.leader:A/1/jobO9MSpf      File "/usr/lib64/python2.7/shutil.py", line 84, in copyfile
WARNING:toil.leader:A/1/jobO9MSpf        copyfileobj(fsrc, fdst)
WARNING:toil.leader:A/1/jobO9MSpf      File "/usr/lib64/python2.7/shutil.py", line 52, in copyfileobj
WARNING:toil.leader:A/1/jobO9MSpf        fdst.write(buf)
WARNING:toil.leader:A/1/jobO9MSpf    IOError: [Errno 28] No space left on device
WARNING:toil.leader:A/1/jobO9MSpf    ERROR:toil.worker:Exiting the worker because of a failed job on host t512n12
WARNING:toil.leader:A/1/jobO9MSpf    WARNING:toil.jobGraph:Due to failure we are reducing the remaining retry count of job 'exportHal' A/1/jobO9MSpf with ID A/1/jobO9MSpf to 0
WARNING:toil.leader:Job 'exportHal' A/1/jobO9MSpf with ID A/1/jobO9MSpf is completely failed
INFO:toil.leader:Finished toil run with 3 failed jobs.
INFO:toil.leader:Failed jobs at end of the run: 'RunCactusPreprocessorThenProgressiveDown2' 9/h/job4wOYRU 'RunCactusPreprocessorThenProgressiveDown' e/w/jobilkErV 'exportHal' A/1/jobO9MSpf
Traceback (most recent call last):
  File "/bin/cactus", line 9, in <module>
    load_entry_point('progressiveCactus==1.0', 'console_scripts', 'cactus')()
  File "/usr/lib/python2.7/site-packages/cactus/progressive/cactus_progressive.py", line 458, in main
    halID = toil.restart()
  File "/usr/lib/python2.7/site-packages/toil/common.py", line 816, in restart
    return self._runMainLoop(rootJobGraph)
  File "/usr/lib/python2.7/site-packages/toil/common.py", line 1059, in _runMainLoop
    jobCache=self._jobCache).run()
  File "/usr/lib/python2.7/site-packages/toil/leader.py", line 237, in run
    raise FailedJobsException(self.config.jobStore, self.toilState.totalFailedJobs, self.jobStore)
toil.leader.FailedJobsException
```
Is there any way to override this behaviour or make toil / cactus see the true amout of disk space?

Thanks,

Tom.

**Comment by lac2208** [comment]
Hello Tom,

I have the exact same problem. Did you find a solution? 

Best, 

Laís

**Comment by tommathers** [comment]
Hi Lais,

Unfortunately, I still have no idea whats going wrong. I spoke to the HPC guys here at the JOhn Innnes Centre and they could not see why it would happen. Maybe we should post someithing on the toil github page?

Its frustrating because I think my alignment is done but I cant extract it!

Cheers,

Tom.

**Comment by lac2208** [comment]
Hello Tom,

It is very frustrating. It seems that toil 3.14  has a default storage
space of 2Gb per run. (see the documentation,
<https://buildmedia.readthedocs.org/media/pdf/toil/releases-3.14.0/toil.pdf>
page
23). The command we give cactus likely does not override this function.
I'm trying to investigate a way to change the default.

On the other hand, I'm also going to try aligning my genomes with SibeliaZ.
Apparently they have a new update that allows for alignment of large
genomes.

Please let me know if you make any progress!

Cheers

**Comment by MatteoSchiavinato** [comment]
> The command we give cactus likely does not override this function.

Any follow-up on this? We are experiencing the same issue with a local instance (non-batch).

**Comment by lac2208** [comment]
Hi Matteo, 
I got it to work. In my case, the problem was the tmp folder location. Toil was saving to a system default tmp located in a folder with small storage space, regardless of the run happening in a directory with lots of space. I fixed it by defining tmp location before run: 

TMPDIR=/home/large-folder/tmp
export TMPDIR

I hope this is the case for you too!

**Comment by MatteoSchiavinato** [comment]
> I hope this is the case for you too!

We came to a similar conclusion as well! Now it is running, let's see if it keeps running. Meanwhile, we had another issue concerning the 'logs` and the `tmp` folders: I think it would be very useful if the program created those, if not existent. It takes days to run it, and sometimes just to see it crash because the logs folder was not there (we thought it would have created it).

thanks!

**Comment by tommathers** [comment]
Hi,

Just wanted to add that I tried setting TMPDIR but this made no difference for me. I just managed to get it running though by setting the --workDir flag as per this post: #84 

Finally managed to finish my alignment!

Thanks,

Tom.

**Comment by amv33576** [comment]
Hello,
I tried with default settings in a SLURM system and did not work with a test data set. Then I added the --workDir flag, and it was a success. Now I am running my complete data set, and I am getting the following messages spread the log file:

[2021-05-12T05:02:43-0400] [Thread-3  ] [W] [toil.statsAndLogging] Got message from job at time 05-12-2021 05:02:43: Job used more disk than requested. Consider modifying the user script to avoid the chance of failure due to incorrectly requested resources. Job files/for-job/kind-PreprocessSequence/instance-1362glqy/cleanup/file-b4ksnzgp/stream used 111.00% (1.8 GB [1978610688B] used, 1.7 GB [1782579200B] requested) at the end of its run.

[2021-05-12T05:06:09-0400] [Thread-3  ] [W] [toil.statsAndLogging] Got message from job at time 05-12-2021 05:06:09: Job used more disk than requested. Consider modifying the user script to avoid the chance of failure due to incorrectly requested resources. Job files/for-job/kind-PreprocessSequence/instance-1362glqy/cleanup/file-cl9kx7z1/stream used 109.81% (1.8 GB [1957401600B] used, 1.7 GB [1782579200B] requested) at the end of its run.

[2021-05-12T05:13:56-0400] [Thread-3  ] [W] [toil.statsAndLogging] Got message from job at time 05-12-2021 05:13:56: Job used more disk than requested. Consider modifying the user script to avoid the chance of failure due to incorrectly requested resources. Job files/for-job/kind-PreprocessSequence/instance-1362glqy/cleanup/file-acl_f4ii/stream used 108.95% (1.8 GB [1942172672B] used, 1.7 GB [1782579200B] requested) at the end of its run.

[2021-05-12T05:14:21-0400] [Thread-3  ] [W] [toil.statsAndLogging] Got message from job at time 05-12-2021 05:14:21: Job used more disk than requested. Consider modifying the user script to avoid the chance of failure due to incorrectly requested resources. Job files/for-job/kind-PreprocessSequence/instance-1362glqy/cleanup/file-q5u6jcat/stream used 100.71% (1.7 GB [1795150848B] used, 1.7 GB [1782579200B] requested) at the end of its run.

The analysis has not stopped, but I am not sure what to do? should I stop the analysis and change somehow the script? or let it run and see if it finish? 

Thanks,

Anyi

**Comment by elcortegano** [comment]
In case it helps anybody I had this issue woth `cactus-align`, and what worked for me was just to create an empty new directory (within my working directory) and pass it to `--workDir`.
