### ISSUE TITLE
cPecanLastz errors

### ISSUE THREAD

**Issue by xiaolongtu** [ComparativeGenomicsToolkit/cactus#741]
Hi,

I just ran cactus meet some troble, the error is as follow:

what had happen? How to solve this problem.

2022-06-18 23:53:33.525398: Running the command: "cPecanLastz tmpko6ekhra.tmp[multiple][nameparse=darkspace] tmp3ss9qmgn.tmp[nameparse=darkspace] --step=3 --ambiguous=iupac,100,100 --ungapped --queryhsplimit=keep,nowarn:1500 --querydepth=keep,nowarn:13 --format=general:name1,zstart1,end1,name2,zstart2+,end2+ --markend"
1 jobs are running, 23 jobs are issued and waiting to run
1 jobs are running, 23 jobs are issued and waiting to run
Got exit code 1 (indicating failure) from job _toil_worker JobFunctionWrappingJob file:/gpfs/home/tuxl/project/20200107_monkey_denovo/03.evolution/phylogegy/cactus_60/jobstore kind-JobFunctionWrappingJob/instance-9ozxddb9.
Job failed with exit value 1: 'JobFunctionWrappingJob' kind-JobFunctionWrappingJob/instance-9ozxddb9
Exit reason: None
The job seems to have left a log file, indicating failure: 'JobFunctionWrappingJob' kind-JobFunctionWrappingJob/instance-9ozxddb9
Log from job "kind-JobFunctionWrappingJob/instance-9ozxddb9" follows:
=========>

  [2022-06-18T03:51:22+0800] [MainThread] [W] [toil.fileStores.abstractFileStore] Downloaded file 'files/for-job/kind-PreprocessSequence/instance-arrucm4o/cleanup/file-6cb18d50
d67b414c9410748d02a3293a/12380' to path '/gpfs/home/tuxl/project/20200107_monkey_denovo/03.evolution/phylogegy/cactus_60/workdir/492b45338fc353e8b623d7046104ab1d/c591/598e/tmpyiy41ygs/6181f3
3563ff5c358c773f6a52449015/5a7d/5364/tmpxx2od7by.tmp'
                Traceback (most recent call last):
                  File "/gpfs/home/tuxl/software/genome/cactus-bin-v2.0.4/venv/lib/python3.6/site-packages/toil/worker.py", line 393, in workerScript
                    job._runner(jobGraph=None, jobStore=jobStore, fileStore=fileStore, defer=defer)
                  File "/gpfs/home/tuxl/software/genome/cactus-bin-v2.0.4/venv/lib/python3.6/site-packages/cactus/shared/common.py", line 933, in _runner
                    fileStore=fileStore, **kwargs)
                  File "/gpfs/home/tuxl/software/genome/cactus-bin-v2.0.4/venv/lib/python3.6/site-packages/toil/job.py", line 2360, in _runner
                    returnValues = self._run(jobGraph=None, fileStore=fileStore)
                  File "/gpfs/home/tuxl/software/genome/cactus-bin-v2.0.4/venv/lib/python3.6/site-packages/toil/job.py", line 2281, in _run
                    return self.run(fileStore)
                  File "/gpfs/home/tuxl/software/genome/cactus-bin-v2.0.4/venv/lib/python3.6/site-packages/cactus/preprocessor/lastzRepeatMasking/cactus_lastzRepeatMask.py", line 192, in run
                    alignment = self.alignFastaFragments(fileStore, targetFiles, fragments)
                  File "/gpfs/home/tuxl/software/genome/cactus-bin-v2.0.4/venv/lib/python3.6/site-packages/cactus/preprocessor/lastzRepeatMasking/cactus_lastzRepeatMask.py", line 92, in alig
nFastaFragments
                    "--markend"])
                  File "/gpfs/home/tuxl/software/genome/cactus-bin-v2.0.4/venv/lib/python3.6/site-packages/cactus/shared/common.py", line 866, in cactus_call
                    raise RuntimeError("Command {} exited {}: {}".format(call, process.returncode, out))
                RuntimeError: Command ['cPecanLastz', 'tmpdr547vbq.tmp[multiple][nameparse=darkspace]', 'tmprcpppz_q.tmp[nameparse=darkspace]', '--step=3', '--ambiguous=iupac,100,100', '--un
gapped', '--queryhsplimit=keep,nowarn:1500', '--querydepth=keep,nowarn:13', '--format=general:name1,zstart1,end1,name2,zstart2+,end2+', '--markend'] exited 1: stdout=None, stderr=FAILURE: in
 load_fasta_sequence for tmpdr547vbq.tmp, sequence length 2,145,000,730+3,000,000 exceeds maximum (2,147,483,637)

                [2022-06-18T03:51:24+0800] [MainThread] [E] [toil.worker] Exiting the worker because of a failed job on host mu02
        <=========

        [2022-06-19T01:38:14+0800] [MainThread] [E] [toil.worker] Exiting the worker because of a failed job on host mu02
<=========
Due to failure we are reducing the remaining try count of job 'JobFunctionWrappingJob' kind-JobFunctionWrappingJob/instance-9ozxddb9 with ID kind-JobFunctionWrappingJob/instance-9ozxddb9 to 1
Issued job 'JobFunctionWrappingJob' kind-JobFunctionWrappingJob/instance-9ozxddb9 with job batch system ID: 26 and cores: 28, disk: 1.8 Ti, and memory: 93.1 Gi
2022-06-19 01:38:36.748209: Running the command: "cactus-preprocess /gpfs/home/tuxl/project/20200107_monkey_denovo/03.evolution/phylogegy/cactus_60/workdir/492b45338fc353e8b623d7046104ab1d/0bc4/a911/tmpv64tc41w/js --inPaths /gpfs/home/tuxl/project/20200107_monkey_denovo/03.evolution/phase2/wulab/prosimian/Otolemur_garnettii/Otolemur_garnettii.sm.fa --outPaths Otolemur_garnettii.sm.fa --workDir /gpfs/home/tuxl/project/20200107_monkey_denovo/03.evolution/phylogegy/cactus_60/workdir/492b45338fc353e8b623d7046104ab1d/0bc4/a911/tmpv64tc41w --maxCores 28 --maxDisk 1.8 Ti --maxMemory 93.1 Gi --realTimeLogging --logInfo --retryCount 0 --binariesMode local"

**Comment by glennhickey** [comment]
This looks like the same issue as #356.  Is one of your fasta inputs more than ~12 gigabases?  If it is, you can hack around it by reducing `proportionToSample="0.2"` inside `src/cactus/cactus_progressive_config.xml` to something smaller (and rerunning `pip install -U .`).  

But beware: we've mostly run Cactus on genomes <=4gb.  We're interested in supporting larger genomes but have not had a chance to work on them much yet.  As it stands, Cactus scales quadratically with the length of the genomes, so unless you have a lot of computing resources, you may not have much luck on such large inputs.

**Comment by lihongxiang97** [comment]
One of my fasta inputs is more than 26Gb, I have reduced "proportionToSample" to 0.07 according "2/26>0.07", But it doesn't seem to work, the error persists, do I need to lower the "proportionToSample" further?

**Comment by glennhickey** [comment]
If you are seeing 
```
load_fasta_sequence for tmpdr547vbq.tmp, sequence length 2,145,000,730+3,000,000 exceeds maximum (2,147,483,637)
```
then you indeed need to try decreasing `proportionToSample`

**Comment by lihongxiang97** [comment]
yes,  I saw this error:
`RuntimeError: Command ['singularity', '--silent', 'exec', '-u', '-B', '/home/ug1549/cactus/207_species_cactus/tmpdir/3f37e1e5c1c451158901cf156c949092/5eff/d896/tmpfb5x_6gu:/mnt', '--pwd', '/mnt', '/home/ug1549/cactus/207_species_cactus/js/cactus.img', 'lastz', 'Pit_1293.fa[multiple][nameparse=darkspace]', 'Pit_1293_frag[nameparse=darkspace]', '--step=3', '--ambiguous=iupac,100,100', '--ungapped', '--queryhsplimit=keep,nowarn:1500', '--querydepth=keep,nowarn:13', '--format=general:name1,zstart1,end1,name2,zstart2+,end2+', '--markend'] exited 1: stderr=FAILURE: in load_fasta_sequence for Pit_1293.fa, sequence length 2,141,775,695+10,000,000 exceeds maximum (2,147,483,637)`
So I decreased “proportionToSample” to 0.07, but the  error persists. Now I'm trying decreasing "proportionToSample" to 0.01, the program is running and I am waiting for the result. It seems to run a lot slower, is it because of adjusting this parameter?
