### ISSUE TITLE
Job used more disk than requested. For CWL, consider increasing the outdirMin requirement

### ISSUE THREAD

**Issue by hoyosmanuel** [ComparativeGenomicsToolkit/cactus#744]
Hi everyone, I am trying to implement cactus using SLURM and I need your help to solve a couple of problems. My main concern is that I am repeatedly getting this error: **LOG-TO-MASTER: Job used more disk than requested. For CWL, consider increasing the outdirMin requirement, otherwise, consider increasing the disk requirement.**

But before asking my question let me explain my exercises in detail.

**1. Initially I ran this exercise**

(mMyo.sm.fa:0.10149507,eFus.sm.fa:0.1142467,rAeg.sm.fa:0.19305446)Anc0
 ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ .------------------eFus.sm.fa 
‎ ‎ ‎ ‎ .--| 
‎ ‎ ‎ ‎|‎ ‎  ‎ ‎‎ ‎  ՝ ---rAeg.sm.fa‎  
‎ ‎ ‎ |‎  
‎ ‎ ‎  ‎ ՝ --mMyo.sm.fa ‎ 

The sequences were of high quality, the exercise ran smoothly without errors and I obtained the final hal archive.
So I know that CACTUS can run on my system

**2. For my second exercise I added one species to the three**

The species tree was:
((mMyo.sm.fa:0.14542096,aJam.softmasked.fa:0.12396091)Anc1:0.04254252,rAeg.sm.fa:0.10311657,eFus.sm.fa:0.74081521)Anc0; 

 ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ .------------------eFus.sm.fa 
‎ ‎ ‎ ‎ .--| 
‎ ‎ ‎ ‎|‎ ‎  ‎ ‎‎ ‎  ՝ ---rAeg.sm.fa‎  
‎ ‎ ‎ ‎|‎ ‎ 
‎ ‎ ‎ |‎--aJam.sofmasked.fa  
‎ ‎ ‎ |‎  
‎ ‎ ‎  ‎ ՝ --mMyo.sm.fa ‎ 
        
And this exercise presented errors. The most parsimonious explanation is that the aJam.sofmasked.fa sequence has some problem. However, I couldn't figure out what the problem was, because the program couldn't run due to memory problems (I think). This is a section of the exercise error log file:

```
[2022-06-23T08:11:11-0500] [MainThread] [I] [toil-rt] cactus_consolidated(Anc1): ERROR: Something went wrong with the command: blossom5 -e /tmp/stTmp6xuNEo -w /tmp/stTmple8MUG > /dev/null 2>&1 
[2022-06-23T08:11:26-0500] [Thread-1  ] [E] [toil.batchSystems.singleMachine] Got exit code 1 (indicating failure) from job _toil_worker CactusConsolidated [file:/lustre/scratch/mhoyosro/cactus/jobstore6/3 kind-CactusConsolidated/instance-uftspf1i](http://file/lustre/scratch/mhoyosro/cactus/jobstore6/3%20kind-CactusConsolidated/instance-uftspf1i). 
[2022-06-23T08:11:26-0500] [MainThread] [W] [toil.leader] Job failed with exit value 1: 'CactusConsolidated' kind-CactusConsolidated/instance-uftspf1i v1 
Exit reason: None 
[2022-06-23T08:11:26-0500] [MainThread] [W] [toil.leader] The job seems to have left a log file, indicating failure: 'CactusConsolidated' kind-CactusConsolidated/instance-uftspf1i v2 
[2022-06-23T08:11:26-0500] [MainThread] [W] [toil.leader] Log from job "kind-CactusConsolidated/instance-uftspf1i" follows: 
```

The log mentioned that while running the command  "cactus_consolidated" an error related to the used disk occurred. This error is the following: 

 
```
[2022-06-23T08:11:11-0500] [MainThread] [I] [toil-rt] cactus_consolidated(Anc1): ERROR: Something went wrong with the command: blossom5 -e /tmp/stTmp6xuNEo -w /tmp/stTmple8MUG > /dev/null 2>&1 
[2022-06-23T08:11:22-0500] [MainThread] [W] [toil.fileStores.abstractFileStore] Failed job accessed files: 
[2022-06-23T08:11:22-0500] [MainThread] [W] [toil.fileStores.abstractFileStore] Downloaded file 'files/for-job/kind-run_prepend_unique_ids/instance-4l7d1s6u/cleanup/file-c82571a4ae8145a2812a34a6f7b799c3/tmpsasexvx4.tmp.fa' to path '/tmp/f9c14101d94e5d10b218187ced25cce3/9de6/0fbb/tmp28u6hqo1.tmp' 
[2022-06-23T08:11:22-0500] [MainThread] [W] [toil.fileStores.abstractFileStore] Downloaded file 'files/no-job/file-4a584548dc944a9cbd05e9bff8e872b4/Anc1.cigar.og_fragment_1' to path '/tmp/f9c14101d94e5d10b218187ced25cce3/9de6/0fbb/tmpz1zczer5.tmp' 
[2022-06-23T08:11:22-0500] [MainThread] [W] [toil.fileStores.abstractFileStore] Downloaded file 'files/for-job/kind-run_prepend_unique_ids/instance-4l7d1s6u/cleanup/file-bc97634dad98439fa8e457c783dfdd5b/tmpxlgjh1cx.tmp.fa' to path '/tmp/f9c14101d94e5d10b218187ced25cce3/9de6/0fbb/tmp6glqse2d.tmp' 
[2022-06-23T08:11:22-0500] [MainThread] [W] [toil.fileStores.abstractFileStore] Downloaded file 'files/no-job/file-acccbf4340e64ddf82dfc8c1eb59bb5d/Anc1.cigar.og_fragment_0' to path '/tmp/f9c14101d94e5d10b218187ced25cce3/9de6/0fbb/tmp_6h68q2u.tmp' 
[2022-06-23T08:11:22-0500] [MainThread] [W] [toil.fileStores.abstractFileStore] Downloaded file 'files/no-job/file-7a2ca8b254174be9b4752b88d83a15d0/Anc1.cigar' to path '/tmp/f9c14101d94e5d10b218187ced25cce3/9de6/0fbb/tmppxmt03zc.tmp' 
[2022-06-23T08:11:22-0500] [MainThread] [W] [toil.fileStores.abstractFileStore] Downloaded file 'files/no-job/file-0c98ff8fe9254b5e96384c71684c8287/Anc1.cigar.secondary' to path '/tmp/f9c14101d94e5d10b218187ced25cce3/9de6/0fbb/tmpnxxayg_q.tmp' 
[2022-06-23T08:11:22-0500] [MainThread] [W] [toil.fileStores.abstractFileStore] LOG-TO-MASTER: Job used more disk than requested. For CWL, consider increasing the outdirMin requirement, otherwise, consider increasing the disk requirement. Job files/for-job/kind-CactusConsolidated/instance-uftspf1i/cleanup/file-3f96fa94f0dd4850ab54260ab722e421/stream used 108.46% disk (12.8 GiB [13754769408B] used, 11.8 GiB [12682102407B] requested). 
The log file ---TOIL WORKER OUTPUT LOG--- continues providing more specific details: 
```

This was the first time I saw the error "Job used more disk than requested. For CWL, consider increasing the outdirMin requirement, otherwise, consider increasing the disk requirement. Job files/for-job/kind-CactusConsolidated/instance-uftspf1i/cleanup/file-3f96fa94f0dd4850ab54260ab722e421/stream used 108.46% disk (12.8 GiB [13754769408B] used, 11.8 GiB [12682102407B] requested). "

However there were other errors that I am trying to interpret:

```
The log file ---TOIL WORKER OUTPUT LOG--- continues providing more specific details: 
Traceback (most recent call last): 
  File "/lustre/work/mhoyosro/software/cactus/cactus-virt/lib/python3.8/site-packages/toil/worker.py", line 405, in workerScript 
    job._runner(jobGraph=None, jobStore=jobStore, fileStore=fileStore, defer=defer) 
  File "/lustre/work/mhoyosro/software/cactus/cactus-virt/lib/python3.8/site-packages/cactus/shared/common.py", line 943, in _runner 
    super(RoundedJob, self)._runner(*args, jobStore=jobStore, 
  File "/lustre/work/mhoyosro/software/cactus/cactus-virt/lib/python3.8/site-packages/toil/job.py", line 2399, in _runner 
    returnValues = self._run(jobGraph=None, fileStore=fileStore) 
  File "/lustre/work/mhoyosro/software/cactus/cactus-virt/lib/python3.8/site-packages/toil/job.py", line 2317, in _run 
    return self.run(fileStore) 
  File "/lustre/work/mhoyosro/software/cactus/cactus-virt/lib/python3.8/site-packages/cactus/pipeline/cactus_workflow.py", line 408, in run 
    messages = runCactusConsolidated(seqMap=seqMap, 
  File "/lustre/work/mhoyosro/software/cactus/cactus-virt/lib/python3.8/site-packages/cactus/shared/common.py", line 197, in runCactusConsolidated 
    masterMessages = cactus_call(check_output=True, returnStdErr=True, realtimeStderrPrefix='cactus_consolidated({})'.format(referenceEvent), 
  File "/lustre/work/mhoyosro/software/cactus/cactus-virt/lib/python3.8/site-packages/cactus/shared/common.py", line 877, in cactus_call 
    raise RuntimeError("Command {} exited {}: {}".format(call, process.returncode, out)) 
RuntimeError: Command ['cactus_consolidated', '--sequences', 'aJam.softmasked.fa /tmp/f9c14101d94e5d10b218187ced25cce3/9de6/0fbb/tmp28u6hqo1.tmp eFus.sm.fa /tmp/f9c14101d94e5d10b218187ced25cce3/9de6/0fbb/tmpz1zczer5.tmp mMyo.sm.fa /tmp/f9c14101d94e5d10b218187ced25cce3/9de6/0fbb/tmp6glqse2d.tmp rAeg.sm.fa /tmp/f9c14101d94e5d10b218187ced25cce3/9de6/0fbb/tmp_6h68q2u.tmp', '--speciesTree', '((mMyo.sm.fa:0.14542096,aJam.softmasked.fa:0.12396091)Anc1:0.04254252,rAeg.sm.fa:0.10311657,eFus.sm.fa:0.74081521)Anc0;', '--logLevel', 'INFO', '--alignments', '/tmp/f9c14101d94e5d10b218187ced25cce3/9de6/0fbb/tmppxmt03zc.tmp', '--params', '/tmp/f9c14101d94e5d10b218187ced25cce3/9de6/0fbb/tmp53u8hgoq.tmp', '--outputFile', '/tmp/f9c14101d94e5d10b218187ced25cce3/9de6/0fbb/tmpn6qijtm1.tmp', '--outputHalFastaFile', '/tmp/f9c14101d94e5d10b218187ced25cce3/9de6/0fbb/tmpubdhpag8.tmp', '--outputReferenceFile', '/tmp/f9c14101d94e5d10b218187ced25cce3/9de6/0fbb/tmpfjopdpm7.tmp', '--outgroupEvents', 'rAeg.sm.fa eFus.sm.fa', '--referenceEvent', 'Anc1', '--secondaryAlignments', '/tmp/f9c14101d94e5d10b218187ced25cce3/9de6/0fbb/tmpnxxayg_q.tmp', '--threads', '36'] exited 1: stdout=Attaching the sequence to the cactus root 1162125, header scaffold_m19_p_1 with length 223369599 and 89768340 total bases aligned and 0 bases aligned to other chromosome threads 
```
 
This last line of the error log ends in a sentence (wich is worring I guess) mentioning the header of the sequences. Which makes me wonder if some feature probably in the header of the aJam.sofmasked.fa  sequence is causing the error. If this is the case I really don't know how to fix it.

In summary. In exercise 2 I had three potential problems:
a: An error with the blossom5 -e command
b: Some Job using more disk than requested
c: And a potential problem with sequence headers (I guess)

**3. For my third exercise I keep using the same tree**

((mMyo.sm.fa:0.14542096,aJam.softmasked.fa:0.12396091)Anc1:0.04254252,rAeg.sm.fa:0.10311657,eFus.sm.fa:0.74081521)Anc0; 

 ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ .------------------eFus.sm.fa 
‎ ‎ ‎ ‎ .--| 
‎ ‎ ‎ ‎|‎ ‎  ‎ ‎‎ ‎  ՝ ---rAeg.sm.fa‎  
‎ ‎ ‎ ‎|‎ ‎ 
‎ ‎ ‎ |‎--aJam.sofmasked.fa  
‎ ‎ ‎ |‎  
‎ ‎ ‎  ‎ ՝ --mMyo.sm.fa ‎ 

But added to my submission header the following line
**TMPDIR=/lustre/scratch/mhoyosro/cactus/TMP**

This way I was able to recover all temporary files to a known location. In this exercise the error related to the command blossom5 -e **disappeared**, but still I am having the problems related to disk space (line 232773 below) and the potential problem with the sequences headers (line 232789 below):

```
232550 [2022-07-06T04:39:26-0500] [Thread-4  ] [W] [toil.statsAndLogging] Got message from job at time 07-06-2022 04:39:26: Job used more disk than requested. For CWL, consider increasing the outdirMin requirement, otherwise, consider increasing the disk requirement. Job files/for-job/kind-TrimAndRecurseOnOutgroups/instance-2n2mqbux/cleanup/file-dac35998ea764fbdacfae5e7d74d7dda/stream used 580.45% disk (11.6 GiB [12465127424B] used, 2.0 GiB [2147483648B] requested).

232625 [2022-07-06T05:36:15-0500] [Thread-4  ] [W] [toil.statsAndLogging] Got message from job at time 07-06-2022 05:36:15: Job used more disk than requested. For CWL, consider increasing the outdirMin requirement, otherwise, consider increasing the disk requirement. Job files/for-job/kind-run_prepend_unique_ids/instance-wtzl__7w/cleanup/file-a9852fb4e23f475796613f85eefb89c0/stream used 390.40% disk (7.8 GiB [8383779328B] used, 2.0 GiB [2147483648B] requested).
232626 [2022-07-06T05:36:16-0500] [MainThread] [I] [toil.leader] Issued job 'run_setup_phase' kind-run_setup_phase/instance-_o62h56l v1 with job batch system ID: 9 and cores: 1, disk: 2.0 Gi, and memory: 2.0 Gi
232695 [2022-07-06T05:36:16-0500] [MainThread] [I] [toil.leader] Issued job 'run_setup_phase' kind-run_setup_phase/instance-_o62h56l v1 with job batch system ID: 9 and cores: 1, disk: 2.0 Gi, and memory: 2.0 Gi
232696 [2022-07-06T13:29:13-0500] [MainThread] [W] [toil.leader] Job failed with exit value 1: 'CactusConsolidated' kind-CactusConsolidated/instance-4o6riyjr v1
232697 Exit reason: None
232698 [2022-07-06T13:29:13-0500] [MainThread] [W] [toil.leader] The job seems to have left a log file, indicating failure: 'CactusConsolidated' kind-CactusConsolidated/instance-4o6riyjr v2
232699 [2022-07-06T13:29:13-0500] [MainThread] [W] [toil.leader] Log from job "kind-CactusConsolidated/instance-4o6riyjr" follows:
232700 =========>
232701 	[2022-07-06T05:36:22-0500] [MainThread] [I] [toil.worker] ---TOIL WORKER OUTPUT LOG---
232702	[2022-07-06T05:36:22-0500] [MainThread] [I] [toil] Running Toil version 5.6.0-c34146a6437e4407a61e946e968bcce67a0ebbca on host cpu-19-1.
232773	[2022-07-06T13:28:59-0500] [MainThread] [W] [toil.fileStores.abstractFileStore] LOG-TO-MASTER: Job used more disk than requested. For CWL, consider increasing the outdirMin requirement, otherwise, consider increasing the disk requirement. Job files/for-job/kind-CactusConsolidated/instance-4o6riyjr/cleanup/file-5ac2b57e9f1c47c09859ab5a9ce791ba/stream used 108.46% disk (12.8 GiB [13754867712B] used, 11.8 GiB [12682102407B] requested).
```

```
232768	[2022-07-06T13:28:59-0500] [MainThread] [W] [toil.fileStores.abstractFileStore] Downloaded file 'files/no-job/file-52c809300cbc44f99d537ee6abc1e8f1/Anc1.cigar.og_fragment_1' to path '/lustre/scratch/mhoyosro/cactus/TMP/baaf9999307c5ebea7e632b88537192e/1409/406c/tmp4dlyxf9v.tmp'
232769	[2022-07-06T13:28:59-0500] [MainThread] [W] [toil.fileStores.abstractFileStore] Downloaded file 'files/for-job/kind-run_prepend_unique_ids/instance-wtzl__7w/cleanup/file-86a6ce1188bb4068afd4d9fdd06221ba/tmpa8xwr9o3.tmp.fa' to path '/lustre/scratch/mhoyosro/cactus/TMP/baaf9999307c5ebea7e632b88537192e/1409/406c/tmplhrxt3sn.tmp'
232770	[2022-07-06T13:28:59-0500] [MainThread] [W] [toil.fileStores.abstractFileStore] Downloaded file 'files/no-job/file-ceb2e39942bc47f4b9fe92911df6d4e5/Anc1.cigar.og_fragment_0' to path '/lustre/scratch/mhoyosro/cactus/TMP/baaf9999307c5ebea7e632b88537192e/1409/406c/tmpd_xqhbje.tmp'
232771	[2022-07-06T13:28:59-0500] [MainThread] [W] [toil.fileStores.abstractFileStore] Downloaded file 'files/no-job/file-46d13ca7c19a48e1bb5d84be75b30541/Anc1.cigar' to path '/lustre/scratch/mhoyosro/cactus/TMP/baaf9999307c5ebea7e632b88537192e/1409/406c/tmp84zm56zf.tmp'
232772	[2022-07-06T13:28:59-0500] [MainThread] [W] [toil.fileStores.abstractFileStore] Downloaded file 'files/no-job/file-ee501802e9f34aff983ecffe8a1f603a/Anc1.cigar.secondary' to path '/lustre/scratch/mhoyosro/cactus/TMP/baaf9999307c5ebea7e632b88537192e/1409/406c/tmpkuredwd5.tmp'
232773	[2022-07-06T13:28:59-0500] [MainThread] [W] [toil.fileStores.abstractFileStore] LOG-TO-MASTER: Job used more disk than requested. For CWL, consider increasing the outdirMin requirement, otherwise, consider increasing the disk requirement. Job files/for-job/kind-CactusConsolidated/instance-4o6riyjr/cleanup/file-5ac2b57e9f1c47c09859ab5a9ce791ba/stream used 108.46% disk (12.8 GiB [13754867712B] used, 11.8 GiB [12682102407B] requested).
232774	Traceback (most recent call last):
232775	  File "/lustre/work/mhoyosro/software/cactus/cactus-virt/lib/python3.8/site-packages/toil/worker.py", line 405, in workerScript
232776	    job._runner(jobGraph=None, jobStore=jobStore, fileStore=fileStore, defer=defer)
232777	  File "/lustre/work/mhoyosro/software/cactus/cactus-virt/lib/python3.8/site-packages/cactus/shared/common.py", line 943, in _runner
232778	    super(RoundedJob, self)._runner(*args, jobStore=jobStore,
232779	  File "/lustre/work/mhoyosro/software/cactus/cactus-virt/lib/python3.8/site-packages/toil/job.py", line 2399, in _runner
232780	    returnValues = self._run(jobGraph=None, fileStore=fileStore)
232781	  File "/lustre/work/mhoyosro/software/cactus/cactus-virt/lib/python3.8/site-packages/toil/job.py", line 2317, in _run
232782	    return self.run(fileStore)
232783	  File "/lustre/work/mhoyosro/software/cactus/cactus-virt/lib/python3.8/site-packages/cactus/pipeline/cactus_workflow.py", line 408, in run
232784	    messages = runCactusConsolidated(seqMap=seqMap,
232785	  File "/lustre/work/mhoyosro/software/cactus/cactus-virt/lib/python3.8/site-packages/cactus/shared/common.py", line 197, in runCactusConsolidated
232786	    masterMessages = cactus_call(check_output=True, returnStdErr=True, realtimeStderrPrefix='cactus_consolidated({})'.format(referenceEvent),
232787	  File "/lustre/work/mhoyosro/software/cactus/cactus-virt/lib/python3.8/site-packages/cactus/shared/common.py", line 879, in cactus_call
232788	    raise RuntimeError("Command {} signaled {}: {}".format(call, signal.Signals(-process.returncode).name, out))
232789	RuntimeError: Command ['cactus_consolidated', '--sequences', 'aJam.softmasked.fa /lustre/scratch/mhoyosro/cactus/TMP/baaf9999307c5ebea7e632b88537192e/1409/406c/tmpfpzdfxvd.tmp eFus.sm.fa /lustre/scratch/mhoyosro/cactus/TMP/baaf9999307c5ebea7e632b88537192e/1409/406c/tmp4dlyxf9v.tmp mMyo.sm.fa /lustre/scratch/mhoyosro/cactus/TMP/baaf9999307c5ebea7e632b88537192e/1409/406c/tmplhrxt3sn.tmp rAeg.sm.fa /lustre/scratch/mhoyosro/cactus/TMP/baaf9999307c5ebea7e632b88537192e/1409/406c/tmpd_xqhbje.tmp', '--speciesTree', '((mMyo.sm.fa:0.14542096,aJam.softmasked.fa:0.12396091)Anc1:0.04254252,rAeg.sm.fa:0.10311657,eFus.sm.fa:0.74081521)Anc0;', '--logLevel', 'INFO', '--alignments', '/lustre/scratch/mhoyosro/cactus/TMP/baaf9999307c5ebea7e632b88537192e/1409/406c/tmp84zm56zf.tmp', '--params', '/lustre/scratch/mhoyosro/cactus/TMP/baaf9999307c5ebea7e632b88537192e/1409/406c/tmpw8xxoh1l.tmp', '--outputFile', '/lustre/scratch/mhoyosro/cactus/TMP/baaf9999307c5ebea7e632b88537192e/1409/406c/tmpdozobrg_.tmp', '--outputHalFastaFile', '/lustre/scratch/mhoyosro/cactus/TMP/baaf9999307c5ebea7e632b88537192e/1409/406c/tmpbzivdhwb.tmp', '--outputReferenceFile', '/lustre/scratch/mhoyosro/cactus/TMP/baaf9999307c5ebea7e632b88537192e/1409/406c/tmpnrwsz_aq.tmp', '--outgroupEvents', 'rAeg.sm.fa eFus.sm.fa', '--referenceEvent', 'Anc1', '--secondaryAlignments', '/lustre/scratch/mhoyosro/cactus/TMP/baaf9999307c5ebea7e632b88537192e/1409/406c/tmpkuredwd5.tmp', '--threads', '36'] signaled SIGBUS: stdout=Attaching the sequence to the cactus root 1162125, header scaffold_m19_p_1 with length 223369599 and 89770632 total bases aligned and 0 bases aligned to other chromosome threads
232790	Attaching the sequence to the cactus root 1162131, header scaffold_m19_p_2 with length 217756413 and 86815324 total bases aligned and 209155 bases aligned to other chromosome threads
232791	Attaching the sequence to the cactus root 1162137, header scaffold_m19_p_3 with length 213723965 and 82221861 total bases aligned and 358471 bases aligned to other chromosome threads
232792	Attaching the sequence to the cactus root 1162143, header scaffold_m19_p_4 with length 130331158 and 35124525 total bases aligned and 398909 bases aligned to other chromosome threads
232793	Attaching the sequence to the cactus root 1162149, header scaffold_m19_p_5 with length 111266764 and 49909196 total bases aligned and 216818 bases aligned to other chromosome threads
232794	Attaching the sequence to the cactus root 1162155, header scaffold_m19_p_6 with length 101075066 and 42273392 total bases aligned and 266443 bases aligned to other chromosome threads
232795	Attaching the sequence to the cactus root 1162161, header scaffold_m19_p_7 with length 94448911 and 42770255 total bases aligned and 235850 bases aligned to other chromosome threads
232796	Attaching the sequence to the cactus root 1162167, header scaffold_m19_p_8 with length 94234955 and 41093983 total bases aligned and 225700 bases aligned to other chromosome threads
232797	Attaching the sequence to the cactus root 1162173, header scaffold_m19_p_9 with length 92776453 and 41444464 total bases aligned and 242338 bases aligned to other chromosome threads
232798	Attaching the sequence to the cactus root 1162179, header scaffold_m19_p_10 with length 80193900 and 34190741 total bases aligned and 256501 bases aligned to other chromosome threads
232799	Attaching the sequence to the cactus root 1162185, header scaffold_m19_p_11 with length 78476750 and 33444286 total bases aligned and 234469 bases aligned to other chromosome threads
232800	Attaching the sequence to the cactus root 1162191, header scaffold_m19_p_12 with length 74216526 and 33768163 total bases aligned and 261166 bases aligned to other chromosome threads
232801	Attaching the sequence to the cactus root 1162197, header scaffold_m19_p_13 with length 58607551 and 27216403 total bases aligned and 157128 bases aligned to other chromosome threads
232802	Attaching the sequence to the cactus root 1162203, header scaffold_m19_p_14 with length 55602309 and 25685576 total bases aligned and 226527 bases aligned to other chromosome threads
232803	Attaching the sequence to the cactus root 1162209, header scaffold_m19_p_15 with length 53400106 and 24556625 total bases aligned and 159949 bases aligned to other chromosome threads
232804	Attaching the sequence to the cactus root 1162215, header scaffold_m19_p_16 with length 53200087 and 24111512 total bases aligned and 159488 bases aligned to other chromosome threads
232805	Attaching the sequence to the cactus root 1162221, header scaffold_m19_p_17 with length 47534757 and 21303489 total bases aligned and 217013 bases aligned to other chromosome threads
232806	Attaching the sequence to the cactus root 1162227, header scaffold_m19_p_18 with length 43537823 and 18838440 total bases aligned and 165393 bases aligned to other chromosome threads
232807	Attaching the sequence to the cactus root 1162233, header scaffold_m19_p_19 with length 42769290 and 17271199 total bases aligned and 186828 bases aligned to other chromosome threads
232808	Attaching the sequence to the cactus root 1162239, header scaffold_m19_p_20 with length 25313220 and 11718459 total bases aligned and 109670 bases aligned to other chromosome threads
232809	Attaching the sequence to the cactus root 1162245, header scaffold_m19_p_21 with length 15591159 and 6328135 total bases aligned and 36543 bases aligned to other chromosome threads
232810	Attaching the sequence to the cactus root 1162251, header scaffold_m19_p_22 with length 8097369 and 2279771 total bases aligned and 62429 bases aligned to other chromosome threads
232811	Attaching the sequence to the cactus root 1162257, header scaffold_m19_p_23 with le, stderr=None
232812	[2022-07-06T13:29:00-0500] [MainThread] [E] [toil.worker] Exiting the worker because of a failed job on host cpu-19-1
232813<=========
```

So finally (thanking you all for your patient reading) this is my question: How can I know if my problems are due to an error inside the aJam.sofmasked.fa sequence (maybe the headers of the sequence) or if this is memory problem due to the use of TOIL in SLURM?

**Comment by gwct** [comment]
Hello,
This or similar disk errors seem to be common issues popping up. In #596, which was started by someone else, I post about the same problem in which most of the analysis ran smoothly, but got caught up on a single branch with this same error. I note that I can run the `blossom5` command it says its getting hung up on successfully and I don't think my sequences or headers have any problems, so I think it is actually related to cactus somehow not having storage, or mis-allocating or not seeing all the storage space available.

[In this post](https://github.com/ComparativeGenomicsToolkit/cactus/issues/596#issuecomment-1139688328) of that issue I link to some other similar issues in which it is suggested to set `--workDir` to a directory with lots of storage, or otherwise changing the default system temp dir from `/tmp/` to something with lots of storage.

Like you, I tried the workarounds with `--workDir` and `$TMPDIR` to no avail -- I would always get the same disk error. Recently, #749 has a similar issue, though with the minigraph pipeline, and I've advised them to try these things as well, but given our experiences I'm not sure it will be successful. 

One final note is that I am also running cactus on SLURM and have also wondered about the compatibility between TOIL and SLURM. Maybe SLURM is the common thread between all of our issues... I wonder if @Overcraft90 from #749 is also running with SLURM?

Luckily for me, my problem was somehow resolved simply with the release of version 2.1.1, but it looks like this type of error comes up a lot, so hopefully the developers can shed some like on this.

**Comment by Overcraft90** [comment]
Hi @gwct,

Thanks for keeping the issue alive, as this seems to be a problem for few people. I confirm the cluster where I'm working also run SLURM.

Unfortunately, as you pointed out, despite the fix with `--workDir` the issue persisted..., I haven't tried to play with $TEMPDIR because I believe I will need to ask the IT team to do so. In fact, I'm host on a third party HPC cluster; thus, I cannot perform specific actions. However, if that's not the case please let me know.

Still waiting for a way to resolve this issue. Thanks in advance!

**Comment by glennhickey** [comment]
Hi [hoyosmanuel](https://github.com/hoyosmanuel).  Sorry for the late reply.  The "used more disk" messages are warnings not errors and can (usually) be safely ignored.  The showstopper in your last log is that the cactus_consolidated command `signaled SIGBUS`.  Unfortunately, that's a very difficult one and I'm not sure what to suggest.

**Comment by hoyosmanuel** [comment]
Thank you so much for your responses, Mr. Hickey and Mr. Thomas. 
Following the advice of Mr. Thomas I installed the most updated version of the program (in a different directory. . . I am currently running a test). But thanks to this I realized that I've made a mistake with the installation path corresponding to the exercise that I presented for this case (#744). Knowing this, I corrected the mistake and ran again this exercise. Coincidentally today the exercise finished, producing at the end a .hal file. As Mr. Hickey pointed out, different errors appeared in the final .err file, but none of them seemed to be relevant. I'm sorry having started a thread without assuming a mistake on my side from the start.
Muchas gracias.

**Comment by hoyosmanuel** [comment]
Thank you so much for your responses, Mr. Hickey and Mr. Thomas.
Following the advice of Mr. Thomas I installed the most updated version of the program (in a different directory. . . I am currently running a test). But thanks to this I realized that I've made a mistake with the path in the bash file corresponding to the exercise that I presented for this case (https://github.com/ComparativeGenomicsToolkit/cactus/issues/744). Knowing this, I corrected the mistake and ran again this exercise. Coincidentally today the exercise finished, producing at the end a .hal file. As Mr. Hickey pointed out, different errors appeared in the final .err file, but none of them seemed to be relevant. I'm sorry having started a thread without assuming a mistake on my side from the start.
Muchas gracias.
