### ISSUE TITLE
Cactus-minigraph: cactus-graphmap-split error

### ISSUE THREAD

**Issue by brettChapman** [ComparativeGenomicsToolkit/cactus#751]
Hi

I'm using cactus-minigraph from the lastest docker image and following the workflow here for the yeast pangenome: https://github.com/ComparativeGenomicsToolkit/cactus/blob/master/doc/pangenome.md

I get to the cactus-graphmap-split step and I get an error about resources being busy. I tried a few different parameters but still get the same error.

I've been running this command through singularity:

```
srun -n 1 singularity exec --cleanenv \
                           --no-home \
                           --overlay ${JOBSTORE_IMAGE} \
                           --bind ${CACTUS_SCRATCH}/tmp:/tmp \
                           ${CACTUS_IMAGE} cactus-graphmap-split /cactus/jobStore ${original_folder}/yeast-pg/yeastPangenome.txt ${original_folder}/yeast-pg/yeast.gfa.gz ${original_folder}/yeast-pg/yeast.paf --outDir ${original_folder}/yeast-pg/chroms/ --realTimeLogging --reference S288C --rescueJobsFrequency 7200 --deadlockWait 960 --deadlockCheckInterval 480 --defaultDisk 5000G --maxCores 2 --binariesMode local
```

I run the job on an image, created by this code:
```
mkdir -p -m 777 ${CACTUS_SCRATCH}/upper ${CACTUS_SCRATCH}/work
  truncate -s 8T "${JOBSTORE_IMAGE}"
  singularity exec ${CACTUS_IMAGE} mkfs.ext3 -d ${CACTUS_SCRATCH} "${JOBSTORE_IMAGE}"
```

The error:
```
[2022-07-21T06:26:58+0000] [MainThread] [I] [toil.worker] Redirecting logging to /tmp/4729222db28b5a1c85d093f98aa7ea2c/de4e/worker_log.txt
[2022-07-21T06:26:58+0000] [MainThread] [I] [toil.leader] Issued job 'split_gfa' kind-filter_paf/instance-52i421nb v3 with job batch system ID: 15 and cores: 1, disk: 197.3 Mi, and memory: 2.0 Gi
cwltool is not installed.
[2022-07-21T06:26:59+0000] [MainThread] [I] [toil.worker] Redirecting logging to /tmp/4729222db28b5a1c85d093f98aa7ea2c/76b9/worker_log.txt
[2022-07-21T06:26:59+0000] [MainThread] [I] [toil.leader] Issued job 'Job' kind-graphmap_split_workflow/instance-gg5ghhvd v2 with job batch system ID: 16 and cores: 1, disk: 4.5 Ti, and memory: 2.0 Gi
cwltool is not installed.
[2022-07-21T06:26:59+0000] [MainThread] [I] [toil.worker] Redirecting logging to /tmp/4729222db28b5a1c85d093f98aa7ea2c/aa4c/worker_log.txt
[2022-07-21T06:27:02+0000] [MainThread] [I] [toil.leader] Finished toil run successfully.
[2022-07-21T06:27:02+0000] [MainThread] [I] [toil.realtimeLogger] Stopping real-time logging server.
[2022-07-21T06:27:02+0000] [MainThread] [I] [toil.realtimeLogger] Joining real-time logging server thread.
Traceback (most recent call last):
  File "/home/cactus/cactus_env/bin/cactus-graphmap-split", line 8, in <module>
    sys.exit(main())
  File "/home/cactus/cactus_env/lib/python3.10/site-packages/cactus/refmap/cactus_graphmap_split.py", line 80, in main
    cactus_graphmap_split(options)
  File "/home/cactus/cactus_env/lib/python3.10/site-packages/cactus/refmap/cactus_graphmap_split.py", line 150, in cactus_graphmap_split
    wf_output = toil.start(Job.wrapJobFn(graphmap_split_workflow, options, config, seqIDMap,
  File "/home/cactus/cactus_env/lib/python3.10/site-packages/toil/common.py", line 953, in start
    self._shutdownBatchSystem()
  File "/home/cactus/cactus_env/lib/python3.10/site-packages/toil/common.py", line 1288, in _shutdownBatchSystem
    self._batchSystem.shutdown()
  File "/home/cactus/cactus_env/lib/python3.10/site-packages/toil/batchSystems/singleMachine.py", line 692, in shutdown
    BatchSystemSupport.workerCleanup(self.workerCleanupInfo)
  File "/home/cactus/cactus_env/lib/python3.10/site-packages/toil/batchSystems/abstractBatchSystem.py", line 395, in workerCleanup
    AbstractFileStore.shutdownFileStore(workflowDir, info.workflowID)
  File "/home/cactus/cactus_env/lib/python3.10/site-packages/toil/fileStores/abstractFileStore.py", line 173, in shutdownFileStore
    CachingFileStore.shutdown(cacheDir)
  File "/home/cactus/cactus_env/lib/python3.10/site-packages/toil/fileStores/cachingFileStore.py", line 1919, in shutdown
    robust_rmtree(dir_)
  File "/home/cactus/cactus_env/lib/python3.10/site-packages/toil/lib/io.py", line 53, in robust_rmtree
    shutil.rmtree(path)
  File "/usr/lib/python3.10/shutil.py", line 722, in rmtree
    _rmtree_safe_fd(fd, path, onerror)
  File "/usr/lib/python3.10/shutil.py", line 678, in _rmtree_safe_fd
    onerror(os.unlink, fullname, sys.exc_info())
  File "/usr/lib/python3.10/shutil.py", line 676, in _rmtree_safe_fd
    os.unlink(entry.name, dir_fd=topfd)
OSError: [Errno 16] Device or resource busy: '.nfs000000001166800800000155'
srun: error: node-1: task 0: Exited with exit code 1
```

**Comment by brettChapman** [comment]
I figured out what was wrong. I had not set the working directory with cactus-graphmap-split
