### ISSUE TITLE
cactus-update-prepare add should print help message instead of throwing exception with no args

### ISSUE THREAD

**Issue by glennhickey** [ComparativeGenomicsToolkit/cactus#753]
```
cactus-update-prepare add
Traceback (most recent call last):
  File "/home/hickey/dev/cactus.clean/venv-clean/bin/cactus-update-prepare", line 33, in <module>
    sys.exit(load_entry_point('Cactus', 'console_scripts', 'cactus-update-prepare')())
  File "/home/hickey/dev/cactus.clean/src/cactus/update/cactus_update_prepare.py", line 1069, in main
    setupBinaries(options)
  File "/home/hickey/dev/cactus.clean/src/cactus/shared/common.py", line 417, in setupBinaries
    if options.latest:
AttributeError: 'Namespace' object has no attribute 'latest'
```

**Comment by glennhickey** [comment]
@thiagogenez

**Comment by thiagogenez** [comment]
@glennhickey Sorry for the late reply on this and thanks for letting me know. Just become aware of this issue. I will check it out

**Comment by thiagogenez** [comment]
@glennhickey finally got some time to check this out - I will do it this week. Sorry for the delay.
