### ISSUE TITLE
RuntimeError

### ISSUE THREAD

**Issue by xiaolongtu** [ComparativeGenomicsToolkit/cactus#761]
$ sh run_toil_cactus.sh
mkdir: cannot create directory ‘workdir’: File exists
mkdir: cannot create directory ‘outdir’: File exists
mkdir: cannot create directory ‘tmpdir’: File exists
/gpfs/home/tuxl/software/genome/cactus-bin-v2.0.4/venv/lib/python3.6/site-packages/OpenSSL/crypto.py:8: CryptographyDeprecationWarning: Python 3.6 is no longer supported by the Python core team. Therefore, support for it is deprecated in cryptography and will be removed in a future release.
  from cryptography import utils, x509
Deprecated toil method.  Please use "toil.lib.conversions.human2bytes()" instead."
Deprecated toil method.  Please use "toil.lib.conversions.human2bytes()" instead."
Deprecated toil method.  Please use "toil.lib.conversions.human2bytes()" instead."
Deprecated toil method.  Please use "toil.lib.conversions.human2bytes()" instead."
Deprecated toil method.  Please use "toil.lib.conversions.human2bytes()" instead."
Deprecated toil method.  Please use "toil.lib.conversions.human2bytes()" instead."
Deprecated toil method.  Please use "toil.lib.conversions.human2bytes()" instead."
Traceback (most recent call last):
  File "/gpfs/home/tuxl/software/genome/cactus-bin-v2.0.4/venv/bin/cactus-prepare-toil", line 8, in <module>
    sys.exit(main_toil())
  File "/gpfs/home/tuxl/software/genome/cactus-bin-v2.0.4/venv/lib/python3.6/site-packages/cactus/progressive/cactus_prepare.py", line 46, in main_toil
    return main(toil_mode=True)
  File "/gpfs/home/tuxl/software/genome/cactus-bin-v2.0.4/venv/lib/python3.6/site-packages/cactus/progressive/cactus_prepare.py", line 230, in main
    cactusPrepare(options, project)
  File "/gpfs/home/tuxl/software/genome/cactus-bin-v2.0.4/venv/lib/python3.6/site-packages/cactus/progressive/cactus_prepare.py", line 391, in cactusPrepare
    with Toil(options) as toil:
  File "/gpfs/home/tuxl/software/genome/cactus-bin-v2.0.4/venv/lib/python3.6/site-packages/toil/common.py", line 769, in __enter__
    config.setOptions(self.options)
  File "/gpfs/home/tuxl/software/genome/cactus-bin-v2.0.4/venv/lib/python3.6/site-packages/toil/common.py", line 200, in setOptions
    "Set clean to \'never\'" % self.clean)
RuntimeError: Contradicting options passed: Clean flag is set to onSuccess despite the stats flag requiring the jobStore to be intact at the end of the run. Set clean to 'never'

hi, could you help me with this problem?

**Comment by glennhickey** [comment]
Hi, could you send me your command line?  From the log it looks like you are using two Toil options that can't be used together, something like `--cleanWorkDir onSuccess --stats`.  If that's the case, not using one or both of those options should fix your issue.

**Comment by xiaolongtu** [comment]
thank you , this is my command line:
cactus-prepare-toil  ./jobstore config.txt \
  --binariesMode local \
  --batchSystem torque \
  --realTimeLogging \
  --outDir $path/outdir \
  --workDir $path/workdir \
  --outHal $path/outdir/out.hal \
  --maxNodes 16 \
  --minNodes 1 \
  --preprocessCores 18 \
  --blastCores 18 \
  --alignCores 18 \
  --preprocessMemory 200G \
  --blastMemory 200G \
  --alignMemory 200G \
  --preprocessDisk 2000G \
  --blastDisk 2000G \
  --alignDisk 2000G \
  --halAppendDisk 2000G \
  --preprocessPreemptible 28 \
  --blastPreemptible 28 \
  --alignPreemptible 28 \
  --halAppendPreemptible 28 \
  --logFile out_cactus.log \
  --stats \
  --disableCaching \
  --disableAutoDeployment \
  --restart

**Comment by glennhickey** [comment]
Maybe try without `--stats`?
