### ISSUE TITLE
Disk for temporary space

### ISSUE THREAD

**Issue by hcsun1** [ComparativeGenomicsToolkit/cactus#764]
Hello,

I can not run Cactus because of an erro.

cwltool is not installed.
cwltool is not installed.
[2022-08-14T09:31:59-0400] [MainThread] [I] [toil.worker] Redirecting logging to /tmp/9c737caaa345505488d0229386d5371f/5ce9/worker_log.txt
[2022-08-14T09:31:59-0400] [MainThread] [I] [toil.worker] Redirecting logging to /tmp/9c737caaa345505488d0229386d5371f/8482/worker_log.txt
Traceback (most recent call last):
  File "/data/lilab/hcsun1/Software/cactus-bin-v2.1.1/cactus_env/bin/cactus", line 8, in <module>
    sys.exit(main())
  File "/data/lilab/hcsun1/Software/cactus-bin-v2.1.1/cactus_env/lib/python3.8/site-packages/cactus/progressive/cactus_progressive.py", line 406, in main
    runCactusProgressive(options)
  File "/data/lilab/hcsun1/Software/cactus-bin-v2.1.1/cactus_env/lib/python3.8/site-packages/cactus/progressive/cactus_progressive.py", line 456, in runCactusProgressive
    halID = toil.start(RunCactusPreprocessorThenProgressiveDown(options, project, memory=configWrapper.getDefaultMemory()))
  File "/data/lilab/hcsun1/Software/cactus-bin-v2.1.1/cactus_env/lib/python3.8/site-packages/toil/common.py", line 951, in start
    return self._runMainLoop(rootJobDescription)
  File "/data/lilab/hcsun1/Software/cactus-bin-v2.1.1/cactus_env/lib/python3.8/site-packages/toil/common.py", line 1273, in _runMainLoop
    return Leader(config=self.config,
  File "/data/lilab/hcsun1/Software/cactus-bin-v2.1.1/cactus_env/lib/python3.8/site-packages/toil/leader.py", line 251, in run
    self.innerLoop()
  File "/data/lilab/hcsun1/Software/cactus-bin-v2.1.1/cactus_env/lib/python3.8/site-packages/toil/leader.py", line 709, in innerLoop
    self._processReadyJobs()
  File "/data/lilab/hcsun1/Software/cactus-bin-v2.1.1/cactus_env/lib/python3.8/site-packages/toil/leader.py", line 606, in _processReadyJobs
    self._processReadyJob(message.job_id, message.result_status)
  File "/data/lilab/hcsun1/Software/cactus-bin-v2.1.1/cactus_env/lib/python3.8/site-packages/toil/leader.py", line 547, in _processReadyJob
    self._runJobSuccessors(job_id)
  File "/data/lilab/hcsun1/Software/cactus-bin-v2.1.1/cactus_env/lib/python3.8/site-packages/toil/leader.py", line 444, in _runJobSuccessors
    self.issueJobs(successors)
  File "/data/lilab/hcsun1/Software/cactus-bin-v2.1.1/cactus_env/lib/python3.8/site-packages/toil/leader.py", line 886, in issueJobs
    self.issueJob(job)
  File "/data/lilab/hcsun1/Software/cactus-bin-v2.1.1/cactus_env/lib/python3.8/site-packages/toil/leader.py", line 862, in issueJob
    jobBatchSystemID = self.batchSystem.issueBatchJob(jobNode, job_environment=job_environment)
  File "/data/lilab/hcsun1/Software/cactus-bin-v2.1.1/cactus_env/lib/python3.8/site-packages/toil/batchSystems/singleMachine.py", line 616, in issueBatchJob
    self.checkResourceRequest(jobDesc.memory, cores, jobDesc.disk, job_name=jobDesc.jobName,
  File "/data/lilab/hcsun1/Software/cactus-bin-v2.1.1/cactus_env/lib/python3.8/site-packages/toil/batchSystems/abstractBatchSystem.py", line 332, in checkResourceRequest
    raise InsufficientSystemResources(msg)
toil.batchSystems.abstractBatchSystem.InsufficientSystemResources: The job CactusPreprocessor is requesting 33449574400 bytes of disk for temporary space, more than the maximum of 5827391488 bytes of disk of free space on None that SingleMachineBatchSystem was configured with, or enforced by --maxDisk.  Try setting/changing the toil option "--workDir" or changing the base temporary directory by setting TMPDIR.Scale is set to 1.0.

Please help me.
Thank you.

**Comment by glennhickey** [comment]
It wants more disk.  See the last part of your log

**The job CactusPreprocessor is requesting 33449574400 bytes of disk for temporary space, more than the maximum of 5827391488 bytes of disk of free space on None that SingleMachineBatchSystem was configured with, or enforced by --maxDisk. Try setting/changing the toil option "--workDir" or changing the base temporary directory by setting TMPDIR.Scale is set to 1.0.**
