### ISSUE TITLE
ValueError: could not convert string to float

### ISSUE THREAD

**Issue by xiaolongtu** [ComparativeGenomicsToolkit/cactus#765]
hi, dear glennhickey  , now I met this problem,  how to solve it ? 

[2022-08-15T00:25:09+0800] [MainThread] [I] [toil.leader] 20 jobs are running, 0 jobs are issued and waiting to run
Workflow Progress  76%|██████████████████████████████████████████████████████████████████████████████████▎                         | 64/84 (0 failures) [4d 7h 01:15<1d 8h 11:39, 0.00 jobs/s][2022-08-15T01:25:10+0800] [MainThread] [I] [toil.leader] 20 jobs are running, 0 jobs are issued and waiting to run
Workflow Progress  76%|██████████████████████████████████████████████████████████████████████████████████▎                         | 64/84 (0 failures) [4d 7h 53:48<1d 8h 28:04, 0.00 jobs/s]
[2022-08-15T02:17:45+0800] [MainThread] [I] [toil.realtimeLogger] Stopping real-time logging server.
[2022-08-15T02:17:45+0800] [MainThread] [I] [toil.realtimeLogger] Joining real-time logging server thread.
Traceback (most recent call last):
  File "/gpfs/home/tuxl/software/cactus-bin-v2.1.1/cactus_env/bin/cactus-prepare-toil", line 8, in <module>
    sys.exit(main_toil())
  File "/gpfs/home/tuxl/software/cactus-bin-v2.1.1/cactus_env/lib/python3.8/site-packages/cactus/progressive/cactus_prepare.py", line 46, in main_toil
    return main(toil_mode=True)
  File "/gpfs/home/tuxl/software/cactus-bin-v2.1.1/cactus_env/lib/python3.8/site-packages/cactus/progressive/cactus_prepare.py", line 238, in main
    cactusPrepare(options, project)
  File "/gpfs/home/tuxl/software/cactus-bin-v2.1.1/cactus_env/lib/python3.8/site-packages/cactus/progressive/cactus_prepare.py", line 399, in cactusPrepare
    get_plan(options, project, seqFile, outSeqFile, toil=toil)
  File "/gpfs/home/tuxl/software/cactus-bin-v2.1.1/cactus_env/lib/python3.8/site-packages/cactus/progressive/cactus_prepare.py", line 615, in get_plan
    toil.start(start_job)
  File "/gpfs/home/tuxl/software/cactus-bin-v2.1.1/cactus_env/lib/python3.8/site-packages/toil/common.py", line 951, in start
    return self._runMainLoop(rootJobDescription)
  File "/gpfs/home/tuxl/software/cactus-bin-v2.1.1/cactus_env/lib/python3.8/site-packages/toil/common.py", line 1273, in _runMainLoop
    return Leader(config=self.config,
  File "/gpfs/home/tuxl/software/cactus-bin-v2.1.1/cactus_env/lib/python3.8/site-packages/toil/leader.py", line 251, in run
    self.innerLoop()
  File "/gpfs/home/tuxl/software/cactus-bin-v2.1.1/cactus_env/lib/python3.8/site-packages/toil/leader.py", line 731, in innerLoop
    self.checkForDeadlocks()
  File "/gpfs/home/tuxl/software/cactus-bin-v2.1.1/cactus_env/lib/python3.8/site-packages/toil/leader.py", line 763, in checkForDeadlocks
    totalRunningJobs = len(self.batchSystem.getRunningBatchJobIDs())
  File "/gpfs/home/tuxl/software/cactus-bin-v2.1.1/cactus_env/lib/python3.8/site-packages/toil/batchSystems/abstractGridEngineBatchSystem.py", line 418, in getRunningBatchJobIDs
    batchIds = self.with_retries(self.worker.getRunningJobIDs)
  File "/gpfs/home/tuxl/software/cactus-bin-v2.1.1/cactus_env/lib/python3.8/site-packages/toil/batchSystems/abstractGridEngineBatchSystem.py", line 473, in with_retries
    return operation(*args, **kwargs)
  File "/gpfs/home/tuxl/software/cactus-bin-v2.1.1/cactus_env/lib/python3.8/site-packages/toil/batchSystems/torque.py", line 110, in getRunningJobIDs
    walltime = hms_duration_to_seconds(walltime)
  File "/gpfs/home/tuxl/software/cactus-bin-v2.1.1/cactus_env/lib/python3.8/site-packages/toil/lib/conversions.py", line 103, in hms_duration_to_seconds
    if(float(val) < 0):
ValueError: could not convert string to float: ''

**Comment by glennhickey** [comment]
This seems like  a Toil issue.  Any idea, @adamnovak ?

**Comment by adamnovak** [comment]
I think this is https://github.com/DataBiosphere/toil/issues/3715 happening., where we couldn't handle not getting a time from Torque. It should have been fixed in https://github.com/DataBiosphere/toil/pull/3962 which is in Toil 5.6.0 and later.

@xiaolongtu What version of Toil do you get in `pip list` in your `cactus_env` virtual environment? And if you `pip install --upgrade "toil>=5.6.0"`, does the problem go away?

**Comment by xiaolongtu** [comment]
@adamnovak  thank you for your suggestion , I found the toil is 5.6.0.  
$ ./pip list
Package            Version
------------------ ------------------
addict             2.4.0
argcomplete        2.0.0
attrs              22.1.0
bagit              1.8.1
biopython          1.79
blessed            1.19.1
boto               2.49.0
boto3              1.24.46
boto3-stubs        1.24.46
botocore           1.27.46
botocore-stubs     1.27.46
CacheControl       0.12.11
Cactus             2.1.1
certifi            2022.6.15
charset-normalizer 2.1.0
cigar              0.1.3
coloredlogs        15.0.1
cwltool            3.1.20211107152837
decorator          5.1.1
dill               0.3.5.1
docker             5.0.3
enlighten          1.10.2
future             0.18.2
futures            3.1.1
humanfriendly      10.0
idna               3.3
iniconfig          1.1.1
isodate            0.6.1
jmespath           1.0.1
lockfile           0.12.2
lxml               4.9.1
mistune            0.8.4
msgpack            1.0.4
mypy-boto3-s3      1.24.36.post1
mypy-extensions    0.4.3
networkx           2.8
numpy              1.23.1
packaging          21.3
pip                22.2.2
pluggy             1.0.0
prefixed           0.3.2
prov               1.5.1
psutil             5.9.1
py                 1.11.0
py-tes             0.4.2
pydot              1.4.2
pyparsing          3.0.9
pytest             7.1.2
python-dateutil    2.8.2
pytz               2022.1
rdflib             6.0.2
requests           2.28.1
ruamel.yaml        0.17.17
ruamel.yaml.clib   0.2.6
s3transfer         0.6.0
schema-salad       8.3.20220801194920
setuptools         63.4.2
shellescape        3.8.1
six                1.16.0
sonLib             2.0
toil               5.6.0
tomli              2.0.1
types-awscrt       0.13.14
types-s3transfer   0.6.0.post4
typing_extensions  4.3.0
urllib3            1.26.11
wcwidth            0.2.5
websocket-client   1.3.3
wheel              0.37.1

**Comment by adamnovak** [comment]
Hm. It looks like maybe your Torque can report times that aren't completely empty strings, but which do have empty strings in them when split on `:`. Whatever is going on, Toil isn't getting the input it expects from the scheduler, and is crashing. Are you using a particularly strange Torque?

I've opened a Toil bug at https://github.com/DataBiosphere/toil/issues/4183 to try and make Toil more permissive here. We should eventually fix it.

One thing that might help illuminate what's going on would be the debug-level logs (`--logDebug`) from a case where this happens. But I think we would be able to hack around it without them.
