### ISSUE TITLE
Failure at the last step of using cactus-graphmap-join to creat the vg index 

### ISSUE THREAD

**Issue by ZoeYang2020** [ComparativeGenomicsToolkit/cactus#767]
Hi, 
I am testing the Minigraph-cactus pipeline. 
I am able to get the evolver primates data successfully run, but for my own data set, the last step of using cactus-graphmap-join to generate the index and vcf file always failed.
My data is bacterial genomes, and I did follow the suggestion rename the  # Haploid sample:
NC_017518   ./NC_017518
NC_017518sim.0  ./NC_017518
for the txt file. 

the error is as following:
[2022-08-16T11:33:38+1200] [MainThread] [I] [toil.job] Processing job 'graphmap_join_workflow' kind-graphmap_join_workflow/instance-eb0hozqi v0
[2022-08-16T11:33:38+1200] [MainThread] [I] [toil] Running Toil version 5.6.0-c34146a6437e4407a61e946e968bcce67a0ebbca on host kscprod-bio9.
[2022-08-16T11:33:38+1200] [MainThread] [I] [toil.realtimeLogger] Starting real-time logging.
[2022-08-16T11:33:38+1200] [MainThread] [I] [toil.leader] Issued job 'graphmap_join_workflow' kind-graphmap_join_workflow/instance-eb0hozqi v1 with job batch system ID: 0 and cores: 1, disk: 2.0 Gi, and memory: 2.0 Gi
[2022-08-16T11:33:39+1200] [MainThread] [I] [toil.worker] Redirecting logging to /tmp/97c28d646d225cd782062204cf19e7dc/abae/worker_log.txt
[2022-08-16T11:33:40+1200] [MainThread] [I] [toil.leader] 0 jobs are running, 0 jobs are issued and waiting to run
[2022-08-16T11:33:40+1200] [MainThread] [I] [toil.leader] Issued job 'clip_vg' kind-clip_vg/instance-wahoerft v1 with job batch system ID: 1 and cores: 1, disk: 4.3 Mi, and memory: 8.7 Mi
[2022-08-16T11:33:40+1200] [MainThread] [I] [toil.worker] Redirecting logging to /tmp/97c28d646d225cd782062204cf19e7dc/7bb0/worker_log.txt
[2022-08-16T11:33:40+1200] [MainThread] [I] [toil-rt] 2022-08-16 11:33:40.715112: Running the command: "clip-vg /tmp/97c28d646d225cd782062204cf19e7dc/7bb0/d8ff/tmpazi_e8bd/4Sim.vg -f -e NC_017518 -o /tmp/97c28d646d225cd782062204cf19e7dc/7bb0/d8ff/tmpazi_e8bd/4Sim.vg.clip.bed -d _MINIGRAPH_ -L"
[2022-08-16T11:33:41+1200] [Thread-1  ] [E] [toil.batchSystems.singleMachine] Got exit code 1 (indicating failure) from job _toil_worker clip_vg file:/NGS/active/IPL/MENINGO/analysis/graph_genome/Minigraph-Cactus/4Sim/jobstore kind-clip_vg/instance-wahoerft.
[2022-08-16T11:33:41+1200] [MainThread] [W] [toil.leader] Job failed with exit value 1: 'clip_vg' kind-clip_vg/instance-wahoerft v1
Exit reason: None
[2022-08-16T11:33:41+1200] [MainThread] [W] [toil.leader] The job seems to have left a log file, indicating failure: 'clip_vg' kind-clip_vg/instance-wahoerft v2
[2022-08-16T11:33:41+1200] [MainThread] [W] [toil.leader] Log from job "kind-clip_vg/instance-wahoerft" follows:
=========>
        [2022-08-16T11:33:40+1200] [MainThread] [I] [toil.worker] ---TOIL WORKER OUTPUT LOG---
        [2022-08-16T11:33:40+1200] [MainThread] [I] [toil] Running Toil version 5.6.0-c34146a6437e4407a61e946e968bcce67a0ebbca on host kscprod-bio9.
        [2022-08-16T11:33:40+1200] [MainThread] [I] [toil.worker] Working on job 'clip_vg' kind-clip_vg/instance-wahoerft v1
        [2022-08-16T11:33:40+1200] [MainThread] [I] [toil.worker] Loaded body Job('clip_vg' kind-clip_vg/instance-wahoerft v1) from description 'clip_vg' kind-clip_vg/instance-wahoerft v1
        [2022-08-16T11:33:40+1200] [MainThread] [I] [cactus.shared.common] Running the command ['clip-vg', '/tmp/97c28d646d225cd782062204cf19e7dc/7bb0/d8ff/tmpazi_e8bd/4Sim.vg', '-f', '-e', 'NC_017518', '-o', '/tmp/97c28d646d225cd782062204cf19e7dc/7bb0/d8ff/tmpazi_e8bd/4Sim.vg.clip.bed', '-d', '_MINIGRAPH_', '-L']
        [2022-08-16T11:33:40+1200] [MainThread] [I] [toil-rt] 2022-08-16 11:33:40.715112: Running the command: "clip-vg /tmp/97c28d646d225cd782062204cf19e7dc/7bb0/d8ff/tmpazi_e8bd/4Sim.vg -f -e NC_017518 -o /tmp/97c28d646d225cd782062204cf19e7dc/7bb0/d8ff/tmpazi_e8bd/4Sim.vg.clip.bed -d _MINIGRAPH_ -L"
        [2022-08-16T11:33:40+1200] [MainThread] [W] [toil.fileStores.abstractFileStore] Failed job accessed files:
        [2022-08-16T11:33:40+1200] [MainThread] [W] [toil.fileStores.abstractFileStore] Downloaded file 'files/no-job/file-39c5b4bbcb64488cb478ec3400fac2bb/4Sim.vg' to path '/tmp/97c28d646d225cd782062204cf19e7dc/7bb0/d8ff/tmpazi_e8bd/4Sim.vg'
        Traceback (most recent call last):
          File "/usr/local/lib/python3.8/dist-packages/toil/worker.py", line 405, in workerScript
            job._runner(jobGraph=None, jobStore=jobStore, fileStore=fileStore, defer=defer)
          File "/usr/local/lib/python3.8/dist-packages/toil/job.py", line 2399, in _runner
            returnValues = self._run(jobGraph=None, fileStore=fileStore)
          File "/usr/local/lib/python3.8/dist-packages/toil/job.py", line 2317, in _run
            return self.run(fileStore)
          File "/usr/local/lib/python3.8/dist-packages/toil/job.py", line 2540, in run
            rValue = userFunction(*((self,) + tuple(self._args)), **self._kwargs)
          File "/usr/local/lib/python3.8/dist-packages/cactus/refmap/cactus_graphmap_join.py", line 343, in clip_vg
            cactus_call(parameters=cmd, outfile=clipped_path)
          File "/usr/local/lib/python3.8/dist-packages/cactus/shared/common.py", line 866, in cactus_call
            raise RuntimeError("Command {} exited {}: {}".format(call, process.returncode, out))
        RuntimeError: Command ['clip-vg', '/tmp/97c28d646d225cd782062204cf19e7dc/7bb0/d8ff/tmpazi_e8bd/4Sim.vg', '-f', '-e', 'NC_017518', '-o', '/tmp/97c28d646d225cd782062204cf19e7dc/7bb0/d8ff/tmpazi_e8bd/4Sim.vg.clip.bed', '-d', '_MINIGRAPH_', '-L'] exited 1: stdout=None, stderr=[clip-vg] error: Failed to fowardize node 36374 in path NC_017518.NC_017518

        [2022-08-16T11:33:40+1200] [MainThread] [E] [toil.worker] Exiting the worker because of a failed job on host kscprod-bio9
<=========
[2022-08-16T11:33:41+1200] [MainThread] [W] [toil.job] Due to failure we are reducing the remaining try count of job 'clip_vg' kind-clip_vg/instance-wahoerft v2 with ID kind-clip_vg/instance-wahoerft to 1
[2022-08-16T11:33:41+1200] [MainThread] [W] [toil.job] We have increased the default memory of the failed job 'clip_vg' kind-clip_vg/instance-wahoerft v2 to 2147483648 bytes
[2022-08-16T11:33:41+1200] [MainThread] [W] [toil.job] We have increased the disk of the failed job 'clip_vg' kind-clip_vg/instance-wahoerft v2 to the default of 2147483648 bytes
[2022-08-16T11:33:41+1200] [MainThread] [I] [toil.leader] Issued job 'clip_vg' kind-clip_vg/instance-wahoerft v3 with job batch system ID: 2 and cores: 1, disk: 2.0 Gi, and memory: 2.0 Gi
[2022-08-16T11:33:41+1200] [MainThread] [I] [toil.worker] Redirecting logging to /tmp/97c28d646d225cd782062204cf19e7dc/dea0/worker_log.txt
[2022-08-16T11:33:41+1200] [MainThread] [I] [toil-rt] 2022-08-16 11:33:41.960372: Running the command: "clip-vg /tmp/97c28d646d225cd782062204cf19e7dc/dea0/280a/tmpdp5dbx4p/4Sim.vg -f -e NC_017518 -o /tmp/97c28d646d225cd782062204cf19e7dc/dea0/280a/tmpdp5dbx4p/4Sim.vg.clip.bed -d _MINIGRAPH_ -L"
[2022-08-16T11:33:42+1200] [Thread-1  ] [E] [toil.batchSystems.singleMachine] Got exit code 1 (indicating failure) from job _toil_worker clip_vg file:/NGS/active/IPL/MENINGO/analysis/graph_genome/Minigraph-Cactus/4Sim/jobstore kind-clip_vg/instance-wahoerft.
[2022-08-16T11:33:42+1200] [MainThread] [W] [toil.leader] Job failed with exit value 1: 'clip_vg' kind-clip_vg/instance-wahoerft v3
Exit reason: None
[2022-08-16T11:33:42+1200] [MainThread] [W] [toil.leader] The job seems to have left a log file, indicating failure: 'clip_vg' kind-clip_vg/instance-wahoerft v5
[2022-08-16T11:33:42+1200] [MainThread] [W] [toil.leader] Log from job "kind-clip_vg/instance-wahoerft" follows:
=========>
        [2022-08-16T11:33:41+1200] [MainThread] [I] [toil.worker] ---TOIL WORKER OUTPUT LOG---
        [2022-08-16T11:33:41+1200] [MainThread] [I] [toil] Running Toil version 5.6.0-c34146a6437e4407a61e946e968bcce67a0ebbca on host kscprod-bio9.
        [2022-08-16T11:33:41+1200] [MainThread] [I] [toil.worker] Working on job 'clip_vg' kind-clip_vg/instance-wahoerft v4
        [2022-08-16T11:33:41+1200] [MainThread] [I] [toil.worker] Loaded body Job('clip_vg' kind-clip_vg/instance-wahoerft v4) from description 'clip_vg' kind-clip_vg/instance-wahoerft v4
        [2022-08-16T11:33:41+1200] [MainThread] [I] [cactus.shared.common] Running the command ['clip-vg', '/tmp/97c28d646d225cd782062204cf19e7dc/dea0/280a/tmpdp5dbx4p/4Sim.vg', '-f', '-e', 'NC_017518', '-o', '/tmp/97c28d646d225cd782062204cf19e7dc/dea0/280a/tmpdp5dbx4p/4Sim.vg.clip.bed', '-d', '_MINIGRAPH_', '-L']
        [2022-08-16T11:33:41+1200] [MainThread] [I] [toil-rt] 2022-08-16 11:33:41.960372: Running the command: "clip-vg /tmp/97c28d646d225cd782062204cf19e7dc/dea0/280a/tmpdp5dbx4p/4Sim.vg -f -e NC_017518 -o /tmp/97c28d646d225cd782062204cf19e7dc/dea0/280a/tmpdp5dbx4p/4Sim.vg.clip.bed -d _MINIGRAPH_ -L"
        [2022-08-16T11:33:42+1200] [MainThread] [W] [toil.fileStores.abstractFileStore] Failed job accessed files:
        [2022-08-16T11:33:42+1200] [MainThread] [W] [toil.fileStores.abstractFileStore] Downloaded file 'files/no-job/file-39c5b4bbcb64488cb478ec3400fac2bb/4Sim.vg' to path '/tmp/97c28d646d225cd782062204cf19e7dc/dea0/280a/tmpdp5dbx4p/4Sim.vg'
        Traceback (most recent call last):
          File "/usr/local/lib/python3.8/dist-packages/toil/worker.py", line 405, in workerScript
            job._runner(jobGraph=None, jobStore=jobStore, fileStore=fileStore, defer=defer)
          File "/usr/local/lib/python3.8/dist-packages/toil/job.py", line 2399, in _runner
            returnValues = self._run(jobGraph=None, fileStore=fileStore)
          File "/usr/local/lib/python3.8/dist-packages/toil/job.py", line 2317, in _run
            return self.run(fileStore)
          File "/usr/local/lib/python3.8/dist-packages/toil/job.py", line 2540, in run
            rValue = userFunction(*((self,) + tuple(self._args)), **self._kwargs)
          File "/usr/local/lib/python3.8/dist-packages/cactus/refmap/cactus_graphmap_join.py", line 343, in clip_vg
            cactus_call(parameters=cmd, outfile=clipped_path)
          File "/usr/local/lib/python3.8/dist-packages/cactus/shared/common.py", line 866, in cactus_call
            raise RuntimeError("Command {} exited {}: {}".format(call, process.returncode, out))
        RuntimeError: Command ['clip-vg', '/tmp/97c28d646d225cd782062204cf19e7dc/dea0/280a/tmpdp5dbx4p/4Sim.vg', '-f', '-e', 'NC_017518', '-o', '/tmp/97c28d646d225cd782062204cf19e7dc/dea0/280a/tmpdp5dbx4p/4Sim.vg.clip.bed', '-d', '_MINIGRAPH_', '-L'] exited 1: stdout=None, stderr=[clip-vg] error: Failed to fowardize node 36374 in path NC_017518.NC_017518

        [2022-08-16T11:33:42+1200] [MainThread] [E] [toil.worker] Exiting the worker because of a failed job on host kscprod-bio9
<=========
[2022-08-16T11:33:42+1200] [MainThread] [W] [toil.job] Due to failure we are reducing the remaining try count of job 'clip_vg' kind-clip_vg/instance-wahoerft v5 with ID kind-clip_vg/instance-wahoerft to 0
[2022-08-16T11:33:42+1200] [MainThread] [W] [toil.leader] Job 'clip_vg' kind-clip_vg/instance-wahoerft v6 is completely failed
[2022-08-16T11:33:47+1200] [MainThread] [I] [toil.leader] Finished toil run with 2 failed jobs.
[2022-08-16T11:33:47+1200] [MainThread] [I] [toil.leader] Failed jobs at end of the run: 'clip_vg' kind-clip_vg/instance-wahoerft v6 'Job' kind-graphmap_join_workflow/instance-eb0hozqi v3
[2022-08-16T11:33:47+1200] [MainThread] [I] [toil.realtimeLogger] Stopping real-time logging server.
[2022-08-16T11:33:47+1200] [MainThread] [I] [toil.realtimeLogger] Joining real-time logging server thread.
Traceback (most recent call last):
  File "/usr/local/bin/cactus-graphmap-join", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.8/dist-packages/cactus/refmap/cactus_graphmap_join.py", line 119, in main
    graphmap_join(options)
  File "/usr/local/lib/python3.8/dist-packages/cactus/refmap/cactus_graphmap_join.py", line 181, in graphmap_join
    wf_output = toil.start(Job.wrapJobFn(graphmap_join_workflow, options, config, vg_ids, hal_ids, unclip_seq_id_map, bed_ids))
  File "/usr/local/lib/python3.8/dist-packages/toil/common.py", line 951, in start
    return self._runMainLoop(rootJobDescription)
  File "/usr/local/lib/python3.8/dist-packages/toil/common.py", line 1273, in _runMainLoop
    return Leader(config=self.config,
  File "/usr/local/lib/python3.8/dist-packages/toil/leader.py", line 289, in run
    raise FailedJobsException(self.jobStore, failed_jobs, exit_code=self.recommended_fail_exit_code)
toil.leader.FailedJobsException: The job store '/NGS/active/IPL/MENINGO/analysis/graph_genome/Minigraph-Cactus/4Sim/jobstore' contains 2 failed jobs: 'clip_vg' kind-clip_vg/instance-wahoerft v6, 'Job' kind-graphmap_join_workflow/instance-eb0hozqi v3
Log from job "'clip_vg' kind-clip_vg/instance-wahoerft v6" follows:
=========>
        [2022-08-16T11:33:41+1200] [MainThread] [I] [toil.worker] ---TOIL WORKER OUTPUT LOG---
        [2022-08-16T11:33:41+1200] [MainThread] [I] [toil] Running Toil version 5.6.0-c34146a6437e4407a61e946e968bcce67a0ebbca on host kscprod-bio9.
        [2022-08-16T11:33:41+1200] [MainThread] [I] [toil.worker] Working on job 'clip_vg' kind-clip_vg/instance-wahoerft v4
        [2022-08-16T11:33:41+1200] [MainThread] [I] [toil.worker] Loaded body Job('clip_vg' kind-clip_vg/instance-wahoerft v4) from description 'clip_vg' kind-clip_vg/instance-wahoerft v4
        [2022-08-16T11:33:41+1200] [MainThread] [I] [cactus.shared.common] Running the command ['clip-vg', '/tmp/97c28d646d225cd782062204cf19e7dc/dea0/280a/tmpdp5dbx4p/4Sim.vg', '-f', '-e', 'NC_017518', '-o', '/tmp/97c28d646d225cd782062204cf19e7dc/dea0/280a/tmpdp5dbx4p/4Sim.vg.clip.bed', '-d', '_MINIGRAPH_', '-L']
        [2022-08-16T11:33:41+1200] [MainThread] [I] [toil-rt] 2022-08-16 11:33:41.960372: Running the command: "clip-vg /tmp/97c28d646d225cd782062204cf19e7dc/dea0/280a/tmpdp5dbx4p/4Sim.vg -f -e NC_017518 -o /tmp/97c28d646d225cd782062204cf19e7dc/dea0/280a/tmpdp5dbx4p/4Sim.vg.clip.bed -d _MINIGRAPH_ -L"
        [2022-08-16T11:33:42+1200] [MainThread] [W] [toil.fileStores.abstractFileStore] Failed job accessed files:
        [2022-08-16T11:33:42+1200] [MainThread] [W] [toil.fileStores.abstractFileStore] Downloaded file 'files/no-job/file-39c5b4bbcb64488cb478ec3400fac2bb/4Sim.vg' to path '/tmp/97c28d646d225cd782062204cf19e7dc/dea0/280a/tmpdp5dbx4p/4Sim.vg'
        Traceback (most recent call last):
          File "/usr/local/lib/python3.8/dist-packages/toil/worker.py", line 405, in workerScript
            job._runner(jobGraph=None, jobStore=jobStore, fileStore=fileStore, defer=defer)
          File "/usr/local/lib/python3.8/dist-packages/toil/job.py", line 2399, in _runner
            returnValues = self._run(jobGraph=None, fileStore=fileStore)
          File "/usr/local/lib/python3.8/dist-packages/toil/job.py", line 2317, in _run
            return self.run(fileStore)
          File "/usr/local/lib/python3.8/dist-packages/toil/job.py", line 2540, in run
            rValue = userFunction(*((self,) + tuple(self._args)), **self._kwargs)
          File "/usr/local/lib/python3.8/dist-packages/cactus/refmap/cactus_graphmap_join.py", line 343, in clip_vg
            cactus_call(parameters=cmd, outfile=clipped_path)
          File "/usr/local/lib/python3.8/dist-packages/cactus/shared/common.py", line 866, in cactus_call
            raise RuntimeError("Command {} exited {}: {}".format(call, process.returncode, out))
        RuntimeError: Command ['clip-vg', '/tmp/97c28d646d225cd782062204cf19e7dc/dea0/280a/tmpdp5dbx4p/4Sim.vg', '-f', '-e', 'NC_017518', '-o', '/tmp/97c28d646d225cd782062204cf19e7dc/dea0/280a/tmpdp5dbx4p/4Sim.vg.clip.bed', '-d', '_MINIGRAPH_', '-L'] exited 1: stdout=None, stderr=[clip-vg] error: Failed to fowardize node 36374 in path NC_017518.NC_017518

        [2022-08-16T11:33:42+1200] [MainThread] [E] [toil.worker] Exiting the worker because of a failed job on host kscprod-bio9

Could you please help me to have a look what cause this error? 

Many thanks

**Comment by ZoeYang2020** [comment]
I have tested it with different data, and it worked. I guess there is some problem to create index and vg graph if there is big inversion in the dataset. 
What I have is a Neisseria meningitidis genome, I mutated the genome (~3k, 4k and 5k)SNPs, and further 200 indel, and then 2 big inversion for each of the simulated genomes  by simuG. 
With the original genome as a reference, the minigraph-cactus didn't work of the last step for  above genomes that contain inversion. 
Then I went back one step, and test the pipeline using genomes that don't have the inversion, and it worked properly to the last step. so I guess there is something wrong or maybe a bug that is hard to dealing with the big inversions. 

I have uploaded my data and script to the https://github.com/ZoeYang2020/Pangenome-graph-for-bacterial-pathogens
NC_017518, is the original genome
genomes with sim at the end of their name are the simulated genomes with SNPs, indels and inversions. 
genomes with Sim1 at the end of their names are the simulated genomes with SNPs and indels, but no inversions. 

[4Sim_retry_minigraph.sh](https://github.com/ZoeYang2020/Pangenome-graph-for-bacterial-pathogens/blob/main/4Sim_retry_minigraph.sh) is the script that I run the dataset without inversions, which worked properly. 
[4Sim_retry2_minigraph.sh](https://github.com/ZoeYang2020/Pangenome-graph-for-bacterial-pathogens/blob/main/4Sim_retry2_minigraph.sh) is the script that I run the dataset (one genome includes inversion), which failed at the last step of generate the vg index things. 
 

If you can help me to test the dataset with inversion, that would be great to see if we can fix it. 

Thank you very much,
Zoe

**Comment by glennhickey** [comment]
Hi, thanks for making this easy to reproduce.  This is indeed a bug.  And a very dumb one at that.  The problem is that the name of your reference `NC_017518` is a prefix of another sample in your input `NC_017518sim`.  `clip-vg` only takes in prefixes so it tries to forwardize both paths which is impossible.

In other words, if the reference sample is a prefix of any other sample names, the pipeline may fail (in the presence of inversions) in this step.  

I will fix it in a later release, but in the meantime you can work around it by renaming    `NC_017518sim` to something that doesn't start with ` `NC_017518`.
