### ISSUE TITLE
RuntimeError

### ISSUE THREAD

**Issue by hcsun1** [ComparativeGenomicsToolkit/cactus#778]
Hello,
I am testing the Minigraph-cactus pipeline. The program reported an erro, but it is still running.

[2022-08-28T03:02:11-0400] [MainThread] [I] [toil.worker] ---TOIL WORKER OUTPUT LOG---
	[2022-08-28T03:02:11-0400] [MainThread] [I] [toil] Running Toil version 5.6.0-c34146a6437e4407a61e946e968bcce67a0ebbca on host localhost.localdomain.
	[2022-08-28T03:02:11-0400] [MainThread] [I] [toil.worker] Working on job 'minigraph_map_one' kind-minigraph_map_one/instance-au9e7_xg v4
	[2022-08-28T03:02:12-0400] [MainThread] [I] [toil.worker] Loaded body Job('minigraph_map_one' kind-minigraph_map_one/instance-au9e7_xg v4) from description 'minigraph_map_one' kind-minigraph_map_one/instance-au9e7_xg v4
	[2022-08-28T03:02:16-0400] [MainThread] [I] [cactus.shared.common] Running the command ['bash', '-c', 'set -eo pipefail && minigraph /data/lilab/sywang1/dierpian/cactus-minigraph/test/tmp/372a0faa6de85410b97705d9dbbb1c0d/ae47/6aa5/tmpzu_oxrvj/mg.gfa /data/lilab/sywang1/dierpian/cactus-minigraph/test/tmp/372a0faa6de85410b97705d9dbbb1c0d/ae47/6aa5/tmpzu_oxrvj/Gala_A.fa -o /data/lilab/sywang1/dierpian/cactus-minigraph/test/tmp/372a0faa6de85410b97705d9dbbb1c0d/ae47/6aa5/tmpzu_oxrvj/M_domestica-Gala.1.gaf -c -xasm -t 16']
	[2022-08-28T03:02:16-0400] [MainThread] [I] [toil-rt] 2022-08-28 03:02:16.599987: Running the command: "bash -c set -eo pipefail && minigraph /data/lilab/sywang1/dierpian/cactus-minigraph/test/tmp/372a0faa6de85410b97705d9dbbb1c0d/ae47/6aa5/tmpzu_oxrvj/mg.gfa /data/lilab/sywang1/dierpian/cactus-minigraph/test/tmp/372a0faa6de85410b97705d9dbbb1c0d/ae47/6aa5/tmpzu_oxrvj/Gala_A.fa -o /data/lilab/sywang1/dierpian/cactus-minigraph/test/tmp/372a0faa6de85410b97705d9dbbb1c0d/ae47/6aa5/tmpzu_oxrvj/M_domestica-Gala.1.gaf -c -xasm -t 16"
	[2022-08-28T03:19:47-0400] [MainThread] [W] [toil.fileStores.abstractFileStore] Failed job accessed files:
	[2022-08-28T03:19:47-0400] [MainThread] [W] [toil.fileStores.abstractFileStore] Downloaded file 'files/no-job/file-5387362b285d453c81ec2283a96d0107/Huahong-purged-new.phased-pan.36.gfa' to path '/data/lilab/sywang1/dierpian/cactus-minigraph/test/tmp/372a0faa6de85410b97705d9dbbb1c0d/ae47/6aa5/tmpzu_oxrvj/mg.gfa'
	[2022-08-28T03:19:47-0400] [MainThread] [W] [toil.fileStores.abstractFileStore] Downloaded file 'files/no-job/file-a3632d34626747aea6b97a5cda162ea2/Gala_A.fa' to path '/data/lilab/sywang1/dierpian/cactus-minigraph/test/tmp/372a0faa6de85410b97705d9dbbb1c0d/ae47/6aa5/tmp84qus307/Gala_A.fa'
	Traceback (most recent call last):
	  File "/data/lilab/hcsun1/Software/cactus-bin-v2.1.1/cactus_env/lib/python3.8/site-packages/toil/worker.py", line 405, in workerScript
	    job._runner(jobGraph=None, jobStore=jobStore, fileStore=fileStore, defer=defer)
	  File "/data/lilab/hcsun1/Software/cactus-bin-v2.1.1/cactus_env/lib/python3.8/site-packages/toil/job.py", line 2399, in _runner
	    returnValues = self._run(jobGraph=None, fileStore=fileStore)
	  File "/data/lilab/hcsun1/Software/cactus-bin-v2.1.1/cactus_env/lib/python3.8/site-packages/toil/job.py", line 2317, in _run
	    return self.run(fileStore)
	  File "/data/lilab/hcsun1/Software/cactus-bin-v2.1.1/cactus_env/lib/python3.8/site-packages/toil/job.py", line 2540, in run
	    rValue = userFunction(*((self,) + tuple(self._args)), **self._kwargs)
	  File "/data/lilab/hcsun1/Software/cactus-bin-v2.1.1/cactus_env/lib/python3.8/site-packages/cactus/refmap/cactus_graphmap.py", line 359, in minigraph_map_one
	    cactus_call(parameters=cmd)
	  File "/data/lilab/hcsun1/Software/cactus-bin-v2.1.1/cactus_env/lib/python3.8/site-packages/cactus/shared/common.py", line 868, in cactus_call
	    raise RuntimeError("Command {} signaled {}: {}".format(call, signal.Signals(-process.returncode).name, out))
	RuntimeError: Command ['bash', '-c', 'set -eo pipefail && minigraph /data/lilab/sywang1/dierpian/cactus-minigraph/test/tmp/372a0faa6de85410b97705d9dbbb1c0d/ae47/6aa5/tmpzu_oxrvj/mg.gfa /data/lilab/sywang1/dierpian/cactus-minigraph/test/tmp/372a0faa6de85410b97705d9dbbb1c0d/ae47/6aa5/tmpzu_oxrvj/Gala_A.fa -o /data/lilab/sywang1/dierpian/cactus-minigraph/test/tmp/372a0faa6de85410b97705d9dbbb1c0d/ae47/6aa5/tmpzu_oxrvj/M_domestica-Gala.1.gaf -c -xasm -t 16'] signaled SIGKILL: stdout=None, stderr=[M::main::36.159*0.96] loaded the graph from "/data/lilab/sywang1/dierpian/cactus-minigraph/test/tmp/372a0faa6de85410b97705d9dbbb1c0d/ae47/6aa5/tmpzu_oxrvj/mg.gfa"
	[M::mg_index::294.872*1.22] indexed the graph
	[M::mg_opt_update::303.279*1.21] occ_max1=100; lc_max_occ=4
	
	[2022-08-28T03:19:48-0400] [MainThread] [E] [toil.worker] Exiting the worker because of a failed job on host localhost.localdomain

Thank you.

**Comment by glennhickey** [comment]
`SIGKILL` usually happens when exceeding some kind of system-specified memory limit.  A few more details here: https://github.com/ComparativeGenomicsToolkit/cactus/issues/231#issuecomment-624902182

One thing you may try is to increase the number of cores with `--mapCores` to run fewer minigraph mapping jobs in parallel, thus reducing peak memory usage.

**Comment by hcsun1** [comment]
Thank you for your answet.Below is my commond:

**Comment by hcsun1** [comment]
Thank you for your answer.Below is my commond:

source /data/lilab/hcsun1/Software/cactus-bin-v2.1.1/cactus_env/bin/activate
export TMPDIR=/data/lilab/sywang1/cactus-minigraph/test/tmp

cactus-graphmap ./jobstore ./accessions.txt phased-pan.36.gfa ./accessions.paf  --realTimeLogging --reference M_F --outputFasta ./accessions.gfa.fa --mapCores 16

And the ./accessions.txt file have 63 geomes.

Thank you.

**Comment by hcsun1** [comment]
I had run cactus-graphmap again with --mapCores 60, but it still reported this erro.

**Comment by hcsun1** [comment]
I had run cactus-graphmap again with --mapCores 60, but it still reported this erro.

**Comment by glennhickey** [comment]
It seems you don't have enough memory to run minigraph on this data on this system?  Unfortunately, I'm not sure there's much more I can do to help.

**Comment by hcsun1** [comment]
Hello 

I encountered another problem.
I have completed cactus-graphmap-join. Below is my command, but the vcf file has not validated variation information.It only has index and partly header information about #.

source /public/home/2017094/hcsun/software/cactus-bin-v2.1.1/cactus_env/bin/activate
export TMPDIR=/public/home/2017094/liar/cactus/tmp
/public/home/2017094/hcsun/software/cactus-bin-v2.1.1/cactus_env/bin/cactus-graphmap-join ./jobstore --vg ./accessions.vg --outDir ./tmp --outName accessions-index --reference M_F --vcf --giraffe --gfaffix  --wlineSep "." --realTimeLogging --clipLength 100000 --clipNonMinigraph

#CHROM  POS     ID      REF     ALT     QUAL    FILTER  INFO    FORMAT  M_F

Thank you

**Comment by glennhickey** [comment]
The VCF output is very dependent on the naming scheme desribed here:
https://github.com/ComparativeGenomicsToolkit/cactus/blob/master/doc/pangenome.md#evolver-primates-preprocessing-and-naming
meaning that all non-reference samples should have a ".0" suffix (assuming they are haploid).

**Comment by hcsun1** [comment]
Below is my partial samples id,but the VCF file have not these ID and varatiion information .

M_F      ./F_Chr_genome.fa
M_zm.1        ./Zm.ccs.asm.hic.hap1.p_ctg.fa
M_zm.2        ./Zm.ccs.asm.hic.hap2.p_ctg.fa
M_f.1       ./He.ccs.asm.hic.hap1.p_ctg.fa
M_f.2       ./He.ccs.asm.hic.hap1.p_ctg.fa
...
...

**Comment by glennhickey** [comment]
The names and command line look perfectly fine.  Have you looked at the other output (xg, gfa, gbwt) to see if they are empty too?  If you can share any of this data, I can take a look.  The ideal would be the .xg, .trans and .gbwt output of cactus-graphmap-join.  If it's too big, maybe we can reproduce on a small subset of the data?

**Comment by hcsun1** [comment]
I have tested a small subset of the data.This is VCF output. Is this the correct result?

[accessions-index.test.zip](https://github.com/ComparativeGenomicsToolkit/cactus/files/9573699/accessions-index.test.zip)

M_F is my reference genome. 

M_F        ../F_Chr_genome.fa
M_F.1      ../F_phased_hap1.chr.fa
M_F.2      ../F_phased_hap2.chr.fa
M_o.1  ../Dongfang.ccs.asm.hic.hap1.p_ctg.fa
M_o.2  ../Dongfang.ccs.asm.hic.hap2.p_ctg.fa
M_s.1   ../Ms_A.fa
M_s.2   ../Ms_B.fa

**Comment by hcsun1** [comment]
Please help me. Is this the correct result?
