### ISSUE TITLE
Termination with signal 9 in cactus consolidated

### ISSUE THREAD

**Issue by Tkastylevsky** [ComparativeGenomicsToolkit/cactus#779]
Hello, 
I've successfully ran the test dataset of cactus on my setup, using the GPU-accelerated version. I then attempted to align two mammalian-sized genomes on this configuration along with the GPU: 8 CPU, 128Go RAM, 1To HDD (which, I know, is inferior to the one you are using, but I would expect that it would just make the runtime longer since the amount of RAM is similar ?). All the first steps work just fine but then it crashes (repeatedly, I've attempted it twice now, along with the automatic retries that cactus does), with a termination with signal 9. I've tried simplifying my fasta headers but it didn't help.

`        [2022-08-31T23:41:16+0000] [MainThread] [I] [toil.worker] ---TOIL WORKER OUTPUT LOG---
        [2022-08-31T23:41:16+0000] [MainThread] [I] [toil] Running Toil version 5.6.0-c34146a6437e4407a61e946e968bcce67a0ebbca on host dd7de6dba2db.
        [2022-08-31T23:41:16+0000] [MainThread] [I] [toil.worker] Working on job 'cactus_cons' kind-cactus_cons/instance-ggnjaif6 v1
        [2022-08-31T23:41:16+0000] [MainThread] [I] [toil.worker] Loaded body Job('cactus_cons' kind-cactus_cons/instance-ggnjaif6 v1) from description 'cactus_cons' kind-cactus_cons/instance-ggnjaif6 v1
        [2022-08-31T23:41:17+0000] [MainThread] [W] [toil.statsAndLogging] Deprecated toil method that will be moved/replaced in a future release."
        [2022-08-31T23:41:19+0000] [MainThread] [W] [toil.statsAndLogging] Deprecated toil method that will be moved/replaced in a future release."
        [2022-08-31T23:41:24+0000] [MainThread] [W] [root] Deprecated toil method.  Please call "logging.getLevelName" directly.
        [2022-08-31T23:41:24+0000] [MainThread] [I] [cactus.shared.common] Running the command ['cactus_consolidated', '--sequences', 'Mus_musculus /tmp/0ba9b734123b536090976801d11e06bb/2ac2/93e1/tmpoh1_oy3v/Mus_musculus.fa Rattus_norvegicus /tmp/0ba9b734123b536090976801d11e06bb/2ac2/93e1/tmpoh1_oy3v/Rattus_norvegicus.fa', '--speciesTree', '(Mus_musculus:1.0,Rattus_norvegicus:1.0)Anc0;', '--logLevel', 'INFO', '--alignments', '/tmp/0ba9b734123b536090976801d11e06bb/2ac2/93e1/tmpoh1_oy3v/Anc0_primary.paf', '--params', '/tmp/0ba9b734123b536090976801d11e06bb/2ac2/93e1/tmpoh1_oy3v/Anc0.config.xml', '--outputFile', '/tmp/0ba9b734123b536090976801d11e06bb/2ac2/93e1/tmpoh1_oy3v/Anc0.c2h', '--outputHalFastaFile', '/tmp/0ba9b734123b536090976801d11e06bb/2ac2/93e1/tmpoh1_oy3v/Anc0.c2h.fa', '--outputReferenceFile', '/tmp/0ba9b734123b536090976801d11e06bb/2ac2/93e1/tmpoh1_oy3v/Anc0.ref', '--outgroupEvents', '', '--referenceEvent', 'Anc0', '--threads', '8', '--secondaryAlignments', '/tmp/0ba9b734123b536090976801d11e06bb/2ac2/93e1/tmpoh1_oy3v/Anc0_secondary.paf']
        [2022-09-01T06:59:26+0000] [MainThread] [W] [toil.fileStores.abstractFileStore] Failed job accessed files:
        [2022-09-01T06:59:26+0000] [MainThread] [W] [toil.fileStores.abstractFileStore] Downloaded file 'files/for-job/kind-LastzRepeatMaskJob/instance-oocx2224/file-6083647f353d49a38d5a0cd3b069767e/tmpcddzfiqo.tmp' to path '/tmp/0ba9b734123b536090976801d11e06bb/2ac2/93e1/tmpoh1_oy3v/Mus_musculus.fa'   
        [2022-09-01T06:59:26+0000] [MainThread] [W] [toil.fileStores.abstractFileStore] Downloaded file 'files/for-job/kind-LastzRepeatMaskJob/instance-bwrhuybv/file-9a5f8b8b32284aea8fe2fde31f4a8c21/tmp5f9br88y.tmp' to path '/tmp/0ba9b734123b536090976801d11e06bb/2ac2/93e1/tmpoh1_oy3v/Rattus_norvegicus.fa'
        [2022-09-01T06:59:26+0000] [MainThread] [W] [toil.fileStores.abstractFileStore] Downloaded file 'files/for-job/kind-trim_unaligned_sequences/instance-xpqk10dw/file-690c1a6f3d4149c7923b8b6b9ea8b76a/tmp8uzxfm_p.tmp' to path '/tmp/0ba9b734123b536090976801d11e06bb/2ac2/93e1/tmpoh1_oy3v/Anc0.paf'
        Traceback (most recent call last):
          File "/home/cactus/cactus_env/lib/python3.8/site-packages/toil/worker.py", line 405, in workerScript
            job._runner(jobGraph=None, jobStore=jobStore, fileStore=fileStore, defer=defer)
          File "/home/cactus/cactus_env/lib/python3.8/site-packages/toil/job.py", line 2399, in _runner
            returnValues = self._run(jobGraph=None, fileStore=fileStore)
          File "/home/cactus/cactus_env/lib/python3.8/site-packages/toil/job.py", line 2317, in _run
            return self.run(fileStore)
          File "/home/cactus/cactus_env/lib/python3.8/site-packages/toil/job.py", line 2540, in run
            rValue = userFunction(*((self,) + tuple(self._args)), **self._kwargs)
          File "/home/cactus/cactus_env/lib/python3.8/site-packages/cactus/pipeline/cactus_workflow.py", line 93, in cactus_cons
            messages = cactus_call(check_output=True, returnStdErr=True,
          File "/home/cactus/cactus_env/lib/python3.8/site-packages/cactus/shared/common.py", line 789, in cactus_call
            raise RuntimeError("{}Command {} exited {}: {}".format(sigill_msg, call, process.returncode, out))
        RuntimeError: Command /usr/bin/time -v cactus_consolidated --sequences 'Mus_musculus /tmp/0ba9b734123b536090976801d11e06bb/2ac2/93e1/tmpoh1_oy3v/Mus_musculus.fa Rattus_norvegicus /tmp/0ba9b734123b536090976801d11e06bb/2ac2/93e1/tmpoh1_oy3v/Rattus_norvegicus.fa' --speciesTree '(Mus_musculus:1.0,Rattus_norvegicus:1.0)Anc0;' --logLevel INFO --alignments /tmp/0ba9b734123b536090976801d11e06bb/2ac2/93e1/tmpoh1_oy3v/Anc0_primary.paf --params /tmp/0ba9b734123b536090976801d11e06bb/2ac2/93e1/tmpoh1_oy3v/Anc0.config.xml --outputFile /tmp/0ba9b734123b536090976801d11e06bb/2ac2/93e1/tmpoh1_oy3v/Anc0.c2h --outputHalFastaFile /tmp/0ba9b734123b536090976801d11e06bb/2ac2/93e1/tmpoh1_oy3v/Anc0.c2h.fa --outputReferenceFile /tmp/0ba9b734123b536090976801d11e06bb/2ac2/93e1/tmpoh1_oy3v/Anc0.ref --outgroupEvents '' --referenceEvent Anc0 --threads 8 --secondaryAlignments /tmp/0ba9b734123b536090976801d11e06bb/2ac2/93e1/tmpoh1_oy3v/Anc0_secondary.paf exited 137: stdout=, stderr=Params file: /tmp/0ba9b734123b536090976801d11e06bb/2ac2/93e1/tmpoh1_oy3v/Anc0.config.xml
        Output file string : /tmp/0ba9b734123b536090976801d11e06bb/2ac2/93e1/tmpoh1_oy3v/Anc0.c2h
        Output hal fasta file string : /tmp/0ba9b734123b536090976801d11e06bb/2ac2/93e1/tmpoh1_oy3v/Anc0.c2h.fa
        Output reference fasta file string : /tmp/0ba9b734123b536090976801d11e06bb/2ac2/93e1/tmpoh1_oy3v/Anc0.ref
        Sequence files and events: Mus_musculus /tmp/0ba9b734123b536090976801d11e06bb/2ac2/93e1/tmpoh1_oy3v/Mus_musculus.fa Rattus_norvegicus /tmp/0ba9b734123b536090976801d11e06bb/2ac2/93e1/tmpoh1_oy3v/Rattus_norvegicus.fa
        Alignments file: /tmp/0ba9b734123b536090976801d11e06bb/2ac2/93e1/tmpoh1_oy3v/Anc0_primary.paf
        Secondary alignments file: /tmp/0ba9b734123b536090976801d11e06bb/2ac2/93e1/tmpoh1_oy3v/Anc0_secondary.paf
Constraint alignments file: (null)
        Species tree: (Mus_musculus:1.0,Rattus_norvegicus:1.0)Anc0;
        Outgroup events:
        Reference event: Anc0
        Loaded the parameters files, 0 seconds have elapsed
        Set up the cactus disk, 0 seconds have elapsed
        Constructed the first flower
        Going to build the event tree with newick string: (Mus_musculus:1.0,Rattus_norvegicus:1.0)Anc0;
        Parsed the tree
        Constructed the basic event tree
        Assigning sequence /tmp/0ba9b734123b536090976801d11e06bb/2ac2/93e1/tmpoh1_oy3v/Mus_musculus.fa to Mus_musculus
        Processing file: /tmp/0ba9b734123b536090976801d11e06bb/2ac2/93e1/tmpoh1_oy3v/Mus_musculus.fa
        The file /tmp/0ba9b734123b536090976801d11e06bb/2ac2/93e1/tmpoh1_oy3v/Mus_musculus.fa is specified incomplete, the sequences will not be attached
        Assigning sequence /tmp/0ba9b734123b536090976801d11e06bb/2ac2/93e1/tmpoh1_oy3v/Rattus_norvegicus.fa to Rattus_norvegicus
        Processing file: /tmp/0ba9b734123b536090976801d11e06bb/2ac2/93e1/tmpoh1_oy3v/Rattus_norvegicus.fa
        The file /tmp/0ba9b734123b536090976801d11e06bb/2ac2/93e1/tmpoh1_oy3v/Rattus_norvegicus.fa is specified incomplete, the sequences will not be attached
        Constructed the initial flower with 237 sequences and 4 events with string: ((Mus_musculus:1,Rattus_norvegicus:1)Anc0:9.22337e+18)ROOT:9.22337e+18; 
        Established the first Flower in the hierarchy, 38 seconds have elapsed
        Converted alignment coordinates, 173 seconds have elapsed
        Stripped any unique IDs, 173 seconds have elapsed
        Starting annealing round with a minimum chain length of 64 and an alignment trim of 3
        Sequence graph statistics after annealing:
        There were 56654154 blocks in the sequence graph, representing 3448335574 total aligned bases
        Block degree stats: min 1, avg 3.741312, median 2, max 25221
        Block support stats: min 0.000000, avg 0.694141, median 1.000000, max 2.000000
        Starting melting round with a minimum chain length of 2
        A melting round is destroying 8715123 blocks with an average degree of 5.701435 from chains with length less than 2. Total aligned bases lost: 49688705
        Starting melting round with a minimum chain length of 4
        A melting round is destroying 7598530 blocks with an average degree of 4.605120 from chains with length less than 4. Total aligned bases lost: 82322856
        Starting melting round with a minimum chain length of 8
        A melting round is destroying 6952931 blocks with an average degree of 3.584111 from chains with length less than 8. Total aligned bases lost: 126665014
        A melting round is destroying 4784236 blocks with an average degree of 3.218468 from chains with length less than 64. Total aligned bases lost: 173246825
        Destroying 278833 recoverable blocks
        The blocks covered 8786575 columns for a total of 32983816 aligned bases
        Destroying 9472 recoverable blocks
        The blocks covered 317198 columns for a total of 1552993 aligned bases
        Destroying 218 recoverable blocks
        The blocks covered 7273 columns for a total of 47886 aligned bases
        Destroying 17 recoverable blocks
        The blocks covered 646 columns for a total of 3437 aligned bases
        Destroying 6 recoverable blocks
        The blocks covered 173 columns for a total of 1099 aligned bases
        Destroying 0 recoverable blocks
        The blocks covered 0 columns for a total of 0 aligned bases
        Sequence graph statistics after melting:
        There were 22379269 blocks in the sequence graph, representing 2401315351 total aligned bases
        Block degree stats: min 1, avg 2.064778, median 2, max 24
        Block support stats: min 0.000000, avg 0.975642, median 1.000000, max 1.000000
        Pinch graph component with 206115 nodes and 220615 edges is being split up by breaking 9804 edges to reduce size to less than 880 max, but found 31 pointless edges
        Ran cactus caf, 13674 seconds have elapsed
        Ran extended flowers ready for bar, 14057 seconds have elapsed
        Ran cactus bar (use poa:1), 21794 seconds have elapsed
        There are 10 layers in the flowers hierarchy
        In the 0 layer there are 1 flowers in the flowers hierarchy
        In the 1 layer there are 21579162 flowers in the flowers hierarchy
        In the 2 layer there are 2402463 flowers in the flowers hierarchy
        In the 3 layer there are 471493 flowers in the flowers hierarchy
        In the 4 layer there are 35916 flowers in the flowers hierarchy
        In the 5 layer there are 2828 flowers in the flowers hierarchy
        In the 6 layer there are 475 flowers in the flowers hierarchy
        In the 7 layer there are 54 flowers in the flowers hierarchy
        In the 8 layer there are 8 flowers in the flowers hierarchy
        In the 9 layer there are 1 flowers in the flowers hierarchy
        Ran cactus make reference, 24774 seconds have elapsed
        Ran cactus make reference bottom up coordinates, 25667 seconds have elapsed
        Ran cactus make reference top down coordinates, 25781 seconds have elapsed
        Command terminated by signal 9
                Command being timed: "cactus_consolidated --sequences Mus_musculus /tmp/0ba9b734123b536090976801d11e06bb/2ac2/93e1/tmpoh1_oy3v/Mus_musculus.fa Rattus_norvegicus /tmp/0ba9b734123b536090976801d11e06bb/2ac2/93e1/tmpoh1_oy3v/Rattus_norvegicus.fa --speciesTree (Mus_musculus:1.0,Rattus_norvegicus:1.0)Anc0; --logLevel INFO --alignments /tmp/0ba9b734123b536090976801d11e06bb/2ac2/93e1/tmpoh1_oy3v/Anc0_primary.paf --params /tmp/0ba9b734123b536090976801d11e06bb/2ac2/93e1/tmpoh1_oy3v/Anc0.config.xml --outputFile /tmp/0ba9b734123b536090976801d11e06bb/2ac2/93e1/tmpoh1_oy3v/Anc0.c2h --outputHalFastaFile /tmp/0ba9b734123b536090976801d11e06bb/2ac2/93e1/tmpoh1_oy3v/Anc0.c2h.fa --outputReferenceFile /tmp/0ba9b734123b536090976801d11e06bb/2ac2/93e1/tmpoh1_oy3v/Anc0.ref --outgroupEvents  --referenceEvent Anc0 --threads 8 --secondaryAlignments /tmp/0ba9b734123b536090976801d11e06bb/2ac2/93e1/tmpoh1_oy3v/Anc0_secondary.paf"
                User time (seconds): 51578.13
                System time (seconds): 20628.53
                Percent of CPU this job got: 274%
                Elapsed (wall clock) time (h:mm:ss or m:ss): 7:18:01
                Average shared text size (kbytes): 0
                Average unshared data size (kbytes): 0
                Average stack size (kbytes): 0
                Average total size (kbytes): 0
                Maximum resident set size (kbytes): 130591296
                Average resident set size (kbytes): 0
                Major (requiring I/O) page faults: 288
                Minor (reclaiming a frame) page faults: 112942808
                Voluntary context switches: 64503822
                Involuntary context switches: 1287165
                Swaps: 0
                File system inputs: 60248
                File system outputs: 4801264
                Socket messages sent: 0
                Socket messages received: 0
                Signals delivered: 0
                Page size (bytes): 4096
                Exit status: 0

        [2022-09-01T06:59:27+0000] [MainThread] [E] [toil.worker] Exiting the worker because of a failed job on host dd7de6dba2db
`
Any idea what I could change to make it work ? 
Thanks in advance,

**Comment by Tkastylevsky** [comment]
Looking at other issues It seems that it's just a thread number problem, sorry for the inconvenience.
