### ISSUE TITLE
DeadlockException being thrown prematurely

### ISSUE THREAD

**Issue by lparsons** [ComparativeGenomicsToolkit/cactus#78]
I can somewhat frequently run into a `DeadlockException` when running cactus jobs. It seems to occur at different points in the workflow, even when running one the exact same data.

I've noticed that cactus is often reporting in the log that jobs are submitted, but toil has yet to actually submit them into the cluster's queue. I regularly see cactus a few hundred jobs "ahead" of what is in the slurm queue. 

One theory I have (admittedly, not substantiated yet) is that sometimes, cactus checks for a deadlock situation at a moment when there are a number of jobs cactus has submitted, but that are not yet in the slurm queue. It sees that only Service jobs are running and throws this exception. When I see this happen, it's often during `CactusReferenceWrapper` stages where there are hundreds or even thousands of jobs, but they are very quick to run, meaning that there are times with 10-20 jobs in the queue followed by periods with no jobs in the queue as toil tries to "catch up".

**Comment by lparsons** [comment]
I just ran into this again, and this time I caught the system with a number of jobs issues by cactus, but not yet in the slurm queue and a number of jobs in the slurm queue, but not yet running and still got the DeadlockException.

@joelarmstrong This seems to be an issue with toil's slurm handing... Any tips on where I might poke around to fix it? I'm happy to submit a PR, but I'm not sure where to start at the moment.

Most recent log message from cactus regarding submitted jobs:
```
INFO:toil.leader:Issued job 'CactusReferenceRecursion2' V/G/jobkNS6oh with job batch system ID: 514 and cores: 1, disk: 2.0 G, and memory: 9.4 G
```

Slurm queue shortly after Deadlock Exception:
```
             JOBID PARTITION                           NAME     USER ST  NODES  CPUS MIN_MEMORY       TIME     NODELIST(REASON)         PRIORITY          SUBMIT_TIME           START_TIME  TIME_LEFT        QOS
          23526506       all                   toil_job_427 lparsons PD      1     1       700M       0:00           (Priority)             4229  2019-05-06T16:28:19                  N/A 1-00:00:00      short
          23526507       all                   toil_job_428 lparsons PD      1     1       700M       0:00           (Priority)             4229  2019-05-06T16:28:19                  N/A 1-00:00:00      short
          23526509       all                   toil_job_429 lparsons PD      1     1       700M       0:00           (Priority)             4229  2019-05-06T16:28:20                  N/A 1-00:00:00      short
          23526510       all                   toil_job_430 lparsons PD      1     1       700M       0:00           (Priority)             4229  2019-05-06T16:28:48                  N/A 1-00:00:00      short
          23526511       all                   toil_job_431 lparsons PD      1     1       700M       0:00           (Priority)             4229  2019-05-06T16:28:48                  N/A 1-00:00:00      short
          23526512       all                   toil_job_432 lparsons PD      1     1       700M       0:00           (Priority)             4229  2019-05-06T16:28:50                  N/A 1-00:00:00      short
          23526514       all                   toil_job_433 lparsons PD      1     1       700M       0:00           (Priority)             4229  2019-05-06T16:29:19                  N/A 1-00:00:00      short
          23526515       all                   toil_job_434 lparsons PD      1     1       700M       0:00           (Priority)             4229  2019-05-06T16:29:19                  N/A 1-00:00:00      short
          23526517       all                   toil_job_435 lparsons PD      1     1       700M       0:00           (Priority)             4229  2019-05-06T16:29:26                  N/A 1-00:00:00      short
          23526519       all                   toil_job_436 lparsons PD      1     1       700M       0:00           (Priority)             4229  2019-05-06T16:29:49                  N/A 1-00:00:00      short
          23526520       all                   toil_job_437 lparsons PD      1     1       700M       0:00           (Priority)             4229  2019-05-06T16:29:49                  N/A 1-00:00:00      short
          23526521       all                   toil_job_438 lparsons PD      1     1       700M       0:00           (Priority)             4229  2019-05-06T16:29:50                  N/A 1-00:00:00      short
          23526523       all                   toil_job_439 lparsons PD      1     1       700M       0:00           (Priority)             4229  2019-05-06T16:30:20                  N/A 1-00:00:00      short
          23526524       all                   toil_job_440 lparsons PD      1     1       700M       0:00           (Priority)             4229  2019-05-06T16:30:20                  N/A 1-00:00:00      short
          23526525       all                   toil_job_441 lparsons PD      1     1       700M       0:00           (Priority)             4229  2019-05-06T16:30:25                  N/A 1-00:00:00      short
          23526528       all                   toil_job_442 lparsons PD      1     1       700M       0:00           (Priority)             4229  2019-05-06T16:30:50                  N/A 1-00:00:00      short
          23526529       all                   toil_job_443 lparsons PD      1     1       700M       0:00           (Priority)             4229  2019-05-06T16:30:50                  N/A 1-00:00:00      short
          23526530       all                   toil_job_444 lparsons PD      1     1       700M       0:00           (Priority)             4229  2019-05-06T16:30:50                  N/A 1-00:00:00      short
          23525316       all                     toil_job_5 lparsons  R      1     1     95367M    1:12:42        della-r2c4n14             4230  2019-05-06T14:54:09  2019-05-06T15:19:23   22:47:18      short
          23525179       all                     toil_job_2 lparsons  R      1     1     95367M    1:39:06         della-r2c3n5             4230  2019-05-06T14:31:17  2019-05-06T14:52:59   22:20:54      short
```

Exception:
```
INFO:toil.leader:Issued job 'CactusReferenceRecursion2' V/G/jobkNS6oh with job batch system ID: 514 and cores: 1, disk: 2.0 G, and memory: 9.4 G
INFO:toil.leader:Job ended successfully: 'CactusReferenceWrapper' k/k/job7kXNgW
INFO:toil.leader:Job ended successfully: 'CactusReferenceWrapper' 8/f/job0ScWfo
INFO:toil.leader:Job ended successfully: 'CactusReferenceWrapper' n/w/job5abkek
INFO:toil.leader:Job ended successfully: 'CactusReferenceWrapper' K/y/job6UnpLD
INFO:toil.leader:Job ended successfully: 'CactusReferenceWrapper' Y/H/jobZ4XAwC
INFO:toil.leader:Job ended successfully: 'CactusReferenceWrapper' Z/7/jobQcgqkx
INFO:toil.leader:Job ended successfully: 'CactusReferenceWrapper' I/m/jobgYDdUI
INFO:toil.leader:Job ended successfully: 'CactusReferenceWrapper' C/H/job55r7qn
INFO:toil.leader:Job ended successfully: 'CactusReferenceWrapper' u/x/job5wHD7o
INFO:toil.leader:Job ended successfully: 'CactusReferenceWrapper' V/l/jobiv4R6L
INFO:toil.leader:Job ended successfully: 'CactusReferenceWrapper' G/h/jobHCKiQ4
INFO:toil.leader:Job ended successfully: 'CactusReferenceWrapper' h/X/joboXcjfg
INFO:toil.leader:Reissued any over long jobs
Traceback (most recent call last):
  File "/home/lparsons/miniconda3/envs/cactus/bin/cactus", line 11, in <module>
    load_entry_point('progressiveCactus', 'console_scripts', 'cactus')()
  File "/tigress/lparsons/kocher_lab/cactus/src/cactus/progressive/cactus_progressive.py", line 477, in main
    halID = toil.restart()
  File "/home/lparsons/miniconda3/envs/cactus/lib/python2.7/site-packages/toil/common.py", line 803, in restart
    return self._runMainLoop(rootJobGraph)
  File "/home/lparsons/miniconda3/envs/cactus/lib/python2.7/site-packages/toil/common.py", line 1044, in _runMainLoop
    jobCache=self._jobCache).run()
  File "/home/lparsons/miniconda3/envs/cactus/lib/python2.7/site-packages/toil/leader.py", line 211, in run
    self.innerLoop()
  File "/home/lparsons/miniconda3/envs/cactus/lib/python2.7/site-packages/toil/leader.py", line 556, in innerLoop
    self.checkForDeadlocks()
  File "/home/lparsons/miniconda3/envs/cactus/lib/python2.7/site-packages/toil/leader.py", line 588, in checkForDeadlocks
    raise DeadlockException("The system is service deadlocked - all %d running jobs are active services" % totalRunningJobs)
toil.leader.DeadlockException
```

**Comment by jasonsydes** [comment]
I can confirm this (the Deadlock) is happening.  I've seen it 12 times now.  Generally when it happens, I have fewer jobs running (maybe this is because I'm using --statePollingWait 120??).  Usually it's two KtServerService jobs running (plus the "head" cactus process).  

I made full runs of evolveMammals.txt and a 4-species test alignment, and I did *not* see the problem.  The problem first came up for me when I tried a 12 species test alignment. 

I'm using Slurm 17.11.13-2 and toil 3.19.0, and our lab has a handful of dedicated nodes on our cluster, so it's not that it's exhausting resources (which I believe is what the deadlock code is supposed to detect?).

This morning I disabled the deadlock detection code and replaced it with code (see below) that will just print out the conditions leading to the deadlock.  Sadly that code hasn't been triggered yet.  If this issue is still open if/when it does, I'll post that output here.

The updated code, from toil/leader.py:
```python
    def checkForDeadlocks(self):
        """
        Checks if the system is deadlocked running service jobs.
        """
        totalRunningJobs = len(self.batchSystem.getRunningBatchJobIDs())
        totalServicesIssued = self.serviceJobsIssued + self.preemptableServiceJobsIssued
        # If there are no updated jobs and at least some jobs running
        if totalServicesIssued >= totalRunningJobs and totalRunningJobs > 0:
            serviceJobs = [x for x in list(self.jobBatchSystemIDToIssuedJob.keys()) if isinstance(self.jobBatchSystemIDToIssuedJob[x], ServiceJobNode)]
            runningServiceJobs = set([x for x in serviceJobs if self.serviceManager.isRunning(self.jobBatchSystemIDToIssuedJob[x])])
            assert len(runningServiceJobs) <= totalRunningJobs

            # If all the running jobs are active services then we have a potential deadlock
            if len(runningServiceJobs) == totalRunningJobs:
                # We wait self.config.deadlockWait seconds before declaring the system deadlocked
                if self.potentialDeadlockedJobs != runningServiceJobs:
                    self.potentialDeadlockedJobs = runningServiceJobs
                    self.potentialDeadlockTime = time.time()
                elif time.time() - self.potentialDeadlockTime >= self.config.deadlockWait:
                    # Jason patched.
                    #     20190501-12way kept deadlocking for no apparent reason.  I'm disabling.
                    # ORIGINAL: raise DeadlockException("The system is service deadlocked - all %d running jobs are active services" % totalRunningJobs)
                    logger.info("Jason DISABLED this DeadlockException: The system is service deadlocked - all %d running jobs are active services" % totalRunningJobs)
                    logger.info("JNOTE: if totalServicesIssued ({}) >= totalRunningJobs ({}) and totalRunningJobs ({}) > 0".format(
                        totalServicesIssued, totalRunningJobs, totalRunningJobs))
                    logger.info("JNOTE: if len(runningServiceJobs ({})) == totalRunningJobs ({}):".format(
                        len(runningServiceJobs), totalRunningJobs))
                    logger.info("JNOTE: if self.potentialDeadlockedJobs ({}) != runningServiceJobs ({}):".format(
                        self.potentialDeadlockedJobs, runningServiceJobs))
                    logger.info("JNOTE: elif time.time() ({}) - self.potentialDeadlockTime ({}) (diff is {}) >= self.config.deadlockWait ({}):".format(
                            time.time(), self.potentialDeadlockTime, time.time() - self.potentialDeadlockTime, self.config.deadlockWait))
            else:
                # We have observed non-service jobs running, so reset the potential deadlock
                self.potentialDeadlockedJobs = set()
                self.potentialDeadlockTime = 0
        else:
            # We have observed non-service jobs running, so reset the potential deadlock
            self.potentialDeadlockedJobs = set()
            self.potentialDeadlockTime = 0
```

**Comment by jasonsydes** [comment]
In case it's helpful, here's some log snippets from several earlier runs that ended in deadlock. 
Produced like so:
```bash
egrep -B40 -i 'deadlock' head-slurm*out  > some_deadlocks.out
```
[some_deadlocks.txt](https://github.com/ComparativeGenomicsToolkit/cactus/files/3150296/some_deadlocks.txt)

**Comment by jasonsydes** [comment]
Ok, I encountered two "deadlocks".  The first one was spurious.  The second one looks like it's real.

I've attached snippets from two slightly different log files.  They show slightly different things. The first is basically --logFile cactus.log but with timestamps added.  The second one is just the slurm log file, which is mostly the same, but includes CalledProcessError (this error may have occurred because I may have been overloading Slurm at the time).

Here's how I generated the snippets:
```
grep -A40 -B40 cactus.timestamps.log > cactus.log.snippets.with.timestamps.txt
grep -A40 -B40 Jason head-slurm-5230631.out > slurm.log.snippets.txt
```
And the snippets are below.  Just search for the string "Jason" in those files and you'll find the entries in context.  But here is what one of the entries looks like without context:
```
INFO:toil.leader:Jason DISABLED this DeadlockException: The system is service deadlocked - all 2 running jobs are active services
INFO:toil.leader:JNOTE: if totalServicesIssued (2) >= totalRunningJobs (2) and totalRunningJobs (2) > 0
INFO:toil.leader:JNOTE: if len(runningServiceJobs (2)) == totalRunningJobs (2):
INFO:toil.leader:JNOTE: if self.potentialDeadlockedJobs (set([165481, 165483])) != runningServiceJobs (set([165481, 165483])):
INFO:toil.leader:JNOTE: elif time.time() (1557344126.23) - self.potentialDeadlockTime (1557333323.45) (diff is 10802.778949) >= self.config.deadlockWait (10800):
```
(Yes, I had patched deadlockWait to be 10800 somewhere previously, so that number makes sense here.)

[cactus.log.snippets.with.timestamps.txt](https://github.com/ComparativeGenomicsToolkit/cactus/files/3160314/cactus.log.snippets.with.timestamps.txt)
[slurm.log.snippets.txt](https://github.com/ComparativeGenomicsToolkit/cactus/files/3160315/slurm.log.snippets.txt)
