### ISSUE TITLE
error cactus_progressive.py

### ISSUE THREAD

**Issue by lucaskbobadilla** [ComparativeGenomicsToolkit/cactus#784]
Hello, I am running cactus with four plant genomes (different species). I am running Cactus via Docker. At the end I am getting two failures at cactus_prossive.py step. Here is the log part where the error is happening. Any ideas are welcome!

Thanks!

Log:

[2022-09-08T21:41:32+0000] [MainThread] [W] [toil.leader] Log from job "kind-progressive_schedule/instance-1e7puap7" follows:
=========>
        [2022-09-08T21:41:32+0000] [MainThread] [I] [toil.worker] ---TOIL WORKER OUTPUT LOG---
        [2022-09-08T21:41:32+0000] [MainThread] [I] [toil] Running Toil version 5.7.1-b5cae9634820d76cb6c13b2a6312895122017d54 on host 2b2327be1738.
        [2022-09-08T21:41:32+0000] [MainThread] [I] [toil.worker] Working on job 'progressive_schedule' kind-progressive_schedule/instance-1e7puap7 v1
        [2022-09-08T21:41:32+0000] [MainThread] [I] [toil.worker] Loaded body Job('progressive_schedule' kind-progressive_schedule/instance-1e7puap7 v1) from descriptio
n 'progressive_schedule' kind-progressive_schedule/instance-1e7puap7 v1
        Traceback (most recent call last):
          File "/home/cactus/cactus_env/lib/python3.10/site-packages/toil/worker.py", line 407, in workerScript
            job._runner(jobGraph=None, jobStore=jobStore, fileStore=fileStore, defer=defer) 
          File "/home/cactus/cactus_env/lib/python3.10/site-packages/toil/job.py", line 2406, in _runner
            returnValues = self._run(jobGraph=None, fileStore=fileStore)
          File "/home/cactus/cactus_env/lib/python3.10/site-packages/toil/job.py", line 2324, in _run
            return self.run(fileStore)
          File "/home/cactus/cactus_env/lib/python3.10/site-packages/toil/job.py", line 2547, in run
            rValue = userFunction(*((self,) + tuple(self._args)), **self._kwargs)
          File "/home/cactus/cactus_env/lib/python3.10/site-packages/cactus/progressive/cactus_progressive.py", line 112, in progressive_schedule
            assert len(dep_table) > 0
        AssertionError
        [2022-09-08T21:41:33+0000] [MainThread] [E] [toil.worker] Exiting the worker because of a failed job on host 2b2327be1738
<=========
[2022-09-08T21:41:33+0000] [MainThread] [W] [toil.job] Due to failure we are reducing the remaining try count of job 'progressive_schedule' kind-progressive_schedule/in
stance-1e7puap7 v5 with ID kind-progressive_schedule/instance-1e7puap7 to 0
[2022-09-08T21:41:33+0000] [MainThread] [W] [toil.leader] Job 'progressive_schedule' kind-progressive_schedule/instance-1e7puap7 v6 is completely failed
[2022-09-08T21:41:41+0000] [MainThread] [I] [toil.leader] Finished toil run with 3 failed jobs.
[2022-09-08T21:41:41+0000] [MainThread] [I] [toil.leader] Failed jobs at end of the run: 'sanitize_fasta_headers' kind-progressive_workflow/instance-4ud6z17i v2 'progre
ssive_schedule' kind-progressive_schedule/instance-1e7puap7 v6 'preprocess_all' kind-preprocess_all/instance-236enjlg v3

Workflow Progress 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████
█████████████████████████████████████████████████| 98/98 (2 failures) [31:28<00:00, 0.05 jobs/s]
Traceback (most recent call last):
  File "/home/cactus/cactus_env/bin/cactus", line 8, in <module>
    sys.exit(main())
  File "/home/cactus/cactus_env/lib/python3.10/site-packages/cactus/progressive/cactus_progressive.py", line 398, in main
    hal_id = toil.start(Job.wrapJobFn(progressive_workflow, options, config_node, mc_tree, og_map, input_seq_id_map))
  File "/home/cactus/cactus_env/lib/python3.10/site-packages/toil/common.py", line 966, in start
    return self._runMainLoop(rootJobDescription)
  File "/home/cactus/cactus_env/lib/python3.10/site-packages/toil/common.py", line 1391, in _runMainLoop
    jobCache=self._jobCache).run()
  File "/home/cactus/cactus_env/lib/python3.10/site-packages/toil/leader.py", line 309, in run
    raise FailedJobsException(self.jobStore, failed_jobs, exit_code=self.recommended_fail_exit_code)
toil.leader.FailedJobsException: The job store '/data/jobStore' contains 3 failed jobs: 'sanitize_fasta_headers' kind-progressive_workflow/instance-4ud6z17i v2, 'progressive_schedule' kind-progressive_schedule/instance-1e7puap7 v6, 'preprocess_all' kind-preprocess_all/instance-236enjlg v3
Log from job "'progressive_schedule' kind-progressive_schedule/instance-1e7puap7 v6" follows:
=========>
        [2022-09-08T21:41:33+0000] [MainThread] [I] [toil.worker] ---TOIL WORKER OUTPUT LOG---
        [2022-09-08T21:41:33+0000] [MainThread] [I] [toil] Running Toil version 5.7.1-b5cae9634820d76cb6c13b2a6312895122017d54 on host 2b2327be1738.
        [2022-09-08T21:41:33+0000] [MainThread] [I] [toil.worker] Working on job 'progressive_schedule' kind-progressive_schedule/instance-1e7puap7 v4
        [2022-09-08T21:41:33+0000] [MainThread] [I] [toil.worker] Loaded body Job('progressive_schedule' kind-progressive_schedule/instance-1e7puap7 v4) from description 'progressive_schedule' kind-progressive_schedule/instance-1e7puap7 v4
        Traceback (most recent call last):
          File "/home/cactus/cactus_env/lib/python3.10/site-packages/toil/worker.py", line 407, in workerScript
            job._runner(jobGraph=None, jobStore=jobStore, fileStore=fileStore, defer=defer)
          File "/home/cactus/cactus_env/lib/python3.10/site-packages/toil/job.py", line 2406, in _runner
            returnValues = self._run(jobGraph=None, fileStore=fileStore)
          File "/home/cactus/cactus_env/lib/python3.10/site-packages/toil/job.py", line 2324, in _run
            return self.run(fileStore)
          File "/home/cactus/cactus_env/lib/python3.10/site-packages/toil/job.py", line 2547, in run
            rValue = userFunction(*((self,) + tuple(self._args)), **self._kwargs)
          File "/home/cactus/cactus_env/lib/python3.10/site-packages/cactus/progressive/cactus_progressive.py", line 112, in progressive_schedule
            assert len(dep_table) > 0
        AssertionError
        [2022-09-08T21:41:33+0000] [MainThread] [E] [toil.worker] Exiting the worker because of a failed job on host 2b2327be1738
<=========

**Comment by lucaskbobadilla** [comment]
Here is my command: 

`docker run -v $(pwd):/data --rm -it quay.io/comparative-genomics-toolkit/cactus:v2.2.1 cactus /data/jobStore /data/seqFile.txt /data/palmer.hal --root S_oleraceae --binariesMode local`

and my seqFile:

((A_cruentus:0.00104350,A_palmeri:0.02920279):0.01516727,A_hypochondriacus:0.00001506,S_oleraceae:0.86145093);
A_cruentus /data/A_cruentus.fasta
A_hypochondriacus /data/Amaranthus_hypochondriacus.faa
A_palmeri /data/A_palmeri.fasta
S_oleraceae /data/S_oleraceae.fasta

**Comment by glennhickey** [comment]
The problem is with 
```
--root S_oleraceae
```
You can't specify a leaf genome as a root.  

Thanks for raising this, as cactus clearly needs to be fixed to print a clear error message for this case, rather than a cryptic assertion failure.

**Comment by lucaskbobadilla** [comment]
Thanks for the quick response!

I tried to run without specifying a root, and I am still getting an error. Does cactus always require a root?

Thanks!

**Comment by glennhickey** [comment]
`--root` is not required.  When I make a phony version of your data
```
#dep_table.txt
((A_cruentus:0.00104350,A_palmeri:0.02920279):0.01516727,A_hypochondriacus:0.00001506,S_oleraceae:0.86145093);
A_cruentus https://raw.githubusercontent.com/ComparativeGenomicsToolkit/cactusTestData/master/evolver/primates/loci1/simHuman.chr6
A_hypochondriacus	https://raw.githubusercontent.com/ComparativeGenomicsToolkit/cactusTestData/master/evolver/primates/loci1/simChimp.chr6
A_palmeri	https://raw.githubusercontent.com/ComparativeGenomicsToolkit/cactusTestData/master/evolver/primates/loci1/simGorilla.chr6
S_oleraceae https://raw.githubusercontent.com/ComparativeGenomicsToolkit/cactusTestData/master/evolver/primates/loci1/simOrang.chr6
```
It runs fine with
```
 docker run -v $(pwd):/data --rm -it quay.io/comparative-genomics-toolkit/cactus:v2.2.1 cactus /data/jobStore /data/dep_table.txt /data/palmer.hal
```

**Comment by lucaskbobadilla** [comment]
That worked! Turns out one of the genomes was not soft masked, and that was throwing me an error. I soft-masked it, and it works perfectly.

Thank you!
