### ISSUE TITLE
cactus-graphmap-join failed

### ISSUE THREAD

**Issue by sdws1983** [ComparativeGenomicsToolkit/cactus#817]
Hi!
I am trying to use the Minigraph-Cactus Pangenome pipeline to construct the graph pan-genome. I have successfully run through the example of yeast pan-genome, and I am currently working my own data.
There were no problems in the previous steps, but at the end of the `cactus-graphmap-join` part, the following error occurred (Some path names are too long and here simplified to ***):

```
[2022-10-25T19:39:38+0800] [MainThread] [I] [toil.realtimeLogger] Starting real-time logging.
[2022-10-25T19:39:38+0800] [MainThread] [I] [toil.leader] Issued job 'make_giraffe_indexes' kind-make_giraffe_indexes/instance-8chhcfex v7 with job batch system ID: 0 and cores: 1, disk: 476.8 Gi, and memory: 238.4 Gi
[2022-10-25T19:39:39+0800] [MainThread] [I] [toil.worker] Redirecting logging to /share/home/***/logs/689c898906d05b01b4c1448152e47f9b/1db7/worker_log.txt
[2022-10-25T19:39:39+0800] [MainThread] [I] [toil-rt] 2022-10-25 19:39:39.688732: Running the command: "vg index -t 1 -j /share/home/***/logs/689c898906d05b01b4c1448152e47f9b/1db7/d1b5/tmpe5bxixhm/joint.dist -s /share/home/***/logs/689c898906d05b01b4c1448152e47f9b/1db7/d1b5/tmpe5bxixhm/joint.snarls /share/home/***/logs/689c898906d05b01b4c1448152e47f9b/1db7/d1b5/tmpe5bxixhm/joint.xg"
[2022-10-25T19:39:40+0800] [MainThread] [I] [toil.leader] 1 jobs are running, 0 jobs are issued and waiting to run
[2022-10-25T19:42:47+0800] [Thread-1  ] [E] [toil.batchSystems.singleMachine] Got exit code 1 (indicating failure) from job _toil_worker make_giraffe_indexes file:/share/home/***/jobstore kind-make_giraffe_indexes/instance-8chhcfex.
[2022-10-25T19:42:47+0800] [MainThread] [W] [toil.leader] Job failed with exit value 1: 'make_giraffe_indexes' kind-make_giraffe_indexes/instance-8chhcfex v7
Exit reason: None
[2022-10-25T19:42:47+0800] [MainThread] [W] [toil.leader] The job seems to have left a log file, indicating failure: 'make_giraffe_indexes' kind-make_giraffe_indexes/instance-8chhcfex v8
[2022-10-25T19:42:47+0800] [MainThread] [W] [toil.leader] Log from job "kind-make_giraffe_indexes/instance-8chhcfex" follows:
=========>
        [2022-10-25T19:39:39+0800] [MainThread] [I] [toil.worker] ---TOIL WORKER OUTPUT LOG---
        [2022-10-25T19:39:39+0800] [MainThread] [I] [toil] Running Toil version 5.7.1-b5cae9634820d76cb6c13b2a6312895122017d54 on host s001.
        [2022-10-25T19:39:39+0800] [MainThread] [I] [toil.worker] Working on job 'make_giraffe_indexes' kind-make_giraffe_indexes/instance-8chhcfex v7
        [2022-10-25T19:39:39+0800] [MainThread] [I] [toil.worker] Loaded body Job('make_giraffe_indexes' kind-make_giraffe_indexes/instance-8chhcfex v7) from description 'make_giraffe_indexes' kind-make_giraffe_indexes/instance-8chhcfex v7
        [2022-10-25T19:39:39+0800] [MainThread] [I] [cactus.shared.common] Running the command ['vg', 'index', '-t', '1', '-j', '/share/home/***/logs/689c898906d05b01b4c1448152e47f9b/1db7/d1b5/tmpe5bxixhm/joint.dist', '-s', '/share/home/***/logs/689c898906d05b01b4c1448152e47f9b/1db7/d1b5/tmpe5bxixhm/joint.snarls', '/share/home/***/logs/689c898906d05b01b4c1448152e47f9b/1db7/d1b5/tmpe5bxixhm/joint.xg']
        [2022-10-25T19:39:39+0800] [MainThread] [I] [toil-rt] 2022-10-25 19:39:39.688732: Running the command: "vg index -t 1 -j /share/home/***/logs/689c898906d05b01b4c1448152e47f9b/1db7/d1b5/tmpe5bxixhm/joint.dist -s /share/home/***/logs/689c898906d05b01b4c1448152e47f9b/1db7/d1b5/tmpe5bxixhm/joint.snarls /share/home/***/logs/689c898906d05b01b4c1448152e47f9b/1db7/d1b5/tmpe5bxixhm/joint.xg"
        [2022-10-25T19:42:46+0800] [MainThread] [W] [toil.fileStores.abstractFileStore] Failed job accessed files:
        [2022-10-25T19:42:46+0800] [MainThread] [W] [toil.fileStores.abstractFileStore] Downloaded file 'files/for-job/kind-vg_indexes/instance-r6lge_iy/file-e8a084094bb4435fa37ddeaa6af690eb/merged.xg' to path '/share/home/***/logs/689c898906d05b01b4c1448152e47f9b/1db7/d1b5/tmpe5bxixhm/joint.xg'
        [2022-10-25T19:42:46+0800] [MainThread] [W] [toil.fileStores.abstractFileStore] Downloaded file 'files/for-job/kind-vg_indexes/instance-r6lge_iy/file-f2d0bd0b3b034fee8cd85ebf4a252cfa/merged.gbwt' to path '/share/home/***/logs/689c898906d05b01b4c1448152e47f9b/1db7/d1b5/tmpe5bxixhm/joint.gbwt'
        [2022-10-25T19:42:46+0800] [MainThread] [W] [toil.fileStores.abstractFileStore] Downloaded file 'files/for-job/kind-vg_indexes/instance-r6lge_iy/file-4693c1624f414fa196b03394bccf6267/merged.snarls' to path '/share/home/***/logs/689c898906d05b01b4c1448152e47f9b/1db7/d1b5/tmpe5bxixhm/joint.snarls'
        Traceback (most recent call last):
          File "/share/home/***/software/cactus-bin-v2.2.3/cactus_env/lib/python3.9/site-packages/toil/worker.py", line 407, in workerScript
            job._runner(jobGraph=None, jobStore=jobStore, fileStore=fileStore, defer=defer)
          File "/share/home/***/software/cactus-bin-v2.2.3/cactus_env/lib/python3.9/site-packages/toil/job.py", line 2406, in _runner
            returnValues = self._run(jobGraph=None, fileStore=fileStore)
          File "/share/home/***/software/cactus-bin-v2.2.3/cactus_env/lib/python3.9/site-packages/toil/job.py", line 2324, in _run
            return self.run(fileStore)
          File "/share/home/***/software/cactus-bin-v2.2.3/cactus_env/lib/python3.9/site-packages/toil/job.py", line 2547, in run
            rValue = userFunction(*((self,) + tuple(self._args)), **self._kwargs)
          File "/share/home/***/software/cactus-bin-v2.2.3/cactus_env/lib/python3.9/site-packages/cactus/refmap/cactus_graphmap_join.py", line 614, in make_giraffe_indexes
            cactus_call(parameters=['vg', 'index', '-t', str(job.cores), '-j', dist_path, '-s', snarls_path, xg_path])
          File "/share/home/***/software/cactus-bin-v2.2.3/cactus_env/lib/python3.9/site-packages/cactus/shared/common.py", line 794, in cactus_call
            raise RuntimeError("{}Command {} exited {}: {}".format(sigill_msg, call, process.returncode, out))
        RuntimeError: Command ['vg', 'index', '-t', '1', '-j', '/share/home/***/logs/689c898906d05b01b4c1448152e47f9b/1db7/d1b5/tmpe5bxixhm/joint.dist', '-s', '/share/home/***/logs/689c898906d05b01b4c1448152e47f9b/1db7/d1b5/tmpe5bxixhm/joint.snarls', '/share/home/***/logs/689c898906d05b01b4c1448152e47f9b/1db7/d1b5/tmpe5bxixhm/joint.xg'] exited 134: stdout=None, stderr=terminate called after throwing an instance of 'std::bad_alloc'
          what():  std::bad_alloc
        ERROR: Signal 6 occurred. VG has crashed. Visit https://github.com/vgteam/vg/issues/new/choose to report a bug.
        Stack trace path: /tmp/vg_crash_sFqR7J/stacktrace.txt
        Please include the stack trace file in your bug report!

        [2022-10-25T19:42:47+0800] [MainThread] [E] [toil.worker] Exiting the worker because of a failed job on host s001
<=========
```

I have searched this error message for the available issues, the most similar to mine is this [issues](https://github.com/ComparativeGenomicsToolkit/cactus/issues/780), but I have checked the memory cost, it was far from the system limit too. By the way, I was running the task on a fat node with nearly 2T memory. So I don't think this error may due to the memory issues. Following is my command:

`cactus-graphmap-join ./jobstore --vg chrom/hal/Chr1.vg chrom/hal/Chr2.vg --hal chrom/hal/Chr1.hal chrom/hal/Chr2.hal --outDir ./ --outName joint --reference R_A --vcf --giraffe --gfaffix  --wlineSep "." --clipLength 10000 --clipNonMinigraph --logFile logs/4.graphjoin.logs --binariesMode local --defaultCores 64 --defaultMemory 256G --defaultDisk 512G`

The size for my data:
```
chrom/hal:
total 18G
-rw-r--r-- 1 xxx xxx 1.2G Oct 23 03:56 Chr1.hal
-rw-r--r-- 1 xxx xxx 5.9G Oct 23 03:56 Chr1.vg
-rw-r--r-- 1 xxx xxx 918M Oct 22 21:35 Chr2.hal
-rw-r--r-- 1 xxx xxx 4.6G Oct 22 21:36 Chr2.vg
```

Can you give me some advice?

Yumin

**Comment by glennhickey** [comment]
Yeah, there are a number of people reporting problems at this step (distance index computation for giraffe).  In my experience, the `--clipLength 10000 --clipNonMinigraph` options have always solved this.

One thing you could try is to run your command without `--giraffe`.  This will make your graph without crashing.  Then you can rerun `cactus-graphmap-join` with `--vgClipOpts "-d 2 -m 1000"  --preserveDs` passing as input the vgs created above.  This will make a subset graph and produce a giraffe index on that (which will be id compatible with your original graph).  Your index will only contain nodes visited by at least two samples.  In practice, you generally want to use this type of graph for giraffe mapping anyway. 

allele frequency filtering in human
https://github.com/ComparativeGenomicsToolkit/cactus/blob/master/doc/pangenome.md#hprc-graph-filtering-by-allele-frequency

and fly
https://github.com/ComparativeGenomicsToolkit/cactus/blob/master/doc/mc-pangenomes/16-fly-pg-2022-05-26-commands.md
