### ISSUE TITLE
AssertionError during progressive_step

### ISSUE THREAD

**Issue by jesspeers** [ComparativeGenomicsToolkit/cactus#819]
Hi, I am running Cactus (v. 2.2.0) on twelve mammal genomes and I have had an error with ‘progressive_step’ that I'm struggling to understand. 

The line I ran was:
`srun cactus --restart --realTimeLogging --cleanWorkDir=onSuccess --noLinkImports --noMoveExports --binariesMode local --maxCores 128 --defaultMemory 4G --maxMemory 512G --defaultDisk 64G --maxDisk 20480G --workDir ./ ./jobstore evolverFelids.txt ./cactus_felids_aln.hal`

The job was running for 43 days and failed with the following error message: 

```
[2022-10-26T05:07:27+0000] [MainThread] [I] [toil.leader] Issued job 'progressive_step' kind-progressive_step/instance-nm7s_4tz v1 with job batch system ID: 150892 and cores: 1, disk: 59.6 Gi, and memory: 3.7 Gi
[2022-10-26T05:07:27+0000] [MainThread] [I] [toil.worker] Redirecting logging to /scratch/jpeers/cactus_sep22/b616669690c750e4af4ad9ac190d43d3/a53a/worker_log.txt
[2022-10-26T05:07:28+0000] [Thread-1 (daddy)] [E] [toil.batchSystems.singleMachine] Got exit code 1 (indicating failure) from job _toil_worker progressive_step file:/scratch/jpeers/cactus_sep22/jobstore kind-progressive_step/instance-nm7s_
[2022-10-26T05:07:28+0000] [MainThread] [W] [toil.leader] Job failed with exit value 1: 'progressive_step' kind-progressive_step/instance-nm7s_4tz v1
Exit reason: None
[2022-10-26T05:07:28+0000] [MainThread] [W] [toil.leader] The job seems to have left a log file, indicating failure: 'progressive_step' kind-progressive_step/instance-nm7s_4tz v2
[2022-10-26T05:07:28+0000] [MainThread] [W] [toil.leader] Log from job "kind-progressive_step/instance-nm7s_4tz" follows:
=========>
        [2022-10-26T05:07:27+0000] [MainThread] [I] [toil.worker] ---TOIL WORKER OUTPUT LOG---
        [2022-10-26T05:07:27+0000] [MainThread] [I] [toil] Running Toil version 5.6.0-c34146a6437e4407a61e946e968bcce67a0ebbca on host n83030.
        [2022-10-26T05:07:27+0000] [MainThread] [I] [toil.worker] Working on job 'progressive_step' kind-progressive_step/instance-nm7s_4tz v1
        [2022-10-26T05:07:28+0000] [MainThread] [I] [toil.worker] Loaded body Job('progressive_step' kind-progressive_step/instance-nm7s_4tz v1) from description 'progressive_step' kind-progressive_step/instance-nm7s_4tz v1
        Traceback (most recent call last):
          File "/home/cactus/cactus_env/lib/python3.10/site-packages/toil/worker.py", line 405, in workerScript
            job._runner(jobGraph=None, jobStore=jobStore, fileStore=fileStore, defer=defer)
          File "/home/cactus/cactus_env/lib/python3.10/site-packages/toil/job.py", line 2399, in _runner
            returnValues = self._run(jobGraph=None, fileStore=fileStore)
          File "/home/cactus/cactus_env/lib/python3.10/site-packages/toil/job.py", line 2317, in _run
            return self.run(fileStore)
          File "/home/cactus/cactus_env/lib/python3.10/site-packages/toil/job.py", line 2540, in run
            rValue = userFunction(*((self,) + tuple(self._args)), **self._kwargs)
          File "/home/cactus/cactus_env/lib/python3.10/site-packages/cactus/progressive/cactus_progressive.py", line 170, in progressive_step
            spanning_tree = get_spanning_subtree(tree, event, ConfigWrapper(config_node), og_map)
          File "/home/cactus/cactus_env/lib/python3.10/site-packages/cactus/progressive/progressive_decomposition.py", line 196, in get_spanning_subtree
            spanning_tree = mc_tree.extractSpanningTree([mc_tree.getName(node) for node in node_id_set])
          File "/home/cactus/cactus_env/lib/python3.10/site-packages/cactus/progressive/multiCactusTree.py", line 82, in extractSpanningTree
            assert len(nodes) > 1
        AssertionError
        [2022-10-26T05:07:28+0000] [MainThread] [E] [toil.worker] Exiting the worker because of a failed job on host n83030
```

I would really appreciate any guidance on the meaning of the error message and how it can be resolved. Thank you!
I have checked and my genomes are soft-masked.

Many thanks,
Jess

**Comment by glennhickey** [comment]
Can you please share your whole log?

**Comment by jesspeers** [comment]
Thank you for such a quick response! 

I have attached the full error file (cactus_felids_2.err.txt.zip).
[cactus_felids_2.err.txt.zip](https://github.com/ComparativeGenomicsToolkit/cactus/files/9881079/cactus_felids_2.err.txt.zip)

Just to note: this run was restarted using --restart as my initial run failed after 7 days due to a node failure. I have attached the initial error file (cactus_felids.err.txt) in case this is also useful.
[cactus_felids.err.txt](https://github.com/ComparativeGenomicsToolkit/cactus/files/9881083/cactus_felids.err.txt)

**Comment by glennhickey** [comment]
Thanks for the logs.  Can you please share the tree you used?  I think this is an issue with it not properly handling a case where you have an ancestral node with a single child or something like that.

**Comment by jesspeers** [comment]
Hi, the tree I used is:
(((((((PanPar,PanLeo),PanOnc),PanTig),((FelNig,FelCat),(PumCon,AciJub))),CanFam),SusScr)),((MusMus,HomSap));

**Comment by glennhickey** [comment]
Are you sure that's the exact tree in `evolverFelids.txt`?  When I try it (with dummy sequence data) I get and error right away
```
cwltool is not installed.
No sequence path found for PanOnc: skipping
Traceback (most recent call last):
  File "/home/hickey/dev/cactus.clean/venv-clean/bin/cactus", line 33, in <module>
    sys.exit(load_entry_point('Cactus', 'console_scripts', 'cactus')())
  File "/home/hickey/dev/cactus.clean/src/cactus/progressive/cactus_progressive.py", line 370, in main
    mc_tree, input_seq_map, og_candidates = parse_seqfile(options.seqFile, config_wrapper)
  File "/home/hickey/dev/cactus.clean/src/cactus/progressive/progressive_decomposition.py", line 41, in parse_seqfile
    seq_file = SeqFile(seqfile_path)
  File "/home/hickey/dev/cactus.clean/src/cactus/progressive/seqFile.py", line 64, in __init__
    self.parseFile(path)
  File "/home/hickey/dev/cactus.clean/src/cactus/progressive/seqFile.py", line 102, in parseFile
    self.cleanTree()
  File "/home/hickey/dev/cactus.clean/src/cactus/progressive/seqFile.py", line 190, in cleanTree
    self.tree.removeLeaf(leaf)
  File "/home/hickey/dev/cactus.clean/venv-clean/lib/python3.8/site-packages/sonLib/nxtree.py", line 157, in removeLeaf
    self.removeDegree2Vertex(parentId)
  File "/home/hickey/dev/cactus.clean/venv-clean/lib/python3.8/site-packages/sonLib/nxtree.py", line 149, in removeDegree2Vertex
    self.nxDg[parentId][childId]['weight'] = float(newWeight)
TypeError: float() argument must be a string or a number, not 'NoneType'
```

**Comment by jesspeers** [comment]
Yes I copied and pasted it directly from `evolverFelids.txt ` and I've just double checked and I'm sure I've not missed any brackets or anything. 

I've copied it again just in case there's anything I'm not seeing but otherwise I'm not sure what's going wrong.
`(((((((PanPar,PanLeo),PanOnc),PanTig),((FelNig,FelCat),(PumCon,AciJub))),CanFam),SusScr)),((MusMus,HomSap));`

**Comment by glennhickey** [comment]
Pretty weird.  Anyway, this tree is rather invalid by most standards.  The mystery to me is how it got so far into Cactus without an error?  Especially since when I run it it [aborts right away](https://github.com/ComparativeGenomicsToolkit/cactus/issues/819#issuecomment-1297161855).  

The problem is the "degree 2" ancestral nodes, ie internal nodes with a single descendant.  There are two in your tree:
The ancestor of `SusScr` and everything to its left descends from one, as does the `MusMus,HomSap` ancestor.  Such nodes don't contain any phylogenetic information and, I assume, can only be the result of misplaced brackets.  

Cactus does attempt to clean these automatically but somehow even that's not working on your tree (hence the crash in `self.removeDegree2Vertex(parentId)`) above.  

So unfortunately, I don't think your run is salvageable.   All I can suggest is:

* fix your tree
* add branch lengths (very important -- can reduce runtime drastically)
* consider running with `cactus-prepare` (see README) to better preserve intermediate information in the event of problems
* (or at the very least, run `cactus-preprocess` first then `cactus --skipPreprocessor` as a second step so at least you don't need to rerun the slow repeat masking
* Update to the latest cactus release and start from scratch

On my end, I'll make sure the tree gets output to the log, but I'm not sure what else to do.  It seems to be behaving as expected on my end by throwing an error right away.

**Comment by jesspeers** [comment]
Thank you so much for your help! You're right, there are extra brackets that I hadn't picked up on. I'll fix the tree, make the changes you suggest and try again.

Many thanks,
Jess

**Comment by jesspeers** [comment]
Hi Glenn,

Thank you again for your help. I updated my tree and Cactus finished successfully.

Many thanks,
Jess
