### ISSUE TITLE
Segalign launched without --gpu flag specified

### ISSUE THREAD

**Issue by jesspeers** [ComparativeGenomicsToolkit/cactus#840]
Hello,

I am trying to run Cactus v2.2.4 on 12 mammal genomes.

Below is my command:
`srun cactus --realTimeLogging --disableCaching --cleanWorkDir=onSuccess --noLinkImports --noMoveExports --binariesMode local --maxCores 129 --defaultMemory 4G --maxMemory 512G --defaultDisk 64G --maxDisk 20480G --workDir ./ ./jobstore evolverFelids.txt ./cactus_v224_aln.hal`

I got this error message:
```
`[2022-11-18T14:59:48+0000] [Thread-1  ] [E] [toil.batchSystems.singleMachine] Got exit code 1 (indicating failure) from job _toil_worker LastzRepeatMaskJob file:/scratch/jpeers/cactus_newinput_v224/jobsto
re kind-LastzRepeatMaskJob/instance-k1gcf59o.
[2022-11-18T14:59:48+0000] [MainThread] [W] [toil.leader] Job failed with exit value 1: 'LastzRepeatMaskJob' kind-LastzRepeatMaskJob/instance-k1gcf59o v1
Exit reason: None
[2022-11-18T14:59:48+0000] [MainThread] [W] [toil.leader] The job seems to have left a log file, indicating failure: 'LastzRepeatMaskJob' kind-LastzRepeatMaskJob/instance-k1gcf59o v2
[2022-11-18T14:59:48+0000] [MainThread] [W] [toil.leader] Log from job "kind-LastzRepeatMaskJob/instance-k1gcf59o" follows:
=========>
        [2022-11-18T14:59:48+0000] [MainThread] [I] [toil.worker] ---TOIL WORKER OUTPUT LOG---
        [2022-11-18T14:59:48+0000] [MainThread] [I] [toil] Running Toil version 5.7.1-b5cae9634820d76cb6c13b2a6312895122017d54 on host n83032.
        [2022-11-18T14:59:48+0000] [MainThread] [I] [toil.worker] Working on job 'LastzRepeatMaskJob' kind-LastzRepeatMaskJob/instance-k1gcf59o v1
        [2022-11-18T14:59:48+0000] [MainThread] [I] [toil.worker] Loaded body Job('LastzRepeatMaskJob' kind-LastzRepeatMaskJob/instance-k1gcf59o v1) from description 'LastzRepeatMaskJob' kind-LastzRepeatM
askJob/instance-k1gcf59o v1
        [2022-11-18T14:59:48+0000] [MainThread] [I] [cactus.shared.common] Running the command ['segalign_repeat_masker', '/scratch/jpeers/cactus_newinput_v224/6361cff7ae7d50af9f4b2d5bcda1e279/a607/3228/t
mpf5ctlfed.tmp', '--lastz_interval=10000000', '--markend', '--neighbor_proportion', '0.2', '--M', '10', '--step=3', '--ambiguous=iupac,100,100']
        [2022-11-18T14:59:48+0000] [MainThread] [I] [toil-rt] 2022-11-18 14:59:48.222491: Running the command: "segalign_repeat_masker /scratch/jpeers/cactus_newinput_v224/6361cff7ae7d50af9f4b2d5bcda1e279
/a607/3228/tmpf5ctlfed.tmp --lastz_interval=10000000 --markend --neighbor_proportion 0.2 --M 10 --step=3 --ambiguous=iupac,100,100"
        [2022-11-18T14:59:48+0000] [MainThread] [W] [toil.fileStores.abstractFileStore] Failed job accessed files:
        [2022-11-18T14:59:48+0000] [MainThread] [W] [toil.fileStores.abstractFileStore] Downloaded file 'files/for-job/kind-PreprocessSequence/instance-td6r169c/cleanup/file-e1f34dd25a194576b539f1c5840a3a
0c/tmpypiio3je.tmp' to path '/scratch/jpeers/cactus_newinput_v224/6361cff7ae7d50af9f4b2d5bcda1e279/a607/3228/tmpsbto3gwa.tmp'
        [2022-11-18T14:59:48+0000] [MainThread] [W] [toil.fileStores.abstractFileStore] Downloaded file 'files/for-job/kind-PreprocessSequence/instance-td6r169c/cleanup/file-e1f34dd25a194576b539f1c5840a3a
0c/tmpypiio3je.tmp' to path '/scratch/jpeers/cactus_newinput_v224/6361cff7ae7d50af9f4b2d5bcda1e279/a607/3228/tmpf5ctlfed.tmp'
        Traceback (most recent call last):
          File "/home/cactus/cactus_env/lib/python3.8/site-packages/toil/worker.py", line 407, in workerScript
            job._runner(jobGraph=None, jobStore=jobStore, fileStore=fileStore, defer=defer)
          File "/home/cactus/cactus_env/lib/python3.8/site-packages/cactus/shared/common.py", line 877, in _runner
            super(RoundedJob, self)._runner(*args, jobStore=jobStore,
          File "/home/cactus/cactus_env/lib/python3.8/site-packages/toil/job.py", line 2406, in _runner
            returnValues = self._run(jobGraph=None, fileStore=fileStore)
          File "/home/cactus/cactus_env/lib/python3.8/site-packages/toil/job.py", line 2324, in _run
            return self.run(fileStore)
          File "/home/cactus/cactus_env/lib/python3.8/site-packages/cactus/preprocessor/lastzRepeatMasking/cactus_lastzRepeatMask.py", line 197, in run
            alignment = self.gpuRepeatMask(fileStore, targetFiles[0])
          File "/home/cactus/cactus_env/lib/python3.8/site-packages/cactus/preprocessor/lastzRepeatMasking/cactus_lastzRepeatMask.py", line 127, in gpuRepeatMask
            segalign_messages = cactus_call(parameters=cmd, work_dir=alignment_dir, returnStdErr=True)
          File "/home/cactus/cactus_env/lib/python3.8/site-packages/cactus/shared/common.py", line 808, in cactus_call
            raise RuntimeError("{}Command {} exited {}: {}".format(sigill_msg, call, process.returncode, out))
        RuntimeError: Command /usr/bin/time -v segalign_repeat_masker /scratch/jpeers/cactus_newinput_v224/6361cff7ae7d50af9f4b2d5bcda1e279/a607/3228/tmpf5ctlfed.tmp --lastz_interval=10000000 --markend --neighbor_proportion 0.2 --M 10 --step=3 --ambiguous=iupac,100,100 exited 1: stdout=None, stderr=Using 129 threads
        Error: No GPU device found!
        Command exited with non-zero status 1
                Command being timed: "segalign_repeat_masker /scratch/jpeers/cactus_newinput_v224/6361cff7ae7d50af9f4b2d5bcda1e279/a607/3228/tmpf5ctlfed.tmp --lastz_interval=10000000 --markend --neighbor_proportion 0.2 --M 10 --step=3 --ambiguous=iupac,100,100"
                User time (seconds): 0.00
                System time (seconds): 0.06
                Percent of CPU this job got: 95%
                Elapsed (wall clock) time (h:mm:ss or m:ss): 0:00.06
                Average shared text size (kbytes): 0
                Average unshared data size (kbytes): 0
                Average stack size (kbytes): 0
                Average total size (kbytes): 0
                Maximum resident set size (kbytes): 3476
                Average resident set size (kbytes): 0
                Major (requiring I/O) page faults: 4
                Minor (reclaiming a frame) page faults: 913
                Voluntary context switches: 4
                Involuntary context switches: 1
                Swaps: 0
                File system inputs: 6138
                File system outputs: 0
                Socket messages sent: 0
                Socket messages received: 0
                Signals delivered: 0
                Page size (bytes): 4096
                Exit status: 1
        
        [2022-11-18T14:59:48+0000] [MainThread] [E] [toil.worker] Exiting the worker because of a failed job on host n83032
<=========
`
```

Cactus tried to rerun this job but it kept failing with the same error until the whole run failed.

It appears to me that Cactus is trying to use segalign which I believe is used when running on GPUs, but I have not specified the --gpu flag in my command and don't have a GPU available. 

Is there a way to disable segalign and use LastZ or to explicitly tell Cactus not to try to use a GPU?

Many thanks,
Jess

**Comment by glennhickey** [comment]
I just double-checked both the binaries and docker image for this release and could not reproduce.  The only way I can imagine cactus running segalign without --gpu is

* you are using the gpu-enabled docker image `quay.io/comparative-genomics-toolkit/cactus:v2.2.4-gpu`
* or you have modified your `src/cactus/cactus_progressive_config.xml` to enable the gpu

In either case, all I can recommend is re-installing from scratch following the instructions in BIN-INSTALL.md

**Comment by glennhickey** [comment]
Though I guess if you were using `quay.io/comparative-genomics-toolkit/cactus:v2.2.4-gpu` then you'd have segalign installed in your PATH.  Strange.

**Comment by jesspeers** [comment]
Sorry, after checking it seems that the gpu version was downloaded erroneously. Thank you for responding so quickly!
