### ISSUE TITLE
error

### ISSUE THREAD

**Issue by zuodabin** [ComparativeGenomicsToolkit/cactus#853]
Hi~，I have a problem, but I know how to solve this problem,

[2022-12-09T17:27:25+0800] [MainThread] [I] [toil.statsAndLogging] Cactus Commit: b699f6bfb4fe88b7876e533dede24e48bbfeb700
[2022-12-09T17:27:25+0800] [MainThread] [I] [toil.statsAndLogging] Tree: (Q.spinosa:0.5,(Nanpar_v2.0:1.0,wowa:1.0)1:0.5)Anc0;
[2022-12-09T17:27:25+0800] [MainThread] [W] [toil.statsAndLogging] Deprecated toil method.  Please use "toil.test.get_temp_file()" instead."
[2022-12-09T17:27:25+0800] [MainThread] [W] [toil.statsAndLogging] Deprecated toil method that will be moved/replaced in a future release."
cat: /data/zuobin/comparative_genome/cactus/tmp5tuseesg: input file is output file
cat: /data/zuobin/comparative_genome/cactus/jobstore: Is a directory
Traceback (most recent call last):
  File "/data/zuobin/software/cactus-bin-v2.2.4/cactus_env/bin/cactus", line 8, in <module>
    sys.exit(main())
  File "/data/zuobin/software/cactus-bin-v2.2.4/cactus_env/lib/python3.9/site-packages/cactus/progressive/cactus_progressive.py", line 391, in main
    catFiles([os.path.join(seq, subSeq) for subSeq in os.listdir(seq)], tmpSeq)
  File "/data/zuobin/software/cactus-bin-v2.2.4/cactus_env/lib/python3.9/site-packages/cactus/shared/common.py", line 94, in catFiles
    system("cat %s > %s" % (" ".join(filesToCat[:maxCat]), catFile))
  File "/data/zuobin/software/cactus-bin-v2.2.4/cactus_env/lib/python3.9/site-packages/toil/lib/bioio.py", line 32, in system
    subprocess.check_call(command, shell=isinstance(command, str), bufsize=-1)
  File "/data/zuobin/miniconda3/lib/python3.9/subprocess.py", line 373, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'cat /data/zuobin/comparative_genome/cactus/seqfile.txt /data/zuobin/comparative_genome/cactus/tmp5tuseesg /data/zuobin/comparative_genome/cactus/wowa.fa /data/zuobin/comparative_genome/cactus/Q.spinosa.fa /data/zuobin/comparative_genome/cactus/Nanpar_v2.0.fa /data/zuobin/comparative_genome/cactus/jobstore > /data/zuobin/comparative_genome/cactus/tmp5tuseesg' returned non-zero exit status 1.

**Comment by glennhickey** [comment]
You need to fix your input seqfile.  It should just have fasta files in it.  If it does have a directory in it , that directory must only contain fasta files (but please just use fasta files).   This is what a good seqfile might look like

```
(Q.spinosa:0.5,(Nanpar_v2.0:1.0,wowa:1.0)1:0.5)Anc0;

Q.spinosa ./q_spinosa.fa.gz
Nanpar_v2 ./nanpar_v2.fa.gz
wowa ./wowa.fa.gz
```

This is what a seqfile that might lead to weird cat errors may look like

```
(Q.spinosa:0.5,(Nanpar_v2.0:1.0,wowa:1.0)1:0.5)Anc0;

Q.spinosa /home/users/cactus/
Nanpar_v2 ./
wowa /home/user/Videos/
```

hope this helps.
