### ISSUE TITLE
segalign_

### ISSUE THREAD

**Issue by RenzoTale88** [ComparativeGenomicsToolkit/cactus#881]
Hi,
I'm trying to align five small genomes using the docker image of cactus with GPU acceleration.
I currently run the software as follow:
```
docker run \
 --gpus all \
 -it \
 -v $(pwd):/data \
 --rm quay.io/comparative-genomics-toolkit/cactus:v2.3.1-gpu cactus ./js /data/cactus.config /data/final.hal \
 --workDir /data/tmpdir/ \
 --setEnv TMPDIR=/data/tmpdir \
 --logFile /data/cactus.log
```
The workflow is initially working fine, but then fails when running the segalign command `segalign_repeat_masker` command with the following error:
```
        [2023-01-04T15:25:27+0000] [MainThread] [W] [toil.fileStores.abstractFileStore] Downloaded file 'files/for-job/kind-PreprocessSequence/instance-k_1aj3f5/cleanup/file-b8cfce4b4592425f905bb1a46b2baf23/tmpkdj0f25e.tmp' to path '/data/tmpdir/dc32f123dd6656d097662570d7aad81a/3a20/7417/tmp819uap7j/genomeA_0_0.tgt'
        Traceback (most recent call last):
          File "/home/cactus/cactus_env/lib/python3.8/site-packages/toil/worker.py", line 407, in workerScript
            job._runner(jobGraph=None, jobStore=jobStore, fileStore=fileStore, defer=defer)
          File "/home/cactus/cactus_env/lib/python3.8/site-packages/cactus/shared/common.py", line 883, in _runner
            super(RoundedJob, self)._runner(*args, jobStore=jobStore,
          File "/home/cactus/cactus_env/lib/python3.8/site-packages/toil/job.py", line 2406, in _runner
            returnValues = self._run(jobGraph=None, fileStore=fileStore)
          File "/home/cactus/cactus_env/lib/python3.8/site-packages/toil/job.py", line 2324, in _run
            return self.run(fileStore)
          File "/home/cactus/cactus_env/lib/python3.8/site-packages/cactus/preprocessor/lastzRepeatMasking/cactus_lastzRepeatMask.py", line 208, in run
            maskedQuery = self.maskCoveredIntervals(fileStore, queryFile, alignment)
          File "/home/cactus/cactus_env/lib/python3.8/site-packages/cactus/preprocessor/lastzRepeatMasking/cactus_lastzRepeatMask.py", line 185, in maskCoveredIntervals
            cactus_call(infile=queryFile, outfile=maskedQuery, work_dir=self.work_dir,
          File "/home/cactus/cactus_env/lib/python3.8/site-packages/cactus/shared/common.py", line 814, in cactus_call
            raise RuntimeError("{}Command {} exited {}: {}".format(sigill_msg, call, process.returncode, out))
        RuntimeError: Command /usr/bin/time -v cactus_fasta_softmask_intervals.py --origin=zero tmpppg_sywm.tmp exited 1: stdout=None, stderr=Traceback (most recent call last):
          File "/home/cactus/bin/cactus_fasta_softmask_intervals.py", line 204, in <module>
            if __name__ == "__main__": main()
          File "/home/cactus/bin/cactus_fasta_softmask_intervals.py", line 82, in main
            f = open(intervalsFile, "rt")
        FileNotFoundError: [Errno 2] No such file or directory: 'tmpppg_sywm.tmp'
        Command exited with non-zero status 1
                Command being timed: "cactus_fasta_softmask_intervals.py --origin=zero tmpppg_sywm.tmp"
                User time (seconds): 0.03
                System time (seconds): 0.00
                Percent of CPU this job got: 93%
                Elapsed (wall clock) time (h:mm:ss or m:ss): 0:00.03
                Average shared text size (kbytes): 0
                Average unshared data size (kbytes): 0
                Average stack size (kbytes): 0
                Average total size (kbytes): 0
                Maximum resident set size (kbytes): 9608
                Average resident set size (kbytes): 0
                Major (requiring I/O) page faults: 0
                Minor (reclaiming a frame) page faults: 1221
                Voluntary context switches: 5
                Involuntary context switches: 0
                Swaps: 0
                File system inputs: 0
                File system outputs: 0
                Socket messages sent: 0
                Socket messages received: 0
                Signals delivered: 0
                Page size (bytes): 4096
                Exit status: 1

        [2023-01-04T15:25:27+0000] [MainThread] [E] [toil.worker] Exiting the worker because of a failed job on host 23603f6a2714
<=========
```

It looks like it cannot save the file successfully, though I have provided the temporary directory both as environment variable and `workDir`, and added full write permission to the directory. The segalign is not running out of memory, using ~1.4/4 Gb. 
Am I missing any relevant flag?

Thanks
Andrea

**Comment by glennhickey** [comment]
Thanks for pointing this out.  It seems to be a bug introduced in v2.3.1 (our automated test server doesn't have a gpu unfortunately).  It will be fixed in the next release, which I'll do asap.  In the meantime you'll have to revert to v2.3.0 in order to run cactus-preprocess with the gpu.

**Comment by RenzoTale88** [comment]
@glennhickey thanks for the quick reply, the version 2.3.0 is working fine.
