### ISSUE TITLE
ValueError: invalid literal for int() with base 10: 'None' at make_chunked_alignments stage

### ISSUE THREAD

**Issue by oneillkza** [ComparativeGenomicsToolkit/cactus#893]
I am running inside the `cactus_v2.3.0-gpu` via Singularity, using `binariesMode local` (inside the container -- see below). The workflow runs OK, until it reaches the `make_chunked_alignments` stage, at which point all jobs of that type fail with the below error. Note that the `evolverMammals.txt` example runs to completion with the same configuration, so I'm guessing it's something to do with my input data that's causing this. Any help or suggestions for debugging would be very welcome! :)

```
	Traceback (most recent call last):
	  File "/projects/koneill_prj/conda/envs/cactus/lib/python3.10/site-packages/toil/worker.py", line 403, in workerScript
	    job._runner(jobGraph=None, jobStore=jobStore, fileStore=fileStore, defer=defer)
	  File "/projects/koneill_prj/conda/envs/cactus/lib/python3.10/site-packages/toil/job.py", line 2727, in _runner
	    returnValues = self._run(jobGraph=None, fileStore=fileStore)
	  File "/projects/koneill_prj/conda/envs/cactus/lib/python3.10/site-packages/toil/job.py", line 2644, in _run
	    return self.run(fileStore)
	  File "/projects/koneill_prj/conda/envs/cactus/lib/python3.10/site-packages/toil/job.py", line 2875, in run
	    rValue = userFunction(*((self,) + tuple(self._args)), **self._kwargs)
	  File "/projects/koneill_prj/conda/envs/cactus/lib/python3.10/site-packages/cactus/paf/local_alignment.py", line 115, in make_chunked_alignments
	    lastz_cores = getOptionalAttrib(lastz_params_node, 'cpu', typeFn=int, default=None)
	  File "/projects/koneill_prj/conda/envs/cactus/lib/python3.10/site-packages/cactus/shared/common.py", line 134, in getOptionalAttrib
	    return typeFn(node.attrib[attribName])
	ValueError: invalid literal for int() with base 10: 'None'
	[2023-01-06T15:11:38-0800] [MainThread] [E] [toil.worker] Exiting the worker because of a failed job on host dlhost09
```

Command used to run:

```
cactus="singularity exec --nv -B /projects cactus_v2.3.0-gpu.sif cactus"
nfs_scratch="/projects/CanSeq/scratch/cactus/turtles_2"

#Toil has all kinds of horrible race condition bugs when using NFS-mounted scratch, so instead point it to the local scratch:
workDir=/var/tmp/
seqFile=/projects/CanSeq/Progressive_cactus/turtles/cactus_seqfile.txt
outHal=/projects/CanSeq/Progressive_cactus/turtles/cryptodira.hal

mkdir -p $workDir
mkdir -p $nfs_scratch
mkdir -p ${nfs_scratch}/logs

${cactus} ${nfs_scratch}/jobstore \
	$seqFile \
	$cryptodira.hal \
	--batchSystem single_machine \
	--binariesMode local \
	--maxCores 16 \
	--consCores 16 \
	--maxMemory 64G \
	--writeLogs ${nfs_scratch}/logs/ \
	--gpu \
	--retryCount 1 \
	--workDir $workDir \
	--writeLogsFromAllJobs \
	--clean onSuccess \
	--cleanWorkDir onSuccess \
	--logDebug 

```

Contents of cactus_seqfile.txt:

```
(Chelydra_serpentina:0.03572,((((Cuora_mccordi:0.00839,Cuora_amboinensis:0.00972):0.01256,Aldabrachelys_gigantea:0.02832):0.00866,(Actinemys_pallida:0.00191,Actinemys_marmorata:0.00260):0.02219):0.00977,(Chelonia_mydas:0.01113,Caretta_caretta:0.01341):0.02671):0.00117,((((Homo_sapiens:0.11399,Gallus_gallus:0.10950):0.02493,Carettochelys_insculpta:0.07929):0.00893,Apalone_spinifera:0.07205):0.02947,Dermatemys_mawii:0.04922):0.00723);

Apalone_spinifera	/projects/CanSeq/Progressive_cactus/turtles/Cryptodira/GCA_000385615.1/GCA_000385615.1_ASM38561v1_genomic.fna
Cuora_mccordi	/projects/CanSeq/Progressive_cactus/turtles/Cryptodira/GCA_003846335.1/GCA_003846335.1_ASM384633v1_genomic.fna
Cuora_amboinensis	/projects/CanSeq/Progressive_cactus/turtles/Cryptodira/GCA_004028625.2/GCA_004028625.2_ASM402862v2_genomic.fna
Carettochelys_insculpta	/projects/CanSeq/Progressive_cactus/turtles/Cryptodira/GCA_007922185.1/GCA_007922185.1_Carettochelys_insculpta-1.0_genomic.fna
Dermatemys_mawii	/projects/CanSeq/Progressive_cactus/turtles/Cryptodira/GCA_007922305.1/GCA_007922305.1_Dermatemys_mawii-1.0_genomic.fna
Chelonia_mydas	/projects/CanSeq/Progressive_cactus/turtles/Cryptodira/GCA_015237465.2/GCA_015237465.2_rCheMyd1.pri.v2_genomic.fna
Chelydra_serpentina	/projects/CanSeq/Progressive_cactus/turtles/Cryptodira/GCA_018859375.1/GCA_018859375.1_ASM1885937v1_genomic.fna
Actinemys_marmorata	/projects/CanSeq/Progressive_cactus/turtles/Cryptodira/GCA_022086475.1/GCA_022086475.1_rActMar1.p_genomic.fna
Actinemys_pallida	/projects/CanSeq/Progressive_cactus/turtles/Cryptodira/GCA_023634205.1/GCA_023634205.1_rActPal1.0.p_genomic.fna
Caretta_caretta	/projects/CanSeq/Progressive_cactus/turtles/Cryptodira/GCA_023653815.1/GCA_023653815.1_GSC_CCare_1.0_genomic.fna
Aldabrachelys_gigantea	/projects/CanSeq/Progressive_cactus/turtles/Cryptodira/GCA_026122505.1/GCA_026122505.1_AldGig_1.0_genomic.fna
Homo_sapiens	/projects/CanSeq/Progressive_cactus/turtles/outgroups/GCA_009914755.4/GCA_009914755.4_T2T-CHM13v2.0_genomic.fna
Gallus_gallus	/projects/CanSeq/Progressive_cactus/turtles/outgroups/GCA_016699485.1/GCA_016699485.1_bGalGal1.mat.broiler.GRCg7b_genomic.fna
```

[slurm_script_2023-01-06_15:11:03.log](https://github.com/ComparativeGenomicsToolkit/cactus/files/10364200/slurm_script_2023-01-06_15.11.03.log)

**Comment by oneillkza** [comment]
Hmm -- I have a hunch this might be from restarting a run that was begun on 2.3.1. I thought this run was starting clean, but the logs say otherwise. 

I'm re-running it from the beginning and will report back if that still fails.

**Comment by oneillkza** [comment]
Yep, a clean run is running past this step and is well into the lastz stages. I'm pretty sure this was just a one-off issue from resuming a job from a different version of cactus.
