### ISSUE TITLE
toil.leader.FailedJobsException

### ISSUE THREAD

**Issue by 790634750** [ComparativeGenomicsToolkit/cactus#894]
Hi, I'm using slurm to run a comparison of 26 maize genomes (about 2.2G each), have done softmask, this is the command I run
#!/bin/bash
#sBATCH -o job.%j.err
#sBATCH -o job.%j.out
#SBATCH -p m256Partition
#SBATCH -J myFirstCactus
#SBATCH --nodes=1 
#SBATCH --ntasks-per-node=26

/usr/bin/time cactus /home/name/js /home/name/evolverMammals.txt /home/name/evolverMammals.hal  --disableCaching --consCores 26 --maxCores 26 --batchSystem slurm
[2023-01-06T22:57:26+0800] [MainThread] [W] [toil.common] Batch system does not support auto-deployment. The user script ModuleDescriptor(dirPath='/home/apps/soft/miniconda3/latest/envs/cactus/lib/python3.7/site-packages', name='cactus.progressive.cactus_progressive', fromVirtualEnv=False) will have to be present at the same location on every worker.
[2023-01-06T22:57:26+0800] [MainThread] [I] [toil.job] Saving graph of 1 jobs, 1 new
[2023-01-06T22:57:26+0800] [MainThread] [I] [toil.job] Processing job 'progressive_workflow' kind-progressive_workflow/instance-d1zp9h0u v0
[2023-01-06T22:57:26+0800] [MainThread] [I] [toil] Running Toil version 5.6.0-c34146a6437e4407a61e946e968bcce67a0ebbca on host cu01.
[2023-01-06T22:57:27+0800] [MainThread] [I] [toil.leader] Issued job 'progressive_workflow' kind-progressive_workflow/instance-d1zp9h0u v1 with job batch system ID: 0 and cores: 1, disk: 2.0 Gi, and memory: 2.0 Gi
[2023-01-06T22:57:29+0800] [MainThread] [I] [toil.leader] 0 jobs are running, 1 jobs are issued and waiting to run
[2023-01-06T22:57:51+0800] [MainThread] [W] [toil.leader] Job failed with exit value 127: 'progressive_workflow' kind-progressive_workflow/instance-d1zp9h0u v1
Exit reason: None
[2023-01-06T22:57:51+0800] [MainThread] [W] [toil.leader] No log file is present, despite job failing: 'progressive_workflow' kind-progressive_workflow/instance-d1zp9h0u v1
[2023-01-06T22:57:51+0800] [MainThread] [W] [toil.job] Due to failure we are reducing the remaining try count of job 'progressive_workflow' kind-progressive_workflow/instance-d1zp9h0u v1 with ID kind-progressive_workflow/instance-d1zp9h0u to 5
[2023-01-06T22:57:51+0800] [MainThread] [I] [toil.leader] Issued job 'progressive_workflow' kind-progressive_workflow/instance-d1zp9h0u v2 with job batch system ID: 1 and cores: 1, disk: 2.0 Gi, and memory: 2.0 Gi
[2023-01-06T22:58:15+0800] [MainThread] [W] [toil.leader] Job failed with exit value 127: 'progressive_workflow' kind-progressive_workflow/instance-d1zp9h0u v2
Exit reason: None
[2023-01-06T22:58:15+0800] [MainThread] [W] [toil.leader] No log file is present, despite job failing: 'progressive_workflow' kind-progressive_workflow/instance-d1zp9h0u v2
[2023-01-06T22:58:15+0800] [MainThread] [W] [toil.job] Due to failure we are reducing the remaining try count of job 'progressive_workflow' kind-progressive_workflow/instance-d1zp9h0u v2 with ID kind-progressive_workflow/instance-d1zp9h0u to 4
[2023-01-06T22:58:15+0800] [MainThread] [I] [toil.leader] Issued job 'progressive_workflow' kind-progressive_workflow/instance-d1zp9h0u v3 with job batch system ID: 2 and cores: 1, disk: 2.0 Gi, and memory: 2.0 Gi
[2023-01-06T22:58:39+0800] [MainThread] [W] [toil.leader] Job failed with exit value 127: 'progressive_workflow' kind-progressive_workflow/instance-d1zp9h0u v3
Exit reason: None
[2023-01-06T22:58:39+0800] [MainThread] [W] [toil.leader] No log file is present, despite job failing: 'progressive_workflow' kind-progressive_workflow/instance-d1zp9h0u v3
[2023-01-06T22:58:40+0800] [MainThread] [W] [toil.job] Due to failure we are reducing the remaining try count of job 'progressive_workflow' kind-progressive_workflow/instance-d1zp9h0u v3 with ID kind-progressive_workflow/instance-d1zp9h0u to 3
[2023-01-06T22:58:40+0800] [MainThread] [I] [toil.leader] Issued job 'progressive_workflow' kind-progressive_workflow/instance-d1zp9h0u v4 with job batch system ID: 3 and cores: 1, disk: 2.0 Gi, and memory: 2.0 Gi
[2023-01-06T22:59:03+0800] [MainThread] [W] [toil.leader] Job failed with exit value 127: 'progressive_workflow' kind-progressive_workflow/instance-d1zp9h0u v4
Exit reason: None
[2023-01-06T22:59:03+0800] [MainThread] [W] [toil.leader] No log file is present, despite job failing: 'progressive_workflow' kind-progressive_workflow/instance-d1zp9h0u v4
[2023-01-06T22:59:03+0800] [MainThread] [W] [toil.job] Due to failure we are reducing the remaining try count of job 'progressive_workflow' kind-progressive_workflow/instance-d1zp9h0u v4 with ID kind-progressive_workflow/instance-d1zp9h0u to 2
[2023-01-06T22:59:03+0800] [MainThread] [I] [toil.leader] Issued job 'progressive_workflow' kind-progressive_workflow/instance-d1zp9h0u v5 with job batch system ID: 4 and cores: 1, disk: 2.0 Gi, and memory: 2.0 Gi
[2023-01-06T22:59:27+0800] [MainThread] [W] [toil.leader] Job failed with exit value 127: 'progressive_workflow' kind-progressive_workflow/instance-d1zp9h0u v5
Exit reason: None
[2023-01-06T22:59:27+0800] [MainThread] [W] [toil.leader] No log file is present, despite job failing: 'progressive_workflow' kind-progressive_workflow/instance-d1zp9h0u v5
[2023-01-06T22:59:27+0800] [MainThread] [W] [toil.job] Due to failure we are reducing the remaining try count of job 'progressive_workflow' kind-progressive_workflow/instance-d1zp9h0u v5 with ID kind-progressive_workflow/instance-d1zp9h0u to 1
[2023-01-06T22:59:28+0800] [MainThread] [I] [toil.leader] Issued job 'progressive_workflow' kind-progressive_workflow/instance-d1zp9h0u v6 with job batch system ID: 5 and cores: 1, disk: 2.0 Gi, and memory: 2.0 Gi
[2023-01-06T22:59:51+0800] [MainThread] [W] [toil.leader] Job failed with exit value 127: 'progressive_workflow' kind-progressive_workflow/instance-d1zp9h0u v6
Exit reason: None
[2023-01-06T22:59:51+0800] [MainThread] [W] [toil.leader] No log file is present, despite job failing: 'progressive_workflow' kind-progressive_workflow/instance-d1zp9h0u v6
[2023-01-06T22:59:51+0800] [MainThread] [W] [toil.job] Due to failure we are reducing the remaining try count of job 'progressive_workflow' kind-progressive_workflow/instance-d1zp9h0u v6 with ID kind-progressive_workflow/instance-d1zp9h0u to 0
[2023-01-06T22:59:52+0800] [MainThread] [W] [toil.leader] Job 'progressive_workflow' kind-progressive_workflow/instance-d1zp9h0u v7 is completely failed
[2023-01-06T22:59:56+0800] [MainThread] [I] [toil.leader] Finished toil run with 1 failed jobs.
[2023-01-06T22:59:56+0800] [MainThread] [I] [toil.leader] Failed jobs at end of the run: 'progressive_workflow' kind-progressive_workflow/instance-d1zp9h0u v7
Traceback (most recent call last):
  File "/home/apps/soft/miniconda3/latest/envs/cactus/bin/cactus", line 8, in <module>
    sys.exit(main())
  File "/home/apps/soft/miniconda3/latest/envs/cactus/lib/python3.7/site-packages/cactus/progressive/cactus_progressive.py", line 396, in main
    hal_id = toil.start(Job.wrapJobFn(progressive_workflow, options, config_node, mc_tree, og_map, input_seq_id_map))
  File "/home/apps/soft/miniconda3/latest/envs/cactus/lib/python3.7/site-packages/toil/common.py", line 951, in start
    return self._runMainLoop(rootJobDescription)
  File "/home/apps/soft/miniconda3/latest/envs/cactus/lib/python3.7/site-packages/toil/common.py", line 1278, in _runMainLoop
    jobCache=self._jobCache).run()
  File "/home/apps/soft/miniconda3/latest/envs/cactus/lib/python3.7/site-packages/toil/leader.py", line 289, in run
    raise FailedJobsException(self.jobStore, failed_jobs, exit_code=self.recommended_fail_exit_code)
toil.leader.FailedJobsException: The job store '/home/zhouhf/js' contains 1 failed jobs: 'progressive_workflow' kind-progressive_workflow/instance-d1zp9h0u v7
127.58user 4.40system 2:38.10elapsed 83%CPU (0avgtext+0avgdata 116696maxresident)k
7312inputs+224outputs (20major+104120minor)pagefaults 0swaps

Then this error appeared, what is the reason?
I observed the comparison results of cactus before and found that the final comparison length he generated was only max 1000bp. How can I make his comparison length longer? What parameters do I need to modify? When running cactus or the haf2maf step ?
I use Command:
./hal2maf /media/name/ext2/cactus/evolverMammals.hal  /media/name/ext1/5/cactus_ancestor_refGap.maf  --maxRefGap 10000000

**Comment by 790634750** [comment]
=========>
	/var/spool/slurm/d/job416385/slurm_script: line 4: _toil_worker: command not found
<=========
[2023-01-07T22:14:36+0800] [MainThread] [W] [toil.job] Due to failure we are reducing the remaining try count of job 'progressive_workflow' kind-progressive_workflow/instance-i2jzvdkc v5 with ID kind-progressive_workflow/instance-i2jzvdkc to 1
[2023-01-07T22:14:36+0800] [MainThread] [I] [toil.leader] Issued job 'progressive_workflow' kind-progressive_workflow/instance-i2jzvdkc v6 with job batch system ID: 5 and cores: 1, disk: 2.0 Gi, and memory: 2.0 Gi
[2023-01-07T22:15:00+0800] [MainThread] [W] [toil.leader] Job failed with exit value 127: 'progressive_workflow' kind-progressive_workflow/instance-i2jzvdkc v6
Exit reason: None
[2023-01-07T22:15:00+0800] [MainThread] [W] [toil.leader] No log file is present, despite job failing: 'progressive_workflow' kind-progressive_workflow/instance-i2jzvdkc v6
[2023-01-07T22:15:00+0800] [MainThread] [W] [toil.leader] The batch system left a non-empty file /home/zhouhf/workDir/toil_b39fe728-5031-4be9-a462-e329a2d8e4f8.5.416386.err.log:
[2023-01-07T22:15:00+0800] [MainThread] [W] [toil.leader] Log from job "kind-progressive_workflow/instance-i2jzvdkc" follows:
=========>
	/var/spool/slurm/d/job416386/slurm_script: line 4: _toil_worker: command not found
<=========
[2023-01-07T22:15:00+0800] [MainThread] [W] [toil.leader] The batch system left an empty file /home/zhouhf/workDir/toil_b39fe728-5031-4be9-a462-e329a2d8e4f8.5.416386.out.log
[2023-01-07T22:15:00+0800] [MainThread] [W] [toil.job] Due to failure we are reducing the remaining try count of job 'progressive_workflow' kind-progressive_workflow/instance-i2jzvdkc v6 with ID kind-progressive_workflow/instance-i2jzvdkc to 0
[2023-01-07T22:15:01+0800] [MainThread] [W] [toil.leader] Job 'progressive_workflow' kind-progressive_workflow/instance-i2jzvdkc v7 is completely failed
[2023-01-07T22:15:06+0800] [MainThread] [I] [toil.leader] Finished toil run with 1 failed jobs.
[2023-01-07T22:15:06+0800] [MainThread] [I] [toil.leader] Failed jobs at end of the run: 'progressive_workflow' kind-progressive_workflow/instance-i2jzvdkc v7
Traceback (most recent call last):
  File "/home/apps/soft/miniconda3/latest/envs/cactus/bin/cactus", line 8, in <module>
    sys.exit(main())
  File "/home/apps/soft/miniconda3/latest/envs/cactus/lib/python3.7/site-packages/cactus/progressive/cactus_progressive.py", line 396, in main
    hal_id = toil.start(Job.wrapJobFn(progressive_workflow, options, config_node, mc_tree, og_map, input_seq_id_map))
  File "/home/apps/soft/miniconda3/latest/envs/cactus/lib/python3.7/site-packages/toil/common.py", line 951, in start
    return self._runMainLoop(rootJobDescription)
  File "/home/apps/soft/miniconda3/latest/envs/cactus/lib/python3.7/site-packages/toil/common.py", line 1278, in _runMainLoop
    jobCache=self._jobCache).run()
  File "/home/apps/soft/miniconda3/latest/envs/cactus/lib/python3.7/site-packages/toil/leader.py", line 289, in run
    raise FailedJobsException(self.jobStore, failed_jobs, exit_code=self.recommended_fail_exit_code)
toil.leader.FailedJobsException: The job store '/home/zhouhf/js' contains 1 failed jobs: 'progressive_workflow' kind-progressive_workflow/instance-i2jzvdkc v7
129.33user 5.91system 2:40.17elapsed 84%CPU (0avgtext+0avgdata 136656maxresident)k
72inputs+264outputs (0major+106991minor)pagefaults 0swaps
/var/spool/slurm/d/job416380/slurm_script: line 12: /home/zhouhf: Is a directory



Hello, I am trying to use cactus on slurm. Cactus is the module load cactus/latest that I loaded using the cluster software library. He suggested that I could not find the toil_worker. I tried to add the parameter export TOIL_SLURM_ARGS="-t 1000:00:00 -q inspur_limit_submit"
But it doesn't solve the problem, what should I do?
