### ISSUE TITLE
Error running cactus via htcondor: ModuleNotFoundError: No module named 'htcondor'

### ISSUE THREAD

**Issue by amizeranschi** [ComparativeGenomicsToolkit/cactus#903]
Hello,

I'm getting the error below when attempting to run Cactus via HTCondor, using the Docker image quay.io/comparative-genomics-toolkit/cactus:v2.3.1. 

Any help with this would be much appreciated.

```
[2023-01-14T10:29:26+0000] [MainThread] [I] [toil.statsAndLogging] Cactus Command: /home/cactus/cactus_env/bin/cactus ./jobStore genomes.txt genomes.hal --logFile cactus.log --realTimeLogging --batchSystem htcondor --consCores 32
[2023-01-14T10:29:26+0000] [MainThread] [I] [toil.statsAndLogging] Cactus Commit: 34aebb0ebe622b9cc6406fb6ae8658428763897d
Traceback (most recent call last):
  File "/home/cactus/cactus_env/bin/cactus", line 8, in <module>
    sys.exit(main())
  File "/home/cactus/cactus_env/lib/python3.10/site-packages/cactus/progressive/cactus_progressive.py", line 361, in main
    with Toil(options) as toil:
  File "/home/cactus/cactus_env/lib/python3.10/site-packages/toil/common.py", line 869, in __enter__
    config.setOptions(self.options)
  File "/home/cactus/cactus_env/lib/python3.10/site-packages/toil/common.py", line 309, in setOptions
    set_batchsystem_options(self.batchSystem, set_option)
  File "/home/cactus/cactus_env/lib/python3.10/site-packages/toil/batchSystems/options.py", line 35, in set_batchsystem_options
    batch_system_type = BATCH_SYSTEM_FACTORY_REGISTRY[batch_system]()
  File "/home/cactus/cactus_env/lib/python3.10/site-packages/toil/batchSystems/registry.py", line 66, in htcondor_batch_system_factory
    from toil.batchSystems.htcondor import HTCondorBatchSystem
  File "/home/cactus/cactus_env/lib/python3.10/site-packages/toil/batchSystems/htcondor.py", line 21, in <module>
    import htcondor
ModuleNotFoundError: No module named 'htcondor'
```

**Comment by amizeranschi** [comment]
Thanks for the suggestion. I gave this a try now, but it didn't work. Here's the output:

```
Unable to find image 'quay.io/comparative-genomics-toolkit/cactus:v2.3.1' locally
v2.3.1: Pulling from comparative-genomics-toolkit/cactus
405f018f9d1d: Pull complete 
98cbc2d5c0e8: Pull complete 
0a7d549adde9: Pull complete 
ad6257b184cd: Pull complete 
2aa756d761cd: Pull complete 
2c68c9e27352: Pull complete 
0ab067ff68e8: Pull complete 
ee1215818a38: Pull complete 
09ab761c1f0a: Pull complete 
9ee0a00b3538: Pull complete 
76dd5e031004: Pull complete 
Digest: sha256:562207b7d607025ec69863e939c5aa1bf0673133ede7cc03bbd8bf855314f193
Status: Downloaded newer image for quay.io/comparative-genomics-toolkit/cactus:v2.3.1
Collecting toil[htcondor]==5.8.0
  Downloading toil-5.8.0-py3-none-any.whl (679 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 679.4/679.4 kB 3.6 MB/s eta 0:00:00
Collecting PyPubSub<5,>=4.0.3
  Downloading Pypubsub-4.0.3-py3-none-any.whl (61 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 61.4/61.4 kB 11.0 MB/s eta 0:00:00
Requirement already satisfied: psutil<6,>=3.0.1 in /home/cactus/cactus_env/lib/python3.10/site-packages (from toil[htcondor]==5.8.0) (5.9.4)
Requirement already satisfied: dill<0.4,>=0.3.2 in /home/cactus/cactus_env/lib/python3.10/site-packages (from toil[htcondor]==5.8.0) (0.3.6)
Requirement already satisfied: pytz>=2012 in /home/cactus/cactus_env/lib/python3.10/site-packages (from toil[htcondor]==5.8.0) (2022.7)
Requirement already satisfied: py-tes<1,>=0.4.2 in /home/cactus/cactus_env/lib/python3.10/site-packages (from toil[htcondor]==5.8.0) (0.4.2)
Requirement already satisfied: enlighten<2,>=1.5.2 in /home/cactus/cactus_env/lib/python3.10/site-packages (from toil[htcondor]==5.8.0) (1.11.1)
Requirement already satisfied: requests<3,>=2 in /home/cactus/cactus_env/lib/python3.10/site-packages (from toil[htcondor]==5.8.0) (2.28.1)
Requirement already satisfied: addict<2.5,>=2.2.1 in /home/cactus/cactus_env/lib/python3.10/site-packages (from toil[htcondor]==5.8.0) (2.4.0)
Requirement already satisfied: typing-extensions in /home/cactus/cactus_env/lib/python3.10/site-packages (from toil[htcondor]==5.8.0) (4.4.0)
Requirement already satisfied: python-dateutil in /home/cactus/cactus_env/lib/python3.10/site-packages (from toil[htcondor]==5.8.0) (2.8.2)
Requirement already satisfied: docker<6,>=3.7.2 in /home/cactus/cactus_env/lib/python3.10/site-packages (from toil[htcondor]==5.8.0) (5.0.3)
ERROR: Ignored the following versions that require a different python version: 3.4.2 Requires-Python ==2.7.*
ERROR: Could not find a version that satisfies the requirement htcondor<9,>=8.6.0; sys_platform != "darwin" and extra == "htcondor" (from toil[htcondor]) (from versions: 9.4.0, 9.5.0, 9.7.0, 9.8.0, 9.8.1, 9.9.0, 9.10.0.post1, 9.11.0, 9.11.1, 9.12.0, 10.0.0, 10.0.1, 10.0.1.post1, 10.1.0, 10.1.1, 10.2.0, 10.2.0.post1)
ERROR: No matching distribution found for htcondor<9,>=8.6.0; sys_platform != "darwin" and extra == "htcondor"
```

**Comment by glennhickey** [comment]
Sorry, the invocation should be just `pip install -U toil[htcondor]`

This works for me with the v2.3.1 cactus docker, but not for v2.4.0.

**Comment by glennhickey** [comment]
Yeah, in light of that [issue](https://github.com/DataBiosphere/toil/issues/4315) I referenced above, I'm suspecting that the htcondor support in Toil hasn't been tested in a while.  I can't really help you with that here, unfortunately, and can only suggest raising an issue with [Toil](https://github.com/DataBiosphere/toil)

**Comment by amizeranschi** [comment]
Alright, I've also opened a separate issue there, specifically for the error above. 

Would be great to see HTCondor support making a return, as it seems to be a good choice of batch scheduler for Cactus, given the large number of small jobs the latter tends to create.
