### ISSUE TITLE
Running cactus on a 32Gb genome

### ISSUE THREAD

**Issue by henrivkgt** [ComparativeGenomicsToolkit/cactus#904]
Hello,

I am trying to align two genomes to each other with cactus, the largest of which is around 32Gb. This is giving some issues. First, I got a crash during the repeatmasking phase, because the size of the chunks of sequence were too large for lastz. I could circumvent this by downloading the cactus_progressive_config.xml, changing the proportionToSample parameter to 0.05, and supplying that config file to my cactus run using the --configFile parameter. However, now after the repeatmasking stage I get another error. Below the log:

Traceback (most recent call last):
  File "/home/cactus/cactus_env/bin/cactus", line 8, in <module>
    sys.exit(main())
  File "/home/cactus/cactus_env/lib/python3.10/site-packages/cactus/progressive/cactus_progressive.py", line 406, in main
    runCactusProgressive(options)
  File "/home/cactus/cactus_env/lib/python3.10/site-packages/cactus/progressive/cactus_progressive.py", line 456, in runCactusProgressive
    halID = toil.start(RunCactusPreprocessorThenProgressiveDown(options, project, memory=configWrapper.getDefaultMemory()))
  File "/home/cactus/cactus_env/lib/python3.10/site-packages/toil/common.py", line 951, in start
    return self._runMainLoop(rootJobDescription)
  File "/home/cactus/cactus_env/lib/python3.10/site-packages/toil/common.py", line 1278, in _runMainLoop
    jobCache=self._jobCache).run()
  File "/home/cactus/cactus_env/lib/python3.10/site-packages/toil/leader.py", line 289, in run
    raise FailedJobsException(self.jobStore, failed_jobs, exit_code=self.recommended_fail_exit_code)
toil.leader.FailedJobsException: The job store '/path/to/jobStore' contains 4 failed jobs: 'RunCactusPreprocessorThenProgressiveDown' kind-RunCactusPreprocessorThenProgressiveDown/instance-1trbq331 v2, 'ProgressiveNext' kind-ProgressiveDown/instance-qfkr8o26 v2, 'CactusBlastPhase' kind-ProgressiveUp/instance-qq8426sd v7, 'RunCactusPreprocessorThenProgressiveDown2' kind-RunCactusPreprocessorThenProgressiveDown2/instance-es6i8h4v v3
Log from job "'CactusBlastPhase' kind-ProgressiveUp/instance-qq8426sd v7" follows:
=========>
        [2023-01-13T09:06:38+0100] [MainThread] [I] [toil.worker] ---TOIL WORKER OUTPUT LOG---
        [2023-01-13T09:06:38+0100] [MainThread] [I] [toil] Running Toil version 5.6.0-c34146a6437e4407a61e946e968bcce67a0ebbca on host --.
        [2023-01-13T09:06:38+0100] [MainThread] [I] [toil.worker] Working on job 'CactusBlastPhase' kind-ProgressiveUp/instance-qq8426sd v5
        [2023-01-13T09:06:39+0100] [MainThread] [I] [toil.worker] Loaded body Job('CactusBlastPhase' kind-ProgressiveUp/instance-qq8426sd v5) from description 'CactusBlastPhase' kind-ProgressiveUp/instance-qq8426sd v5
        [2023-01-13T09:06:39+0100] [MainThread] [I] [toil.fileStores.abstractFileStore] LOG-TO-MASTER: Running blast using the trimming strategy
        [2023-01-13T09:07:02+0100] [MainThread] [W] [toil.fileStores.abstractFileStore] Failed job accessed files:
        [2023-01-13T09:07:02+0100] [MainThread] [W] [toil.fileStores.abstractFileStore] Downloaded file 'files/for-job/kind-MergeChunks2/instance-hu7mg_b6/file-574dab3a286c4532a708666098e053d7/tmpshaqy_77.tmp' to path '/path/to/cactusworkdir/e50ac85c0c40503c87e9e6a9683794c9/a637/3b77/tmpo_q4l7jm.tmp'
        [2023-01-13T09:07:02+0100] [MainThread] [W] [toil.fileStores.abstractFileStore] Downloaded file 'files/for-job/kind-MergeChunks/instance-w7948icq/file-61b513eb638340248428eeb0fffa9dba/tmpi58lwe6e.tmp' to path '/path/to/cactusworkdir/e50ac85c0c40503c87e9e6a9683794c9/a637/3b77/tmpkrmksecl.tmp'
        [2023-01-13T09:07:02+0100] [MainThread] [W] [toil.fileStores.abstractFileStore] LOG-TO-MASTER: Job used more disk than requested. For CWL, consider increasing the outdirMin requirement, otherwise, consider increasing the disk requirement. Job 'CactusBlastPhase' kind-ProgressiveUp/instance-qq8426sd v5 used 2901.42% disk (58.0 GiB [62307598336B] used, 2.0 GiB [2147483648B] requested).

        Traceback (most recent call last):
          File "/home/cactus/cactus_env/lib/python3.10/site-packages/toil/worker.py", line 405, in workerScript
            job._runner(jobGraph=None, jobStore=jobStore, fileStore=fileStore, defer=defer)
          File "/home/cactus/cactus_env/lib/python3.10/site-packages/cactus/shared/common.py", line 932, in _runner
            super(RoundedJob, self)._runner(*args, jobStore=jobStore,
          File "/home/cactus/cactus_env/lib/python3.10/site-packages/toil/job.py", line 2399, in _runner
            returnValues = self._run(jobGraph=None, fileStore=fileStore)
          File "/home/cactus/cactus_env/lib/python3.10/site-packages/toil/job.py", line 2317, in _run
            return self.run(fileStore)
          File "/home/cactus/cactus_env/lib/python3.10/site-packages/cactus/pipeline/cactus_workflow.py", line 279, in run
            trimBlastNode = findRequiredNode(blastNode, "trimBlast")
          File "/home/cactus/cactus_env/lib/python3.10/site-packages/cactus/shared/common.py", line 121, in findRequiredNode
            return nodes[0]
        IndexError: list index out of range
        [2023-01-13T09:07:02+0100] [MainThread] [E] [toil.worker] Exiting the worker because of a failed job on host --
<=========

Any help on how to solve this would be appreciated!

Best,
Henri

**Comment by oneillkza** [comment]
Have you considered increasing the disk requirement?

It can be helpful to run `cactus -h` to get the full set of command line parameters with descriptions. I don't think I've seen those documented anywhere else. I suspect there's a parameter you can set to increase disk requirements.

(It's also possible the 2GB is hardcoded into the workflow somewhere.)

**Comment by glennhickey** [comment]
That error `IndexError: list index out of range` is a problem with your `--configFile`.  Are you sure that you didn't make any other changes (or mix up versions) when creating this file? 

For the 32Gb input genomes size: we've never tried on anything nearly that big.  Good luck, but unfortunately I can't say I'm optimistic about your chances. Not that I don't think it's possible, but I'd be surprised if there isn't a round of tuning and fixing needed for it to work.

**Comment by henrivkgt** [comment]
Thanks for the suggestions, indeed the cactus version we currently have is a bit older. I have downloaded the newest cactus release and config file, and am retrying with that.

**Comment by henrivkgt** [comment]
With the newest release it ran without any further errors. Thanks!
