### ISSUE TITLE
Restart fails

### ISSUE THREAD

**Issue by jdamas13** [ComparativeGenomicsToolkit/cactus#909]
Hi,
My cactus run was killed because I ran out of space on my disk.
After solving that issue, I am trying to use the --restart flag to complete it.
However, it doesn't seem to be working.

I pasted the log below. Is there a way to work around this?

Thank you for your help!

###################################################################################################
root@2db0c9c3c2ce:/data# cactus --restart jobStore/ cactus_20DEC2022.config marsupials_20DEC2022.hal
[2023-01-23T21:28:52+0000] [MainThread] [I] [toil.statsAndLogging] Enabling realtime logging in Toil
[2023-01-23T21:28:52+0000] [MainThread] [I] [toil.statsAndLogging] Cactus Command: /home/cactus/cactus_env/bin/cactus --restart jobStore/ cactus_20DEC2022.config marsupials_20DEC2022.hal
[2023-01-23T21:28:52+0000] [MainThread] [I] [toil.statsAndLogging] Cactus Commit: b699f6bfb4fe88b7876e533dede24e48bbfeb700
[2023-01-23T21:28:52+0000] [MainThread] [W] [toil.common] Requested restart but the workflow has already been completed; allowing exports to rerun.
Traceback (most recent call last):
  File "/home/cactus/cactus_env/lib/python3.10/site-packages/toil/common.py", line 989, in restart
    self._jobStore.load_root_job()
  File "/home/cactus/cactus_env/lib/python3.10/site-packages/toil/jobStores/abstractJobStore.py", line 266, in load_root_job
    raise JobException("The root job '%s' doesn't exist. Either the Toil workflow "
toil.job.JobException: The root job 'kind-progressive_workflow/instance-rz5ckgcx' doesn't exist. Either the Toil workflow is finished or has never been started

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/cactus/cactus_env/bin/cactus", line 8, in <module>
    sys.exit(main())
  File "/home/cactus/cactus_env/lib/python3.10/site-packages/cactus/progressive/cactus_progressive.py", line 365, in main
    hal_id = toil.restart()
  File "/home/cactus/cactus_env/lib/python3.10/site-packages/toil/common.py", line 993, in restart
    return self._jobStore.get_root_job_return_value()
  File "/home/cactus/cactus_env/lib/python3.10/site-packages/toil/jobStores/abstractJobStore.py", line 300, in get_root_job_return_value
    return safeUnpickleFromStream(fH)
  File "/home/cactus/cactus_env/lib/python3.10/site-packages/toil/common.py", line 1687, in safeUnpickleFromStream
    return pickle.loads(string)
  File "/home/cactus/cactus_env/lib/python3.10/site-packages/toil/job.py", line 2911, in __new__
    return cls._resolve(*args)
  File "/home/cactus/cactus_env/lib/python3.10/site-packages/toil/job.py", line 2923, in _resolve
    value = safeUnpickleFromStream(fileHandle)
  File "/home/cactus/cactus_env/lib/python3.10/site-packages/toil/common.py", line 1687, in safeUnpickleFromStream
    return pickle.loads(string)
  File "/home/cactus/cactus_env/lib/python3.10/site-packages/toil/job.py", line 2911, in __new__
    return cls._resolve(*args)
  File "/home/cactus/cactus_env/lib/python3.10/site-packages/toil/job.py", line 2923, in _resolve
    value = safeUnpickleFromStream(fileHandle)
  File "/home/cactus/cactus_env/lib/python3.10/site-packages/toil/common.py", line 1687, in safeUnpickleFromStream
    return pickle.loads(string)
  File "/home/cactus/cactus_env/lib/python3.10/site-packages/toil/job.py", line 3008, in __setstate__
    raise RuntimeError(
RuntimeError: This job was passed promise files/no-job/file-a3084765d34e4412820383ce74e9ef53/stream that wasn't yet resolved when it ran. The job 'export_hal' kind-export_hal/instance-2j6g929e v0 that fulfills this promise hasn't yet finished. This means that there aren't enough constraints to ensure the current job always runs after 'export_hal' kind-export_hal/instance-2j6g929e v0. Consider adding a follow-on indirection between this job and its parent, or adding this job as a child/follow-on of 'export_hal' kind-export_hal/instance-2j6g929e v0.

**Comment by glennhickey** [comment]
Often, these types of errors are bugs: our automated tests don't cover all restart cases for all tools.  But I'm looking at this and can't see anything too wrong with the code. So I suspect that you having run out of disk may have left your job store (which is kept on disk) in a contradictory state and I unfortunately don't have any advice on how to repair it.  

Sorry, I understand this can be frustrating after a really long run, especially as it's failing at the very end of the pipeline.  The [step-by-step](https://github.com/ComparativeGenomicsToolkit/cactus/blob/master/doc/progressive.md#running-step-by-step) interface could be one way to mitigate this in the future.

**Comment by jdamas13** [comment]
Thank you for your quick reply, Glenn!
It is indeed a bit frustrating as this run was going on for ~1 month.
For the future, is there a way to estimate how much space a run will need?
Thanks again!

**Comment by diekhans** [comment]
This seems is a toil bug.  Toil should not delete its previous state before the current state is safely written to disk.  
If you have not deleted your jobstore, we can perhaps get the toil group to look at it. 

Yes, do restart with the step-by-step, I doubt it this is fixable.

**Comment by adamnovak** [comment]
If you do `toil status --printPerJobStats --printChildren --printLogs` on the job store, that should dump all the information about the graph of jobs that is actually still there. Digging around in there for Cactus state files might also be useful; there might be something saved that @glennhickey knows how to resume from.

Toil *isn't* supposed to delete its old job state files before the new ones are written, but it relies on the filesystem being able to e.g. do a rename atomically, and on a closed file *actually* being on disk and not subject to data loss after `close()` returns. @jdamas13 what filesystem have you been using for your job store? NFS? Or something else?

**Comment by adamnovak** [comment]
The output of `tree` on the job store directory might be helpful here.

**Comment by adamnovak** [comment]
There aren't any jobs in this job store at the moment, I don't think. The job descriptions are all stored in files with the name "job", and there aren't any of those in the tree. So I think the workflow decided all the jobs had finished and cleaned them all up (or else managed to lose *all* of them, not just the root job).

The offending promise is at `files/no-job/file-a3084765d34e4412820383ce74e9ef53/stream` and should have been overwritten but apparently wasn't. I don't see any file next to it to evidence a pending update.

There is a file at 
`files/for-job/kind-export_hal/instance-2j6g929e/cleanup/file-9baade0e6ae54c2e8fa9b5ba95fecdca/stream` that would have been written by the `export_hal` job, so if the final HAL file *is* on disk anywhere, I would bet it's there (even though I don't see why it would be in `cleanup/`). @glennhickey Is there a good way to check a HAL file for truncation?

I wish we had the logs from the run itself; they might indicate where exactly in the Toil code we encountered a full disk error, and thus where exactly we didn't handle it properly.

**Comment by glennhickey** [comment]
Thanks Adam.  This is definitely worth trying.  If that file (or any others in the job store) may be a HAL file, then you could be in luck.  The first thing to check is passing it into `halStats`.  If that gives sensible results then you can use `halValidate` to make sure it's not truncated.  

halValidate is slow.  If you file is big you can do something like ` for genome in $(halStats aln.hal --genomes) ; do halValidate aln.hal --genome $genome ; done` to check genome-by-genome.

**Comment by jdamas13** [comment]
That file is only a few bites, so I don't believe it is a hal. 
I looked carefully into all the files in the jobStore and noted that I have .fa, .c2h, and .ref for 4 (out of 28) ancestors in my tree. 
Should I have had all of them there if the job was completed successfully?
