### ISSUE TITLE
Problem in running test case of Cactus with basic format

### ISSUE THREAD

**Issue by ShoumikSaha** [ComparativeGenomicsToolkit/cactus#92]
To run Cactus, I followed the instructions of **README.md**
pip install virtualenv
virtualenv cactus_env
source cactus_env/bin/activate
pip install --upgrade toil[all]
From cactus repo : pip install --upgrade .
Then I installed docker following instructions mentioned in this website - https://www.digitalocean.com/community/tutorials/how-to-install-and-use-docker-on-ubuntu-18-04
After that, running this command- '**cactus jobStore examples/evolverMammals.txt examples/evolverMammals.hal --root mr**' isn't working. It raises **FailedJobException**.
The last part of the error message is -

"INFO:toil.leader:Finished toil run with 27 failed jobs.
INFO:toil.leader:Failed jobs at end of the run: 'BatchPreprocessor' A/8/jobgR5evM 'BatchPreprocessor' 4/r/jobqerPKm 'PreprocessSequence' u/h/jobap6iWs 'CactusPreprocessor2' z/t/jobJBkYWC 'BatchPreprocessor' Y/r/jobUoQ3wG 'PreprocessSequence' C/E/jobLX5AtD 'logAssemblyStats' H/w/jobxOnSZG 'BatchPreprocessor' S/Z/jobaufp62 'PreprocessSequence' o/B/jobh3fCtc 'logAssemblyStats' N/E/jobdJByW4 'BatchPreprocessor' l/S/jobGVW_l2 'CactusPreprocessor2' V/G/jobh6_ndw 'logAssemblyStats' i/J/jobklgyEu 'PreprocessSequence' O/Y/jobpTFeJQ 'BatchPreprocessor' M/C/jobFCfTi2 'BatchPreprocessor' i/M/job323GQ_ 'logAssemblyStats' E/Y/jobLbROgr 'logAssemblyStats' o/2/jobmgugQD 'PreprocessSequence' C/V/jobgn1IeD 'BatchPreprocessor' 4/Y/jobguTZxK 'CactusPreprocessor2' y/u/jobbAUwzN 'CactusPreprocessor2' m/t/job_05MZX 'BatchPreprocessor' l/G/jobWQ6aV7 'CactusPreprocessor2' 3/a/jobmQTq6z 'CactusPreprocessor' U/0/jobKagZQA 'BatchPreprocessor' p/5/jobkPrPwr 'RunCactusPreprocessorThenProgressiveDown' 7/0/jobr1oZxl
Traceback (most recent call last):
  File "/home/shoumik/Thesis/cactus_env/bin/cactus", line 10, in <module>
    sys.exit(main())
  File "/home/shoumik/Thesis/cactus_env/local/lib/python2.7/site-packages/cactus/progressive/cactus_progressive.py", line 520, in main
    halID = toil.start(RunCactusPreprocessorThenProgressiveDown(options, project, memory=configWrapper.getDefaultMemory()))
  File "/home/shoumik/Thesis/cactus_env/local/lib/python2.7/site-packages/toil/common.py", line 781, in start
    return self._runMainLoop(rootJobGraph)
  File "/home/shoumik/Thesis/cactus_env/local/lib/python2.7/site-packages/toil/common.py", line 1054, in _runMainLoop
    jobCache=self._jobCache).run()
  File "/home/shoumik/Thesis/cactus_env/local/lib/python2.7/site-packages/toil/leader.py", line 246, in run
    raise FailedJobsException(self.config.jobStore, self.toilState.totalFailedJobs, self.jobStore)
toil.leader.FailedJobsException"

I've been stuck here for so many hours. I tried so many things, but those didn't work out. It will be really helpful if someone can help me out here.

**Comment by diekhans** [comment]
Please attach the full log to the ticket, as it doens't have
the error message of the root cause problem.

**Comment by ShoumikSaha** [comment]
@diekhans I have attached a log.txt file at the end. Thanks in advance.

**Comment by diekhans** [comment]
It appears that you are not in the docker group and so can't run docker.

**Comment by DailyDreaming** [comment]
@ShoumikSaha See step 2: https://www.digitalocean.com/community/tutorials/how-to-install-and-use-docker-on-ubuntu-18-04

**Comment by adamnovak** [comment]
@ShoumikSaha Yeah, your real problem is here:

```
WARNING:toil.leader:f/P/jobAX9eOB    docker: Got permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Post http://%2Fvar%2Frun%2Fdocker.sock/v1.40/containers/create?name=42bd699a-a347-43ad-8001-408c1111808f: dial unix /var/run/docker.sock: connect: permission denied.
```

You should be able to fix this with:

```
sudo usermod -aG docker ${USER}
```

And then to make super sure that you are logged out and in again and have picked up the right permissions, you can reboot:

```
sudo shutdown -r now
```

Then to test it, you can run:

```
docker version
```

If that doesn't successfully report a version for both the client and the server, you won't be able to run anything using Docker through Toil either. If it does, you can restart your workflow by running the same command you ran before with `--restart` added to it.
