### ISSUE TITLE
cactus-graphmap-join fails during clip_vg

### ISSUE THREAD

**Issue by leleory** [ComparativeGenomicsToolkit/cactus#920]
Hi all,
During a pangenome run of cactus (v2.4.0) cactus-graphmap-join fails on one of the chromosomes during the clip_vg step.
The error is the following:

2023-02-07 10:37:36.714509: Successfully ran: "bash -c set -eo pipefail && vg convert -g -p /exports/cmvm/tmp/cj0p0o4i/sscro11_13.vg.gfaffixed.gfa | vg mod -u -" in 777.7413 seconds
2023-02-07 10:37:36.732632: Running the command: "bash -c set -eo pipefail && clip-vg /exports/cmvm/tmp/cj0p0o4i/sscro11_13.vg.gfaffixed -f -e sscro11 -d _MINIGRAPH_ -L | vg clip -d 1 - -P sscro11 | vg ids -s -"
Got exit code 1 (indicating failure) from job _toil_worker clip_vg file:/exports/cmvm/pangenome/js_graphmap_join kind-clip_vg/instance-mqvpt3ri.
Child 72616 for job 0 succeeded
Ran jobID: 0 with exit value: 1
Job failed with exit value 1: 'clip_vg' kind-clip_vg/instance-mqvpt3ri v7
Exit reason: None
Notifying toil.bus.JobCompletedMessage with message: JobCompletedMessage(job_type='clip_vg', job_id='kind-clip_vg/instance-mqvpt3ri', exit_code=1)
Job 'clip_vg' kind-clip_vg/instance-mqvpt3ri v7 continues to exist (i.e. has more to do)
The job seems to have left a log file, indicating failure: 'clip_vg' kind-clip_vg/instance-mqvpt3ri v8
Log from job "kind-clip_vg/instance-mqvpt3ri" follows:
=========>
        7805317 1       A
        <15792356       <3328991,>22686079      7       GCTGTGG
        <1896639        <1896638,>22749064      1       G
        <15043213       <3552439,<15043212      1       G

        >20900025       <22702520,>124916       1       T
        <22758305       <22702520,>124917       1       T
        [2023-02-07T10:20:30+0000] [MainThread] [I] [toil-rt] 2023-02-07 10:20:30.207671: Successfully ran: "gfaffix /exports/cmvm/tmp/cj0p0o4i/sscro11_13.vg.gfa --output_refined /exports/cmvm/tmp/cj0p0o4i/sscro11_13.vg.gfaffixed.gfa --check_transformation --dont_collapse sscro11*" in 693.6725 seconds
        [2023-02-07T10:20:30+0000] [MainThread] [I] [toil-rt] 2023-02-07 10:20:30.209738: Running the command: "head -1 /exports/cmvm/tmp/cj0p0o4i/sscro11_13.vg.gfa"
        [2023-02-07T10:20:30+0000] [MainThread] [I] [toil-rt] 2023-02-07 10:20:30.243956: Successfully ran: "head -1 /exports/cmvm/tmp/cj0p0o4i/sscro11_13.vg.gfa" in 0.0247 seconds
        [2023-02-07T10:20:30+0000] [MainThread] [I] [toil-rt] 2023-02-07 10:20:30.244473: Running the command: "sed -i /exports/cmvm/tmp/cj0p0o4i/sscro11_13.vg.gfaffixed.gfa -e 1s/.*/H        VN:Z:1.1        RS:Z:sscro11 _MINIGRAPH_/"
        [2023-02-07T10:24:38+0000] [MainThread] [I] [toil-rt] 2023-02-07 10:24:38.952932: Successfully ran: "sed -i /exports/cmvm/tmp/cj0p0o4i/sscro11_13.vg.gfaffixed.gfa -e 1s/.*/H   VN:Z:1.1        RS:Z:sscro11 _MINIGRAPH_/" in 248.7031 seconds
        [2023-02-07T10:24:38+0000] [MainThread] [I] [toil-rt] 2023-02-07 10:24:38.963777: Running the command: "bash -c set -eo pipefail && vg convert -g -p /exports/cmvm/tmp/cj0p0o4i/sscro11_13.vg.gfaffixed.gfa | vg mod -u -"
        [2023-02-07T10:37:36+0000] [MainThread] [I] [toil-rt] 2023-02-07 10:37:36.714509: Successfully ran: "bash -c set -eo pipefail && vg convert -g -p /exports/cmvm/tmp/cj0p0o4i/sscro11_13.vg.gfaffixed.gfa | vg mod -u -" in 777.7413 seconds
        [2023-02-07T10:37:36+0000] [MainThread] [I] [toil-rt] 2023-02-07 10:37:36.732632: Running the command: "bash -c set -eo pipefail && clip-vg /exports/cmvm/tmp/cj0p0o4i/sscro11_13.vg.gfaffixed -f -e sscro11 -d _MINIGRAPH_ -L | vg clip -d 1 - -P sscro11 | vg ids -s -"
        [2023-02-07T10:50:51+0000] [MainThread] [W] [toil.fileStores.abstractFileStore] Failed job accessed files:
        [2023-02-07T10:50:51+0000] [MainThread] [W] [toil.fileStores.abstractFileStore] Downloaded file 'files/no-job/file-7c39c18f679d430a8f0ee110b68e87b1/sscro11_13.vg' to path '/exports/cmvm/tmp/cj0p0o4i/sscro11_13.vg'
        [2023-02-07T10:50:51+0000] [MainThread] [W] [toil.fileStores.abstractFileStore] LOG-TO-MASTER: Job used more disk than requested. For CWL, consider increasing the outdirMin requirement, otherwise, consider increasing the disk requirement. Job 'clip_vg' kind-clip_vg/instance-mqvpt3ri v7 used 225.89% disk (12.5 GiB [13394378752B] used, 5.5 GiB [5929624358B] requested).
        [2023-02-07T10:50:51+0000] [MainThread] [D] [toil.deferred] Running own deferred functions
        [2023-02-07T10:50:51+0000] [MainThread] [D] [toil.deferred] Out of deferred functions!
        [2023-02-07T10:50:51+0000] [MainThread] [D] [toil.deferred] Running orphaned deferred functions
        [2023-02-07T10:50:51+0000] [MainThread] [D] [toil.deferred] Ran orphaned deferred functions from 0 abandoned state files
        Traceback (most recent call last):
          File "/exports/cmvm/src/cactus-bin-v2.4.0/cactus_env_2.4/lib/python3.7/site-packages/toil/worker.py", line 403, in workerScript
            job._runner(jobGraph=None, jobStore=jobStore, fileStore=fileStore, defer=defer)
          File "/exports/cmvm/src/cactus-bin-v2.4.0/cactus_env_2.4/lib/python3.7/site-packages/toil/job.py", line 2727, in _runner
            returnValues = self._run(jobGraph=None, fileStore=fileStore)
          File "/exports/cmvm/src/cactus-bin-v2.4.0/cactus_env_2.4/lib/python3.7/site-packages/toil/job.py", line 2644, in _run
            return self.run(fileStore)
          File "/exports/cmvm/src/cactus-bin-v2.4.0/cactus_env_2.4/lib/python3.7/site-packages/toil/job.py", line 2875, in run
            rValue = userFunction(*((self,) + tuple(self._args)), **self._kwargs)
          File "/exports/cmvm/src/cactus-bin-v2.4.0/cactus_env_2.4/lib/python3.7/site-packages/cactus/refmap/cactus_graphmap_join.py", line 410, in clip_vg
            cactus_call(parameters=cmd, outfile=clipped_path)
          File "/exports/cmvm/src/cactus-bin-v2.4.0/cactus_env_2.4/lib/python3.7/site-packages/cactus/shared/common.py", line 824, in cactus_call
            raise RuntimeError("{}Command {} exited {}: {}".format(sigill_msg, call, process.returncode, out))
        RuntimeError: Command ['bash', '-c', 'set -eo pipefail && clip-vg /exports/cmvm/tmp/cj0p0o4i/sscro11_13.vg.gfaffixed -f -e sscro11 -d _MINIGRAPH_ -L | vg clip -d 1 - -P sscro11 | vg ids -s -'] exited 1: stdout=None, stderr=vg: /home/anovak/workspace/vg/include/bdsg/internal/packed_structs.hpp:590: uint64_t bdsg::PackedVector<Backend>::get(const size_t&) const [with Backend = bdsg::STLBackend; uint64_t = long unsigned int; size_t = long unsigned int]: Assertion `i < filled' failed.
        ERROR: Signal 6 occurred. VG has crashed. Visit https://github.com/vgteam/vg/issues/new/choose to report a bug.
        Stack trace path: /tmp/vg_crash_cH65l2/stacktrace.txt
        Please include the stack trace file in your bug report!
        error[VPKG::load_one]: Correct input type not found in standard input while loading handlegraph::MutablePathMutableHandleGraph
        
        [2023-02-07T10:50:51+0000] [MainThread] [E] [toil.worker] Exiting the worker because of a failed job on host node1d01
<=========

Any help would be appreciated.

Thanks,
Lel

**Comment by glennhickey** [comment]
Hmm, hard to say from the logs.  My guess is that `clip-vg` is running out of memory.  If you're sure that this is not happening and are able to share `sscro11_13.vg` I can try to reproduce here.

**Comment by leleory** [comment]
I allocated 600G of memory and the job never used more than 230G.
I got stuck with this error, if you can look into whether you can reproduce the error that would be great.
Here is the link
https://drive.google.com/file/d/1mfpjQExOrrzr_pYaJCMn-_-bXbz8q536/view?usp=sharing

**Comment by glennhickey** [comment]
Thanks, I am able to reproduce.  The crash is in `vg clip`.  I'd thought it was a result of a failure in the previous `clip-vg` command but it doesn't seem like it.  I'll update back here once it's fixed...
```
vg: /home/anovak/workspace/vg/include/bdsg/internal/packed_structs.hpp:590: uint64_t bdsg::PackedVector<Backend>::get(const size_t&) const [with Backend = bdsg::STLBackend; uint64_t = long unsigned int; size_t = long unsigned int]: Assertion `i < filled' failed.
```
The callstack being
```
#13   Object "/public/groups/cgl/graph-genomes/hickey/work/cactus-bin-v2.4.0/bin/vg", at 0x5e609d, in _start
#12   Object "/public/groups/cgl/graph-genomes/hickey/work/cactus-bin-v2.4.0/bin/vg", at 0x1e83eef, in __libc_start_main
#11   Object "/public/groups/cgl/graph-genomes/hickey/work/cactus-bin-v2.4.0/bin/vg", at 0x5b6a6e, in main
#10   Object "/public/groups/cgl/graph-genomes/hickey/work/cactus-bin-v2.4.0/bin/vg", at 0xcef6cb, in vg::subcommand::Subcommand::operator()(int, char**) const
#9    Object "/public/groups/cgl/graph-genomes/hickey/work/cactus-bin-v2.4.0/bin/vg", at 0xbec794, in main_clip(int, char**)
#8    Object "/public/groups/cgl/graph-genomes/hickey/work/cactus-bin-v2.4.0/bin/vg", at 0x1292390, in vg::clip_low_depth_nodes_and_edges(handlegraph::MutablePathMutableHandleGraph*, long, std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&, long, bool)
#7    Object "/public/groups/cgl/graph-genomes/hickey/work/cactus-bin-v2.4.0/bin/vg", at 0x1291210, in vg::clip_low_depth_nodes_and_edges_generic(handlegraph::MutablePathMutableHandleGraph*, std::function<void (std::function<void (handlegraph::handle_t, vg::Region const*)>)>, std::function<void (std::function<void (std::pair<handlegraph::handle_t, handlegraph::handle_t>, vg::Region const*)>)>, long, std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&, long, bool)
#6    Object "/public/groups/cgl/graph-genomes/hickey/work/cactus-bin-v2.4.0/bin/vg", at 0x809f8c, in bdsg::BasePackedGraph<bdsg::STLBackend>::for_each_path_handle(std::function<bool (handlegraph::path_handle_t const&)> const&) const
#5    Object "/public/groups/cgl/graph-genomes/hickey/work/cactus-bin-v2.4.0/bin/vg", at 0x12901eb, in _ZNSt17_Function_handlerIFbRKN11handlegraph13path_handle_tEEZNS0_20BoolReturningWrapperIZN2vg38clip_low_depth_nodes_and_edges_genericEPNS0_29MutablePathMutableHandleGraphESt8functionIFvS9_IFvNS0_8handle_tEPKNS6_6RegionEEEEES9_IFvS9_IFvSt4pairISA_SA_ESD_EEEElRKSt6vectorINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEESaISU_EElbEUlS1_E2_Lb0EE4wrapERKSZ_EUlDpOT_E_E9_M_invokeERKSt9_Any_dataS3_
#4    Object "/public/groups/cgl/graph-genomes/hickey/work/cactus-bin-v2.4.0/bin/vg", at 0x128cd94, in bdsg::PackedVector<bdsg::STLBackend>::get(unsigned long const&) const [clone .isra.0] [clone .part.0]
#3    Object "/public/groups/cgl/graph-genomes/hickey/work/cactus-bin-v2.4.0/bin/vg", at 0x1e94295, in __assert_fail
#2    Object "/public/groups/cgl/graph-genomes/hickey/work/cactus-bin-v2.4.0/bin/vg", at 0x5b5e67, in __assert_fail_base.cold
#1    Object "/public/groups/cgl/graph-genomes/hickey/work/cactus-bin-v2.4.0/bin/vg", at 0x5b5f97, in abort
#0    Object "/public/groups/cgl/graph-genomes/hickey/work/cactus-bin-v2.4.0/bin/vg", at 0x144d17b, in raise
```

**Comment by glennhickey** [comment]
This should be fixed in the [latest release](https://github.com/ComparativeGenomicsToolkit/cactus/releases)
