### ISSUE TITLE
Issue about RuntimeError with toil.worker

### ISSUE THREAD

**Issue by YanCheer** [ComparativeGenomicsToolkit/cactus#936]
Sorry to raise another issue. When I finally installed the Cactus on our computer cluster, I ran the eaxample file in the cactus_env with the command like  `cactus ./Test/js ./cactus/examples/evolverMammals.txt ./Test/cactus/evolverMammals.hal`. 
Unfortunately, I got another problem as follows:

> <=========
> Log from job 'CactusBarWrapper' kind-CactusBarWrapper/instance-7u1e7f37 follows:
> =========>
>         [2023-02-21T23:18:55+0800] [MainThread] [I] [toil.worker] ---TOIL WORKER OUTPUT LOG---
>         [2023-02-21T23:18:55+0800] [MainThread] [I] [toil] Running Toil version 4.2.0-3aa1da130141039cb357efe36d7df9b9f6ae9b5b on host mu01.
>         [2023-02-21T23:18:55+0800] [MainThread] [I] [cactus.shared.common] Running the command ['cactus_bar', '--logLevel', 'INFO', '--cactusDisk', '<st_kv_database_conf type="kyoto_tycoon">\n\t\t\t<kyoto_tycoon database_dir="fakepath" host="10.0.16.99" port="15662" />\n\t\t</st_kv_database_conf>\n\t', '--maximumLength', '1000000.0', '--spanningTrees', '5', '--gapGamma', '0.0', '--matchGamma', '0.2', '--splitMatrixBiggerThanThis', '3000', '--anchorMatrixBiggerThanThis', '500', '--repeatMaskMatrixBiggerThanThis', '500', '--diagonalExpansion', '20', '--constraintDiagonalTrim', '14', '--minimumDegree', '2', '--minimumIngroupDegree', '1', '--minimumOutgroupDegree', '0', '--pruneOutStubAlignments', '--alignAmbiguityCharacters', '--useProgressiveMerging', '--largeEndSize', '5000', '--minimumSizeToRescue', '100', '--minimumCoverageToRescue', '0.5', '--minimumNumberOfSpecies', '1', '--partialOrderAlignmentBandConstant', '10', '--partialOrderAlignmentBandFraction', '0.01']
>         cactus_bar: unrecognized option '--partialOrderAlignmentBandConstant'
>         cactus_baseAligner [flower-names, ordered by order they should be processed], version 0.2

>   ... ... (Some other information are omitted.)

>         -h --help : Print this help screen
>         Traceback (most recent call last):
>           File "/GS01/software/biosoft/python/anaconda3-2019.07/cactus_env/lib/python3.6/site-packages/toil/worker.py", line 368, in workerScript
>             job._runner(jobGraph=jobGraph, jobStore=jobStore, fileStore=fileStore, defer=defer)
>           File "/GS01/software/biosoft/python/anaconda3-2019.07/cactus_env/lib/python3.6/site-packages/cactus/shared/common.py", line 1407, in _runner
>             super(RoundedJob, self)._runner(jobGraph=jobGraph, jobStore=jobStore, fileStore=fileStore, defer=defer)
>           File "/GS01/software/biosoft/python/anaconda3-2019.07/cactus_env/lib/python3.6/site-packages/toil/job.py", line 1424, in _runner
>             returnValues = self._run(jobGraph, fileStore)
>           File "/GS01/software/biosoft/python/anaconda3-2019.07/cactus_env/lib/python3.6/site-packages/toil/job.py", line 1361, in _run
>             return self.run(fileStore)
>           File "/GS01/software/biosoft/python/anaconda3-2019.07/cactus_env/lib/python3.6/site-packages/cactus/pipeline/cactus_workflow.py", line 921, in run
>             messages = runBarForJob(self, features=self.featuresFn(), fileStore=fileStore)
>           File "/GS01/software/biosoft/python/anaconda3-2019.07/cactus_env/lib/python3.6/site-packages/cactus/pipeline/cactus_workflow.py", line 889, in runBarForJob
>             partialOrderAlignmentBandFraction=self.getOptionalPhaseAttrib("partialOrderAlignmentBandFraction", float))
>           File "/GS01/software/biosoft/python/anaconda3-2019.07/cactus_env/lib/python3.6/site-packages/cactus/shared/common.py", line 566, in runCactusBar
>             job_name=jobName, fileStore=fileStore, features=features)
>           File "/GS01/software/biosoft/python/anaconda3-2019.07/cactus_env/lib/python3.6/site-packages/cactus/shared/common.py", line 1344, in cactus_call
>             raise RuntimeError("Command {} exited {}: {}".format(call, process.returncode, out))
>         RuntimeError: Command ['cactus_bar', '--logLevel', 'INFO', '--cactusDisk', '<st_kv_database_conf type="kyoto_tycoon">\n\t\t\t<kyoto_tycoon database_dir="fakepath" host="10.0.16.99" port="15662" />\n\t\t</st_kv_database_conf>\n\t', '--maximumLength', '1000000.0', '--spanningTrees', '5', '--gapGamma', '0.0', '--matchGamma', '0.2', '--splitMatrixBiggerThanThis', '3000', '--anchorMatrixBiggerThanThis', '500', '--repeatMaskMatrixBiggerThanThis', '500', '--diagonalExpansion', '20', '--constraintDiagonalTrim', '14', '--minimumDegree', '2', '--minimumIngroupDegree', '1', '--minimumOutgroupDegree', '0', '--pruneOutStubAlignments', '--alignAmbiguityCharacters', '--useProgressiveMerging', '--largeEndSize', '5000', '--minimumSizeToRescue', '100', '--minimumCoverageToRescue', '0.5', '--minimumNumberOfSpecies', '1', '--partialOrderAlignmentBandConstant', '10', '--partialOrderAlignmentBandFraction', '0.01'] exited 1: stdout=
>         [2023-02-21T23:18:56+0800] [MainThread] [E] [toil.worker] Exiting the worker because of a failed job on host mu01
> <=========

I have indeed no idea what this kind of **Error** means and even don't know how to solve this. Could any one help me ??

**Comment by glennhickey** [comment]
Your log is referring to `cactus_bar` which hasn't been part of cactus for months (years?).  It's also referring to python3.6 which Cactus won't run on. 

1. Remove all previous installations of cactus, including virtualenvs and source dirs
2. Download the latest release: https://github.com/ComparativeGenomicsToolkit/cactus/releases/download/v2.4.2/cactus-bin-v2.4.2.tar.gz (If you're on a very old computer, use https://github.com/ComparativeGenomicsToolkit/cactus/releases/download/v2.4.2/cactus-bin-legacy-v2.4.2.tar.gz instead)
3. Exactly follow the instructions to install it: https://github.com/ComparativeGenomicsToolkit/cactus/blob/v2.4.2/BIN-INSTALL.md

**Comment by YanCheer** [comment]
> 

Thank you for suggestion. In fact, the administrator of our computer clusters gave me a path in which an old version of cactus had been installed two years ago. I will ask for the installation of the newest Cactus. 

Thanks agin for your kind and timely help!
