### ISSUE TITLE
Error related to accelerators

### ISSUE THREAD

**Issue by d-ayhan** [ComparativeGenomicsToolkit/cactus#937]
Hello, I have been trying to run cactus on a single machine (single core in a slurm server) and I am encountering the below error message. I do not have access to GPU but it tries to access 'nvidia-smi'. How do I disable the accelerators? Thank you.
[version: 2.4.1]

`Traceback (most recent call last):`
`  File "/home/.conda/envs/cac-env/bin/cactus-graphmap", line 33, in <module>
    sys.exit(load_entry_point('Cactus==2.4.1', 'console_scripts', 'cactus-graphmap')())`
`  File "/home/.conda/envs/cac-env/lib/python3.8/site-packages/cactus/refmap/cactus_graphmap.py", line 93, in main
    graph_map(options)`
`  File "/home/.conda/envs/cac-env/lib/python3.8/site-packages/cactus/refmap/cactus_graphmap.py", line 184, in graph_map
    paf_id, gfa_fa_id, gaf_id, unfiltered_paf_id, paf_filter_log, paf_was_filtered = toil.start(Job.wrapJobFn(`
`  File "/home/.conda/envs/cac-env/lib/python3.8/site-packages/toil/common.py", line 1007, in start
    self._batchSystem = self.createBatchSystem(self.config)`
`  File "/home/.conda/envs/cac-env/lib/python3.8/site-packages/toil/common.py", line 1156, in createBatchSystem
    return batch_system(**kwargs)`
`  File "/home/.conda/envs/cac-env/lib/python3.8/site-packages/toil/batchSystems/singleMachine.py", line 149, in __init__
    self.accelerator_identities = get_individual_local_accelerators()`
`  File "/home/.conda/envs/cac-env/lib/python3.8/site-packages/toil/lib/accelerators.py", line 84, in get_individual_local_accelerators`
`    return [{'kind': 'gpu', 'brand': 'nvidia', 'api': 'cuda', 'count': 1} for _ in range(count_nvidia_gpus())]`
`  File "/home/.conda/envs/cac-env/lib/python3.8/site-packages/toil/lib/accelerators.py", line 64, in count_nvidia_gpus
    subprocess.check_output(["nvidia-smi", "-q", "-x"])`
`  File "/home/.conda/envs/cac-env/lib/python3.8/subprocess.py", line 415, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,`
`  File "/home/.conda/envs/cac-env/lib/python3.8/subprocess.py", line 493, in run
    with Popen(*popenargs, **kwargs) as process:`
`  File "/home/.conda/envs/cac-env/lib/python3.8/subprocess.py", line 858, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,`
`  File "/home/.conda/envs/cac-env/lib/python3.8/subprocess.py", line 1704, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)`
`PermissionError: [Errno 13] Permission denied: 'nvidia-smi'`

**Comment by glennhickey** [comment]
We'll fix this. In the meantime, I think your only work-around would to be to make sure that `nvidia-smi` is not in your `PATH` before running cactus.  It will work fine if it can't find `nvidia-smi`, but doesn't seem to handle [your case](https://github.com/DataBiosphere/toil/pull/4391).

**Comment by d-ayhan** [comment]
Hello. Thank you for getting back to me. 
The system administrator informed us that there was no GPU in our environment so we couldn't fix the issue by removing it. I still don't know how `nvidia-smi` was found by cactus. 
However, we found a work-around by tweaking the accelerators.py script so that it always returns false for gpu functions. If anyone has a similar problem until the fix is released, I am attaching the edited parts of the accelerators.py file.

`def count_nvidia_gpus() -> int:`
`    #try:`
`    #    return int(minidom.parseString(`
`    #        subprocess.check_output(["nvidia-smi", "-q", "-x"])`
`    #    ).getElementsByTagName("attached_gpus")[0].firstChild.data)`
`    #except (FileNotFoundError, subprocess.CalledProcessError, IndexError, ValueError):`
`    #    return 0`
`    return 0`

`def get_individual_local_accelerators() -> List[AcceleratorRequirement]:`
`    #return [{'kind': 'gpu', 'brand': 'nvidia', 'api': 'cuda', 'count': 1} for _ in range(count_nvidia_gpus())]`
`    return []`
    
`def get_restrictive_environment_for_local_accelerators(accelerator_numbers : Set[int]) -> Dict[str, str]:`
`    #return {'CUDA_VISIBLE_DEVICES': ','.join(str(i) for i in accelerator_numbers)}`
`    return {'CUDA_VISIBLE_DEVICES':''}`

**Comment by nicolo-tellini** [comment]
Dear @d-ayhan ,

I am facing the same issue.
thank you for your work-around.  
Can you please explain where accelerators.py is located? 

best,

nic

**Comment by d-ayhan** [comment]
Dear @nicolo-tellini,
For me, it is located in `~/.conda/envs/cac-env/lib/python3.8/site-packages/toil/lib/`, but it would be different for you. You might find the file location in the error log.

**Comment by nicolo-tellini** [comment]
Hello,

I am still trying to fix it. 
It seems like I do not have NVIDIA drivers installed on my server (not even a gpu).
I run a greedy "grep -R count_nvidia_gpus" inside my anaconda3 folder (I installed python3.10 from here) but it returned empty.  is nvdia necessary for running cactus?

**Comment by glennhickey** [comment]
You can try installing the latest version of Toil (where this should be patched)
```
pip install -U git+https://github.com/DataBiosphere/toil.git
```
(this can be done instead, or after, the suggested way of installing toil which is `pip install -U -r toil-requirement.txt`)

**Comment by nicolo-tellini** [comment]
Hi @glennhickey ,

thank you. At the end I installed python3.8 from anaconda and the accelerators.py was hidden in the lib directory inside cactus-bin-v.2.4.4.

best 

nic
