### ISSUE TITLE
cactus-preprocess fails for some genomes

### ISSUE THREAD

**Issue by danielle-khost** [ComparativeGenomicsToolkit/cactus#941]
Hi there,
I am attempting to run Cactus as part of a snakemake workflow linked [here](https://github.com/harvardinformatics/GenomeAnnotation-WholeGenomeAlignment) for several bird genomes. For a few of my genomes, `cactus-preprocess` runs successfully but for others it fails, specifically at the 'CheckUniqueHeaders' job. Here is an excerpt from the log files:

```
[2023-02-16T23:13:44+0000] [MainThread] [C] [toil.jobStores.abstractJobStore] Repairing job: kind-PreprocessSequence/instance-pypgkkh1
[2023-02-16T23:13:44+0000] [MainThread] [I] [toil] Running Toil version 5.6.0-c34146a6437e4407a61e946e968bcce67a0ebbca on host holygpu7c26101.rc.fas.harvard.edu.
[2023-02-16T23:13:44+0000] [MainThread] [I] [toil.realtimeLogger] Starting real-time logging.
[2023-02-16T23:13:44+0000] [MainThread] [I] [toil.leader] Issued job 'CheckUniqueHeaders' kind-PreprocessSequence/instance-pypgkkh1 v10 with job batch system ID: 0 and cores: 1, disk: 2.5 Gi, and memory: 2.0 Gi
cwltool is not installed.
[2023-02-16T23:13:45+0000] [MainThread] [I] [toil.worker] Redirecting logging to /tmp/a860ee09dcf35523905cdc1270149755/3bb4/worker_log.txt
[2023-02-16T23:13:45+0000] [Thread-1  ] [E] [toil.batchSystems.singleMachine] Got exit code 1 (indicating failure) from job _toil_worker CheckUniqueHeaders file:/n/holyscratch01/informatics/dkhost/tmp/F_mad-mask kind-PreprocessSequence/instance-pypgkkh1.
[2023-02-16T23:13:45+0000] [MainThread] [W] [toil.leader] Job failed with exit value 1: 'CheckUniqueHeaders' kind-PreprocessSequence/instance-pypgkkh1 v10
Exit reason: None
[2023-02-16T23:13:45+0000] [MainThread] [W] [toil.leader] The job seems to have left a log file, indicating failure: 'CheckUniqueHeaders' kind-PreprocessSequence/instance-pypgkkh1 v11
[2023-02-16T23:13:45+0000] [MainThread] [W] [toil.leader] Log from job "kind-PreprocessSequence/instance-pypgkkh1" follows:
=========>
        [2023-02-16T23:13:45+0000] [MainThread] [I] [toil.worker] ---TOIL WORKER OUTPUT LOG---
        [2023-02-16T23:13:45+0000] [MainThread] [I] [toil] Running Toil version 5.6.0-c34146a6437e4407a61e946e968bcce67a0ebbca on host holygpu7c26101.rc.fas.harvard.edu.
        [2023-02-16T23:13:45+0000] [MainThread] [I] [toil.worker] Working on job 'CheckUniqueHeaders' kind-PreprocessSequence/instance-pypgkkh1 v10
        Traceback (most recent call last):
          File "/home/cactus/cactus_env/lib/python3.8/site-packages/toil/worker.py", line 379, in workerScript
            job = Job.loadJob(jobStore, jobDesc)
          File "/home/cactus/cactus_env/lib/python3.8/site-packages/toil/job.py", line 2283, in loadJob
            with manager as fileHandle:
          File "/usr/lib/python3.8/contextlib.py", line 113, in __enter__
            return next(self.gen)
          File "/home/cactus/cactus_env/lib/python3.8/site-packages/toil/jobStores/fileJobStore.py", line 596, in read_file_stream
            self._check_job_store_file_id(file_id)
          File "/home/cactus/cactus_env/lib/python3.8/site-packages/toil/jobStores/fileJobStore.py", line 779, in _check_job_store_file_id
            raise NoSuchFileException(jobStoreFileID)
        toil.jobStores.abstractJobStore.NoSuchFileException: File 'files/for-job/kind-CheckUniqueHeaders/instance-3lb_h2ho/cleanup/file-58fb37a0331046be89017e6347521c23/stream' does not exist.
        [2023-02-16T23:13:45+0000] [MainThread] [E] [toil.worker] Exiting the worker because of a failed job on host holygpu7c26101.rc.fas.harvard.edu
<=========
```

I took a look at the fasta headers, and for the life of me I can't determine what is different between the genomes that ran and the ones that didn't. For reference, here are some example headers for a genome that passed the CheckUniqueHeaders step:

```
>zmaur.ptg000001l
>zmaur.ptg000002l
>zmaur.ptg000003l
>zmaur.ptg000004l
>zmaur.ptg000005l
```
 
And here are examples from a genome that didn't:

```
>fmada.ptg000001l
>fmada.ptg000002l
>fmada.ptg000003l
>fmada.ptg000004l
>fmada.ptg000005l
```
 
The genome files are not gzipped, as far as I can tell. I am using the singularity image of Cactus (v2.2.0), and was able to successfully run an alignment using the test mammal data, so I am confident that it isn't my install. Any thoughts on what the issue might be? Is it possible my files actually are compressed somehow?

Thank you for your time!
Danielle

**Comment by glennhickey** [comment]
Hi.  I don't think this has anything to do with your fasta files themselves but is rather a cluster / filesystem / toil issue.  What command are you running exactly?
