### ISSUE TITLE
Including `mr` in newick tree

### ISSUE THREAD

**Issue by mbarkdull** [ComparativeGenomicsToolkit/cactus#955]
Good afternoon, 

I am attempting to use cactus to align a series of genomes. My install works perfectly on the included sample data, but when I try it on my data it fails with the error message 

```
INFO:    underlay of /etc/localtime required more than 50 (77) bind mounts
[2023-03-09T18:26:33+0000] [MainThread] [I] [toil.statsAndLogging] Enabling realtime logging in Toil
[2023-03-09T18:26:33+0000] [MainThread] [I] [toil.statsAndLogging] Cactus Command: /home/cactus/cactus_env/bin/cactus /data/jobStore /data/CVAR_scaf_3500.txt /data/CVAR_scaf_3500.hal --root mr --binariesMode local
[2023-03-09T18:26:33+0000] [MainThread] [I] [toil.statsAndLogging] Cactus Commit: 5a8c1fd5fea79e18c7ed1f8cbca7fb5cbac35bb4
Traceback (most recent call last):
  File "/home/cactus/cactus_env/bin/cactus", line 8, in <module>
    sys.exit(main())
  File "/home/cactus/cactus_env/lib/python3.10/site-packages/cactus/progressive/cactus_progressive.py", line 375, in main
    og_map = compute_outgroups(mc_tree, config_wrapper, set(og_candidates), options.root)
  File "/home/cactus/cactus_env/lib/python3.10/site-packages/cactus/progressive/progressive_decomposition.py", line 65, in compute_outgroups
    outgroup.importTree(mc_tree, mc_tree.getNodeId(root_name))
  File "/home/cactus/cactus_env/lib/python3.10/site-packages/cactus/progressive/multiCactusTree.py", line 219, in getNodeId
    return self.nameToId[name]
KeyError: 'mr'
```

After inspecting both my input files and the sample input files, I noticed that the sample input file has a node labelled `mr` in the newick tree (((simHuman_chr6:0.144018,(simMouse_chr6:0.084509,simRat_chr6:0.091589)**mr**:0.271974):0.020593,(simCow_chr6:0.18908,simDog_chr6:0.16303):0.032898);).

My input tree does not have any node labelled `mr`; when I randomly label a node `mr`, the above error resolves and cactus runs successfully. 

I have two questions: 

1. What is the purpose of the `mr` label?
2. Does it matter which internal node is labeled with `mr`? I.e. would it be appropriate for me to randomly label an internal node in my own data?

Thanks so much!

**Comment by glennhickey** [comment]
Please the following from `cactus --help`
```
  --root ROOT           Name of ancestral node (which must appear in NEWICK
                        tree in <seqfile>) to use as a root for the alignment.
                        Any genomes not below this node in the tree may be
                        used as outgroups but will never appear in the output.
                        If no root is specifed then the root of the tree is
                        used.
```
In that example, `mr` is the parent of `m`ouse and `r`at. The example only aligned those two species (via the `--root` option) in order to save time (cactus used to be much slower).  I've removed the `--root mr` from the example in order to avoid further confusion. If you want to align your whole tree, don't use `--root`.  If you want to align a subtree, give it a sensible label and use `--root` to select it.

**Comment by mbarkdull** [comment]
I see! I missed that `--root mr` was included in the command that I ran. 

Thank you for the quick answer and clear explanation!
