### ISSUE TITLE
ob failed with exit value 1: 'progressive_schedule' kind-progressive_schedule/instance-3y3p

### ISSUE THREAD

**Issue by lalibelulalo** [ComparativeGenomicsToolkit/cactus#962]
Hello, when i run my command:
cactus ./js ./examples/evolverPico.txt ./evolverPico.hal

I have tis error:

[2023-03-14T10:59:48-0600] [MainThread] [W] [toil.leader] Job failed with **exit value 1**: 'progressive_schedule' kind-progressive_schedule/instance-3y3p
rwfc v1
Exit reason: None
[2023-03-14T10:59:48-0600] [MainThread] [W] [toil.leader] The job seems to have left a log file, indicating failure: 'progressive_schedule' kind-progr
essive_schedule/instance-3y3prwfc v2
[2023-03-14T10:59:48-0600] [MainThread] [W] [toil.leader] Log from job "kind-progressive_schedule/instance-3y3prwfc" follows:
=========>
	[2023-03-14T10:59:47-0600] [MainThread] [I] [toil.worker] ---TOIL WORKER OUTPUT LOG---
	[2023-03-14T10:59:47-0600] [MainThread] [I] [toil] Running Toil version 5.9.2-54bfe0b146b76ecc6221de384c255e1be89547c6 on host lalibelulalo-HP
-Laptop-14-dq1xxx.
	[2023-03-14T10:59:47-0600] [MainThread] [I] [toil.worker] Working on job 'progressive_schedule' kind-progressive_schedule/instance-3y3prwfc v1
	[2023-03-14T10:59:47-0600] [MainThread] [I] [toil.worker] Loaded body Job('progressive_schedule' kind-progressive_schedule/instance-3y3prwfc v
1) from description 'progressive_schedule' kind-progressive_schedule/instance-3y3prwfc v1
	Traceback (most recent call last):
	  File "/home/lalibelulalo/software/cactus/cactus_env/lib/python3.10/site-packages/toil/worker.py", line 403, in workerScript
	    job._runner(jobGraph=None, jobStore=jobStore, fileStore=fileStore, defer=defer)
	  File "/home/lalibelulalo/software/cactus/cactus_env/lib/python3.10/site-packages/toil/job.py", line 2743, in _runner
	    returnValues = self._run(jobGraph=None, fileStore=fileStore)
	  File "/home/lalibelulalo/software/cactus/cactus_env/lib/python3.10/site-packages/toil/job.py", line 2660, in _run
	    return self.run(fileStore)
	  File "/home/lalibelulalo/software/cactus/cactus_env/lib/python3.10/site-packages/toil/job.py", line 2888, in run
	    rValue = userFunction(*((self,) + tuple(self._args)), **self._kwargs)
	  File "/home/lalibelulalo/software/cactus/cactus_env/lib/python3.10/site-packages/cactus/progressive/cactus_progressive.py", line 147, in pro
gressive_schedule
	    raise RuntimeError("Unable to schedule job dependencies.  Please file a bug report on github")
	RuntimeError: Unable to schedule job dependencies.  Please file a bug report on github
	[2023-03-14T10:59:47-0600] [MainThread] [E] [toil.worker] Exiting the worker because of a failed job on host lalibelulalo-HP-Laptop-14-dq1xxx
<=========
[2023-03-14T10:59:48-0600] [MainThread] [W] [toil.job] Due to failure we are reducing the remaining try count of job 'progressive_schedule' kind-progr
essive_schedule/instance-3y3prwfc v2 with ID kind-progressive_schedule/instance-3y3prwfc to 1
[2023-03-14T10:59:48-0600] [MainThread] [I] [toil.leader] Issued job 'progressive_schedule' kind-progressive_schedule/instance-3y3prwfc v3 with job ba
tch system ID: 102 and disk: 2.0 Gi, memory: 2.0 Gi, cores: 1, accelerators: [], preemptible: False
[2023-03-14T10:59:48-0600] [MainThread] [I] [toil.worker] Redirecting logging to /tmp/e64406ef4328538da949f1e5bf59d31c/5a34/worker_log.txt
[2023-03-14T10:59:48-0600] [Thread-1 (daddy)] [E] [toil.batchSystems.singleMachine] Got exit code 1 (indicating failure) from job _toil_worker progres
sive_schedule file:/home/lalibelulalo/software/cactus/js kind-progressive_schedule/instance-3y3prwfc.
[2023-03-14T10:59:48-0600] [MainThread] [W] [toil.leader] Job failed with exit value 1: 'progressive_schedule' kind-progressive_schedule/instance-3y3p
rwfc v3
Exit reason: None
[2023-03-14T10:59:48-0600] [MainThread] [W] [toil.leader] The job seems to have left a log file, indicating failure: 'progressive_schedule' kind-progr
essive_schedule/instance-3y3prwfc v5
[2023-03-14T10:59:48-0600] [MainThread] [W] [toil.leader] Log from job "kind-progressive_schedule/instance-3y3prwfc" follows:
=========>
	[2023-03-14T10:59:48-0600] [MainThread] [I] [toil.worker] ---TOIL WORKER OUTPUT LOG---
	[2023-03-14T10:59:48-0600] [MainThread] [I] [toil] Running Toil version 5.9.2-54bfe0b146b76ecc6221de384c255e1be89547c6 on host lalibelulalo-HP
-Laptop-14-dq1xxx.
	[2023-03-14T10:59:48-0600] [MainThread] [I] [toil.worker] Working on job 'progressive_schedule' kind-progressive_schedule/instance-3y3prwfc v4
	[2023-03-14T10:59:48-0600] [MainThread] [I] [toil.worker] Loaded body Job('progressive_schedule' kind-progressive_schedule/instance-3y3prwfc v
4) from description 'progressive_schedule' kind-progressive_schedule/instance-3y3prwfc v4
	Traceback (most recent call last):
	  File "/home/lalibelulalo/software/cactus/cactus_env/lib/python3.10/site-packages/toil/worker.py", line 403, in workerScript
	    job._runner(jobGraph=None, jobStore=jobStore, fileStore=fileStore, defer=defer)
	  File "/home/lalibelulalo/software/cactus/cactus_env/lib/python3.10/site-packages/toil/job.py", line 2743, in _runner
	    returnValues = self._run(jobGraph=None, fileStore=fileStore)
	  File "/home/lalibelulalo/software/cactus/cactus_env/lib/python3.10/site-packages/toil/job.py", line 2660, in _run
	    return self.run(fileStore)
	  File "/home/lalibelulalo/software/cactus/cactus_env/lib/python3.10/site-packages/toil/job.py", line 2888, in run
	    rValue = userFunction(*((self,) + tuple(self._args)), **self._kwargs)
	  File "/home/lalibelulalo/software/cactus/cactus_env/lib/python3.10/site-packages/cactus/progressive/cactus_progressive.py", line 147, in pro
gressive_schedule
	    raise RuntimeError("Unable to schedule job dependencies.  Please file a bug report on github")
	RuntimeError: Unable to schedule job dependencies.  Please file a bug report on github
	[2023-03-14T10:59:48-0600] [MainThread] [E] [toil.worker] Exiting the worker because of a failed job on host lalibelulalo-HP-Laptop-14-dq1xxx
<=========
[2023-03-14T10:59:48-0600] [MainThread] [W] [toil.job] Due to failure we are reducing the remaining try count of job 'progressive_schedule' kind-progr
essive_schedule/instance-3y3prwfc v5 with ID kind-progressive_schedule/instance-3y3prwfc to 0
[2023-03-14T10:59:48-0600] [MainThread] [W] [toil.leader] Job 'progressive_schedule' kind-progressive_schedule/instance-3y3prwfc v6 is completely fail
ed
[2023-03-14T10:59:55-0600] [MainThread] [I] [toil.leader] Finished toil run with 3 failed jobs.
[2023-03-14T10:59:55-0600] [MainThread] [I] [toil.leader] Failed jobs at end of the run: 'preprocess_all' kind-preprocess_all/instance-38ch2pii v3 'pr
ogressive_schedule' kind-progressive_schedule/instance-3y3prwfc v6 'sanitize_fasta_headers' kind-progressive_workflow/instance-rfenrmdb v3

Workflow Progress 100%|█████████████████████████████████████████████████████████████████████████████| 103/103 (2 failures) [01:01<00:00, 1.69 jobs/s]
[2023-03-14T10:59:55-0600] [MainThread] [I] [toil.realtimeLogger] Stopping real-time logging server.
[2023-03-14T10:59:56-0600] [MainThread] [I] [toil.realtimeLogger] Joining real-time logging server thread.
Traceback (most recent call last):
  File "/home/lalibelulalo/software/cactus/cactus_env/bin/cactus", line 8, in <module>
    sys.exit(main())
  File "/home/lalibelulalo/software/cactus/cactus_env/lib/python3.10/site-packages/cactus/progressive/cactus_progressive.py", line 400, in main
    hal_id = toil.start(Job.wrapJobFn(progressive_workflow, options, config_node, mc_tree, og_map, input_seq_id_map))
  File "/home/lalibelulalo/software/cactus/cactus_env/lib/python3.10/site-packages/toil/common.py", line 1030, in start
    return self._runMainLoop(rootJobDescription)
  File "/home/lalibelulalo/software/cactus/cactus_env/lib/python3.10/site-packages/toil/common.py", line 1475, in _runMainLoop
    jobCache=self._jobCache).run()
  File "/home/lalibelulalo/software/cactus/cactus_env/lib/python3.10/site-packages/toil/leader.py", line 330, in run
    raise FailedJobsException(self.jobStore, failed_jobs, exit_code=self.recommended_fail_exit_code)
toil.leader.FailedJobsException: The job store '/home/lalibelulalo/software/cactus/js' contains 3 failed jobs: 'preprocess_all' kind-preprocess_all/instance-38ch2pii v3, 'progressive_schedule' kind-progressive_schedule/instance-3y3prwfc v6, 'sanitize_fasta_headers' kind-progressive_workflow/instance-rfenrmdb v3
Log from job "'progressive_schedule' kind-progressive_schedule/instance-3y3prwfc v6" follows:
=========>
	[2023-03-14T10:59:48-0600] [MainThread] [I] [toil.worker] ---TOIL WORKER OUTPUT LOG---
	[2023-03-14T10:59:48-0600] [MainThread] [I] [toil] Running Toil version 5.9.2-54bfe0b146b76ecc6221de384c255e1be89547c6 on host lalibelulalo-HP-Laptop-14-dq1xxx.
	[2023-03-14T10:59:48-0600] [MainThread] [I] [toil.worker] Working on job 'progressive_schedule' kind-progressive_schedule/instance-3y3prwfc v4
	[2023-03-14T10:59:48-0600] [MainThread] [I] [toil.worker] Loaded body Job('progressive_schedule' kind-progressive_schedule/instance-3y3prwfc v4) from description 'progressive_schedule' kind-progressive_schedule/instance-3y3prwfc v4
	Traceback (most recent call last):
	  File "/home/lalibelulalo/software/cactus/cactus_env/lib/python3.10/site-packages/toil/worker.py", line 403, in workerScript
	    job._runner(jobGraph=None, jobStore=jobStore, fileStore=fileStore, defer=defer)
	  File "/home/lalibelulalo/software/cactus/cactus_env/lib/python3.10/site-packages/toil/job.py", line 2743, in _runner
	    returnValues = self._run(jobGraph=None, fileStore=fileStore)
	  File "/home/lalibelulalo/software/cactus/cactus_env/lib/python3.10/site-packages/toil/job.py", line 2660, in _run
	    return self.run(fileStore)
	  File "/home/lalibelulalo/software/cactus/cactus_env/lib/python3.10/site-packages/toil/job.py", line 2888, in run
	    rValue = userFunction(*((self,) + tuple(self._args)), **self._kwargs)
	  File "/home/lalibelulalo/software/cactus/cactus_env/lib/python3.10/site-packages/cactus/progressive/cactus_progressive.py", line 147, in progressive_schedule
	    raise RuntimeError("Unable to schedule job dependencies.  Please file a bug report on github")
	RuntimeError: Unable to schedule job dependencies.  Please file a bug report on github
	[2023-03-14T10:59:48-0600] [MainThread] [E] [toil.worker] Exiting the worker because of a failed job on host lalibelulalo-HP-Laptop-14-dq1xxx
<=========

My data: **evolverPico.txt**
((Synechococcus_sp_A15-28:0.077271,Synechococcus_sp_A15-24:0.0258301)0.571013:0.0143911,(Synechococcus_sp_A18-40:0.00722579,(Synechococcus_sp_RS9915:0.00618045,((Synechococcus_sp_BOUM118:0.00562888,Synechococcus_sp_A18-46_1:0.0072395)0.123122:0.00396224,(Synechococcus_sp_WH_8103:0.00566746,Parasynechococcus_marenigrum_WH_8102:0.0033991)0.172079:0.00695343)0.127:0.0058426)0.174018:0.00726377)0.571013:0.0143911);

Parasynechococcus_marenigrum_WH_8102 https://raw.githubusercontent.com/lalibelulalo/HIP/main/Genomes/Picocyanobacteria/Parasynechococcus_marenigrum_WH_8102.fna
Synechococcus_sp_A15-24 https://raw.githubusercontent.com/lalibelulalo/HIP/main/Genomes/Picocyanobacteria/Synechococcus_sp_A15-24.fna
Synechococcus_sp_RS9915 https://raw.githubusercontent.com/lalibelulalo/HIP/main/Genomes/Picocyanobacteria/Synechococcus_sp_RS9915.fna
Synechococcus_sp_A15-28 https://raw.githubusercontent.com/lalibelulalo/HIP/main/Genomes/Picocyanobacteria/Synechococcus_sp_A15-28.fna
Synechococcus_sp_A18-40 https://raw.githubusercontent.com/lalibelulalo/HIP/main/Genomes/Picocyanobacteria/Synechococcus_sp_A18-40.fna
Synechococcus_sp_BOUM118 https://raw.githubusercontent.com/lalibelulalo/HIP/main/Genomes/Picocyanobacteria/Synechococcus_sp_BOUM118.fna
Synechococcus_sp_A18-46_1 https://raw.githubusercontent.com/lalibelulalo/HIP/main/Genomes/Picocyanobacteria/Synechococcus_sp_A18-46_1.fna
Synechococcus_sp_WH_8103 https://raw.githubusercontent.com/lalibelulalo/HIP/main/Genomes/Picocyanobacteria/Synechococcus_sp_WH_8103.fna

**Comment by glennhickey** [comment]
Very strange!  Thanks for sharing an easy-to-reproduce example.  I'll fix it asap.

**Comment by glennhickey** [comment]
It works fine if you remove the numeric internal node labels from your tree.  Ex:
```
((Synechococcus_sp_A15-28:0.077271,Synechococcus_sp_A15-24:0.0258301):0.0143911,(Synechococcus_sp_A18-40:0.00722579,(Synechococcus_sp_RS9915:0.00618045,((Synechococcus_sp_BOUM118:0.00562888,Synechococcus_sp_A18-46_1:0.0072395):0.00396224,(Synechococcus_sp_WH_8103:0.00566746,Parasynechococcus_marenigrum_WH_8102:0.0033991):0.00695343)0.127:0.0058426):0.00726377):0.0143911);
```
Cactus doesn't expect numbers as internal node names and I guess that's confusing the parser.  I thought we had an error message for this, but I guess not.  So your work-around is to fix the tree to not have numbers in the node names -- and we should fix cactus to give a better error message.
