### ISSUE TITLE
Crash permissions

### ISSUE THREAD

**Issue by fmarletaz** [ComparativeGenomicsToolkit/cactus#97]
Hi - thanks for developing and maintaining cactus. I am running cactus on a single cluster in local mode on 5 mammal genomes. The main alignment phase seems to have gone through but then cactus crashes on an error involving `ktserver` and permission issues. I was able to run the test job successfully. Should I increase somewhere extra memory on disk? I am rather confused by the output error. 
Thanks! 

```
WARNING:toil.leader:V/h/jobcdwNOz    INFO:cactus.shared.common:Running the command ['docker', 'run', '--interactive', '--net=host', '--log-driver=none', '-u', '1792811946:1792800513', '-v', '/tmp/toil-577937c8-d065-41bd-b0f5-155874e9f25d-97c4e647c3303439f5ca0ad55ba4d463/tmphX4BXY/67915332-c081-4d60-bf06-2a4378587b10:/data', '-p', '23466:23466', '--name', '4cf73e65-9bba-4a03-ba85-277d16b07a94', '--rm', 'quay.io/comparative-genomics-toolkit/cactus:42bcd8149eff4d9a8d24bef985ae237f2bffde14', u'ktserver', u'-port', u'23466', u'-ls', u'-tout', u'200000', u'-th', u'64', u'-bgs', u'tXqqnCp/snapshot', u'-bgsc', u'lzo', u'-bgsi', u'1000000', u'-log', u'tmpjkHthG.tmp', u':#opts=ls#bnum=30m#msiz=50g#ktopts=p']
WARNING:toil.leader:V/h/jobcdwNOz    WARNING: Published ports are discarded when using host network mode
WARNING:toil.leader:V/h/jobcdwNOz    Running command catchsegv 'ktserver' '-port' '23466' '-ls' '-tout' '200000' '-th' '64' '-bgs' 'tXqqnCp/snapshot' '-bgsc' 'lzo' '-bgsi' '1000000' '-log' 'tmpjkHthG.tmp' ':#opts=ls#bnum=30m#msiz=50g#ktopts=p'
WARNING:toil.leader:V/h/jobcdwNOz    CRITICAL:toil.lib.bioio:Error starting ktserver.
WARNING:toil.leader:V/h/jobcdwNOz    INFO:cactus.shared.common:Work dirs: set([])
WARNING:toil.leader:V/h/jobcdwNOz    INFO:cactus.shared.common:Docker work dir: .
WARNING:toil.leader:V/h/jobcdwNOz    INFO:cactus.shared.common:Running the command ['docker', 'run', '--interactive', '--net=host', '--log-driver=none', '-u', '1792811946:1792800513', '-v', '/tmp/toil-577937c8-d065-41bd-b0f5-155874e9f25d-97c4e647c3303439f5ca0ad55ba4d463/tmphX4BXY/67915332-c081-4d60-bf06-2a4378587b10:/data', '--name', 'a398af2b-2f23-4d5c-8e00-3c1e7137fbcb', '--rm', 'quay.io/comparative-genomics-toolkit/cactus:42bcd8149eff4d9a8d24bef985ae237f2bffde14', 'ktremotemgr', 'remove', '-port', '23466', '-host', '129.67.27.196', 'TERMINATE']
WARNING:toil.leader:V/h/jobcdwNOz    CRITICAL:toil.lib.bioio:Error starting ktserver.
WARNING:toil.leader:V/h/jobcdwNOz    WARNING:toil.fileStore:LOG-TO-MASTER: Job used more disk than requested. Consider modifying the user script to avoid the chance of failure due to incorrectly requested resources. Job i/5/job8doRaN/g/tmpRY44mD-_serialiseJob-stream used 958.78% (19.2 GB [20589568000B] used, 2.0 GB [2147483648B] requested) at the end of its run.
WARNING:toil.leader:V/h/jobcdwNOz    Traceback (most recent call last):
WARNING:toil.leader:V/h/jobcdwNOz      File "/home/zoo/zool1048/installs/cactus/cactus_env/local/lib/python2.7/site-packages/toil/worker.py", line 331, in workerScript
WARNING:toil.leader:V/h/jobcdwNOz        job._runner(jobGraph=jobGraph, jobStore=jobStore, fileStore=fileStore)
WARNING:toil.leader:V/h/jobcdwNOz      File "/home/zoo/zool1048/installs/cactus/cactus_env/local/lib/python2.7/site-packages/toil/job.py", line 1378, in _runner
WARNING:toil.leader:V/h/jobcdwNOz        returnValues = self._run(jobGraph, fileStore)
WARNING:toil.leader:V/h/jobcdwNOz      File "/home/zoo/zool1048/installs/cactus/cactus_env/local/lib/python2.7/site-packages/toil/job.py", line 1726, in _run
WARNING:toil.leader:V/h/jobcdwNOz        returnValues = self.run(fileStore)
WARNING:toil.leader:V/h/jobcdwNOz      File "/home/zoo/zool1048/installs/cactus/cactus_env/local/lib/python2.7/site-packages/toil/job.py", line 1676, in run
WARNING:toil.leader:V/h/jobcdwNOz        startCredentials = service.start(self)
WARNING:toil.leader:V/h/jobcdwNOz      File "/home/zoo/zool1048/installs/cactus/cactus_env/local/lib/python2.7/site-packages/cactus/pipeline/ktserverToil.py", line 33, in start
WARNING:toil.leader:V/h/jobcdwNOz        snapshotExportID=snapshotExportID)
WARNING:toil.leader:V/h/jobcdwNOz      File "/home/zoo/zool1048/installs/cactus/cactus_env/local/lib/python2.7/site-packages/cactus/pipeline/ktserverControl.py", line 62, in runKtserver
WARNING:toil.leader:V/h/jobcdwNOz        raise RuntimeError("Unable to launch ktserver in time. Log: %s" % log)
WARNING:toil.leader:V/h/jobcdwNOz    RuntimeError: Unable to launch ktserver in time. Log: 2019-09-29T02:38:51.238998Z: [SYSTEM]: ================ [START]: pid=10
WARNING:toil.leader:V/h/jobcdwNOz    2019-09-29T02:38:51.239240Z: [SYSTEM]: opening a database: path=:#opts=ls#bnum=30m#msiz=50g#ktopts=p
WARNING:toil.leader:V/h/jobcdwNOz    2019-09-29T02:38:51.246761Z: [SYSTEM]: applying a snapshot file: db=0 ts=1568315983182000000 count=70361674 size=42819207870
WARNING:toil.leader:V/h/jobcdwNOz    2019-09-29T02:44:05.578362Z: [ERROR]: [DB]: :: 9: system error: too short region
WARNING:toil.leader:V/h/jobcdwNOz    2019-09-29T02:44:05.593173Z: [ERROR]: could not apply a snapshot: system error: too short region
WARNING:toil.leader:V/h/jobcdwNOz    2019-09-29T02:44:05.605901Z: [SYSTEM]: starting the server: expr=:23466
WARNING:toil.leader:V/h/jobcdwNOz    2019-09-29T02:44:05.610102Z: [SYSTEM]: server socket opened: expr=:23466 timeout=200000.0
WARNING:toil.leader:V/h/jobcdwNOz    2019-09-29T02:44:05.610167Z: [SYSTEM]: listening server socket started: fd=4
WARNING:toil.leader:V/h/jobcdwNOz
WARNING:toil.leader:V/h/jobcdwNOz    ERROR:toil.worker:Exiting the worker because of a failed job on host zoo-susumu
WARNING:toil.leader:V/h/jobcdwNOz    WARNING:toil.jobGraph:Due to failure we are reducing the remaining retry count of job 'KtServerService' V/h/jobcdwNOz with ID V/h/jobcdwNOz to 5

Traceback (most recent call last):
  File "/home/zoo/zool1048/installs/cactus/cactus_env/bin/cactus", line 10, in <module>
    sys.exit(main())
  File "/home/zoo/zool1048/installs/cactus/cactus_env/local/lib/python2.7/site-packages/cactus/progressive/cactus_progressive.py", line 477, in main
    halID = toil.restart()
  File "/home/zoo/zool1048/installs/cactus/cactus_env/local/lib/python2.7/site-packages/toil/common.py", line 815, in restart
    self._shutdownBatchSystem()
  File "/home/zoo/zool1048/installs/cactus/cactus_env/local/lib/python2.7/site-packages/toil/common.py", line 1064, in _shutdownBatchSystem
    self._batchSystem.shutdown()
  File "/home/zoo/zool1048/installs/cactus/cactus_env/local/lib/python2.7/site-packages/toil/batchSystems/singleMachine.py", line 281, in shutdown
    BatchSystemSupport.workerCleanup(self.workerCleanupInfo)
  File "/home/zoo/zool1048/installs/cactus/cactus_env/local/lib/python2.7/site-packages/toil/batchSystems/abstractBatchSystem.py", line 323, in workerCleanup
    shutil.rmtree(workflowDir)
  File "/usr/lib/python2.7/shutil.py", line 247, in rmtree
    rmtree(fullname, ignore_errors, onerror)
  File "/usr/lib/python2.7/shutil.py", line 247, in rmtree
    rmtree(fullname, ignore_errors, onerror)
  File "/usr/lib/python2.7/shutil.py", line 256, in rmtree
    onerror(os.rmdir, path, sys.exc_info())
  File "/usr/lib/python2.7/shutil.py", line 254, in rmtree
    os.rmdir(path)
OSError: [Errno 13] Permission denied: '/tmp/toil-577937c8-d065-41bd-b0f5-155874e9f25d-97c4e647c3303439f5ca0ad55ba4d463/tmprJyIsM/d3f8a6f2-2509-47fa-ae8d-718166af740a'
```

**Comment by diekhans** [comment]
Due to the fact that every HCA cluster is different, it is not
really possible for us to debug system-specific problems.  One
solution is to run in AWS to have a consistent environment.

This appears like ktserver can't start because it can load save
state.

The error at the end maybe a hint, as the pipeline should not be creating a directory
it can't then delete:

  > OSError: [Errno 13] Permission denied: '/tmp/toil-577937c8-d065-41bd-b0f5-155874e9f25d-97c4e647c3303439f5ca0ad55ba4d463/tmprJyIsM/d3f8a6f2-2509-47fa-ae8d-718166af740a'
