### ISSUE TITLE
error

### ISSUE THREAD

**Issue by 790634750** [ComparativeGenomicsToolkit/cactus#974]

**Comment by 790634750** [comment]
> _No description provided._

	[2023-03-23T07:24:21+0800] [MainThread] [I] [toil-rt] cactus_consolidated(N0): Stripped any unique IDs, 0 seconds have elapsed
	[2023-03-23T07:24:21+0800] [MainThread] [I] [toil-rt] cactus_consolidated(N0): cactus_consolidated: cactus_consolidated.c:351: main: Assertion `!flower_builtBlocks(flower)' failed.
	[2023-03-23T07:24:21+0800] [MainThread] [W] [toil.fileStores.abstractFileStore] Failed job accessed files:
	[2023-03-23T07:24:21+0800] [MainThread] [W] [toil.fileStores.abstractFileStore] Downloaded file 'files/for-job/kind-cactus_cons/instance-63_qaxc4/file-1d0245cf7075446fb255047cbdb23377/N1.ref' to path '/home/zhouhf/js_5maize/06b9aa47452f5c6fb0a5631f511d16d7/b704/76f8/tmp88pexhvn/N1.fa'
	[2023-03-23T07:24:21+0800] [MainThread] [W] [toil.fileStores.abstractFileStore] Downloaded file 'files/for-job/kind-cactus_cons/instance-mfjhg5ff/file-7e7647ec49134381a0316db8618b7f85/N2.ref' to path '/home/zhouhf/js_5maize/06b9aa47452f5c6fb0a5631f511d16d7/b704/76f8/tmp88pexhvn/N2.fa'
	[2023-03-23T07:24:21+0800] [MainThread] [W] [toil.fileStores.abstractFileStore] Downloaded file 'files/for-job/kind-trim_unaligned_sequences/instance-aadoe1ce/file-02c66e4bad03471f88f5a1432d06f959/tmpruxuw4gw.tmp' to path '/home/zhouhf/js_5maize/06b9aa47452f5c6fb0a5631f511d16d7/b704/76f8/tmp88pexhvn/N0.paf'
	Traceback (most recent call last):
	  File "/home/zhouhf/testCactus/cactus-bin-v2.4.0/cactus_env/lib/python3.10/site-packages/toil/worker.py", line 403, in workerScript
	    job._runner(jobGraph=None, jobStore=jobStore, fileStore=fileStore, defer=defer)
	  File "/home/zhouhf/testCactus/cactus-bin-v2.4.0/cactus_env/lib/python3.10/site-packages/toil/job.py", line 2727, in _runner
	    returnValues = self._run(jobGraph=None, fileStore=fileStore)
	  File "/home/zhouhf/testCactus/cactus-bin-v2.4.0/cactus_env/lib/python3.10/site-packages/toil/job.py", line 2644, in _run
	    return self.run(fileStore)
	  File "/home/zhouhf/testCactus/cactus-bin-v2.4.0/cactus_env/lib/python3.10/site-packages/toil/job.py", line 2875, in run
	    rValue = userFunction(*((self,) + tuple(self._args)), **self._kwargs)
	  File "/home/zhouhf/testCactus/cactus-bin-v2.4.0/cactus_env/lib/python3.10/site-packages/cactus/pipeline/cactus_workflow.py", line 93, in cactus_cons
	    messages = cactus_call(check_output=True, returnStdErr=True,
	  File "/home/zhouhf/testCactus/cactus-bin-v2.4.0/cactus_env/lib/python3.10/site-packages/cactus/shared/common.py", line 826, in cactus_call
	    raise RuntimeError("{}Command {} signaled {}: {}".format(sigill_msg, call, signal.Signals(-process.returncode).name, out))
	RuntimeError: Command ['cactus_consolidated', '--sequences', 'N1 /home/zhouhf/js_5maize/06b9aa47452f5c6fb0a5631f511d16d7/b704/76f8/tmp88pexhvn/N1.fa N2 /home/zhouhf/js_5maize/06b9aa47452f5c6fb0a5631f511d16d7/b704/76f8/tmp88pexhvn/N2.fa', '--speciesTree', '(N1:0.0135912,N2:0.0135912)N0;', '--logLevel', 'INFO', '--alignments', '/home/zhouhf/js_5maize/06b9aa47452f5c6fb0a5631f511d16d7/b704/76f8/tmp88pexhvn/N0_primary.paf', '--params', '/home/zhouhf/js_5maize/06b9aa47452f5c6fb0a5631f511d16d7/b704/76f8/tmp88pexhvn/N0.config.xml', '--outputFile', '/home/zhouhf/js_5maize/06b9aa47452f5c6fb0a5631f511d16d7/b704/76f8/tmp88pexhvn/N0.c2h', '--outputHalFastaFile', '/home/zhouhf/js_5maize/06b9aa47452f5c6fb0a5631f511d16d7/b704/76f8/tmp88pexhvn/N0.c2h.fa', '--outputReferenceFile', '/home/zhouhf/js_5maize/06b9aa47452f5c6fb0a5631f511d16d7/b704/76f8/tmp88pexhvn/N0.ref', '--outgroupEvents', '', '--referenceEvent', 'N0', '--threads', '45', '--secondaryAlignments', '/home/zhouhf/js_5maize/06b9aa47452f5c6fb0a5631f511d16d7/b704/76f8/tmp88pexhvn/N0_secondary.paf'] signaled SIGABRT: stdout=, stderr=None
	[2023-03-23T07:24:21+0800] [MainThread] [E] [toil.worker] Exiting the worker because of a failed job on host gpu01
<=========
