### ISSUE TITLE
The following error was encountered ,when run "--restart"

### ISSUE THREAD

**Issue by Sh1ne111** [ComparativeGenomicsToolkit/cactus#987]
Hi,  
    when I run 'cactus jobstore 24sp_config.txt 24sp_cactus.hal --maxCores 24 --stats --restart', I got the following error , How to solve it ？

 Best,

Chen

[2023-04-13T09:16:30+0800] [MainThread] [I] [toil.statsAndLogging] Enabling realtime logging in Toil
[2023-04-13T09:16:30+0800] [MainThread] [I] [toil.statsAndLogging] Cactus Command: /share/home/aa/anaconda3/envs/py39/bin/cactus jobstore 24sp_config.txt 24sp_cactus.hal --maxCores 24 --stats --restart
[2023-04-13T09:16:30+0800] [MainThread] [I] [toil.statsAndLogging] Cactus Commit: 985e2c515fe08b41b593b2aaf44f9b8adb32dfcb
[2023-04-13T10:28:59+0800] [MainThread] [I] [toil] Running Toil version 5.9.2-54bfe0b146b76ecc6221de384c255e1be89547c6 on host c023.
[2023-04-13T10:28:59+0800] [MainThread] [I] [toil.realtimeLogger] Starting real-time logging.
[2023-04-13T10:29:00+0800] [MainThread] [I] [toil.realtimeLogger] Stopping real-time logging server.
[2023-04-13T10:29:00+0800] [MainThread] [I] [toil.realtimeLogger] Joining real-time logging server thread.
Traceback (most recent call last):
  File "/share/home/aa/anaconda3/envs/py39/bin/cactus", line 8, in <module>
    sys.exit(main())
  File "/share/home/aa/anaconda3/envs/py39/lib/python3.9/site-packages/cactus/progressive/cactus_progressive.py", line 364, in main
    hal_id = toil.restart()
  File "/share/home/aa/anaconda3/envs/py39/lib/python3.9/site-packages/toil/common.py", line 1067, in restart
    return self._runMainLoop(rootJobDescription)
  File "/share/home/aa/anaconda3/envs/py39/lib/python3.9/site-packages/toil/common.py", line 1470, in _runMainLoop
    return Leader(config=self.config,
  File "/share/home/aa/anaconda3/envs/py39/lib/python3.9/site-packages/toil/leader.py", line 162, in __init__
    self._message_subscription = self.toilState.bus.connect_output_file(self.config.write_messages)
  File "/share/home/aa/anaconda3/envs/py39/lib/python3.9/site-packages/toil/bus.py", line 390, in connect_output_file
    stream = open(file_path, 'wb')
FileNotFoundError: [Errno 2] No such file or directory: '/var/tmp/pbs.647674.mn01/tmplq4l4l76'

**Comment by glennhickey** [comment]
Is `cactus jobstore 24sp_config.txt 24sp_cactus.hal --maxCores 24 --stats --restart` your exact command? (ie you're not running on a cluster or anything?)

If so, this seems it may be a Toil bug.  I'll raise an issue there.  In the meantime you can try to run
```
mkdir -p /var/tmp/pbs.647674.mn01
```
then retry your command.  

In the future, you may also be able to avoid this by using `--workDir` to specify a location that will not get cleaned between runs.  

I've never seen this before, but I almost never use `--stats` so I wonder if the issue may be related to that...

**Comment by adamnovak** [comment]
It looks like Toil is trying to re-use the same path it used when it first ran as the place to log its messages about what is happening in the workflow, for things like `toil stats`.

I have a fix for this in a PR, but the workaround would be to manually pass the `--writeMessages` option and a path to a file that Toil can use instead, in a directory that exists, when doing the restart. So something like:

```
cactus jobstore 24sp_config.txt 24sp_cactus.hal --maxCores 24 --stats --restart --writeMessages ./messages.txt
```
