### ISSUE TITLE
run example in the cactus failed

### ISSUE THREAD

**Issue by yuzhenpeng** [ComparativeGenomicsToolkit/cactus#99]
Dear Sir, 
Thanks for your wonderful software. Firstly, I installed the Cactus used bioconda. It succeed.
But, when I run the examlpe the software provide. It failed. I got the follow warnings. I don't konw the reason. Could you please give me some help.

`$cactus jobStore examples/evolverMammals.txt examples/evolverMammals.hal --restart
Root logger is at level 'INFO', 'toil' logger at level 'INFO'.
Root logger is at level 'INFO', 'toil' logger at level 'INFO'.
Requested restart but the workflow has already been completed; allowing exports to rerun.
Traceback (most recent call last):
  File "/Bio/home/Yanglab/Yuzhenpeng/miniconda2/bin/cactus", line 11, in <module>
    load_entry_point('progressiveCactus==1.0', 'console_scripts', 'cactus')()
  File "/Bio/home/Yanglab/Yuzhenpeng/miniconda2/lib/python2.7/site-packages/cactus/progressive/cactus_progressive.py", line 477, in main
    halID = toil.restart()
  File "/Bio/home/Yanglab/Yuzhenpeng/miniconda2/lib/python2.7/site-packages/toil/common.py", line 763, in restart
    return self._jobStore.getRootJobReturnValue()
  File "/Bio/home/Yanglab/Yuzhenpeng/miniconda2/lib/python2.7/site-packages/toil/jobStores/abstractJobStore.py", line 218, in getRootJobReturnValue
    with self.readSharedFileStream('rootJobReturnValue') as fH:
  File "/Bio/home/Yanglab/Yuzhenpeng/miniconda2/lib/python2.7/contextlib.py", line 17, in __enter__
    return self.gen.next()
  File "/Bio/home/Yanglab/Yuzhenpeng/miniconda2/lib/python2.7/site-packages/toil/jobStores/fileJobStore.py", line 378, in readSharedFileStream
    raise NoSuchFileException(sharedFileName,sharedFileName)
toil.jobStores.abstractJobStore.NoSuchFileException: File 'rootJobReturnValue' (rootJobReturnValue) does not exist`

**Comment by zhangyuxin1012** [comment]
I also have a similar problem. Have you solved your problem?

**Comment by jiaanqiang** [comment]
I running on a cluster, and also have a similar problem.

**Comment by zhangyuxin1012** [comment]
You can add my wechat according to my email phone number, I don't know if I can help you solve this problem!

-----原始邮件-----
发件人:jiaanqiang ***@***.***>
发送时间:2023-07-08 15:43:33 (星期六)
收件人: ComparativeGenomicsToolkit/cactus ***@***.***>
抄送: 1012 ***@***.***>, Comment ***@***.***>
主题: Re: [ComparativeGenomicsToolkit/cactus] run example in the cactus failed (#99)



I running on a cluster, and also have a similar problem.

—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you commented.Message ID: ***@***.***>


--

复旦大学江湾新校区生命科学学院G411
上海市杨浦区淞沪路2005号, 200438
School of Life Sciences, Fudan University
Room G411, 2005#Songhu Road, Shanghai 200438, China
Mobile: 186-4207-0433

**Comment by MauriAndresMU1313** [comment]
Did you solve this issue?
